### ISSUE TITLE
unknown blob

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/dotnet-docker#100]
I've tried to download docker images using 'docker pull Microsoft/dotnet:nanoserver-core' etc.
the results is everything downloads except :- 

cf62dbf6d334: Downloading
...
unknown blob

?

**Comment by MichaelSimons** [comment]
@grahamehorner, what host OS are you using?  Windows images can only be pulled/run on a [Windows container compatible host](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/system_requirements).

**Comment by MichaelSimons** [comment]
Closing because of no response - please reactive with host OS information if this is still an issue.
