### ISSUE TITLE
Dotnet:sdk2.1 has removed support for Windows Server 2016 OS Build 14393.2848

### ISSUE THREAD

**Issue by timothies** [dotnet/dotnet-docker#1004]
## Steps to reproduce the issue
PS>  docker pull  microsoft/dotnet:2.1-sdk

## Expected behavior
Download docker image microsoft/dotnet:2.1-sdk 
(alternatively referred to as docker pull mcr.microsoft.com/dotnet/core/sdk:2.1)

## Actual behavior
"a Windows version 10.0.16299-based image is incompatible with a 10.0.14393 host"

## Additional information (e.g. issue happens only occasionally)
I am running Windows Server 2016 OS Build 14393.2848.   

This was previously working 
PS> docker images  microsoft/dotnet:2.1-sdk

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
microsoft/dotnet    2.1-sdk             d2a8dd640867        2 months ago        2.62GB

## Output of `docker version`

```
Client:
 Version:      18.03.1-ee-2
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   ebbcd7e
 Built:        Tue Jul 10 21:32:32 2018
 OS/Arch:      windows/amd64
 Experimental: false

Server:
 Engine:
  Version:      18.03.1-ee-2
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.10.2
  Git commit:   ebbcd7e
  Built:        Tue Jul 10 21:49:06 2018
  OS/Arch:      windows/amd64
  Experimental: false

```

## Output of `docker info`

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 975
Server Version: 18.03.1-ee-2
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2848.amd64fre.rs1_release.190305-1856)
Operating System: Windows Server 2016 Datacenter Version 1607 (OS Build 14393.2848)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14GiB
Name: dev-timothies09
ID: NRL4:NNV5:YF6U:B3BZ:SS2C:QTFF:TEV3:NUF2:WVOE:KLXS:IJDK:5VFW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
See our [.NET Core Container Images now Published to Microsoft Container Registry](https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/) blog post which also discusses the Nano Server 2016 images reaching the end of the support cycle.  If still needed you can use them via the OS versioned tags such as `2.1-sdk-nanoserver-sac2016` (unsupported).

**Comment by timothies** [comment]
Ok, understood.  
Thanks alot Michael that gets me out of a bind in the short term.  In the medium term we'll upgrade to 2019.   
Issue resolved
