### ISSUE TITLE
“Access is denied” occurs for command “net start server” service on a Windows Docker dotnet image

### ISSUE THREAD

**Issue by danzaharescu** [dotnet/dotnet-docker#1010]
## Steps to reproduce the issue
1. Start a container with command prompt like this:
 "docker run -it --rm  mcr.microsoft.com/dotnet/core/runtime cmd"
2. After container starts and terminal is directed to container internal system run
  "net start server".

## Expected behavior
Server should start. 

## Actual behavior
An error message occurs:
"System error 5 has occurred.
Access is denied."

## Additional information (e.g. issue happens only occasionally)
The same problem occurs if I try to start the service from CMD in Dockerfile.

## Output of `docker version`
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

## Output of `docker info`

Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 159
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.590)
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.92GiB
Name: sro-2272
ID: FYLK:MM3E:3PHK:UJGV:5KGY:3VN5:R4O7:RWP5:7ZK2:LJFS:I5G4:47OL
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 40
 System Time: 2019-03-25T13:45:17.6038123+02:00
 EventsListeners: 1
HTTP Proxy: 10.40.8.26:3128
HTTPS Proxy: 10.40.8.26:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by MichaelSimons** [comment]
By default user within Nano Server images is the ContainerUser.  This looks to be the source of the permission error.  You can change to run as the ContainerAdministrator via `docker run -it --rm --user ContainerAdministrator mcr.microsoft.com/dotnet/core/runtime`.  This still doesn't fully solve your issue however.

This is an issue that is specific to the nanoserver OS base image that the .NET Core images are based on.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).

**Comment by danzaharescu** [comment]
Hello Michael,

Thanks for the quick reply,
My with the new parameter, I have a new error message:
"System error 1075 has occurred.
The dependency service does not exist or has been marked for deletion."
Seems a step forward...
I have posted the problem to the windows container forum as yo recommended.
If my understanding is correct, you are building the dotnet image over the nanoserver image, and the problem is already in the base container that you use as input.

Regards,
Dan

**Comment by MichaelSimons** [comment]
Hi Dan, yes you are correct in that the problem is in the base image.  You can reproduce the problem directly by using the `mcr.microsoft.com/windows/nanoserver:1803` image directly.
