### ISSUE TITLE
Please ship NuGet.org packages in NuGetFallbackFolder

### ISSUE THREAD

**Issue by ctaggart** [dotnet/dotnet-docker#1021]
Continuing from https://github.com/NuGet/Home/issues/7921, can you please ship nuget packages that match NuGet.org in NuGetFallbackFolder. Right now, they don't match and that is probably causing the nuget lock validation to break. Even if this is not the cause, the packages in that folder should match.

# `microsoft.csharp\4.0.1\.nupkg.metadata` contentHash
NuGetFallbackFolder
```
17h8b5mXa87XYKrrVqdgZ38JefSUqLChUQpXgSnpzsM0nDOhE40FTeNWOJ/YmySGV6tG6T8+hjz6vxbknHJr6A==
```

NuGet.org
```
eEgt/ktABPBa/1xBex3M6b7C4dYsGQ0HWuwe9Xhflgu4cvn4a5VvFSLj5vyTKkp+hKrVpTRdqTXDTAxsIL1Reg==
```

There are more examples, such as Microsoft.NETCore.Platforms.1.1.0.

**Comment by MichaelSimons** [comment]
@ctaggart - can you indicate which sdk images you are looking at?

**Comment by ctaggart** [comment]
It was in the linked issue, but may not have been clear. I am using the latest stable `2.2.105` locally on Windows and this docker image:

```
PS C:\Users\taggac\github\froto> docker run -it --rm -v ${PWD}:/src -w /src mcr.microsoft.com/dotnet/core/sdk:2.2.105 bash
root@d544929d370f:/src# cat /usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.csharp/4.0.1/.nupkg.metadata
{
  "version": 1,
  "contentHash": "17h8b5mXa87XYKrrVqdgZ38JefSUqLChUQpXgSnpzsM0nDOhE40FTeNWOJ/YmySGV6tG6T8+hjz6vxbknHJr6A=="
}root@d544929d370f:/src# cat global.json
{
  "sdk": {
    "version": "2.2.105"
  }
```

**Comment by ctaggart** [comment]
Windows shows:
```
PS C:\Users\taggac\github\froto> cat ~/.nuget\packages\microsoft.csharp\4.0.1\.nupkg.metadata
{
  "version": 1,
  "contentHash": "eEgt/ktABPBa/1xBex3M6b7C4dYsGQ0HWuwe9Xhflgu4cvn4a5VvFSLj5vyTKkp+hKrVpTRdqTXDTAxsIL1Reg=="
}
PS C:\Users\taggac\github\froto> cat "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.csharp\4.0.1\.nupkg.metadata"
{
  "version": 1,
  "contentHash": "17h8b5mXa87XYKrrVqdgZ38JefSUqLChUQpXgSnpzsM0nDOhE40FTeNWOJ/YmySGV6tG6T8+hjz6vxbknHJr6A=="
}
PS C:\Users\taggac\github\froto> dotnet --version
2.2.105
```

**Comment by MichaelSimons** [comment]
Closed per the conversation in https://github.com/NuGet/Home/issues/7921.

**Comment by ctaggart** [comment]
@MichaelSimons I don't know why you closed this. Shipping packages in the NuGetFallbackFolder is causes the pain that is conversation https://github.com/NuGet/Home/issues/7921

**Comment by MichaelSimons** [comment]
Isn't the underlying issue covered by https://github.com/NuGet/Home/issues/7414 (which isn't getting fixed)?  The NuGetFallbackFolder is part of the sdk and not specific to the .NET Docker images.  If you have push back on the underlying issue not being fixed in 2.* please direct it towards NuGet.

**Comment by ctaggart** [comment]
Thanks for the link. Makes sense now. Will do.
