### ISSUE TITLE
Pulling microsoft/dotnet:2.1-aspnetcore-runtime fails on WS2016 version 1607

### ISSUE THREAD

**Issue by Adamon17** [dotnet/dotnet-docker#1022]
## Steps to reproduce the issue
1.Docker pull microsoft/dotnet:2.1-aspnetcore-runtime

## Expected behavior
Docker will download and extract relevant layers for the image

## Actual behavior
Docker downloads all layers and fails to extract layer 407ada6e90de

## Additional information (e.g. issue happens only occasionally)
This layer appears to be an indicator of the image for OS version 1709. Looking at documentation it appears only version 1803 and 1709 are currently supported, thus 1607 is outdated. 1607 is a LTSC whereas 1709 and 1803 are SAC. Surely the LTSC should have more long term support? Especially seeing as 1709 will shortly no longer be supported by microsoft.

## Output of `docker version`

```
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: true
```

## Output of `docker info`

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel n
 Log: awslogs etwlogs fluentd
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (1
Operating System: Windows Ser
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8GiB
Name: LL-VM-DEV-07
ID: RCBH:5DIK:GI43:MD2C:K63X:
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docke
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
Windows Server 2016 is LTSC but the .NET Core Docker images are based on Nano Server. The Nano Server 2016 release was a [SAC](https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview#semi-annual-channel) release hence it is EOL.  We recently published a [blog](https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/) that discusses this and what your options are.

**Comment by Adamon17** [comment]
@MichaelSimons  Thanks for that. So we don't really have any options other than to use a non supported version of the dotnet core image unless we move to using the SAC windows versions? This seems like it could effect a lot of people given that we're only 3 years into the LTSC lifecycle and I'm not sure how secure it is to use a non supported image in a production environment.

**Comment by Adamon17** [comment]
That is to say, is there a version of a .NET Core docker image that isn't based on Nano Server or is this the only option?

**Comment by MichaelSimons** [comment]
@Adamon17, unfortunately there is not a supported NanoServer container image that is compatible with Windows Server 2016.  If you need to stay on Windows Server 2016, you can take one of our [Dockerfiles ](https://github.com/dotnet/dotnet-docker/blob/master/2.1/aspnet/nanoserver-1809/amd64/Dockerfile) and modify it to be based on the larger Windows Server Core image.  You would have to updated accordingly as new .NET Core patches are released.

```
# escape=`

# Installer image
FROM mcr.microsoft.com/windows/servercore:1809 AS installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install ASP.NET Core Runtime
ENV ASPNETCORE_VERSION 2.1.9

RUN Invoke-WebRequest -OutFile aspnetcore.zip https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/$Env:ASPNETCORE_VERSION/aspnetcore-runtime-$Env:ASPNETCORE_VERSION-win-x64.zip; `
    $aspnetcore_sha512 = '9885c15250529c92a95f951ad498e6448b229fef0ba40fdf8e3aab3a24d25611851d245c698783b0901d46b227e175fa30f17f6021560e34ccce3014912f3bbf'; `
    if ((Get-FileHash aspnetcore.zip -Algorithm sha512).Hash -ne $aspnetcore_sha512) { `
        Write-Host 'CHECKSUM VERIFICATION FAILED!'; `
        exit 1; `
    }; `
    `
    Expand-Archive aspnetcore.zip -DestinationPath dotnet; `
    Remove-Item -Force aspnetcore.zip


# Runtime image
FROM mcr.microsoft.com/windows/servercore:1809

# Note: Runtime image's SHELL is the CMD shell (different than the installer image).

COPY --from=installer ["/dotnet", "/Program Files/dotnet"]

# In order to set system PATH, ContainerAdministrator must be used
USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\Program Files\dotnet"
USER ContainerUser

# Configure web servers to bind to port 80 when present
ENV ASPNETCORE_URLS=http://+:80 `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true `
    # Deprecated, use `DOTNET_RUNNING_IN_CONTAINER` instead - https://github.com/dotnet/dotnet-docker/issues/677
    DOTNET_RUNNING_IN_CONTAINERS=true
```

**Comment by brianbolger** [comment]
I'm currently trying to get the same thing working for the 2.2 runtime using the following tweaks:

```
# Installer image
#FROM mcr.microsoft.com/windows/servercore:1809 AS installer
FROM mcr.microsoft.com/windows/servercore:ltsc2016 AS installer

...

# Runtime image
#FROM mcr.microsoft.com/windows/nanoserver:1809
FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.2551
```

I found the above nanoserver tag via:
https://hub.docker.com/_/microsoft-windows-nanoserver

but buried under this link:
https://mcr.microsoft.com/v2/windows/nanoserver/tags/list

**Comment by MichaelSimons** [comment]
Just to be clear, `mcr.microsoft.com/windows/nanoserver:10.0.14393.2551` is a sac2016 based image which is not being supported by windows.  If you want a Windows supported configuration, use `mcr.microsoft.com/windows/servercore:ltsc2016` in both `FROM` instructions.

**Comment by brianbolger** [comment]
Thanks for the timely advice @MichaelSimons 😉 
The nanoserver images did not work well, took down the whole test server after a few minutes.

Specifying `mcr.microsoft.com/windows/servercore:ltsc2016` in both `FROM` instructions worked. 

We also had to remove the `USER `commands from the below snippet as I don't think those accounts exist for the base image:
```
# In order to set system PATH, ContainerAdministrator must be used
#USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\Program Files\dotnet"
#USER ContainerUser
```

**Comment by MichaelSimons** [comment]
As noted earlier the 1607 images are EOL.  Closing

**Comment by Cloudmersive** [comment]
The way you guys just happily break and EOL these images is super annoying

**Comment by Cloudmersive** [comment]
It is not acceptable that 1607 is already EOL.  This is horrible.
