### ISSUE TITLE
SSL connection could not be established for nuget restore in windows nano image

### ISSUE THREAD

**Issue by rammaram06** [dotnet/dotnet-docker#1031]
## Steps to reproduce the issue
1. Use windows .netcore sdk image (I'm using version 2.1.301)
2. Copy nuget.config which points to private artifactory nuget respository with ssl enabled
3. Run dotnet restore

## Expected behavior
Pull nuget dependencies from private nuget repository

## Actual behavior
```
 The remote certificate is invalid according to the validation procedure.
[16:35:31][Step 2/4] C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error : Failed to retrieve information about 'Microsoft.AspNetCore' from remote source 'https://testartifactory.xxx.org/artifactory/api/nuget/nuget/FindPackagesById()?id='Microsoft.AspNetCore'&semVerLevel=2.0.0'. [C:\app\Core.Services.sln]
[16:35:31][Step 2/4] C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [C:\app\Core.Services.sln]
[16:35:31][Step 2/4] C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error :   The remote certificate is invalid according to the validation procedure. [C:\app\Core.Services.sln]
[16:35:31][Step 2/4]   Retrying 'FindPackagesByIdAsyncCore' for source 'https://testartifactory.xxx.org/artifactory/api/nuget/nuget/FindPackagesById()?id='DocumentFormat.OpenXml'&semVerLevel=2.0.0'.
[16:35:31][Step 2/4]   The SSL connection could not be established, see inner exception.
[16:35:31][Step 2/4]     The remote certificate is invalid according to the validation procedure.
```

## Additional information (e.g. issue happens only occasionally)
Since this is nano Image, I couldnt figure out our internal CA cert to the image.

## Output of `docker version`

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        1ac774dfdd
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       1ac774dfdd
  Built:            02/10/2019 04:13:25
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
PS C:\Windows\system32> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.316)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8GiB
Name: docker-server
ID: KTPV:IWPI:5IMR:LCAK:6XVT:AC3A:FZAB:MQ4U:JWIZ:U5O3:R56Y:NPDB
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by rammaram06** [comment]
I  couldn't figure out how to add our internal CA cert to nano image, is there a way to add it?

**Comment by MichaelSimons** [comment]
@rammaram06 - Take a look at the [Developing ASP.NET Core Applications with Docker over HTTPS](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https-development.md) which illustrates how certs are being used with a running app utilizing a volume mount.

```
-v %USERPROFILE%\.aspnet\https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https
```

Closing as this issue isn't directly related to the microsoft/dotnet image content.  You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.

**Comment by embix** [comment]
@rammaram06 do you have a solution yet?

**Comment by jstafford5380** [comment]
@MichaelSimons  So, I think you're referring to using a certificate with a running app but the problem seems to be with docker being able to communicate with a nuget server during the build process. Are we talking about the same thing?

**Comment by MichaelSimons** [comment]
@jstafford5380 - for build scenarios, there are a couple options I have seen used in practice.  This [blog article](https://pythonspeed.com/articles/docker-build-secrets/) (which I have no association with) explains one.  Going forward however, Docker has been adding better support for build secrets  which is described [here](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information).  This support has not yet shipped in production.

**Comment by jstafford5380** [comment]
I don't think that's the issue either. I think this might be more relevant if it were about talking to a private nuget server where you would have to pass an api key or something to gain access, but again this is a nothing-special scenario where it's literally just trying to restore packages from nuget.org and it can't establish a connection because the SSL connection is failing.

**Comment by akumaramar** [comment]
I am facing similar issue. 
`1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/KubernetisTest/KubernetisTest.csproj]
1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : The SSL connection could not be established, see inner exception. [/src/KubernetisTest/KubernetisTest.csproj]
1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : The remote certificate is invalid according to the validation procedure. [/src/KubernetisTest/KubernetisTest.csproj]`

Any help would be appreciated.

**Comment by schuettecarsten** [comment]
We have the same problem with our local NuGet server. The server uses a self-signed certificate and we cannot restore NuGet packages from this server when running "dotnet restore" in a docker container.

**Comment by clintstedman** [comment]
We have started experiencing this over the last couple of weeks. Builds that were working are now failing. I am not sure what has changed to cause this. And we have followed all suggested solutions for private nuget feeds.

Has anyone found a solution?

**Comment by jinaldesailive** [comment]
Importing certificate into my docker image worked for me.
used Import-Certificate

**Comment by bsulliva** [comment]
@jinaldesailive, do you have a working example? I have this issue and haven't been able to fix it so far

**Comment by Vitegor** [comment]
@bsulliva, you should check, how you exported certificate that you want to install. I had error if i used exporting in DER encoding, but it worked with certificate in base64 encoding:
![image](https://user-images.githubusercontent.com/8503289/146327660-9465f927-aa4a-43da-bfb3-bc99c0d7bda0.png)

**Comment by rchanda26** [comment]
> I am facing similar issue. `1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/KubernetisTest/KubernetisTest.csproj] 1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : The SSL connection could not be established, see inner exception. [/src/KubernetisTest/KubernetisTest.csproj] 1>/usr/share/dotnet/sdk/2.2.401/NuGet.targets(123,5): error : The remote certificate is invalid according to the validation procedure. [/src/KubernetisTest/KubernetisTest.csproj]`
> 
> Any help would be appreciated.

@kumaramar do you find any solution to this problem ? I'm facing similar issue and unable to resolve.
