### ISSUE TITLE
Packages built with mcr.microsoft.com/dotnet/core/aspnet:2.2 on 2019 doesn't work on 1803

### ISSUE THREAD

**Issue by dozer75** [dotnet/dotnet-docker#1044]
Disclaimer: This may be some misunderstanding from my part, but I think that this is quite limiting. If there are some workaround, please advice how to do it.

I have a Dockerfile that uses mcr.microsoft.com/dotnet/core/aspnet:2.2 as base image. I build my package using a Windows Server 2019 (1809), but when I try to use this package on a 1803 server I get the following error  `a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host.`

Is this really how it should be? That we can't build docker packages on a newer OS than the hosts that should run them?

## Steps to reproduce the issue
1. Create a docker file with the following minimalistic information:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS publish

ENTRYPOINT ["cmd", "/c", "dir"]

```

2. Build this on a 1809 server and publish it
3. On a 1803 server try to run this docker package

## Expected behavior
Since mcr.microsoft.com/dotnet/core/aspnet:2.2 which is according to the [Announcement](https://github.com/dotnet/dotnet-docker/issues/1041) a multi arch solution and the 1803 is listed as supported it should work.

## Actual behavior
Getting the error `a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host.`

## Output of `docker version`

```
**Docker build server:**
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.3
 Git commit:        33a45cd0a2
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       33a45cd0a2
  Built:            11/07/2018 00:24:12
  OS/Arch:          windows/amd64
  Experimental:     true

**Docker host:**
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.3
 Git commit:        33a45cd0a2
 Built:             unknown-buildtime
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       33a45cd0a2
  Built:            11/07/2018 00:24:12
  OS/Arch:          windows/amd64
  Experimental:     true
```

## Output of `docker info`

```
**Docker build server:**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.09.0
Storage Driver: lcow (linux) windowsfilter (windows)
 LCOW:
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.107)
OSType: windows
Architecture: x86_64
CPUs: 16
Total Memory: 31.9GiB
Name: XXXXXXXXX
ID: YBVS:MMRW:AQTG:XAH4:JFOI:65RK:RNUG:NISC:42LQ:YUOS:ORCM:V2D4
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2019-04-10T11:18:01.0410093+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Docker host:**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.09.0
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Datacenter Version 1803 (OS Build 17134.407)
OSType: windows
Architecture: x86_64
CPUs: 40
Total Memory: 255.9GiB
Name: XXXXXXXXX
ID: GF5H:X3WD:CVPZ:I52R:F4VY:5QZL:KNJV:EWB3:P5HO:XERG:T3ZK:43PM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 24
 System Time: 2019-04-10T11:18:51.4803087+02:00
 EventsListeners: 0
Username: XXXXXX
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
Please see the [Windows Container Version Compatibility](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) documentation.

> Older containers will run the same on newer hosts with Hyper-V isolation, and the same (older) kernel version will still be used. However, if you want to run a container based on a newer Windows build - it can only run on the newer host build.

In your particular scenario where you are building on 1809 and want to run on 1803, you should build using an 1803 base image.  This will produce an 1803 based image that can then be run on a 1803 host.

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-nanoserver-1803
```

**Comment by dozer75** [comment]
Yes, I know I can fixate the Docker build definition to a specific version, but then I need a package for all versions for both LTS and SAC of Windows and Linux and thus the multi-arch is rendered useless. 
With the amount of releases of Windows Server (at least 2 LTS (may be more with extended support) and 3 SAC at any given time) it will be quite an amount of packages to handle and to do this we will need one docker build file for each windows version that is currently supported and in addition a Linux based build environment for building Linux packages. 
Not to mention that not all nano server packages supports all .NET Core versions (e.g. 2016 docker package doesn't support ASP.NET Core 2.1.9 but 2.1.8) so we'll have to build different target platforms to solve this or fixate the ASP.NET Core version to the lowest (which again both Omnisharp/Visual Studio Code and dotnet publish command complains about). 

So, where is actually the benefit using these multi-arch tag? Is it needed at all or does it just add confusion and issues around versions?

In my little world I thought that a Docker package that was based on a multi-arch package was really multi-arch that could be started on all supported host operating systems that the base package supports, but it isn't. 
Using them only makes it possible to avoid build issues when building on different OS environments, which in turn fixates the base version to the one that is related to the OS, it doesn't help hosting at all, it will only create issues when you realize that a package is built on a newer OS than the hosting environment is running. 
I now think that the only really usable scenario for multi arch packages are end of line packages (for example a micro service that can be deployed standalone) and not for base packages.

It may be that I am to inexperienced with Docker, but here are some additional thoughts I have.

Using nano server relies to much on the host system (even with Hyper-V isolation) to be efficient and cost effective (just see the matrix provided in the link, to support all versions you'll constantly need to have the latest OS on the host). The more I look at nano server I feel that it doesn't fit into a containerized environment because of this. For example: If a Docker package micro service will require new version of ASP.NET Core which is only available on a nano server version that is newer than the hosting server environment (e.g. having a LTSC hosting environment, but the nano server package with the new ASP.NET Core is a SAC version) it will require the hosting environment to upgrade their environment to a non-LTSC server version with the cost that has (and in addition LTSC/SAC doesn't have any upgrade paths so fresh installs are required).

This issue with nano server is it really the same using Linux instead of nano server? If I build a Docker package based on one Linux package, it can't be executed on older versions of Linux or other distributions of Linux? 

I am happy I found these issues now before we're going to create a new micro service architecture and can prepare both the development environment and the hosting environment better.

**Comment by richlander** [comment]
You can keep using the multi-arch tag, but store it as an arg that can be overridden with `docker build` in the case you are building Windows images. You can have what you want, with a little extra effort on your part.

Example of the pattern: https://github.com/dotnet/dotnet-docker/blob/master/3.0/runtime/alpine3.9/amd64/Dockerfile#L1-L2

You made need to use HyperV isolation to run a (older) Nano Server version that doesn't match your host.

**Comment by dozer75** [comment]
Yes, I've seen that it has been used here in different packages, and it's probably the solution to go for, but then multi-arch is quite limited in it's use and it may be better to have good build scripts that handles the different architectures instead in a consistent way.

I'll close this issue now, not quite needed to be open since it isn't any good way to solve it in the distributed docker images anyway and more of an opinion.
