### ISSUE TITLE
Build pipeline perf: skip Docker cleanup on hosted agents

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1050]
The build pipelines can spend a few dozen seconds on each job running the Docker cleanup steps.  But this isn't necessary when running on a hosted agent since the hosted agent always starts in a "clean" state and is re-imaged after being used so it can be left in a dirty state.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/docker-tools #256](https://github.com/dotnet/docker-tools/issues/256) via [**ZenHub**](https://www.zenhub.com/)
