### ISSUE TITLE
Build pipeline perf: copy images optimization

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1051]
There should be some investigation on ways to optimize the "copy image" jobs.

* Reduce the number of build agents that handle copying so that a single agent copies more tags than it does currently.  This will free up additional agents which would be nice.
* Investigate whether it'd be beneficial to run all of the `az acr import` calls in a single call to `docker run`.  Currently, we execute `docker run ... az acr import` for each tag.  There's some extra overhead with doing that.

**Comment by MichaelSimons** [comment]
Closing as this is covered by https://github.com/dotnet/docker-tools/issues/165.
