### ISSUE TITLE
Host ASP.NET Core Images on Docker with .cer certificate

### ISSUE THREAD

**Issue by eglerjl** [dotnet/dotnet-docker#1053]
Is it possible to host ASP.NET Core Images with Docker over HTTPS using a .cer file instead of a .pfx? The existing documentation does not indicate that you cannot, but only provides examples for the .pfx configuration.

I am seeing the below configuration in the Kestrel documentation. Are there settings for these similar to `ASPNETCORE_Kestrel__Default__Subject` that we can use to configure this certificate selection mechanism for Docker?
```
"Default": {
  "Subject": "<subject; required>",
  "Store": "<cert store; defaults to My>",
  "Location": "<location; defaults to CurrentUser>",
  "AllowInvalid": "<true or false; defaults to false>"
}
```

## Output of docker version
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       142dfcedca
  Built:            02/28/2019 06:31:15
  OS/Arch:          windows/amd64
  Experimental:     false

```

**Comment by richlander** [comment]
PTAL @javiercn

**Comment by blowdart** [comment]
CER files don't have the private keys, so no, you can't as we need the private keys to bind.

**Comment by javiercn** [comment]
.NET only supports pfx AFAIK, so the key and the certificate can't be in separate files if that's what you were asking.

**Comment by MichaelSimons** [comment]
Closing as the question was answered in the discussion.

> Is it possible to host ASP.NET Core Images with Docker over HTTPS using a .cer file instead of a .pfx?

No
