### ISSUE TITLE
Refactor run-tests.ps1 to not install .NET Core

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#1077]
It should not be necessary to install .NET Core within run-tests.ps1.  This logic is not robust and will fail the builds periodically.  Investigate other options such as building/running the tests within a container to eliminate this flakiness.

**Comment by mthalman** [comment]
This is specific to Windows which requires that tests be run directly on the build agent instead of a container.

**Comment by mthalman** [comment]
This wouldn't be necessary once https://github.com/dotnet/docker-tools/issues/159 is fixed. This hasn't been causing any functional issues so I think it makes sense to not do any work here and just wait for the Windows nested container support.
