### ISSUE TITLE
create sdk Docker tag

### ISSUE THREAD

**Issue by bbodenmiller** [dotnet/dotnet-docker#108]
Appears there is `core`, `core-deps`, and `onbuild` Docker tags pointing at the latest release... why no `sdk` tag?

**Comment by MichaelSimons** [comment]
@bbodenmiller, the `latest` tag points to the latest `sdk` image.  What is your scenario in which having an `sdk` tag would be beneficial over using the `latest` tag?

**Comment by bbodenmiller** [comment]
It's just not clear that `latest` points at the latest version of the sdk. Nor is it clear about the other tags actually.

**Comment by MichaelSimons** [comment]
@bbodenmiller, point noted that `latest` is not clear as to what is references.  Can you expand on what you mean by "Nor is it clear about the other tags actually."  I am not following what you mean by this.  -Thanks

**Comment by bbodenmiller** [comment]
I guess it is outlined at https://github.com/dotnet/dotnet-docker#supported-tags which tags are what. I just found it confusing that `latest` wasn't quickly called out as the image you most likely want to use and that the "Image variants" section makes no mention of the tags that follow the latest version. e.g. perhaps the "`microsoft/dotnet:<version>-sdk`" header could be updated to "`microsoft/dotnet:<version>-sdk`, `latest`" and so on.
