### ISSUE TITLE
docker build doesn't cache the package restore

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/dotnet-docker#109]
## Steps to reproduce the issue
1. `git clone git@github.com:IdentityServer/IdentityServer4.Samples.git`
2. `cd IdentityServer4.Samples/Docker`
3. `git checkout cad8612d2c20b12b3e8a5b30c826f25938b3f141`
4. `docker-compose build`
5. Change a `.cs` file inside `./src` folder
6. run `docker-compose build` again

## Expected behavior

Should not do a package restore again as [it does the `project.json` copy + `dotnet restore` before copying the other files](https://github.com/IdentityServer/IdentityServer4.Samples/blob/cad8612d2c20b12b3e8a5b30c826f25938b3f141/Docker/docker-api.dockerfile#L3-L6).

## Actual behavior

Executes `dotnet restore` again.

## Output of `docker version`

```
Tugberks-MBP:MVC and API tugberk$ docker -v
Docker version 1.12.0, build 8eab29e
```

## Output of `docker info`

```
Tugberks-MBP:MVC and API tugberk$ docker info
Containers: 15
 Running: 2
 Paused: 0
 Stopped: 13
Images: 256
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 268
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: IKXJ:DDA7:PXVP:N2NZ:3NJ4:KQI7:RIMZ:U57R:QSLW:JPCO:FQL6:7PSU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 55
 System Time: 2016-09-15T10:43:25.44631528Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by SteveLasker** [comment]
I have to look at this with a little more time as I'm not familiar with this sample. The image we posted microsoft/aspnetcore assumes you're placing the published content, from dotnet publish (release mode) into the image. Take a look at http://aka.ms/DockerToolsForVS to see how we create and structure dockerfiles. You can see the results of a dockerized project here: https://github.com/SteveLasker/DockerToolsForVS-040-Sample

**Comment by SteveLasker** [comment]
Hi @tugberkugurlu
Looking a bit more at the Dockerfiles, these use a mode where the code is copied and restored in the container. While we ad modishly haven't done a great job explaining a best practice for building images with compiled languages, such as .NET, this is using this model 
What the sample should do is copy the output of a published folder into the image.
Building the published output could be done with a build image or on your developer workstation with dotnet publish 
This is something well document more and will likely be a core part of our ignite presentation. 
As we prepare for ignite this week, I'll see if I can propose an update/pull request to the identity repo
Steve

**Comment by naamunds** [comment]
@tugberkugurlu Because the Dockerfiles in [IdentityServer4.Samples/Docker/](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Docker) use `microsoft/dotnet:1.0.0-preview2-onbuild` as their base image, the `ONBUILD` instructions [defined in `microsoft/dotnet:1.0.0-preview2-onbuild`](https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview2/debian/onbuild/Dockerfile) are executed before any instructions declared in the IdentityServer4.Samples Dockerfiles.
> ONBUILD COPY . /dotnetapp
> ONBUILD RUN dotnet restore

This means that the .cs file which was modified in step 5 of your repro is copied to the container before `dotnet restore` is run.

If these `ONBUILD` instructions are not desired for IdentityServer4.Samples, it might be better to use `microsoft/dotnet:1.0.0-preview2-sdk` as the base image.

**Comment by MichaelSimons** [comment]
@tugberkugurlu, the [Dockerfiles ](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Docker) do not seem optimal.  They are based on the onbuild image which already copies the entire contents of the Docker context into a dotnetapp folder of the image.  The onbuild also performs a dotnet restore from the dotnetapp folder.  The Dockerfile then proceeds to copy the app xxx specific content into an app folder.  This duplication is not necessary; it increases the docker build times and bloats the resulting images.

At a glance it appears that the Dockerfiles should simply be based on the sdk image (1.0.0-preview2-sdk or latest) and then everything would work as expected.

**Comment by MichaelSimons** [comment]
Logged https://github.com/IdentityServer/IdentityServer4.Samples/issues/66 to address the issue with the sample Dockerfiles.  Closing this issue.

**Comment by szalapski** [comment]
@MichaelSimons Do you have a better link?   https://github.com/IdentityServer/IdentityServer4.Samples/issues/66 seems to be broken, and I have the same question.

**Comment by MichaelSimons** [comment]
@szalapski, Sorry I do not.  It appears as though the https://github.com/IdentityServer/IdentityServer4.Samples repo was deleted.
