### ISSUE TITLE
Investigate why re-runs do not work for pipeline builds

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1096]
The Azure Pipeline jobs have the ability to be re-run from a PR build, showing a re-run link command in GitHub.  This is useful if a job were to fail for a random reason unrelated to the changes.  The problem is that something about how the pipelines are defined prevents the re-run from working.  It becomes a no-op.  This needs to be investigated.

**Comment by MichaelSimons** [comment]
This issue has been fixed in Azure Pipelines.
