### ISSUE TITLE
Ask: Provide unprivileged docker aspnet core runtime image for Linux

### ISSUE THREAD

**Issue by loekd** [dotnet/dotnet-docker#1099]
## Is your feature request related to a problem? Please describe.
The provided aspnet core runtime images run as root. For optimal security (least privilege), I want aspnetcore to run as a regular user (non-root). 

## Describe the solution you'd like
I'd like to be able to pull a (microsoft managed) aspnet core runtime image (e.g. `mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim-unprivileged`) that exposes an unprivileged port, like 8080 and runs as a standard user.
Similar to this [nginx](https://github.com/nginxinc/docker-nginx-unprivileged) image.

## Describe alternatives you've considered
There's a workaround described [here](https://github.com/aspnet/aspnet-docker/issues/271#issuecomment-317492437) that works, but it adds clutter to all my dockerfiles.
I could create an intermediate image, but it would require regular maintenance.

## Additional context
n/a

**Comment by MichaelSimons** [comment]
This is something that we do not believe belongs within the .NET images.  It is difficult to add a user and configure it in a way that satisfies a broad audience.  This is something that better belongs at the app layer.

Closing as Won't Fix
