### ISSUE TITLE
Base Dockerfile should be based on Debian

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#11]
The base Dockerfile should be based on Debian.  Currently the .NET CLI tooling does not support Debian.  Issue #6 has some additional information on why this is desirable.

**Comment by MichaelSimons** [comment]
I have verified CoreCLR (packages) now supports Debian 8.  Dotnet cli RID detection also works.  The only remaining piece is that the project.json produced by `dotnet new` has not been updated to reference the latest NETStandard.Library that supports Debian 8.  This is needed to provide a working 'out of box' experience.

**Comment by dleeapho** [comment]
dotnet new changes are done. We need CLI to be build on Debian and create a Debian tarball at a minimum.

**Comment by fthamura** [comment]
I vote for alpine linux ...smaller

**Comment by MichaelSimons** [comment]
@fthamura thanks for the input.  Alpine is on our radar - https://github.com/dotnet/dotnet-docker/issues/22

**Comment by MichaelSimons** [comment]
The preview1/rc2 images are based on Debian - https://github.com/dotnet/dotnet-docker/pull/36
