### ISSUE TITLE
Cant pull aspnet / dotnet core image from Microsoft registry

### ISSUE THREAD

**Issue by tburnett80** [dotnet/dotnet-docker#1102]
## Steps to reproduce the issue
1. Issue docker pull command from https://hub.docker.com/_/microsoft-dotnet-core-aspnet/?tab=description

C:\>docker pull mcr.microsoft.com/dotnet/core/aspnet:2.2

## Expected behavior
Image is pulled from Microsoft container registry

## Actual behavior
Docker fails to pull while giving the following message:

no matching manifest for unknown in the manifest list entries

## Additional information (e.g. issue happens only occasionally)
![image](https://user-images.githubusercontent.com/4324080/57147711-d30a6180-6d8d-11e9-8618-dafda6f10f86.png)

## Output of `docker version`

```
Client: Docker Engine - Enterprise
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        c3516c43ef
 Built:             03/27/2019 18:22:15
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       c3516c43ef
  Built:            03/27/2019 18:20:29
  OS/Arch:          windows/amd64
  Experimental:     false

```

## Output of `docker info`

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 18.09.4
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2906.amd64fre.rs1_release_inmarket.190401-1809)
Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.2906)
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 16GiB
Name: 
ID: 
Docker Root Dir: D:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by MichaelSimons** [comment]
Please see [this announcement](https://github.com/dotnet/dotnet-docker/issues/1041) regarding the nanoserver-sac2016 and nanoserver-1709 images reaching EOL.

**Comment by MichaelSimons** [comment]
Closing issue as nanoserver-sac2016 images are EOL.
