### ISSUE TITLE
2.2.203 SDK ridiculously large, 500MB+ download, unpacked 1.75GB affecting CI times

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/dotnet-docker#1105]
2.2.203 SDK has a ridiculously large, 500MB+ download, unpacked according to docker images it's 1.75GB, and it's affecting CI times.

It seems we're even getting rate limited by `mcr.microsoft.com` during sdk downloads.

Compared to it the 3.0 sdk is 688MB unpacked and <200MB download. Will this also grow over the lifetime of 3.x to these huge sizes?

**Comment by MichaelSimons** [comment]
The large SDK size in the pre 3.0 images comes primarily from the NuGet package cache.  This has been removed in 3.0.  See https://github.com/dotnet/designs/pull/50 for details.

**Comment by NinoFloris** [comment]
Great thanks a lot, thanks for the link!
