### ISSUE TITLE
Support servercore in addition to nanoserver

### ISSUE THREAD

**Issue by M-Pixel** [dotnet/dotnet-docker#1106]
## Steps to reproduce the issue
Go to https://hub.docker.com/_/microsoft-dotnet-core-runtime/

## Expected behavior
There are options based on both of the Windows base images, just like for [PowerShell](https://hub.docker.com/_/microsoft-powershell) and many others.

## Actual behavior
There are only options based on `nanoserver` for Windows.

`dotnet` does not exist in Windows Server Core, so if I want to use `dotnet foobar.dll` in a container, my only option is to build my own image.

**Comment by MichaelSimons** [comment]
@M-Pixel Could you please share what your scenario is in which you would like to have a Windows Server Core based .NET Core  image?  Our recommendation is to use the lightweight Nano Server based images.  This provides the best .NET Core experience.

**Comment by M-Pixel** [comment]
.NET Core application that interacts with a headless Firefox process.  Firefox and numerous other Win32 programs out there do not support Nano Server (yet).

**Comment by MichaelSimons** [comment]
@M-Pixel, I acknowledge your scenario but there isn't enough demand to warrant the cost of producing and maintaining Server Core images.  For scenarios like this, it is expected that you can easily copy the nanoserver Dockerfiles and switch the base image or `servercore`.
