### ISSUE TITLE
is it just me or docker alpine images are huge?

### ISSUE THREAD

**Issue by cyberhck** [dotnet/dotnet-docker#1108]
I tried the following:
```bash
docker pull mcr.microsoft.com/dotnet/core/sdk:2.1-alpine
docker pull mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
docker pull mcr.microsoft.com/dotnet/core/sdk
```
And noticed the size are very large
- `2.1-alpine` tag is 1.48 GB
- `2.2-alpine` tag is 1.48 GB
- `latest` tag is 1.74 GB
as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/3640284/57424648-97b2db80-7242-11e9-872f-937de294fac0.png)

I'd love if someone else also can verify, I don't think it's expected.

**Comment by tuananh** [comment]
it's the sdk image, it's understandably big right? if you want to be small, use runtime image

**Comment by cyberhck** [comment]
I didn't know dotnet sdk would go over 1GB, okay, will close if it's expected, just wanted to make sure it's nothing unexpected.
