### ISSUE TITLE
Dotnet Core SDK 2.1.507 Not Found

### ISSUE THREAD

**Issue by Pede23** [dotnet/dotnet-docker#1135]
## Steps to reproduce the issue
1. Create DockerFile
2. Attempt to use 'FROM mcr.microsoft.com/dotnet/core/sdk:2.1.507'

## Expected behavior

Docker image for dotnet core sdk 2.1.507 should exist.

## Actual behavior

Docker image for dotnet core sdk 2.1.507 does not exist.

## Additional information (e.g. issue happens only occasionally)

Would it be possible for an image with this version of the SDK to be created?

**Comment by MichaelSimons** [comment]
We only produce SDK images for the latest versions of the SDK which for 2.1 is currently `2.1.700`.  What is your scenario for wanting to 2.1.507?

**Comment by Pede23** [comment]
Our pipeline is not set up to use MSBUILD >= 16.0.0. We are also still using VS2017 and we have not prepared to update to VS2019 on our dev machines etc.

**Comment by Pede23** [comment]
I'd be happy to generate it. I need the wget URL i would need to pull in the sdk though. Can you help me with that?

**Comment by MichaelSimons** [comment]
You can find the URLs for 2.1.507 [here](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.11/2.1.11-download.md#downloads)

**Comment by Pede23** [comment]
fixed
