### ISSUE TITLE
windows server images

### ISSUE THREAD

**Issue by miahwk** [dotnet/dotnet-docker#1137]
Which is the windows container image?
Does look like `docker pull mcr.microsoft.com/dotnet/core/sdk:2.1-nanoserver-1803`?
If use the 2.1 tag,it is the linux image. 
![image](https://user-images.githubusercontent.com/20128378/58232188-7c2ff080-7d6b-11e9-924c-4e751774f580.png)
![image](https://user-images.githubusercontent.com/20128378/58232229-95d13800-7d6b-11e9-89ef-22528cbcfb15.png)
What is the different between them? Such as tag `2.1`. I just want to use windows image. Could someone help me?

**Comment by MichaelSimons** [comment]
@miahwk - The `2.1` tag is a [multi-platform tag](https://github.com/dotnet/dotnet-docker/issues/239).  That means the tag references multiple images.  When you pull the tag, you will get an image that matches your platform.  If you are getting a linux image that implies to me that you are pulling the tag from a linux container environment.  Windows tags can only be pulled from a Windows container environment.  See this link on how to [switch environments](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) on Windows.  You can run `docker info` to see what you container mode is set to via the `OSType` property.

**Comment by MichaelSimons** [comment]
Closing per previous response.

**Comment by miahwk** [comment]
@MichaelSimons Thank you. So you meas if use 2.1 tag, it will match the container OSType?

**Comment by MichaelSimons** [comment]
No - If you use multi-arch tags, the container OS will be compatible with your host OS.  By this I mean the architecture will be compatible, the OS type (Linux/Windows) will match and for Windows, the OS version will be compatible with the host.

**Comment by miahwk** [comment]
@MichaelSimons I got it. Thank you for your help. :)
