### ISSUE TITLE
Failed to load X*), error: /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.5/libhostpolicy.so: file too short

### ISSUE THREAD

**Issue by lightel** [dotnet/dotnet-docker#1143]
## Steps to reproduce the issue
1. Create new application: `dotnet new console`
2. Add **Dockerfile** with the following content
```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
EXPOSE 80
COPY dist /app
WORKDIR /app
ENTRYPOINT ["dotnet", "app.dll"]

```
3. Build app: `dotnet publish -c Release -o dist`
4. Build docker image: `docker build -t aspcore_docker_test .`
5. Run docker container: `docker run -it aspcore_docker_test`

## Expected behavior
Dockerized app runs successfully.

## Actual behavior
```
Failed to load X*), error: /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.5/libhostpolicy.so: file too short
An error occurred while loading required library libhostpolicy.so from [/usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.5]
```

## Additional information (e.g. issue happens only occasionally)
Issue happens with the official Docker image for running ASP.NET Core applications `mcr.microsoft.com/dotnet/core/aspnet:2.2`. The alpine image (`mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine`) works fine.

## Output of `docker version`

```
PS C:\Work\Sources\docker> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 96
 Running: 0
 Paused: 0
 Stopped: 96
Images: 214
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 558d4kurqdczxokh01utjnsj5
 Is Manager: true
 ClusterID: 9aqvyb3s9geuew9njvq5a4c15
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d174a12
ID: JLSP:KM6K:YZZN:3W5I:YGFI:IER4:AE5D:UMSU:JMMV:3K35:FYXL:MUMZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 167
 System Time: 2019-05-29T10:00:31.8644878Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by mthalman** [comment]
@lightel  - I was not able to repro this myself using your steps.  I got the "Hello World" message when I tried.  I'm curious why you're using aspnet as the base image for a console app.  Have you tried this with any of the sample apps at https://github.com/dotnet/dotnet-docker/tree/master/samples/ to see whether it reproduces with any of those?

**Comment by lightel** [comment]
@mthalman thank you for your response. Seems like there was some issue with my environment. I wasn't able to repro this this issue on another PC and after I pruned all the containers and images from the original PC it started working. Just in case if somebody ever run into this issue use this command to reset docker:
`docker system prune --all --force --volumes`

**Comment by micahmo** [comment]
`docker system prune --all --force --volumes`

This worked for me too, thanks! Note that it's important to prune the system with Visual Studio closed, so that it can clean up the automatic container that Visual Studio creates/runs for your project.
