### ISSUE TITLE
Swap generated docker file extension so that every non-default file ends with `.Dockerfile`

### ISSUE THREAD

**Issue by ivansharamok** [dotnet/dotnet-docker#1152]
## Issue

Code editing tools like Visual Studio (VS) recognize `Dockerfile` or any file with `.Dockerfile` extension as a DOCKERFILE. Once the `Dockerfile` file is recognized by VS, the syntax highlight and intellisense features become available for use. Any `Dockerfile` that doesn't end up with `.Dockerfile` extension is treated as a regular TXT file.
Consider making auto-generated non-default Dockerfiles to have `.Dockerfile` extension rather that staring with Dockerfile as a prefix.

## Expected behavior

Every `Dockerfile` when opened in VS Code or other IDE should have highlighted syntax.

## Actual behavior

Every dockerfile named differently than `Dockerfile` and the name does not end with `.Dockerfile`, loses syntax highlight in IDE (e.g. VS Code)

## Additional information (e.g. issue happens only occasionally)

Proposed naming convension

| Now | Proposed |
| ---- | ---------- |
| Dockerfile | Dockerfile |
| Dockerfile.alpine-x64 | alpine-x64.Dockerfile |
| Dockerfile.nanoserver-sac2016 | nanoserver-sac2016.Dockerfile |
| Dockerfile.preview | preview.Dockerfile |

**Comment by mthalman** [comment]
Thanks for the suggestion @ivansharamok.  We'll discuss this in our next triage.

Be aware that you can set VS Code to use Dockerfile syntax highlighting even if the file is named Dockerfile.*.  In the lower-right status bar there's a Language Mode indicator.  With these filenames, the mode will be set to Plain Text by default.  But you can click it and change it to Dockerfile to give you the syntax highlighting you want.

**Comment by ivansharamok** [comment]
thanks, @mthalman. Sounds like an easy workaround but requires manual intervention and education. 
I believe it could be easier to make VS Code to handle this by default rather than try to educate every developer on features VS Code (or any other IDE) offers.

**Comment by MichaelSimons** [comment]
We have discussed this and are not going to make this change as we feel this is the pattern used most often within the community and has it's advantages.  We see this as a tooling issue in regards to not handling a commonly used practice within the Docker ecosystem.
