### ISSUE TITLE
IdentityModel with docker sdk 2.2

### ISSUE THREAD

**Issue by EmilioMaestro** [dotnet/dotnet-docker#1156]
## Steps to reproduce the issue
1. Create a web API with Microsoft.IdentityModel (jwt token) .net core 2.2
2. Test it with local IIS
3. Build it with docker sdk 2.2

## Actual behavior

Build Failed

## Additional information (e.g. issue happens only occasionally)

docker sdk image 2.2 does not contain libs Microsoft.IdentityModel

UserService.cs(3,17): error CS0234: The type or namespace name 'IdentityModel' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/src/OTIC-API.Services/OTIC-API.Services.csproj]
UserService.cs(11,14): error CS0234: The type or namespace name 'IdentityModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [/src/OTIC-API.Services/OTIC-API.Services.csproj]

Build FAILED.

## Output of `docker version`

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

## Output of `docker info`
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 135
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155ddf340c
ID: MGYE:LXZO:WY4Y:7YVV:BB7S:6PJ7:KP6P:QLCC:4XMH:PEGU:NXIA:BXMR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2019-06-04T12:56:09.2290304Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by mthalman** [comment]
@EmilioMaestro - I can't seem to repro this behavior.  What does your Dockerfile look like?

Here's what I had tried to repro:
1. Get the ASP.NET sample app following the instructions here: https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp#getting-the-sample.
2. Modified the HomeController.cs file to reference a type from Microsoft.IdentityModel:
    ```
    public IActionResult About()
    {
        ViewData["Message"] = typeof(Microsoft.IdentityModel.Tokens.AsymmetricSecurityKey).Name;

        return View();
    }
    ```
3. Build the image: `docker build --pull -t aspnetapp .`

Can you try those steps as well and see if you can repro?  If not, can you compare how your app differs from the sample?

**Comment by EmilioMaestro** [comment]
Thanks for you answer.

My DockerFile

> FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
> WORKDIR /app
> EXPOSE 4501
> 
> FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
> WORKDIR /src
> COPY ["OTIC-API/OTIC-API.csproj", "OTIC-API/"]
> COPY ["OTIC-API.Services/OTIC-API.Services.csproj", "OTIC-API.Services/"]
> COPY ["OTIC-API.Services.Contracts/OTIC-API.Services.Contracts.csproj", "OTIC-API.Services.Contracts/"]
> COPY ["OTIC-API.Entities.Contracts/OTIC-API.Entities.Contracts.csproj", "OTIC-API.Entities.Contracts/"]
> COPY ["OTIC-API.Dal.Contracts/OTIC-API.Dal.Contracts.csproj", "OTIC-API.Dal.Contracts/"]
> COPY ["OTIC-API.Entities/OTIC-API.Entities.csproj", "OTIC-API.Entities/"]
> COPY ["OTIC-API.Dal/OTIC-API.Dal.csproj", "OTIC-API.Dal/"]
> RUN dotnet restore "OTIC-API/OTIC-API.csproj"
> COPY . .
> WORKDIR "/src/OTIC-API"
> RUN dotnet build "OTIC-API.csproj" -c Release -o /app
> 
> FROM build AS publish
> RUN dotnet publish "OTIC-API.csproj" -c Release -o /app
> 
> FROM base AS final
> WORKDIR /app
> COPY --from=publish /app .
> ENTRYPOINT ["dotnet", "OTIC-API.dll"]
> 

Also, i'm using self hosted Azure agent on my computer to build image and push it to my docker hub. 

I already using that to build another repo (and it works) see bolow

> FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
> WORKDIR /app
> EXPOSE 4500
> 
> # copy csproj and restore as distinct layers
> COPY *.sln .
> COPY ServiceProcessing.Web/*.csproj ./ServiceProcessing.Web/
> RUN dotnet restore
> 
> # copy everything else and build app
> COPY ServiceProcessing.Web/. ./ServiceProcessing.Web/
> WORKDIR /app/ServiceProcessing.Web
> RUN dotnet publish -c Release -o out
> 
> 
> FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
> WORKDIR /app
> COPY --from=build /app/ServiceProcessing.Web/out ./
> ENTRYPOINT ["dotnet", "ServiceProcessing.Web.dll"]

**Comment by EmilioMaestro** [comment]
Yes. It's working on my VS2017. Compiling & execute. This is only when i'm building the docker image.

**Comment by mthalman** [comment]
I'm asking about this:

> Also, i'm using self hosted Azure agent on my computer to build image and push it to my docker hub.

> I already use that to build another repo (and it works) see bolow

It sounds like you're saying that you've got another app that you've successfully built a Docker image for.  Is that true?  Does that app reference Microsoft.IdentityModel?

**Comment by EmilioMaestro** [comment]
Yes, it's true. 

No references, that's why it works.

**Comment by mthalman** [comment]
For the project that does currently work, have you verified that if you add a reference to Microsoft.IdentityModel it will fail?

Without a project to repro this on, it's difficult to resolve this issue.  Are you able to send your project to me at mthalman@microsoft.com?  Otherwise, are you able to create a simple project from scratch that you can repro this on?

**Comment by EmilioMaestro** [comment]
> For the project that does currently work, have you verified that if you add a reference to Microsoft.IdentityModel it will fail?

It's works. I'll try something else why my first project who didn't work. There is NuGets packages named as "Microsoft.IdentityModel". Although, there is a Microsoft DLL for that...

**Comment by MichaelSimons** [comment]
Closing as this seems related to the specific project.  Feel free to continue the conversation or re-open if further investigation surfaces issues with the .NET Core images.
