### ISSUE TITLE
Asp.net core runtime for rhel 6 

### ISSUE THREAD

**Issue by balarvs2002** [dotnet/dotnet-docker#1158]
Where do I download asp.net core runtime for rhel 6?

**Comment by mthalman** [comment]
Red Hat manages their own Docker images.  You'll need to go through them to find it if one exists.  Check here to start with: https://access.redhat.com/documentation/en-us/net_core/2.2/html/getting_started_guide/gs_install_dotnet.

**Comment by MichaelSimons** [comment]
We (.NET Core team) does not produce any Docker images for RHEL.  RHEL themselves produce rhel 7 images.  .NET Core does produce [rhel 6 SDK artifacts](https://dotnet.microsoft.com/download/dotnet-core/2.2) that you can grab the runtimes from and produce your own Docker image from.

**Comment by balarvs2002** [comment]
@MichaelSimons ; Thanks for your reply.
