### ISSUE TITLE
Move off ILLink.Tasks in samples to 3.0 SDK linker

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#1167]
As described in this post: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-6/

Example usage: https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile.debian-x64-selfcontained#L16

**Comment by MichaelSimons** [comment]
A prerequisite for this is to release 3.0 and upgrade the sample to be based on the 3.0 images.
