### ISSUE TITLE
Memory leak/much higher memory consumption since 2019-06-11 release

### ISSUE THREAD

**Issue by MiloszKrajewski** [dotnet/dotnet-docker#1170]
Docker images (microsoft/dotnet:runtime) released on 2019-06-11 seem to have either memory leak or much higher memory consumption. Same service, released on previous image was working fine with 128MB memory limit. Now they crash with mysterious message "Killed" (I understand it is docker killing them) and when memory limit is increased (512MB for now) they completely saturate it.

## Expected behavior
Working and not being killed by docker.

## Actual behavior
Are killed by docker.

## Docker version
Unfortunately, I don't know as it is on AWS Fargate 1.3.0. I can say though thay Fargate 1.3.0 is the latest.

**Comment by mthalman** [comment]
What OS is this?  Windows? Linux?  Can you provide a simple project that can reproduce this behavior?  What version of the image were you using previously?

**Comment by MiloszKrajewski** [comment]
Hi,

It happens on AWS Fargate. Which is hosting docker containers on Amazon Linux which is based on Red Hat. I actually cannot find version of kernel/docker/whatever but the platform, AWS Fargate 1.3.0 is the newest one, so it should be pretty recent version of kernel/docker.

We always used latest image version, not caring too much about which one is it, literally:
```
FROM microsoft/dotnet:runtime
```

Yesterday we noticed services being restarted from time to time, with cryptic message "Killed". No exception or anything, they are just stopped. Googling this symptom leads to OOM and docker killing service when it reaches some limit.

I do understand that 128MB limit is relatively low, but at the same time they worked with this limit week before (and week before that) and suddenly all just stopped. From https://hub.docker.com/_/microsoft-dotnet-core-runtime/ I found out that new image has been just released and it coincides with those restarts.

I acknowledge that I I don't know too much, I just hope you know what actually change 2 days ago and that might be a clue.

**Comment by mthalman** [comment]
Can you provide a simple project that can reproduce this behavior?

**Comment by MiloszKrajewski** [comment]
I have nothing apart from our "real" services which will not work without all the databases, queues and consul. I can create a skeleton service doing almost nothing, but this might prove nothing.

I just hoped that there is something distinctive which was delivered two days ago: new .NET Core runtime, new libuv? As I said, this problem suddenly appear without any code changes, just after rebuilding docker images with new `microsoft/dotnet:runtime` as base images.

**Comment by mthalman** [comment]
The only change that occur on 6-11 was that the images were rebuilt due to a new Debian base image.  In your case, since you're using microsoft/dotnet:runtime, that uses debian:stretch-slim as a base image.  So a change was made to that image which caused us to rebuild our .NET runtime image.  That's the only difference; the .NET bits in the previous image and current image are identical.  So without a repro project, it's difficult to determine what interaction between the new base image and the .NET Core runtime is that is causing the issue.

For now, you should be able to get unblocked by referencing the digest value of the previous version of the image:
`FROM mcr.microsoft.com/dotnet/core/runtime@sha256:066c31b113b0a20e6155d3bd8a314563c688d2ec31c11d7e551af5bc2595f30c`

**Comment by MiloszKrajewski** [comment]
Thank you. That is helpful, I dug sha for older image, but yours is better.

**Comment by MichaelSimons** [comment]
Without having a set of steps to reproduce this issue or to know details about the containerized app, it is difficult to help.  This is the only report we have seen in regards to picking up the latest base image.

On a side note, I am curious as to why you are using the `microsoft/dotnet:runtime` tag versus a versioned tag?  The `microsoft/dotnet:runtime` tag will get updated to point to `3.0` once it releases and the may break your app.  In general, I would recommend using the `<major>.<minor>` tags which will allow you to isolate yourself from breaking changes yet pick up the latest patch releases.
