### ISSUE TITLE
Fix dotnet-core-size-validation build

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1179]
The size validation build is failing due to its baseline files not being up-to-date.  The Windows leg is also failing due to the addition of Windows 1903; it needs to be run on a compatible agent OS that can pull down the 1903 image.

**Comment by MichaelSimons** [comment]
This highlights the importance of getting these tests run as part of CI (https://github.com/dotnet/dotnet-docker/issues/936).
