### ISSUE TITLE
ASPNETCORE_URLS environment variable set in SDK image

### ISSUE THREAD

**Issue by jmezach** [dotnet/dotnet-docker#1199]
I was wondering why the ASPNETCORE_URLS environment variable is being set for the SDK images. I can see that this was added with #428, and discussed in #426. The rationale there was that one shouldn't use dotnet run inside of the container in the first place, but if you do at least it would work.

With the availability of remote development features in VS Code, especially with containers, I would suggest this makes less sense now. Personally I think that using the SDK image as a base image for creating a development container is a really nice way to setup consistent development environments for teams to use.

Now this does beg the question whether it makes sense that ASPNETCORE_URLS is set so http://+:80 for the SDK image, since if you would install the SDK directly on your machine the environment variable wouldn't be set and Kestrel will default to using ports 5000 and 5001 (for http and https respectively). Therefore I would suggest removing this from the SDK image to create consistency with a native install.

Additionally, the ASPNETCORE_Environment variable isn't set within the SDK image. To be consistent with the native install I would imagine this variable be set to Development in the SDK image.

**Comment by MichaelSimons** [comment]
@richlander, @glennc - Could you provide input on this issue?

1. Should the SDK images continue setting ASPNETCORE_URLS?
2. Should the SDK images be setting ASPNETCORE_Environment as well in the container?

**Comment by MichaelSimons** [comment]
We believe `ASPNETCORE_URLS` should be removed from the SDK images and should be done for 3.0.  When addressing, keep in mind the Alpine SDK images are based on the `runtime-dep` images.  In these images, the setting will have to be 'reversed'.
