### ISSUE TITLE
Are there Windows versions of these images?

### ISSUE THREAD

**Issue by jjmpsp** [dotnet/dotnet-docker#1204]
Do these images support Windows or no? This issue appears to suggest tags are for multiple architectures: https://github.com/dotnet/dotnet-docker/issues/1137 but I've tried a series of combinations and always get the same error about windows/amd64 not being supported.

```C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 10.0.14393 in the manifest list entries.```

## Steps to reproduce the issue
1. docker run --rm mcr.microsoft.com/dotnet/core/samples (or)
2. docker run --rm mcr.microsoft.com/dotnet/core/sdk:2.
3. docker run --rm mcr.microsoft.com/dotnet/core/aspnet:2.2

## Expected behavior
Windows compatible image is pulled successfully.

## Actual behavior
Error is produced: ```C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 10.0.14393 in the manifest list entries.```

## Output of `docker version`

```
Client: Docker Engine - Enterprise
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        1578dcadd2
 Built:             05/04/2019 02:34:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       1578dcadd2
  Built:            05/04/2019 02:32:24
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 43
 Running: 6
 Paused: 0
 Stopped: 37
Images: 44
Server Version: 18.09.6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat
 Log: awslogs etwlogs fluentd gelf
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2
Operating System: Windows Server 20
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 8GiB
Name: WIN-6FDE18KEH93
ID: FY6X:VYWE:NB67:EEAB:QOBI:JIIM:Q
Docker Root Dir: C:\ProgramData\doc
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
```

Can anyone from Microsoft advise?
Thank you

**Comment by jjmpsp** [comment]
So I've tried more tags and I think the answer to my question is Yes.

**Comment by mthalman** [comment]
> Does this mean I need a newer host OS?
> `Windows version 10.0.17134-based image is incompatible with a 10.0.14393 host`

Correct.  You cannot use a Docker image that targets a newer version of Windows compared to the Windows version of the Docker host (but you can use Docker images that target _older_ versions).  In this case, there are no supported .NET Core images for 1607 (build 14393).

The recommendation would be to use a host OS that matches or exceeds the version of Windows you want an image for.

**Comment by mthalman** [comment]
See [Windows container version compatibility](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) for more info.

**Comment by jjmpsp** [comment]
Gotcha. So by reading other sources, it seems these images are supported for any Windows 10 build newer than April 16th 2018, or any version of Windows Server 2019. I was running Windows Server 2016 which is why I saw the above error.

```
Version 1803 (April 2018 Update)
The Windows 10 April 2018 Update[511][512] (also known as version 1803[513] and codenamed "Redstone 4") is the fifth major update to Windows 10 and the fourth in a series of updates under the Redstone codenames. It carries the build number 10.0.17134. The first preview was released to Insiders on August 31, 2017. The final release was made available to Windows Insiders on April 16, 2018, followed by a public release on April 30, and began to roll out on May 8.[514][515]
```

Thanks @mthalman for the update
