### ISSUE TITLE
source of runtime-deps:2.2-alpine3.9

### ISSUE THREAD

**Issue by codingfunwoody** [dotnet/dotnet-docker#1209]
I saw it is using by [2.2/runtime/alpine3.9/amd64/](https://github.com/dotnet/dotnet-docker/blob/master/2.2/runtime/alpine3.9/amd64/Dockerfile)
Would it be open source?
i only see runtime-deps/alpine3.8/amd64 folder.

**Comment by codingfunwoody** [comment]
finally i installed it on alpine3.9 base on runtime-deps/alpine3.8/amd64. I guess it is the same runtime-deps?

**Comment by mthalman** [comment]
No, it actually shares the runtime-deps from 2.1: [2.1/runtime-deps/alpine3.9/amd64/Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime-deps/alpine3.9/amd64/Dockerfile).  This is described via the metadata in the [manifest.json](https://github.com/dotnet/dotnet-docker/blob/a94b5b591f78a28e12bbe57f2725962b1ec22f73/manifest.json#L111) file where it specifies that the 2.2-alpine3.9 tag should be defined for [2.1/runtime-deps/alpine3.9/amd64/Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime-deps/alpine3.9/amd64/Dockerfile).

**Comment by MichaelSimons** [comment]
All source links are available on the Docker Hub pages.  For this particular scenario, you can find the available runtime-deps tags and Dockerfile source links at https://hub.docker.com/_/microsoft-dotnet-core-runtime-deps/.
