### ISSUE TITLE
Add ca-certificates to core-deps image

### ISSUE THREAD

**Issue by thinktainer** [dotnet/dotnet-docker#121]
## Steps to reproduce the issue
1. Create a self contained deployment that calls a SSL encrypted website endpoint
2. Copy deployment to core-deps image
3. Run the application
## Expected behavior

Endpoint communication should succeed.
## Actual behavior

The connection cannot be established due to missing ca-certificates package.

**Comment by MichaelSimons** [comment]
cc @dleeapho, @glennc - When core-deps was created, the requirement was to only added the required .NET core dependencies and to keep the image as small as possible.  Adding ca-certificates would add 3.5 MB.  What are your thoughts?  The core image includes ca-certificates and curl.

**Comment by glennc** [comment]
@thinktainer Is there a reason you can't ad ca-certificates to your own image? I assume that you are doing that now and this is more to make something like this work out-of-the-box for others. Is that correct?

I am also assuming that ca-certificates are not in the core image, is that right @MichaelSimons?

**Comment by naamunds** [comment]
The `core` image installs both `ca-certifiactes` and `curl` on top of what's installed in the `core-deps` image.  See https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/core/Dockerfile#L4-L6.

**Comment by glennc** [comment]
Of course. So we can download dotnet.

I am not against moving the 3.5mb down to core-deps. We have to assume that SSL is eventually going to be the default for any HTTP endpoint, and also assume that connecting over HTTP is so common that we might as well pay any cost here.

@MichaelSimons do you agree?

**Comment by MichaelSimons** [comment]
@glennc, I agree.

**Comment by naamunds** [comment]
I've made a PR for this in the nightly repo.  Adding `ca-certificates` only increased the size of the image on my Ubuntu Docker host by 1.8 MB, from 164.1 MB to 165.9 MB.

**Comment by thinktainer** [comment]
Thank you for the fast turn around.

**Comment by MichaelSimons** [comment]
@naamunds - Thanks for fixing this in nightly.  Because this is a functional change, I am thinking this should not be made in the official Dockerfiles until we move to 1.1 of the runtime - e.g. rev the version of the Dockerfile.

**Comment by dleeapho** [comment]
@MichaelSimons - I agree we should wait on the 'official' Dockerfiles for 1.1

**Comment by naamunds** [comment]
Makes sense. @thinktainer, in the meantime you can use `microsoft/dotnet-nightly:rel-1.0.0-core-deps`, which is otherwise identical to `microsoft/dotnet:1.0.1-core-deps`.

**Comment by naamunds** [comment]
Makes sense.

@thinktainer, in the meantime you can use the following Dockerfile to create a core-deps image with ca-certificates:

    FROM microsoft/dotnet:1.0.1-core-deps
 
    RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
        && rm -rf /var/lib/apt/lists/*

Alternatively, you can use `microsoft/dotnet-nightly:rel-1.0.0-core-deps`, but be aware that breaking changes may be made to `dotnet-nightly` images, so they're not intended for use in production environments.

**Comment by thinktainer** [comment]
Thank You!
