### ISSUE TITLE
StackTrace show wrong or no line number.

### ISSUE THREAD

**Issue by crucialize** [dotnet/dotnet-docker#1210]
## Steps to reproduce the issue
1. Download my solution file. The length of the code (Program.cs) is only 35 lines.
2. Run "docker build -f BugApp/Dockerfile . --tag bugapp" 
3. Run "docker run bugapp" and see the output

The code in the zip file only can reproduce the situation of missing line number.
[BugApp.zip](https://github.com/dotnet/dotnet-docker/files/3364004/BugApp.zip)

Program.cs
```cs
static void Main(string[] args)
		{
			Stream s = null;

			const int BufferSize = 4096 * 1024;
			var buffer = new byte[BufferSize];

			var t = ReceiveMessage();

			async Task ReceiveMessage()
			{

				try
				{
					throw new Exception("CustomException");

					await s.ReadAsync(buffer, 0, BufferSize);// !!!
					buffer[0] = 0;// !!!
				}
				catch (Exception e)
				{
					Console.WriteLine(e);
				}
			}
		}
```

## Expected behavior
```cs
System.Exception: CustomException
   at BugApp.Program.<>c__DisplayClass0_0.<<Main>g__ReceiveMessage|0>d.MoveNext() in /src/BugApp/Program.cs:line 23
```

## Actual behavior
```cs
System.Exception: CustomException
   at BugApp.Program.<>c__DisplayClass0_0.<<Main>g__ReceiveMessage|0>d.MoveNext()
```
You can see that the line number is missing.
The code in the zip file only can reproduce the situation of missing line numbers.

## Additional information (e.g. issue happens only occasionally)
Bug occurs both on my pc (windows10) and my cloud server (ubuntu).
In Program.cs, line 25 and line 26 will not be executed, but is crucial to the occurence of the bug.
Try to change or delete line 25 and 26, output will be different. (which is confusing). Remove either of line 25 or 26, the stacktrace will show the line number.

**Comment by mthalman** [comment]
I believe this is because your Dockerfile is configured to build the project with the Release configuration.  This behavior would be expected in that case.  If you were to build your app locally on your PC (without using Docker) and specify the Release configuration, you'd get the same behavior.  You can change your Dockerfile to specify Debug for the configuration and you should see the line number information (although this would not be recommended for production scenarios, of course).

**Comment by crucialize** [comment]
@mthalman I just tried what you said and it seem that you are right.
In release mode, only when I set optimize=false, the output is the same as debug mode.
And I will do this to my project, because my program is not cpu-bounded.

Thanks!
