### ISSUE TITLE
Docker RUN dotnet publish -c Release -o /app Could not resolve this reference.

### ISSUE THREAD

**Issue by butterngo** [dotnet/dotnet-docker#1226]
Hi all, 
I'm a newbie, now I am setting a docker image but I can't restore dependencies package for it.
The error massage.
Step 10/15 : RUN dotnet publish -c Release -o /app
 ---> Running in 5dd089087c77
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 37.2 ms for /src/CSharpJWT/CSharpJWT.csproj.
  Restore completed in 41.01 ms for /src/Client1/Client1.csproj.
/usr/share/dotnet/sdk/2.2.301/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.AspNetCore.Authentication.JwtBearer". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/src/CSharpJWT/CSharpJWT.csproj]
/usr/share/dotnet/sdk/2.2.301/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.AspNetCore.Identity". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/src/CSharpJWT/CSharpJWT.csproj]

And this is dockerfile

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src

COPY CSharpJWT/*.csproj ./CSharpJWT/

COPY Client1/*.csproj ./Client1/
RUN dotnet restore "./Client1/Client1.csproj" -s https://api.nuget.org/v3/index.json

COPY . .
WORKDIR /src/Client1
RUN dotnet publish -c Release -o /app

FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Client1.dll"]
Any suggestion for me

**Comment by MichaelSimons** [comment]
@butterngo - Without seeing the source code it is difficult to provide help.  Why is CSharpJWT copied in but not restored?  You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.  Closing as this issue isn't directly related to the microsoft/dotnet image in question.
