### ISSUE TITLE
Nanoserver can not  install vcredist_x64.exe

### ISSUE THREAD

**Issue by wangxin5355** [dotnet/dotnet-docker#1232]
my web api need call c++ dll ，but Nanoserver can not  install vcredist_x64.exe .
and i do not want use windowsservercore ,Because it's too big。
did Nanoserver will Support the installation vcredist_x64.exe  In the future。

**Comment by MichaelSimons** [comment]
This is an issue that is specific to the nanoserver OS base image that the microsoft/dotnet are based on.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
