### ISSUE TITLE
Investigate changing sort order of build matrix

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1240]
Currently jobs that build the runtime end up getting queued to agents before the jobs that build the SDK because of their order in the build matrix.  Because the SDK images end up taking longer, it could end up being beneficial for the total build time if they were queued first.  We should test this hypothesis.

**Comment by MichaelSimons** [comment]
There is not a trivial solution for this and the return/value is not worthwhile.  Additionally, the order the jobs are run in Azure Devops is not deterministic.
