### ISSUE TITLE
How to use custom domain name on local development

### ISSUE THREAD

**Issue by nvcken** [dotnet/dotnet-docker#1246]
## Steps to reproduce the issue
1. Followed by and running on MacOS https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md
2. Enter https://localhost:8001 works fine ( MacOS )

## Expected behavior
Wanna to use custom domain like https://mydomain.local, because need to test with sub domain endpoint https://api.mydomain.local

**Comment by MichaelSimons** [comment]
Closing as this issue isn't directly related to the .NET Docker images themselves.  You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.
