### ISSUE TITLE
Docker image is huge (NuGetFallbackFolder)

### ISSUE THREAD

**Issue by pauldraper** [dotnet/dotnet-docker#1255]
Related to #1108.

mcr.microsoft.com/dotnet/core/sdk images are *HUGE*.

Like, 1.8GB huge. Over three times larger than (for example) OpenJDK docker images.

Most of this is in /usr/share/dotnet/sdk/NuGetFallbackFolder, which has all sorts of stuff: sqlite stuff, ASP.net, Json.NET, Entity Framework.

I can already download this stuff with nuget (and the specific versions I want too). I'd rather have a core SDK image with the essentials that doesn't take half an hour to download.

**Comment by MichaelSimons** [comment]
@pauldraper - this issues has been addressed in 3.0.  See the [3.0 Preview 7 announcement](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/) for details.

**Comment by MichaelSimons** [comment]
Closing as this is fixed in 3.0.  Feel free to continue the discussion.
