### ISSUE TITLE
How to set nuget source user/password?

### ISSUE THREAD

**Issue by jwillmer** [dotnet/dotnet-docker#1265]
I try to interact with nuget inside of the sdk container but I get `/bin/sh: 1: nuget: not found`. How can I interact with nuget?

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 
RUN nuget source Add -Name "Private Feed" -Source ".." -UserName "UserVAR" -Password "PassVAR"
```

**Comment by jwillmer** [comment]
I created a [StackOverflow question](https://stackoverflow.com/questions/57462205/how-to-add-private-nuget-source-in-dotnet-dockerfile/57477426#57477426) to this issue.

**Comment by MichaelSimons** [comment]
@mthalman - we get a number of NuGet/secret questions.  Perhaps there is an opportunity for a sample in this space.  Additionally we should engage with the NuGet folks on what patterns they recommend for Docker usage.

**Comment by mthalman** [comment]
@jwillmer - We've added some recommendations for how to manage private NuGet feed credentials in Docker scenarios at https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/nuget-credentials.md.  Let us know if this meets your needs.
