### ISSUE TITLE
Can we optimize download speed in mainland China

### ISSUE THREAD

**Issue by ZhangGaoxing** [dotnet/dotnet-docker#1269]
## Steps to reproduce the issue

Every time I pull a image from `mcr.microsoft.com`, the speed is very slow(about 200k/s). It's painful
 ☹. Other products download speed of .NET are normal, such as direct from .NET homepage download installation package.

**Comment by MichaelSimons** [comment]
Moved issue to https://github.com/microsoft/containerregistry/issues/7.
