### ISSUE TITLE
Remove Windows Server Core images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#127]
Nano Server is the optimal Windows container environment to develop, test and run .NET Core applications within.  Windows Server Core on the other hand targets full framework .NET applications.  It makes sense that we help guide users to the container environment that will provide them the best .NET Core experience.  In an effort to support this, the Windows Server Core images should be dropped.

**Comment by richlander** [comment]
See: https://github.com/dotnet/dotnet-docker/pull/128
