### ISSUE TITLE
The tags listed on docker hub do not exist

### ISSUE THREAD

**Issue by adragoset** [dotnet/dotnet-docker#1278]
https://hub.docker.com/_/microsoft-dotnet-core-sdk/

Seriously this is really messed up that none of this page is kept up to date and you guys have hidden what tags actually exsist in the repository.

For example:
microsoft/dotnet:2.2-bionic is a not a valid container even though the tag is listed right in the list. 

microsoft/dotnet:2.2.104-sdk thats a tag that doesnt even exist in the list but pulls a container fine. 

How can i actually figure out what tags are real and how to pull linux containers? Why cant i see what tags exist in this repo like ever other docker repository on docker hub?

**Comment by MichaelSimons** [comment]
https://hub.docker.com/_/microsoft-dotnet-core is the _landing page_ of sorts and doesn't list any tags.  What image tags are you looking for - [runtime](https://hub.docker.com/_/microsoft-dotnet-core-runtime/), [aspnet](https://hub.docker.com/_/microsoft-dotnet-core-aspnet/), [sdk](https://hub.docker.com/_/microsoft-dotnet-core-sdk/), etc?  You will need to navigate to the corresponding repo for the type of images you are looking for.

That being said, it looks like you have not migrated to use the mcr.microsoft.com registry.  Try pulling `docker pull mcr.microsoft.com/dotnet/core/sdk:2.2-bionic`  You can read about the microsoft registry at https://github.com/dotnet/announcements/issues/101.

**Comment by MichaelSimons** [comment]
Closing per my previous response.  If there are remaining issues please let us know.

**Comment by ayg-qliktech** [comment]
@MichaelSimons: Hi. I think this issue needs to be reopened. Latest tags aren't reflecting on DockerHub for whatever reason(s). We can see here that last known tag showing is v8.0.203 for example here: https://hub.docker.com/_/microsoft-dotnet-sdk/ when the latest tag available is really v8.0.302: https://github.com/dotnet/dotnet-docker/tree/main/src/sdk/8.0. Perhaps this is an issue from DockerHub side, but we're not seeing this issue with any other base images we use outside of dotnet. Thanks.

**Comment by mthalman** [comment]
There's an existing open issue for this: https://github.com/dotnet/dotnet-docker/issues/5327
