### ISSUE TITLE
It was not possible to find any compatible framework version - alpine3.9 preview 8

### ISSUE THREAD

**Issue by WorldIsM** [dotnet/dotnet-docker#1279]
## Steps to reproduce the issue
1. Build dotnet-docker/3.0/aspnet/alpine3.9/amd64/Dockerfile with preview8 web service
2. Run image

## Expected behavior
Service run successfully

## Actual behavior
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview8-28405-07' was not found.
  - The following frameworks were found:
      3.0.0-preview7-27912-14 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

## Additional information (e.g. issue happens only occasionally)
ls /usr/share/dotnet/shared/Microsoft.NETCore.App

3.0.0-preview7-27912-14

Is it fine that image contains 3.0.0-preview7-27912-14?

BR.

**Comment by mthalman** [comment]
That Dockerfile references `mcr.microsoft.com/dotnet/core/runtime:3.0-alpine3.9` as its base image.  You likely have an older cached version of that base image on your machine.  Be sure to use the `--pull` option when calling `docker build` to ensure you get the latest version of the base image.

**Comment by WorldIsM** [comment]
Thanks
