### ISSUE TITLE
Preview 9 Docker Angular SPA Unable to start Kestrel. 

### ISSUE THREAD

**Issue by AlbertoBonfiglio** [dotnet/dotnet-docker#1296]
## Steps to reproduce the issue
1.Create new dotnet spa angular project with preview 9 (same happens on 8)
2. In VS2019 add Docker support (Linux)
3. Add **/node_modules/ to .dockerignore
4. add :
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - 
RUN apt-get update && apt-get install -y build-essential nodejs
to Dockerfile after Workdir /src in the build environment
5. Build image 
6 Run container:   docker run --rm -it -p 44355:443/tcp -p 8056:80/tcp docktest:latest
## Expected behavior
Application works 

## Actual behavior
Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at docktest.Program.Main(String[] args) in /src/Program.cs:line 17

## Output of `docker version`
Docker version 19.03.2, build 6a30dfc

(paste your output here)
```

## Output of `docker info`
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.0-5-g5b97415-tp-docker)

Server:
 Containers: 22
  Running: 6
  Paused: 0
  Stopped: 16
 Images: 119
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 11.71GiB
 Name: docker-desktop
 ID: 6DRG:KY3J:KDSX:GZUQ:QPCZ:HMFN:WUHW:6H45:XQEQ:WLRZ:IKNB:QFMA
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 65
  Goroutines: 78
  System Time: 2019-09-05T15:48:48.8201549Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by AlbertoBonfiglio** [comment]
Btw if I install the app on Ubuntu 18.04 it works

**Comment by mthalman** [comment]
@AlbertoBonfiglio - Can you provide the full Dockerfile as well?

**Comment by AlbertoBonfiglio** [comment]
Hi, here it is.  passwords and user names are xxx and just for testing. they will be removed later

Dockerfile:

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get update && apt-get install -y build-essential nodejs
COPY ["IdeaBox/IdeaBox.csproj", "IdeaBox/"]
COPY ["Ideabox.EF/Ideabox.EF.csproj", "Ideabox.EF/"]
RUN dotnet restore "IdeaBox/IdeaBox.csproj"
COPY . .
WORKDIR "/src/IdeaBox"
RUN dotnet build "IdeaBox.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "IdeaBox.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

# Install krb5 packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get remove krb5-config krb5-user \
    && apt-get install -y krb5-config krb5-user samba sssd chrony

# copy configuration files for kerberos
COPY IdeaBox/Docker/krb5.conf /etc/krb5.conf
COPY IdeaBox/Docker/smb.conf /etc/samba/smb.conf
COPY IdeaBox/Docker/chrony.conf /etc/chrony/chrony.conf
COPY IdeaBox/Docker/sssd.conf /etc/sssd/sssd.conf
COPY IdeaBox/Docker/nsswitch.conf /etc/nsswitch.conf
COPY IdeaBox/Docker/hosts /etc/hosts
COPY IdeaBox/Docker/UserName.keytab /app/UserName.keytab

RUN chown root:root /etc/sssd/sssd.conf \
	&& chmod 600 /etc/sssd/sssd.conf

ENV ASPNETCORE_URLS="https://+http://+:"
ENV ASPNETCORE_HTTPS_PORT=5001
ENV ASPNETCORE_Kestrel__Certificates__Default__Password="xxx"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path="bee-selfsigned.pfx"
ENV CONN="Server=172.17.0.3;User Id=xxx;Password=xxx;Database=xxx"

COPY IdeaBox/Docker/launch.sh /launch.sh
#ENTRYPOINT /launch.sh
ENTRYPOINT ["dotnet", "IdeaBox.dll"]

**Comment by AlbertoBonfiglio** [comment]
Well after 2 days I figured out it's not an issue of docker. The issue is in the aspnetcore or kestrel, as if instead of passing the environment variables ASPNETCORE_URLS="https://+http://+:" I configure kestrel using appsettings..json like this 
 "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://*:6000"
      },

      "HttpsInlineCertFile": {
        "Url": "https://*:443",
        "Certificate": {
          "Path": "./cert.pfx",
          "Password": "xxxx",
          "AllowInvalid": "true"
        }
      }
    },

    "Certificates": {
      "Default": {
        "Path": "./cert.pfx",
        "Password": "xxxx"
      }
    }
  },
it works. 

So I guess we can close this? Or can we link it to the kestrel or aspnetcore github issues?

**Comment by MichaelSimons** [comment]
@AlbertoBonfiglio - please open a kestrel/aspnetcore specific issue for the issue you discovered.
