### ISSUE TITLE
Docker build starts to produce error.

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/dotnet-docker#1303]
## Steps to reproduce the issue
Hi, I have the following dockerfile: https://github.com/Squidex/squidex/blob/master/Dockerfile

The build is based on the following file: https://github.com/Squidex/squidex/blob/master/libs/Dockerfile

So basically I use the following images

* microsoft/dotnet:2.2-sdk for Build
* microsoft/dotnet:2.2-runtime-deps-alpine for running

It is working fine and was working fine for a long time. This weekend I have produced a last stable version of my product and since then I have only made minor changes in Javascript files. I have not updated any dependencies.

But when I start the latest dev build from yesterday I see the following error in the logs:

"no usable version of the libssl was found"

In my build server logs I have seen messages about Mounted the first time:

```
The push refers to repository [docker.io/squidex/squidex]
--
1394 | a1f15a8c57f8: Preparing
1395 | 1177af4ec384: Preparing
1396 | 88870e88422b: Preparing
1397 | a96b0f202d31: Preparing
1398 | f1b5933fe4b5: Preparing
1399 | f1b5933fe4b5: Mounted from microsoft/dotnet
1400 | a96b0f202d31: Mounted from microsoft/dotnet
1401 | 88870e88422b: Pushed
1402 | 1177af4ec384: Pushed
1403 | a1f15a8c57f8: Pushed
```

I have no clue what happened but it seems that the wrong layers get referenced or so.

UPDATE: When I run `apk info` it shows my libssl1.1, but the dockerfile of `microsoft/dotnet:2.2-runtime-deps-alpine` shows that libssl1.0 should be installed:

> docker run --entrypoint "apk"  microsoft/dotnet:2.2-runtime-deps-alpine -a info

## Expected behavior
The built error should run.

## Actual behavior

See above

## Output of `docker version`

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701GiB
Name: build
ID: 3QSW:T2XB:XV7M:IRBG:4H5B:LTWK:KUBG:QO2K:2KNY:BPFB:3XMX:TBDC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mthalman** [comment]
This is likely because yesterday, the shared tag for 2.2 on Alpine has moved to 3.9 from 3.8 which has a different version of libssl.  To workaround your incompatibility with libssl1.1, you can explicitly target Alpine 3.8 by using these tags:
```
mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.8
mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.8
```

**Comment by MichaelSimons** [comment]
.NET Core is capable of working with either libssl1.0 or libssl1.1.  In 2.* it will try to load 1.0 and if not found it will fallback to 1.1.  When running on alpine 3.9 .NET will use libssl1.1. see https://github.com/dotnet/corefx/blob/release/2.2/src/Native/Unix/System.Security.Cryptography.Native/opensslshim.cpp#L34 for details.

Have you validated that a third party component you have a dependency is not requiring libssl1.0?

On an unrelated topic, I noticed that you are publishing with the following rid - `alpine.3.7-x64` (https://github.com/Squidex/squidex/blob/master/Dockerfile#L40).  If you are running with alpine 3.8 or 3.9, this could cause issues.

**Comment by SebastianStehle** [comment]
Hard to tell which of the dependencies might have a problem with libssl, because I do not get a stacktrace or so. I have not validated it manually yet. Perhaps IdentityServer.

Thanks for pointing to me to the problem with the alpine version.

**Comment by SebastianStehle** [comment]
Good question, but it is still 2.2. I think I get confused with all this versions. Considering that 3.0 will land soon I would just try out the @mthalman

**Comment by MichaelSimons** [comment]
I modified your app to remove the RuntimeFrameworkVersion property and to use the latest SDK version and I no longer saw the libssl issue.  Closing as this appears to be app specific.  Feel free to continue the conversation and re-open if you see it is an issue with the .NET Core image.
