### ISSUE TITLE
Include digest, git hash, and Dockerfile on hub.docker.com (or some other trusted location).

### ISSUE THREAD

**Issue by MicahZoltu** [dotnet/dotnet-docker#1308]
## Steps to reproduce the issue
1. Build a piece of software with strict security requirements for deterministic and trusted builds.
1. Go to https://hub.docker.com/_/microsoft-dotnet-core-sdk/ to get the digest for the latest stable tag.
1. Notice that no digests are listed since the normal Docker Hub UI isn't utilized (which does include digests).
1. Also notice that you cannot see the exact Dockerfile that was used for a particular build/version like you can on Docker Hub normally.
1. Be paranoid enough to not trust that the image you get redirected to when you pull `2.2` is in fact a trusted image build built from a Dockerfile that you have personally audited.
1. Be sad and go build the image from scratch instead so you can get a trusted digest.

## Expected behavior
A digest is published (and ideally verified/automatically checked) when new images are published.  It would be great if this digest was posted in multiple locations for security.

## Actual behavior
No image digests are posted anywhere that is readily accessible.
No Dockerfiles are published and connected to the builds that go out (have to sift through git and hope you can find the exact commit hash that resulted in the build).

## Additional information (e.g. issue happens only occasionally)
This problem started with the migration to MCR, which made it so images were no longer published to docker hub which has this functionality built-in.

----

There is a tug of war between doing everything manually (e.g., building docker images from scratch by hand all the way up the chain) and UX simplicity of trusting certain actors in certain ways.  At the moment, the lack of published digests, git commit hashes, and Dockerfiles for images published to MCR makes it so using the dotnet docker images requires notably more trust than should be necessary.  Instead of just having to trust Microsoft's build process, I also need to trust that the registry is feeding me a trustfully built image, and that the Dockerfile used by the build system to build/publish the release was in fact a legitimate Dockerfile.

If Microsoft were to publish the digest, git commit hash, and Dockerfile then auditors would be able to verify that the digest matches the Dockerfile and source code used to build the image, and users could reduce their trust network to line involving the page publishing the digest.  If the digest is published in multiple places then the paranoid user could verify the digest on both sources to further reduce their trust requirements.

**Comment by MicahZoltu** [comment]
It is worth noting that the Dockerfile currently linked on hub.docker.com doesn't link to a specific git commit, it links to `master` branch, which is mutable (and is updated regularly).  This makes the link useful for eyeballing what is probably in the associated image, but it isn't useful from an auditing perspective.

**Comment by MichaelSimons** [comment]
@MicahZoltu - thanks for providing this feedback.  It has been something on our radar as of recent.  We are using #212 to track this work.
