### ISSUE TITLE
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

### ISSUE THREAD

**Issue by sanjaykulkarni04** [dotnet/dotnet-docker#1309]
Steps to reproduce the issue
1. Create a default docker file created by visual studio 2019 for Linux container
2. Add "RUN dotnet test" command (dot net CLI command to run all unit tests inside docker container) in the docker file.
3. Right-click on DockerFile and select "Build docker image" option in visual studio 2019
4. Getting error - **_MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file._**

**Below is the docker file - **

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["LinedataAnalytics/LinedataAnalytics.csproj", "LinedataAnalytics/"]
RUN dotnet restore "LinedataAnalytics/LinedataAnalytics.csproj"
COPY . .
WORKDIR "/src/LinedataAnalytics"
RUN dotnet build "LinedataAnalytics.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "LinedataAnalytics.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

WORKDIR /app
RUN dotnet test

**Comment by MichaelSimons** [comment]
@sanjaykulkarni04, I see you added `RUN dotnet test` within the final stage of your Dockerfile.  The final stage doesn't appear to contain any of your source code as you are only copying your published app into it.  If you are looking to run your unit tests as part of your Docker build, I would suggest moving the `RUN dotnet test` line immediately after you build the project e.g. `RUN dotnet build "LinedataAnalytics.csproj" -c Release -o /app`.  Alternatively you could create a separate phase for running the tests.  Refer do the [.NET Core Docker Samples](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile) for how to do this.

Closing as this isn't an issue with the .NET Core image.  For usage questions like this, you might have better luck getting support on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.

**Comment by sanjaykulkarni04** [comment]
Thanks, @MichaelSimons 

one more assistance requires, how to run the unit test into multiple containers(run in parallel) by segregating test suites (tests)?

**Comment by MichaelSimons** [comment]
That's a good question for [StackOverflow](https://stackoverflow.com/).  My initial reaction is that doesn't feel natural to do as part of a `docker build`.  You may have better luck utilizing an orchestrator and running multiple containers via `docker run`.

**Comment by sanjaykulkarni04** [comment]
Thanks again, will do research on it.

**Comment by avneet-01** [comment]
@MichaelSimons @sanjaykulkarni04 Were you able to come to a solution? I'm also getting this error when I try to install edge-js on my Azure VM Ubuntu 20.4. I installed and tried with Dotnet SDK 3.1, 5 & 6 as well still problem persists. Please have a look at the error image:

![image](https://user-images.githubusercontent.com/74612853/146067583-13ba4ddf-49f3-47b1-baa2-895ccaabb957.png)
