### ISSUE TITLE
Remove tzdata package from Alpine-based runtime-deps images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1311]
In order to maintain consistency among the `runtime-deps` images, we've decided that none of the `runtime-deps` images should have the `tzdata` package installed.  This package is currently installed in the Alpine images and should be removed.  Consumers of these images that need to call into the `TimeZoneInfo` API will need to explicitly install the `tzdata` package in their own Dockerfile.

**Comment by MichaelSimons** [comment]
This change should be made to all new .NET versions going forward.  Making this change to previous versions such as 2.1 and 2.2 would be considered a breaking change.

**Comment by MichaelSimons** [comment]
Related to #1264
