### ISSUE TITLE
Download from dotnetcli.azureedge.net URL instead of blob storage

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1317]
The dotnet-install script installs .NET from dotnetcli.azureedge.net whereas the Dockerfiles install bits from dotnetcli.blob.core.windows.net.  The Dockerfiles should be updated to target dotnetcli.azureedge.net.

**Comment by MichaelSimons** [comment]
We should validate what the best practice is for using a CDN backed storage account.

**Comment by mthalman** [comment]
Confirmed that dotnetcli.azureedge.net is the CDN-backed host and dotnetcli.blob.core.windows.net is the uncached one.

**Comment by mthalman** [comment]
Finished roll out with https://github.com/dotnet/dotnet-docker/pull/1473
