### ISSUE TITLE
Tags are not listed on docker hub

### ISSUE THREAD

**Issue by tboby** [dotnet/dotnet-docker#1335]
I wanted to migrate my CI to use .NET Core 3.0, but discovered there is no complete listing of tags on the docker hub page: https://hub.docker.com/_/microsoft-dotnet-core-sdk/

There seems to be a markdown table containing at least some of the builds, but the "Tags" tab of the page doesn't seem to exist. E.g. https://hub.docker.com/_/python?tab=tags

An example of an undocumented tag is `3.0`.

Is there a reason the proper tag page isn't used?

Edit: just noticed there's a link to a json file with all the tags, but 3.0 is still missing from the documentation page, which seems like a process problem!

**Comment by MichaelSimons** [comment]
@tboby - the markdown table does include all of the currently supported tags. `3.0` is listed there.  It is included in multiple section because it is a multi-platform tag.

![image](https://user-images.githubusercontent.com/8290530/65529152-3cb11680-debb-11e9-956f-fe9061931956.png)
