### ISSUE TITLE
.NET Core `latest` Docker tags updated to 3.0

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#1337]
# .NET Core `latest` Docker tags updated to 3.0

The `latest` tags for the [dotnet/core](https://hub.docker.com/_/microsoft-dotnet-core) repos have been updated to reference [.NET Core 3.0](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/).

## Details

* [dotnet-docker#1334](https://github.com/dotnet/dotnet-docker/pull/1334)

The `latest` tags for the [dotnet/core](https://hub.docker.com/_/microsoft-dotnet-core) repos are always intended to reference the latest supported version of .NET Core. At this time, the latest supported version is .NET Core 3.0.

The following Docker repos have been updated:

* [dotnet/core/sdk](https://hub.docker.com/_/microsoft-dotnet-core-sdk)
* [dotnet/core/aspnet](https://hub.docker.com/_/microsoft-dotnet-core-aspnet)
* [dotnet/core/runtime](https://hub.docker.com/_/microsoft-dotnet-core-runtime)
* [dotnet/core/runtime-deps](https://hub.docker.com/_/microsoft-dotnet-core-runtime-deps)
* [dotnet/core/samples](https://hub.docker.com/_/microsoft-dotnet-core-samples)

It is recommended to use a more-specific tag than `latest` for anything other than casual development. Once you have an application that you believe will eventually go to production, you are recommended to use a tag like `3.0`. The [.NET Core Docker Samples](https://github.com/dotnet/dotnet-docker/tree/master/samples) contain examples of more specific usage such as the [.NET Core console sample](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile).

**Comment by GraemeF** [comment]
I'm finding that I with tag `mcr.microsoft.com/dotnet/core/sdk:3.0` am getting image 4e9e8dec2900 and the following output:

```
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
```

The `DOTNET_SDK_VERSION` env var is set to `3.0.100-preview7-012821` in this image.

With tag `mcr.microsoft.com/dotnet/core/sdk:3.0.100` I am getting image 4422e7fb740c and a non-preview version of msbuild:

```
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

Looks like the sdk tag for 3.0 isn't updated properly.

**Comment by MichaelSimons** [comment]
Closing announcement but please feel free to discuss.
