### ISSUE TITLE
pwsh not executable by non-root users

### ISSUE THREAD

**Issue by robmccready** [dotnet/dotnet-docker#1340]
## Steps to reproduce the issue
1. Launch container as non-root user: 
    docker run -it -u 123:123 mcr.microsoft.com/dotnet/core/sdk:3.0
2. Inside container attempt to launch pwsh
3. bash: /usr/bin/pwsh: Permission denied
4. ls -al /usr/share/powershell shows permissions on pwsh
    -rwxr--r-- 1 root root 86584 Sep 23 15:06 pwsh

## Expected behavior
pwsh should be executable by non-root user. Jenkins passes the jenkins user to docker which forces a non-root user.

## Actual behavior
pwsh permission denied 

## Work around
I created my own image inheriting from mcr.microsoft.com/dotnet/core/sdk:3.0 with
   RUN chmod 755 /usr/share/powershell/pwsh

**Comment by MichaelSimons** [comment]
@adityapatwardhan - This seems like something we should fix.  Is this something you can create a PR for?

**Comment by robmccready** [comment]
I looked at two of the docker files and it looks like the powershell download/install is consistent in each so I think I should be able to put a PR together in the next few days.

**Comment by MichaelSimons** [comment]
@robmccready - If you make a PR, please make it against the nightly branch.

**Comment by mthalman** [comment]
Finished roll out with https://github.com/dotnet/dotnet-docker/pull/1473
