### ISSUE TITLE
Default execution of build-and-test.ps1 overwrites local changes with docker hub images

### ISSUE THREAD

**Issue by robmccready** [dotnet/dotnet-docker#1346]
## Steps to reproduce the issue
1. Download clean nightly branch
2. Make change to a Dockerfile (e.g. 3.0\sdk\buster\amd64)
3. Run build-and-test.ps1

## Expected behavior
By default the execution build-and-test.ps1 should execute tests against local builds of images.

## Actual behavior
The default behavior does not pass $IsLocalRun = $true to ./tests/run-tests.ps1 which causes the test application to run "docker pull" on images during execution of tests. This overwrites the local changes image causing tests to fail.

TestResults TRX file will have "Executing: docker pull mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-buster" in the log

docker images mcr.microsoft.com/dotnet/core-nightly/sdk will shows that 3.0-buster is now a different image than the locally built 3.0, 3.0.100, 3.0.100-buster, and latest images.

This drove me nuts while working on [Bug 1340](https://github.com/dotnet/dotnet-docker/issues/1340)

## Workaround 
Separate the build and test calls to pass necessary parameters to not pull down images during testing

.\build-and-test.ps1 -SkipTesting:$true
cd .\tests
.\run-tests.ps1 -IsLocalRun:$true

## Fix
* Add IsLocalRun parameter to build-and-test.ps1 defaulting to $true
  * pass IsLocalRun parameter to call to .\eng\common\build-and-test.ps1
* Add IsLocalRun parameter to .\eng\common\build-and-test.ps1 defaulting to $true
  * pass IsLocalRun parameter to .\test\run-tests.ps1
* Add default $true to IsLocalRun parameter to .\tests\run-tests.ps1

I can put together a PR if this sounds correct.

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/dotnet-docker/pull/1357
