### ISSUE TITLE
Request to create generic docker install script

### ISSUE THREAD

**Issue by ptr727** [dotnet/dotnet-docker#1356]
I am trying to create a docker image that adds DotNet Core SDK 3 to a code-server container allowing container based VS Code and DotNet Core 3 Linux development.
See:
https://github.com/cdr/code-server/blob/master/Dockerfile
https://github.com/linuxserver/docker-code-server/blob/master/Dockerfile

There is the very convenient dotnet core install script for Linux:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
But this script does not install prerequisites, nor does it register dotnet for use in a container, it performs a local install.

It would be great if any container creator can simply call the same script to ensure that any docker environment has dotnet core correctly installed.
See: https://github.com/dotnet/dotnet-docker/blob/master/3.0/sdk/bionic/amd64/Dockerfile

If such a script can be created the dockerfile will be greatly simplified, and installation steps can be consolidated into a single install script.

(Same goes for installing PS in docker and linux)

**Comment by MichaelSimons** [comment]
@ptr727 - Have you considered installing dotnet via a package manager?  Is this feasible in your situation?  It seems like this would solve some or most of your issues.

One reason the .NET Core Dockerfiles don't make use of an installation script such as `dotnet-install` is to provide clarity in what is installed.  The .NET Core Dockerfiles try to adhere to the Dockerfile best practices and guidelines Docker uses within the official repositories.  See their [guidelines](https://github.com/docker-library/official-images#clarity) on clarity.

We don't plan on changing the .NET Core Dockerfiles to utilize an installation script.

**Comment by ptr727** [comment]
I read the best practices link, but I don't think it encourages duplicating complicated scripts, when all uses of said script need to be updated when the "master" changes, else all other uses may break, basic principles of re-use.

I did end up installing using a package manager, but this means I need to know the base OS, so that I can register the correct Msft repository. When the base image changes, I again need to update my script to include the correct repository. It also means I cannot install pre-releases until they make it to a repository, which often never happens.

A master docker install script, similar to the vanilla install script, that detects the OS, and installs the correct artifacts including pre-releases would be more robust.

So I disagree with your reasoning, but accept your answer.

**Comment by MichaelSimons** [comment]
I don't disagree that the install script you propose would be more robust.  The mindset we take however is to produce Docker images that are transparent in what they contain.  This in my opinion is spirit of the clarity guideline I referenced earlier.  If a customer runs `docker history mcr.microsoft.com/dotnet/core/runtime:3.0` they should be able to get a clear understanding of what is contained within the image.  If an installation script is utilized, the user will not get this clarify when running `docker history`.  So in essence we are doing more work on the production side to provide a better experience for the image consumer.  The consequence of this is inconvenience for users such as yourself who want to mimic what we are doing within your own Dockerfiles.
