### ISSUE TITLE
No access to core containers

### ISSUE THREAD

**Issue by zorgoz** [dotnet/dotnet-docker#136]
## Steps to reproduce the issue
0. Environment: Windows 2016 with container feature enabled
1. Create Dockerfile 
2. Add FROM microsoft/1.0-nanoserver-core or any other except bare nanoserver
3. Issue docker build command

## Expected behavior
The container is pulled if necessary.

## Actual behavior
Process fails with: `unauthorized: authentication required `

## Additional information (e.g. issue happens only occasionally)
Bare microsoft/naonserver base OS image is downloaded and used correctly, but that has no dnet core on board.

## Output of `docker version`
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

## Output of `docker info`
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 5
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 2 GiB
Name: WIN-I2T6RG3UFC7
ID: IVGX:3OBZ:RYBB:N6CM:2F65:PZ22:EDC7:4Z22:BDQM:BJNX:BHHI:DSFD
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MichaelSimons** [comment]
@zorgoz - In step 3 of your repro, when you say "any other except bare nanoserver" does that mean any other microsoft/dotnet image or any other image outside of microsoft/dotnet?  This doesn't appear to be a microsoft/dotnet image specific issue which is why I ask.

**Comment by zorgoz** [comment]
@MichaelSimons - I have tried only some from those built for Debian (they are accessible, but they fail because of the platform). So what I meant was any other microsoft/dotnet image based on nanoserver is failing with this authentication error.

**Comment by zorgoz** [comment]
My mistake. I made a syntax error, i have used the tag as image name. It is interesting trough, that Debian based ones behaved differently.
