### ISSUE TITLE
Create a migration guide for 2.x -> 3.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1363]
We can use this to document any Docker-specific notes for the migration.

Examples:

- [x] The exclusion of the tzdata package in Alpine: https://github.com/dotnet/dotnet-docker/issues/1264#issuecomment-537563565
- [ ] The removal of ASPNETCORE_URLS environment variable in SDK images: https://github.com/dotnet/dotnet-docker/issues/1199

**Comment by MichaelSimons** [comment]
This feels like something that would be best covered with an _announcement_.

**Comment by mthalman** [comment]
tzdata announcement: https://github.com/dotnet/dotnet-docker/issues/1366

**Comment by MichaelSimons** [comment]
Closing as 3.0 has been out for some time and there have been no reported issues with the ASPNETCORE_URLS change.
