### ISSUE TITLE
怎么查看日志

### ISSUE THREAD

**Issue by Linshiqi** [dotnet/dotnet-docker#1364]
按照安装过程启动，没发现报什么错，但是没有修改到阿里云上的解析记录，在哪里查看详细启动日志

**Comment by MichaelSimons** [comment]
@Linshiqi - I do not understand which logs you are asking about.  Can you provide more information?  It would be more helpful if you included the exact steps to reproduce the issue.

**Comment by Linshiqi** [comment]
Sorry, my bad, I was asking other repo issue, this will be closed.
