### ISSUE TITLE
docker images for dotnet 3.0 does not have netcoreapp3.0 support

### ISSUE THREAD

**Issue by brainbug89** [dotnet/dotnet-docker#1375]
I get an error message when trying to run `donet restore` in a Dockerfile with base image **microsoft/dotnet:3.0-sdk**.

Initially created here: https://github.com/aspnet/EntityFrameworkCore/issues/18057

## Steps to reproduce the issue
`docker build .` with Dockerfile:
```
FROM microsoft/dotnet:3.0-sdk AS build
WORKDIR /src
COPY ["", "CoreProject/"]
RUN dotnet restore "CoreProject/CoreProject.csproj"
```

## Expected behavior
Build runs without errors.

## Actual behavior
Error message:
```
error NU1202: Package Microsoft.EntityFrameworkCore 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.EntityFrameworkCore 3.0.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)
```

## Additional information (e.g. issue happens only occasionally)
EF Core version: 3.0.0
Target framework: .NET Core 3.0
Operating system: microsoft/dotnet:3.0-sdk

## Output of `docker version`

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 57
 Running: 1
 Paused: 0
 Stopped: 56
Images: 357
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.0.0-29-generic
Operating System: Ubuntu 19.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.764GiB
Name: 49103551v02
ID: IQRS:NCOX:RPJ5:S4X4:B77W:LE3C:4ZEP:R6ZI:ABSH:IV2J:36IK:IPOU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by mthalman** [comment]
The `microsoft/dotnet:3.0-sdk` image tag is pointing to an early preview of 3.0 that is no longer supported.  See [this announcement](https://github.com/dotnet/announcements/issues/101) about the migration of Docker tags to MCR.  Note that the 2.x tags that existed on Docker Hub are still being maintained with the latest updates, just not the 3.0 tags in this case.  You'll want to update your tag references to the new MCR location.  In this case, `microsoft/dotnet:3.0-sdk` should be updated to `mcr.microsoft.com/dotnet/core/sdk:3.0`.  You can find all the current tags on [Docker Hub](https://hub.docker.com/_/microsoft-dotnet-core/).

**Comment by MichaelSimons** [comment]
Closing, please pull the images from mcr.microsoft.com
