### ISSUE TITLE
POWERSHELL_DISTRIBUTION_CHANNEL env var is not set correctly in the Windows SDK images.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#1402]
The POWERSHELL_DISTRIBUTION_CHANNEL env variable is set in the builder image when it should be set in the sdk image.  I believe the result of this is that the PowerShell telemetry is not logging a distribution channel.

**Comment by MichaelSimons** [comment]
@daxian-dbw, @adityapatwardhan - Can one of address this?  This should be fixed in the 3.1 images of the nightly branch.  This does not meet the servicing bar for 3.0

**Comment by MichaelSimons** [comment]
@adityapatwardhan - Is this something that could get fixed soon so that it makes it into the `3.1 preview 2` release?

**Comment by mthalman** [comment]
This will be made available in the 3.1 preview 3 release.
