### ISSUE TITLE
Fail to start global tool on windowsservercore-1803

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/dotnet-docker#1410]
My gitlab pipeline uses the following docker image:

> mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1803

in my pipeline i install .net core with the recommended command:

> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1')))"

I register the  global tools folder in the path variable

> $Env:path += $Env:UserProfile +"/.dotnet/tools/;"

I install my global tool:

> dotnet tool install -g buildcli

I start the tool:

> buildcli build

I get the following error message:

>  Invalid runtimeconfig.json 

The tool is built with the following msbuild settings:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--<TargetFrameworks>netcoreapp3.0;netcoreapp2.2;netcoreapp2.1</TargetFrameworks>-->
    <TargetFrameworks>netcoreapp2.2;netcoreapp2.1;netcoreapp3.0</TargetFrameworks>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>buildcli</ToolCommandName>
    <!--<PackageId>buildcli</PackageId>-->
    <PackageTags>TagA TagB</PackageTags>
    <!--<Version Condition="'$(Version)' == ''">1.0.0001</Version>-->
  </PropertyGroup>

```

on the Alpine .net core sdk docker image it works without any issues.

**Comment by TFTomSun** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--<TargetFrameworks>netcoreapp3.0;netcoreapp2.2;netcoreapp2.1</TargetFrameworks>-->
    <TargetFrameworks>netcoreapp2.2;netcoreapp2.1;netcoreapp3.0</TargetFrameworks>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>buildcli</ToolCommandName>
    <!--<PackageId>buildcli</PackageId>-->
    <PackageTags>TagA TagB</PackageTags>
    <!--<Version Condition="'$(Version)' == ''">1.0.0001</Version>-->
  </PropertyGroup>

```

**Comment by MichaelSimons** [comment]
What does the runtimeconfig.json file look like for the `buildcli` global tool?  What args are you passing into the `dotnet-install.ps1` when you invoke it?  

In case you didn't know, the .NET FX SDK images already contain a copy of the .NET Core SDK.

```
>docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1803 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by TFTomSun** [comment]
@MichaelSimons 

Thanks for the hint that .net core was already installed. I removed the installation, but the problem still persists.

The runtimeconfig.json looks like:

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.0.0"
    }
  }
}
```

On Windows 10 and Alpine Linux the tool works.

**Comment by TFTomSun** [comment]
I think i figured out the problem. The actual package id of the tool is very long. Because of the global tools folder structure and .net core build output structure, it lead to very long file names. With a short package id, the tool works. Would be good, if the error message would be more useful. And maybe overthinking the folder structures might make sense too.

**Comment by MichaelSimons** [comment]
Closing as this is not an issue specific to the .NET Core Docker images.  @TFTomSun - please, consider following up with the https://github.com/dotnet/sdk repo on improving the user experience for this long file name scenario.
