### ISSUE TITLE
FSI fails to start

### ISSUE THREAD

**Issue by basvdlinden** [dotnet/dotnet-docker#1433]
## Steps to reproduce the issue
1. `docker run --rm -it mcr.microsoft.com/dotnet/core/sdk:latest`
2. `dotnet fsi`

## Expected behavior
Able to use fsi

## Actual behavior
`Unhandled exception. System.PlatformNotSupportedException: The system does not support the STA thread apartment.`

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:55:51 2019
  OS/Arch:          windows/amd64
  Experimental:     false```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.449)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.95GiB
 Name: Black
 ID: ZD6S:MG2G:LMPS:FI4Q:PGAX:PJJ2:CG5B:5YN6:RDUC:AM4E:MJC5:3MGM
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2019-11-02T20:57:47.439352+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
I wonder if this is related to https://github.com/dotnet/coreclr/issues/26947.  I know that's VB but it could be the same underlying cause.

**Comment by MichaelSimons** [comment]
Setting `COREHOST_TRACE=1` indicates the failure is coming from the fsharp fsi.exe.  Moving to the fsharp repo.

A workaround would be to use a Windows Server Core based image.  The .NET Framework Docker SDK images include the .NET Core SDK and may be a suitable substitute for you - e.g. `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1903`

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/fsharp #7813](https://github.com/dotnet/fsharp/issues/7813) via [**ZenHub**](https://www.zenhub.com/)
