### ISSUE TITLE
dotnet/core/sdk:3.0 fails to build sourcecode containing regional characters (even if they are considered unicode characters)

### ISSUE THREAD

**Issue by moanrose** [dotnet/dotnet-docker#1445]
## Steps to reproduce the issue
1. Create a multi project solution with web api project, and class library project
2. Add project reference to class library project from web api project
2. Add docker support
3. Make sourcecode in Startup.cs containing regional character - in my case it is æ,ø, å
4. From the solution folder issue the command `docker build -f webapi/Dockerfile -t webapi:stable .`

## Expected behavior
According the the C# language specification, it should be possible to use unicode characters in classnames, namespaces etc. - Therefore i would expect the project to compile, and the docker image to be built.

## Actual behavior

During the build step `RUN dotnet build "webapi.csproj" -c Release -o /app/build`  i recieve the following errors:

Startup.cs(29,37): error CS1002: ; expected [/src/webapi/webapi.csproj]
Startup.cs(29,37): error CS1056: Unexpected character '�' [/src/webapi/webapi.csproj]
Startup.cs(29,52): error CS1002: ; expected [/src/webapi/webapi.csproj]
Startup.cs(29,52): error CS1513: } expected [/src/webapi/webapi.csproj]
Startup.cs(29,55): error CS1002: ; expected [/src/webapi/webapi.csproj]
Startup.cs(29,55): error CS1056: Unexpected character '�' [/src/webapi/webapi.csproj]
Startup.cs(29,72): error CS1525: Invalid expression term ')' [/src/webapi/webapi.csproj]

If i remove all regional characters from the sourcecode, i can build the docker image without problems.

## Additional information (e.g. issue happens only occasionally)

if I issue the the same build command `dotnet build "webapi.csproj" -c Release -o /app/build` outside docker (powershell) the project compiles just fine

### This is my Dockerfile

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["webapi/webapi.csproj", "webapi/"]
COPY ["classlibrary/classlibrary.csproj", "classlibrary/"]
RUN dotnet restore "webapi/webapi.csproj"
COPY . .
WORKDIR "/src/webapi"
RUN dotnet build "webapi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "webapi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "webapi.dll"]
```

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 53
  Running: 45
  Paused: 0
  Stopped: 8
 Images: 68
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 4.833GiB
 Name: docker-desktop
 ID: RPBZ:QRO5:75EF:VVFH:L7C4:UJS4:LS6L:OSLG:EU27:M4K7:4SDX:P2CL
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 175
  Goroutines: 155
  System Time: 2019-11-06T12:27:49.6999704Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
@moanrose - Can you please share your source that reproduces the issue or include a set of concrete repro steps?  I quickly tried reproducing this and was not able to.

**Program.cs**
```
using System;

namespace æøå
{
    class æøå
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            string æøå = "hi";
            Console.WriteLine(æøå);
        }
    }
}
```

**Dockerfile**
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "issue-1445.dll"]
```

**Comment by moanrose** [comment]
Hi Michael

My code must have been created/scaffolded in some funky encoding other than UTF-8, because when i looked at the projects in question today, in order to reproduce the issue - my regional characters were all garbled. After changing the regional characters to ther "un-garbled" equivalent, i were able to build the docker images using the dotnet/core/sdk:3.0 image

I apologize for the inconvenience

**Comment by JamelKalai** [comment]
@moanrose how did you solved i have same issue in windows container !?
