### ISSUE TITLE
Cannot create Bitmap from stream inside Alpine-based dotnet image

### ISSUE THREAD

**Issue by FrameBassman** [dotnet/dotnet-docker#1465]
## Steps to reproduce the issue
1. Clone https://github.com/framebassman/BlobContentType repository 
`git clone git@github.com:FrameBassman/BlobContentType.git`
2. Run application
`make start-test`
3. Make sure the app is running
`bash ./Scripts/wait-until-service-is-up.sh`
4. Run test
`dotnet test BlobContentType.Test`

## Expected behavior
Application should not throw an exception. Test should pass

## Actual behavior
Test fails. The following code:
```
var imageUrl = "https://barcode.tec-it.com/barcode.ashx?data=ABC-abc-1234&code=Code128&dpi=96";
using(var input = await _client.GetStreamAsync(imageUrl)) 
{
 _log.LogWarning("Inside input");
 using(var memory = new MemoryStream())
 {
  _log.LogWarning("Inside memory");
  var bitmap = new Bitmap(input);
 }
}
```
throws the following exception
```
warn: BlobContentType.Web.Controllers.PictureController[0]
      Inside input
warn: BlobContentType.Web.Controllers.PictureController[0]
      Inside memory
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLR8REHR5AL4", Request id "0HLR8REHR5AL4:00000001": An unhandled exception was thrown by the application.
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Bitmap..ctor(Stream stream)
   at BlobContentType.Web.Controllers.PictureController.Index() in /app/Controllers/PictureController.cs:line 34
...
```

## Additional information (e.g. issue happens only occasionally)
I have install the following libraries inside alpine-based container
```
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update \
    && apk add \
        libgdiplus
```

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 292
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-35-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.28GiB
 Name: cs-ws174380
 ID: JROJ:UOIZ:XFEN:V26K:IA6A:IKXG:XVRZ:T2AZ:MN2N:IXAJ:SYRN:6KC6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: framebassman
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by mthalman** [comment]
When using the `System.Drawing.Common` package, you require some additional native dependencies to be installed.  See https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/using-system-drawing-common.md for more details.  Please re-open if this doesn't address your problem.

**Comment by FrameBassman** [comment]
Unfortunately, I have installed `libgdiplus` library (see issue description) but nothing changes
@mthalman Seems, that I have not rights to re-open this issue. Could you do it?

**Comment by mthalman** [comment]
Potentially related to https://github.com/dotnet/corefx/issues/41527, although this only seems to repro in a Docker container.  It seems to be specific to the image type.  The repro project attempts to access a GIF which causes the exception.  But after changing it to access a JPEG URL, it works.

**Comment by FrameBassman** [comment]
I just replace 
`https://barcode.tec-it.com/barcode.ashx?data=ABC-abc-1234&code=Code128&dpi=96`
to
`https://www.scandit.com/wp-content/themes/scandit/barcode-generator.php?symbology=code128&value=213214214&size=200&ec=L`
and it works
Thanks

**Comment by skadenic19** [comment]
Hello,

What if I can't change GIF to JPEG? For example I use external .net library with embedded resource? This resource is GIF. The problem is not solved for me cause I can not change external library.

**Comment by mthalman** [comment]
@skadenic19 - The issue is unrelated to the .NET Docker images.  It's in the .NET runtime.  Please respond to https://github.com/dotnet/corefx/issues/41527 if you think that's related to your issue or log a new issue at https://github.com/dotnet/runtime.
