### ISSUE TITLE
Latest version of the SDK installing 3.0 instead of 3.1

### ISSUE THREAD

**Issue by davidmikh** [dotnet/dotnet-docker#1467]
## Steps to reproduce the issue
1. Create a docker container from an image that installs .NET Core from `mcr.microsoft.com/dotnet/core-nightly/sdk:latest`

## Expected behavior
The latest version of .NET Core (3.1) is installed

## Actual behavior
.NET Core 3.0 is installed

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 1
  Paused: 0
  Stopped: 12
 Images: 475
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: 2GUV:XSRJ:M2YY:QKE7:BI4H:OCZU:H3MW:GXKV:ULG2:B4NV:IEFS:DRHO
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 28
  Goroutines: 44
  System Time: 2019-11-14T22:47:37.8759641Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
The `latest` tag will always point to the latest released version of the product.  3.0 is currently the latest released version, 3.1 is in preview.  Having `latest` reference pre-release bits is not desirable as it is not a stable and supported version.

**Comment by davidmikh** [comment]
Ah I see, thanks for the clarification. Is there another tag I can use for the latest preview version of .NET Core or do I need to specify 3.1?

**Comment by MichaelSimons** [comment]
@davidmikh - `3.1` would be the correct tag to use in order to get the latest version of 3.1 as the previews and RTM versions are released.

**Comment by davidmikh** [comment]
@MichaelSimons sorry I forgot to mention this earlier, since we're specifically targeting the `core-nightly` version of the SDK in this scenario would it be possible for that one to target the most recent release when using `latest` regardless of stability, or to have a different URL / tag for this altogether if necessary? 

We were hoping to have a way to always get the latest preview version of the SDK regardless of stability

**Comment by MichaelSimons** [comment]
Re-opening for discussion per @davidmikh's latest response.

**Comment by MichaelSimons** [comment]
@davidmikh, Can you explain your use case in more detail?  What is your usage where you always want the latest SDK w/latest runtime?

**Comment by davidmikh** [comment]
@MichaelSimons I'm trying to write automated tests for a scenario in .NET Core on a docker container to make sure there isn't a regression in the latest preview builds of .NET Core.

**Comment by MichaelSimons** [comment]
We made a decision that we will change the tagging strategy for “latest” in nightly.  With the recent release of 3.1, latest was already moved so there are no additional tagging changes need at this time.

I will be using this issue to track the changes to the [tagging guidelines documentation](https://github.com/dotnet/dotnet-docker/blob/master/documentation/tagging-guidelines.md).
