### ISSUE TITLE
Use NuGet to clear local resources in Windows ARM Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1496]
The changes made in https://github.com/dotnet/dotnet-docker/pull/1493 used a workaround for the Windows ARM Dockerfile: https://github.com/dotnet/dotnet-docker/blob/fd7733aa7bbfa7f05a583492cff2a27bd92745ed/3.1/sdk/nanoserver-1809/arm32v7/Dockerfile#L27

It manually deletes the `NuGetScratch` folder instead of calling into NuGet to clear local resources as the AMD64 Dockerfile: https://github.com/dotnet/dotnet-docker/blob/fd7733aa7bbfa7f05a583492cff2a27bd92745ed/3.1/sdk/nanoserver-1809/amd64/Dockerfile#L30

Calling the NuGet command was problematic because it was getting a failure attempting to remove the `NuGetScratch` folder.  This particular problem could be resolved by setting `USER ContainerAdministrator` before the `RUN` command that installs PowerShell.  But when that change is made, it leads to test failures in the `VerifyAspNetImage_AppScenario` and `VerifyRuntimeImage_AppScenario` tests because of https://github.com/dotnet/dotnet-docker/issues/1054.  There might be a way to resolve the testing issues through some magic combination of Dockerfile commands.  It just needs to be experimented with.

**Comment by MichaelSimons** [comment]
Closing since support for Windows ARM is being dropped (#1840).
