### ISSUE TITLE
Docker for Windows container volume specification error

### ISSUE THREAD

**Issue by shashijeevan** [dotnet/dotnet-docker#1499]
## Steps to reproduce the issue
I am using Docker Desktop on Windows 10.
Enabled Windows containers option
Tried to run sample asp.net core app using the instructions given in the following link (Windows using Windows containers section)
https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md
I was able to create the development certificate and trust it.
Pulled the image successfully

I tried running the container using the command given in the instructions

docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:/https/ mcr.microsoft.com/dotnet/core/samples:aspnetapp

## Expected behavior
It should have started the container with two endpoints HTTP and HTTPS.

## Actual behavior
Docker failed to start the container and generated the following error

docker: Error response from daemon: invalid volume specification: 'C:\Users\devuser\.aspnet\https:/https/'.
See 'docker run --help'.

I had to change the Volume specification 

from
%USERPROFILE%\.aspnet\https:/https/

to
%USERPROFILE%\.aspnet\https:C:\https

to make it work.

## Additional information (e.g. issue happens only occasionally)
Looks like this is an issue in the instructions.

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 7
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.476)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.91GiB
 Name: TEKFRIDAY189
 ID: 72WH:CU7D:QOSV:ZCWI:2XJ6:GBFP:G4JI:ROUT:BWXE:HAGY:CWP3:FBZ3
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2019-11-26T20:35:29.5723463+05:30
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
It looks like you're looking at the Linux instructions, not Windows.  The Windows instructions _do_ state to use the syntax that did work for you:
```cmd
docker pull mcr.microsoft.com/dotnet/core/samples:aspnetapp
docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" -e ASPNETCORE_Kestrel__Certificates__Default__Path=\https\aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:C:\https\ mcr.microsoft.com/dotnet/core/samples:aspnetapp
```

**Comment by shashijeevan** [comment]
You are right. I was looking at 'Windows using Linux containers' section.
