### ISSUE TITLE
Dotnet restore does not create a lock file

### ISSUE THREAD

**Issue by kataik** [dotnet/dotnet-docker#150]
I have a folder structure, which has a _Dockerfile_ in its root. The solution folders are under a folder named **src** and the .NET Core solutions can be found underneath, for example:

> ./src/CoreLibrary/src/CoreLibrary/project.json
> ./src/CoreLibrary/test/CoreLibrary.Tests/project.json

My _Dockerfile_ has the following code:

```
FROM microsoft/dotnet:latest
MAINTAINER Kornel Balint Katai <kataik@gmail.com>

RUN apt-get -y clean \
	&& apt-get -y purge \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
	&& curl -sL https://deb.nodesource.com/setup_4.x | bash - \
	&& apt-get install -y nodejs \
	&& npm install -g bower \
	&& npm install -g gulp \
	&& rm -rf /var/lib/apt/lists/*

VOLUME /build
VOLUME /publish

WORKDIR /build

COPY . .

RUN dotnet restore -s https://api.nuget.org/v3/index.json
RUN dotnet build ./**/project.json -c Release
RUN dotnet publish ./CoreLibrary/src/CoreWeb --framework netcoreapp1.0 --output /publish --configuration Release

EXPOSE 5000

ENTRYPOINT ["dotnet", "run", "/publish/CoreWeb/CoreWeb.dll"]
```

## Steps to reproduce the issue
1. Execute `docker build`

## Expected behavior
The build process succeeds.

## Actual behavior
The build process fails during the `dotnet build` command with the following error message:

> Project x does not have a lock file. Please run "dotnet restore" to generate a new lock file.

## Additional information (e.g. issue happens only occasionally)
The logs created during the restore states that the lock files are created, eg:

> log : Writing lock file to disk. Path: /build/src/CoreLibrary/src/CoreWeb/project.lock.json

, but the files does not exists. If I execute restore on my local PC, it works like a charm.

**Comment by MichaelSimons** [comment]
@kataik, I have been unable to reproduce this.  I'm curious if you ever see this happen if you don't use Docker Volumes?

**Comment by MichaelSimons** [comment]
@kataik, I just noticed something with your `Dockerfile` that looks incorrect.  You declare the `VOLUME` before coping the project, restoring, and building.  This looks to be the source of your problem.  According to the [Dockerfile documentation](https://docs.docker.com/engine/reference/builder/#/volume) 

```
Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.
```

Try moving the `VOLUME` commands to the end of the `Dockerfile`.

**Comment by MichaelSimons** [comment]
@kataik, if my last response did not address your issue, please update this issue and re-open.
