### ISSUE TITLE
Trying to set up image Firewall (Permission denied)

### ISSUE THREAD

**Issue by molidestroyer** [dotnet/dotnet-docker#1506]
I'm trying to block all connection within the image except the port which i'm using on my netcore app. The idea was block all ports except 8443

## Steps to reproduce the issue
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
RUN apt-get update && apt-get --yes install ufw && \
	apt --yes install sudo && \
	whoami && \
	su && \
	sudo service ufw start && \
	sudo ufw enable && \
	sudo ufw status verbose && \
	sudo -s ufw app list && \
	sudo -s ufw default deny incoming && \
	sudo -s ufw default deny outgoing && \
	sudo -s ufw allow 8443/tcp

## Expected behavior
ufw Instruction it's working

## Actual behavior
Skip starting firewall: ufw (not enabled)...done.
12>[91mERROR: problem running ufw-init
12>/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
12>/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
12>/lib/ufw/ufw-init: 118: /lib/ufw/ufw-init: modprobe: not found
12>iptables-restore: line 6 failed
12>iptables-restore: line 22 failed
12>iptables-restore v1.8.2 (nf_tables): Couldn't load match `conntrack':No such file or directory
12>Error occurred at line: 2
12>Try `iptables-restore -h' or 'iptables-restore --help' for more information.
12>iptables-restore: line 4 failed
12>iptables-restore: line 5 failed
12>iptables-restore: line 21 failed
12>iptables-restore v1.8.2 (nf_tables): unknown option "--dport"
12>Error occurred at line: 19
12>Try `iptables-restore -h' or 'iptables-restore --help' for more information.
12>iptables-restore: line 10 failed
12>iptables-restore v1.8.2 (nf_tables): Couldn't load match `limit':No such file or directory
12>Error occurred at line: 8
12>Try `iptables-restore -h' or 'iptables-restore --help' for more information.
12>iptables-restore v1.8.2 (nf_tables): Chain 'ufw-before-input' does not exist
12>/lib/ufw/ufw-init: 384: /lib/ufw/ufw-init: sysctl: not found
12>Problem loading ipv6 (skipping)
12>Problem running '/etc/ufw/before.rules'
12>Problem running '/etc/ufw/after.rules'
12>Problem running '/etc/ufw/user.rules'
12>Service 'xxxx.api' failed to build: The command '/bin/sh -c apt-get update && apt-get --yes install ufw && 	apt --yes install sudo && 	whoami && 	su && 	sudo service ufw start && 	sudo ufw enable && 	sudo ufw status verbose && 	sudo -s ufw app list && 	sudo -s ufw default deny incoming && 	sudo -s ufw default deny outgoing && 	sudo -s ufw allow 8443/tcp' returned a non-zero code: 1
12>[0m

## Additional information (e.g. issue happens only occasionally)
I tried also the same with iptables but i'm getting but I receive permission denied all the time, I'm executing as root (I think..)

12>Default incoming policy changed to 'deny'
12>(be sure to update your rules accordingly)
12>Default outgoing policy changed to 'deny'
12>(be sure to update your rules accordingly)
12>�[91mWARN: initcaps
12>[Errno 2] iptables: Permission denied (you must be root).
12>�[0mRules updated
12>Rules updated (v6)

Any ideas how to do that into the image?

**Comment by MichaelSimons** [comment]
This issue isn't directly related to the .NET Core images.  You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/), [Docker Forums](https://forums.docker.com/), or [Docker Slack Channel](http://dockr.ly/slack).

In case you haven't looked already, searching for `ufw docker` on the web will show a lot of discussions on the topic of UFW and Docker.
