### ISSUE TITLE
Feature: Easy way to install C# in an existing Docker image

### ISSUE THREAD

**Issue by cburgmer** [dotnet/dotnet-docker#1510]
Hey there,

I'm running a project comparing different programming languages to each other. I'd like to include C#. I'm running this in Docker and so far mostly everything can be included via an `apk add X`. 

For reference the file: https://github.com/cburgmer/json-path-comparison/blob/master/src/Dockerfile

Can I do something similar with dotnet?

**Comment by MichaelSimons** [comment]
@cburgmer, see our [Installing .NET Core in a Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/installing-dotnet.md) docker sample snippets documentation.  Please let us know if you find it helpful or not.

**Comment by cburgmer** [comment]
Hmm, that seems to need a Linux, so I would need Ubuntu or something similar, so goodbye Alpine. I now found https://docs.microsoft.com/it-it/dotnet/core/install/linux-package-manager-ubuntu-1904#troubleshoot-the-package-manager. This is probably the goto solution for a manual Docker setup. Good enough for me. Thanks.

I guess the question remains why it's hard to get dotnet on Alpine, it does seem to me that way. Feel free to close this issue anyway.

**Comment by MichaelSimons** [comment]
@LeeCow, @dagood. FYI, Here is a request for Alpine package support.

Have we considered producing APK packages (not hosted on a feed) as a first step in support?

Closing.  https://github.com/dotnet/core-setup/issues/4957 is tracking APK support.

**Comment by dagood** [comment]
> Have we considered producing APK packages (not hosted on a feed) as a first step in support?

I don't think we have, and `fpm` seems to support them ([apk.rb](https://github.com/jordansissel/fpm/blob/304619416b11be594489e3aa78980d4fae38401c/lib/fpm/package/apk.rb)) so it may not be too difficult to add. We use `fpm` for RPM packages and it's relatively easy to use.
