### ISSUE TITLE
Snyk finds 24 High security alerts from image

### ISSUE THREAD

**Issue by Staggerlee011** [dotnet/dotnet-docker#1515]
## Steps to reproduce the issue
1. create docker image using mcr.microsoft.com/dotnet/core/aspnet:3.1
2. run free snyk scan

image and dotnet image used [here ](https://github.com/Staggerlee011/dotnet/blob/master/site/dockerfile)

## Expected behavior
I was hoping for no high, medium or low security alerts

## Actual behavior
it found 24 high, 21 medium and 9 low

**Comment by MichaelSimons** [comment]
@Staggerlee011 - Please read the [Staying up-to-date with .NET Container Images](https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/) blog we wrote a while ago.  The _Security Updates and Vulnerability Scanning_ section discusses the vulnerabilities in the Debian based images such as the 3.1 tag you mention.  I encourage you to run a security scan on the `debian:buster-slim` image which `mcr.microsoft.com/dotnet/core/aspnet:3.1` is based on.  If you are looking for a secure image with no vulnerabilities, our recommendation is to use the alpine based images such as `mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine`

**Comment by MichaelSimons** [comment]
Closing per previous recommendation.  Feel free to continue the discussion.

**Comment by Staggerlee011** [comment]
Hi @MichaelSimons thanks for this (Sorry for the late reply). Rather open ended question im sure, but whats the reason for all the different images, is it just to cover personal prefernce or is there performance / other benifits between them (ie the alpine version has less poss security vulns)
