### ISSUE TITLE
Inconsistent use of locale environment variables

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1516]
The `LC_ALL` and `LANG` environment variables are set in Alpine SDK images but not any other distro SDKs.  Additionally, none of the runtime images include these environment variables.  We need to figure out what the correct pattern is and make things consistent.  Should these variables be defined at all?  Should they be in the runtime images across the board?  Any changes for this will need to be made in the 5.0 timeframe since it will be a breaking change.

Related customer issue that required setting the environment variables: https://github.com/dotnet/dotnet-docker/issues/1483

**Comment by MichaelSimons** [comment]
Making any changes here would be considered a breaking change and should be done in the 5.0 timeframe.

**Options:**
1. Don't set `LC_ALL` and `LANG` anywhere.
1. Set `LC_ALL` and `LANG` in all sdk images - This is a more curated and prescriptive experience.  A downside to this is inconsistency with the runtime images which may cause issues for users e.g. they miss this when creating their runtime images.
1. Do in some places and not others - This is state we are in now and feels like the least desirable behavior for obvious reasons.

For the last two options, it feels like using EN-US is the wrong choice as our images should be global friendly.

After discussing this, we decided to go with option 1 - Don't set `LC_ALL` and `LANG` anywhere.  This follows a strategy of being policy free as much as possible.
