### ISSUE TITLE
"The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found." under runtime:3.1 image

### ISSUE THREAD

**Issue by bartekkois** [dotnet/dotnet-docker#1539]
## Steps to reproduce the issue
1. Build and run .NET Core 3.1 app with runtime:3.1-alpine image (tested code: https://github.com/bartekkois/GPONMonitor)

## Expected behavior
Container and app should start properly without erros.

## Actual behavior
Container produces the following error:
> Creating gponmonitor_gponmonitornew_1 ... done
Attaching to gponmonitor_gponmonitornew_1
gponmonitornew_1  | It was not possible to find any compatible framework version
gponmonitornew_1  | The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
gponmonitornew_1  |   - No frameworks were found.
gponmonitornew_1  |
gponmonitornew_1  | You can resolve the problem by installing the specified framework and/or SDK.
gponmonitornew_1  |
gponmonitornew_1  | The specified framework can be found at:
gponmonitornew_1  |   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64

## Additional information (e.g. issue happens only occasionally)
After changing runtime:3.1-alpine to sdk:3.1-alpine image container build and runs without errors:
> Creating network "gponmonitor_default" with the default driver
Creating gponmonitor_gponmonitornew_1 ... done
Attaching to gponmonitor_gponmonitornew_1
gponmonitornew_1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
gponmonitornew_1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
gponmonitornew_1  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
gponmonitornew_1  |       No XML encryptor configured. Key {a3747f9e-2a0d-41db-a4b6-34ec0a96a7d7} may be persisted to storage in unencrypted form.
gponmonitornew_1  | warn: Microsoft.AspNetCore.Server.Kestrel[0]
gponmonitornew_1  |       Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Address not available'.
gponmonitornew_1  | warn: Microsoft.AspNetCore.Server.Kestrel[0]
gponmonitornew_1  |       Unable to bind to https://localhost:5001 on the IPv6 loopback interface: 'Address not available'.

## Output of `docker version`
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

## Output of `docker info`
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: monitor
ID: ASB2:KRBY:RKLA:J4OS:ELI3:LQMI:5XEP:7OGN:PR2D:N52W:JCRV:532D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bartekkois
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**Comment by Wulf** [comment]
hey @bartekkois, what ended up being the problem?

**Comment by bartekkois** [comment]
Here is the solution https://github.com/bartekkois/GPONMonitor/commit/00bd4babd2ec19fe66e20c0d704b2e8f2583fa45
