### ISSUE TITLE
Visual Studio Docker tools 0.41 docker build is failing

### ISSUE THREAD

**Issue by tilutza** [dotnet/dotnet-docker#154]
## Steps to reproduce
- Create a new template project from VS 2015 U3 with Docker Tools 0.41 installed

try to build manually:
```
$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED   SIZE
microsoft/aspnetcore   1.0.1               ae3c624183ac        19 hours ago   266.8 MB
busybox                latest              e02e811dd08f        4 weeks ago   1.093 MB

using the detaulf docker support from VS, issue command:
$ docker-compose.exe build
←[33mWARNING←[0m: The TAG variable is not set. Defaulting to a blank string.
Building netcoretest
Step 1 : FROM microsoft/aspnetcore:1.0.1
 ---> ae3c624183ac
Step 2 : ENTRYPOINT dotnet NetCoreTest.dll
 ---> Running in 264445a7b999
 ---> a8ea53ecaf55
Removing intermediate container 264445a7b999
Step 3 : ARG source=.
 ---> Running in 51e020a4f8f0
 ---> 33fc2ebb8d87
Removing intermediate container 51e020a4f8f0
Step 4 : WORKDIR /app
 ---> Running in 8e23d27f745c
 ---> 799f8a168ac1
Removing intermediate container 8e23d27f745c
Step 5 : EXPOSE 80
 ---> Running in aa7ce1d85a50
 ---> b0640bb323a5
Removing intermediate container aa7ce1d85a50
Step 6 : COPY $source .
 ---> 8eda43b93c49
Removing intermediate container cea48847ec5b
Successfully built 8eda43b93c49

$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED   SIZE
netcore                test                8eda43b93c49        25 seconds ago   269.9 MB
microsoft/aspnetcore   1.0.1               ae3c624183ac        19 hours ago   266.8 MB
busybox                latest              e02e811dd08f        4 weeks ago   1.093 MB

$ docker run -it netcore:test
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

On my side it does not work either to debug from Visual Studio either, but I think it is not related to. However, I will paste here, maybe it is related:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PrepareForCompile" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22name%22%3A%7B%22netcoretest_netcoretest%22%3Atrue%7D%7D&limit=1: open //./pipe/docker_engine: The system cannot find the file specified.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.PrepareForCompile.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing\ImportAfter\Microsoft.DotNet.Docker.targets	61	
`

I have the following tools installed
![image](https://cloud.githubusercontent.com/assets/5718468/20151264/258634c4-a6c2-11e6-80ad-c5a6cff742e2.png)

and 
![image](https://cloud.githubusercontent.com/assets/5718468/20151545/2b40cb58-a6c3-11e6-9067-2d5a4674d7eb.png)

## Expected  behavior
run the docker image

## Environment data
```
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64


$ docker info
Containers: 28
 Running: 0
 Paused: 0
 Stopped: 28
Images: 10
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:4
0:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: 7SCP:CT4X:L6OJ:APN3:I2D4:6OX2:RTSV:M5DW:YY4D:YWKE:UYUU:CF5Q
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-11-10T12:58:36.615512276Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

$ docker-machine.exe ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.2


```

**Comment by MichaelSimons** [comment]
@tilutza - the issue you are encountering does not appear specific to the microsoft/dotnet images themselves.  I think you would be better off starting a discussion with [Visual Studio Tools for Docker](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4) about this issue.  

Is your app getting compiled prior to running  docker-compose.exe build?  Try running docker run -it netcore:test but change the entrypoint to bash and inspect the contents of the image.  Verify the container contains your app's binaries and that you can run `dotnet NetCoreTest.dll`

**Comment by tilutza** [comment]
Regarding the Visual Studio error, I have added a comment in the [troubleshooting page](https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-troubleshooting-docker-errors/), but for clarity I will paste here as well:

> For those who are using Docker Toolkit and they are trying to deploy using Visual Studio after using 0.41 toolkit, I was able to do a workaround to work:
> - open a cmd (logged in as the current user and not Administrator)
> - execute: @FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i
> - start Visual Studio by typing devenv
> 
> I have tried to specify the environment variables in the project properties and in the docker-compose.yml, but no other option is working.

Unfortunately I don't know the reason, since I would have change the github page.

However, the issue does not occurs with Windows 10 and Docker Tools (not the one in Virtual Box).

@MichaelSimons I will give a try tomorrow and see the results

**Comment by MichaelSimons** [comment]
@tilutza, if this is still an issue, please follow up with [Visual Studio Tools for Docker](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4).  Closing issue.
