### ISSUE TITLE
dotnet restore error /usr/share/dotnet/sdk/3.1.100/NuGet.targets(123,5): error

### ISSUE THREAD

**Issue by SharksFX** [dotnet/dotnet-docker#1540]
## Steps to reproduce the issue
1.  Add Docker Support in Visual Studio 2019 - Version 16.4.2. Creates Docker file 

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["DockerTest2/DockerTest2.csproj", "DockerTest2/"]
RUN dotnet restore "DockerTest2/DockerTest2.csproj"
COPY . .
WORKDIR "/src/DockerTest2"
RUN dotnet build "DockerTest2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DockerTest2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DockerTest2.dll"]

2. In Visual Studio right click the Dockerfile and select "Build Docker Image"

## Expected behavior
Docker image is generated and built 

## Actual behavior

Creation of the image fails on step "RUN dotnet restore "DockerTest2/DockerTest2.csproj"

## Additional information (e.g. issue happens only occasionally)

Happens all the time! Have checked and implemented a multitude of "fixes" linked to this issue and nothing works.

1>Sending build context to Docker daemon  15.87kB
1>
1>Step 1/17 : FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
1> ---> 08d8cf51bdfd
1>Step 2/17 : WORKDIR /app
1> ---> Using cache
1> ---> 00bc1390e231
1>Step 3/17 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
1> ---> 9817c25953a8
1>Step 4/17 : WORKDIR /src
1> ---> Using cache
1> ---> 7cd733deb55c
1>Step 5/17 : COPY ["DockerTest2/DockerTest2.csproj", "DockerTest2/"]
1> ---> Using cache
1> ---> 968c4326921e
1>Step 6/17 : RUN dotnet restore "DockerTest2/DockerTest2.csproj"
1> ---> Running in ed8d8894d04b
1>/usr/share/dotnet/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/DockerTest2/DockerTest2.csproj]
1>/usr/share/dotnet/sdk/3.1.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/src/DockerTest2/DockerTest2.csproj]
1>/usr/share/dotnet/sdk/3.1.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/src/DockerTest2/DockerTest2.csproj]
1>Removing intermediate container ed8d8894d04b
1>The command '/bin/sh -c dotnet restore "DockerTest2/DockerTest2.csproj"' returned a non-zero code: 1
1>c:\users\mikeb\documents\visual studio 2019\dockertest2\dockertest2\dockerfile : error CTC1014: Docker command failed with exit code 1.

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 9
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.934GiB
 Name: docker-desktop
 ID: PBIE:S6ZD:PBEM:G37D:PDZ3:2DZN:W6ZK:IBC2:HDDI:SMHM:PT7U:GGYU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 33
  Goroutines: 48
  System Time: 2019-12-24T10:06:02.2303727Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
This is typically a local environment issue and not an issue with the Docker image itself.

@SharksFX - Please investigate by reviewing similar issues that have been logged:
* https://github.com/dotnet/dotnet-docker/issues/1341
* https://github.com/dotnet/dotnet-docker/issues/1031

**Comment by MichaelSimons** [comment]
@SharksFX - Were you able to take a look at the issues @mthalman referenced?  Did they help pinpoint the problem?

Closing as this appears to be a local environment issue.  Feel free to continue the conversation.
