### ISSUE TITLE
Report on the health monitoring and diagnostics capabilities of .NET Core containerized workloads

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker#1571]
We should build a better understanding of how industry container health monitoring and diagnostic practices work with .NET Core workloads. With that we can provide better .NET specific customer guidance, identify platform opportunities and differentiators. 
Phases:
1. Start with basics like `docker logs`
2. Look at aspnet health checks functionality
3. Survey 3rd party monitoring solutions like Sysdig, Datadog, etc. and how they work with aspnet health checks

**Comment by mthalman** [comment]
[Triage]
We've done some work at addressing health monitoring as part of https://github.com/dotnet/dotnet-docker/pull/4352. At this point, we're going to leave it at that unless any further comes up.
