### ISSUE TITLE
update-dependencies tool not accessing checksum URLs correctly

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1576]
There is an aspect of how the update-dependencies tool retrieves the checksum for a .NET artifact that needs to be fixed.  It attempts to access checksum files with a URL pattern of `https://dotnetcli.blob.core.windows.net/dotnet/checksums/<version>-<product>-sha.txt` but this results in a 404.  The checksums are now available for an entire release (both runtime and SDK) in a single URL and the text must be parsed to access the necessary value: `https://dotnetcli.blob.core.windows.net/dotnet/checksums/<version>-sha.txt`.

**Comment by MichaelSimons** [comment]
When doing this work, please ensure the solution works for the nightly repo/branch. The daily builds don't have their checksums placed in the checksums folder mentioned. Also ensure that msrc builds are accounted for.

**Comment by MichaelSimons** [comment]
One option to consider would be to make the fall back logic that computes the checksum if not found to be optional behavior (off by default).  The update-deps build which updates nightly should probably turn on this option.
