### ISSUE TITLE
update-dependencies should fail if checksums not available

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1579]
When running the update-dependencies tool, it will attempt several methods of getting a checksum for a .NET artifact.  If all of those attempts fail for a given artifact, it should cause the tool to return a non-zero exit code.  Currently, it does not and it's left to a person to look over the Dockerfiles to verify things are set properly.

**Comment by MichaelSimons** [comment]
When doing this work, please ensure the solution works for the nightly repo/branch.  The daily builds don't have their checksums placed in the checksums folder mentioned.  Also ensure that msrc builds are accounted for.
