### ISSUE TITLE
Runtime amd64 images throw error - "It was not possible to find any installed .NET Core SDKs"

### ISSUE THREAD

**Issue by streamcap** [dotnet/dotnet-docker#1589]
## Steps to reproduce the issue
1. Create the following Dockerfile:
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine
RUN dotnet --version
CMD ["dotnet", "--version"]
2. Build a docker image from the dockerfile: "docker build -t dotnet-test ."
3.Run the image as a container: "docker run -it --rm dotnet-test"

## Expected behavior
Both during build and during run, the proper .net core version number is displayed (e.g., 3.1.101)

## Actual behavior
The following error message is presented:
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

## Additional information (e.g. issue happens only occasionally)
Replacing the image reference with /aspnet:3.1-alpine yields same error.
Replacing the image reference with /sdk:3.1-alpine yields proper behavior.

Same error has been found using the images with -bionic and -buster-slim tags.

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.934GiB
 Name: docker-desktop
 ID: O7FA:EXOW:K6W4:RZNK:IMRB:5IHE:453N:6CEG:SXFH:MOPD:55UA:4GZP
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 44
  System Time: 2020-01-16T12:52:11.8186833Z
  EventsListeners: 1
 HTTP Proxy: *** [Withheld]
 HTTPS Proxy: *** [Withheld]
 No Proxy: *** [Withheld]
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
@streamcap - You are using a `runtime` image which does not contain the .NET Core SDK.  You cannot build within a runtime image.  Try using an [`sdk` image](https://hub.docker.com/_/microsoft-dotnet-core-sdk).

The runtime images are optimized for running published .NET Core projects.  They don't contain the .NET Core SDK to reduce the image size.  This makes them quicker to pull and supports a larger number of images in production environments.

**Comment by streamcap** [comment]
I am NOT trying to build an app. I am trying to run it.
The .NET Core CLI clearly states that you should be able to run a .NET Core app in a Linux environment using the command "dotnet *.dll", or something to that effect.

I also tried changing the last line of the Dockerfile to read:
`ENTRYPOINT ["dotnet", "--version"]`
The same error occurs.

**Comment by streamcap** [comment]
Sorry everyone. I had quite the learning experience today.
It turned out to be somewhat of an an Error-40 on our part - apparently, "docker --version" is a build command and thus off limits in a runtime-only environment. Also, you can't run a .net core application that has been moved to a cache mount, which obviously stands to reason since that would otherwise be an attack vector to execute malicious code.

We tried again with a DLL file that was copied in the old-fashioned way and all is well.

Once again, sorry for taking up your time.
