### ISSUE TITLE
Missing support mcr.microsoft.com/dotnet/core/sdk:2.2

### ISSUE THREAD

**Issue by AdalynRockwood** [dotnet/dotnet-docker#1591]
## Steps to reproduce the issue
1. Go to https://hub.docker.com/_/microsoft-dotnet-core-sdk 
2. Notice page no longer references sdk:2.2. 
3. 
Set up a project with a Docker file that uses 2.2 as base like follows.
     FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base

## Expected behavior
Successful build

## Actual behavior
Failure on dotnet restore
dotnet restore
/usr/share/dotnet/sdk/2.1.803/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [/opt/atlassian/pipelines/agent/build/......csproj]

## Output of `docker version`
This will be 
```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
@AdalynRockwood - As of Dec 23rd, 2.2 is now EOL and no longer supported.  Per this [announcement](https://github.com/dotnet/dotnet-docker/issues/1542), we are no longer servicing the 2.2 images.  The 2.2 tags were also removed from the documented list of supported tags.  The existing 2.2 tags/images are still available for use at your own risk.  Please migrate your project to a newer version of .NET.  I would suggest 3.1 which is an LTSC release.  For more details see the .[NET Core official support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

**Comment by AdalynRockwood** [comment]
Thank you, for the timely response.

**Comment by MichaelSimons** [comment]
Closing issue per my previous guidance.  Feel free to continue discussing.
