### ISSUE TITLE
Minimal runtime dependencies should be captured in a --slim variant

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker#16]
**NAME** 
--slim variant for dotnet cli apps

**SYNOPSIS**
Provide the smallest possible base image for any .NET Core app to run in. 

**DESCRIPTION**
Developers can use `dotnet publish` and `dotnet compile --native` to encapsulate runtime dependencies that can then be `COPY`'d to a minimal-footprint image (i.e. excludes dotnet cli toolchain). Yet there are Linux packages that are needed for any .NET Core app to run; for example, ICU). Are there other minimal dependencies that should be included?

**Comment by MichaelSimons** [comment]
https://github.com/dotnet/dotnet-docker/pull/36 added core-deps and core images.  core-deps image only contains the .NET Core dependencies necessary to run a standalone app on.  The core image only contains the .NET runtime which is necessary to run a standard app on.
