### ISSUE TITLE
Aspnet.core Linux Docker GDI+

### ISSUE THREAD

**Issue by TonyKindschuh** [dotnet/dotnet-docker#1601]
## Steps to reproduce the issue
1. Create image using mcr.microsoft.com/dotnet/core/aspnet:2.2
2. Aspnet.core app that is using System.Drawing.Common package
3. Install apt-get to get GDI packages
4. Try to create thumbnail

## Expected behavior
Getting an exception "System.Runtime.InteropServices.ExternalException: A generic error occured in GDI+

## Actual behavior
Create my files

## Additional information (e.g. issue happens only occasionally)
I found this post already https://github.com/dotnet/dotnet-docker/issues/618 , and I added the apt-get below to my docker file, and it resolved the error I was getting related to that post, but now I'm getting the generic GDI+ error.

RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*

My Docker File
------------------------------------------
# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2

ENV ASPNETCORE_ENVIRONMENT=Development

# install System.Drawing native dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build-env /app/MyApp/out .

ENTRYPOINT ["dotnet", "MyApp.dll"]
-------------------------------------------------

Aspnet code
--------------------------------
            var image = System.Drawing.Image.FromFile(GetFilePath(value.file.FileName));
            var thumb = image.GetThumbnailImage(120, 120, () => false, IntPtr.Zero);
            thumb.Save(Path.ChangeExtension(GetThumbPath(value.file.FileName), "thumb"));
----------------------------------------
## Output of `docker version`

Client: Docker Engine - Community
 Version: 19.03.1
API Version: 1.40
Go version: go1.12.5
Git commit: 74b1e89

Server: Docker Engine - Community
 Engine:
  Version: 19.03.1
  Api Version: 1.40
 Git commit: 74b1e89

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
My first suggestion is to upgrade to a newer version of .NET Core.  2.2 went EOL on Dec 23, 2019.  I would suggest upgrading to the latest LTS version - 3.1

**Comment by mthalman** [comment]
@TonyKindschuh - I'm unable to repro this.  Can you provide a zip file with a standalone project that causes this exception?

**Comment by MichaelSimons** [comment]
Closing due to lack of response.  Feel free to respond with the requested steps to reproduce if this is still and issue.
