### ISSUE TITLE
fatal path not found

### ISSUE THREAD

**Issue by krisrajzlive** [dotnet/dotnet-docker#1603]
## Steps to reproduce the issue
1.git clone https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp/aspnetapp
2.fatal : repository https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp/aspnetapp not found
3.

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by mthalman** [comment]
`git clone` doesn't let you clone only a specific directory.  You need to clone the entire repo.  The root of the repo is at https://github.com/dotnet/dotnet-docker.  So use this command:
`git clone https://github.com/dotnet/dotnet-docker`
