### ISSUE TITLE
How can we import PKI module in PowerShell

### ISSUE THREAD

**Issue by jinaldesailive** [dotnet/dotnet-docker#1605]
I want to import PKI module of PowerShell in the SDK 3.0 image.
How we can do it ?

I want to run Import-Certificate command using PowerShell, but the command is part of PKIClient module of PowerShell which is not part of SDK 3.0 nanoserver.

Command I ran
docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1803 pwsh

Now I want to run Import-Certificate command to import my client certificate.

**Comment by MichaelSimons** [comment]
Closing as this issue isn't directly related to the .NET Core images.  This is a general PowerShell Docker question.  You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.
