### ISSUE TITLE
PR build should build and test sample images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1619]
There is currently a separate [pipeline](https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/dotnet-core-samples.yml) for running a sample build for PR validation.  This builds and tests the sample Dockerfiles but it ends up pulling the base .NET images the samples are based on.  So it's testing with already published base images rather than the content of the repo.

Instead the [dotnet-core](https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/dotnet-core.yml) and [dotnet-core-nightly](https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/dotnet-core-nightly.yml) pipelines should be updated to build the sample images in addition to the product images (but for PR builds only).

To make this work, the sample Dockerfiles for images that are published will need to be updated to have a `REPO` arg in the same way that the official product Dockerfiles do in order for a reference to a staging repo location to be passed when building.

**Comment by MichaelSimons** [comment]
The official Dockerfiles make use of an ARG to be able to dynamically change the repo of the base image.  Using an ARG in the samples is undesirable.  This is not the standard pattern we would recommend to customers.

There is functionality in Image-Builder to [rewrite the from statements](https://github.com/dotnet/docker-tools/blob/8642cbbfda83b7e5df32a6a0094c4bed9ad322fc/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L286).  This code may be useful for this scenario.

**Comment by MichaelSimons** [comment]
We don't think this has a high ROI.  The samples don't add significant test coverage over the existing Dockerfile unit tests.
