### ISSUE TITLE
What's the license of these images?

### ISSUE THREAD

**Issue by omajid** [dotnet/dotnet-docker#164]
Suppose I want to build on top of these dockerfiles on Linux and possibly even distribute the resulting docker images. Maybe I want to mirror all of dockerhub locally. What license should I be looking at?

- The LICENSE file says this is licensed under MIT
- The README refers to a proprietary license for .NET Core binaries: https://www.microsoft.com/net/dotnet_library_license.htm
- The README says the source code of .NET Core is under MIT (is this relevant give the license of the binary above?)

So what's the combined license? It's not MIT (or another open source license), is it?

**Comment by MichaelSimons** [comment]
@richlander, @kendrahavens, @vivmishra - please respond.

**Comment by richlander** [comment]
The .NET Core product is licensed as the .NET Library license you have listed. You can think of this as the "Microsoft distribution of .NET Core".

The source is copyright .NET Foundation and is MIT licensed.

You are free to do what you want, which is build images on top. If that doesn't work for you, I'd love to learn more. Would be good to jump on a call to have a higher-velocity discussion. You can mail me @ rlander@ms.

**Comment by MichaelSimons** [comment]
@omajid, Did Rich's response answer your question?  Feel free to reach out if you have additional questions.

**Comment by omajid** [comment]
Thanks, yes, Rich's response addresses my questions.
