### ISSUE TITLE
Need to make it easier to run nuget in docker image to publish builds to private repos

### ISSUE THREAD

**Issue by tommed** [dotnet/dotnet-docker#168]
## Summary

Like most (I'm sure), docker and dotnet are a great paradigm for automated build systems. However, when the end artefact of your build is one or more nuget packages, it is extremely hard to get `dotnet-docker` to publish nuget packages to a repo.

This isn't necessarily this repo's domain but, the vision of running builds on this infrastructure is no doubt a great use of this technology and it would be a crying shame if there wasn't a way to achieve the following...

## Steps to reproduce the issue
1. Launch `microsoft/dotnet:1.1.0-sdk-msbuild`
2. Install nuget `apt-get update && apt-get install -y nuget`
2. Perform a `dotnet pack -c Release MyProject.csproj`
3. Now attempt to push to private repo `nuget push MyPackage.nupkg $MYTOKEN -Source $MY_PRIVATE_REPO`

## Expected behavior

When token and repo URI is correct, nuget should push to repo.

## Actual behavior

```
﻿WARNING: No API Key was provided and no API Key could be found for 'https://www.myget.org/F/vapps-private/auth/1e0b67b4-9225-4f7b-9252-a37e00924af2/api/v2'. To save an API Key for a source use the 'setApiKey' command.
Pushing ViProCloud.Common 1.0.0 to 'https://www.myget.org/F/vapps-private/auth/1e0b67b4-9225-4f7b-9252-a37e00924af2/api/v2'...
﻿Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
```

## Additional information (e.g. issue happens only occasionally)

I have tried to do an `apt-get update && apt-get install mono-devel` and then run the following (a documented workaround for nuget on linux):

```
$ mozroots --import --machine --sync
$ certmgr -ssl -m https://go.microsoft.com
$ certmgr -ssl -m https://nugetgallery.blob.core.windows.net
$ certmgr -ssl -m https://nuget.org
```

However there are two problems here
1. mozroots has huge amounts of dependencies which sucks in a docker paradigm
2. `certmgr -ssl` requires a human to confirm (no force or yes flag available) and therefore breaks the automated build process

## Output of `docker version`

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

## Output of `docker info`

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 143
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 205
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 958.1 MiB
Name: moby
ID: PWJP:KPSE:SRA5:DT7H:GVXE:NGKF:DKZP:I62H:JKNM:UH3S:SW2X:RU7H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: tmedhurst
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by natemcmaster** [comment]
Have you tried using `dotnet nuget push` instead of Mono's nuget implementation? (See `dotnet nuget push --help`).

**Comment by tommed** [comment]
Is this correct? This is a private repo I'm trying to push to, so nuget's `-Source` parameter is needed here:
```
dotnet nuget push MyPackage.1.0.0.nupkg -Source $NUGET_URI
Specify --help for a list of available options and commands.
error: Unrecognized option '-Source'
```

**Comment by MichaelSimons** [comment]
@tommed please try `-s` or `--source` instead.

**Comment by tommed** [comment]
Nice! thanks

**Comment by kenkendk** [comment]
I found that the problem with nuget in Docker can be solved by:

1. install `ca-certificates-mono`
2. Add `RUN nuget update -self`

That avoids all the dependencies on `mozroots` and `cert-sync`

**Comment by tommed** [comment]
YES!

**Comment by tommed** [comment]
`ca-certificates-mono` does not exist on the Debian `buildpack-deps:jessie-scm` image that dotnet is based on. There is `ca-certificates` and `nuget update -self` fails with: "Error getting response stream (Write: The authentication or decryption has failed.): SendFailure"

**Comment by kenkendk** [comment]
I think this can explain it:
http://www.mono-project.com/docs/about-mono/releases/3.12.0/

If `ca-certificates-mono` does not exist, it should be possible to run:
```
cert-sync /etc/ssl/certs/ca-certificates.crt
```

**Comment by tommed** [comment]
Doesn't cert-sync require huge amounts of dependencies? See initial comments

**Comment by kenkendk** [comment]
It should be bundled with Mono, but I have not checked.

**Comment by tommed** [comment]
The whole point is not to require mono in the first place. The dotnet core SDK and CLI should have everything out needs. Why then install the entire mono runtime in a docker image, just so you can push a nuget package? It's just ssl certificates that are stopping this

**Comment by kenkendk** [comment]
I see... I am using the Mono runtime anyway, so no problem for me.
Maybe you need to ask the Debian maintainers why they dropped `ca-certificates-mono` in Jessie, and maybe they can explain what to do instead. I have looked for that information for another use case, but not found anything.

**Comment by tommed** [comment]
Thank you

**Comment by dagrooms52** [comment]
Any fix? I'm going through this runaround right now. Unable to do any NuGet operations without the error `SecureChannelFailure`. A `nuget restore` and even the above `nuget update -self` give this error.
