### ISSUE TITLE
Memory usage grows indefinitely in aspnet 3.1 in Kubernetes

### ISSUE THREAD

**Issue by barriem** [dotnet/dotnet-docker#1681]
## Steps to reproduce the issue
1. Create an ASPNET core project
2. Wrap in docker container using `mcr.microsoft.com/dotnet/core/aspnet:3.1`
3. Deploy the docker container into a Kubernetes cluster

## Expected behavior
Memory usage remains fairly stable after growing to a particular size

## Actual behavior
Memory usage continues to grow, even when the process is idle

## Additional information (e.g. issue happens only occasionally)
Running the same code using the following tags has the same issue:
```
3.1
3.1-alpine
3.1-bionic
3.1.0
3.1.0-alpine
```

The exact same code running under `mcr.microsoft.com/dotnet/core/aspnet:3.0` does not exhibit the same behaviour.

## Output of `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

<img width="785" alt="Screenshot 2020-02-13 at 22 17 04" src="https://user-images.githubusercontent.com/526154/74483839-3bef4000-4eaf-11ea-8b0f-5160d4a12c4a.png">

**Comment by barriem** [comment]
seems very relevant to old issues - such as this one:
https://github.com/dotnet/aspnetcore/issues/14117

**Comment by omajid** [comment]
cc @tmds

**Comment by barriem** [comment]
Just a note on the above - the code is compiled with the same version of ASPNET core that we're deploying with.  I.e. when we run using `mcr.microsoft.com/dotnet/core/aspnet:3.1` then the code is first built against `mcr.microsoft.com/dotnet/core/sdk:3.1`.   When we run using `mcr.microsoft.com/dotnet/core/aspnet:3.0` then the code is first built against `mcr.microsoft.com/dotnet/core/sdk:3.0`

**Comment by tmds** [comment]
This could be due to the change in `ProcessorCount` that happend from 3.0 to 3.1 (https://github.com/dotnet/runtime/issues/622).
This change will be reverted as part of the next 3.1 patch release, which is probably still this month.
Keep an eye out for the patch release, and then give it another try.

cc @richlander

**Comment by tmds** [comment]
> This change will be reverted as part of the next 3.1 patch release, which is probably still this month.

.NET Core 3.1.2 is available.

**Comment by MichaelSimons** [comment]
@barriem, can you please run your scenario with the 3.1.2 runtime and let us know if your problem is resolved?

**Comment by barriem** [comment]
Hi @MichaelSimons, @tmds - Thanks very much for letting us know. I will try this out tomorrow and get back to you.

**Comment by barriem** [comment]
Hi @MichaelSimons , @tmds - We pushed one of microservices into our dev K8S cluster this morning around 9:30 UTC using `3.1.2`, it's been running for ~ 7 hours and memory usage is looking a lot more stable than with `3.1.1`.   If everything is still looking good in the morning will close the ticket.

Thanks for your help.

**Comment by barriem** [comment]
Looking good after 24 hours of use, thanks all.

**Comment by irmomanie** [comment]
This problem is back with `3.1.9-alpine`

**Comment by MichaelSimons** [comment]
@irmomanie, Could you please open a new issue with the details of what you are seeing?

**Comment by irmomanie** [comment]
> @irmomanie, Could you please open a new issue with the details of what you are seeing?

Sure thing: https://github.com/dotnet/dotnet-docker/issues/2360
