### ISSUE TITLE
Create LTS tag

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/dotnet-docker#169]
Like latest, but for the slow, stable train.

aspnetcore images will be adding a tag named `lts` to mark this. cref https://github.com/aspnet/aspnet-docker/issues/168

**Comment by MichaelSimons** [comment]
@kendrahavens is going to follow up with Rich on whether or not we want this.  It does add complexity and may cause some confusion with latest.

**Comment by richlander** [comment]
Let's skip it. Support levels should be left to docs.
