### ISSUE TITLE
Change nightly pipeline trigger to only run on Dockerfile updates

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1708]
Currently the [dotnet-core-nightly](https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/dotnet-core-nightly.yml) pipeline is triggered whenever a commit to the nightly branch is made.  This just wastes a lot of compute because there are often changes made to the branch that don't result in a change to the images that get published.

I propose that the pipeline be updated so that it only triggers if a change is made to a Dockerfile.  Admittedly, the nightly branch can be useful to test out infrastructure changes as well.  In those cases, I think it's more appropriate for the dev to manually queue a test build if they want to verify the pipeline.

**Comment by MichaelSimons** [comment]
From a concrete implementation perspective, are you proposing we add an exclusion for /eng and /test?  Perhaps more simply stated, we trigger off of src, manifest, and possibly readme template changes?

**Comment by mthalman** [comment]
I think a better way would be to just use includes rather than excludes.  So we could have includes for manifest.json, 2.1, 3.0, and 3.1.  That's it.  If just a readme gets changed, I think we'd just run the standalone readme update pipeline.
