### ISSUE TITLE
Unable to install AccessDatabaseEngine_X64.exe on mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809

### ISSUE THREAD

**Issue by SebastienHo** [dotnet/dotnet-docker#1740]
## Steps to reproduce the issue
1. Create dockerfile 

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809

EXPOSE 80
COPY "./AccessDatabaseEngine_X64.exe" C:
RUN C:\AccessDatabaseEngine_X64.exe /quiet /passive /norestart

WORKDIR /app
#install binaries
COPY "./.cicd/publish/${APP_NAME}" .

CMD set ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
CMD echo %DLL_NAME%
CMD dotnet %DLL_NAME%`
```
2. Download  AccessDatabaseEngine_X64.exe (https://www.microsoft.com/fr-fr/download/details.aspx?id=13255) and store same path as dockerfile.
3. Open a powershell, set up path to where the docker file is.
4. Run 'docker build .'

## Expected behavior

Build a image with AccessDatabaseEngine_X64.exe

## Actual behavior

Step 1/9 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809
 ---> f89c62aeffaf
Step 2/9 : EXPOSE 80
 ---> Running in 0c3b7ff425f0
Removing intermediate container 0c3b7ff425f0
 ---> 9ddab89033da
Step 3/9 : COPY "./.cicd/docker/Windows/netcoreapp3.1/AccessDatabaseEngine_X64.exe" C:
 ---> dc3dd1837713
Step 4/9 : RUN C:\AccessDatabaseEngine_X64.exe /quiet /passive /norestart
 ---> Running in 0694675634a6
The command 'cmd /S /C C:\AccessDatabaseEngine_X64.exe /quiet /passive /norestart' returned a non-zero code: 3221225781

## Additional information (e.g. issue happens only occasionally)
It always happen

## Output of `docker version`

```
**Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 19.04GiB
 Name: docker-desktop
 ID: BCK2:ZHNQ:6C2V:DHDX:7SHG:4HE6:RBJO:ZH45:3WZB:FS73:DT7S:AQGZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 74
  Goroutines: 90
  System Time: 2020-03-08T23:35:04.348150978Z
  EventsListeners: 5
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
Did you look for any installer logs?  I would be surprised if the AccessDatabaseEngine_X64.exe supports running on Nano Server.  You may need to create a Windows Server Core image to be able to run this installer.  [This documentation](https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/installing-dotnet.md) may be of help in regards to creating your own .NET image based on Windows Server Core.

**Comment by SebastienHo** [comment]
Thanks for your answer,

I have tested the following dockerfile

FROM mcr.microsoft.com/windows/servercore:1809
MAINTAINER TraceParts Team
WORKDIR /
EXPOSE 80

#Pass variables
ARG VERSION=""
ARG APP_NAME=""
ARG APP_PROJ=""

ENV ASPNETCORE_ENVIRONMENT="Local"
ENV DLL_NAME "${APP_NAME}.dll"

# Install Access database engine
# escape=\
COPY "./.cicd/docker/Windows/netcoreapp3.1/AccessDatabaseEngine_X64.exe" C:
RUN C:\AccessDatabaseEngine_X64.exe /quiet /passive /norestart

#install dotnet core 3.1
RUN powershell -Command \
        $ErrorActionPreference = 'Stop'; \
        $ProgressPreference = 'SilentlyContinue'; \
        Invoke-WebRequest \
            -UseBasicParsing \
            -Uri https://dot.net/v1/dotnet-install.ps1 \
            -OutFile dotnet-install.ps1; \
        ./dotnet-install.ps1 \
            -InstallDir '/Program Files/dotnet' \
            -Channel 3.0 \
            -Runtime dotnet; \
        Remove-Item -Force dotnet-install.ps1 \
    && setx /M PATH "%PATH%;C:\Program Files\dotnet"


COPY "./.cicd/docker/Windows/netcoreapp3.1/AccessDatabaseEngine_X64.exe" .
RUN AccessDatabaseEngine_X64.exe /quiet /passive /norestart
RUN powershell -Command Remove-Item AccessDatabaseEngine_X64.exe -Force -Recurse

WORKDIR /app

COPY "./.cicd/publish/${APP_NAME}" .

CMD set ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
CMD echo %DLL_NAME%
CMD dotnet %DLL_NAME%

On my local development machine (latest docker desktop version ) : it works.

On our CI build machine (Windows core 2019), it fails. Our CI server runs the container with Hyper-V isolation

Sending build context to Docker daemon  609.4MB
Step 1/20 : FROM mcr.microsoft.com/windows/servercore:1809
---> 73d9a9b9c9fb
Step 2/20 : MAINTAINER TraceParts Team
---> Using cache
---> 93e8a995016a
Step 3/20 : WORKDIR /
---> Using cache
---> a08b1f7c25b0
Step 4/20 : EXPOSE 80
---> Using cache
---> 3e419071d207
Step 5/20 : ARG VERSION=""
---> Using cache
---> d439f6e75f40
Step 6/20 : ARG APP_NAME=""
---> Using cache
---> 88ae7c9578ed
Step 7/20 : ARG APP_PROJ=""
---> Using cache
---> 4739726689c7
Step 8/20 : ENV ASPNETCORE_ENVIRONMENT="Local"
---> Using cache
---> 7ecb14cd119a
Step 9/20 : ENV DLL_NAME "${APP_NAME}.dll"
---> Using cache
---> 93cc5d30eee6
Step 10/20 : COPY "./.cicd/docker/Windows/netcoreapp3.1/AccessDatabaseEngine_X64.exe" C:
---> Using cache
---> 6a3e66302314
Step 11/20 : RUN C:\AccessDatabaseEngine_X64.exe
---> Running in afc1b85b46c1
The command 'cmd /S /C C:\AccessDatabaseEngine_X64.exe' returned a non-zero code: 3221225785

Here is my CI build machine docker configuration :

Client: Docker Engine - Enterprise
Version:           19.03.5
API version:       1.40
Go version:        go1.12.12
Git commit:        2ee0c57608
Built:             11/13/2019 08:00:16
OS/Arch:           windows/amd64
Experimental:      false

Server: Docker Engine - Enterprise
Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false

Is it a miss configuration on the CI server?

Thanks for your help.


De : Michael Simons <notifications@github.com>
Envoyé : jeudi 12 mars 2020 15:16
À : dotnet/dotnet-docker <dotnet-docker@noreply.github.com>
Cc : Sébastien Ho <sebastien.ho@traceparts.com>; Author <author@noreply.github.com>
Objet : Re: [dotnet/dotnet-docker] Unable to install AccessDatabaseEngine_X64.exe on mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 (#1740)


Did you look for any installer logs? I would be surprised if the AccessDatabaseEngine_X64.exe supports running on Nano Server. You may need to create a Windows Server Core image to be able to run this installer. This documentation<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdotnet-docker%2Fblob%2Fmaster%2Fsamples%2Fsnippets%2Finstalling-dotnet.md&data=01%7C01%7Csebastien.ho%40traceparts.com%7Ce0c2d5d88a8447930d4d08d7c68fe1db%7C0b42243bc3e74087bce35035455944ba%7C0&sdata=xEMqF2VyXm945WAYJ3Dc1rZ1NgiWasUycARg9Jk4les%3D&reserved=0> may be of help in regards to creating your own .NET image based on Windows Server Core.

**Comment by MichaelSimons** [comment]
@SebastienHo - This is a question for the Access folks or to ask on the [Windows Containers Forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers) since it is unrelated to the dotnet/core images.

I do have a couple suggestions to try.

1. Try running as the ContainerAdministrator.  The default user is ContainerUser.  I am skeptical this will help since it works locally for you.
2. Have you tried running with Hyper-V isolation locally?  This may help you pinpoint the differences between the two environments.
3. If you have a repo environment, try running the installer from a container interactively versus from your Dockerfile.  Once you do this, you should be able to look for the installation logs which may give you some clues.

Closing as this issue is unrelated to the dotnet/core images.
