### ISSUE TITLE
Please add back DOTNET_SDK_VERSION environment variable in 3.1 SDK images

### ISSUE THREAD

**Issue by LordNibbler274** [dotnet/dotnet-docker#1743]
It appears that the 3.1 SDK images no longer set the DOTNET_SDK_VERSION environment variable, that is available in the 2.1 images. Can we add it back please as this made it very simple to fully qualify the path to the SDK?

**Comment by richlander** [comment]
Can you describe the underlying scenario where you need access to this path? Thanks.

**Comment by LordNibbler274** [comment]
This is probably quite niche but I would like to be able to call vstest.console.dll in the container:

https://github.com/G-Research/DotNetDockerTest/blob/fe38bc8b0b3d0a0f7f73349d66f71324ae0db5d3/src/DockerVSTestTask.cs#L191

Having this variable set means that I don't need to know the container or the specific SDK version being used in order for this to work.

**Comment by MichaelSimons** [comment]
When fixing this, we want to ensure the ENV is set consistently across all images.  In the 2.1 images it is not set in the images that are built with multi-stage Dockerfiles.

**Comment by MichaelSimons** [comment]
A potential workaround would be to grab the version from dotnet output of `dotnet --info` or `dotnet --list-sdks`

**Comment by richlander** [comment]
Wouldn't `dotnet --version` be better? No parsing.

**Comment by MichaelSimons** [comment]
That works if you want the SDK version within the SDK image but doesn't work if you want the runtime version.

The scenario in which I think this would be useful is a slight permutation of the scenario originally described.  For the crossgen usage scenarios we would want to users to be able to write SDK based dockerfiles the contain the following following:

`dotnet publish -c release -o /app --no-restore --target-version $DOTNET_VERSION`

**Comment by LordNibbler274** [comment]
I think that adding DOTNET_VERSION seems like a good way to go. Ultimately anything that is consistent between the different images is fine for my purposes. For the short term my workaround has simply been to build off the microsoft image and add the environment variable myself but being able to use the official image would be much better, thanks.
