### ISSUE TITLE
amd64 Dockerfile should be using an platform specific FROM image

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#1758]
The amd64 Dockerfile should be using an platform specific FROM image (e.g. `amd64/debian:buster-slim` vs `debian:buster-slim`).  This makes the amd64 Dockerfiles ([example](https://github.com/dotnet/dotnet-docker/blob/master/3.1/runtime-deps/buster-slim/amd64/Dockerfile#L1)) inconsistent with the arm Dockerfiles ([example](https://github.com/dotnet/dotnet-docker/blob/master/3.1/runtime-deps/buster-slim/arm64v8/Dockerfile#L1)).  Because of this the amd64 dockerfiles will not behave correctly when built on other platforms besides amd64.

Another side affect of this is the base image monitoring infrastructure that triggers builds when the base image changes is not working optimally.  The base image monitoring infrastructure is monitoring the multi-platform digests instead of the concrete images.  This means it is possible that a build gets triggered unnecessarily when manifest entries change outside of the amd64 entry.

**Comment by MichaelSimons** [comment]
Friendly reminder that the 2.1 and 3.1 focal Dockerfiles in nightly need to be fixed since they are only in the nightly branch.

**Comment by mthalman** [comment]
Focal Dockerfiles were updated as part of https://github.com/dotnet/dotnet-docker/pull/1787.  Closing.
