### ISSUE TITLE
Update tag for next 5.0 preview release

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1780]
Currently the tag is `5.0.0-preview` but tags for the next preview release should be distinguished from the first preview release.  The proposal would be to have a tag value of `5.0.0-preview.2` since the versioning scheme of the release artifacts is `5.0.0-preview.2.<build>`.  This will require a change to the update-dependencies tool to parse this version string appropriately.

**Comment by MichaelSimons** [comment]
This was fixed in https://github.com/dotnet/dotnet-docker/pull/1785/files
