### ISSUE TITLE
How to add compilation symbols?

### ISSUE THREAD

**Issue by Metrowerks** [dotnet/dotnet-docker#1797]
Hi, how can I add compilation symbols to my S2I build? I have tried using the DOTNET_CONFIGURATION variable but it seems to only allow Release or Debug. 

I was using the .Net Core 2.1 Docker image.

**Comment by aslicerh** [comment]
@Metrowerks 

Hi, are you using the Redhat or Centos based images? If so, you should file a ticket at https://github.com/redhat-developer/s2i-dotnetcore

Also, can you clarify if you're looking for symbols for the base .NET Core libs or for your own source code? Or just some more details in general in what exactly you're trying to do?

**Comment by Metrowerks** [comment]
@aslicerh 
Hi aslicerh, I'm using the Redhat one. I'm trying to use compilation symbols for my source code to skip certain blocks of code for different environment when I build the solution.

**Comment by MichaelSimons** [comment]
Per @aslicerh's suggestion, please file a ticket at https://github.com/redhat-developer/s2i-dotnetcore.
