### ISSUE TITLE
Performance test the various crossgen2 options

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#1821]
This issue tracks the work to do performance testing on the various crossgen2 options discussed in #1791.  The work to implement the Dockerfile is tracked under #1820.

The performance testing should include analyzing the startup time, execution time as well as analyze the size of the various images including the size of the shared layers.

**Comment by MichaelSimons** [comment]
The following table provides the sizes of the the various crossgen2 options discussed in #1791.  These were produced from https://github.com/dotnet/dotnet-docker/commit/942d7ee9faacac8a37c17d5cb40becdbbd972bd0 by running `.\build-and-test.ps1 -Version 5.0 -OS alpine3.11 -Mode Build`

| Image                                        | Dockerfile                                                                                                                                           | Base Image                | Total Size | Owned Layers Size | Shared Layers Size | 
|----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------|------------|-------------------|--------------------| 
| runtime-deps:5.0-alpine3.11                  | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/runtime-deps/alpine3.11/amd64/Dockerfile)                  | alpine:3.11               | 9.41       |                   |                    | 
| runtime:5.0-alpine3.11                       | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/runtime/alpine3.11/amd64/Dockerfile)                       | runtime-deps              | 90.2       | 80.79             | 9.41               | 
| runtime:5.0-alpine3.11-composite             | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/runtime/alpine3.11/amd64/composite/Dockerfile)             | runtime-deps              | 117        | 107.59            | 9.41               | 
| aspnet:5.0-alpine3.11                        | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/aspnet/alpine3.11/amd64/Dockerfile)                        | runtime                   | 108        | 17.8              | 90.2               | 
| aspnet:5.0-alpine3.11-composite              | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/aspnet/alpine3.11/amd64/composite/Dockerfile)              | runtime-deps              | 152        | 142.59            | 9.41               | 
| aspnet:5.0-alpine3.11-composed-composite     | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/aspnet/alpine3.11/amd64/composed-composite/Dockerfile)     | runtime:composite         | 142        | 25                | 117                | 
| aspnet:5.0-alpine3.11-runtime-composite      | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/aspnet/alpine3.11/amd64/runtime-composite/Dockerfile)      | runtime:composite         | 135        | 18                | 117                | 
| sdk:5.0-alpine3.11                           | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/sdk/alpine3.11/amd64/Dockerfile)                           | runtime-deps              | 418        | 408.59            | 9.41               | 
| sdk:5.0-alpine3.11-aspnet-base               | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/sdk/alpine3.11/amd64/aspnet-base/Dockerfile)               | aspnet                    | 418        | 310               | 108                | 
| sdk:5.0-alpine3.11-aspnet-composite          | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/sdk/alpine3.11/amd64/aspnet-composite/Dockerfile)          | aspnet:composite          | 462        | 310               | 152                | 
| sdk:5.0-alpine3.11-aspnet-composed-composite | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/sdk/alpine3.11/amd64/aspnet-composed-composite/Dockerfile) | aspnet:composed-composite | 452        | 310               | 142                | 
| sdk:5.0-alpine3.11-runtime-composite         | [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/feature/r2r-version-bubbles/5.0/sdk/alpine3.11/amd64/runtime-composite/Dockerfile)         | aspnet:runtime-composite  | 445        | 310               | 135                | 

**All sizes (MB) are the expanded image on disk**

**Comment by MichaelSimons** [comment]
cc @richlander, @davidwrighton

**Comment by MichaelSimons** [comment]
@davidwrighton - you mentioned the following at https://github.com/dotnet/dotnet-docker/pull/1775#issue-394508076

>The produced image is 152MB, 86MB of which is the composite shared image with just the R2R code in it. Previous efforts on size reduction of the R2R images are not reflected in this number, and will need to be rebuilt

Are these size reduction changes checked in?  Do you know what build of crossgen2 I should be trying to get?

**Comment by MichaelSimons** [comment]
@richlander, @davidwrighton - When do we want @billwert to run some perf tests against these proposed options?  What functional validation should we be doing?  I have hooked up the docker tests which run and e2e app scenario with these new images.

@billwert - Do you have the infrastructure in place to measure containerized app startup?  In order to test the images do you need them published to a Docker registry?

**Comment by davidwrighton** [comment]
@MichalSimons size reduction changes will require significant work. It will take a month or two once we are focussed on it.

**Comment by davidwrighton** [comment]
Also, we are actively working on the correctness of these larger composite images. At the moment, I have relatively little confidence in correctness, but that confidence should grow rapidly over the next month or so.
