### ISSUE TITLE
Docker .Net Core Life Cycle Clarification

### ISSUE THREAD

**Issue by jbaig** [dotnet/dotnet-docker#1842]
I just wanted to get some clarification for planning on the life cycle of using .net core on Docker on a Windows Server.  
Over the past year, all of the official .net core 2016 images have stopped being supported mostly because the underlying supported nanoserver versions that they use as the base reached end of life.
Although the server version may be LTSC, the official .net core images are based on nanoserver which uses the Semi Annual Channel and is only supported for 1.5 to sometimes 2 years. Potentially meaning that the an official .net core docker image for each major server version (2016/2019/etc) would only be supported up to 1 year after the release of the next major server version.

For example the latest nanoserver will reach EOL in 5/2021.  If a new version of Windows Server comes out this year, is the plan that official .net core images will only be kept being supported on 2019 until 2022 assuming one more version of nanoserver that works on 2019 is released as well this year.

Then for planning purposes, for an application running in docker with .net core to keep using official images, the application will have to be migrated to a new Windows Server version potentially within a year of its release in order to not have to roll your own image using the larger servercore images.

Additional References:
#1041 - Nano Server 2016 and 1709 no longer Supported by .NET Core
#1469 - Windows Server, version 1803 no longer supported by .NET Core 
[Base Image Lifecycle](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle)
[Windows Server End of Life](https://endoflife.software/operating-systems/windows/windows-server)
[Servicing Channels](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19#should-you-keep-servers-on-the-ltsc-or-move-them-to-the-semi-annual-channel)

**Comment by richlander** [comment]
Thanks for the feedback. This isn't the first time we've seen this request. I created a general request for feedback on this @ #1852. We will wait for more feedback to come in. Feel free to provide your feedback on that issue, too.

**Comment by julioas09** [comment]
As consultant, I have seen several customers run into this problem. They need stable environments (banking, health...) and use Windows Server LTSC hosts. Since Nano Server support lifecycle is only 18 months, they are forced to use Server Core images.
What is the point of a nanoserver version for ltsc if the support is only 18m?

**Comment by MichaelSimons** [comment]
We will be using #1852 to track the discussion around adding Server Core images.
