### ISSUE TITLE
MS SQL connection issue with Asp.net core runtime image for alpine and buster-slim tags. 

### ISSUE THREAD

**Issue by Cool-Ravi** [dotnet/dotnet-docker#1851]
## Steps to reproduce the issue
1. Create asp.net core 3.1 application with method to connect to SQL and get data.
2. Create DOCKERFILE with base image as "FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS base" and build image as "FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build"
3. Build and run the image. 

## Expected behavior
Should able to connect to SQL DB and get the data.

## Actual behavior
Getting error in sql connection while opening connection.

## Additional information (e.g. issue happens only occasionally)
This issue is with Asp.net core runtime image for tags alpine and buster-slim whereas it is working for 3.1-bionic tag.

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by mthalman** [comment]
Could you be more specific regarding the error you're seeing?  Could you also provide some sample code that causes the error?

**Comment by MichaelSimons** [comment]
Given the statement that this works with bionic but not alpine or buster, my suspicion is that you are encountering this issue described in dotnet/SqlClient#222.

**Comment by Cool-Ravi** [comment]
> Given the statement that this works with bionic but not alpine or buster, my suspicion is that you are encountering this issue described in [dotnet/SqlClient#222](https://github.com/dotnet/SqlClient/issues/222).

Yes, it's kind of same. What is solution ?

**Comment by MichaelSimons** [comment]
Please consult the referenced thread where it mentions the necessary SQL configuration changes or a workaround of using an Ubuntu image.
