### ISSUE TITLE
Support for x86 only .NET Core apps

### ISSUE THREAD

**Issue by profnimrod** [dotnet/dotnet-docker#1874]
Are there any published base images I can use to create a Windows Docker container that targets x86 only?  The reason I need it is that I have a .NET Core 3.1.3. Web Service that makes use of a C++ DLL (compiled for Win32).  All works fine when self-hosted and targeting x86, but fails when I add the default Windows docker support in Visual Studio 2019.

**Comment by MichaelSimons** [comment]
We do not provide `x86` .NET Core images, only x64 and arm32/64.  You could easily produce your own x86 image variant.  We have some guidance for creating your own .NET Core images [here](https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/installing-dotnet.md).

**Comment by MichaelSimons** [comment]
x86 Windows images don't exist so you would would incur the overhead of running x86 in an x64 environment.

We have no intention of adding x86 to our x64 images.
