### ISSUE TITLE
[Bug?]  We cannot run a console .net core application made by dotnet publish

### ISSUE THREAD

**Issue by nicoclau** [dotnet/dotnet-docker#1896]
## Steps to reproduce the issue
1. docker run --rm -it mcr.microsoft.com/dotnet/core/sdk:3.1.201-buster
2. root@01f869de746d:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
3. root@01f869de746d:/# mkdir DotNetTest
root@01f869de746d:/#
4. root@01f869de746d:/# cd DotNetTest/
root@01f869de746d:/DotNetTest#
5. root@01f869de746d:/DotNetTest# dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /DotNetTest/DotNetTest.csproj...
  Restore completed in 158.37 ms for /DotNetTest/DotNetTest.csproj.

Restore succeeded.

6. root@01f869de746d:/DotNetTest# dotnet publish -c Release -o Publish
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 40.18 ms for /DotNetTest/DotNetTest.csproj.
  DotNetTest -> /DotNetTest/bin/Release/netcoreapp3.1/DotNetTest.dll
  DotNetTest -> /DotNetTest/Publish/
root@01f869de746d:/DotNetTest#

7. root@01f869de746d:/DotNetTest# cd Publish/
root@01f869de746d:/DotNetTest/Publish#

8. root@01f869de746d:/DotNetTest/Publish# dotnet run DotNetTest.dll
Couldn't find a project to run. Ensure a project exists in /DotNetTest/Publish, or pass the path to the project using --project.

9. root@01f869de746d:/DotNetTest/Publish# cd ..
root@01f869de746d:/DotNetTest# dotnet run DotNetTest.dll
Hello World!
## Expected behavior

The Release version to run with the command 
root@01f869de746d:/DotNetTest/Publish# dotnet run DotNetTest.dll
Hello World!

## Actual behavior

root@01f869de746d:/DotNetTest/Publish# dotnet run DotNetTest.dll
Couldn't find a project to run. Ensure a project exists in /DotNetTest/Publish, or pass the path to the project using --project.

## Output of `docker version`

 docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Output of `docker info`

docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 25
  Running: 23
  Paused: 0
  Stopped: 2
 Images: 109
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: RIDT:YKXL:3D7D:HFSP:OVKX:YNUW:AEJS:LPVH:DNON:CE67:3QYV:RCVV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 178
  Goroutines: 171
  System Time: 2020-05-07T19:34:51.348103313Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by omajid** [comment]
Try running just `dotnet DotNetTest.dll` instead of `dotnet run DotNetTest.dll`.

The [documentation for `dotnet run`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run) says:

> The `dotnet run` command is used in the context of projects, not built assemblies. If you're trying to run a framework-dependent application DLL instead, you must use `dotnet` without a command. For example, to run `myapp.dll`, use:

>     dotnet myapp.dll

**Comment by nicoclau** [comment]
Thanks for your answer.
It works, it is weird because I did 

'dotnet run DotNetTest.dll' with Jenkins + Docker 

it worked in the publish directory.

Can you please tell what is the file without extension DotNet beside DotNet.dll ?

Thanks

$ dotnet DotNet.dll
Hello World!
$ ls -la
total 0
drwxrwxrwx 1 root root  4096 May  7 23:06 .
drwxrwxrwx 1 root root  4096 May  7 23:06 ..
-rwxr-xr-x 1 root root 86424 May  7 23:06 DotNet
-rwxr-xr-x 1 root root   388 May  7 23:06 DotNet.deps.json
-rwxr-xr-x 1 root root  4608 May  7 23:06 DotNet.dll
-rwxr-xr-x 1 root root   632 May  7 23:06 DotNet.pdb
-rwxr-xr-x 1 root root   146 May  7 23:06 DotNet.runtimeconfig.json

**Comment by MichaelSimons** [comment]
`DotNetTest` is a platform specific executable that is an alternative to using `dotnet DotNetTest.dll`.  Please see the [runtime-dependent executable documentation](https://docs.microsoft.com/en-us/dotnet/core/deploying/#produce-an-executable) for more details.

I'm not sure why the Jenkins Docker image behaves the way it does.  I would not expect that to work.
