### ISSUE TITLE
HttpClient causing SSL certificate issues when running .NET 5.0 inside Docker (Linux Container Host)

### ISSUE THREAD

**Issue by tareksharbak** [dotnet/dotnet-docker#1897]
Trying to call any HTTPS endpoint using .NET 5.0 running in Docker (Linux Container Host) is causing the call to fail with the following exception:
System.Net.Http.HttpRequestException: 'The SSL connection could not be established, see inner exception.'
Inner Exception:
AuthenticationException: The remote certificate is invalid according to the validation procedure.

This is happening when running the code in a Docker container in both Kubernetes (AKS) or locally using Docker for Windows.

Affected .NET Version: .NET 5.0 Preview 3.

Repro steps:
- In Visual Studio 2019 Preview v16.6.0 Preview 5.0, create a new Console Application
- Add the following code: 
```cs
HttpClient httpClient = new HttpClient();
var response = await httpClient.GetAsync("[Any HTTPS Endpoint");
```
- Right click on the project and add Docker Support
- Run inside Docker (Linux Containers)

Running the code either locally (without Docker) or by downgrading to .NET 3.1 solves the issue without any code changes.

**Comment by MichaelSimons** [comment]
`curl` was removed intentionally from the runtime images as it is not a product requirement and has had some critical vulnerabilities which is undesirable.  Dropping `ca-certificates` was an oversight and is something that should be covered in the container tests.

**Comment by davidsh** [comment]
>Dropping ca-certificates was an oversight and is something that should be covered in the container tests.

Is there going to be PR for dotnet/dotnet-docker to fix the images to add back `ca-certificates` ?

**Comment by MichaelSimons** [comment]
>Is there going to be a PR for dotnet/dotnet-docker to fix the images to add back ca-certificates ?

Yes

**Comment by mthalman** [comment]
This fix is in the [5.0](https://hub.docker.com/_/microsoft-dotnet) Preview 4 images.

**Comment by mburumaxwell** [comment]
I am experiencing this same issue running net core 3.1. I have noticed that if the image is based on 3.1.3-buster-slim, the error does not show but all *-buster-slim images afterward have this error. It surprisingly also not present when running with 3.1-alpine or 3.1*-alpine. The particular certificate missing is the GeoTrust Global CA one. The endpoint being accessed is  https://api.push.apple.com

**Comment by mthalman** [comment]
@mburumaxwell - This is due to the version of ca-certificates that is available in the Buster package feed.  See https://github.com/dotnet/dotnet-docker/issues/2145#issuecomment-669217855.  In the case of Alpine, it is still using an earlier version of ca-certificates.

**Comment by edwin1222** [comment]
> ca-certificates package

Hi, can you share how to add the ca-certificates package?

Thanks!

**Comment by mthalman** [comment]
> Hi, can you share how to add the ca-certificates package?

Can I ask why you're asking? The `ca-certificates` package is included in the .NET container images by default so it's not necessary to add it. Or are you asking how this is done in general when not using the .NET container images. In that case, then it depends on what Linux distro you're targeting. If the Linux distro has `apt-get`, you'd install it in the following way:

```Dockerfile
RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by edwin1222** [comment]
> > Hi, can you share how to add the ca-certificates package?
> 
> Can I ask why you're asking? The `ca-certificates` package is included in the .NET container images by default so it's not necessary to add it. Or are you asking how this is done in general when not using the .NET container images. In that case, then it depends on what Linux distro you're targeting. If the Linux distro has `apt-get`, you'd install it in the following way:
> 
> ```dockerfile
> RUN apt-get update \
>     && apt-get install -y ca-certificates \
>     && rm -rf /var/lib/apt/lists/*
> ```

 I am asking because ive been getting error. "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel" I thought maybe its related to ca-certificates package. 
Im running windows container on windows server. The app works except it gives SSL/TLS error on making http api calls.
Thanks!

**Comment by mthalman** [comment]
> I am asking because ive been getting error. "_The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel_" & "_The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot_"
> I thought maybe its related to ca-certificates package.
> Im running windows containers (aspnet:4.8 & aspnet:5.0) on windows server.

Since you're using Windows containers, `ca-certificates` is not relevant because that's a Linux package. The reason for the error is completely dependent on your configuration and what you're attempting to access. Since it's not relevant to this issue, please post a discussion to either https://github.com/dotnet/dotnet-docker/discussions (.NET Core/.NET) or https://github.com/microsoft/dotnet-framework-docker/discussions (.NET Framework), depending on which platform you're targeting.
