### ISSUE TITLE
Allow multiple product family readmes to be referenced in manifest

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1902]
Now that we'll have two different product families based on `dotnet` and `dotnet/core`, there should be a way to define independent base README files for each product family and reference them from the manifest.  Currently the manifest only reference one root README.  See https://github.com/dotnet/docker-tools/pull/520#pullrequestreview-409201164

**Comment by MichaelSimons** [comment]
We decided to cleanup this special logic once it is no longer needed (https://github.com/dotnet/docker-tools/issues/523).  There isn't a need to add long term support for multiple product families in a single manifest.
