### ISSUE TITLE
Add README for feature/r2r-version-bubbles branch

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#1913]
The [feature/r2r-version-bubbles branch](https://github.com/dotnet/dotnet-docker/tree/feature/r2r-version-bubbles) includes an experimental feature and direction for improving container performance. It include three (I think) variants of the experiment, with the goal of defining the sweet spot(s) between performance and developer UX.

We should consider the following:

- Add a README (of some name; maybe `README-branch.md` or `README-experiement.md` that describes the goals, the feature, and the experiments we intend to do. 
  - The file would be deleted (or moved to a separate doc that describes the new nature of .NET container images ) upon merge to master.
  - This would also describe the specific Dockerfiles and what we are intending to achieve with each one.
  - It would also instruct people (like our perf team) on the progression we recommend for testing these options.
- Publish experimental images to the `nightly` or repo or other repo in a publicly-accessible registry.

**Comment by MichaelSimons** [comment]
Added a [readme ](https://github.com/dotnet/dotnet-docker/tree/feature/r2r-version-bubbles) to the branch.  The work to publish the images to `nightly` is being put on hold for now.
