### ISSUE TITLE
Templating system for readmes

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1931]
With the introduction of a new set of readme files from https://github.com/dotnet/dotnet-docker/pull/1919, maintenance of readme markdown files is becoming increasingly more complex, time consuming, and error prone.  If mistakes are made in the readmes, it can cause confusion with readers and a shows a lack of professionalism.

A way to solve this problem is by creating a templating system that can generate readme files from a set of template files.  A template file would be a mix of static content and dynamic content that is injected to account for variation amongst the readme files.  There are several libraries that provide this kind of functionality (a good example is https://r3c.github.io/cottle/).

Benefits:
* A template would allow for consistent changes across all readme files.  Currently, making a consistent change across the readme files could result in updates to 10 different files.  This could potentially be reduced down to changing a single file.
* One master template could be defined that can account for variations in both master and nightly branches.  This would make diffing between the branches simpler because the template should always be the same between the two branches even though the outputted readme files would be different.  Currently, it can be difficult to determine which changes need to be merged from one branch to another because there are inherent differences between the readmes in the two branches that need to be maintained.

**Comment by mthalman** [comment]
@MichaelSimons - I think this can be closed now, right?

**Comment by MichaelSimons** [comment]
yes.
