### ISSUE TITLE
Prebuild Windows-based images to simship with Windows release

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1941]
We should consider having our .NET Docker images based on Windows to be built ahead of Patch Tuesday so that we can simship those images with Windows

Benefits:
* Consumers of .NET Docker images on Windows have immediate access to updated images as soon as Windows releases.
* Lowers the number of Windows build agents needed for a speedy release.  (Only .NET Framework would require the build agents.)

**Comment by MichaelSimons** [comment]
We do release the .NET images shortly after the base image updates.  When there are .NET releases the same day as the Windows release, we would not be able to pre-build the images because the .NET artifacts must be publicly available.  The ROI for doing this work is minimal.  Closing as won't fix.
