### ISSUE TITLE
Should I be able to build a lib targeting net45 from within a microsoft/dotnet:1.1.0-sdk-projectjson container?

### ISSUE THREAD

**Issue by lewislabs** [dotnet/dotnet-docker#197]
## Steps to reproduce the issue
Using `microsoft/dotnet:1.1.0-sdk-projectjson` should I be able to build a library that targets "netcoreapp1.0" and "net452"?

Here's my project.json
```
{
    "version": "2.0.0-*",
    "buildOptions": {
        "debugType": "portable"
    },
    "dependencies": {},
    "frameworks": {
        "net45": {
            "frameworkAssemblies": {
                "System.Runtime.Serialization": "4.0.0"
            }
        },
        "net451": {
            "frameworkAssemblies": {
                "System.Runtime.Serialization": "4.0.0"
            }
        },
        "net452": {
            "frameworkAssemblies": {
                "System.Runtime.Serialization": "4.0.0"
            }
        },
        "netcoreapp1.0": {
            "dependencies": {
                "System.Globalization": "4.0.11",
                "System.Collections": "4.0.11",
                "System.Threading": "4.0.11",
                "System.Runtime.Serialization.Primitives": "4.1.1"
            }
        }
    }
}
```

When I build this on my host machine (`dotnet build`) it works fine. But when I try to build the project inside a container I get 
` error NU1001: The dependency System.Runtime.Serialization >= 4.0.0 could not be resolved.` for the 3 .NET Framework targets. 

## Expected behavior

The `dotnet build` works inside the container. 

## Actual behavior
`error NU1001: The dependency System.Runtime.Serialization >= 4.0.0 could not be resolved`. for the 3 .NET Framework targets.

## Additional information (e.g. issue happens only occasionally)
my host version of the dotnet sdk is `1.0.0-preview2-003156`

## Output of `docker version`

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

## Output of `docker info`

```
Containers: 24
 Running: 2
 Paused: 0
 Stopped: 22
Images: 386
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 450
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: CDTV:LLDK:KDNV:K2X4:2NLQ:DXGE:XLXG:OGMC:SO6Z:KNXJ:H2LP:XE4U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by natemcmaster** [comment]
> Should I be able to build a lib targeting net45

Short answer: not by default. .NET Framework is a Windows-only component. The image is Linux based, so it doesn't have the .NET Framework assemblies installed.

I'd recommend looking into targeting 'netstandard1.0' or 'netstandard1.1' instead of cross-compiling. These are compatible with both .NET Core and .NET Framework 4.5.

**Comment by lewislabs** [comment]
Would love to target netstandard but unfortunately we need to reference System.Runtime.Serialization for the Datacontractattribute.

**Comment by lewislabs** [comment]
It does build fine though if mono is installed in the container. I'm not sure if that's a blessing or a hidden feature though!

**Comment by natemcmaster** [comment]
Are you referencing https://www.nuget.org/packages/System.Runtime.Serialization.Primitives/? Haven't tried it myself, but docs say it contains the  Datacontractattribute.

Referencing mono is a close approximation of .NET Framework...with a few corner cases. It makes the container really big though, so we don't plan to put that in our images.

**Comment by lewislabs** [comment]
Yes we are referencing System.Runtime.Serialization.Primitives. I didn't think that would work across .NET Framework as well. I'll have another try.

**Comment by lewislabs** [comment]
Seems like this has worked fine for our use case. Thanks for the clarity @natemcmaster

**Comment by natemcmaster** [comment]
Happy to help!
