### ISSUE TITLE
Image size regression for 2.1 runtime-deps on Alpine 3.12

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1973]
The changes to add support for Alpine 3.12 introduced a sizeable increase to the 2.1 runtime-deps image.  It went from 12.3 MB in Alpine 3.11 to 55.5 MB in Alpine 3.12.  This is because of the addition of a python3 dependency from the lttng-ust package.  This issue tracks the Alpine package issue that was logged as a result of this dependency change: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11610.

**Comment by mthalman** [comment]
This has been fixed in the Alpine package feed.  The python3 package is no longer a dependency.  It's been made a dependency of the sub-package lttng-ust-tools.

**Comment by MichaelSimons** [comment]
Won't the image size baseline need to be updated?
