### ISSUE TITLE
No executable found matching command “dotnet-/../.dll” when running dotnet core docker image in Azure Web App on Linux

### ISSUE THREAD

**Issue by devedse** [dotnet/dotnet-docker#198]
Hi all, I'm running into an issue with running the docker dotnet image on the Linux containers in Azure. I'm not exactly sure if this issue is related to the docker image itself or to something strange Azure is doing, but since I haven't been able to get any response on my post on Stackoverflow, I wanted to try it here as well :).

A very detailed description of my issue can be found on the following link:
http://stackoverflow.com/questions/41958888/no-executable-found-matching-command-dotnet-dll-when-running-dotnet-core

In summary:
Whenever I try to run my docker container (which does work locally on a Linux VM) on the docker on the Azure Web App For Linux docker container host I see the following message:

2017-01-31T13:11:46.757760723Z No executable found matching command "dotnet-/home/DeveMazeGeneratorCoreWebPublish/DeveMazeGeneratorWeb.dll"

## Steps to reproduce the issue
See my stackoverflow post

## Expected behavior
The container will start and run successfully

## Actual behavior
The following error message is shown when running the container in Azure:
2017-01-31T13:11:46.757760723Z No executable found matching command "dotnet-/home/DeveMazeGeneratorCoreWebPublish/DeveMazeGeneratorWeb.dll"

## Additional information (e.g. issue happens only occasionally)
The container does work from my local machine.

## Output of `docker version`

```
Unknown, is on Azure
```

## Output of `docker info`

```
Unknown, is on Azure
```

**Comment by MichaelSimons** [comment]
@devedse, I took a look at your project/Dockerfile and agree this issue doesn't not seem related to the dotnet image.  I agree something seems suspect with Azure.  I tried reproducing with a new aspnet1.1 project and it worked fine within Azure.  Have you considered asking your question on the [Azure AppService forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview)?

**Comment by devedse** [comment]
Created a post here:
https://social.msdn.microsoft.com/Forums/en-US/a9ff9289-c254-4d35-b8ce-a6ab50f58c48/no-executable-found-matching-command-dotnetdll-when-running-dotnet-core-docker-image-in?forum=windowsazurewebsitespreview

**Comment by MichaelSimons** [comment]
@devedse, just noticed your stackoverflow post was answered.  As we both suspected Azure was doing some magic that was not jiving with your Dockerfile.

**Comment by devedse** [comment]
Yep thanks, forgot to close this one :)
