### ISSUE TITLE
`dotnet-core-nightly` pipeline YAML not configured to disable CI on public build

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1991]
The [dotnet-core-nightly](https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/dotnet-core-nightly.yml) pipeline is used by both internal and public builds.  The YAML, however, is not configured in a way that disables CI.  The registered pipeline however was configured to disable CI through the AzDO pipeline UI.  That UI no longer exists and so the pipeline was "grandfathered" into this behavior.  In order to accurately reflect how the pipeline should behave, the YAML should be updated to enforce this behavior.  That way, if the pipeline in AzDO is ever deleted and added back, then things will continue to work as expected.

**Comment by MichaelSimons** [comment]
@mthalman can this issue be closed?  If not what work is remaining?
