### ISSUE TITLE
Where is the executable file in container?

### ISSUE THREAD

**Issue by verdysh** [dotnet/dotnet-docker#2021]
Hi!
I have next dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder
WORKDIR /src
COPY ./Sources /src
RUN dotnet publish ./MyApp/MyApp.csproj -o /publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as runtime
WORKDIR /host
COPY --from=builder /publish /host
ENTRYPOINT dotnet MyApp.dll
```

If I run container:
```
docker build -t my-app .
docker run --name my-app-container my-app
```
all works fine.

As an experiment, I want to launch the container without launching the application and launch the application there manually:
`docker run --name my-app-container -it --entrypoint "/bin/bash" my-app`

An invitation appears, I am writing:
`dotnet MyApp.dll`

Response:
> bash: dotnet: command not found

Why doesn’t it find **dotnet** if everything in ENTRYPOINT in the dockerfile starts up normally?

**Comment by MichaelSimons** [comment]
@verdysh, I'm not noticing anything incorrect.  Can you try these steps with the .NET Core Docker samples?

``` console
> docker pull mcr.microsoft.com/dotnet/core/samples:aspnetapp
> docker run --name my-app-container -it --entrypoint "/bin/bash" mcr.microsoft.com/dotnet/core/samples:aspnetapp
> dotnet aspnetapp.dll
```

If it works it might be useful to compare the two images (yours vs the sample) to see how they differ.

**Comment by verdysh** [comment]
@MichaelSimons, your example works as expected.

> If it works it might be useful to compare the two images (yours vs the sample) to see how they differ.

Could you tell me in more detail how to do this?

**Comment by MichaelSimons** [comment]
A good thing to check/compare would be to run `whereis dotnet`.  Is it possible for you to share your image (e.g. push it to a public registry)?

**Comment by verdysh** [comment]
@MichaelSimonsI, don’t know what happened, but now I repeated all the actions that I had done before and... everything worked! Sorry to bother you in vain!
