### ISSUE TITLE
Building ASP.NET project results in an MSB1003 ( Specify a project or solution file. The current working directory does not contain a project or solution file.)

### ISSUE THREAD

**Issue by OctopusNetworkDevelopment** [dotnet/dotnet-docker#203]
## Steps to reproduce the issue
1. cd into ASP.NET MVC project made with .NET 4.5 and C#6
2. run `docker run microsoft/dotnet dotnet restore`
3. also happens when I specify project file, solution file, and even nuget package config file

## Expected behavior
Should build the project into it's respective format

## Actual behavior
Throws an error about the project or solution file not existing

## Additional information (e.g. issue happens only occasionally)
Happens all the time. On Windows 10 Home and using the docker terminal

## Output of `docker version`

```
time="2017-02-09T19:20:47Z" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

## Output of `docker info`

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 1
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.47-boot2docker
Operating System: Boot2Docker 1.13.1 (TCL 7.2); HEAD : b7f6033 - Wed Feb  8 20:31:48 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: DB4F:JG5I:7TLD:HERM:7QHO:FYM7:IF77:OLQ7:DARV:X7DE:SKXR:MWAH
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2017-02-09T19:21:49.207701723Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
@OctopusNetworkDevelopment - Does your project have a project.json file or is it msbuild based (e.g. has a csproj)?  I am suspecting you have a project.json file.  If so, please see this [announcement](https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/).     You will need to either use the `1.1.0-sdk-projectjson` Docker image or migrate your project over to msbuild.

**Comment by OctopusNetworkDevelopment** [comment]
@MichaelSimons definitely msbuild based, no project.json and msbuild works in a normal cmd

**Comment by OctopusNetworkDevelopment** [comment]
@MichaelSimons thanks for the quick reply btw

**Comment by MichaelSimons** [comment]
@OctopusNetworkDevelopment, Are you literally running `docker run microsoft/dotnet dotnet restore` within the project directory?  If so, you are going to need to get the project's source code into the Docker container.  The container is empty by default.  You could do this by mounting the current project's directory as a volume within the container or you could create a Dockerfile to do this.  An example of this is [here](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-dev).

**Comment by OctopusNetworkDevelopment** [comment]
@MichaelSimons is it possible to mount my C drive and use my original dev folder? Just to keep everything in the same place that's all...

Just tried and I can't find it

**Comment by MichaelSimons** [comment]
@OctopusNetworkDevelopment, I take it you are running on Windows?  You should be able to do something like `docker run -v c:/:/cdrive microsoft/dotnet`.  You will have to make sure the drive is shared in your Docker settings.

**Comment by MichaelSimons** [comment]
@OctopusNetworkDevelopment - were you able to get your project mounted in the container?  Feel free to close this issue if you were able to `dotnet restore` your project within a container.

**Comment by OctopusNetworkDevelopment** [comment]
@MichaelSimons  couldn't actually find the docker settings, but I decided to go with an ftp deployment strategy instead of a docker machine. Thanks for your help anyway, I'll close it.

**Comment by MichaelSimons** [comment]
@OctopusNetworkDevelopment - For future reference here is the some [documentation on the docker settings for Windows](https://docs.docker.com/docker-for-windows/#/docker-settings)
