### ISSUE TITLE
Enhancement: Publish images with side by side installation of LTS versions

### ISSUE THREAD

**Issue by coderpatros** [dotnet/dotnet-docker#2048]
For projects that target multiple .net core versions it would be great to have images that include 2.1 and 3.1.

Our particular use case is for a dotnet cli command. We are targeting both 2.1 and 3.1.

I know it probably isn't practical to do this for all .net sdk version combinations. But I think it would be reasonable for just long term support releases of the sdk.

There are other ways around this issue. But I think this would greatly simplify things for the consumer, which in this case, is me :)

**Comment by mthalman** [comment]
@coderpatros - Can you provide more detail on what you mean by this:
> Our particular use case is for a dotnet cli command. 

I'm also curious to know what the reasons are for not having all your projects target the same version.  Do the outputs of those projects really need to run within the same container?

**Comment by coderpatros** [comment]
Hi @mthalman 

We target both the 2.1 and 3.1 versions of .net core and publish a nuget package with both included.

What this means is that you can install our dotnet cli command whether you have 2.1 or 3.1 installed. We could just target 3.1. But that would mean existing consumers of the command would need 3.1 installed to use it with their existing 2.1 projects.

2.1 is a long term support release and we would like to offer the same support cycle.

The outputs don't need to run within the same container. What I would like is a container that we could _build_ our project in. Which of course requires both SDK versions.

There are ways we can get around this. But we also want to be able to create deterministic builds. And a way for consumers to independently verify that what has been published is what they are using. One driver for this is high assurance scenarios. But it would also add an extra layer of confidence between OSS maintainers who have never met each other in real life, etc.

I can't remember the project that was affected by this. But there was one where a release was published with no corresponding commit in the public repo. It turned out a maintainer had slipped in a dodgy release.

The simplest way I can think of enabling this is to create release builds in a docker container. That way, regardless of the platform/environment you are running, as long as you have docker, you can re-run the build process and verify the output.

There are other ways to do this. But it is much simpler if we can just `dotnet test` and `dotnet pack` without having to worry about being specific about target frameworks.

It's not a big deal. We can just create our own dockerfile which does this. But as we have two current long term support versions I thought it made sense to have an official docker image which could support OSS maintainers who are building software and trying to follow the same support cycle as upstream.

**Comment by coderpatros** [comment]
I've already started on a dockerfile to do this. So if you want I could raise a PR. But the dockerfile is the easy part. No doubt you need to settle on naming/path conventions, build/release, etc.

But putting it out there that I'm happy to do it. Maybe an LTS tag much like there is a 2.1 and 3.1 tag/path?

But then it gets even more trickier because then there are multiple versions within each version.

**Comment by mthalman** [comment]
Got it.  So you'd be happy with just a multi-version SDK image then?

**Comment by coderpatros** [comment]
@mthalman that would be awesome.

Although, while I have your attention, it would probably be good to also have a LTS SDK preview image too. We've already been testing against 5 to make sure we aren't going to hit any major snags. But when a LTS version of 5 is impending it would help to have an official image.

Once again, easy enough to work around. But it reduces friction for OSS maintainers and is very much appreciated :)

**Comment by mthalman** [comment]
You should be able to use the 3.1 SDK image to build your 2.1 projects.  The SDK allows for previous versions to be built.  Let us know if that fulfills your requirements.

**Comment by coderpatros** [comment]
True, but you can't run tests for frameworks that aren't installed.

**Comment by MichaelSimons** [comment]
There are trade-offs here.  Adding all of the supported runtime versions and variations (e.g. .NET and ASP.NET) to the SDK really increases the size.  This is especially the case for 2.1 because of the lzma cache.  While the use case is valid, it doesn't feel like the 80% usage scenario.  In other words it is useful for your scenario but undesired for others.  This feels like it would be best solved with a custom Dockerfile based on the latest SDK which adds the additional runtimes that are needed.  Alternatively it may be possible to utilize a multi-stage Dockerfile for this.  Build the product using the latest SDK in one phase, and then run the 2.1 tests  in a subsequent phase using the 2.1 SDK.  Another option is to COPY the runtime in from the 2.1 runtime image.

Closing but feel free to continue discussing.

**Comment by coderpatros** [comment]
No problem @MichaelSimons, my thoughts is that it would of been a different tag. So you would only be pulling it down if you specifically wanted all current LTS versions.

But I agree, it probably isn't in the 80%. Or possibly even in the 90%.

We'll continue to use a custom Dockerfile. I was just hoping to push that maintenance upstream :P

**Comment by MichaelSimons** [comment]
@coderpatros - thanks for bringing this scenario to our attention and having a discussion about it.  To be transparent with the problems we face with producing the .NET images, customers have told us they have troubles deciphering which tags to use given the number of distros/architectures/etc we support.  Adding addition image variants such as one with multiple runtimes is going to compound that problem.  If adding a new image variant would solve high usage scenarios it would justify the additional tags and we would consider it.  I don't see this scenario as being one, at least we haven't heard users telling us it is.

**Comment by coderpatros** [comment]
Oh yeah, 100% @MichaelSimons the dockerfile was the easy part.
