### ISSUE TITLE
Installing ef in docker causing errors - Tool 'dotnet-ef' failed to install

### ISSUE THREAD

**Issue by fulminous** [dotnet/dotnet-docker#2054]
## Steps to reproduce the issue
1. Create a docker file using base image "mcr.microsoft.com/dotnet/core/sdk:3.1" and install dotnet-ef using below command
 RUN dotnet tool install --global dotnet-ef --version 3.1.0
2. Run Docker file and it will result into error. 
Here is the docker file content

`FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
  
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY . ./

ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 3.1.0`

## Expected behavior

It should install dotnet-ef but resulting in error

## Actual behavior

> /usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/tmp/234bo1kx.csn/restore.csproj]
/usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error :   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. [/tmp/234bo1kx.csn/restore.csproj]
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

I am trying to run this docker on aws ubuntu 18 machine

**Comment by MichaelSimons** [comment]
@fulminous - have you verified that you have network access within a running container from your configuration?  I ask because it is common for firewalls etc to block network access within containers.

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY . ./

ENV PATH="${PATH}:/root/.dotnet/tools"
RUN ping github.com -c 3
RUN dotnet tool install --global dotnet-ef --version 3.1.0
```

**Comment by fulminous** [comment]
> @fulminous - have you verified that you have network access within a running container from your configuration? I ask because it is common for firewalls etc to block network access within containers.
> 
> ```
> FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
> 
> WORKDIR /app
> EXPOSE 80
> EXPOSE 443
> COPY . ./
> 
> ENV PATH="${PATH}:/root/.dotnet/tools"
> RUN ping github.com -c 3
> RUN dotnet tool install --global dotnet-ef --version 3.1.0
> ```

I can check that but i did not configure any firewall on aws and its a fresh lightsail ubuntu 18 machine. Interesting thing is that some time it works and sometimes it doesn't. Currently it is working fine and able to run the whole docker file.

**Comment by MichaelSimons** [comment]
This appears to be a general network connectivity problem.  I don't suspect this is something specific to the .NET Docker images.  If you have evidence that suggests otherwise please respond.
