### ISSUE TITLE
Create Windows Server Core based images for full fx + core multi targeting

### ISSUE THREAD

**Issue by dasMulli** [dotnet/dotnet-docker#208]
Since you can't build and test applications that multi-target `netcoreapp*` and `net*`, it would be nice to have docker images that have both full framework and a .net core runtime + SDK installed.

**Comment by dasMulli** [comment]
(Related to https://github.com/dotnet/sdk/issues/335 since just adding mono on top of an ubuntu image doesn't work)

**Comment by MichaelSimons** [comment]
@dasMulli, have you considered creating your own image based on https://hub.docker.com/r/microsoft/dotnet-framework/ which adds .net core runtime + SDK?  The concern with adding more image variants on top of what already exists is that we already have issues with the number of image variants and people are having difficulties discerning which image is appropriate for their scenario.  We will continue monitoring the requests for such images and will add images when the demand warrants them.  In the mean time I am going to note this and close the issue.

@Glennc - Seems like this image variant may fall into the image generation/recommendation tool you have been pondering.

**Comment by dasMulli** [comment]
@MichaelSimons yes, just felt that this should be a first-party image (windows server updates, tooling releases etc.).
So just consider it a +1 for that image type ;)

**Comment by glennc** [comment]
@MichaelSimons I agree. I really should do some more implementation and less talking :)
