### ISSUE TITLE
5.0 Dockerfiles still use "core" in the default repo name

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2084]
As part of the changes for https://github.com/dotnet/dotnet-docker/issues/1765, the repo name for the 5.0 images dropped "core" from the name.  But the 5.0 Dockerfiles also have a `REPO` ARG that defines the default repo name to use.  The build infrastructure overrides this based on what's defined in the manifest so the official images end up being tagged correctly.  But if you were to build one of those Dockerfiles without overriding `REPO`, the wrong repo would be used, resulting in an out-of-date base image since that repo is no longer being updated.

Example:
https://github.com/dotnet/dotnet-docker/blob/5731be852a857b3b49acacb75d881f6d516c562c/src/aspnet/5.0/alpine3.12/amd64/Dockerfile#L1

**Comment by MichaelSimons** [comment]
It would be nice to fix this before the next 5.0 preview release (preview 8).
