### ISSUE TITLE
Incorrect PR build leg paths for 5.0 Alpine

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2090]
The changes from https://github.com/dotnet/dotnet-docker/pull/2064 end up causing the 5.0 Alpine PR build leg in nightly to build a bunch of images that should not be built.  This is due to the build matrix generation.  This leg ends up having the following build paths defined for it:

```
--path src/runtime-deps/5.0/alpine3.12/amd64 --path src/runtime/5.0/alpine3.12/amd64 --path src/aspnet/5.0/alpine3.12/amd64 --path src/sdk/5.0/alpine3.12/amd64 --path src/monitor/5.0/alpine/amd64 --path src/sdk/3.1/alpine3.12/amd64 --path src/aspnet/3.1/alpine3.12/amd64
```

It should only be built with the following:

```
--path src/runtime-deps/5.0/alpine3.12/amd64 --path src/runtime/5.0/alpine3.12/amd64 --path src/aspnet/5.0/alpine3.12/amd64 --path src/sdk/5.0/alpine3.12/amd64
```

**Comment by MichaelSimons** [comment]
This should get fixed before merging the `monitor` images to master.
