### ISSUE TITLE
Support building against Mono

### ISSUE THREAD

**Issue by petr-k** [dotnet/dotnet-docker#21]
Now, .NET Framework Reference Assemblies are not available and the image cannot be used to build `net451` targets.

**Comment by ahmetalpbalkan** [comment]
@petr-k are you getting a compilation error?

**Comment by petr-k** [comment]
On `dotnet pack`, I am getting:
`DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.`

I ran bash and tried installing `mono-complete` package and pointing the environment variable above to mono's `xbuild-frameworks` folder, but to no avail.

**Comment by ahmetalpbalkan** [comment]
I haven't used dotnet CLI before. I've only built with MonoDevelop in the past. Any ideas what might be causing that? I am planning to refresh bits on NuGet today or tomorrow, if you could find what is wrong, I really appreciate any fixes. Other than that I'm afraid I don't have a solution here.

**Comment by MichaelSimons** [comment]
This looks related to dotnet/cli#531.

**Comment by ahmetalpbalkan** [comment]
oh I'm sorry I confused this repo with my Docker.DotNet repo, apologies. Ignore my comment.

**Comment by petr-k** [comment]
@MichaelSimons Yes, it's slightly related. Actually, the issue you're linking to led me to the idea to specify the variable myself, one of the comments there also says which paths should be taken into account. I think the primary issue is that the Mono bits are just not included in the image in the first place.

**Comment by borgdylan** [comment]
The CLI does not support mono at all. If you need a variant/fork that does check out the deb package at https://github.com/borgdylan/dotnet-cli.

**Comment by petr-k** [comment]
@borgdylan How does the statement of CLI not supporting mono at all relate, e.g., to the issue @MichaelSimons linked above? It seems that CLI aims to support Mono as well..

**Comment by borgdylan** [comment]
I meant that the stock CLI requires .net core to run plus it ignores the existence of mono debug files while publishing.

**Comment by petr-k** [comment]
What do you mean by "mono debug files", exactly? Is it the reference assemblies?

**Comment by borgdylan** [comment]
mono "pdbs" i.e mdb files are not supported. I will consider patching my fork of the cli that runs on mono so that publish does not fail when no pdbs are present when compiling in debug mode..

**Comment by petr-k** [comment]
The issue I described has nothing to do with the unavailability of runtime debugging information during publishing, but merely the fact that the image lacks the required reference assemblies to target .NET 4.5.x. Can you explain how that relates to your fork? I should not need any forked version of CLI since it does support mono.

**Comment by borgdylan** [comment]
My fork uses mono as the CLR  (targeting net461) instead of CoreCLR. It also pre sets the reference assemblies env var in the bootup scripts.

**Comment by petr-k** [comment]
Running the CLI on mono is not needed for it to target net461, though, or is it? PDBs/MDBs do not play any role here.

**Comment by borgdylan** [comment]
No it does not. But not all machines can run CoreCLR as things stand currently. Also on Linux to run net461 apps mono is needed which supports portable pdb and mdb files only for debugging. Do remember that not all compilers support portable pdb output and still output regular pdb on windows and mdb on Linux/mac.

**Comment by petr-k** [comment]
Just to be perfectly clear - I do not intend to run the output artifacts on Linux. The scenario I am after is to build on Linux, target NET461, run the output on Windows.

**Comment by borgdylan** [comment]
Remember that you will not be able to debug them on windows i.e. the debug symbols will not load due to the path differences and teh differences between portable and regular pdb.

**Comment by MichaelSimons** [comment]
There are no plans to create a supported Mono based image at this time.  If there is a strong demand for it we would reconsider but there isn't at this point.  Closing Issue.
