### ISSUE TITLE
Changing home directory path causes a path error during debugging. 

### ISSUE THREAD

**Issue by jzoss** [dotnet/dotnet-docker#210]
## Steps to reproduce the issue
1. Set your environmental variable HOME variable to some (E.G. C:\Home 
2.  Start a new project in VS2017.. add docker support 
3. Try to Debug. 

## Expected behavior

It should start debugging.

## Actual behavior

Debugging does not start .. you get 

Starting: "docker" exec -i 4da16cb49137 /clrdbg/clrdbg --interpreter=mi
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/clrdbg/clrdbg\": stat /clrdbg/clrdbg: no such file or directory"
"docker" exited with code 126 (0x7E).

## Additional information (e.g. issue happens only occasionally)

So I can look at see that the install script has actually installed the docker image to 

 %UserProfile%\clrdbg

However Looking docker output .. you see 

    volumes:
    - C:\DevTest\WebApplication2\WebApplication2:/app:rw
    - C:\HOME\clrdbg:/clrdbg:ro
    - C:\HOME\.nuget\packages:/root/.nuget/packages:ro

it's installing the package to the  %UserProfile%  but running it from the HOME

**Comment by MichaelSimons** [comment]
@SteveLasker, this looks like a VS 2017 related issue.  Can you have someone on your side take a look at this?  On a related note did you get a location setup where VS related issues like this should be logged?

**Comment by dazhao-msft** [comment]
@jzoss , this is because docker-compose will honor %HOME% over %USERPROFILE% when resolving ~ in docker-compose files. 

The workaround for now is either not setting %HOME% on your box, or using {USERPROFILE} directly in the paths in your docker-compose files.

We're getting rid of ~ in the paths in vNext, which should be able to fix this problem. Thanks for reporting the issue.

**Comment by MichaelSimons** [comment]
Closing issue as this issue is specific to the VS Docker tooling and not directly related to the microsoft/dotnet Docker images.  Per @dazhao-msft [comment](https://github.com/dotnet/dotnet-docker/issues/210#issuecomment-281438427), this is already being tracked with their vNext work.
