### ISSUE TITLE
Unable to pull image from mcr mcr.microsoft.com/dotnet/core/aspnet:3.1 on Windows Server 2016.

### ISSUE THREAD

**Issue by BibhutiBhusanDora** [dotnet/dotnet-docker#2101]
## Steps to reproduce the issue
1. Run powershell in admin mode on Windows Server 2016
2. Run-> docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1

## Expected behavior
Should be able to download the specified image from mcr.

## Actual behavior
Getting below error-
PS C:\> docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1
3.1: Pulling from dotnet/core/aspnet
**no matching manifest for windows/amd64 10.0.14393 in the manifest list entries**
PS C:\>

## Output of `docker version`

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 14393 (14393.3750.amd64fre.rs1_release.200601-1853)
 Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.3750)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 16GiB
 Name: USEDEV27069
 ID: H2T4:SECT:QT2D:S63B:WCO2:EQR6:FYZ3:RJDC:NZHF:YIIV:PVVB:JYYT
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
All I want to know which image should I pull from mcr in order to be able to host WEB API based on .net core 3.1

**Comment by mthalman** [comment]
.NET Core is only released on Windows Nano Server.  Versions of Nano Server compatible with Windows Server 2016 have been out of support for a while now (see https://github.com/dotnet/dotnet-docker/issues/1041).

Your options are to use newer version of Windows for the host OS, such as Windows Server 2019, or to create your own Docker image based on mcr.microsoft.com/windows/servercore:ltsc2016 and [install .NET Core](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/installing-dotnet.md) yourself.

**Comment by mthalman** [comment]
@vbshell - I recommend that you post this question to https://github.com/microsoft/service-fabric/ since it's specific to that service.
