### ISSUE TITLE
Create tests for the monitor images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2117]
A set of unit tests should be created for the `monitor` images.  To conform with the existing tests, two basic tests come to mind.

1. Validate the static state such as the `ENVs` defined in the image.
1. A basic scenario test that ensures dotnet-monitor is installed correctly and is usable.

I consider these tests to be a requirement before merging the images to the master branch.

**Comment by mthalman** [comment]
This issue is dependent on a fix for https://github.com/dotnet/dotnet-docker/issues/2090 because there's not currently a test leg that gets generated specifically for the monitor image.
