### ISSUE TITLE
Create tag-details.md

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/dotnet-docker#212]
### Benefits of adding tag-details.md
* Help provide more info on the breakdown of what is in each Docker image
* Help explain the naming conventions behind tag schema
* Other repos use this solution to help new users understand their repo

**Comment by MichaelSimons** [comment]
This should be done for both dotnet-docker as well as dotnet-docker-nightly.

**Comment by MichaelSimons** [comment]
Tooling to generate the tag-details is covered with https://github.com/dotnet/docker-tools/issues/79.

**Comment by mthalman** [comment]
If this metadata included package versions it would help in diagnosing issues like this: https://github.com/dotnet/dotnet-docker/issues/2145.

**Comment by mthalman** [comment]
While we see there being useful information here for customers, we don't have any plans to implement this.
