### ISSUE TITLE
Docker - Console core 3.1 application - Could not load file or assembly Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by matke2002** [dotnet/dotnet-docker#2135]
## Error info  
`Microsoft.Extensions.DependencyInjection.Abstractions` is present in NuGet config  
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Afh.OCR.Scan.Program.CreateHostBuilder(String[] args)
   at Afh.OCR.Scan.Program.Main(String[] args) in /tmp/proj/Afh.OCR.Scan/Program.cs:line 15
```

I need to run `dotnet publish -c Release -o out` twice or more to solve issue.  
This issue appeared first time after I added `EmailKit` library project.  

Please find attachment for project info [core_docker_issue.zip](https://github.com/dotnet/dotnet-docker/files/5015266/core_docker_issue.zip)  
I removed most of code, so build will not work in your case. 
Please check for created dlls (with publish) in folder *dependency_injection_dll*  
Please, notify me if you need more details.

## Steps to reproduce the issue
1. Starting docker in "debug" mode: `docker run --name netsdk --rm -it -v /tmp/afh-ocr-scan:/tmp/proj  mcr.microsoft.com/dotnet/core/sdk:3.1`
2. `apt-get update && apt-get install -y --allow-unauthenticated libgdiplus libc6-dev` - required by LeadTools library, otherwise will happen exception with missing `libdl`  
```
System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
```
3. `cd /tmp/proj && dotnet restore`
4. `dotnet publish -c Release -o out`
5. `cd out && dotnet Afh.OCR.Scan.dll` - exception described above happens, *Microsoft.Extensions.DependencyInjection.Abstractions.dll* is present in folder
6. `cd .. && dotnet publish -c Release -o out` - repeating *publish*
7. `cd out && dotnet Afh.OCR.Scan.dll` - application started successfully 

## Expected behavior
To start application after one `dotnet publish -c Release -o out`

## Actual behavior
Need to run twice or more `dotnet publish -c Release -o out` for successful run

## Additional information  
* This issue happens only on docker.
* On windows is everything fine
* Not tested on bare-metal linux

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 48
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.9.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 991MiB
 Name: centos7-docker
 ID: ENU2:YDZU:N6SV:KQUD:V6HW:TI7T:GG44:PFOA:T65W:EKCG:V5QJ:VTA6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Comment by mthalman** [comment]
I'm guessing that your app works fine if you run it from your built Docker image but gets this error when running it in this "debug" configuration, is that right?  This is most likely because you've got stale assemblies in the bin folder of your project that you're then volume mapping into the container.

The zip files you provided show that the bad assemblies are version 3.1.4 which is not the version referenced in your project. The good assemblies are version 3.1.6.  My suggestion would be to ensure that your bin and obj folders are clean before attempting this scenario.

This is the same manner in which "docker builds" should be done to only copy the project source assets via the build context and not include any bin or obj folders.  This is implicitly done by how your .dockerignore file is defined.  But that only applies when running `docker build`.  Since you're doing volume mapping, you end up including the bin/obj folders when you should not.  Either that, or you should at least make sure those folders contain up-to-date assemblies.

**Comment by matke2002** [comment]
Hi @mthalman 
no, built docker image have the same issue. 
I removed all _bin_ and _obj_ folders before copying project to Docker builder machine. Even I have done `docker system prune` several times.
I will check for versions 3.1.4 in project, thanks for pointing to this.

**Comment by matke2002** [comment]
I repeated build.
Cleaned everything:
- removed all bin and obj from project
- executed `docker system prune --all` to make sure that there is no some cached docker layer

After first `dotnet publish` command, I have got next result:
```
# exiftool out/Microsoft.Extensions.DependencyInjection.Abstractions.dll
ExifTool Version Number         : 11.16
File Name                       : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Directory                       : out
File Size                       : 37 kB
File Modification Date/Time     : 2020:04:15 03:36:10+00:00
File Access Date/Time           : 2020:08:03 15:14:16+00:00
File Inode Change Date/Time     : 2020:08:03 15:14:34+00:00
File Permissions                : rwxr--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2090:10:24 08:54:47+00:00
Image File Characteristics      : Executable, Large address aware, DLL
PE Type                         : PE32
Linker Version                  : 48.0
Code Size                       : 25600
Initialized Data Size           : 2560
Uninitialized Data Size         : 0
Entry Point                     : 0x821e
OS Version                      : 4.0
Image Version                   : 0.0
Subsystem Version               : 4.0
Subsystem                       : Windows command line
File Version Number             : 3.100.420.21409
Product Version Number          : 3.1.4.0
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Win32
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : Neutral
Character Set                   : Unicode
Comments                        : Abstractions for dependency injection...Commonly used types:..Microsoft.Extensions.DependencyInjection.IServiceCollection
Company Name                    : Microsoft Corporation
File Description                : Microsoft.Extensions.DependencyInjection.Abstractions
File Version                    : 3.100.420.21409
Internal Name                   : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Legal Copyright                 : © Microsoft Corporation. All rights reserved.
Original File Name              : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Product Name                    : Microsoft .NET Extensions
Product Version                 : 3.1.4+7cc2a109d98493cf617de56709ec188fa5cd3fc1
Assembly Version                : 3.1.4.0

```
version is 3.1.4.0.

After second build, result is:   
```
# exiftool out/Microsoft.Extensions.DependencyInjection.Abstractions.dll
ExifTool Version Number         : 11.16
File Name                       : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Directory                       : out
File Size                       : 37 kB
File Modification Date/Time     : 2020:06:17 06:47:30+00:00
File Access Date/Time           : 2020:08:03 15:14:18+00:00
File Inode Change Date/Time     : 2020:08:03 15:15:29+00:00
File Permissions                : rwxr--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2102:09:17 23:08:28+00:00
Image File Characteristics      : Executable, Large address aware, DLL
PE Type                         : PE32
Linker Version                  : 48.0
Code Size                       : 25600
Initialized Data Size           : 2560
Uninitialized Data Size         : 0
Entry Point                     : 0x821e
OS Version                      : 4.0
Image Version                   : 0.0
Subsystem Version               : 4.0
Subsystem                       : Windows command line
File Version Number             : 3.100.620.31605
Product Version Number          : 3.1.6.0
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Win32
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : Neutral
Character Set                   : Unicode
Comments                        : Abstractions for dependency injection...Commonly used types:..Microsoft.Extensions.DependencyInjection.IServiceCollection
Company Name                    : Microsoft Corporation
File Description                : Microsoft.Extensions.DependencyInjection.Abstractions
File Version                    : 3.100.620.31605
Internal Name                   : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Legal Copyright                 : © Microsoft Corporation. All rights reserved.
Original File Name              : Microsoft.Extensions.DependencyInjection.Abstractions.dll
Product Name                    : Microsoft .NET Extensions
Product Version                 : 3.1.6+be18161fbed286d6fb7a7b1c7999ce70a50cf3eb
Assembly Version                : 3.1.6.0
```
so 3.1.6.0

How's that possible? 
I see no reference to version 3.1.4 in project.

**Comment by mthalman** [comment]
Since you said you're able to make this happen with a built Docker image, can you provide the steps for that including a project that can build without errors?  I don't think the repro steps need to actually execute the app.  I think the important aspect of this is to just be able to repro that it ends up getting a 3.1.4 version of the assembly.

**Comment by matke2002** [comment]
Hi @mthalman 
please check this [demo-afh-ocr-scan.zip](https://github.com/dotnet/dotnet-docker/files/5021044/demo-afh-ocr-scan.zip)

to build, and run docker, execute next commands:  
```
docker build --pull -t ocr-demo -f Dockerfile .
docker run --name ocr-test --rm -it -e  AWS__Region=eu-west-3   ocr-demo
```
or you can use "debug" commands I provided in the first message.

If I downgrade DI to version 3.1.4, it works.

I discovered also that package `NETCore.MailKit` I use in *EmailService* lib project, requires minimum DI 3.1.4, so probably this downloaded and cached DI.

If I edit `Afh.EmailService.csproj` and add DI 3.1.6 at the beginning:   
```
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.1.6" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.3" />
</ItemGroup>
```
then I built app twice, both time was success run.

But this brings me a new questions: 
- does NuGet PM downloads packages following order in `ItemGroup`?
- may it happen that `NETCore.MailKit` downloads first DI 3.1.4, and *publish* use 3.1.4 version again instead of 3.1.6?

Thanks

**Comment by mthalman** [comment]
I ran the commands you provided and the app started fine:
```
docker build --pull -t ocr-demo -f Dockerfile .
docker run --name ocr-test --rm -it -e  AWS__Region=eu-west-3   ocr-demo
```

I also checked the version of the Microsoft.Extensions.DependencyInjection.Abstractions.dll file and saw that it is 3.1.6.

**Comment by matke2002** [comment]
Did you run it several times? 
Each time to clean entire docker with `docker system purge --all --force` ?

**Comment by mthalman** [comment]
> Did you run it several times?
> Each time to clean entire docker with `docker system purge --all --force` ?

Yes, I've run it several times and always works.  Note that running `docker system prune` should really have no effect on how the dotnet build resolves packages.  All it's really doing in this case is giving you a clean slate from which to cause the image to be rebuilt.  But you could just do that with the `--no-cache` option on `docker build`.

**Comment by matke2002** [comment]
Ok, strange that it always works in your case.
Since added line `<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.6" />` in email library helped, and I had no issues so far, I'm closing this.

Thanks
