### ISSUE TITLE
Get-GeneratedDockerfiles script doesn't support dynamic variables

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2144]
It is possible to define variable references in the manifest file for a variable that is not statically defined in the manifest but rather passed in via a `var` argument in an Image Builder command.  An example of this is the `UniqueId` variable here: https://github.com/dotnet/docker-tools/blob/a9b75c5c340d2aaf7b6a334b99020c3aac55448b/src/Microsoft.DotNet.ImageBuilder/manifest.json#L9.

The problem is that such a manifest file will result in a build failure as part of the pre-build validation that runs the Get-GeneratedDockerfiles script to ensure the Dockerfiles are up-to-date.  This happens because the custom `var` arguments do not get passed to the `generateDockerfiles` command.

**Comment by mthalman** [comment]
A workaround for this is to define a default value for the variable in the manifest.  Maybe that's fine for supporting this.

**Comment by MichaelSimons** [comment]
Closing as there is no requirement/driver to change the behavior.
