### ISSUE TITLE
Remove "core" repo tags for 5.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2154]
The 5.0 images have temporarily been getting tagged with the old "core" repo name until VS added support for the new 5.0 tagging scheme (see https://github.com/dotnet/dotnet-docker/pull/2087).  Now that VS 16.7 adds this support we should stop publishing the old "core" repo name tags.

**Comment by MichaelSimons** [comment]
We would like to get this done for the new 5.0 preview release.

**Comment by MichaelSimons** [comment]
Closing as this was fixed as part of the 5.0 Preview 8 release.
