### ISSUE TITLE
dotnet-sdk 3.1.401-alpine does not have the 3.1.401 SDK installed

### ISSUE THREAD

**Issue by gldraphael** [dotnet/dotnet-docker#2163]
## Steps to reproduce the issue

Create a Dockerfile in an empty directory:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.401-alpine
WORKDIR /repro
RUN dotnet --list-sdks
```

and run:

```
docker build .
```

## Expected behavior

`--list-sdks` should print `3.1.401`.

## Actual behavior

`--list-sdks` prints `3.1.302`:

```
~\Desktop\aspnet-bug-exp> docker build .
Sending build context to Docker daemon  6.656kB
Step 1/3 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1.401-alpine
 ---> 7567e8b2887e
Step 2/3 : WORKDIR /repro
 ---> Running in 6622221994c6
Removing intermediate container 6622221994c6
 ---> 28f422aeb566
Step 3/3 : RUN dotnet --list-sdks
 ---> Running in a6ddb0206e64
3.1.302 [/usr/share/dotnet/sdk]
Removing intermediate container a6ddb0206e64
 ---> a77dc4804f10
Successfully built a77dc4804f10
```

## Additional information

Works ok with buster (`mcr.microsoft.com/dotnet/core/sdk:3.1.401-buster`).
See: https://github.com/dotnet/dotnet-docker/blob/e5bad167d310430ea178a07b9153b863d851966b/src/sdk/3.1/alpine3.12/amd64/Dockerfile#L22-L30
(I got the permalink from the dockerhub tags table. `master` uses the same `3.1.302` version too. Seems like an oversight.)

**Comment by mthalman** [comment]
@gldraphael - Thanks for bringing this to our attention.

The issue has now been resolved.  Please re-pull the image tags to get the updated version.
