### ISSUE TITLE
Consider using Alpine for .NET Samples

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#2167]
Today, we use Debian for our samples. Our samples should put our best foot forward. I think using Alpine would be better since the samples would be much smaller. We'd have to figure out what to do for Linux ARM32 (we don't support Alpine for that configuration). 

Experience today:

```console
rich@thundera ~ % docker pull mcr.microsoft.com/dotnet/core/samples
Using default tag: latest
latest: Pulling from dotnet/core/samples
bf5952930446: Pull complete 
95f9f5484a21: Pull complete 
ebc43d54b0d9: Pull complete 
eb8b3fc30ae1: Pull complete 
de3474ac322e: Pull complete 
2befaca40243: Pull complete 
Digest: sha256:be09dbeae0cc5cbcd069d391399280eb8a3c3501cc021994e0ae353140dba2a8
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/samples:latest
mcr.microsoft.com/dotnet/core/samples:latest
rich@thundera ~ % docker images | grep mcr.microsoft.com/dotnet/core/samples
mcr.microsoft.com/dotnet/core/samples           latest                    203ee9fd2283        23 hours ago        190MB
rich@thundera ~ % docker images | grep 3.1                                    
mcr.microsoft.com/dotnet/core/runtime           3.1-alpine                b30a31240b43        5 hours ago         87.2MB
mcr.microsoft.com/dotnet/core/runtime           3.1                       c6f90064476b        24 hours ago        190MB
```

**Comment by MichaelSimons** [comment]
We have two options for ARM32

1. Don't publish ARM32 images in the samples repo.
2. Build the ARM32 images based on a different distro (e.g. Debian) than the AMD64 and ARM64 images.

After discussing this we believe option 2 is the way to go.

**Comment by MichaelSimons** [comment]
This change should be made when 5.0 is released.  This is when the samples repo would transition from `dotnet/core/samples` to `dotnet/samples`.

**Comment by richlander** [comment]
This issue is significantly related to https://github.com/dotnet/dotnet-docker/issues/2182. They make sense to do together, or not at all.

**Comment by mthalman** [comment]
We'll first update the Alpine sample Dockerfiles to have an architecture-agnostic version of alpine-slim. That will serve as the basis for being able to publish the sample images. That means we won't use https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile as the Dockerfile for building the images anymore.
