### ISSUE TITLE
Alpine image of aspnet does not connect with SQL database.

### ISSUE THREAD

**Issue by Abhishekqwerty** [dotnet/dotnet-docker#2168]
Earlier I had used Debian based aspnet image for one of my microservice. It was working as expected since there is a vulnerability for Debian OS, I have moved the base image for my microservice to use alpine based aspnet docker image.

A problem arose that, I can't connect to my Azure-hosted SQL database when I am using Alpine Image. 
Debian Image was connecting to the same database. Checked all the dll files for connecting the SQL database. 

Please have a look at this issue.

**Comment by mthalman** [comment]
Can you provide some more detail here?  What is the error you're getting?  What does your code look like that's making the connection?  What does your Dockerfile look like?  Have you verified whether your container can connect to other Internet-facing services?

**Comment by MichaelSimons** [comment]
Without know any details, you may be encountering this issue - https://github.com/dotnet/SqlClient/issues/222
