### ISSUE TITLE
There is not docker binary in all dotnet images.

### ISSUE THREAD

**Issue by sh-vasily** [dotnet/dotnet-docker#2189]
Hello. In our team we have ci pipeline in gitlab. We use dotnet docker imge in it. But in this image there is not docker binary and we use some bad code:
curl -fsSL https://get.docker.com > get-docker.sh
"sh ./get-docker.sh"
Is there a way to avoid this?

**Comment by MichaelSimons** [comment]
@sh-vasily - I'm not certain I am understanding what the issue is.  What dotnet docker image are you using?  Can you provide a set of steps that can reproduce the issue you are encountering?  Thanks.

**Comment by sh-vasily** [comment]
Thx for answer! Steps to reproduce:
1. Use any dotnet core image, for example mcr.microsoft.com/dotnet/core/sdk:3.1
2. Try to use commands
`docker login`
`docker push` inside of netcore image
3. This fail cause there is not docker image in dotnet sdk container.
In our gitlab pipeline we firstly build and push our dotnet services to our registry and because of it we need to use docker inside container.

**Comment by MichaelSimons** [comment]
Adding the Docker cli to the sdk image is something that we suggest doing in your own custom image based on the .NET sdk image.  Having the Docker cli installed is not something that would be widely used therefore it adds bloat to the image for the majority of use cases.
