### ISSUE TITLE
Create a docker image with both aspnet and sdk

### ISSUE THREAD

**Issue by JeremyMahieu** [dotnet/dotnet-docker#2195]
It would be nice if there was a docker image that has both aspnet and sdk installed. You need the skd for remote debugging with Visual Studio.

**Comment by MichaelSimons** [comment]
The `sdk` images do include `aspnet`.

**Comment by JeremyMahieu** [comment]
Oh. But the `sdk` does not run my project while the `aspnet` does. I will investigate.
Thanks for the quick response.

**Comment by MichaelSimons** [comment]
One difference which may or may not affect your usage is that the `sdk` image has `ASPNETCORE_URLS` ENV unset while the `aspnet` image has it set to `http://+:80`

**Comment by JeremyMahieu** [comment]
Yeah exactly, that's it, the sdk binds on port 5000 while aspnet binds on 80.

**Comment by JeremyMahieu** [comment]
Solved by adding`ENV ASPNETCORE_URLS=http://+:80` to my docker file.
Thanks.
