### ISSUE TITLE
Create Alpine-based dotnet images

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker#22]
Alpine is a small footprint distro that is gaining wide adoption in Official images. Prereq is to get Alpine support for the dotnet runtime, libraries, and CLI.

**Comment by ctaggart** [comment]
This is one of the reasons I like golang, is that they have a [golang:alpine docker image](https://hub.docker.com/_/golang/) that is very small. There is now even a [rust-musl-builder](https://github.com/emk/rust-musl-builder) docker image. It would be nice if `dotnet --native` supported targeting `musl` too, so the binaries could be put on alpine images.

**Comment by markrendle** [comment]
I know one of the things that's been blocking this is the absence of libttng on Alpine, but guess what? [It's available now!](http://lttng.org/download/#alpine)

**Comment by RTodorov** [comment]
Hello guys!

Is this still on the roadmap? It's a bit hard to understand the current status of https://github.com/dotnet/coreclr/issues/917.

Thanks!

**Comment by MichaelSimons** [comment]
@RTodorov, Yes Alpine support is being actively worked on although there is no set release date as of now.

**Comment by MaximRouiller** [comment]
Just pinging the old thread to see if we could have a good ol' status update. :smile:

**Comment by RTodorov** [comment]
Looking very much forward to it! It would be a huge improvement for those running dotnet core on Linux.

**Comment by MichaelSimons** [comment]
While progress is being made on Alpine, it is not yet an [officially supported OS](https://github.com/dotnet/core/blob/master/roadmap.md#supported-os-versions).

**Comment by mrnickel** [comment]
I'd like to add my voice to the chorus of people requesting alpine support for .NET.

Loving this support team! Keep up the good work!

**Comment by skbergam** [comment]
Yes this would be a great addition.

**Comment by ErikSchierboom** [comment]
@MichaelSimons I see that you've removed the "blocked dependency" label 14 days, does that mean there is no longer any blocking issue to prevent this from happening? Having a .NET Core Alpine image would be brilliant.

**Comment by MichaelSimons** [comment]
@ErikSchierboom, I'm sorry but this work is still blocked on official support for Alpine.  The blocked dependency label was removed as dependencies are being tracked differently (on a KanBan board).

**Comment by ErikSchierboom** [comment]
@MichaelSimons Ah, okay. Is there anywhere that I can track progress being done on that part?

**Comment by richlander** [comment]
I was talking to @Petermarcu about Alpine support today. My understanding of the status:

- Alpine support _was_ very close.
- Latest [Alpine switched SSL libraries](http://lists.alpinelinux.org/alpine-devel/5463.html) and has slowed our efforts. We have not yet started on this project.

Once this work is done, we will provide Alpine-based container images.

**Comment by Petermarcu** [comment]
@bartonjs can you confirm the state of crypto libs in the latest alpine version sometime soon?

**Comment by kbatman37** [comment]
+1
Any updates?

**Comment by MichaelSimons** [comment]
@kbatman37 still blocked on official .NET Core support.

**Comment by kbatman37** [comment]
@MichaelSimons What is the current blocker? Also, where could I lookup the information to see that it is blocked?

**Comment by eerhardt** [comment]
Just to cross-link the current status:  https://github.com/dotnet/coreclr/issues/917#issuecomment-326071764

@janvorli is currently working on supporting Alpine in .NET Core 2.1.

**Comment by MichaelSimons** [comment]
Alpine images are now available in the [microsoft/dotnet-nightly](https://hub.docker.com/r/microsoft/dotnet-nightly/) repo and are ready for testing.  See https://github.com/dotnet/dotnet-docker-nightly/issues/500 for additional details.  The .NET Core Docker samples repo was also updated to include an [Alpine sample](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod-alpine-preview).  We look forward to hearing your feedback - both positive and negative.  Thanks

**Comment by kasper3** [comment]
Cheers! 👍 

Will the .NET Core be published as an official Alpine package by Microsoft / dotnet foundation (so we can simply do `apk add dotnet` in Alpine box someday)?

**Comment by annymsMthd** [comment]
Any chance for arm images? This would be perfect for Resin.io projects

**Comment by MichaelSimons** [comment]
@annymsMthd - Can you clarify - are you asking specifically about Alpine ARM images?

**Comment by MichaelSimons** [comment]
> Will the .NET Core be published as an official Alpine package by Microsoft / dotnet foundation (so we can simply do apk add dotnet in Alpine box someday)?

@janvorli - Can you answer?

**Comment by janvorli** [comment]
@annymsMthd regarding the ARM, the missing piece is crossfs creation for ARM Alpine Linux in coreclr / corefx / core-setup so that we can cross build the nuget packages. We don't have ARM machines in the official build labs and the current crossfs creation supports only debian based target distros. If anyone from the community would be able to add the Alpine crossfs creation to coreclr (the other distros use the same mechanism), then it would speed up the process of getting the arm packages a lot. Otherwise it would need to wait until I get to that.

**Comment by janvorli** [comment]
> Will the .NET Core be published as an official Alpine package by Microsoft / dotnet foundation (so we can simply do apk add dotnet in Alpine box someday)?

We would prefer the distro owners to add dotnet packages. We did the debian / redhat ones to support the most frequently used distros that way from the beginning, but we don't have a plan to do that for other distros. We are working on an end to end build of all components from sources to make it easy and acceptable for distro owners to add dotnet packages.
