### ISSUE TITLE
Image does not support .Net Core self-contained x86 app

### ISSUE THREAD

**Issue by brentarias** [dotnet/dotnet-docker#2210]
## Steps to reproduce the issue
I have created a .Net Core 3.1 console app that executes the following lines of code:

```
var arch = RuntimeInformation.ProcessArchitecture;
Console.WriteLine($"Starting as {arch}");
```

I confirm the application is working by publishing to my laptop filesystem as a self-contained app:

```
dotnet publish --configuration Release --runtime win10-x86 -p:Platform=x86 NeoAgent.sln
```

The `NeoAgent.sln` has several .Net Core 3.1 library project references, but none are used to produce the output. The resulting console app `idfextplatformD.exe` produces the expected "x86" output.

I then build a docker image for this console app as follows:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ENV DOTNET_RUNNING_IN_CONTAINER=true

WORKDIR /PlatformConnect
COPY . .
RUN dotnet publish --configuration Release --runtime win-x86 -p:Platform=x86 NeoAgent.sln
WORKDIR ./PlatformExtract/bin/x86/Release/netcoreapp3.1/win-x86/publish
CMD ["idfextplatformD.exe"]
```

The image is built successfully and the container launches.  The expected `idfextplatformD.exe` is found where expected.

## Expected behavior

Executing `idfextplatformD.exe` (whether directly or interactively) produces the output "Starting as x86".

## Actual behavior

The `idfextplatformD.exe` produces nothing.  No console output or error message.  It is silent.  However, `$lastexitcode` produces the code -1073741515.

This error is consistent.  It always fails.  In a separate gitter dotnet/cli channel, I was told that this image  `mcr.microsoft.com/dotnet/core/sdk:3.1` is based on nano server, which does not support x86.  If true, this immediately raises questions:

- Why is this image tagged as `x86-64` in docker hub if it does not support x86?
- Why does the docker hub page for this image not state whether it is based on nano server or server core?
- How do I properly "shop" for an image that does support an x86 self-contained .Net Core app?

**Update...**

I've revised my dockerfile into a two-stage which built my solution as x86 from `mcr.microsoft.com/dotnet/core/sdk:3.1`, and then loaded the bits into `mcr.microsoft.com/windows/servercore:1809`.  I tried two scenarios: a self-contained build and a framework dependent.  In the latter case I added an x86 dotnet runtime deployment to `mcr.microsoft.com/windows/servercore:1809`.

<ins>Both of these scenarios were successful.</ins>  So indeed the issue, if it is an issue, is with `mcr.microsoft.com/dotnet/core/sdk:3.1`.  Its kinda funny that it can build the x86 bits, but can't run them.

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:57:30 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 49
  Running: 1
  Paused: 0
  Stopped: 48
 Images: 131
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.1016)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.73GiB
 Name: RM1-P-WS040
 ID: N4HO:APIT:VHOQ:4YMH:NZFL:5XPQ:RUUP:X32P:D6BC:ARRE:5JFT:C2L3
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 50
  System Time: 2020-09-03T11:51:41.0009252-07:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
The SDK supports building applications that target any platform.  The .NET Windows images are based on Nano Server which only supports running x64 applications.  The `x86-64` labeling in Docker Hub is misleading.  

Closing as #1852 covers adding support for Windows Server Core images.

**Comment by zandiarash** [comment]
> The SDK supports building applications that target any platform. The .NET Windows images are based on Nano Server which only supports running x64 applications. The `x86-64` labeling in Docker Hub is misleading.
> 
> Closing as #1852 covers adding support for Windows Server Core images.

Is there a possible solution to have an x86 webapi image running with docker ?

**Comment by richlander** [comment]
Not as far as I know. The best path is to convert the app to 64-bit.

**Comment by zandiarash** [comment]
> Not as far as I know. The best path is to convert the app to 64-bit.

Actually I am using some obfuscated dll files that I don't know their developers and they are x86 and there is no way to convert them without source codes.
Any way thanks for your reply.
