### ISSUE TITLE
Cryptographic libraries used in .net core docker image- Information request.

### ISSUE THREAD

**Issue by sumantfordev** [dotnet/dotnet-docker#2225]
From multiple articles/blog i have read that .net core uses open SSL installed in the operating system for all cryptographic operations. 
My question is when doing cryptographic operations in a .net core container, does it uses the openssl library installed in the docker image or does it uses the cryptographic libraries installed in the Host operating system?

**Comment by omajid** [comment]
> My question is when doing cryptographic operations in a .net core container, does it uses the openssl library installed in the docker image or does it uses the cryptographic libraries installed in the Host operating system? 

It uses the OpenSSL library that's present in the container image.

If it could/would use the library from the host, that would basically break the isolation properties that docker containers provide.

**Comment by MichaelSimons** [comment]
Closing per @omajid's response.
