### ISSUE TITLE
dotnet --version should not produce error in runtime (only) containers

### ISSUE THREAD

**Issue by am11** [dotnet/dotnet-docker#2235]
## Steps to reproduce the issue

Using aspnet 5 preview (Linux) docker container on macOS x64 to simply check the dotnet version in container's PATH fails as follow:

```sh
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

command used:
```sh
$ docker run mcr.microsoft.com/dotnet/aspnet:5.0 dotnet --version
```

## Expected behavior

SDK should not be required to simply check the `--version`.

## Actual behavior

SDK container is required to check the version.

## Additional information (e.g. issue happens only occasionally)

Error is thrown persistently.

**Comment by mthalman** [comment]
The `--version` flag is part of the SDK.  For runtime-only, you can use `--info`:

```
> docker run mcr.microsoft.com/dotnet/aspnet:5.0 dotnet --info

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
This behavior is an aspect of the .NET SDK and runtime and is not specific to the Docker images.

**Comment by am11** [comment]
Thanks Matt, indeed it is just about the `--version` switch (fixed the title/description).
Assuming you agree with `--version` should still work without the SDK, could you please [transfer](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) this issue to SDK repo?

**Comment by am11** [comment]
I have noticed (remembered actually: https://github.com/dotnet/sdk/issues/6569) that `--version` switch reflects the SDK version rather the host's, so it is a dependency by design. It is a totally separate discussion if the other way around would have been better.  I will just go ahead and close this issue.
