### ISSUE TITLE
Vulnerability: Image should be created with a non-root user

### ISSUE THREAD

**Issue by sspradhan1** [dotnet/dotnet-docker#2239]
We are using Alpine 3.12 based .net core as base. Else docker file is same as generated by Visual Studio. Prisma Scan is showing vulnerability:  Image should be created with a non-root user. When we try to add non root user in docker file, the .net Web API is throwing exception: System.Net.Scokets.SocketException: Permission denied  in Program.cs, Main Method. Can we create image without root user?

**Comment by MichaelSimons** [comment]
I think there are really two issues here.  

1. ASP.NET throwing a SocketException when running under a non-root user.  The tracking issue for this is https://github.com/dotnet/aspnetcore/issues/4699.
1. Add a non-root user.  This is something discussed in https://github.com/dotnet/dotnet-docker/issues/1757.  It was decided that this is something that best belongs in a derived image where you can define the user that best suites your needs.

**Comment by sspradhan1** [comment]
Thanks Michael makes sense. The issue was with port 80 that we were using which required privileged user access.
