### ISSUE TITLE
Reponse time for HttpClient for POST requests are very slow due to old libcurl.

### ISSUE THREAD

**Issue by damtur** [dotnet/dotnet-docker#225]
## Steps to reproduce the issue
1. Test performance of simple .NET Core app in Linux (with libcurl 7.38) https://github.com/damtur/dotnetcore-post-bug
2. Test the same application in Docker image (with libcurl 7.53.1) provided in https://gist.github.com/damtur/3519cb6e74ed570c8b4bbb5baddc86fe#file-dockerfile

## Expected behavior

Response time in Linux should be similar to windows and be around 1 ms per request.

## Actual behavior

For libcurl 7.38 I'm seeing response time ~40ms
For libcurl 7.53.1 I'm seeing response time ~1ms

## Additional information (e.g. issue happens only occasionally)

Plese see a blog post for more information: https://www.linkedin.com/pulse/post-net-core-damian-turczy%C5%84ski

## Output of `docker version`

```
Client:                                    
 Version:      17.03.1-ce                  
 API version:  1.27                        
 Go version:   go1.7.5                     
 Git commit:   c6d412e                     
 Built:        Tue Mar 28 00:40:02 2017    
 OS/Arch:      windows/amd64               
                                           
Server:                                    
 Version:      17.03.1-ce                  
 API version:  1.27 (minimum version 1.12) 
 Go version:   go1.7.5                     
 Git commit:   c6d412e                     
 Built:        Fri Mar 24 00:00:50 2017    
 OS/Arch:      linux/amd64                 
 Experimental: true                        
```

## Output of `docker info`

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 51
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 75
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 3K2R:A3HU:YMAH:OJ5V:7UKT:DLXD:7QYD:Z5U7:W5ZM:LPET:GJV4:M7BO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-04-04T11:23:49.6104466Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
See related discussion in https://github.com/dotnet/corefx/issues/13551

**Comment by damtur** [comment]
Workaround for that issue:
Use Dockerimage with libcurl >=  7.50.2. image: https://gist.github.com/damtur/3519cb6e74ed570c8b4bbb5baddc86fe

Another note:
In .Net Core 2.0 the issue is solved. 

More info:
https://github.com/dotnet/corefx/pull/16895
https://curl.haxx.se/libcurl/c/CURLOPT_TCP_NODELAY.html

**Comment by MichaelSimons** [comment]
As noted in other threads, this issuse has been fixed in the next release (2.0) - https://github.com/dotnet/corefx/pull/15354/files and has been back ported to 1.1 - https://github.com/dotnet/corefx/pull/16895.  Docker images will be available with the fix when the next version is released.

**Comment by AnthonyMastrean** [comment]
Is there a schedule or any indication when the next 1.1 Docker image will be published?

**Comment by MichaelSimons** [comment]
.NET Core 1.1.2 was just released yesterday including new docker images.  Please give them a try.

**Comment by AnthonyMastrean** [comment]
Doesn't appear to be included. https://github.com/dotnet/corefx/issues/19658#issuecomment-300863362

**Comment by MichaelSimons** [comment]
The [fix](https://github.com/dotnet/corefx/pull/15354) is in microsoft/dotnet:1.1.2-runtime image.  Note the fix was not to upgrade the libcurl dependency, rather it is to set `CURLOPT_TCP_NODELAY`.
