### ISSUE TITLE
ASP.NET 5 on windows containers -  shrink from 306 MB to 100 MB ?

### ISSUE THREAD

**Issue by prabh-62** [dotnet/dotnet-docker#2257]
## Steps
- `git clone` [this repo](https://github.com/dotnet/dotnet-docker)
- Replace content of [samples\aspnetapp\Dockerfile.nanoserver-x64-slim](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile.nanoserver-x64-slim) with this code snippet
```dockerfile
# https://hub.docker.com/_/microsoft-dotnet-core
FROM  mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp/. ./aspnetapp/
WORKDIR /source/aspnetapp
RUN dotnet publish --no-restore  -c Release --self-contained true -o /app /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=None /p:DebugSymbols=false

# final stage/image
# Uses the 2004 release; 1909, 1903, and 1809 are other choices
FROM mcr.microsoft.com/windows/nanoserver:2004 AS runtime
WORKDIR /app
COPY --from=build /app ./

# Configure web servers to bind to port 80 when present
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENTRYPOINT ["aspnetapp"]

```
- Replace content of [samples\aspnetapp\aspnetapp\aspnetapp.csproj](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetapp/aspnetapp.csproj) with this code snippet
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UserSecretsId>57393389627611478466</UserSecretsId>
  </PropertyGroup>

</Project>
```
- `cd cd .\samples\aspnetapp\`
- `docker build -t aspnet5container -f Dockerfile.nanoserver-x64-slim .` (Switch to Windows Containers in Docker)
- `docker history aspnet5container`
```log
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
a783b34b40fa        2 minutes ago       cmd /S /C #(nop)  ENTRYPOINT ["aspnetapp"]      41kB                
8e2d7c7c3e39        2 minutes ago       cmd /S /C #(nop)  ENV DOTNET_RUNNING_IN_CONTΓÇª   41kB                
367a3899f495        2 minutes ago       cmd /S /C #(nop)  ENV ASPNETCORE_URLS=http:/ΓÇª   41kB                
a417c09cde13        2 minutes ago       cmd /S /C #(nop) COPY dir:3bb056ffe1a6215264ΓÇª   44.1MB              
41495be71814        2 minutes ago       cmd /S /C #(nop) WORKDIR C:\app                 41kB                
25bef4c08869        13 days ago         Apply image 2004-amd64                          262MB               
```
- If we inspect the size of `aspnet5container` image, it comes out to be `306 MB` (nanoserver - `262 MB` + app - `44 MB`). Is there anything we can do to shrink the size of docker image and bring it down to `100 MB`?

## Additional Information
- We cannot use Linux containers in our organization. (We would rather not put effort in fixing cross-platform bugs surfacing in production and all developers use windows machines)

## Output of `docker version`
```
Docker version 19.03.12, build 48a66213fe
```

## Output of `docker info`
```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2004 (OS Build 19041.508)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.84GiB
 Name: User-dev
 ID: VKKG:XOWC:PWG5:P24F:YDDN:ZDM3:CLXR:NNRV:3BYY:IZKX:KLAY:PZRF
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 43
  System Time: 2020-09-20T16:11:06.6317883-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by prabh-62** [comment]
Setting flag `ReadyToRun` to `True` (`/p:PublishReadyToRun=true`) increases the app's size by 2x (`44 MB` -> `77 MB`)

```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
5c94bd5b8e0b        34 minutes ago      cmd /S /C #(nop)  ENTRYPOINT ["aspnetapp"]      41kB                
066dcb13b6e3        34 minutes ago      cmd /S /C #(nop)  ENV DOTNET_RUNNING_IN_CONTΓÇª   41kB                
f63ec8b0c5cb        34 minutes ago      cmd /S /C #(nop)  ENV ASPNETCORE_URLS=http:/ΓÇª   41kB                
2933cf5c46ba        34 minutes ago      cmd /S /C #(nop) COPY dir:1011cf9a6851bb439aΓÇª   77.1MB              
41495be71814        50 minutes ago      cmd /S /C #(nop) WORKDIR C:\app                 41kB                
25bef4c08869        13 days ago         Apply image 2004-amd64                          262MB               
```

Therefore, I took it out in the published example above

**Comment by mthalman** [comment]
You're asking to make a Docker image smaller than its base image.  That's simply not possible to do with Docker.  Nano Server is the smallest variant of Windows images so that's the best you're going to do with Windows.

As you alluded to, Linux has options that can provide much smaller image sizes, particularly with Alpine.  You'll need to weigh the importance of platform choice versus image size and decide which one you can compromise on.

**Comment by MichaelSimons** [comment]
@prabh-62, Can you share more details with us on your scenario?  What is driving the 100 MB size constraint/goal?

**Comment by prabh-62** [comment]
I have tried deploying windows containers to [Azure Container Instances](https://azure.microsoft.com/en-ca/services/container-instances/) and [web apps](https://azure.microsoft.com/en-ca/services/app-service/containers/) and the whole experience has been real slow.

I created an ASP.NET 5 web api with .NET 5 RC1 SDK and created a docker image with self-contained version of web API.
Tried to deploy with latest nanoserver base image on ACI and I get `UnsupportedWindowsVersion` error
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:2004
```
![container_base_error](https://user-images.githubusercontent.com/13006107/93838791-efe05700-fc58-11ea-8414-d082f74a93af.PNG)

Then, I tried with `1909` version, and got the same error on Azure Portal - `UnsupportedWindowsVersion`
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1909
```
Then with `1903`, same error  - `UnsupportedWindowsVersion`
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1903
```

Then downgraded further to `1809`, and now I can't even run the API locally.
```

**Comment by prabh-62** [comment]
It doesn't look like [Google Cloud run](https://cloud.google.com/run) and [AWS Fargate](https://aws.amazon.com/fargate/) don't support windows containers so there's no real choice for deploying windows containers. 

Introducing Kubernetes would make the infrastructure much more complex and we 'd rather not manage complex `YAML` files

**Comment by MichaelSimons** [comment]
> We will eventually be having 20+ ASP.NET 5 apps running on windows containers. Higher the image size, the more costly it would be to maintain images in Azure container registry (Pricing)

Keep in mind layer sharing comes into effect here.  If the images share a common base image, then only one copy of the base layers will existing in your registry.

**Comment by prabh-62** [comment]
So, is it being suggested that customers can use `nanoserver:sac2016` which is `1171 MB` in size for deploying applications to Azure Container Instances ?

I don't see another alternative unless something I am unaware of.
```dockerfile
FROM mcr.microsoft.com/windows/nanoserver:sac2016
```

**Comment by MichaelSimons** [comment]
@prabh-62 - You are asking questions that are primarily related to ACI.  You will get better responses asking them in the appropriate ACI channels.  Please see the ACI documentation for [What Windows base OS images are supported](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-faq#what-windows-base-os-images-are-supported).

**Comment by prabh-62** [comment]
Ideally, I should be able to redirect some of the feedback here to the ACI team at Microsoft.

`nanoserver:1809` will also be EOL by Nov 10, 2020 😱 (https://github.com/microsoft/Windows-Containers/issues/52)

And thank you for not closing the issue right away @MichaelSimons 

I will just work with `300 MB` `nanoserver:1809` base image until there is something better and deployable to ACI

**Comment by MichaelSimons** [comment]
@prabh-62 - You're welcome. I have a couple more thoughts I wanted to share.

1.  We are going to add support for Server Core based images for the .NET 5.0 release.  This may not be attractive because of the size, but Server Core does have LTSC releases.  See https://github.com/dotnet/dotnet-docker/issues/1852 for details.
1.  ACI does [cache some base images](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#cached-images).  This should eliminate any performance concerns about the speed of pulling Nano Server or Server Core images if you are based on a version that is cached.  Storage costs still apply however but shared layers help minimize this.

**Comment by prabh-62** [comment]
1. It's fine if ACI caches Server Core image on cloud however, we would have to pull GBs of docker images on our local machines + in CI environments(if not cached) to run tests which makes it unusable for us.
2. If ACI is the only service to support windows containers and it caches `nanoserver` images, then we don't have to aim for `100 MB` mark. However, this means, if Google Cloud run/AWS Fargate starts supporting windows containers on some day, and they don't cache, we 'd still have performance implications.
