### ISSUE TITLE
Pre-build tests cannot be run with Windows container mode

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2261]
When attempting to run tests on a developer machine configured to target Windows container mode, the pre-build tests fail.  The pre-build tests rely on `mcr.microsoft.com/mcr/renderingtool` for which there is no image available for Windows.  This results in the following error:
```
 -- EXECUTING: docker pull mcr.microsoft.com/mcr/renderingtool:1.0
 1.0: Pulling from mcr/renderingtool
image operating system "linux" cannot be used on this platform
```

**Comment by MichaelSimons** [comment]
This is also going to be an issue in the microsoft/dotnet-framework-docker repo as well.
