### ISSUE TITLE
Question about setting HTTP Strict-Transport-Security in a docker container with code or compose/container settings

### ISSUE THREAD

**Issue by keaedwar** [dotnet/dotnet-docker#2268]
I'm using the **mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim** docker Linux image and I would like to add HSTS headers to the website, but I've not been successful in doing that.

The first thing I tried was adding the following in the Startup.cs file. I've tried setting up the HSTS values in the ConfigureServices(IServiceCollection services) method by adding them with `services.AddHsts(options => { options.Preload = true; options.IncludeSubDomains = true; options.MaxAge = TimeSpan.FromDays(365); });` and calling `app.UseHsts();` in the Configure(IApplicationBuilder app, IWebHostEnvironment env) method, but they don't seem to work from there.

I thought that maybe the above method doesn't work on a Linux docker container, so I tried looking for ways to set up the Strict-Transport-Security header in the docker container, but I can't seem to figure out how to setup the correct values in the 3.1-buster-slim container.  I've tried to use the HSTS documentation for nginx (which the buster slim image reports as the base of its hosting service), but the buster slim doesn't seem to have the necessary software to configure HSTS this using that method. 

Is there a way to set the HSTS header from the docker container or are there instructions that can be added to the docker-compose file to set up HSTS for the 3.1-buster-slim image based containers?

Thank you!
Alan Edwards

**Comment by MichaelSimons** [comment]
This looks like a question well-suited for [StackOverflow](https://stackoverflow.com/) rather than the .NET docker issue tracker.  The StackOverflow audience is much larger and you will have better luck getting a good answer there.

**Comment by keaedwar** [comment]
I asked it here because there doesn't seem to be a way to set it in the mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim image and the .NET Core way of adding it using service options doesn't work either.

**Comment by gsej** [comment]
The issue here is that the middleware that adds the header (which you access with something like `app.UseHsts()`) will only add the header if the request is an https request. On the fact of it, this makes sense, but if you're running your dotnet core app in a docker container, then you might be terminating your SSL outside of the container (e.g. if you're hosting the container in an Azure AppService). The solution is to add your own tiny piece of middleware:
```
app.Use(async (context, next) => {
     context.Response.Headers.Add("Strict-Transport-Security", "max-age=31536000");
     await next.Invoke();
});
```
