### ISSUE TITLE
.net core 2.2.4 docker images for windows container doesnt support powershell

### ISSUE THREAD

**Issue by anantjs11** [dotnet/dotnet-docker#2271]
Hi,
Our application is into .net core 2.2.4 and have recently started creating Docker container for this application.

We need to run some powershell commands in the dockerfile.

When we tried writing Dockerfile for building the docker image using .net core base image for .net core 2.2.4, we are not able to run any powershell commands inside the container.

I know that .net core 3.0 supports powershell (pwsh) but we cant upgrade our app to .net core version 3.x

please provide me a solution to support powershell using .net core 2.2.4 base images.

Expecting your valuable response.

Thanks

**Comment by mthalman** [comment]
.NET Core 2.2 has been out of support since Dec. 2019 so there will be no updates made to those Docker images.  The currently supported versions of .NET Core are 2.1 and 3.1.  Only the 3.1 SDK images contain PowerShell Core.

Why are you unable to upgrade to .NET Core 3.1?  That would be the recommended path forward.

**Comment by anantjs11** [comment]
@mthalman  I agree, we are supposed to upgrade to 3.1, but there are some private nuget packages we use in our app are into .net core 2.2 only, so in order to support those packages we need to be in 2.2 only. so cant upgrade to 3.1

Is there any alternative to install powershell with 2.2 itself in dockrrfile?
We need powershell commands to run successfully.

**Comment by MichaelSimons** [comment]
@anantjs11 - Can you explain your scenario for using PS?  Do you need it in the resulting Docker image or only within the Dockerfile while building the image?

**Comment by MichaelSimons** [comment]
Closing as discussed, 2.2 is no longer supported.  @anantjs11, we would still be interested in hearing more about your scenario.
