### ISSUE TITLE
Improve the UX of the Full Tag Listing in Docker Hub

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2273]
When .NET customers visit any of the .NET runtime-deps, runtime, aspnet, and sdk Docker repositories today, they are presented with an overwhelming number of images to choose from. Currently most of the repositories contain 29 different images and 97 different tags.  Once .NET 5.0 is released, another 12 images and 49 tags will be added to the matrix of supported images.   

When users are looking for an image, they most often are seeking an image that is compatible with their OS type (Linux/Windows) and architecture. To help support this the tag listing is split into sections by OS type and architecture. Because of the compatibility limitations with Windows containers, Windows images are separated by version.

The following illustrates what the runtime repo’s Full Tag Listing would look like after the upcoming .NET 5.0 release: 
 
![image](https://user-images.githubusercontent.com/8290530/94448736-e0896e00-0170-11eb-9bde-6718fd48ad5a.png)

Even though the bar is high for adding new images, it is highly likely that as .NET matures, evolves and becomes more popular, the matrix will grow making the tag listing even more daunting. 

Aside from the sheer number of tags presented another issue with the current tag listing is that it doesn't give any indication of what the shared/manifest tags are.  While this isn't something most users care about it is important for a subset of users.

We should consider experimenting with different approaches to see how we can improve the UX of the Full Tag Listing.

**Comment by MichaelSimons** [comment]
[Triage] Moving to backlog as this has dropped in priority and we've haven't had success in garnering interest from MCR.

**Comment by mthalman** [comment]
We're not going to make .NET Docker specific implementation changes for this. Any improvements in UX would be handled natively within the MAR portal.
