### ISSUE TITLE
Getting 401 unauthorized at dotnet restore following the "Using the Azure Artifact Credential Provider"

### ISSUE THREAD

**Issue by cacizi41** [dotnet/dotnet-docker#2278]
Steps to reproduce the issue
---
1. Create a .netcore project with Dockerfile
2. In Dockerfile, follow the steps on the [Using the Azure Artifact Credential Provider](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider) example 
3. Create a nuget.config
4. Run docker build command

Expected behavior
---
Restore nuget package from private feeds

Actual behavior
---
Got 401 unauthorized. 

Dockerfile(restore section)
---
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Continue'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /src

# Change user to workaround https://github.com/microsoft/artifacts-credprovider/issues/201
USER ContainerAdministrator
# Install the cred provider
RUN Invoke-WebRequest -Uri https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 -OutFile installcredprovider.ps1; `
    .\installcredprovider.ps1; `
    del installcredprovider.ps1
USER ContainerUser

COPY . .
ARG SCSHARED_FEED_ACCESSOTOKEN
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{"endpointCredentials": [{"endpoint":"https://microsoftit.pkgs.visualstudio.com/_packaging/SCSharedPlatform/nuget/v3/index.json", "password":"$SCSHARED_FEED_ACCESSOTOKEN"}, {"endpoint":"https://microsoftit.pkgs.visualstudio.com/_packaging/UHRS/nuget/v3/index.json", "password":"$SCSHARED_FEED_ACCESSOTOKEN"}]}"
RUN echo $Env:VSS_NUGET_EXTERNAL_FEED_ENDPOINTS
RUN dotnet restore "Source/OnePdmIngestor.csproj"
```
Error Message
---
![image](https://user-images.githubusercontent.com/14630538/94598563-f61b9800-0243-11eb-93da-6aedfcebbb3a.png)

The print result of VSS_NUGET_EXTERNAL_FEED_ENDPOINTS:
```{endpointCredentials: [{endpoint:https://microsoftit.pkgs.visualstudio.com/_packaging/SCSharedPlatform/nuget/v3/index.json, password:***}, {endpoint:https://microsoftit.pkgs.visualstudio.com/_packaging/UHRS/nuget/v3/index.json, password:***}]}```

Docker build command:

> docker build --build-arg SCSHARED_FEED_ACCESSTOKEN=PAT .

PAT permission and status
---
![image](https://user-images.githubusercontent.com/14630538/94598451-d2585200-0243-11eb-88d1-2a5c28b5ccf3.png)

nuget.config
---
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="public" value="https://api.nuget.org/v3/index.json" />
		<add key="SCShared" value="https://microsoftit.pkgs.visualstudio.com/_packaging/SCSharedPlatform/nuget/v3/index.json" />
		<add key="UHRS" value="https://microsoftit.pkgs.visualstudio.com/_packaging/UHRS/nuget/v3/index.json" />
	</packageSources>
</configuration>
```

Output of docker version
---
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:57:30 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

Output of docker info
---
```
Client:
 Debug Mode: false

Server:
 Containers: 66
  Running: 0
  Paused: 0
  Stopped: 66
 Images: 157
 Server Version: 19.03.12
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2004 (OS Build 19041.508)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.92GiB
 Name: weqiang-0507
 ID: AVXP:CFHR:LLXD:ANR2:JOOB:H5QU:42FS:IPQH:V527:KHZP:RHLC:SDT4
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 41
  System Time: 2020-09-29T14:45:43.2707605-07:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by Anup-Antony** [comment]
I seem to have the same issue when running Docker build using the linux version when using the Azure Artifact Credential Provider to `dotnet restore` which has a package in the Github Packages Registry 

I get a bunch of **Warning 401** But in the end the `dotnet restore` succeeds too. 
 
`/usr/share/dotnet/sdk/2.1.811/NuGet.targets(123,5): warning : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured. `

` /usr/share/dotnet/sdk/2.1.811/NuGet.targets(123,5): warning : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured. 
  Retrying 'FindPackagesByIdAsync' for source 'https://nuget.pkg.github.com/<myOrganisation>/download/microsoft.extensions.fileproviders.composite/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).`

The docker build step in the pipeline still succeeds. 
Could someone help me fix this issue ?

**Comment by mthalman** [comment]
@Anup-Antony - I don't believe Azure Artifact Credential Provider is relevant when targeting GitHub Packages Registry.  Please follow the [GPR documentation](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages) on authenticating.

**Comment by mthalman** [comment]
@cacizi41 - Could you provide the updated edits you made to fix the encoding for the Windows platform?

**Comment by Anup-Antony** [comment]
Thanks @mthalman . I switched back to using templated Nuget.config and injecting the username and password (token) into the Docker file as build arguments and works without an issue.

**Comment by MichaelSimons** [comment]
Closing as underlying issue was resolved.  If anyone discovers issues with the Using the Azure Artifact Credential Provider documentation, please let us know.

**Comment by valbers** [comment]
Hi, I know this is issue is kind of old, but since I ran into the same issue and found the solution, I thought it'd be helpful to leave a comment.
The solution to this problem (as reported by OP) is to define the docker build arg carrying the PAT before **and** after the FROM instruction where it's going to be used.

In the OP's case that would be:
```Dockerfile
# ---- HERE (It's ok if it doesn't have a default value as long as you provide it from the outside when building the image
# |
# \/
ARG SCSHARED_FEED_ACCESSOTOKEN 
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Continue'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /src

# Change user to workaround https://github.com/microsoft/artifacts-credprovider/issues/201
USER ContainerAdministrator
# Install the cred provider
RUN Invoke-WebRequest -Uri https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 -OutFile installcredprovider.ps1; `
    .\installcredprovider.ps1; `
    del installcredprovider.ps1
USER ContainerUser

COPY . .
# ---- AND HERE
# |
# \/
ARG SCSHARED_FEED_ACCESSOTOKEN
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{"endpointCredentials": [{"endpoint":"https://microsoftit.pkgs.visualstudio.com/_packaging/SCSharedPlatform/nuget/v3/index.json", "password":"$SCSHARED_FEED_ACCESSOTOKEN"}, {"endpoint":"https://microsoftit.pkgs.visualstudio.com/_packaging/UHRS/nuget/v3/index.json", "password":"$SCSHARED_FEED_ACCESSOTOKEN"}]}"
RUN echo $Env:VSS_NUGET_EXTERNAL_FEED_ENDPOINTS
RUN dotnet restore "Source/OnePdmIngestor.csproj"
```

See also: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

**Comment by mthalman** [comment]
@valbers - The first `ARG SCSHARED_FEED_ACCESSOTOKEN` line isn't actually necessary.  `ARG` instructions defined above a `FROM` instruction are only needed if they define an arg that is going to be referenced within a `FROM` instruction line (e.g. defining an arg for a tag value).
