### ISSUE TITLE
SDK preview image missing

### ISSUE THREAD

**Issue by jchable** [dotnet/dotnet-docker#228]
## Steps to reproduce the issue
1. Find a preview image by clicking on the Preview link on the welcome page
2. Having a 404 error because the folder doesn't exist

## Expected behavior
=> Download sdk 2 preview docker image

## Actual behavior
=> 404 error page

**Comment by jchable** [comment]
Even if the link is dead, we can find the SDK preview Docker image at : https://github.com/dotnet/dotnet-docker-nightly

**Comment by MichaelSimons** [comment]
@jchable, thanks for bringing this issue to our attention.  I am going to re-open this issue as the broken link should be fixed.
