### ISSUE TITLE
Upgrade samples to 5.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2285]
After the GA release of the official 5.0 images, the samples should be upgraded to target 5.0 instead of 3.1.

**Comment by MichaelSimons** [comment]
@mthalman - I see a number of 3.1 references in the samples markdown.  Is there another issue tracking this work or should it be tracked with this issue?  I see this issue was recently moved to Rollout.

**Comment by mthalman** [comment]
I missed those.  I'll update that content as part of https://github.com/dotnet/dotnet-docker/pull/2356.
