### ISSUE TITLE
dotnet restore tries to access /.nuget/NuGet/NuGet.Config

### ISSUE THREAD

**Issue by roederja2** [dotnet/dotnet-docker#229]
## Steps to reproduce the issue
1.  Use the dotnet:1.1.1-sdk image to build a dotnet project with Jenkins on Linux.
2. Start off the build with dotnet restore --configfile NuGet.Config in the directory with the solution

## Expected behavior
Restore works

## Actual behavior
```
dotnet restore --configfile NuGet.Config

/usr/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Failed to read NuGet.Config due to unauthorized access. Path: '/.nuget/NuGet/NuGet.Config'.
```

## Additional information (e.g. issue happens only occasionally)
I think this can be fixed by creating the path in the docker image. But really donet should not insist on reading from that location.

## Output of `docker version`

```
Client:
Version:         1.10.3
API version:     1.22
Package version: docker-common-1.10.3-57.el7.x86_64
Go version:      go1.6.2
Git commit:      79ebcd8-unsupported
Built:           Thu Oct 20 14:37:17 2016
OS/Arch:         linux/amd64

Server:
Version:         1.10.3
API version:     1.22
Package version: docker-common-1.10.3-57.el7.x86_64
Go version:      go1.6.2
Git commit:      79ebcd8-unsupported
Built:           Thu Oct 20 14:37:17 2016
OS/Arch:         linux/amd64
```

## Output of `docker info`

```
Containers: 83
Running: 1
Paused: 0
Stopped: 82
Images: 79
Server Version: 1.10.3
Storage Driver: devicemapper
Pool Name: docker-253:0-2216369-pool
Pool Blocksize: 65.54 kB
Base Device Size: 107.4 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 51.47 GB
Data Space Total: 107.4 GB
Data Space Available: 29.6 GB
Metadata Space Used: 56.44 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.091 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
Volume: local
Network: host bridge null
Authorization: rhel-push-plugin
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.64 GiB
Name: <SOME NAME>
ID: 2UXB:L6PV:3KWB:PN6C:BUEU:2K5D:MMD2:KIZW:HW62:SXPB:VFHM:YDM3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Comment by MichaelSimons** [comment]
roederja2, can you check if Jenkins is running the image with a specific user e.g. `docker run -u <XXX>`?  I recall Jenkins does this by default.  The behavior you describe is what I see if you run a dotnet image with a non-root user.  To workaround this you can run as root user `e.g don't specify the -u option or use -u 0` or you can set the HOME variable to a directory the current user has access to e.g. `export HOME=$PWD/artifacts/home`.

If you can confirm this is what is happening, then I think this issue should be moved to https://github.com/NuGet/Home/issues so that NuGet can provide a better experience for this scenario.

**Comment by roederja2** [comment]
Hi,
you are right Jenkins runs the image as a non-root user. I built an image that contains a config file at that location to fix this. I also mounted directories for the cache and packages directory to speed up the build. Nuget restore is insanely slow without the cache (even compared to running with an empty cache).

This should probably be documented somewhere. And yes agree that nuget should be fixed to not try to read the global config when another one is specified as an argument.

**Comment by MichaelSimons** [comment]
I believe NuGet's semantics are that any custom config is composed on top of the global config.  

Ideally it would be nice if the experience would just work in this scenario, perhaps by building a package cache in the local directory.  Alternatively, the user experience could guide users down the path to how to either setting up the correct permissions or instruct you how to configure NuGet to use an alternative path.

**Comment by MichaelSimons** [comment]
Moved to https://github.com/NuGet/Home/issues/5106.  Please continue the conversation on it.
