### ISSUE TITLE
Issue when pulling base docker image

### ISSUE THREAD

**Issue by merbla** [dotnet/dotnet-docker#23]
Hi,

I am not sure if this a local issue for myself or something larger.  When pulling the latest image from DockerHub for `microsoft/dotnet` I receive the following issue.

Am I missing something?

Thanks,

*Example*
```
$ docker pull microsoft/dotnet
Using default tag: latest
latest: Pulling from microsoft/dotnet

d89e1bee20d9: Pull complete
9e0bc8a71bde: Pull complete
27aa681c95e5: Pull complete
a3ed95caeb02: Pull complete
81a56d4235fc: Pull complete
37b228997dc8: Pull complete
4920b6adeb72: Pull complete
Digest: sha256:c6a0887f45714b800fa5208234eac091101842a4a210b7dac2a66b7929063081
Status: Downloaded newer image for microsoft/dotnet:latest

$ docker run -t -i microsoft/dotnet
root@bb68b5ae6796:/# dotnet
dotnet: lttng-ust-comm.c:1446: lttng_ust_init: Assertion `!ret' failed.
Aborted
```

*My Environment*

- `OSX 10.11.3`
- `Docker version 1.10.0, build 590d5108`
- `docker-machine version 0.6.0, build e27fb87`
- `Virtual Box 5.0.14 r105127`

**Comment by MichaelSimons** [comment]
@merbla, can you try running dotnet a second time and report back whether or not it is successful?

**Comment by dleeapho** [comment]
I can repro it, but it seems intermittent, ie on the same container, running dotnet will sometimes work.

**Comment by MichaelSimons** [comment]
This issue is being tracked in the dotnet cli repository - dotnet/cli#1582.

**Comment by merbla** [comment]
Thanks @MichaelSimons @dleeapho
