### ISSUE TITLE
Teamcity CI building docker-compose fails: "runtimeconfig.json"

### ISSUE THREAD

**Issue by gromilQaaaa** [dotnet/dotnet-docker#2302]
```
:35:19
  Building gateway
22:35:20
  Step 1/13 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
22:35:20
   ---> 28de0d96c539
22:35:20
  Step 2/13 : WORKDIR /app
22:35:20
   ---> Using cache
22:35:20
   ---> 2e3a6afcf772
22:35:20
  
22:35:20
  Step 3/13 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
22:35:20
   ---> c4155a9104a8
22:35:20
  Step 4/13 : WORKDIR /src
22:35:20
   ---> Using cache
22:35:20
   ---> eae44c180794
22:35:20
  Step 5/13 : COPY gateway/*csproj /csproj-files/
22:35:20
   ---> Using cache
22:35:20
   ---> 8a0a43b45313
22:35:20
  Step 6/13 : COPY . .
22:35:20
   ---> Using cache
22:35:20
   ---> 9d47f69cbd53
22:35:20
  Step 7/13 : WORKDIR gateway/
22:35:20
   ---> Using cache
22:35:20
   ---> 17c6566d7a6b
22:35:20
  Step 8/13 : RUN dotnet publish -c Release -o /app
22:35:23
   ---> Running in 27a0ede4e5da
22:35:24
  A JSON parsing exception occurred in [/usr/share/dotnet/sdk/3.1.402/dotnet.runtimeconfig.json]: * Line 1, Column 2 Syntax error: Malformed token
22:35:24
  Invalid runtimeconfig.json [/usr/share/dotnet/sdk/3.1.402/dotnet.runtimeconfig.json] [/usr/share/dotnet/sdk/3.1.402/dotnet.runtimeconfig.dev.json]
22:35:25
  Service 'gateway' failed to build: The command '/bin/sh -c dotnet publish -c Release -o /app' returned a non-zero code: 147
```

Hello, I was previously building with net.core 3.1.100 and everything was fine. But at some point docker file started picking up 3.1.402 which was not installed (Imo it is incorrect that you override docker image). Even after I installed the needed 3.1.402 the issue is still the same. Here is my Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

COPY gateway/*csproj /csproj-files/
COPY . .

WORKDIR gateway/
RUN dotnet publish -c Release -o /app


FROM build AS publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "gateway.dll"]
```

<img width="580" alt="image" src="https://user-images.githubusercontent.com/5392680/95625467-33242d80-0a81-11eb-884c-6810c8d72fc2.png">

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.8"
    }
  }
}
```

**Comment by MichaelSimons** [comment]
Given the error `A JSON parsing exception occurred in [/usr/share/dotnet/sdk/3.1.402/dotnet.runtimeconfig.json]: * Line 1, Column 2 Syntax error: Malformed token` it makes me think this is related to the BOM of the `dotnet.runtimeconfig.json` file.  @gromilQaaaa, are you using the latest `mcr.microsoft.com/dotnet/core/sdk:3.1` image?  Can you share the digest of the image you are using?

**Comment by gromilQaaaa** [comment]
mcr.microsoft.com/dotnet/core/sdk      3.1                     c4155a9104a8        4 weeks ago         708MB
mcr.microsoft.com/dotnet/core/aspnet   3.1                     28de0d96c539        4 weeks ago         207MB

@MichaelSimons these are the images that are being downloaded... As I see by this 3.1 it always downloads the latest minor version. And this logic broke my building :(

**Comment by gromilQaaaa** [comment]
```
docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:  
```

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 19
  Running: 12
  Paused: 0
  Stopped: 7
 Images: 31
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 19.6GiB
 Name: ubuntu
 ID: B2EC:HWES:OSQL:NMIJ:5D4Q:4CI6:3UZP:ABN2:7TXJ:CFHK:U4SP:SE5W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by gromilQaaaa** [comment]
Okay, I tried building the demo and it worked. And while doing that I noticed that it has downloaded newer image of 3.1 sdk. You are cheaters :D So I just removed all the dotnet images I had and it helped.
PS: but I still believe that it was some bug on your side :) Thank you for your help.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/5392680/95884024-4afef880-0d84-11eb-9f4e-b8430fb5d902.png">

**Comment by MichaelSimons** [comment]
The new .NET images you are referring to are a result of the base OS images (debian) changing/patching.  The .NET contents in these new images remained the same.  Anytime a base image is changed, the .NET images automatically get rebuilt/released.   You can read more about this on our [Staying up-to-date with .NET Container Images](https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/) blog post.  We will however be releasing a new version of .NET today as part of the regular patching release process.

If you don't like getting the latest .NET versions automatically, you can use the three part version tags such as `mcr.microsoft.com/dotnet/core/sdk:3.1.403`.  This allows you to control when you take new versions.  Keep in mind however, when a new patch version is released, the previous version is no longer supported which is why we encourage the use of the two part version tags.

I wish you had a repro so that this issue could be investigated further to be able to root cause the problem.
