### ISSUE TITLE
Using a nanoserver:2004 image shows error "no matching manifest for windows/amd64 10.0.17763 in the manifest list entries"

### ISSUE THREAD

**Issue by StefH** [dotnet/dotnet-docker#2303]
## Steps to reproduce the issue
Using this docker file:
``` dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
LABEL maintainer="Stef Heyenrath"
WORKDIR /app

# copy csproj and restore as distinct layers
COPY StandAlone.NETCoreApp.csproj ./
RUN dotnet restore

# copy everything else and build
COPY *.cs ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM mcr.microsoft.com/windows/nanoserver:2004
WORKDIR /app
COPY --from=build-env /app/out ./
EXPOSE 80
ENTRYPOINT ["dotnet", "wiremock-net.dll", "--Urls", "http://*:80"]
CMD ["--WireMockLogger", "WireMockConsoleLogger"]
```
(https://raw.githubusercontent.com/WireMock-Net/WireMock.Net-docker/master/StandAlone.NETCoreApp/Dockerfile.nanoserver-2004)

And this pipeline: https://github.com/WireMock-Net/WireMock.Net-docker/blob/master/azure-pipelines.nano.yml

## Expected behavior
Docker image is build and published.

## Actual behavior
```
Step 8/13 : FROM mcr.microsoft.com/windows/nanoserver:2004
2004: Pulling from windows/nanoserver
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
```

## Output of `docker version`
Don't know this, I'm using Azure Pipelines.

## Output of `docker info`
Don't know this, I'm using Azure Pipelines.

**Comment by MichaelSimons** [comment]
@StefH, It looks like you have your Azure Pipeline configured to run on a Windows Server 2019 environment as per [this yml setting](https://github.com/WireMock-Net/WireMock.Net-docker/blob/master/azure-pipelines.nano.yml#L2).  Windows containers have [version compatibility limits](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-10-2004).  This means that you cannot run a Windows Server 2004 container on a Windows Server 2019 machine/host.  What environment do you intend to run the resulting image on?  Is it a Windows Server 2019 environment or 2004?

**Comment by StefH** [comment]
Hello @MichaelSimons,

I thought that windows-2019 would be correct to build a 2004 nano image.

Which vmImage should I use in case I want to build a 2004 nano image?

**Comment by MichaelSimons** [comment]
By looking at the [supported hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) I don't see one that supports this scenario.  You may have to provide your own agent.  This is a question to ask Azure Pipelines.

Closing as this is not an issue with the .NET Core images.
