### ISSUE TITLE
Image for .netcore 2.0

### ISSUE THREAD

**Issue by Jonathan34** [dotnet/dotnet-docker#234]
Hi,

It seems image for .net core 2.0 are not available yet. It is an useful if one wants to test the deployment without messing up with its environment. Especially since .net core 2.0 will soon be in preview

**Comment by natemcmaster** [comment]
@Jonathan34 you can try pre-release images here: https://hub.docker.com/r/microsoft/dotnet-nightly/.

**Comment by Jonathan34** [comment]
Great, thanks! Might be a good idea to add a link in the main page :)

**Comment by Jonathan34** [comment]
So I tried the dotnet-nightly but it seems the 2.0 sdk is not included in the `*-sdk` images (nor the latest):
```
Starting test execution, please wait...
build_1  | Testhost process exited with error: It was not possible to find any compatible framework version
build_1  | The specified framework 'Microsoft.NETCore.App', version '2.0.0-preview2-25307-02' was not found.
build_1  |   - Check application dependencies and target a framework version installed at:
build_1  |       /
build_1  |   - Alternatively, install the framework version '2.0.0-preview2-25307-02'.
```

**Comment by natemcmaster** [comment]
The dotnet-nightly images contain 2.0.0-preview1 bits. See https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/sdk/jessie/Dockerfile#L20.

**Comment by Jonathan34** [comment]
I see, i thought it would point the latest. Preview 1 is fine.
although 
```/usr/share/dotnet/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): warning : Dependency specified was Microsoft.NETCore.App (>= 2.0.0-preview1-005957-00) but ended up with Microsoft.NETCore.
App 2.0.0-preview2-002062-00.```
But this has nothing to do with docker images.

**Comment by Jonathan34** [comment]
And I think i understand why this warning appears and prevents my test to run:
the nuget/myget feed does not contain the package provided in your docker image: 
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App

So nuget automatically tries to find the closer package `2.0.0-preview2-002062-00`.
So I do not have any solution for this to work with your image it seems...

Any clue @natemcmaster ?
Thanks

**Comment by natemcmaster** [comment]
@Jonathan34 can you share your csproj?

**Comment by Jonathan34** [comment]
My nuget.config
```
<packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```

my test csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-preview1-005957-00</RuntimeFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\API.csproj"></ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

**Comment by natemcmaster** [comment]
The problem is your `RuntimeFrameworkVersion` property. This should correspond to the version of Microsoft.NETCore.App you want to use. Because there is no package with version `2.0.0-preview1-005957-00`, NuGet is rolling you forward to preview2, as you previously mentioned. 

This fix: remove this property. The SDK will automatically use the version of Microsoft.NETCore.App that is bundled in the image.

**Comment by Jonathan34** [comment]
@natemcmaster thanks, i confirm it works without it... i was just following the dogfooding for .net 2.0: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#option-1-framework-dependent

**Comment by MichaelSimons** [comment]
Per @natemcmaster the https://hub.docker.com/r/microsoft/dotnet-nightly/ can be used to get the latest version of .NET Core before it is released.  Additionally .NET Core 2.0 preview 1 has been released therefore images are available on https://hub.docker.com/r/microsoft/dotnet/
