### ISSUE TITLE
Memory usage grows indefinitely in aspnet 3.1.9 in Kubernetes

### ISSUE THREAD

**Issue by irmomanie** [dotnet/dotnet-docker#2360]
### Describe the Bug

This references: https://github.com/dotnet/dotnet-docker/issues/1681
Memory grows indefinitely with 3.1.9-alpine image. I quickly tried reverting to 3.1.7, but that spiked even more on startup. So I moved back to 3.1.2 to see how it goes over time, and that seems to be stable.

### Steps to Reproduce

1. Create an ASPNET core project
2. Wrap in docker container using mcr.microsoft.com/dotnet/core/aspnet:3.1.9
3. Deploy the docker container into a Kubernetes cluster

### Other Information

<img width="1203" alt="Screenshot 2020-11-03 at 07 48 07" src="https://user-images.githubusercontent.com/72875474/97956656-8ac86700-1da9-11eb-9479-53f20be1b3bc.png">

**Comment by MichaelSimons** [comment]
@tmds - Thoughts?  Any `ProcessorCount` related changes made recently?

cc @richlander

**Comment by tmds** [comment]
I'm not aware of anything. cc @janvorli @Maoni0 

@irmomanie what are you running as Kubernetes cluster? Can you give more info about the Kubernetes version, and what distro and kernel is this running on?

**Comment by irmomanie** [comment]
It's a standard AKS cluster, with version 1.18.8.

**Comment by tmds** [comment]
@irmomanie have you tried using the non-alpine images?

**Comment by irmomanie** [comment]
No I haven't. I can try some this week to see if there's any difference.

**Comment by MichaelSimons** [comment]
@irmomanie, Have you had a chance to test your scenario on a non-alpine image?

**Comment by irmomanie** [comment]
Hi, no I haven't. I did start using 3.1.10 and that seems to be working fine.

**Comment by MichaelSimons** [comment]
Closing as it doesn't reproduce on 3.1.10.  If other's see this on the current release, please let us know.
