### ISSUE TITLE
Breaking Change: Removal of curl from .NET 5.0 runtime Docker images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2379]
# Removal of curl from runtime Docker images

The `curl` package has been removed from the `runtime` and `aspnet` Linux images with the release of .NET 5.0. This is considered a breaking change which may impact your build or application when upgrading to .NET 5.0.

## Details

Our primary goal in producing Docker images for .NET is to reduce the occurrences of security vulnerabilities. We determined that the use of `curl` in these images wasn't a common enough scenario to justify the increased security surface area it added. If you rely on `curl` as part of `docker build`, you are encouraged to install it yourself in your Dockerfile, or rely on multi-stage build, by using a buildpack-deps stage, as we do for [.NET runtime images](https://github.com/dotnet/dotnet-docker/blob/master/src/runtime/5.0/focal/amd64/Dockerfile#L5). If you only require `curl` when consuming the `sdk` image, you won't be affected since `curl` is included in that image.

### Related Issues

* [Remove curl from runtime image](https://github.com/dotnet/dotnet-docker/issues/1645)

**Comment by HaroonSaid** [comment]
noticed that wget is also not present, whats the recommend path for doing container health check?

**Comment by MichaelSimons** [comment]
> noticed that wget is also not present, whats the recommend path for doing container health check?

A couple options that come to mind.
1. Use an Alpine based image because it includes wget.
2. Add your tool of choice in your derived image.

**Comment by chrisbecke** [comment]
Might want to update [your docs ](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019) then.
