### ISSUE TITLE
Upgrade update-dependencies tool to .NET 5

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2389]
The update-dependencies tool is currently targeting .NET Core 3.1: https://github.com/dotnet/dotnet-docker/blob/4bb19cfbf6e5a43744c209ee6ae1ba28fb8ab309/eng/update-dependencies/update-dependencies.csproj#L5

Now that .NET 5 has been released, it should really be updated to that version.

**Comment by MichaelSimons** [comment]
We should log a similar issue for the dotnet-framework repo.
