### ISSUE TITLE
.NET Core Docker images will move to multi-arch based tags

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/dotnet-docker#239]
## Summary
Docker has a [multi-arch feature]( https://github.com/moby/moby/issues/15866) that [microsoft/dotnet-nightly]( https://hub.docker.com/r/microsoft/dotnet-nightly/) recently started utilizing.  The plan is to port this to the [official microsoft/dotnet repo]( https://hub.docker.com/r/microsoft/dotnet/) shortly.  The multi-arch feature allows a single tag to be used across multiple machine configurations.  Without this feature each architecture/OS/platform requires a unique tag.  For example, the microsoft/dotnet:1.0-runtime tag is based on Debian and microsoft/dotnet:1.0-runtime-nanoserver if based on Nano Server.  With multi-arch there will be one common microsoft/dotnet:1.0-runtime tag.  If you pull that tag from a Linux container environment you will get the Debian based image whereas if you pull that tag from a Windows container environment you will get the Nano Server based image.  This helps provide tag uniformity across Docker environments thus eliminating confusion.

Current microsoft/dotnet tags:
- [`1.0.5-runtime`, `1.0-runtime` (*1.0/debian/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/runtime/Dockerfile)
- [`1.0.5-runtime-nanoserver`, `1.0-runtime-nanoserver` (*1.0/nanoserver/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.0/nanoserver/runtime/Dockerfile)
- [`1.0.5-runtime-deps`, `1.0-runtime-deps` (*1.0/debian/runtime-deps/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/runtime-deps/Dockerfile)
- [`1.0.5-sdk`, `1.0-sdk` (*1.0/debian/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.0/debian/sdk/Dockerfile)
- [`1.0.5-sdk-nanoserver`, `1.0-sdk-nanoserver` (*1.0/nanoserver/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.0/nanoserver/sdk/Dockerfile)
- [`1.1.2-runtime`, `1.1-runtime`, `1-runtime`, `runtime` (*1.1/debian/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/runtime/Dockerfile)
- [`1.1.2-runtime-nanoserver`, `1.1-runtime-nanoserver`, `1-runtime-nanoserver`, `runtime-nanoserver` (*1.1/nanoserver/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.1/nanoserver/runtime/Dockerfile)
- [`1.1.2-runtime-deps`, `1.1-runtime-deps`, `1-runtime-deps`, `runtime-deps` (*1.1/debian/runtime-deps/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/runtime-deps/Dockerfile)
- [`1.1.2-sdk`, `1.1-sdk`, `1-sdk`, `sdk`, `latest` (*1.1/debian/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/sdk/Dockerfile)
- [`1.1.2-sdk-nanoserver`, `1.1-sdk-nanoserver`, `1-sdk-nanoserver`, `sdk-nanoserver`, `nanoserver` (*1.1/nanoserver/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/1.1/nanoserver/sdk/Dockerfile)
- [`2.0.0-preview1-runtime`, `2.0-runtime`, `2-runtime` (*2.0/debian/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/2.0/debian/runtime/Dockerfile)
- [`2.0.0-preview1-runtime-nanoserver`, `2.0-runtime-nanoserver`, `2-runtime-nanoserver` (*2.0/nanoserver/runtime/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/2.0/nanoserver/runtime/Dockerfile)
- [`2.0.0-preview1-runtime-deps`, `2.0-runtime-deps`, `2-runtime-deps` (*2.0/debian/runtime-deps/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/2.0/debian/runtime-deps/Dockerfile)
- [`2.0.0-preview1-sdk`, `2.0-sdk`, `2-sdk` (*2.0/debian/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/2.0/debian/sdk/Dockerfile)
- [`2.0.0-preview1-sdk-nanoserver`, `2.0-sdk-nanoserver`, `2-sdk-nanoserver` (*2.0/nanoserver/sdk/Dockerfile*)](https://github.com/dotnet/dotnet-docker/blob/master/2.0/nanoserver/sdk/Dockerfile)

New multi-arch microsoft/dotnet-nightly tags:
- `1.0.5-runtime`, `1.0-runtime`:
    - [`1.0.5-runtime-jessie` (*1.0/runtime/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/runtime/jessie/Dockerfile)
    - [`1.0.5-runtime-nanoserver` (*1.0/runtime/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/runtime/nanoserver/Dockerfile)
- `1.0.5-runtime-deps`, `1.0-runtime-deps`:
    - [`1.0.5-runtime-deps-jessie` (*1.0/runtime-deps/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/runtime-deps/jessie/Dockerfile)
- `1.0.5-sdk`, `1.0-sdk`:
    - [`1.0.5-sdk-jessie` (*1.0/sdk/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/sdk/jessie/Dockerfile)
    - [`1.0.5-sdk-nanoserver` (*1.0/sdk/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/sdk/nanoserver/Dockerfile)
- `1.1.2-runtime`, `1.1-runtime`, `1-runtime`, `runtime`:
   - [`1.1.2-runtime-jessie` (*1.1/runtime/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.1/runtime/jessie/Dockerfile)
    - [`1.1.2-runtime-nanoserver` (*1.1/runtime/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.1/runtime/nanoserver/Dockerfile)
- `1.1.2-runtime-deps`, `1.1-runtime-deps`, `1-runtime-deps`, `runtime-deps`:
    - [`1.1.2-runtime-deps-jessie` (*1.1/runtime-deps/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.1/runtime-deps/jessie/Dockerfile)
- `1.1.2-sdk`, `1.1-sdk`, `1-sdk`, `sdk`, `latest`:
    - [`1.1.2-sdk-jessie` (*1.1/sdk/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.1/sdk/jessie/Dockerfile)
    - [`1.1.2-sdk-nanoserver` (*1.1/sdk/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.1/sdk/nanoserver/Dockerfile)
- `2.0.0-preview1-runtime`, `2.0-runtime`, `2-runtime`:
    - [`2.0.0-preview1-runtime-jessie` (*2.0/runtime/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/runtime/jessie/Dockerfile)
    - [`2.0.0-preview1-runtime-nanoserver` (*2.0/runtime/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/runtime/nanoserver/Dockerfile)
- `2.0.0-preview1-runtime-deps`, `2.0-runtime-deps`, `2-runtime-deps`:
    - [`2.0.0-preview1-runtime-deps-jessie` (*2.0/runtime-deps/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/runtime-deps/jessie/Dockerfile)
- `2.0.0-preview1-sdk`, `2.0-sdk`, `2-sdk`:
    - [`2.0.0-preview1-sdk-jessie` (*2.0/sdk/jessie/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/sdk/jessie/Dockerfile)
    - [`2.0.0-preview1-sdk-nanoserver` (*2.0/sdk/nanoserver/Dockerfile*)](https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.0/sdk/nanoserver/Dockerfile)

This change has been in [microsoft/dotnet-nightly]( https://hub.docker.com/r/microsoft/dotnet-nightly/) for a little over a week. If you have feedback please file an issue on the [.NET Core Docker GitHub repo](https://github.com/dotnet/dotnet-docker).

## .NET Core Docker Tools
The tooling to produce multi-arch tags is still evolving.  As a result we found it necessary to create some tooling to build the images and produce the manifest that enables multi-arch.  This [tooling](https://github.com/dotnet/docker-tools) is open sourced as well.

[Reposting from dotnet/announcements](https://github.com/dotnet/announcements/issues/14)

**Comment by galvesribeiro** [comment]
First, thanks to @TerribleDev for remind that it was in the announcement repo, and sorry to all others being spammed. I though I was in the proper repo because the thread wasn't closed. Sorry my bad. (@kendrahavens forgot to lock it 😄 )

But in all cases, even being easy to create a Dockerfile, you will eventually get tons of questions asking "how to create a Windows Server Core with .Net Core image?" from newcomers really soon. So I think it don't hurt to have that image published. 

Btw, @terribledev, when I mentioned _missing APIs_  I was talking about WIN32 APIs, not .Net ones.

**Comment by kendrahavens** [comment]
Sorry, folks. Locking the conversation in the announcements repo let's us limit the notifications subscribers get there.

> Hey, I was saying that it should be on the list of .Net Core images since it is a valid scenario.

Thank you @galvesribeiro! I agree, we should make it an easy scenario to use. We are working with the VSTS team now to make a full .NET framework "build" image that would have msbuild, .NET Core sdk, and common assembly references to help with the monolithic scenarios you mention.

@TerribleDev This is precisely the scenario we are thinking of. It's good to hear more parties are interested in this.

**Comment by ronkpunk** [comment]
Hello, I'm trying to get a multi-arch docker image, starting from "mcr.microsoft.com/dotnet/aspnet:6.0" but I've an issue creating the "arm/v7" image.

Is this the right place where I can ask for (and maybe resolve) my issue?

Thank you in advance

**Comment by mthalman** [comment]
@ronkpunk - Please post your question to https://github.com/dotnet/dotnet-docker/discussions.
