### ISSUE TITLE
[Nightly] Utilize the Arcade dependency flow mechanism to update the product versions referenced by the Dockerfiles.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2395]
Currently the product dependency flow into this repo is achieved via custom logic specific to this repo.  A scheduled build runs once a day which utilizes _latest channel links_ to discover the latest product versions, updates the manifest.versions.json file, regenerates the artifacts (Dockerfiles, readmes, etc), and creates a PR.  The prescribed way to achieve this is to use the Arcade dependency flow mechanism but that wasn't thought to be possible because this repo is a little different in that artifacts need to be regenerated via custom logic specific to the repo.  In a recent discussion on this, a proposal was made that the dependency flow mechanism could be utilized to update the manifest.versions.json file and generate a PR.  A GH action could then be created that looks for this type of PR and creates an additional commit which contains the regenerated artifacts.  This provides a nice separation of responsibility between the common dependency flow mechanism and the specialized logic to trigger the code generation.

There isn't much of a business need/value to make this change at the moment.  It is not a trivial piece of work and the current process being utilized is satisfying the current needs.  If a time comes where this changes, we should consider implementing what is described here.  An example of when this may make sense to implement would be if/when the build infra is moved to GH actions.

cc @riarenas, @mmitche, @mthalman

**Comment by mthalman** [comment]
[Triage]
This is substantial work and its importance isn't too great. Our solution for using this is the update-dependencies tool
