### ISSUE TITLE
mcr.microsoft.com/dotnet/sdk:5.0 using MSBuild 16.8.0-preview-20475-05

### ISSUE THREAD

**Issue by johnkors** [dotnet/dotnet-docker#2400]
Is the 5.0 image correct to use a preview version of MSBuild?

Running dotnet publish using the 5.0 sdk tag within a container:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0
..
RUN dotnet publish
```

output from a docker build:
```
Step 6/10 : RUN dotnet publish
 ---> Running in f083add4a2b6
Microsoft (R) Build Engine version 16.8.0-preview-20475-05+aed5e7ed0 for .NET
```

While, if I do publish on my local machine without docker:

```
➜ MyApp git:(master) ✗ dotnet --version
5.0.100

➜  MyApp git:(master) ✗ dotnet publish
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
```

**Comment by MichaelSimons** [comment]
@johnkors, Can you check which version of the sdk your local mcr.microsoft.com/dotnet/sdk:5.0 image contains?  You can retrieve this by running the following command.

```
docker run --rm mcr.microsoft.com/dotnet/sdk:5.0 dotnet --info
```

I suspect that you have an older preview version of the sdk image cached on your machine.  You will need to re-pull the image to get the latest version - `docker pull mcr.microsoft.com/dotnet/sdk:5.0`.

**Comment by johnkors** [comment]
Ah, correct. Yes, I have an older image cached. Maybe my docker knowledge is a bit lacking - I was expecting this to update when the 5.0 image changed from preview to rtm. 

Do I have to re-pull the 5.0 image for every patch (ex., a potential 5.0.101 or 5.0.200)?

**Comment by MichaelSimons** [comment]
@johnkors, This behavior catches a lot of people at some point or another.  If you don't have an image pulled, commands like `build` and `run` will implicitly pull images but if the tag already exists locally, they will not "refresh" the image.  You will need to explicitly pull a tag if you want to get the latest image.  The build command does support a `--pull` option which you may find convenient for scenarios like this. HTH.
