### ISSUE TITLE
Including missing TLS Certificate 

### ISSUE THREAD

**Issue by Radu-Gina** [dotnet/dotnet-docker#2409]
Hello,

When will the 2 new certificates mentioned here (https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes) will be updated on the .NET Core images (https://hub.docker.com/_/microsoft-dotnet-core-sdk/):

- Microsoft RSA Root Certificate Authority 2017
- Microsoft ECC Root Certificate Authority 2017

Any time-frames for the update ?

Thanks !

**Comment by MichaelSimons** [comment]
The certificates included within the .NET images come from installing ca-certificates ([debian example](https://github.com/dotnet/dotnet-docker/blob/master/src/runtime-deps/3.1/buster-slim/amd64/Dockerfile#L5)).  If/when the the new msft certificates are included in this package, they will get picked in the next build of the .NET images.  This appears to have already happened in the Ubuntu based images but not yet for Alpine or Debian.
