### ISSUE TITLE
Creating Ubuntu Bionic images for .NET 5.0 (aspnet:5.0-bionic & sdk:5.0-bionic)

### ISSUE THREAD

**Issue by mburakeker** [dotnet/dotnet-docker#2415]
### Describe the Problem
I am having trouble establishing a connection to an MSSQL 13.0 server using aspnet:5.0-buster-slim, sdk:5.0-buster-slim images, and System.Data.SqlClient.SqlConnection method, and getting the following exception:
`System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)`
### Describe the Solution
For my problem, I have found out that this answer https://stackoverflow.com/a/58136494/5523378 works and I would like to ask if you could create the aspnet:5.0-bionic and sdk:5.0-bionic images.

### Additional Context
I believe that this issue is related to https://github.com/dotnet/SqlClient/issues/222

**Comment by mthalman** [comment]
Have you tried Ubuntu Focal instead (`aspnet:5.0-focal` & `sdk:5.0-focal`)?

Ubuntu Bionic (18.04) is an older version of Ubuntu.  Ubuntu Focal (20.04) is the latest version and was the supported version of Ubuntu at the time of the 5.0 release.  You can read about which versions are supported in our [platform support policy](https://github.com/dotnet/dotnet-docker/blob/master/documentation/platform-matrix-suport.md).  I suspect that Focal should work for you.

**Comment by mburakeker** [comment]
> Have you tried Ubuntu Focal instead (`aspnet:5.0-focal` & `sdk:5.0-focal`)?
> 
> Ubuntu Bionic (18.04) is an older version of Ubuntu. Ubuntu Focal (20.04) is the latest version and was the supported version of Ubuntu at the time of the 5.0 release. You can read about which versions are supported in our [platform support policy](https://github.com/dotnet/dotnet-docker/blob/master/documentation/platform-matrix-suport.md). I suspect that Focal should work for you.

Yes, I already have tried `5.0-buster-slim`, `5.0-focal`, `5.0-alpine`, `3.1-focal` but only `3.1-bionic` was solving my issue. 

I just tried it again to see if it was a caching issue but unfortunately, the problem still occurs.

**Comment by mthalman** [comment]
Ah, this is because Focal uses a newer version of the `openssl` package compared to Bionic (1.1.1f vs 1.1.1).  The newer version no longer supports TLS 1.0 and 1.1 and your target SQL Server likely is not supporting TLS 1.2 (see https://github.com/dotnet/SqlClient/issues/567#issuecomment-634390841).

The recommendation is to upgrade SQL Server to support TLS 1.2.  If you have no control over that, you may consider client-side configuration changes as documented in this [post](https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level).

I think it is unlikely we will add Bionic for 5.0 to support this scenario but I'll leave this open so we can discuss at triage.

**Comment by mburakeker** [comment]
Thanks for your help @mthalman 
In this case, we have no control over the SQL server so chose to rebuild the .NET 5.0 images with bionic. I am dropping the links below in case someone wants to create their own images or use the pre-built ones.

Source: https://github.com/ModelBusinessSolutions/dotnet-bionic-dockerfiles

Pre-built images for bionic amd64: 
<a href="https://hub.docker.com/r/modelerp/aspnet"> modelerp/aspnet:5.0.0-bionic-amd64</a>
<a href="https://hub.docker.com/r/modelerp/sdk"> modelerp/sdk:5.0.100-bionic-amd64</a>

**Comment by MichaelSimons** [comment]
Recapping what @mthalman previously stated, we are only going to support the latest Ubuntu LTS for 5.0 per our [platform support policy](https://github.com/dotnet/dotnet-docker/blob/master/documentation/platform-matrix-suport.md).  Our recommendation for scenarios that encounter this problem would be to modify the client-side config as documented in this [post](https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level).
