### ISSUE TITLE
dotnet/core/sdk:3.1 container cannot RUN apt-get update

### ISSUE THREAD

**Issue by akamor** [dotnet/dotnet-docker#2425]
### Describe the Bug

Cannot run apt-get update on mcr.microsoft.com/dotnet/core/sdk:3.1.

Looks to be because Debian 10 change to some repo names, perhaps.

When you run:

```bash
docker build -t repo .
```
You get the output
```bash
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1
 ---> f5db59f77c51
Step 2/2 : RUN apt-get update
 ---> Running in 70e241936b0b
Ign:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://security.debian.org/debian-security buster/updates InRelease
Ign:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 http://security.debian.org/debian-security buster/updates Release
  404  Not Found [IP: 151.101.202.132 80]
Err:5 http://deb.debian.org/debian buster Release
  404  Not Found [IP: 151.101.202.132 80]
Err:6 http://deb.debian.org/debian buster-updates Release
  404  Not Found [IP: 151.101.202.132 80]
Reading package lists...
E: The repository 'http://security.debian.org/debian-security buster/updates Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
```

### Steps to Reproduce

Use the following Dockerfile and run docker build -t repo .

```bash
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN apt-get update
```

### Output of `docker version`

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Output of `docker info`
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 5
  Paused: 0
  Stopped: 9
 Images: 151
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 50GiB
 Name: docker-desktop
 ID: TGAH:2NWV:RGY2:4LEV:N46P:5KDM:KPZ6:WOSM:WS25:WJIL:FW4Y:7KHT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 81
  Goroutines: 85
  System Time: 2020-12-02T04:25:18.9307381Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by MichaelSimons** [comment]
I suspect this is an issue with the Debian package feed that is not specific to Docker images.  I was able to run the following without issue.  I speculate the underlying package feed issue was resolved.

```console
> docker run --rm mcr.microsoft.com/dotnet/core/sdk:3.1 apt-get update
Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [254 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7856 B]
Fetched 8407 kB in 1s (5730 kB/s)
Reading package lists...
```

@akamor, Can you verify `apt-get update` is now working?

**Comment by akamor** [comment]
@MichaelSimons Unfortunately your docker run command still generates the same error for me.

When I add 

RUN apt-get update --allow-releaseinfo-change

to my Dockerfile things work, so I am at least unblocked.  I agree its likely a debian feed issue but I'm not seeing it anywhere else but for this docker image so was wondering if y'all had any other reports of this.

**Comment by MichaelSimons** [comment]
I have not heard of any others encountering this issue.  Have you tried using the base Debian image to rule out the .NET image?  `docker run --rm debian:buster apt-get update`

**Comment by akamor** [comment]
Sorry, I should've thought to do that.

It gives same error.  I think this issue can be closed out because its def not specific to the dotnet containers.  Thanks for your help.

**Comment by patelriki13** [comment]
@MichaelSimons 
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build

RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2

RUN apt-get update

RUN apt-get install -y openjdk-17-jre
```
**Error:** Unable to locate package openjdk-17-jre
```
> [4/4] RUN apt-get install -y openjdk-17-jre:
0.447 Reading package lists...
0.832 Building dependency tree...
0.908 Reading state information...
0.950 E: Unable to locate package openjdk-17-jre
------
```

Any idea for this error ? how to fix it?

**Comment by MichaelSimons** [comment]
> @MichaelSimons Dockerfile:
> 
> ```
> FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
> 
> RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2
> 
> RUN apt-get update
> 
> RUN apt-get install -y openjdk-17-jre
> ```
> 
> **Error:** Unable to locate package openjdk-17-jre
> 
> ```
> > [4/4] RUN apt-get install -y openjdk-17-jre:
> 0.447 Reading package lists...
> 0.832 Building dependency tree...
> 0.908 Reading state information...
> 0.950 E: Unable to locate package openjdk-17-jre
> ------
> ```
> 
> Any idea for this error ? how to fix it?

.NET 3.1 is EOL.  Please upgrade to a supported version.  I would suggest upgrading to the latest LTS version, 8.0, but 6.0 and 7.0 are also in support.  If you still have issues installing openjdk, I would be glad to help.

**Comment by patelriki13** [comment]
Thanks for replying, @MichaelSimons 
We cannot upgrade from 3.1 to the latest version because we have lagacy product and currently we don't have any plans for upgrade.

**Comment by lbussell** [comment]
> Thanks for replying, @MichaelSimons We cannot upgrade from 3.1 to the latest version because we have lagacy product and currently we don't have any plans for upgrade.

The 3.1 images were based on Debian 10:
```
PS> docker run --rm mcr.microsoft.com/dotnet/sdk:3.1 cat /etc/issue
Debian GNU/Linux 10 \n \l
```

The latest version of the JDK available on Debian 10 is `openjdk-11`:
```
PS> docker run --rm mcr.microsoft.com/dotnet/sdk:3.1 /bin/sh -c 'apt-get update && apt-cache search openjdk'
...
openjdk-11-jdk - OpenJDK Development Kit (JDK)
...
```

Unfortunately there's nothing we can do about which packages Debian ships.
