### ISSUE TITLE
Support pre-release servicing drops

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2427]
We should be providing updates of our nightly images whenever possible for servicing releases.  These would be drops that are not MSRC-related and thus would be publicly available.  For example, 5.0.1 is not a MSRC release so it has builds available at `https://dotnetcli.blob.core.windows.net/dotnet/sdk/5.0.1-servicing.<build>`.   Doing this for servicing drops is important for the same reason it's important for preview releases: it provides an additional level of validation of the release and specifically for container environments.

There are a few issues that need to be resolved in order to provide these updates:

- The Dockerfile templates do not currently support the path syntax required to reference these servicing drops.  The path includes the build version for the directory name but only the product version for the filename (e.g. https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.101-servicing.20601.5/dotnet-sdk-5.0.101-win-x64.zip).  But the Dockerfile templates use the same version in both the directory name and the filename: https://github.com/dotnet/dotnet-docker/blob/eb12720ccea648c2e543ffa1c358f47ba0cc292d/eng/dockerfile-templates/sdk/5.0/Dockerfile.nanoserver#L14  The Dockerfile template needs the ability to provide distinct values for the version specified between the directory and filename.
- The same issue exists for the update-dependencies tool for the URL that it constructs in order to retrieve the SHA values of the files.  While it does have logic to provide distinct version values between the directory and filename: https://github.com/dotnet/dotnet-docker/blob/eb12720ccea648c2e543ffa1c358f47ba0cc292d/eng/update-dependencies/DockerfileShaUpdater.cs#L36 It doesn't actually set those variables to distinct values for servicing drops due to its special case logic which only accounts for RTM releases: https://github.com/dotnet/dotnet-docker/blob/eb12720ccea648c2e543ffa1c358f47ba0cc292d/eng/update-dependencies/DockerfileShaUpdater.cs#L101
- In order to automate the creation of PRs that update the Dockerfile for new servicing drops, there needs to be changes to the build pipeline which does this.  Currently, the pipeline can only handle two channels: one for the the core .NET product (runtime, aspnet, sdk) and one for the .NET monitor tool.  These are represented as stages within the pipeline: https://github.com/dotnet/dotnet-docker/blob/eb12720ccea648c2e543ffa1c358f47ba0cc292d/eng/pipelines/update-dependencies.yml#L12 In order to be able to support nightly updates for both preview releases and servicing releases, there needs to be support for handling an additional channel.

**Comment by MichaelSimons** [comment]
Another piece to be on lookout for is that the PRs created by the update-dependencies tools don't overwrite each other.  For example I suspect the 3.1 PR might overwrite an existing 5.0 PR.

**Comment by mthalman** [comment]
Having a servicing release that is public-only is very rare. Nearly all of the servicing releases have internal builds associated with them. And support for that is available from https://github.com/dotnet/dotnet-docker/issues/2152.

It's not worth the investment to support building container images for .NET servicing builds that are public-only when they happen so rarely.
