### ISSUE TITLE
Unable to start debugging Docker container

### ISSUE THREAD

**Issue by PawLove** [dotnet/dotnet-docker#243]
Hi! I'm trying out the Visual Studio 2017 Community and ASP.NET Core web app and get a prompt stating "Unable to start debugging. Unable to establish a connection to VSDBG. Debug output may contain more information."

Output Windows shows the following:

Starting: "docker" exec -i dd11077d4248 /clrdbg/vsdbg/vsdbg --interpreter=mi
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/clrdbg/vsdbg/vsdbg\": stat /clrdbg/vsdbg/vsdbg: no such file or directory"
"docker" exited with code 126 (0x7E).

I saw that a similar problem was being discussed
https://github.com/dotnet/dotnet-docker/issues/162
But the solution did not help.

## Steps to reproduce the issue
1.Open VS 2017 Community
2.Create new ASP.NET Core Web App
3.Debug with Docker

## Expected behavior
Should run app in container and allow breakpoints, etc.

## Actual behavior
It prompts with error mentioned above. It does appear to deploy and run a container.

## Output of `docker version`
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

## Output of `docker info`
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 2NIF:L7XL:JNC7:UIWV:VCGX:KBZU:MITL:43VJ:X3VR:DWKL:BZAO:TXP6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 32
 System Time: 2017-05-22T17:19:35.5988348Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MichaelSimons** [comment]
@PawLove, Would you mind closing this issue and opening a new one at https://github.com/Microsoft/DockerTools?  This repo is just for the microsoft/dotnet Docker images.  We are trying to keep the tooling issues separate.  Thanks

**Comment by MichaelSimons** [comment]
Linking to related DockerTools issue - https://github.com/Microsoft/DockerTools/issues/17
