### ISSUE TITLE
Server Core 2016 LTSC + .Net Core

### ISSUE THREAD

**Issue by jbaig** [dotnet/dotnet-docker#2438]
> From: https://hub.docker.com/_/microsoft-dotnet-sdk/
> 
> Our plan is to produce .NET images for LTSC Windows Server versions, only. We also plan to produce Windows Server Core images for .NET 5.0+. If you want some other combinations of images, please file separate issues on this repo. We have achieved the goals that were set out by this issue.

_Originally posted by @richlander in https://github.com/dotnet/dotnet-docker/issues/1852#issuecomment-710649760_

There was an image created for 2019 LTSC, but will there be an image for the 2016 LTSC?  
That would still be covered until 2022.
[Base Image Lifecycle](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle)

**Comment by MichaelSimons** [comment]
Our intention was to support LTSC images starting with 2019 going forward.  We have not seen much demand for LTSC 2016 images.  We will leave this issue open for 1 month.  If this is an image that you would find useful, please +1 or leave a comment letting us know.

**Comment by MichaelSimons** [comment]
Closing, At this time we do not intend to add support for Windows Server Core LTSC 2016 images.  If this is an image variant you need, please let us know your usage scenario.

**Comment by iskiselev** [comment]
Per documentation at https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md:
Windows Server Core - support all LTS versions starting with .NET 5.0.

ltsc2016 image is still supported (though it is in extended support). If there is no intention to provide ltsc2016 docker images, it would be great to explicitly mention it in documentation.

**Comment by mthalman** [comment]
@iskiselev - I have a PR at https://github.com/dotnet/dotnet-docker/pull/4350 to clarify this in our doc. Thanks!
