### ISSUE TITLE
Update samples to demonstrate use of `--mount=type=cache` to speed up `dotnet restore`

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2457]
With the [release of Docker 20.10](https://www.docker.com/blog/introducing-docker-engine-20-10/), support has been added for `RUN --mount`.  One scenario for this feature is to provide a means to persist package caches such as NuGet between builds so that even if the layer is invalidated and has to be rebuilt, the cached contents can be reused in order to speed up builds.  The [.NET Docker Samples ](https://github.com/dotnet/dotnet-docker/tree/master/samples) should be updated to demonstrate the use of this new feature.

**Comment by rhyek** [comment]
How could we configure a mount cache for build artifacts to make dotnet build/publish faster on consecutive runs?

**Comment by mthalman** [comment]
Closing this in favor of https://github.com/dotnet/dotnet-docker/issues/1788.
