### ISSUE TITLE
Add validation of packages installed by the Dockerfiles so that they align with the product

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#246]
### Summary

The packages that are installed by Dockerfiles are defined independently of what the product's actual dependencies are.  These should be in sync such that if product dependencies are changed in any way, the Dockerfiles will reflect that change.  Today this is a manual process but it can be improved through the work being done in https://github.com/dotnet/core/issues/5651.

### Goal

Contributors can use automation to validate that the Linux packages installed in Dockerfiles match up with the official product dependencies.

**Comment by MichaelSimons** [comment]
@mthalman - Can you log a product issue to define a place where the native dependencies are declared?  This is the only way to guarantee the Docker images, snaps, and native linux packages (e.g. debian packages) all include the correct set.

**Comment by mthalman** [comment]
I've logged https://github.com/dotnet/coreclr/issues/26303 for the product to provide a way to determine the required package list.

**Comment by mthalman** [comment]
Closing as this requires more work on https://github.com/dotnet/core/issues/5651 that's not happening any time soon.
