### ISSUE TITLE
Request for daily builds for 2-sdk?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/dotnet-docker#247]
We're currently stuck waiting for preview 2 as many things that are currently in the develop branch fix problems we have with preview 1. 

Currently there is no easy way to run these daily builds in a container, except creating them ourselves.

Would it be possible to weekly/daily publish a container with a 'daily' build of the 2.0 previews?

**Comment by natemcmaster** [comment]
Have you checked out https://github.com/dotnet/dotnet-docker-nightly?

**Comment by NinoFloris** [comment]
How I did not find this... :) thanks guys!
