### ISSUE TITLE
Move image to debian stretch

### ISSUE THREAD

**Issue by aensidhe** [dotnet/dotnet-docker#250]
Debian stretch will be [released at June, 17](https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html). I would suggest to move .net core images to debian stretch, because it has newer (and safer) packages like graphicsmagick 1.3.25, not 1.3.20, etc.

Also, it would be new LTS release of Debian.

**Comment by natemcmaster** [comment]
cc @MichaelSimons @richlander

**Comment by MichaelSimons** [comment]
@aensidhe, the current plan is to release the 2.0 images based on top of debian stretch.  We already have images available in [microsoft/dotnet-nightly](https://hub.docker.com/r/microsoft/dotnet-nightly/).  We are also in the [midst of making](https://github.com/dotnet/dotnet-docker-nightly/issues/321) these the default images for linux.  Modifying the 1.0 images to be based on stretch seems like it would be a breaking change.  We could add debian:stretch based images for 1.0 but there are no plans to do this at the moment.

**Comment by aensidhe** [comment]
@MichaelSimons ok, we can create them ourselves for us. Only one question remains - will VS debugging work with them or not. I think, I should try someday and find out.

**Comment by richlander** [comment]
@aensidhe Would be great to learn more about your use case. Mail me at rlander@ms if you'd like to chat.

**Comment by MichaelSimons** [comment]
Debian Stretch Dockerfiles have been added for 2.0 (in preview) - https://github.com/dotnet/dotnet-docker/commit/5718313edebd70fa2ec4db35424ce656575be348.  See [announcement](https://github.com/dotnet/announcements/issues/16) for more details.
