### ISSUE TITLE
Can we register bash completions for the 2.0+ sdk images?

### ISSUE THREAD

**Issue by g0t4** [dotnet/dotnet-docker#251]
The .NET Core 2.0 CLI has command line completion, it would be nice to enable completion for SDK images. 

Here are the completion docs: https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md

Here's the registration script: https://github.com/dotnet/cli/blob/master/scripts/register-completions.bash

**Comment by MichaelSimons** [comment]
@richlander, @kendrahavens - Thoughts on enabling this in the 2.0 SDK images?  I think it would be useful.  I do have some concerns however with taking a dependency on the registration scripts that are at the source tip versus archived with the build artifacts that we consume in the Dockerfile.  As it stands, it is theoretically possible that the Dockerfile could break if a non-compatible change where made to the scripts.  If we want to do this I can work with the CLI team on how this concern could be addressed.

**Comment by MichaelSimons** [comment]
Found out from the CLI team that story around this feature is not complete.  They are eventually planning on supporting a way to install/register tab completion which will alleviate the concerns I mentioned earlier.  This won't happen until post 2.0.  The recommendation from CLI was to hold off enabling within the official Dockerfiles until the feature is complete.

**Comment by omajid** [comment]
> Found out from the CLI team that story around this feature is not complete. They are eventually planning on supporting a way to install/register tab completion which will alleviate the concerns I mentioned earlier. 

Can you share any details? I found out that copying the current bash completion to `/usr/share/bash-completion/completions/dotnet` seems to work fairly well.

**Comment by g0t4** [comment]
I assume we'll have something like dotnet complete install? Similar to npm
completion?

https://docs.npmjs.com/cli/completion

-- 
Typed with thumbs and sent with love from Boomerang



----------
On Thu, Jun 22, 2017 at 11:04 AM, Omair Majid <notifications@github.com>
wrote:

Found out from the CLI team that story around this feature is not complete.
They are eventually planning on supporting a way to install/register tab
completion which will alleviate the concerns I mentioned earlier.

Can you share any details? I found out that copying the current bash
completion to /usr/share/bash-completion/completions/dotnet seems to work
fairly well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/dotnet-docker/issues/251#issuecomment-310407798>,
or mute the thread

**Comment by MichaelSimons** [comment]
@g0t4 - yes that is where CLI would like to get to.

**Comment by mthalman** [comment]
[Triage]
No additional work has been done to allow the tab completion registration script be consumable in a supportable way. Given that and that there hasn't been much demand for this feature, we're going to close this.
