### ISSUE TITLE
Previous arm64 solutions build stop working

### ISSUE THREAD

**Issue by valeria-tejada-incontact** [dotnet/dotnet-docker#2513]
### Describe the Bug

On our current solutions, we use dotnet build for arm64 architecture using sdk:3.1.402-bionic-arm64v8 image, this used to work properly until December 20th, after that date we experienced a return code 1.

### Steps to Reproduce

1. Create a base solution using netcore 3.1
2. Add docker support
3. Insert the following docker code:
`FROM mcr.microsoft.com/dotnet/core/runtime:3.1.8-bionic-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic-arm64v8 AS devBase
WORKDIR /src

FROM devBase AS build
COPY . .
RUN dotnet build "src/Test.sln" -c Release -o /app

FROM build AS publish
RUN dotnet publish "src/Test.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Test.dll"]`

4. Run docker command => docker build -f ./Dockerfile -t test .

### Other Information

Usually execute this command take a few minutes but with the issue, it gets stuck around 30 min.

### Output of `docker version`

Docker version 19.03.13, build 4484c46d9d

### Output of `docker info`

`Step 1/14: FROM mcr.microsoft.com/dotnet/core/runtime:3.1.8-bionic-arm64v8 AS base
3.1.8-bionic-arm64v8: Pulling from dotnet/core/runtime
c9ca07cb7eb0: Pull complete
Digest: sha256:3cae85d41d0c2e73d04208d06989ca063f0479ac990c8a27c8485efda90f3955
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/runtime:3.1.8-bionic-arm64v8
 ---> 2ca3cdd191f8
Step 2/14 : WORKDIR /app
 ---> Running in fe58a5b5c075
Removing intermediate container fe58a5b5c075
 ---> 8a3b2d7cf50c
Step 3/14 : EXPOSE 80
 ---> Running in b0af7c98523c
Removing intermediate container b0af7c98523c
 ---> 5def6c0843a9
Step 4/14 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic-arm64v8 AS devBase
3.1.402-bionic-arm64v8: Pulling from dotnet/core/sdk
3aa6ae443a21: Pull complete
Digest: sha256:46b85c71c3ca2820588681b729ebca2214de6f0d00cb8bf5f15b2faabde2e3f5
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic-arm64v8
 ---> 52d1ae94fea9
Step 5/14 : WORKDIR /src
 ---> Running in f3710b863c1e
Removing intermediate container f3710b863c1e
 ---> ad904e47f38d
Step 6/14 : FROM devBase AS build
 ---> ad904e47f38d
Step 7/14 : COPY . .
 ---> b22d3c30380e
Step 8/14 : RUN dotnet build "src/Test.sln" -c Release -o /app
 ---> Running in c45d0e620b12
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /src/Test/Test.csproj (in 9.52 sec).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:37:32.32
The command '/bin/sh -c dotnet build "src/Test.sln" -c Release -o /app' returned a non-zero code: 1`

**Comment by MichaelSimons** [comment]
@valeria-tejada-incontact, I would suggest enabling verbose output during the build (e.g. `-v d` or `-v diag`).  Look through the output for details on the source of the failure and what is taking so much time.

**Comment by valeria-tejada-incontact** [comment]
Thank you for your response @MichaelSimons! I tried that and found some NuGet packages that were taking too much time to restore. So I created an empty project and tried to build it for arm64 architecture using the same Docker containers as other projects but it still fails. This is the last part of the verbose output:

`2:6>Done building target "_CleanGetCurrentAndPriorFileWrites" in project "TestApp.csproj".
   2:6>Target "_CleanRecordFileWrites" in file "/usr/share/dotnet/sdk/3.1.402/Microsoft.Common.CurrentVersion.targets" from project "/src/TestApp/TestApp.csproj" (target "CoreBuild" depends on it):
       Task "RemoveDuplicates"
       Done executing task "RemoveDuplicates".
       Task "MakeDir"
       Done executing task "MakeDir".
       Task "WriteLinesToFile"
       Done executing task "WriteLinesToFile".
   2:6>Done building target "_CleanRecordFileWrites" in project "TestApp.csproj".
   2:6>Done Building Project "/src/TestApp/TestApp.csproj" (default targets) -- FAILED.
   1:2>Done executing task "MSBuild" -- FAILED.
   1:2>Done building target "Build" in project "TestApp.sln" -- FAILED.
   1:2>Done Building Project "/src/TestApp.sln" (default targets) -- FAILED.

Build FAILED.

       "/src/TestApp.sln" (default target) (1:2) ->
       "/src/TestApp/TestApp.csproj" (default target) (2:6) ->
       (CoreCompile target) ->
         /usr/share/dotnet/sdk/3.1.402/Roslyn/Microsoft.CSharp.Core.targets(70,5): error : qemu: uncaught target signal 11 (Segmentation fault) - core dumped [/src/TestApp/TestApp.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:05.80
The command '/bin/sh -c dotnet build "TestApp.sln" -c Release -o /app/build -r linux-arm -v d' returned a non-zero code: 1`

This project only contains a 'Hello World' and builds running dotnet build locally, only fails when I add docker support for arm64 architecture.

**Comment by MichaelSimons** [comment]
It appears as though you may be trying to run a .NET arm image with an amd64 docker host. If so, Docker utilizes QEMU in this scenario which is not a supported .NET configuration.  You can build arm images with an amd host but cannot run them.  The .NET Docker samples describe this pattern [here](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/README.md#build-an-image-for-arm32-and-arm64).

**Comment by valeria-tejada-incontact** [comment]
This was working before and no code or configuration changes were pushed on our projects. I checked several times with the different images and frameworks that are offered on Docker Hub. 

We are using this one:
![image](https://user-images.githubusercontent.com/45498473/105076453-7408e680-5a61-11eb-852d-73f32356b882.png)
![image](https://user-images.githubusercontent.com/45498473/105076724-d1049c80-5a61-11eb-989b-d522864d275d.png)

Is there any other image that we could use?

**Comment by valeria-tejada-incontact** [comment]
I just found that the issue is displayed when this command is executed:
`RUN dotnet build "TestApp.sln" -c **release** -o /app/build -r linux-arm`

But if you change the **release** to **debug** it works as expected.

**Comment by MichaelSimons** [comment]
@valeria-tejada-incontact, Can you paste the output of running `docker info`?  Can you include Dockerfile that works and the Dockerfile that doesn't?  Is the only difference `-c debug` vs `-c release`?

**Comment by valeria-tejada-incontact** [comment]
I tried to reproduce the issue and paste the output but I wasn't able to do it. 
Yes, the only change was between `-c debug` and `-c release` as you can see on the images.

**Comment by valeria-tejada-incontact** [comment]
I will close this issue as our solutions are building properly on arm64 architecture now, if there's any new change on docker containers please let me know. Thank you for all your help :)
