### ISSUE TITLE
Pipebuild definitions should reference a specific version of pipebuild

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#253]
There recently was a regression in the pipebuild tool used for builds.  This caused the docker builds to fail.  The reason the docker builds started failing was because the build definition references the latest version of the pipebuild tool.  This reference should be changed to a specific version.  It should be an explicit action to take a newer version of pipebuild.

**Comment by richlander** [comment]
So, should we make that explicit action?

**Comment by MichaelSimons** [comment]
Yes - I was planning to make this change the next time I have to touch the build definition.

**Comment by MichaelSimons** [comment]
I just modified all of the docker pipebuild definitions to use an explicit version of the tool.
