### ISSUE TITLE
Add support for Alpine 3.13

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2530]
# New Linux Distro Version

Distro: [Alpine 3.13](https://alpinelinux.org/posts/Alpine-3.13.0-released.html)

## ImageBuilder Tasks

- [x] Ensure that the ImageBuilder supports the new distro version in the [code](https://github.com/dotnet/docker-tools/blob/master/src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs) to generate the correct README display name from the version specified in the manifest

## Nightly Branch Tasks

1. - [x] Copy the Dockerfiles of the most recent version of that distro (or author new ones for an entirely new distro) and place them in a version-specific folder under their respective variants (runtime-deps, runtime, aspnet, sdk). Note: not all variants have a corresponding runtime-deps image.
1. - [x] Modify the Dockerfiles as appropriate for any specific changes related to the new distro version
1. - [x] Update [manifest.json](https://github.com/dotnet/dotnet-docker/blob/nightly/manifest.json) to reference the new set of Dockerfiles with the appropriate tags
      - [x] Move any distro-specific floating tags to the newer version (e.g. `3.1-alpine`)
1. - [x] Update the [test data](https://github.com/dotnet/dotnet-docker/blob/nightly/tests/Microsoft.DotNet.Docker.Tests/TestData.cs) to include the new distro version
1. - [x] Update the [tags metadata templates](https://github.com/dotnet/dotnet-docker/tree/master/eng/mcr-tags-metadata-templates) to include the new distro version
1. - [x] Run the command to update the READMEs: `.\eng\readme-templates\Get-GeneratedReadmes.ps1`
1. - [x] Run the command to update the image size baseline file: `.\tests\performance\Validate-ImageSize.ps1 -UpdateBaselines`
1. - [x] Inspect generated changes for correctness
1. - [x] Consider whether sample Dockerfiles should be authored if this is a new distro and them to the [samples](https://github.com/dotnet/dotnet-docker/tree/master/samples)
1. - [x] Run the command to build and test your changes: `.build-and-test.ps1 -OS <os>`
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR to nightly branch
1. - [x] Wait for automatically queued CI build to finish on [dotnet-docker-nightly pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=359) (internal MSFT link)
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in [Docker Hub](https://hub.docker.com/_/microsoft-dotnet-nightly)

## Master Branch Tasks

1. - [x] Revert the changes in (https://github.com/dotnet/dotnet-docker/pull/2566) when support for 2.1 and 3.1 is ready.
1. - [x] After the product teams have signed off on the new distro, merge these changes to the master branch as part of the [release process](dotnet-release.md) for the next .NET release
1. - [x] Create an announcement (example: [Alpine 3.10](https://github.com/dotnet/dotnet-docker/issues/1418)) unless the new distro is added only for pre-release versions in which the announcement would be incorporated in the pre-release notes.
      - [x] 5.0 announcement: https://github.com/dotnet/dotnet-docker/issues/2593

**Comment by mthalman** [comment]
Related to https://github.com/dotnet/core/issues/5687

**Comment by andyast** [comment]
Is there a plan to support Alpine 3.13 for 3.1?  I see updated .NET 5.0 images but not for 3.1.


Thanks

**Comment by mthalman** [comment]
> Is there a plan to support Alpine 3.13 for .NET 3.1? I see updated .NET 5.0 images but not for 3.1.
> 
> Thanks

Yes, there is a plan for 3.1.  We weren't able to get the proper amount of Alpine 3.13 validation done in time for the last 3.1 servicing release.  Expect to see it in a future 3.1 servicing release.

**Comment by andyast** [comment]
Thank you, are the servicing releases on a schedule?

**Comment by mthalman** [comment]
Yes, 2nd Tuesday of every month (aka Patch Tuesday).

**Comment by andyast** [comment]
> Yes, 2nd Tuesday of every month (aka Patch Tuesday).

Perfect.   Thank you.

**Comment by MichaelSimons** [comment]
@andyast, FYI, https://github.com/dotnet/core/issues/5687 tracks the overall Alpine 3.13 onboarding status and also provides a timeline for completion.

**Comment by andyast** [comment]
> @andyast, FYI, [dotnet/core#5687](https://github.com/dotnet/core/issues/5687) tracks the overall Alpine 3.13 onboarding status and also provides a timeline for completion.

Thank you, not sure how I missed that while searching.

**Comment by MichaelSimons** [comment]
@andyast, you didn't miss it.  After seeing your question I asked the right folks to update the issue with the current status which they just did.  Thank you for asking!

**Comment by ektrah** [comment]
```
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:5.0-alpine3.13
  pull stats: download 168.2MiB in 4.255s (39.53MiB/s), extract 168.2MiB in 2.858s (58.85MiB/s)
  time to create container: 412ms
  using image mcr.microsoft.com/dotnet/sdk@sha256:afd534d0f6d62945151e474de0eb5f506e82a5d0a3a8bcb85163ce6c70d54179
```
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.13
 OS Platform: Linux
 RID:         linux-musl-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Shouldn't the RID be *alpine.3.13-x64* rather than *linux-musl-x64*?

**Comment by mthalman** [comment]
> Shouldn't the RID be _alpine.3.13-x64_ rather than _linux-musl-x64_?

I've logged https://github.com/dotnet/runtime/issues/50739 for this issue.
