### ISSUE TITLE
Remove Alpine 3.13 arm32 workaround

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2539]
Some tests had to be [disabled](https://github.com/dotnet/dotnet-docker/pull/2532/commits/08582f1bd071ba5782f52c78357b684b3a377f32) when adding Dockerfiles for Alpine 3.13 arm32 due to https://github.com/dotnet/runtime/issues/47423.  These should be re-enabled when the issue is fixed.

**Comment by MichaelSimons** [comment]
[Triage] @mthalman - Can you link this to the fix and close?
