### ISSUE TITLE
>net Core 3.0 SDK docker images Powershell Core does not contain Certificate modules

### ISSUE THREAD

**Issue by parveenLily** [dotnet/dotnet-docker#2549]
When i try to install a root certificate i get the  following error, looks like certificates modules are not there yet, can i alteast import them?

Import-PfxCertificate : The term 'Import-PfxCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:80
+ ... ring rootpassword -AsPlainText -Force ; Import-PfxCertificate -FilePa ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Import-PfxCertificate:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by parveenLily** [comment]
i thought i added it to windows container issue?It is more like this issue:
Git missing in Windows-based SDK image (available on Linux) #2338.Could be lebeled docker files, enhencements.

**Comment by MichaelSimons** [comment]
Copied from _https://github.com/dotnet/dotnet-docker/issues/1069#issuecomment-769426728_ by @SteveL-MSFT

Import-PfxCertificate is part of the PKI module which is part of Windows, but works with PowerShell 7.

@SteveL-MSFT, Is it possible for users to add the PKI module in the .NET SDK images built on Nano Server?

@parveenLily, You mentioned `3.0`, this version of .NET is [no longer supported](https://github.com/dotnet/core/blob/master/releases.md).  Please upgrade to a supported version - 3.1 or 5.0.

**Comment by MichaelSimons** [comment]
I'm not certain whether or not the PKI module is compatible with Nano Server.  This is a question to ask in the [PowerShellCore community](https://github.com/PowerShell/PowerShell/issues/new/choose).

If you can upgrade your project to .NET 5.0, [Windows Server Core images are supported](https://github.com/dotnet/dotnet-docker/issues/2377).  With these you can install the PKI module via:

``` powershell
Install-Module WindowsCompatibility
Import-WinModule PKI
```
