### ISSUE TITLE
Security Vulnerabilities in dotnet/core/aspnet:3.1-bionic

### ISSUE THREAD

**Issue by vineetmimrot** [dotnet/dotnet-docker#2567]
### Describe the Bug
We are using mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic as the base image for our service, but we are getting the following security vulnerability listed in our S360 

1.  Ubuntu Security Notification for Apt Vulnerability (USN-4667-1) | Risk | MEDIUM | AdjustedSeverity | 5.7
2. Ubuntu Security Notification for P11-kit Vulnerabilities (USN-4677-1) | Risk | HIGH | AdjustedSeverity | 7.5

Please let me know if you need any more inputs.

**Comment by mthalman** [comment]
According to the documentation for those two notices, the images are up-to-date with the fixed packages.

USN-4667-1 requires version 1.6.12ubuntu0.2 of `apt`
USN-4677-1 requires version 0.23.9-2ubuntu0.1 of `libp11-kit0`

Both of these are satisfied as you can see in the results below:

```console
❯ docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
3.1-bionic: Pulling from dotnet/core/aspnet
Digest: sha256:990fc50c74a5cb714c425ee3af0de9106695cdd5da12fadec7b541a3aa5500cc
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic

❯ docker run --rm mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic /bin/sh -c "apt list | grep apt"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

apt/now 1.6.12ubuntu0.2 amd64 [installed,local]
libapt-pkg5.0/now 1.6.12ubuntu0.2 amd64 [installed,local]

❯ docker run --rm mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic /bin/sh -c "apt list | grep p11"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libp11-kit0/now 0.23.9-2ubuntu0.1 amd64 [installed,local]
```

Possible reasons for your scan results are that they are not reporting on the latest version of the image or they are false positives.

**Comment by vineetmimrot** [comment]
Thanks @mthalman  for the clarifications.
