### ISSUE TITLE
Set the Category, OS, and Architecture attributes of the Docker Hub repositories

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2588]
MCR now supports setting these attributes via it's repo YAML.  Setting these attributes will help the UX for users exploring the DH content.

Related to https://github.com/dotnet/docker-tools/issues/527 and https://github.com/dotnet/docker-tools/issues/526

See the MCR [documentation](https://msazure.visualstudio.com/MicrosoftContainerRegistry/_git/docs?path=%2FSections%2FProductAttributes.md&_a=preview) (internal Microsoft link) for details on how to specify the attributes in the MCR repo YAML.

**Comment by MichaelSimons** [comment]
The architecture and OS platform do not flow to DH correctly.  MCR is working to resolve the issue.

**Comment by lbussell** [comment]
[Triage] These attributes aren't being correctly mirrored to DockerHub. Tracking this issue isn't providing us any value currently so it should be closed.
