### ISSUE TITLE
Drop support for Alpine 3.12-based images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2596]
Per the [.NET Docker platform support policy](https://github.com/dotnet/dotnet-docker/blob/master/documentation/supported-platforms.md), support for any particular version of Alpine will be dropped three months after support for a new version is added.

.NET 5.0 Alpine 3.13 images were [released](https://github.com/dotnet/dotnet-docker/issues/2593) February 9, 2021. ~~As a result the Alpine 3.12 images will no longer be produced after May 9, 2021. At this time, the Dockerfiles should be removed from the repo, entries removed from the manifest.json, the tags should be removed from the READMEs, etc.~~

[Update] .NET 3.1 and 2.1 Alpine 3.13 images were release March 9th.  As a result the Alpine 3.12 images will no longer be produced after June 9, 2021. At this time, the Dockerfiles should be removed from the repo, entries removed from the manifest.json, the tags should be removed from the READMEs, etc.

**Comment by MichaelSimons** [comment]
[Triage] Even though 3.13 support for 3.1/2.1 and 5.0 did not come online at the same time, we recommend dropping 3.12 support at the same time.  We will remove support 3 months after the latest .NET version adds support.
