### ISSUE TITLE
`latest` image freezes immediately after running `dotnet new`

### ISSUE THREAD

**Issue by muojp** [dotnet/dotnet-docker#26]
Hi. I ran `microsoft/dotnet:latest` image to give a try on dotnet commands and found the image seem somehow wrong.

Repro:

```
$ docker run -it microsoft/dotnet:latest
# mkdir hello_world
root@880ccf5e3177:/# cd hello_world/
root@880ccf5e3177:/hello_world# dotnet new
Created new C# project in /hello_world.
^C^C
```

Issue: `Created new C# project in /hello_world.` line doesn't return and no further operation can be done (whole container freezes). Also, even if you try `docker kill XXXXXXXX` to force-kill frozen container, the container cannot be killed (only one workaround is to restart docker-daemon itself).

Env: I tested both on Linux host and Mac OS X(docker-machine+VMware Fusion) hosts and confirmed the same behavior.

Linux env:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
```

OS X env:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

Could anybody reproduce this?

FYI: current `latest` means https://hub.docker.com/r/microsoft/dotnet/builds/btl9c2jpeyehe89ivzdvfcr/ this image.

**Comment by MichaelSimons** [comment]
I have been able to reproduce this on 1.9.1.  It will also reproduce if you upgrade `dotnet` within the container to the latest version.  It will not repro for me once I upgrade the machine to docker 1.10 however.  That may be a viable workaround.  I also noticed it does not appear to be specific to any particular `dotnet` command - you can repro by just running `dotnet` to get the list of commands.

**Comment by muojp** [comment]
@MichaelSimons thanks. I confirmed it works fine on Docker 1.10.3.

I suppose it great to put `use 1.10+ or your Docker get stuck` sort of memo on README. How do you think?

**Comment by MichaelSimons** [comment]
@muojp, can you state what Linux host you were able to reproduce this issue with?  Os version? Kernel version?

I don't think it is a correct statement to say you need 1.10+ for this to work.  I suspect the underlying issue may be described here https://github.com/docker/docker/issues/18180.  If this is indeed the case, this is a kernel issue.

**Comment by muojp** [comment]
@MichaelSimons sure.

I can reproduce the issue on the following Linux env. (on Azure)

```
$ uname -a
Linux [hostname masked] 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux 8 \n \l
$ cat /etc/debian_version 
8.3
```

On the other hand, I cannot reproduce the issue anymore on my OS X env. (via VMware Fusion+Boot2Docker) after updating to b2d 1.10.3( https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso ):

```
$ uname -a
Linux dev 4.1.19-boot2docker #1 SMP Mon Mar 7 17:44:33 UTC 2016 x86_64 GNU/Linux
$ cat /etc/issue 
Core Linux
```

**Comment by MichaelSimons** [comment]
@muojp, per https://github.com/docker/docker/issues/18180#issuecomment-193708192, you would need to update your Debian kernel to 3.16.7-ckt20-1+deb8u4 to get the fix for the issue.

**Comment by muojp** [comment]
@MichaelSimons sounds great.

I performed `apt-get update` followed by `apt-get upgrade` and checked the log entry saying `replacing 3.16.7-ckt20-1+deb8u3 with 3.16.7-ckt20-1+deb8u4`, then I rebooted to see the result.

```
$ uname -a
Linux [hostname masked] 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
```

seems great. Then I tested the same command:

```
$ docker run -it microsoft/dotnet:latest
root@c4ba5b45ec6f:/# mkdir hello_world 
root@c4ba5b45ec6f:/# cd hello_world/
root@c4ba5b45ec6f:/hello_world# dotnet new
Created new C# project in /hello_world.
root@c4ba5b45ec6f:/hello_world# 
```

Great! Now I can continue testing `dotnet` command family with Docker. :smiley: I didn't imagine this is a kernel issue and also such a new one.

**Comment by dleeapho** [comment]
@muojp, thanks for surfacing it. To your suggestion of putting the something in the readme about this issue, since this is a kernel issue that is well known and it is not specific to dotnet I do not think we need to add this info to our readme.

**Comment by muojp** [comment]
@dleeapho okay. It sounds reasonable for me. So, shall I simply close this issue?

**Comment by TheRubble** [comment]
I'm having a the same issue on Ubuntu 14.04, if I use the image provided on docker hub. 
microsoft/dotnet:1.0.0-preview1, when ever I use dotnet new inside a container it hangs.

Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

**Comment by MichaelSimons** [comment]
@TheRubble - What version of Docker are you using?

**Comment by TheRubble** [comment]
@MichaelSimons Hi I'm using Docker version 1.11.2, build b9f10c9

**Comment by tugberkugurlu** [comment]
@therubble see this: https://github.com/docker/docker/issues/22357#issuecomment-222827798 I had the same issue and that solved my problem or I should probably say "worked around my problem".

**Comment by marwooj** [comment]
Mowing to overlay fixed my issue.
