### ISSUE TITLE
Azure Artifact Credential Provider example does not work

### ISSUE THREAD

**Issue by r3dr4gon** [dotnet/dotnet-docker#2609]
### Describe the Bug

The following example does not work:
https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider
 
The returned error: 
```error : Unable to load the service index for source ... error :   Response status code does not indicate success: 401 (Unauthorized) ...```

### Steps to Reproduce

Copy the dokerfile example and run it with docker build . --build-arg "Token"

### Other Information

If I use the same user name and password in the nuget.config file, everything is working as expected.
I.e. in this example:
https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#use-a-multi-stage-build-to-protect-nugetconfig-passed-by-build-context
In addition hardcoding the PAT in the password field, still results in 401.

### Output of `docker version`

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:26:48 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 35
 Server Version: 20.10.2
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1909 (OS Build 18363.1379)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.71GiB
 Name: LAPTOP-LIRON
 ID: 4XDY:MTFA:3I34:F7JF:5OIY:24NV:UN6I:45AR:OPXY:W2RC:XEJ2:YKRW
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
What example are you referring to?  Can you provide a link?

**Comment by r3dr4gon** [comment]
Terribly sorry, of course, I should have been more specific.
I update the title and explanation.

This is the example I was referring:
https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider

**Comment by mthalman** [comment]
I'm still having trouble understanding exactly which scenario is working for you and which is not.  Can you provide snippets of the Dockerfile, nuget.config, and Docker commands, replacing secrets with fake values as necessary?  I'd like to see snippets of both the scenarios that work for you and those that don't.

Also, be sure you read through the troubleshooting sections:
* https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#credential-provider-troubleshooting
* https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#general-troubleshooting

**Comment by r3dr4gon** [comment]
I will try to be more clear.

[Use a multi-stage build to protect nuget.config passed by build context](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#use-a-multi-stage-build-to-protect-nugetconfig-passed-by-build-context) works. (I.e. my username and PAT are working).

[Using the Azure Artifact Credential Provider](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider) Does not work, I took it as is (same docker file, different azure nuget feed which I used in the nuget.config hardcode method).

As for troubleshooting, I tried as suggested to print the env var:
```
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{`"endpointCredentials`": [{`"endpoint`":`"https://fabrikam.pkgs.visualstudio.com/_packaging/MyGreatFeed/nuget/v3/index.json`", `"username`":`"docker`", `"password`":`"${FEED_ACCESSTOKEN}`"}]}"
RUN echo %VSS_NUGET_EXTERNAL_FEED_ENDPOINTS%
```
This did not work (it just printed  %VSS_NUGET_EXTERNAL_FEED_ENDPOINTS%), I even tried hardcode the value of ${FEED_ACCESSTOKEN} in the:
```
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{`"endpointCredentials`": [{`"endpoint`":`"https://fabrikam.pkgs.visualstudio.com/_packaging/MyGreatFeed/nuget/v3/index.json`", `"username`":`"docker`", `"password`":`"XXX`"}]}"
```
Which also did not work.

My project is .net5, and there was no problem pinging microsoft server.

**Comment by mthalman** [comment]
> This did not work (it just printed %VSS_NUGET_EXTERNAL_FEED_ENDPOINTS%), I even tried hardcode the value of ${FEED_ACCESSTOKEN} in the:

If that's the case, then the Dockerfile must not be in the context of a Windows command shell at that point.  Can you provide more context with your Dockerfile?  What base image tag are you using?  Are you changing the `SHELL` prior to this point in the Dockerfile, for example to use PowerShell?

Are you using the same password between the nuget.config scenario and credential provider scenario?  Have you tried replacing the `` `"username`":`"docker`" `` portion of the string with your username?

**Comment by MichaelSimons** [comment]
[Triage] inactive - closing.
