### ISSUE TITLE
Microsoft SDK docker image can build but not run a web app

### ISSUE THREAD

**Issue by sfoslund** [dotnet/dotnet-docker#2611]
---
**Issue moved from dotnet/sdk#15109**
- Please respond to @LukePerrin.

---

_From @LukePerrin on Tuesday, December 29, 2020 12:12:09 PM_

Am trying to create a docker image where you can build/publish but also run a .net core website but having a real issue with image mcr.microsoft.com/dotnet/sdk:5.0. 

If you build inside a container with that it publishes no problem but when you run you get issues. By contrast if you run with mcr.microsoft.com/dotnet/aspnet:5.0
 then you get no issues, that runs the app fine, but of course you cant use that package to publish or build as its runtime only.

I have done an experiement to run a .net core web app using identical source code and dockerfiles except one is using the sdk and one is using aspnet. Both dockerfiles build an image using pre-built dlls from a publish folder that was generated before. They look like this..

docker file 1

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
#copy dlls from publish into working directory
COPY /publish .
ENTRYPOINT ["dotnet", "/app/Whipover.dll"]

docker file 2

FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
#copy dlls from publish into working directory
COPY /publish .
ENTRYPOINT ["dotnet", "/app/Whipover.dll"]
Docker file 1 image runs the website no problem,
 Docker file 2 image gives the error.. " Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'."

Do we know why that is? I thought the sdk image is supposed to be able to do everything the aspnet image can do. As for the error I could modify docker file 2 to include

#ENV ASPNETCORE_URLS=http://+:80
#EXPOSE 80 5000
.. which runs the website but then it cant retrieve the contents of wwwroot.. so that would be another issue. Also I dont see why I need to manually expose port 80 when dockerfile 1 had no problem at all?

Thanks

**Comment by MichaelSimons** [comment]
Please take a look at the [.NET Docker samples](https://github.com/dotnet/dotnet-docker/blob/master/samples/run-in-sdk-container.md#aspnet-core-app).  They demonstrate using the SDK to run an ASP.NET Core app.

**Comment by ntindle** [comment]
Also running into this issue. It reserves the port but nothing happens.

**Comment by MichaelSimons** [comment]
[Triage] @sfoslund or @ntindle - can either of you please share a project and Dockerfile that reproduces what you are encountering?

**Comment by ntindle** [comment]
I'm sorry, I cannot. I was able to work around this by using `dotnet run` instead of `dotnet project.dll`. I think it is something with krestral and my code not interacting correctly.

**Comment by MichaelSimons** [comment]
[Triage] closing as no repro was provided.
