### ISSUE TITLE
Tracking: Large disk size increase in Microsoft.NET.Sdk.Razor folder

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2616]
The size for the 6.0 SDK images had a fairly large increase due to a change in size of the `Microsoft.NET.Sdk.Razor` folder.  This is intended to be a tracking issue for the SDK issue that was logged for this: https://github.com/dotnet/sdk/issues/15996.

**Comment by mthalman** [comment]
The tracked issue has been closed as by design due to [crossgen changes](https://github.com/dotnet/installer/pull/9635) that were made in order to reduce JIT time in the SDK.

**Comment by MichaelSimons** [comment]
[Triage] this raises a question if the .NET Docker images should be cross gen'd differently than the primary product.
