### ISSUE TITLE
Validate installed packages against actual product dependencies

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2618]
### Summary

The packages that are installed by Dockerfiles are defined independently of what the product's actual dependencies are.  These should be in sync such that if product dependencies are changed in any way, the Dockerfiles will reflect that change.  Today this is a manual process but it can be improved through the work being done in https://github.com/dotnet/core/issues/5651.

### Goal

Contributors can use automation to validate that the Linux packages installed in Dockerfiles match up with the official product dependencies.

**Comment by MichaelSimons** [comment]
Is this a duplicate of https://github.com/dotnet/dotnet-docker/issues/246?  If so, perhaps we can adjust the wording of #246 and close this new issue.

**Comment by mthalman** [comment]
Ah, indeed.  Forgot about that.  I'll update the original.

Duplicate of #246
