### ISSUE TITLE
runtime-deps:5.0 cannot be pulled on Windows Server

### ISSUE THREAD

**Issue by dylan-smith** [dotnet/dotnet-docker#2634]
### Describe the Bug

You can't pull the dotnet/runtime-deps:5.0 image on Windows Server.  I think this is related to the image manifests, but I'm not entirely clear exactly how they work.

When running builds on GitHub-hosted Actions servers - which use Azure VM's running Windows Server 1809 (10.0.17763.1757) - you can docker pull sdk:5.0, aspnet:5.0, runtime:5.0 just fine, but runtime-deps:5.0 gives you an error:

![image](https://user-images.githubusercontent.com/1508559/109579767-256a5580-7abf-11eb-9775-e1a7c63c0eb9.png)

Interestingly it works on my local desktop, not sure if that's because I'm on a more recent version of Windows (2004 10.0.19041.804 - however for non-Core versions of Windows Server 1809 is the most recent build) or because I'm using Docker Desktop 20.10.2 whereas the build servers are using Docker EE 19.03.14 (which is the most recent version if you install using `Install-Package -Name docker -ProviderName DockerMsftProvider` which is how GitHub/Azure Pipelines install docker on their hosted-runners).

If you do a docker manifest inspect and compare the runtime:5.0 image to the runtime-deps:5.0 I see that the runtime-deps doesn't have any manifests for windows.  I suspect that is relevant.

`docker manifest inspect mcr.microsoft.com/dotnet/runtime-deps:5.0`
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:f7a58af2a9d69ca507ebe1bd1a460a7029954be6a7ba536fec1f383cae2119ea",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:eca7c9da1205a8b92d341a258a1eb40a7d8c20c226b61c96dfcba69c0c4355fc",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:89c25ec1609adad189fa66c01ed3ec447518a6d43258e4b92e45a61e9ada7e73",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

`docker manifest inspect mcr.microsoft.com/dotnet/runtime:5.0`
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1160,
         "digest": "sha256:2d1ee32fa04172a9cb05f31eee18e1b75ccef42f8092562354b9bbe40c66c8b9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1160,
         "digest": "sha256:ff6564a10d00bb2efdae72d7edd155835be40e2e5bc41ed1b65e956b11854932",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1160,
         "digest": "sha256:ff2024ed350975d32106e94e3c2bccaf2147574ede4b42fbba2266d00b150074",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1958,
         "digest": "sha256:6b5b069e43644d0da5b1e0e0d987616b40ba22dd664bc5e45bdc204441b47344",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1757"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1958,
         "digest": "sha256:0b6fcbe3c493583b368a18e67ff1ab02eb247aa31dcdccc2d409a7affd172ace",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18363.1379"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1962,
         "digest": "sha256:95aab2c9af752cbf1fb3700be9f15730b7a7514660ea41e42f262409d3bba865",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19041.804"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1962,
         "digest": "sha256:ebe7f8f0619dca3062944a5441db5a32b64ab1a057e497734dda06978c4dddf0",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.804"
         }
      }
   ]
}
```

### Steps to Reproduce

Easiest way to see it is to look at this GitHub Actions build that does a docker pull on both windows agents and linux agents:
https://github.com/dylan-smith/dotnet-docker/runs/2009155344

![image](https://user-images.githubusercontent.com/1508559/109580424-310a4c00-7ac0-11eb-8f04-fa48fabe6c1d.png)

### Other Information

Error Message:
```
5.0: Pulling from dotnet/runtime-deps
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
```

### Output of `docker version`

```
Client: Mirantis Container Runtime
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        e820475
 Built:             12/17/2020 19:30:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       57e3a05525
  Built:            12/17/2020 19:29:00
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Output of `docker info`

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 19.03.14
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1757)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7GiB
 Name: fv-az153-100
 ID: 77KY:5BYC:AW5U:JGEK:DBAV:2TQO:W2EJ:RRKB:Y2UP:PRPQ:A3R5:JQF3
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
> If you do a docker manifest inspect and compare the runtime:5.0 image to the runtime-deps:5.0 I see that the runtime-deps doesn't have any manifests for windows. I suspect that is relevant.

Correct.  You can also see that there are no tags listed for Windows at https://hub.docker.com/_/microsoft-dotnet-runtime-deps.  This is because runtime-deps is not applicable to Windows.  The runtime-deps images are intended to install dependencies that .NET requires.  For Linux, this involves installing several packages.  For Windows, everything that's needed is already included in the base Windows images.  Thus, there's no need for runtime-deps images for Windows.

What is the reason that you're attempting to pull this from a machine targeting Windows containers?

**Comment by dylan-smith** [comment]
I think this might come down to a lack of understanding on my part.  I wasn't aware until just now that when you use the same image tag on a windows host it builds a windows-based container, and a linux based one on a linux host.  And from what I can tell the Mirantis docker engine that is used on the windows servers doesn't support targeting linux based containers like docker desktop does on my windows workstation.

In that case the behavior makes sense, sorry for the noise.
