### ISSUE TITLE
aspnet 3.1 Dockerfiles don't set ASPNETCORE_VERSION environment variable

### ISSUE THREAD

**Issue by chreden** [dotnet/dotnet-docker#2662]
### Describe the Bug

None of the Dockerfiles for aspnet/3.1 set the ASPNETCORE_VERSION environment variable - some libraries that we use were using this to detect the asp.net core version.

I have manually added it into our product Dockerfiles but it feels like a hack. 3.1 seems like the odd one out as 2.1 (and 3.0) set it. 5.0/6.0 set ASPNET_VERSION.

If this was intentional I can raise a bug with the libraries that stopped working for them to deal with it or I can continue with the workaround.

### Steps to Reproduce

3.1:
```
docker inspect -f '{{.Config.Env}}' mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ASPNETCORE_URLS=http://+:80 DOTNET_RUNNING_IN_CONTAINER=true]
```

3.0:
```
 docker inspect -f '{{.Config.Env}}' mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ASPNETCORE_URLS=http://+:80 DOTNET_RUNNING_IN_CONTAINER=true DOTNET_VERSION=3.0.3 ASPNETCORE_VERSION=3.0.3]
```

**Comment by MichaelSimons** [comment]
[Triage] This is a duplicate of sorts to https://github.com/dotnet/dotnet-docker/issues/1743 which was fixed in 5.0.  We decided against backporting this to 3.1 because we consider it to be a breaking change.  Closing.
