### ISSUE TITLE
ToLowerInvariant fails on accented characters with runtime:3.1-alpine

### ISSUE THREAD

**Issue by stelian56** [dotnet/dotnet-docker#2675]
"JESÚS_RAMÓN".ToLowerInvariant() evaluates to "jesÚs_ramÓn" with mcr.microsoft.com/dotnet/core/runtime:3.1-alpine.

However, it evaluates to the expected "jesús_ramón" with mcr.microsoft.com/dotnet/core/runtime:3.1-focal.

**Comment by MichaelSimons** [comment]
The Alpine images have the .NET Invariant Mode enabled by default ([details](https://github.com/dotnet/dotnet-docker/issues/371)). Use cases that cannot tolerate the globalization invariant mode can reset the `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` environment variable ([Sample](https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile.alpine-x64#L18))

**Comment by stelian56** [comment]
Thank you @michael-clemens , your explanation makes sense.
