### ISSUE TITLE
Aspnet Core Arm64 Dockerfile url gone AWOL

### ISSUE THREAD

**Issue by alberk8** [dotnet/dotnet-docker#2698]
### Describe the Bug
The dockerfile  "RUN wget is getting a 404"

https://github.com/dotnet/dotnet-docker/blob/main/src/aspnet/5.0/alpine3.12/arm64v8/Dockerfile

### Steps to Reproduce
on Linux 
 $ wget -O aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.4/aspnetcore-runtime-5.0.4-l

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-136-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.852GiB
 Name: developmentdocker
 ID: WF42:3QGB:ZDVL:F6DF:TYY3:XMBJ:PCJS:GUOM:CBYH:5FQM:SABT:7SEA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: 
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by mthalman** [comment]
The URL you provided is cut off at the end: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.4/aspnetcore-runtime-5.0.4-l.  The correct URL is https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.4/aspnetcore-runtime-5.0.4-linux-musl-arm64.tar.gz.  That URL is downloading fine for me.

**Comment by MichaelSimons** [comment]
@alberk8, the ASP.NET Core url you included is incomplete

> $ wget -O aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.4/aspnetcore-runtime-5.0.4-l

Which flavor of the runtime you are trying to acquire.  The correct musl x64 url is `https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.4/aspnetcore-runtime-5.0.4-linux-musl-x64.tar.gz`

**Comment by MichaelSimons** [comment]
[Triage] Closing per @mthalman's response.
