### ISSUE TITLE
"It was not possible to find any installed .NET Core SDKs"

### ISSUE THREAD

**Issue by kasparwolfisbergscs** [dotnet/dotnet-docker#2706]
### Describe the Bug

I built a docker image via the visual studio generated Dockerfile.

```
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["NoSdkBug/NoSdkBug.csproj", "NoSdkBug/"]
RUN dotnet restore "NoSdkBug/NoSdkBug.csproj"
COPY . .
WORKDIR "/src/NoSdkBug"
RUN dotnet build "NoSdkBug.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NoSdkBug.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NoSdkBug.dll"]
```

This image runs fine when I run it locally on my docker engine (on a windows computer). When I push the image to our OpenShift cluster, the image does not work as intended and just puts this message out and shuts down:
```
It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download 
```
Now I have to assume this is either a bug with the aspnet:3.1 image or a misleading error message (why would an SDK be required to run an application?).

### Steps to Reproduce
Using
```
Microsoft Visual Studio Professional 2019
Version 16.9.2
```
1. Create new visual studio web-api application (.net Core).
1. Add docker and container orchestration support through VS.
1. Build the docker image (release config, I did it through the context menu of the generated docker-compose project)
1. Run the image on a kubernets / OpenShift cluster.

### Other Information

* Please include any relevant error messages.
This is the (only) message that the container will put out before shutting down.
```
It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download 
```
* Does this issue consistently happen? It has never not happened on openshift with this image.
* Do you know of any workarounds? No.

### Output of `docker version`
The Kubernets/OpenShift versions of the environment where the bug occurs:
```
openshift v3.11.374
kubernetes v1.11.0+d4cacc0
```

This is my local docker engine, where the image is built. The image runs fine on this.
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.32GiB
 Name: docker-desktop
 ID: 4DAK:XDAN:7F3U:HDFI:D4HI:JFQP:BYNV:ZTX6:XDGV:MTF2:63HK:H6PS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 42
  Goroutines: 47
  System Time: 2021-03-31T11:36:06.7287677Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
Does this happen with any project or just your project in particular?  For example, can you repro this using the [sample project](https://github.com/dotnet/dotnet-docker/tree/main/samples/aspnetapp)?

Can you provide the `docker run` command that is being used to run the container?

**Comment by kasparwolfisbergscs** [comment]
Well It happened in our "real" project and I wondered the same thing. So I created a new project in VS with docker and orchestration (compose) support and built the image, same error. So I assume it's not project specific.

I will try the sample project.

I'm not sure if I can figure out the exact ```docker run``` command that is being used by OpenShift (Kubernetes).

**Comment by mthalman** [comment]
> I'm not sure if I can figure out the exact `docker run` command that is being used by OpenShift (Kubernetes).

This is important to know because it may be overriding the ENTRYPOINT that is defined in the Dockerfile which could cause all sorts of behavior if it wasn't defined appropriately. I would suggest sifting through the logs if you can find anything there.

**Comment by omajid** [comment]
Hi!

Can you tell us a bit more about this step:

> Run the image on a kubernets / OpenShift cluster.

How are you running it? The exact commands would be nice to know. I am asking because there are some ways of building/running that might (?) modify the `ENTRYPOINT` and others that wont (AFAIK). If we know the exact command, we might have a better idea of what's going wrong and where.

Replacing the ENTRYPOINT with something like this might also let us find out more:

    ENTRYPOINT ["dotnet", "--info"]

And maybe also (in a separate build/run):

   ENTRYPOINT ["ls"]

cc @aslicerh

**Comment by kasparwolfisbergscs** [comment]
Thanks for the help.

In the end it came down to me mounting a volume to the wrong directory and thus overriding the .dll location with an empty directory. So the entrypoint pointed to a .dll that did not exist. An oversight on my part.

```
 It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

This error/warning message is the only output you'll get for a invalid .dll argument to the `dotnet` command and seems very misleading in this case. Especially since a running a `dotnet doesnotexist.dll` on my local dotnet runtime yields a different message that is a lot more helpful.

**Comment by mthalman** [comment]
> This error/warning message is the only output you'll get for a invalid .dll argument to the `dotnet` command and seems very misleading in this case. Especially since running a `dotnet doesnotexist.dll` on my local dotnet runtime yields a different message that is a lot more helpful.

Relevant: https://github.com/dotnet/sdk/issues/10648

**Comment by Sri-darshan** [comment]
I am also facing the similar issue, but I havent mounted any volume externally

Below is my dockerfile

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["API/API.csproj", "API/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Utility/Utility.csproj", "Utility/"]
COPY ["DataCore/DataCore.csproj", "DataCore/"]
RUN dotnet restore "API/API.csproj"
COPY . .
WORKDIR "/src/API"
RUN dotnet build "API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
#COPY --from=publish /app/publish . *tried this but no luck*
 COPY --from=publish publish .`
ENTRYPOINT ["dotnet", "run", "app/API.dll"]
#ENTRYPOINT ["dotnet", "run", "API.dll"] *no luck either*

**Comment by Sri-darshan** [comment]
docker logs 9e579eb345e0
It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download

**Comment by Sri-darshan** [comment]
My code is in gitlab and using gitlab-ci for CICD

**Comment by RenanFG** [comment]
> docker logs 9e579eb345e0 It was not possible to find any installed .NET Core SDKs Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from: https://aka.ms/dotnet-download

Same issue happened while Deploying in AKS (Azure). My dockerfile looks similar to urs. Any solution?
