### ISSUE TITLE
Having a `Get` method that has side-effects seems strange to me, especially considering that `GetAverage` has no side-effects.  This could maybe just be resolved by naming it something like `AddRangeAsync`.

### ISSUE THREAD

**Issue by BillyGeoThink2020** [dotnet/dotnet-docker#2730]
Having a `Get` method that has side-effects seems strange to me, especially considering that `GetAverage` has no side-effects.  This could maybe just be resolved by naming it something like `AddRangeAsync`.

_Originally posted by @mthalman in https://github.com/dotnet/dotnet-docker/pull/2713#r607147280_

**Comment by mthalman** [comment]
I'm assuming this was created by mistake.

**Comment by mthalman** [comment]
@BillyGeoThink2020 - If you intended to reply to the comment you posted, you can do so directly in the [PR discussion](https://github.com/dotnet/dotnet-docker/pull/2713).
