### ISSUE TITLE
Please make a lightweight image based on the features of alpine and .net self-containierd

### ISSUE THREAD

**Issue by Uchiha-Peng** [dotnet/dotnet-docker#2755]
### Describe the Problem

Please make a lightweight image based on the features of alpine and .net self-containierd

### Describe the Solution

Hello. NET development team, I am a .NET developer, I love .NET, .NET works well on Docker, but the image size of .NET application package is very large, I think you can use Alpine as the base image, Only install the dependencies required by .NET on Alpine without installing the runtime, and then use the self-contained features of .NET to publish a single file, so that the resulting image will be very small. I have done a test, the same MVC template application, the size of the image generated by the Dockerfile generated by Visual Studio is 210MB, and the image is generated by the self-contained way that does not depend on the runtime, and it is only 88MB. I think you can launch a self-contained official image, Thank you, and hope that .NET is getting better and better.

### Additional Context

This is the Dockerfile I tested and the detailed process: [click here](https://mp.weixin.qq.com/s/d9BlHCwOLAFhds5dR4nxiA)

```
FROM alpine:3.13 AS base
WORKDIR /app
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["mvcweb.csproj", "."]
RUN dotnet restore "./mvcweb.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "mvcweb.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "mvcweb.csproj" -c Release -o /app/publish --self-contained true -r linux-musl-x64 -f net5.0 -p:PublishSingleFile=true -p:PublishTrimmed=true
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENV TZ=Asia/Shanghai
EXPOSE 80
RUN chmod +x . \
    && apk add --no-cache tzdata icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \ 
    && echo $TZ > /etc/timezone
ENTRYPOINT ["./mvcweb]
```

**Comment by mthalman** [comment]
@Uchiha-Peng - Thanks for your input.  This is a known scenario for which we have a solution.  This is the purpose of the [`runtime-deps`](https://hub.docker.com/_/microsoft-dotnet-runtime-deps/) images.  Those images are based on the base Linux distro and then add the required Linux packages and configuration needed to run a .NET application.  This will then be capable of running a self-contained .NET application.  Please read our sample documentation on [optimizing for size](https://github.com/dotnet/dotnet-docker/tree/main/samples/aspnetapp#optimizing-for-size) as well as a [sample Dockerfile](https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.alpine-x64-slim) that effectively accomplishes the same thing as you've described here.

Let me know whether this solution accomplishes what you're wanting.

**Comment by Uchiha-Peng** [comment]
Thank You
