### ISSUE TITLE
after upgrade dotnetcore 2.0 to 3.1 facing the issue libhostpolicy.so: invalid ELF header

### ISSUE THREAD

**Issue by magiccreater** [dotnet/dotnet-docker#2768]
`cross-env ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=http://+:80 dotnet watch run --no-restore`
A JSON parsing exception occurred in [`/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.14/Microsoft.NETCore.App.deps.json`]: * Line 1, Column 2 Syntax error: Malformed token
Failed to load (5�, error: `/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.14/libhostpolicy.so`: invalid ELF header
An error occurred while loading required library libhostpolicy.so from [`/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.14`]

I am using this in docker file 
`FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env`

My local system is MacOs and this same configuration working in Linux system. 
Any Help is appreciate.

**Comment by mthalman** [comment]
Can the provide the Dockerfile and perhaps a sample project that demonstrates this behavior?

**Comment by magiccreater** [comment]
For me issue is with upgrade of docker, now I downgrade docker to 19 and its working again, so for who facing same kind of issue check the version of docker 20 has issue with this dotnet core sdk. thank you.

**Comment by mthalman** [comment]
Thanks for the additional information regarding the Docker version.  It would still be helpful if you could provide a project and Dockerfile that can be used to reproduce this behavior.

**Comment by MichaelSimons** [comment]
[Triage] @magiccreater, can you please provide a project that reproduces this behavior so that we can investigate?

**Comment by MichaelSimons** [comment]
[Triage] This appears to be related to the Docker version installed.  Closing as there were no repro steps provided to investigate further.
