### ISSUE TITLE
Define policy for when images get rebuilt to address package security vulnerabilities.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2787]
If there is a vulnerability in a package included in a .NET layer and there is a package patch available that addresses the CVE, when will the image get rebuilt to pick it up?  This should be captured in the [Image Update Policy](https://github.com/dotnet/dotnet-docker#image-update-policy).  The image update policy only discusses base image and .NET servicing.

* We update the supported .NET images within 12 hours of any updates to their base images (e.g. debian:buster-slim, windows/nanoserver:1909, buildpack-deps:bionic-scm, etc.).
* We publish .NET images as part of releasing new versions of .NET including major/minor and servicing.

**Comment by mthalman** [comment]
The content in https://github.com/dotnet/dotnet-docker/pull/4842 should be included with this.

**Comment by lbussell** [comment]
[Triage] We have something like this in [Vulnerability Workflow](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md), but we should have it written down more concretely when precisely we will re-build, and the Vulnerability Workflow should reference it.

**Comment by MichaelSimons** [comment]
This is a prereq to fixing #1455.
