### ISSUE TITLE
Cannot run dotnet 2.0.0 project with runtime docker image.

### ISSUE THREAD

**Issue by Merurino** [dotnet/dotnet-docker#279]
## Steps to reproduce the issue
1. Create a new Project using `dotnet new webapi`
2. Go to this project folder (i.e. `dotnetapp` and add a `DockerFile` in it with the same instructions contained in https://hub.docker.com/r/microsoft/dotnet/ 
Content of the file: 
```
FROM microsoft/dotnet:runtime
WORKDIR /dotnetapp
COPY out .
ENTRYPOINT ["dotnet", "dotnetapp.dll"]
```
3. As also pointed in the docker hub help, try to run the container:
```
dotnet restore
dotnet publish -c Release -o out
docker build -t dotnetapp .
docker run -it --rm dotnetapp
```

## Expected behavior
The application runs as it runs when we use the non-runtime image (sdk) 

## Actual behavior
I get the following error:
```
Error:
  An assembly specified in the application dependencies manifest (dotnetapp.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml
```

## Additional information (e.g. issue happens only occasionally)
Output of `dotnet version` = `2.0.0`

## Output of `docker version`
```
Docker version 1.12.1, build 23cf638
```

## Output of `docker info`

```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 50
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 30
 System Time: 2017-08-16T04:41:41.482914397Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by natemcmaster** [comment]
It looks like you're trying to run an ASP.NET Core web app. Although this may have worked with ASP.NET Core 1.0 and 1.1, starting in 2.0 you need to either

(1) use `microsoft/aspnetcore` instead. This image bundles the ASP.NET Core Runtime Store

```Dockerfile
FROM microsoft/aspnetcore:2.0.0
WORKDIR /dotnetapp
COPY out .
ENTRYPOINT ["dotnet", "dotnetapp.dll"]
```

or (2) disable the publish-time trimming so that your dependencies assemblies are copied into your published output.
```xml
<PropertyGroup>
   <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>
```

cc @glennc

**Comment by Merurino** [comment]
Thanks a lot @natemcmaster , indeed now with .net core 2.0 I need to use the aspnetcore image. My project in version 1 was running on the SDK image that's why it was working even without the aspnetcore specific image. 

Cheers

**Comment by ebh** [comment]
@Merurino, that is the single best issue report I have seen on GitHub. You should get an award for how good it is.
