### ISSUE TITLE
Docker image sets NUGET_XMLDOC_MODE=skip, disrupting nuget restore

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/dotnet-docker#2790]
### Describe the Bug

The docker image https://hub.docker.com/_/microsoft-dotnet-sdk sets environment variable NUGET_XMLDOC_MODE=skip. This negatively impacts nuget restore, causing certain package files to fail to restore properly. 

While this setting may be useful in your build process during creation of the nuget package, it negatively impacts users of the docker image that may not be aware of this non-default setting. Our build infrastructure used this nuget image as an image for our build agents, and it's causing our builds to fail due to missing files in the nuget restore.

While I do know how to override this setting, I consider this a temporary work around. Nuget images shouldn't leak their build settings into the image produced, and should instead clean up the environment for the user's uses when finalizing the docker image. The only environment variables set in the final image should be (a) those built into the OS it's using (e.g. having a username set, program files, etc.) and (b) those necessary for the container's intended function (e.g. WindowsSdkDir, and other things a Developer Command Prompt for VS 2019 might set).

### Steps to Reproduce

in the linked docker container, run `echo NUGET_XMLDOC_MODE='%NUGET_XMLDOC_MODE%'`

[expected]: NUGET_XMLDOC_MODE=''
[actual]: NUGET_XMLDOC_MODE='skip'

https://github.com/dotnet/dotnet-docker/blob/5d9e2099db7d73b97a9008ec948dcade7b34904b/src/sdk/5.0/windowsservercore-ltsc2019/amd64/Dockerfile#L13

**Comment by aaronla-ms** [comment]
This setting doesn't disable just xml docs. My team owns a nuget which (for compatibility reasons) includes xml files that are provided side by side in the lib/net462 folder. Our build team claims to be using these docker images for their builds, and the net results is that nuget restore fails to restore our entire package.

The net result is the build fails to restore packages as it would on a typical developer machine (out of box configuration of visual studio doesn't set NUGET_XMLDOC_MODE=skip, for instance).

**Comment by MichaelSimons** [comment]
@AArnott, Can you please open a [NuGet issue](https://github.com/NuGet) to track the issue with the `NUGET_XMLDOC_MODE` setting - e.g. it applies to more than just xmldoc?

**Comment by aaronla-ms** [comment]
@MichaelSimons I'm following up with my dev on the nuget package where this was used. On closer inspection, it looks like this xml file is actually a doc file and it was shipped with our service only accidentally. That said, I still can't find any metadata to suggest this -- it just seems to be a file naming convention in nuget. Would appreciate getting to the bottom of this setting.

To summarize, 
(a) we probably shouldn't be relying on this file, but 
(b) it _is_ a regression that our builds stopped working when we adopted container images with this non-default setting configured.

**Comment by AArnott** [comment]
@MichaelSimons I wonder why you're asking me to do this. I'm not working with docker and I'm not on the nuget team either. I _could_ do this, but if you do it, you'll get the notifications and I won't, which sounds appropriate since this has nothing to do with me.

FWIW though, have you folks thought about the "dev container" scenario? VS Code promotes using a `.devcontainer/Dockerfile` in repos so that anyone who opens the repo can be immediately productive in development, with all dependencies satisfied from the container. These containers are often based on a dotnet sdk docker image (for example [this one](https://github.com/AArnott/Library.Template/blob/main/.devcontainer/Dockerfile)). Since these are used for development, dropping .xml doc files will do substantial harm to the Intellisense experience for these developers.

**Comment by MichaelSimons** [comment]
I apologize @AArnott, I mistakenly referenced your username versus the original author aaronla.  You raise a good point however, we will take a look at this scenario.

**Comment by MichaelSimons** [comment]
[Triage] We should validate the e2e UX the xml doc setting has on the dev container scenario.  We should also measure the gains the xml doc setting has on a range of restore scenarios.  This setting was originally added early on in .NET to provide a smaller sdk image as a result of the SDK carrying around the NuGet package cache.  To summarize, we are saying the reasons the xml doc setting were added in the first place no longer exists so we should investigate it's usefulness.  

@mthalman, please investigate.

**Comment by mthalman** [comment]
Not setting `NUGET_XMLDOC_MODE=skip` definitely has an impact on both restore time and disk space.

For my testing, I used the project for the C# TechEmpower benchmark: https://github.com/TechEmpower/FrameworkBenchmarks/blob/6769bf6dd9fde18c30e63f700689fc7e9b4232bd/frameworks/CSharp/aspnetcore/Benchmarks/Benchmarks.csproj. This project has 5 top-level package references.  This expands out to a total of 116 nested packages that actually get restored. For my testing, I retargeted the Dockerfile to use the .NET 6 SDK.

Average restore time: 
* With `NUGET_XMLDOC_MODE=skip`: 14.5 seconds (0.125 seconds per package)
* Without `NUGET_XMLDOC_MODE=skip`: 20.7 seconds (0.178 seconds per package)

This is a 42% increase in restore time when `NUGET_XMLDOC_MODE=skip` isn't set.

For disk space:
* With `NUGET_XMLDOC_MODE=skip`: 306 MB (2.64 MB per package)
* Without `NUGET_XMLDOC_MODE=skip`: 679 MB (5.85 MB per package)

This is a 121% increase in disk space when `NUGET_XMLDOC_MODE=skip` isn't set. This disk usage is only relevant to the image layer that has restored the packages (typically the build stage of a Dockerfile). That layer wouldn't typically be included in the final application image.

**Comment by MichaelSimons** [comment]
[Triage] There is clearly value in maintaining the `NUGET_XMLDOC_MODE=skip`.  We feel this is beneficial to the 80+ percentage use cases.  In the cases where this isn't desired, the recommendation is to override this setting.  Another options for use cases like this is to retrieve the xml doc file explicitly from the nupkg.

**Comment by AArnott** [comment]
> Another options for use cases like this is to retrieve the xml doc file explicitly from the nupkg.

The use case is .NET development within a container. I don't know how the compiler would be told to take this option.

> In the cases where this isn't desired, the recommendation is to override this setting.

For others' reference, the way to override this setting is to add this to the Dockerfile:

```Dockerfile
ENV NUGET_XMLDOC_MODE=
```

**Comment by mthalman** [comment]
> The use case is .NET development within a container. I don't know how the compiler would be told to take this option.

Right, so there's a tension here between the two scenarios: build automation and developer environment.  Which do we optimize for?  To date, we've mostly been focused on satisfying the former.  Perhaps there's an opportunity to provide a container curated for dev environment scenarios. This warrants further discussion.

**Comment by aaronla-ms** [comment]
> Perhaps there's an opportunity to provide a container curated for dev environment scenarios. This warrants further discussion.

Possibly, but the differences should be incredibly minor -- otherwise you risk "it works on my machine but not in the lab"-itis.
