### ISSUE TITLE
string.Normalize not working in alpine image

### ISSUE THREAD

**Issue by svrooij** [dotnet/dotnet-docker#2798]
### Describe the Bug

After hours of debugging and researching the web, I finally figured our that `"söme-string".Normalize(NormalizationForm.FormD);` simply doesn't work in my dotnet core worker, running in the alpine container (**FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine**)

### Steps to Reproduce

1. Create a simple console application with `"söme-string".Normalize(NormalizationForm.FormD);` inside.
2. Docker build it into the `mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine` image.
3.  🎉 not working

### Other Information

I finally figured out that the alpine image is lacking support for any globalization features, and only just realized that this also matters for `string.Normalize(...);`

Deeply hidden in the Dockerfiles I found the following code.

https://github.com/dotnet/dotnet-docker/blob/af55df2c8cdef6805beefe8c4213c1f42dcba8d7/src/runtime-deps/3.1/alpine3.13/amd64/Dockerfile#L19L20

Apparently there is a decision made to not include `icu` and to opt-out of [Globalization settings](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization). I figured this out by finding [this closed issue](https://github.com/dotnet/runtime/issues/12452).

I fixed my application being able to use `string.Normalize(...);` with the following addition to my **Dockerfile**, but I really think this could be documented better.

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS prod
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN apk add --no-cache icu
```

The current dockerfiles opt-out of something without the user knowing about it. It can maybe also be caught at buildtime, something like: "You're building your app for a platform without globalization, but this code references some globalization feature. 

I would also settle for an exception like "NotSupported => You cannot use globalization features because you've opted-out."

As stated in the [globalization feature description](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md) this feature is meant to be **opt-in**:
> The drawback of running in the invariant mode is applications will get poor globalization support. This new option is only recommended for developers that understand globalization and the impact of its absence.

### Output of `docker version`

Irrelevant....

```plain
Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
```

### Output of `docker info`

Irrelevant...

**Comment by MichaelSimons** [comment]
@svrooij, I'm sorry the default globalization setting caused you trouble.  Do you have a suggestion on where and how to document this setting so that you would have discovered it sooner?

**Comment by svrooij** [comment]
I'm not sure where this should be placed. There was an overview off different tags at Dockerhub someday.

Maybe at least at selecting tag [page](https://github.com/dotnet/dotnet-docker/blob/main/samples/selecting-tags.md)

And maybe in the mentioned globalization feature description page, as it states the Linux images "include" the ICU library, which is not the case.

My guess is that this is similar to the same issue with timezone data being removed from the alpine image when dotnet 3.0 was released.

**Comment by MichaelSimons** [comment]
[Triage] Thanks for the feedback @svrooij.  We think the following changes would help in discovering this setting.

1. Making mention of this in https://github.com/dotnet/dotnet-docker/blob/main/samples/selecting-tags.md#targeting-a-specific-operating-system makes sense.  This section could benefit from more verbiage describing the differences and why you may choose one distro versus the other.
2. The [globalization feature description](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md) page should also get updated as it is misleading in the Alpine case.
3. Add a note to the runtime, aspnet, and sdk Dockerfiles calling out the globalization invariant mode setting inherited from the runtime-deps image.

**Comment by svrooij** [comment]
@MichaelSimons that are some great points, hadn't thought about the last one.

Maybe also create a Rosalyn warning that catches any call to a globalization feature at build time when the opt-out environment variable is set?

**Comment by svrooij** [comment]
@MichaelSimons And maybe also include a note about missing timezone data? Since the alpine image is missing the `tzdata` package since the migration to dotnet 3 (or was it 2.2 not sure) as well

> Add a note to the runtime, aspnet, and sdk Dockerfiles calling out the globalization invariant mode setting inherited from the runtime-deps image.
