### ISSUE TITLE
dotnet nuget add stopped working on 5.0.300 

### ISSUE THREAD

**Issue by kauemendes** [dotnet/dotnet-docker#2861]
Hi Guys, 

I have the following Dockerfile with multi-stage build and run and we use it for most of our projects.

```
ARG SDKVERSION=5.0
ARG REGISTRY_NAME=smthg.azurecr.io
ARG IMAGE_NAME=baseimage
ARG RTVERSION=5.0
ARG DLLRUN=HOST.dll
ARG GIT_PAT=gitpatencoded
ARG CSPROJTOBUILD=generated/Host/Host.csproj

FROM mcr.microsoft.com/dotnet/sdk:$SDKVERSION as build
LABEL stage=build
ARG DLLRUN
ARG GIT_PAT
ARG CSPROJTOBUILD

ENV GIT_PAT ${GIT_PAT}
ENV CSPROJTOBUILD ${CSPROJTOBUILD}
ENV DLLRUN ${DLLRUN}
WORKDIR /build
COPY . .
RUN dotnet nuget add source "https://pkgs.dev.azure.com/org/_packaging/PrivateFeed/nuget/v3/index.json" -n "AzureDevops" --username vsts --password $GIT_PAT --store-password-in-clear-text
RUN dotnet publish $CSPROJTOBUILD --configuration Release --verbosity "normal" --output ./build 

FROM $REGISTRY_NAME/$IMAGE_NAME:$RTVERSION as runtime
ARG DLLRUN
ENV DLLRUN ${DLLRUN}
WORKDIR /app
COPY --from=build /build/build /app
ENTRYPOINT dotnet $DLLRUN
```

We were using `dotnet nuget add source` for authenticating into Azure DevOps Feed using Personal Access Token (PAT). But since this release (https://github.com/dotnet/dotnet-docker/issues/2830), we are facing this error:

```
#11 sha256:782cdf02e5f2eb6eed9707ddf8d59f05aa837566215d9364302e65bee8a4b07d
#11 5.736 Could not execute because the application was not found or a compatible .NET SDK is not installed.
#11 5.736 Possible reasons for this include:
#11 5.736   * You intended to execute a .NET program:
#11 5.736       The application 'nuget' does not exist.
#11 5.736   * You intended to execute a .NET SDK command:
#11 5.736       A compatible installed .NET SDK for global.json version [5.0.201] from [/build/global.json] was not found.
#11 5.736       Install the [5.0.201] .NET SDK or update [/build/global.json] with an installed .NET SDK:
#11 5.740         5.0.300 [/usr/share/dotnet/sdk]
```

We had to go back and use 5.0.203, which works like a charm. But we would like to keep things up to date.

What are the specialist suggestion or alternatives for handle `dotnet nuget add source`, properly? I would not like to copy nuget.config, most of our developers do not even have nuget.config on their repositories. 

Thanks in advance! 

### Output of `docker version`
 docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  

### Output of `docker info`
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.103GiB
 Name: docker-desktop
 ID: LAX7:TC7R:TUPA:IKL7:F5ZM:BDYZ:REJH:QCFO:I74D:HNWE:3GB3:2YJT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 45
  System Time: 2021-06-04T09:33:32.6623964Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by mthalman** [comment]
This looks to be the relevant info from the error message:

```
#11 5.736       A compatible installed .NET SDK for global.json version [5.0.201] from [/build/global.json] was not found.
#11 5.736       Install the [5.0.201] .NET SDK or update [/build/global.json] with an installed .NET SDK:
#11 5.740         5.0.300 [/usr/share/dotnet/sdk]
```

What does the `sdk` section of your `global.json` file look like?  It appears to be configured to require the 5.0.201 SDK.

**Comment by kauemendes** [comment]
sorry, bout that! Never mind this issue, please! I was at a dead end.
