### ISSUE TITLE
Official `Dockerfile.debian-arm32` does not work due to multiple dependency problems (libunwind && "failed to create CoreCLR, HRESULT: 0x80004005")

### ISSUE THREAD

**Issue by zaneclaes** [dotnet/dotnet-docker#2863]
### Describe the Bug

I built my project with [the official Arm32v7 Dockerfile](https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile.debian-arm32) on a Raspberry Pi 4.  The build succeeded, but it failed to run due to the missing the `libunwind` dependency as [described in this bug](https://github.com/dotnet/sdk/issues/6325). After adding `RUN apt-get -y update && apt-get install -y libunwind8` to the Dockerfile, I instead encountered this error: 

```
Failed to create CoreCLR, HRESULT: 0x80004005
```

Which led me to [this issue](https://github.com/dotnet/runtime/issues/44417#issuecomment-855288407), but @janvorli informed me that this was an unrelated issue. 

I was able to finally run my project by removing the `--self-contained false` from the Dockerfile's `dotnet publish`. 

### Steps to Reproduce

I am still attempting to discover what, in particular, causes this issue. It does NOT happen when building directly from this repository, but it does happen when using the Dockerfile to build my ASP.NET React SPA. I would need to try to bisect what the difference may be between these two, which I have not yet had time to do.

**Note** that the same exact project works just fine on `amd64` (even when using the `aspnet:5.0-buster-slim` runtime), so the problem is specific to `arm`. I'm not 100% clear why the `--self-contained false` flag is applied only to some Dockerfiles (while it is [absent in the main Dockerfile](https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile)). My assumption from the documentation on this repository was that this flag was added for "a good reason" (*waves hands*). The fact that the flag is present on some architectures and not others suggested to me that it was necessary for the ARM architecture, but that appears to be incorrect.

### Output of `docker version`

`Docker version 20.10.1, build 831ebea`

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 65
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.79-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 1.823GiB
 Name: hvac
 ID: EYU4:QRTY:JEP2:BJNR:M77L:G6NF:2567:RSEW:FQ7X:2KGU:HZPG:CEKI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: inzania
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Comment by janvorli** [comment]
@zaneclaes what was the behavior before you've installed the libunwind? There should be no dependency on libunwindin the runtime since at least .NET Core 3.1 where we have integrated libunwind source into our runtime and got rid of that dependency.

**Comment by janvorli** [comment]
I've tried the same official sample docker file on my Odroid N2 and it worked without any modifications. The container has built and it also could execute correctly (printing "Hello world!"). So I wonder what was the difference that caused it to not to work in your case (my OS on the Odroid is Ubuntu 18.04, but that should not play any role).

**Comment by zaneclaes** [comment]
> what was the behavior before you've installed the libunwind?

More or less as described in the linked issue, i.e., `Failed to load /app/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory`. You can pull a container with this issue from `makerverse/core:arm32v7-53` (on docker.io).

> I've tried the same official sample docker file on my Odroid N2 and it worked without any modifications. The container has built and it also could execute correctly (printing "Hello world!"). 

Just to reiterate from the OP, in case you missed it:

>  It does NOT happen when building directly from this repository, but it does happen when using the Dockerfile to build my ASP.NET React SPA.  I would need to try to bisect what the difference may be between these two, which I have not yet had time to do.

I would like to try to figure out what causes it, but I don't know what this HRESULT code is implying, and therefore don't quite know where to begin bisecting (except to start randomly removing dependencies). However, perhaps a good spot to start would be by with the React SPA template. Part of the challenge is that I'm on DSL, so every Docker container build takes about 90 minutes to build 😭

**Comment by janvorli** [comment]
Ah, I am sorry for missing it. The error HRESULT is unfortunately a "general error" and it is coming from the later stages of the runtime where fine grained error kind detection is missing at some places. So we cannot guess anything from that code. There is a plan to start tackle diagnosability of these stages after the .NET 6 is code complete, but that doesn't help you now.
Let me try to pull down the image you've mentioned to see if I can figure out something from that.
The weird thing though is that we should not depend on libunwind in recent .NET Core, in fact I can see it should not be referencing it in 2.1 and higher, so it almost looks as if it was targeting runtime < 2.1 by accident.
I've tried the container you've pointed me too and it confirms that - the /app/libcoreclr.so comes from .NET Core 2.0, so it seems that your project files or something request that version by accident.

**Comment by janvorli** [comment]
```
strings /app/libcoreclr.so | grep "@(#)"
@(#)Version 4.6.26328.01 @BuiltBy: root-1faec335d2d8 @Commit: b8c69ed222a1e6e5392783cbb4df5faa87be349e
```
Here is the commit:
https://github.com/dotnet/coreclr/commit/b8c69ed222a1e6e5392783cbb4df5faa87be349e
See the release/2.0.0 tag in it.

**Comment by zaneclaes** [comment]
Thanks very much for digging into this with me. Do you have any advice how I can figure out what is pulling in .NET Core 2.x? I found[ an approach for printing the dependency tree](https://stackoverflow.com/questions/44944172/net-core-dependency-tree), but it doesn't show me what would be bringing in the old runtime.

**Comment by zaneclaes** [comment]
I'm also trying to figure out why these problems would be specific to ARM architecture. Shouldn't the dependencies be the same?

**Comment by janvorli** [comment]
I would start by scanning all the .csproj files in your project to see if there is a reference to 2.0 anywhere. But since it happening for ARM only, it might be that you are referencing a package that exists only for 2.0 for ARM for some reason while it exists for newer versions for e.g. x64. But this is a pure speculation, as a low level runtime guy I don't have sufficient knowledge of this kind of stuff to give you a reasonable advice. 
But maybe one thing. Would it be possible to share the list produced by the `PrintAllReferences` you've found and mentioned above? My guess is that something indicative of the problem should be there. It would be great to get the output of the same thing for x64 so that we can compare the differences.

**Comment by zaneclaes** [comment]
> But since it happening for ARM only, it might be that you are referencing a package that exists only for 2.0 for ARM for some reason while it exists for newer versions for e.g. x64. But this is a pure speculation, as a low level runtime guy I don't have sufficient knowledge of this kind of stuff to give you a reasonable advice.

That was my best guess too; glad it comports.

Taking the brute force approach and scrolling thru the NuGet packages, I do see some which list only `.NETStandard 2.1` amongst the **Frameworks & Dependencies**. However, one such package is `Microsoft.EntityFrameworkCore`. Not being super familiar with versioning here, I had simply assumed that such a package must support the latest dotnet5 architecture. Am I right to suspect it, or off-base?

[Here is the output](https://gist.github.com/zaneclaes/dcdb5c5dbc16566f9b1af59cab2a957c). However, I did discover I have a few unnecessary (or questionably necessary) dependencies. For example, I had thought `Microsoft.DotNet.Watcher.Tools` was needed to use `dotnet watch run`, but that is a development (not production) dependency...

**Comment by zaneclaes** [comment]
>  It would be great to get the output of the same thing for x64 so that we can compare the differences.

Whoops, the link in the last message was done on my MacBook Pro, so it'll be x64. It'll take me a few min to get the ARM.

**Comment by janvorli** [comment]
There is a plenty of 2.0 .NET runtime packages referenced, e.g. the actual runtime:
```
Referenced package: Microsoft.NETCore.App/2.0.7
```

**Comment by zaneclaes** [comment]
> There is a plenty of 2.0 .NET runtime packages referenced, e.g. the actual runtime:
> 
> ```
> Referenced package: Microsoft.NETCore.App/2.0.7
> ```

Indeed; that is listed as `Implicitly Installed` in the IDE (rather than listed in the .csproj).

**Comment by zaneclaes** [comment]
Just to make sure I understand — is this "bad?" 

Which is to say — ".NET Standard 2.x (and old .NET Core) dependencies will result in importing the 2.x runtime?"

<img width="796" alt="Screen Shot 2021-06-07 at 9 29 05 AM" src="https://user-images.githubusercontent.com/2084821/121046397-3805c200-c773-11eb-9939-5856498f49e7.png">

<img width="811" alt="Screen Shot 2021-06-07 at 9 32 38 AM" src="https://user-images.githubusercontent.com/2084821/121046851-54096380-c773-11eb-9b57-4502d5b80ea3.png">

**Comment by janvorli** [comment]
What is the TargetFramework setting in your .csproj files? That should determine the framework used for self contained apps (self contained apps contain the framework binaries as part of the app).

**Comment by zaneclaes** [comment]
Here's the actual [.csproj](https://github.com/makermadecnc/makerverse/blob/zkc-modernize/Makerverse.csproj#L3) in the github branch I'm working on (open-source project). tl;dr, it's dotnet5. Note that I have pared down the dependencies significantly at this point, to see if I can get a working build without them (and without libunwind).

**Comment by janvorli** [comment]
Btw, you were interested in what was the reason for passing `--self-contained false`. The answer is - the final image size is smaller that way. The base docker already contains .NET runtime and without that flag, the app would contain a copy of the whole runtime again in the application directory.

**Comment by zaneclaes** [comment]
Thanks for that — this has been very enlightening. I have been able to remove the libunwind dependency and build with `--self-contained false`. I thought you might find this screenshot from my Grafana dashboard interesting, showing the containers' memory & CPU usage and my progress in optimizing it thusfar. 

<img width="2075" alt="Screen Shot 2021-06-07 at 12 58 03 PM" src="https://user-images.githubusercontent.com/2084821/121073675-0c450500-c790-11eb-9e30-8a53f3129fbe.png">

**Comment by janvorli** [comment]
I am glad to hear that you were able to fix the problem. I was happy to help.
