### ISSUE TITLE
Unable to run published files into container with latest .net 6 preview

### ISSUE THREAD

**Issue by musictopia2** [dotnet/dotnet-docker#2927]
[Dockerfile.txt](https://github.com/dotnet/dotnet-docker/files/6729636/Dockerfile.txt)

When I try the commands to copy the published files to docker and run, it always fails.  Gives some type of access file violation.
Tried the same thing under .net 5 and no problems.
An earlier preview of .net 6 did not have the problem at all.
Would be disappointed if a person was not allowed to publish files and copying those files to docker.  There are cases where I need libraries not in the folders and not on nuget and don't want to be forced to publish all my libraries to nuget even though it may access files from my personal computer.

**Comment by mthalman** [comment]
Please provide the following:

* The output of `docker version`.
* The output of `docker info`.
* The output of your `docker build` command producing the error.
* The actual error message.
* Ideally, an example project that demonstrates the behavior.

**Comment by musictopia2** [comment]
What finally happened was I tried the nightly builds then the problem went away.  I hope this means that preview 6 will fix the problem.

**Comment by MichaelSimons** [comment]
[Triage] Closing since the issue was resolved with the latest 6.0 builds.  If this re-occurs, please provide the information @mthalman requested.
