### ISSUE TITLE
Save Data protection keys even after container is destroyed

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/dotnet-docker#295]
## Steps to reproduce the issue
1. Run an aps.net core app using the command 
_docker run -p 5000:80 --name containerda containerda-img_
2.
3.

## Expected behavior
Should run with out any warning. 

## Actual behavior
I get an warning saying 

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container
. Protected data will be unavailable when container is destroyed.

## Output of `docker version`
Docker version 17.06.2-ce, build cec0b72
```
I need a method to persist these keys even when the container is destroyed

**Comment by natemcmaster** [comment]
Seems like a good candidate for aspnetcore documentation. https://github.com/aspnet/docs There are some docs already, but none for docker-specific scenarios.

Basically, you'll need to store the keys in a folder that is docker volume (i.e. shared volme or a host mounted volume), or you'll need to store them in an external provider, like Azure Key Vault or Redis.

cref https://github.com/aspnet/DataProtection/issues/185

**Comment by VenkateshSrini** [comment]
@natemcmaster,
I have tried to mount a volume like this 
docker run -v d:/venkatesh/aspnetcore/2.0/containerdasample/publish/containerapp/keys:/root/.aspnet/dataprotection-keys -p 5000:80 --name containerda containerda-img
In this I would expect the key to be stored in mounted volume but even after that I keep getting this error. I do not want to loose the encryption key. Can you please share me some link that has sample solution to this problem

**Comment by MichaelSimons** [comment]
I moved this issue to https://github.com/aspnet/aspnet-docker/issues/303 since this is specific to ASP.NET Core.
