### ISSUE TITLE
I couldn't figure out the best area label to add to this PR. If you have write-permissions please help me learn by adding exactly one area label.

### ISSUE THREAD

**Issue by BillyGeoThink2020** [dotnet/dotnet-docker#2959]
I couldn't figure out the best area label to add to this PR. If you have write-permissions please help me learn by adding exactly one area label.

_Originally posted by @dotnet-issue-labeler[bot] in https://github.com/dotnet/dotnet-docker/issues/2958#issuecomment-877483221_

**Comment by mthalman** [comment]
Looks like this issue was mistakenly created. If you need help logging an issue, go ahead and respond here.
