### ISSUE TITLE
Can't pull the image of microsoft/aspnetcore-build:2.0.5-2.1.4

### ISSUE THREAD

**Issue by dngtathanh** [dotnet/dotnet-docker#2960]
### Describe the Bug

We have some services which are using the image `microsoft/aspnetcore-build:2.0.5-2.1.4` to build but they all don't work anymore. The problem occurs today, they still woked well few days ago.

Is it cleaned from the Docker Hub? Do you have a doc/article/blog says about it?

And do you have any ideas to fix it? (Upgrade to 2.1 or 3.1 also a solution)

### Steps to Reproduce
Run command
```
docker pull microsoft/aspnetcore-build:2.0.5-2.1.4
```

Its response
```
Error response from daemon: pull access denied for microsoft/aspnetcore-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Output of `docker version`

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by mthalman** [comment]
Yes, the announcement of this deletion is in https://github.com/dotnet/dotnet-docker/issues/2848.

The recommendation would be to upgrade to at least 3.1 since 2.1 will be EOL next month.  Even better would be to upgrade to 5.0.  Please see https://hub.docker.com/_/microsoft-dotnet for the set of .NET Core Docker repositories and their supported tags.

**Comment by dngtathanh** [comment]
Hmm, it's clear now. It would be a lot of work to do. Thanks a lot @mthalman
