### ISSUE TITLE
Create Nano Server images for the 1709 release

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#298]
Nano Server based images should be created and available when [Windows Server 1709](https://blogs.technet.microsoft.com/windowsserver/2017/09/25/faster-releases-for-a-faster-world-first-semi-annual-release-of-windows-server/) releases.  The existing Nano Server images must be maintained as 1709 images are not backwards compatible.

**Comment by natemcmaster** [comment]
>  The existing Nano Server images must be maintained 

What exactly will this look like? Two or more Nano Server images? If so, how will they be tagged?
