### ISSUE TITLE
Missing `powershell`/`pwsh` in `dotnet/aspnet:5.0` and `dotnet/runtime:5.0` images

### ISSUE THREAD

**Issue by Saibamen** [dotnet/dotnet-docker#2984]
### Describe the Bug

There is no `powershell` or `pwsh` in `mcr.microsoft.com/dotnet/aspnet:5.0` and `mcr.microsoft.com/dotnet/runtime:5.0` images (Windows containers).

Previously I wanted to use `mcr.microsoft.com/dotnet/sdk:5.0` as `runtime` - it works in my Docker inside my local machine, but I had error in Azure `Unable to start container. Error message: Index was outside the bounds of the array` - more info here: https://docs.microsoft.com/en-us/answers/questions/463587/windows-containers-unable-to-start-container-error.html

### Steps to Reproduce

Dockerfile:
```dockerfile
#FROM mcr.microsoft.com/dotnet/aspnet:5.0 as runtime
FROM mcr.microsoft.com/dotnet/runtime:5.0 as runtime

# powershell not exist on aspnet and runtime
RUN powershell Write-Host "test from powershell - runtime"
# pwsh not exist on aspnet and runtime
RUN pwsh Write-Host "test from pwsh - runtime"
```

### Other Information

---

### Output of `docker version`

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:41 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 50
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19042.1110)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.83GiB
 Name: WINDOWS-L20SI7S
 ID: PWNZ:5WEB:EEOZ:WCVK:YW57:BDGI:LY3L:HKNL:P4C4:JKGE:XIIY:YISQ
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 31
  System Time: 2021-07-21T16:16:46.2806097+02:00
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
PowerShell is only provided in the SDK image.  Adding PowerShell adds overhead to the image which isn't directly applicable to running .NET applications. There hasn't been sufficient demand for having it either. We have no plans on adding PowerShell in runtime-related images.

What is your particular need for PowerShell?  You can make use of a multi-stage Dockerfile to install pwsh in an sdk stage and add it to your Dockerfile if necessary.   Another thing to consider would be to file an issue on the https://github.com/dotnet/sdk repo for allowing global tools to be installed outside of the context of the SDK, just directly using the dotnet CLI.

**Comment by Saibamen** [comment]
>What is your particular need for PowerShell?
I have a PS script in Entrypoint to change properties in `App.config` or `appsettings.json` based on environment variables

I fixed it. Here is my Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build

### Download and unzip PowerShell

# Define Args for the needed to add the package
# Install Stable version (https://aka.ms/powershell-release?tag=stable)
ARG PS_VERSION=7.1.3
ARG PS_PACKAGE=PowerShell-${PS_VERSION}-win-x64.zip
ARG PS_PACKAGE_URL=https://github.com/PowerShell/PowerShell/releases/download/v${PS_VERSION}/${PS_PACKAGE}

SHELL ["cmd", "/S", "/C"] # Fix for Azure DevOps build...
WORKDIR /powershell

RUN curl -L %PS_PACKAGE_URL% -o %PS_PACKAGE%
RUN tar -xf %PS_PACKAGE%
RUN del %PS_PACKAGE%

### Do build stuff

FROM mcr.microsoft.com/dotnet/runtime:5.0 as runtime

WORKDIR /powershell
COPY --from=build /powershell/. .

WORKDIR /app
### COPY your app files

ENTRYPOINT ["C:\\powershell\\pwsh", "c:\\app\\Docker-Startup.ps1"]
```

**Comment by Saibamen** [comment]
@mthalman 
`mcr.microsoft.com/dotnet/framework/aspnet:4.8` is used in my other Docker image as runtime (WebAPI project) and this image contains `powershell` command so that is why I created this bug report

But please don't delete `powershell` from this tag :D

**Comment by MichaelSimons** [comment]
The reason the `mcr.microsoft.com/dotnet/framework/aspnet:4.8` image has PowerShell is because it's based on Windows Server Core which includes PowerShell.  If image size if not a concern of yours, you could utilize the .NET Core images based on Windows Server Core as a way to get PowerShell - `mcr.microsoft.com/dotnet/aspnet:5.0-windowsservercore-ltsc2019`.  .NET images are only available for the LTSC versions of Windows Server Core however.
