### ISSUE TITLE
Unable to start debugging Docker containers

### ISSUE THREAD

**Issue by lczc1988** [dotnet/dotnet-docker#300]
## Steps to reproduce the issue
1.Log in to machine with azure AD account.
2.Start docker for windows
3.Create a asp.net core web api and click Docker to debug. Report error as below.

Starting: "docker" exec -i b7ca27fbf035 /clrdbg/vsdbg/vsdbg --interpreter=mi
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"/clrdbg/vsdbg/vsdbg\": stat /clrdbg/vsdbg/vsdbg: input/output error"
"docker" exited with code 126 (0x7E).
 
docker-compose -f "C:\Projects\testdocker2\TestDocker2\docker-compose.yml" -f "C:\Projects\testdocker2\TestDocker2\docker-compose.override.yml" -f "C:\Projects\testdocker2\TestDocker2\docker-compose.vs.debug.yml" -p dockercompose357593242 config
services:
  testdocker2:
    build:
      args:
        source: obj/Docker/empty/
      context: C:\Projects\testdocker2\TestDocker2\TestDocker2
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
    image: testdocker2:dev
    labels:
      com.microsoft.visualstudio.targetoperatingsystem: linux
    ports:
    - 80/tcp
    volumes:
    - C:\Projects\testdocker2\TestDocker2\TestDocker2:/app:rw
    - C:\Users\EdX\clrdbg:/clrdbg:ro
    - C:\Users\EdX\.nuget\packages:/root/.nuget/packages:ro
version: '2.0'
docker  ps --filter "status=running" --filter "name=dockercompose357593242_testdocker2_" --format {{.ID}} -n 1
b7ca27fbf035

## Expected behavior

Start debugging and can visit the site.

## Actual behavior

Report error.

## Output of `docker version`
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:48:20 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
(paste your output here)
```

## Output of `docker info`

```Starting: "docker" exec -i b7ca27fbf035 /clrdbg/vsdbg/vsdbg --interpreter=mi
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:262: starting container process caused "exec: \"/clrdbg/vsdbg/vsdbg\": stat /clrdbg/vsdbg/vsdbg: input/output error"
"docker" exited with code 126 (0x7E).
(paste your output here)
```

**Comment by MichaelSimons** [comment]
Since this is related to VS Docker Tools, I moved it to https://github.com/Microsoft/DockerTools/issues/45.
