### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by patoncrispy** [dotnet/dotnet-docker#302]
## Steps to reproduce the issue
1. Try to install azure-cli using apt-get and then login to Azure.
```
    - apt-get update
    - apt-get install apt-transport-https
    - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | tee /etc/apt/sources.list.d/azure-cli.list
    - apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
    - apt-get update
    - apt-get install azure-cli
    - az login --service-principal -u "$AZURE_SERVICE_PRINCIPAL_NAME" -p $AZURE_SERVICE_PRINCIPAL_PASSWORD --tenant "$AZURE_SERVICE_PRINCIPAL_TENANT"
```

## Expected behavior
I should be able to log in to Azure.

## Actual behavior
This fails with the error:
`ERROR: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /REMOVED/oauth2/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))`

## Additional information (e.g. issue happens only occasionally)
I'm trying to build my dotnet core projects on GitLab CI. I'm using docker image: `microsoft/dotnet:2.0.0-sdk`. This issue has also been reported on [Azure CLI GitHub page](https://github.com/Azure/azure-cli/issues/4360) and a [reference ](https://github.com/requests/requests/issues/3482) there was made to the fact that it could be how Python was compiled, indicating it may be an issue with the Docker image being used...?

**Comment by MichaelSimons** [comment]
@patoncrispy - Python is not installed as part of the [`microsoft/dotnet:2.0.0-sdk` image](https://github.com/dotnet/dotnet-docker/tree/master/2.0/sdk/stretch/amd64) itself rather it looks to be coming as a package dependency from the [buildpack-deps:scm base image](https://github.com/docker-library/buildpack-deps/blob/1845b3f918f69b4c97912b0d4d68a5658458e84f/stretch/scm/Dockerfile).  You could verify this easily by running your steps with the buildpack-deps:scm.

**Comment by MichaelSimons** [comment]
Per my previous comment, Python is not installed as part of microsoft/dotnet image, it comes from a base image.  Closing.
