### ISSUE TITLE
Using the dotnetcore 3.1.18-3.14 alpine image gives manifest not found

### ISSUE THREAD

**Issue by ashinde90** [dotnet/dotnet-docker#3041]
Refer this Dockerfile -> https://github.com/dotnet/dotnet-docker/blob/7856e49413e94928f986dfd976fb42beee453105/src/aspnet/3.1/alpine3.14/amd64/Dockerfile

The FROM image given here does not get pulled and throws manifest not found error

I am trying to update my aspdotnetcore image using the above docker file but it fails at pulling the image mentioned-->

~ % docker pull mcr.microsoft.com/dotnet/runtime:3.1.18-alpine3.14                             
**Error response from daemon: manifest for mcr.microsoft.com/dotnet/runtime:3.1.18-alpine3.14 not found: manifest unknown: manifest tagged by "3.1.18-alpine3.14" is not found**

### Steps to Reproduce
run the docker pull for the image mentioned in the Dockerfile --> 
ARG REPO=mcr.microsoft.com/dotnet/runtime
FROM $REPO:3.1.18-alpine3.14 

Please get the docker file issue fixed.

**Comment by mthalman** [comment]
The Dockerfile you are referencing is in the nightly branch, which is for preview versions of the .NET Docker images.  These are considered to be unstable but you're welcome to target them using the nightly repo path: `mcr.microsoft.com/dotnet/nightly/runtime`.  Alpine 3.14 is not yet available for the official supported images.  You can see the tag listings between the two repos at the following pages:

* https://hub.docker.com/_/microsoft-dotnet-runtime
* https://hub.docker.com/_/microsoft-dotnet-nightly-runtime

**Comment by ashinde90** [comment]
@mthalman When can we expect a stable docker file to use ? We are waiting to get this released for our organization.

**Comment by MichaelSimons** [comment]
[Triage] https://github.com/dotnet/dotnet-docker/issues/2937 is tracking the work to support Alpine 3.14 - closing this issue.
