### ISSUE TITLE
[Feature request] A smaller runtime image

### ISSUE THREAD

**Issue by tuananh** [dotnet/dotnet-docker#310]
Reference: https://github.com/dotnet/dotnet-docker/pull/309

**Comment by MichaelSimons** [comment]
@richlander - thoughts?  I've heard no other asks for a slimmer Debian image.  All asks have been for alpine.

**Comment by mahald** [comment]
i think anyone is interested in smaller images (at least me is), as alpine usually is the smallest (2MB !!) people ask for alpine. 
ist there any reason not to use 
`debian:stretch-slim` (also official) ?
`stretch-slim` is 22 MB (compressed in the registry) while `stretch` is 45MB while alpine is 2 MB.
im currently dling ur dockerfiles for stretch and change it to stretch-slim to get a smaller image. And all is still workings fine.

**Comment by mahald** [comment]
PS: `strech-slim` is also as small (both 22MB in the registry) as this bitnami stretch, so it migth be better to use stretch-slim. Note: for the dev image it doens't really matter, but for the runtime image the slim variant is desired. and i don't see any disatvantage in using it (at least not for the runtime).

On the other hand if alpine is comming out and if it runs as stable as debian i gonna use apline due to it's size and don't care for stretch anymore.

**Comment by richlander** [comment]
Alpine support is coming soon.

**Comment by AnthonyMastrean** [comment]
@richlander Hi, from 2018! Which issues/PRs should we follow for updates? Are we generally just waiting on .NET Core 2.1 release? Until then, thank you!

@MichaelSimons I would love to avoid maintaining my own custom Debian slim image. The only change is in the `FROM` line 😄 

```diff
-FROM debian:stretch
+FROM debian:stretch-slim
```
https://github.com/dotnet/dotnet-docker/blob/master/2.0/runtime-deps/stretch/amd64/Dockerfile#L1

Of course, the Alpine image the superior solution for managing image size, that's probably why it's most requested.

**Comment by MichaelSimons** [comment]
@AnthonyMastrean - 2.1-preview1 images are available today.  This includes the Alpine images as well as ubuntu-slim based runtime images.  Ubuntu was chosen as it is generally more secure (e.g. has fewer vulnerabilities) than Debian. 

Regarding your suggestion of changing the 2.0 images to be based on stretch-slim, we would not be able to make a change like this as it would be considered a breaking change.

**Comment by AnthonyMastrean** [comment]
@MichaelSimons I'll wait for the .NET Core 2.1 GA. I have some older apps running on .NET Core 1.1 LTS for the forseeable future. I guess I'll just maintain my custom base images! If it's not too complicated to explain, why is a slim image considered breaking? What if it's provided _in addition_ to the regular image?

**Comment by MichaelSimons** [comment]
@AnthonyMastrean - Changing the existing images to slim is considered breaking as users can have dependencies on the components/files that were removed within the slim image.  An additional image would be the way to add support.

**Comment by richlander** [comment]
I think we can close this now ... We're not going to change the base image of the 2.0 images and the 2.1 images have a solution. Good?

**Comment by MichaelSimons** [comment]
Hearing no objection on the [new distros for the 2.1 images](https://github.com/dotnet/dotnet-docker/pull/385), I'm closing this.  We always welcome feedback on distros we produce images for.
