### ISSUE TITLE
Document update policy for floating tags

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3118]
There should be documentation which states when floating tags get updated.  For example, `5.0-alpine` will be updated to reference the latest supported Alpine version.  But `5.0` will always remain on the original Debian version and _not_ be updated when a new Debian version becomes supported (except for the case when the original Debian version is EOL).

**Comment by lbussell** [comment]
There is new Debian specific wording about this scenario in this commit: https://github.com/dotnet/dotnet-docker/commit/c4db60bcedb9ff27d2a69ce52bf2bf783f4ab576#diff-12e467a8e7db8784c23f1b5ba6b2c8b5243c77430c3c777bc3d1db07ac4b600f
