### ISSUE TITLE
Stop producing Nano Server Version suffixed tags for non-fully qualified versions

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#312]
@ravimeda commented on [Sun Oct 08 2017](https://github.com/dotnet/dotnet-docker-nightly/issues/454)

## Steps to reproduce the issue
1. Open `manifest.json`, and navigate to https://github.com/dotnet/dotnet-docker-nightly/blob/master/manifest.json#L76
2. Notice that tag contains `$(nanoServerVersion)`

## Expected behavior
There isn't any customer usage scenario of these images. Hence these images are no longer needed to be built.

---

@MichaelSimons commented on [Mon Oct 09 2017](https://github.com/dotnet/dotnet-docker-nightly/issues/454#issuecomment-335178532)

Currently there are a lot Nano Server version suffixed tags being produced for .NET Core.  For example for the 1.1 runtime the following tags are built:
```
1.1.4-runtime-nanoserver-10.0.14393.1715
1.1-runtime-nanoserver-10.0.14393.1715
1-runtime-nanoserver-10.0.14393.1715
runtime-nanoserver-10.0.14393.1715
```
None of these tags are documented in the readme.  These are being produced for legacy reasons.  The only one that is of value is the fully qualified version one (1.1.4-runtime-nanoserver-10.0.14393.1715).  The remained of the tags should be dropped during the next Nano Server servicing event as this is when a new versioned tag would be created and nobody would have a dependency on it.

**Comment by natemcmaster** [comment]
Can we stop producing these for microsoft/aspnetcore(-build) images too?

**Comment by MichaelSimons** [comment]
@natemcmaster - I think so.  I think it makes sense to keep the repos in alignment.
