### ISSUE TITLE
Add distroless support for CBL-Mariner

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3141]
- [x] Define custom Linux VM scale set agent pool
- [x] Support "FROM scratch" Dockerfiles in Image Builder
- [x] Define CBL-Mariner builder Dockerfile
- [x] Pre-build script for building CBL-Mariner distroless image
- [x] Define distroless Dockerfiles for CBL-Mariner
- [x] Update tests to handle distroless
- [x] Merge to main

**Comment by johnazariah** [comment]
Watching!

**Comment by olljanat** [comment]
@mthalman so are those distroless runtime images now available on somewhere? I cannot see those at least on https://hub.docker.com/_/microsoft-dotnet-runtime/ or https://hub.docker.com/_/microsoft-dotnet-aspnet/

**Comment by mthalman** [comment]
@olljanat - These distroless container images are for [CBL-Mariner](https://github.com/microsoft/cbl-mariner), an internal Linux distro for Microsoft. They aren't supported publicly. The only supported tags are the ones shown in [Docker Hub](https://hub.docker.com/_/microsoft-dotnet).

**Comment by olljanat** [comment]
@mthalman Any possiblity to get also public version of those? Afaiu that was what @richlander proposed on https://github.com/dotnet/dotnet-docker/pull/3139#issuecomment-928098857 that there should be distroless + rootless image available for those of us who want minimize attack surface.

**Comment by mthalman** [comment]
> Any possibility to get also public version of those?

While CBL-Mariner remains an internal Linux distro for Microsoft, there will not be publicly supported container images for it in any form.

Comments from @richlander were really saying that we would use our work in providing distroless container images of CBL-Mariner internally at Microsoft as a learning experience for providing a broader public offering of distroless. We plan to publish a memo that clarifies what our strategy is for distroless going forward. But don't expect that until after the new year.
