### ISSUE TITLE
Update to newer dotnet cli as current version does not understand netcoreapp framework

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/dotnet-docker#32]
I understand dotnet core RC2 will be out in a couple of weeks but another more recent alpha to aid people in getting it running would not hurt as this version is horribly outdated.

**Comment by MichaelSimons** [comment]
@NinoFloris you may consider utilizing the [preview image](https://hub.docker.com/r/microsoft/dotnet-preview/).  This image contains the latest CLI.  It is updated each time a new CLI build is available.

**Comment by NinoFloris** [comment]
Alright, thanks
