### ISSUE TITLE
Use manifest-based tags for Windows versions (RS1, RS3, ...)

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#322]
# Use manifest-based tags for Windows versions (RS1, RS3, ...)

We should use manifest-based tags for dotnet images to enable the same tags to be used for RS1 and RS3. The Docker client will pull the correct image for the given OS (RS1 or RS1 and RS2 machines and RS3 for RS3+ machines).

The same change is being made to .NET Framework images: https://github.com/Microsoft/dotnet-framework-docker/issues/32

## Experience

We want the following example behavior:

- Logical tag: 2.0.0-runtime
- RS1/2 physical tag: 2.0.0-runtime-nanoserver-10.0.14393.1770
- RS3+ physical tag: 2.0.0-runtime-nanoserver-1709_KB4043961

We will make this change for all .NET Core nanoserver images.

## Context

Docker offers a feature called [manifest lists](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#manifest-list) that enable you to create [multi-arch images](https://blog.docker.com/2017/09/docker-official-images-now-
multi-platform/). This feature enables a single logical tag to be exposed but that can result in different images for different operating systems. The feature was developed for different OSes -- Windows vs. Linux -- but it can also be used for different versions of the same OS. That's what we want here, to offer different images for the same logical tag, but differ by Windows version.

Windows container images are not as portable as Linux ones. Windows 10 RS3 images cannot be loaded on an RS1 system. 

You need [Docker 17.10](https://docs.docker.com/release-notes/docker-ce/#17100-ce-2017-10-17) or later to use Windows-version-specific manifest list tags. The following [change]( https://github.com/moby/moby/commit/38aef56e1fcb8ea318df98c89cf002267b88a136#diff-77a3b9683ea5b78ddbf146c0cbad74e1) from the Docker 17.10 release notes is the one that enables this functionality.

* Add support for Windows version filtering on pull [moby/moby#35090](https://github.com/moby/moby/pull/35090)

## Resources

* [Windows Server 2016 Nano Server Docker tags](https://hub.docker.com/r/microsoft/nanoserver/tags/)
* [Windows 10 Version History](https://en.wikipedia.org/wiki/Windows_10_version_history)

**Comment by richlander** [comment]
This issue has already been fixed.

What still needs to happen:

- Add manifest tags to 1709 section.
- Note which Docker client version you need.

**Comment by MichaelSimons** [comment]
Manifest tags were added to the documentation with #341
