### ISSUE TITLE
Image appears to pin CPU

### ISSUE THREAD

**Issue by blitzd** [dotnet/dotnet-docker#33]
I was going through the .NET Core 1.0 walk-through on docker containers, and left this image running after having issued the commands (this is the full output of docker logs):

```
root@ff075d846319:/# mkdir helloworld
root@ff075d846319:/# cd helloworld/
root@ff075d846319:/helloworld# dotnet new
Created new C# project in /helloworld.
```

I came back after the weekend to find it had pinned the CPU at 100% full time since that command had been run. The dotnet process was Z, and couldn't be killed (SIGKILL/SIGTERM). I had to reboot the actual host to resolve the issue.

I don't know if there's any relevant logs that would help determine what the issue was, but I have the container still if someone can point me in the right direction...

**Comment by MichaelSimons** [comment]
@blitzd,  can you provide the `docker --version` and the `lsb-release -a` from your host?  Can you also provide the `dotnet --info` from the container?

**Comment by blitzd** [comment]
@MichaelSimons 

```
Docker version 1.9.1, build a34a1d5
```

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

As for the --info, I got this:

```
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001598)
Usage: dotnet mmon-options] mmand] guments]

Arguments:
  mmand]     The command to execute
  guments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package
```

It never returned from that, and then I got pinned at 100% again. Any suggestions for how to kill this without performing another reboot?

**Comment by MichaelSimons** [comment]
@blitzd Is your host by change an Azure VM?  I am wondering if by you are encountering the same issue described in https://github.com/dotnet/cli/issues/2644#issuecomment-213632460.  Have you also tried using a newer dotnet version?  For example have you tried the [microsoft/dotnet-preview](https://hub.docker.com/r/microsoft/dotnet-preview/) image?

Regarding killing the container, did you try `docker rm -fv CONTAINER_ID`?

**Comment by blitzd** [comment]
The host is on VMWare. I haven't tried any newer dotnet version - as I said I was just going through the walk-through, and assumed that ```:latest``` would be the newest image. ```rm -fv``` (or any other similar commands, just hang.

**Comment by MichaelSimons** [comment]
@blitzd, what kernel version is your host using?

**Comment by blitzd** [comment]
@MichaelSimons 

```Linux webapps 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by MichaelSimons** [comment]
@blitzd - You may have hit https://github.com/docker/docker/issues/18180 which is a docker issue.  The [solution](https://github.com/docker/docker/issues/18180#issuecomment-193708192) on Ubuntu 15.10 is to Upgrade kernel to 4.2.0-30.35 or later.

**Comment by blitzd** [comment]
@MichaelSimons Yes that looks to have been it, 30.35 update resolved the issue. Thanks for your help!
