### ISSUE TITLE
Cannot remote debug using Visual Studio with (--privileged -v /lib:lib -v /usr/lib:/usr/lib) aspnet:6.0-bullseye-slim-arm32v7

### ISSUE THREAD

**Issue by mwkldeveloper** [dotnet/dotnet-docker#3304]
### Describe the bug
Using image "aspnet:6.0-bullseye-slim-arm32v7" on raspberry pi4,
I try run a simple .net6 WebAPI project without --privileged (it may be related to #3253) . 

The same as #3253 mentioned:  need --privileged to run, otherwise Aborted (core dumped).
But I found that if  add (`-v /lib:lib -v /usr/lib:/usr/lib`), it runs good, and no need add --privileged
Below work without Aborted (core dumped):
`docker run -it -v ~/app:/app -v /lib:lib -v /usr/lib:/usr/lib --name=test --rm  --network=host mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7`

Then, I try  remote debug using Visual Studio 2022, and it doesn't work.
The VS 2022 can connected to the container , but the program cannot pause at the break point.

So, i try add back  --privileged, But the same , connected to the container , but the program cannot pause
`docker run -it --privileged  -v ~/app:/app -v /lib:lib -v /usr/lib:/usr/lib --name=test --rm  --network=host mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7`

Then, i try remove (`-v /lib:lib -v /usr/lib:/usr/lib`), it work!!, can remote debug now.
`docker run -it --privileged  -v ~/app:/app  --name=test --rm  --network=host mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7`

### To Reproduce
Use --privileged  -v /lib:lib -v /usr/lib:/usr/lib  together:

`docker run -it --privileged  -v ~/app:/app -v /lib:lib -v /usr/lib:/usr/lib --name=test --rm  --network=host mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7`

### Further technical details
```
- root@iguardevice:/# dotnet --info

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- Visual Studio 2022

**Comment by mwkldeveloper** [comment]
i think some file are missing as i mount /lib and /usr/lib directly? Which file is used for remote debug?

**Comment by mthalman** [comment]
> Then, i try remove (`-v /lib:lib -v /usr/lib:/usr/lib`), it work!!, can remote debug now.
> `docker run -it --privileged -v ~/app:/app --name=test --rm --network=host mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7`

If it works, then why do you want to add the volume mounting? Mounting system files from the host isn't something that would be recommended. As for https://github.com/dotnet/dotnet-docker/issues/3253, the workaround for this is to [update libseccomp on the host](https://github.com/dotnet/dotnet-docker/issues/3253#issuecomment-956378676), not run as privileged.

**Comment by mwkldeveloper** [comment]
@mthalman 
I think I mix up the issue. 
When add volume mounting, it don't need --privileged, I thought #3253 issue gone. 
But it cannot remote debug even add --privileged , so I thought  it is another issue.
I close this issue now, the problem seems come from volume mount overwrite some file, and #3253 issue is still here.
