### ISSUE TITLE
mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1909 is using preview versions

### ISSUE THREAD

**Issue by BBoldenow** [dotnet/dotnet-docker#3315]
### Describe the Bug

mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1909 is using preview version

❯ docker pull mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1909
❯ docker run --rm -it mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-1909
C:\>dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Output of `docker version`

Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:54:29 2021
  OS/Arch:          windows/amd64
  Experimental:     false

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 60
  Running: 0
  Paused: 0
  Stopped: 60
 Images: 176
 Server Version: 20.10.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.1801)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.76GiB
 Name: ENG00058
 ID: 5IUM:ROYF:6UNQ:5WL4:7YUD:U3PM:HOPS:DJJZ:AKHC:GW6Z:ESUJ:BQXF
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by mthalman** [comment]
This is because Windows Server, version 1909 is no longer supported as of May 2021. Please see https://github.com/dotnet/dotnet-docker/issues/2806 for more info.

**Comment by BBoldenow** [comment]
@mthalman - Thanks for the quick response and the information. That link doesn't seem to have a recommended version - is it 2004 or do I have to go back to 1809?

**Comment by mthalman** [comment]
> @mthalman - Thanks for the quick response and the information. That link doesn't seem to have a recommended version - is it 2004 or do I have to go back to 1809?

It really depends on what's available in your target build and production environments. The latest version is Windows Server 2022, which is an [LTSC version](https://docs.microsoft.com/windows-server/get-started/servicing-channels-comparison#long-term-servicing-channel-ltsc). If your build and production environment support that version, I would go with that if your application can migrate without issue. The other [SAC versions](https://docs.microsoft.com/windows-server/get-started/servicing-channels-comparison#semi-annual-channel) that are currently supported are 20H2, 2004, and 1809. Version 2004 goes out of support later this month so I wouldn't recommend that. Version 1809 was originally a SAC version but has since had support extended for containers until Jan 2024.

**Comment by BBoldenow** [comment]
Thanks. It looks like I'll have to target 1809 for the time being.
