### ISSUE TITLE
No connection could be made because the target machine actively refused it. (api.nuget.org:443) - sdk:5.0-nanoserver-2004

### ISSUE THREAD

**Issue by QuAzI** [dotnet/dotnet-docker#3324]
NuGet packages absolutely unavailable under sdk:5.0-nanoserver-2004 if `isolation=process` enabled
```
  "exec-opts": [
    "isolation=process"
  ],
```

# Steps to reproduce

Create Dockerfile
```
FROM mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-2004

WORKDIR /App
COPY App/ ./
ENTRYPOINT ["dotnet", "run"]
```

then
```
docker rm nuget-test
dotnet new console -o App -n NetCore.Docker --framework "net5.0"
cd app

dotnet add package Newtonsoft.Json --version 13.0.1

cd ..
docker build -t nuget-test -f Dockerfile .
docker run -it --rm nuget-test
```

It always finishes with
```
C:\Program Files\dotnet\sdk\5.0.403\NuGet.targets(131,5): error :   No connection could be made because the target machine actively refused it. (api.nuget.org:443) [C:\App\NetCore.Docker.csproj]
C:\Program Files\dotnet\sdk\5.0.403\NuGet.targets(131,5): error :   No connection could be made because the target machine actively refused it. [C:\App\NetCore.Docker.csproj]
```

# Environment

Edition: Windows 10 Pro
Version: 21H2
Installed on: 18 ‎Sep ‎2020
OS build: 19044.1387
Experience: Windows Feature Experience Pack 120.2212.3920.0
Docker Engine: v20.10.11

**Comment by seekerman** [comment]
您好，您的邮件我已经收到，我会尽快回复的。祝您生活愉快！        ——  于云鹏   O(∩_∩)O

**Comment by mthalman** [comment]
Have you verified general network connectivity? For example, are you able to run `ping api.nuget.org` from within the container?

Also note that [Windows Server, version 2004 will be EOL next week, Dec. 14](https://docs.microsoft.com/en-us/lifecycle/products/windows-server). So it is recommended that you upgrade to a supported version soon.

**Comment by QuAzI** [comment]
@mthalman it is big problem. I am trying to use 2004 because other images crashes with `The operating system of the container does not match the host operating system`
```
![image](https://user-images.githubusercontent.com/1897605/145052092-531b5486-e285-42f3-b7e9-ff21ab477b48.png)
```
And looks like there is no other way to have `isolation=process` with fresh versions of win10 pro. Even if it 21H2 (which is marked as LTSC for Enterprise and IoT)

**Comment by mthalman** [comment]
> I am trying to use 2004 because other images crashes with `The operating system of the container does not match the host operating system`

Please see this [article on Windows container version compatibility](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1). That explains why you are getting this error. The host and container must be compatible versions with respect to the isolation mode.

Can you please respond to my earlier question:

> Have you verified general network connectivity? For example, are you able to run `ping api.nuget.org` from within the container?

**Comment by QuAzI** [comment]
Looks like all fine with network
![image](https://user-images.githubusercontent.com/1897605/145055698-0c7f4f65-461f-41b7-bce6-8c625219368d.png)

It is nice document which is absolutely doesn't have any mentions about **21H2** (
Latest is **21H1** which should support **20H2** but for **21H2** it doesn't work : `The operating system of the container does not match the host operating system`. And I can't downgrade my OS.
Also 20H2 will be EOL [soon too](https://docs.microsoft.com/en-us/windows/release-health/release-information). 1809 doesn't have process isolation. So I don't have any way to run containers with normal performance

**Comment by mthalman** [comment]
I'm really confused how you're able to run a 2004 container in process isolation from a 21H2 machine. The only Windows version that should be able to execute a 2004 container in process isolation is from a 2004 host machine.

Can you clarify things? Instead of using the options in the daemon.json file, can you show the output from the command line by using the `--isolation=process` option in `docker run`? And also please include the output of `ver` from the host machine. That will help me make sense of things.

**Comment by QuAzI** [comment]
```
>ver
Microsoft Windows [Version 10.0.19044.1387]

>docker inspect --format='{{.OsVersion}}' nuget-test
'10.0.19041.1348'
```
![image](https://user-images.githubusercontent.com/1897605/145072787-0bb1ebea-6bf1-4b5c-96af-9f3878314b0b.png)

full run
https://user-images.githubusercontent.com/1897605/145071642-4a167b55-6816-48c8-9508-5146e2d3fdf8.mp4

**Comment by mthalman** [comment]
Ok, so you're using a 2004 host machine. Why are you asking about 21H2 then? That's where my confusion comes from.

**Comment by QuAzI** [comment]
My host is 19044 and it is 21H2. 19041 in docker. But nuget doesn't work properly in this combination.

**Comment by mthalman** [comment]
@QuAzl - Just to confirm, this works if you use hyperv isolation but not if you use process isolation, is that correct?

**Comment by QuAzI** [comment]
Exactly. NuGet in container 2004 works fine with hyperv (default) isolation on 21H2 host. But doesn't work with process isolation.
And all it happens because there is no way to use 21H2 containers. Looks like it is bad idea to install any updates after 20H2.
And there is no way to build it. All required containers don't have version for 21H2.
And I also can't use there Linux Containers because for some items I need Windows Containers but mixed mode broken.

**Comment by mthalman** [comment]
I followed up with the Windows Container team regarding this because it didn't make sense to me that you are able to run a 2004 container with process isolation on a Win 10 21H2 host. (I was able to replicate that behavior myself.) It turns out this is a bug and not intended to be a supported configuration. If running with process isolation is required, the recommendation is to upgrade to Windows 11 and use a LTSC 2022 container (`sdk:5.0-nanoserver-ltsc2022`). Otherwise, hyperv isolation is the only supported mode in Win 10 21H2.

**Comment by QuAzI** [comment]
I can't upgrade to Windows 11 now. And I can't work properly when MSVS and then Docker Desktop regularly getting stuck

32GB RAM, i7-10510U, NVMe SSD - is it not enough to run a bit containers? Why I need different OS?

![image](https://user-images.githubusercontent.com/1897605/145266060-a016891c-d500-45bb-b9ac-44e81a05aabb.png)

**Comment by mthalman** [comment]
Triage: If you're having performance issues with hyperv isolation that are blocking you, please follow up with https://github.com/Microsoft/Windows-Containers to help investigate that. This doesn't seem specifically related to the .NET Docker images but rather Windows containers and the isolation mode.
