### ISSUE TITLE
.NET 6 docker container run fail (Exited 132) on Debian arm32

### ISSUE THREAD

**Issue by KevinKao809** [dotnet/dotnet-docker#3351]
### Describe the Bug
I follow the steps to create a docker image (by Dockerfile.debian-arm32) on X64 Ubuntu VM without issue, but fail to run it on physical arm32 device with "Exited (132)"ㄡ

### Steps to Reproduce
1. Setup a Ubuntu 21.10 VM (X64), install Docker 20.10.12, install dotnet 6.0.100
2. Download files to VM (Dockerfile.debian-arm32, Program.cs, dotnetapp.csproj)
3. Build docker image by below command:
    `docker build --pull -t dotnetapp:debian-arm32 -f Dockerfile.debian-arm32 .`
4. push dotnetapp:debian-arm32 to my image registry
5. pull dotnetapp:debian-arm32 on my Device (armhf, Debain 9)
6. Run it
    docker run `dotnetapp:debian-arm32`

### Output of `docker version`

Docker version 19.03.15, build 99e3ed8919

### Output of `docker info`

Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 19.03.15
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.0-cip-rt-moxa-imx7d
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: armv7l
 CPUs: 2
 Total Memory: 1.971GiB
 Name: Moxa
 ID: ZJVB:HO7B:EYE3:3G5U:3IMC:CACU:ANI2:56OM:UVDS:TMT6:S5J3:TJFE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support

**Comment by mthalman** [comment]
This is related to https://github.com/dotnet/dotnet-docker/issues/3253. Specifically, a workaround is to [install an updated version of libseccomp](https://github.com/dotnet/dotnet-docker/issues/3253#issuecomment-956378676). I had the same issue on my RaspberryPi and installing the new version of libseccomp resolve the issue. Another alternative is to execute `docker run` with the `--privileged` option.

**Comment by mthalman** [comment]
[Triage] Closing per the [previous comment](https://github.com/dotnet/dotnet-docker/issues/3351#issuecomment-994818075) that this is a known issue with regards to libseccomp and Docker that can be worked around.
