### ISSUE TITLE
Running dotnet-monitor as a non-root user

### ISSUE THREAD

**Issue by ZloyChert** [dotnet/dotnet-docker#3368]
### Describe the Problem

Docker file for dontet-monitor doesn't contain switching to non-root user. 
So, to run as non-root user, I need to create and push image, that wraps that one.
https://github.com/dotnet/dotnet-docker/blob/main/src/monitor/6.0/alpine/amd64/Dockerfile

### Describe the Solution

On alpine, **USER 405** can be used to run as non-root user

### Additional Context

I have wrapper image for now and seems, everything works well with it.

**Comment by mthalman** [comment]
@jander-msft - Can you provide your thoughts on this request. Is it reasonable to have a non-root user defined by default?

**Comment by jander-msft** [comment]
Absolutely! I'll investigate this a bit and come back with some data.

**Comment by jander-msft** [comment]
When running dotnet-monitor in listen mode and running as the 405 user:
- An app running as the 405 user or as root can connect to dotnet-monitor to establish the diagnostic port connection.
- An app running as any other user will not successfully connect and in fact hang it's runtime until it can connect (which will never happen).

When running dotnet-monitor in connect mode and running as the 405 user:
- An app running as the 405 user can be connected to by dotnet-monitor to establish the diagnostic port connection.
- An app running as any other user will not allow dotnet-monitor to connect to it.

Additionally, while the dotnet-monitor image is based on Alpine Linux, it does work with other distributions that applications may be running on, so making the assumption that user 405 exists in the containers is not necessarily valid. Those other distributions may have other guest or low privilege users out-of-the-box.

It's my opinion that the dotnet-monitor image should be kept as-is to run as the default (root) user. However, it is authored in such a way to allow a customer to easily change the user to the one that they would like to use in their deployments. We can update dotnet-monitor documentation to describe how to switch the user and what are the implications of doing so.

**Comment by fmad** [comment]
> We can update dotnet-monitor documentation to describe how to switch the user and what are the implications of doing so.

@jander-msft Has this been done? If so, where can I find this information? Thanks.

**Comment by Krishnadas-KP** [comment]
@jander-msft I tried the setup mentioned in your previous comment.
Dotnet monitor as 405 user
App running as root (user 0) in kubernetes
Dotnet monitor in Listen mode added as sidecar

But dotnet monitor is not able to get /metrics or /livemetrics etc. When I check /processes, I get [] so I think dotnet monitor cant find any processes. How could this be ? Any suggestions ?

**Comment by jander-msft** [comment]
Please see https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md for an example of how to run .NET Monitor in listen mode. It doesn't show how to change the user, but so long as .NET Monitor is running as the same user as the app OR the app container is running as root, then it should work in listen mode.

**Comment by Krishnadas-KP** [comment]
@jander-msft Thanks for the reply. But it is not working for me with a sample app. This is the manifest I am trying with. The app container is not starting when dotnet-monitor is in Listen mode so I assume it is unable to connect. When it is in connect mode it starts up but as this thread says dotnet monitor cant get any metrics. Bit baffled here on what could be the issue.

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      containers:
      - name: app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          runAsUser: 405
          runAsGroup: 100
      - name: sidecar
        image: mcr.microsoft.com/dotnet/monitor:7.0
        args: [ "collect", "--no-auth" ]
        ports:
        - containerPort: 52323
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        - name: DOTNETMONITOR_Urls
          value: http://localhost:52323
        - name: DOTNETMONITOR_Metrics__Endpoints
          value: http://+:52325
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
        securityContext:
          runAsUser: 405
          runAsGroup: 100
      volumes:
      - name: diagvol
        emptyDir: {}`

**Comment by Krishnadas-KP** [comment]
@ZloyChert Has this worked for you ? I am trying to run dotnet monitor as non root sidecar alongside my application container which is also non root. I have set 405 as the user in dockerfile and can see that the dotnet monitor process gets run as 405 user when exec ing into the container. I have also set 405 as the user for the application container. But it is not able to communicate with dotnet monitor. Have you done anything extra to make it work ?

**Comment by jander-msft** [comment]
> @jander-msft Thanks for the reply. But it is not working for me with a sample app. This is the manifest I am trying with. The app container is not starting when dotnet-monitor is in Listen mode so I assume it is unable to connect. When it is in connect mode it starts up but as this thread says dotnet monitor cant get any metrics. Bit baffled here on what could be the issue.
> 
> > apiVersion: apps/v1
> > kind: Deployment
> > metadata:
> > name: deploy-exampleapp
> > spec:
> > replicas: 1
> > selector:
> > matchLabels:
> > app: exampleapp
> > template:
> > metadata:
> > labels:
> > app: exampleapp
> > spec:
> > restartPolicy: Always
> > containers:
> > - name: app
> > image: mcr.microsoft.com/dotnet/samples:aspnetapp
> > imagePullPolicy: Always
> > env:
> > - name: ASPNETCORE_URLS
> > value: http://+:80
> > - name: DOTNET_DiagnosticPorts
> > value: /diag/dotnet-monitor.sock
> > volumeMounts:
> > - mountPath: /diag
> > name: diagvol
> > resources:
> > limits:
> > cpu: 250m
> > memory: 512Mi
> > requests:
> > cpu: 50m
> > memory: 32Mi
> > securityContext:
> > runAsUser: 405
> > runAsGroup: 100
> > - name: sidecar
> > image: mcr.microsoft.com/dotnet/monitor:7.0
> > args: [ "collect", "--no-auth" ]
> > ports:
> > - containerPort: 52323
> > imagePullPolicy: Always
> > env:
> > - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
> > value: Listen
> > - name: DOTNETMONITOR_Storage__DefaultSharedPath
> > value: /diag
> > - name: DOTNETMONITOR_Urls
> > value: http://localhost:52323
> > - name: DOTNETMONITOR_Metrics__Endpoints
> > value: http://+:52325
> > volumeMounts:
> > - mountPath: /diag
> > name: diagvol
> > resources:
> > requests:
> > cpu: 50m
> > memory: 32Mi
> > limits:
> > cpu: 250m
> > memory: 256Mi
> > securityContext:
> > runAsUser: 405
> > runAsGroup: 100
> > volumes:
> > - name: diagvol
> > emptyDir: {}

You have to change the URL binding on the application container to a non-privileged port (typically something 1000+) otherwise the application will fail to startup.

If you have further questions/issues, please feel free to open a new issue in https://github.com/dotnet/dotnet-monitor/issues

**Comment by Krishnadas-KP** [comment]
Thanks @jander-msft. I tried with my app container running user 1000 and it still is not working. I have raised a new issue here https://github.com/dotnet/dotnet-monitor/issues/4018
