### ISSUE TITLE
Disable UseAppHost in sample FDD Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3392]
The sample FDD Dockerfiles generated all use the following line:

```Dockerfile
RUN dotnet publish -c release -o /app --no-restore
```

This ends up outputting both an app executable and a library file in the output directory. See the [publish documentation](https://docs.microsoft.com/dotnet/core/deploying/#publish-framework-dependent):

> Publishing an app as framework-dependent produces a cross-platform binary as a dll file, and a platform-specific executable that targets your current platform.

Either file can be used to execute the app. The executable can be executed directly while the DLL requires the use of the .NET CLI (`dotnet aspnetapp.dll`). From an image size perspective, it seems wasteful to include both files in the output. Only one of them is actually needed in order to execute the app. The Dockerfile is configured to only make use of the DLL:

```Dockerfile
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```

So it seems reasonable to simply not include the executable in the output.

By configuring the `UseAppHost` property, the publish logic can be configured to not include the executable in the output.

I propose that the sample FDD Dockerfiles disable this property by default:

```Dockerfile
RUN dotnet publish -c release -o /app --no-restore /p:UseAppHost=false
```

**Comment by richlander** [comment]
This approach seems like overkill. I agree that the apphost is unnecessary for this scenarios, however, I think we should continue using it for a few reasons.

- The additional CLI complexity (as guidance) isn't worth the size win (~200k).
- Native platforms start with a single exe, not a launcher.
- This launcher pattern breaks when you switch to single file or native aot.

**Comment by mthalman** [comment]
[Triage]
The samples have been updated to make use of the app host which reflects the points that were made in https://github.com/dotnet/dotnet-docker/issues/3392#issuecomment-1491278642. Based on those reasons, we've determined that the disabling of UseAppHost should not be done.
