### ISSUE TITLE
Exclude icu from distroless CBL-Mariner

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3394]
The `icu` package is currently included in the distroless version of CBL-Mariner:

https://github.com/dotnet/dotnet-docker/blob/c80eae7c725c4c51a2ea18d0f0bb888f47d49e30/src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile#L11

In order to reduce the image size/content, I propose that the `icu` package be excluded and have invariant mode enabled, just as is done for Alpine:

https://github.com/dotnet/dotnet-docker/blob/c80eae7c725c4c51a2ea18d0f0bb888f47d49e30/src/runtime-deps/3.1/alpine3.14/amd64/Dockerfile#L19-L20

This would be a breaking change and thus should be done starting with .NET 7.

**Comment by mthalman** [comment]
[Triage] Also consider doing this for .NET 6 after coordinating with 1st party customers due to the breaking change aspect.

**Comment by AndrewP-GH** [comment]
@mthalman Hello!
How to customize the distroless image if I set <InvariantGlobalization>fase</InvariantGlobalization> to use culture-specific logic? Or distrolees image is designed to be used only for the invariant culture app?
