### ISSUE TITLE
Last layer "GUID" does not have a base layer reference

### ISSUE THREAD

**Issue by girishgouda** [dotnet/dotnet-docker#34]
I am trying to create a custom docker image using the dockerfile as shown

FROM microsoft/dotnet:0.0.1-alpha-onbuild

RUN mkdir -p /dotnetapp
WORKDIR /dotnetapp

ENTRYPOINT ["dotnet", "run"]

ONBUILD COPY . /dotnetapp
ONBUILD RUN dotnet restore

i get the error **Last layer "91f7f9444ee1305921aa584bb4806c40bcece5c618f83ac383e105b23bdb6aad" does not have a base layer reference**

I am trying to build the image in windows server 2016 TP5 on Azure 

Any help is much apprciated

Thanks

**Comment by MichaelSimons** [comment]
This is a result of not having a [manifest](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md) defined.  When on Windows Server Core and Nano Server, docker will try to pull the Linux images which are invalid on Windows platforms.  It seems like docker should have a better story here though - not everyone is going to support all platforms.

**Comment by timotei** [comment]
> docker will try to pull the Linux images which are invalid on Windows platforms.

Is this a limitation which is planned to be removed in the final release of Windows Containers?

**Comment by MichaelSimons** [comment]
@timotei, Creating a Docker manifest is what will address this.  This contains metadata that docker will read in order to determine which image applies to each platform/architecture.  Additionally if docker doesn't find a matching image, it will then display a more friendly error message to the user.  We will add a manifest for the microsoft/dotnet images once it is fully flushed out.

**Comment by MichaelSimons** [comment]
This work is being tracked with https://github.com/dotnet/dotnet-docker/issues/99.  Closing this issue.

**Comment by timotei** [comment]
@MichaelSimons I understand that, but my question was more like: will this limitation (running Linux on Windows platforms) be removed in the final release?

**Comment by MichaelSimons** [comment]
@timotei, you can run Linux on the Windows platform via [Docker for Windows](https://docs.docker.com/engine/installation/windows/).  

@PatrickLang, @friism - Is there any documentation (e.g. blog article) that talks about Docker for Windows vs Windows Containers, what the use cases are for each, how they can be used SxS and what the road maps looks like?  I think this would be helpful as there seems to be some confusion between the two.

**Comment by friism** [comment]
* What are they: https://forums.docker.com/t/in-docker-for-windows-does-each-container-run-in-separate-vm/19192/6?u=friism
 * How to run them side by side: https://forums.docker.com/t/linux-and-windows-images-side-by-side/20518/4?u=friism
 

Work has been done to improve these errors, see details here:

 * https://github.com/docker/docker/issues/24766
 * https://github.com/docker/docker/pull/24819

I'd be interested to know if these checks and errors are not working.

... and yes, we're working on installing both with Docker for Windows
