### ISSUE TITLE
Provide official distroless images

### ISSUE THREAD

**Issue by jasper-d** [dotnet/dotnet-docker#3405]
### Describe the Problem
Official runtime images (e.g. `mcr.microsoft.com/dotnet/runtime` and `mcr.microsoft.com/dotnet/aspnet`) are quite big (`runtime:6.0-bullseye-slim` is 188 MB). This does not only increase bandwidth and storage usage all over the place as well as startup time, but also increases the attack surface.
Additionally, these images run as root by default. If you're lucky your container runtime won't execute them because of policies, if you lack such policies and you forget to specify a user explicitly you just have made it very easy for an attacker.

There are already distroless and rootless images available (e.g. `mcr.microsoft.com/dotnet/runtime:6.0-cbl-mariner1.0-distroless-amd64`) which are not only smaller but also have a reduced attack surface. Unfortunately, these images are not officially supported (https://github.com/dotnet/dotnet-docker/issues/3141#issuecomment-992519162), so users currently have two options: build lightweight secure images themself or rely on Mariner images that come without support.

Building images yourself is of course possible but requires some effort (analyzing native dependencies, setting up build pipelines, updating everything for new .NET major releases etc.). Using an unsupported images avoids that work but if they aren't updated any longer at some point one may run outdated images with vulnerabilities. 

### Describe the Solution
It would be nice if .NET would come with officially supported distroless images that are on par with images for other runtimes, follow security best practices and work out of the box in standard setups (e.g. `COMPlus_EnableDiagnostics=0` so that containers do not crash at startup).
Consider removing native dependency that are not used by typical container workloads (i.e. #3394 and krb5) or provide additional "fat" variants if users actually need them.

**Comment by mthalman** [comment]
Thanks for sharing your interest in distroless. The original issue requesting broad distroless support is https://github.com/dotnet/dotnet-docker/issues/2074. We just had a conversation yesterday about adding distroless support for Alpine Linux. Would that suit your needs? Or would you require a glibc-based distro?

**Comment by jasper-d** [comment]
> The original issue requesting broad distroless support is #2074.
Sorry, I didn't realize that the issue is still active. I'm going to close this one.

> Or would you require a glibc-based distro?
Alpine/musl would be totally fine for me. From my experience, if something requires glibc it typically also requires a bunch of other libs and isn't well suited for distroless anyways.

**Comment by olljanat** [comment]
> (e.g. `COMPlus_EnableDiagnostics=0` so that containers do not crash at startup). 

@jasper-d just FYI that default `COMPlus_EnableDiagnostics=1` works fine as long you have write access to `/tmp`. Look my hardening examples in https://github.com/dotnet/dotnet-docker/issues/1772#issuecomment-1196483685
