### ISSUE TITLE
Size increase in .NET Monitor 7.0 image

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3429]
The image size validation pipeline had a failure this week showing that the `mcr.microsoft.com/dotnet/nightly/monitor:7.0` image has increased in size compared to last week's size:

| Validation Date | Monitor Version | Image Size |
| - | - | - |
| 1/16/2022 | 7.0.0-alpha.1.22062.4 | 108,103,360 |
| 1/23/2022 | 7.0.0-alpha.1.22070.6 | 115,703,202 |

This size increase is due to nearly doubling the size of the /app folder where .NET Monitor is located. Here's a screenshot of the diff:

![image](https://user-images.githubusercontent.com/15789599/150795769-b3ce2d6a-9ce0-46bb-84c9-580fe836eb26.png)

cc @jander-msft

**Comment by jander-msft** [comment]
Image was switched over to 7.0 base image and baseline size recalculated.
