### ISSUE TITLE
New Linux Distro Version - CBL-Mariner 2.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3455]
# New Linux Distro Version

Distro: CBL-Mariner 2.0

## ImageBuilder Tasks

- [x] Ensure that the ImageBuilder supports the new distro version in the [code](https://github.com/dotnet/docker-tools/blob/main/src/Microsoft.DotNet.ImageBuilder/src/McrTagsMetadataGenerator.cs) to generate the correct README display name from the version specified in the manifest

## Nightly Branch Tasks

1. - [x] Copy the Dockerfiles of the most recent version of that distro (or author new ones for an entirely new distro) and place them in a version-specific folder under their respective variants (runtime-deps, runtime, aspnet, sdk). Note: not all variants have a corresponding runtime-deps image.
1. - [x] Modify the Dockerfiles as appropriate for any specific changes related to the new distro version
1. - [x] Update [manifest.json](https://github.com/dotnet/dotnet-docker/blob/nightly/manifest.json) to reference the new set of Dockerfiles with the appropriate tags
      - [ ] Move any distro-specific floating tags to the newer version (e.g. `3.1-alpine`)
1. - [x] Update the [test data](https://github.com/dotnet/dotnet-docker/blob/nightly/tests/Microsoft.DotNet.Docker.Tests/TestData.cs) to include the new distro version
1. - [x] Update the [tags metadata templates](https://github.com/dotnet/dotnet-docker/tree/main/eng/mcr-tags-metadata-templates) to include the new distro version
1. - [x] Run the command to update the READMEs: `.\eng\readme-templates\Get-GeneratedReadmes.ps1`
1. - [x] Run the command to update the image size baseline file: `.\tests\performance\Validate-ImageSize.ps1 -UpdateBaselines`
1. - [x] Inspect generated changes for correctness
1. - [x] Consider whether sample Dockerfiles should be authored if this is a new distro and them to the [samples](https://github.com/dotnet/dotnet-docker/tree/main/samples)
1. - [x] Run the command to build and test your changes: `.build-and-test.ps1 -OS <os>`
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR to nightly branch
1. - [x] Wait for automatically queued CI build to finish on [dotnet-docker-nightly pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=359) (internal MSFT link)
1. - [x] Confirm READMEs have been updated in [Docker Hub](https://hub.docker.com/_/microsoft-dotnet)

## Main Branch Tasks

1. - [x] After the product teams have signed off on the new distro, merge these changes to the main branch as part of the [release process](dotnet-release.md) for the next .NET release
1. - [x] Create an announcement (example: [Alpine 3.10](https://github.com/dotnet/dotnet-docker/issues/1418)) unless the new distro is added only for pre-release versions in which the announcement would be incorporated in the pre-release notes.

**Comment by mthalman** [comment]
I created a blocking bug related to installing `prebuilt-ca-certificates`: https://dev.azure.com/microsoft/OS/_workitems/edit/38162114

**Comment by olljanat** [comment]
Will distroless images be included to releases when this is ready?

Kubernetes 1.23 graduated [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) to beta so I don't see any reason to use anything else than distroless version anymore.

**Comment by mthalman** [comment]
> Will distroless images be included to releases when this is ready?

We currently only provide distroless container images for [CBL-Mainer](https://github.com/microsoft/CBL-Mariner) which is a distribution of Linux internally used at Microsoft. It is not publicly supported.

Providing distroless support for other Linux distributions is something we want to invest in but there is no ETA on that work yet. For discussion on distroless support, please refer to https://github.com/dotnet/dotnet-docker/issues/2074.

**Comment by aelij** [comment]
@mthalman Can you please also add Mariner 2.0 distroless container images for dotnet-monitor?

**Comment by mthalman** [comment]
> @mthalman Can you please also add Mariner 2.0 distroless container images for dotnet-monitor?

cc @jander-msft

**Comment by jhueppauff** [comment]
> It is not publicly supported.

@mthalman Is there a roadmap/eta when this will be supported?

**Comment by mthalman** [comment]
> > We currently only provide distroless container images for [CBL-Mainer](https://github.com/microsoft/CBL-Mariner) [...] It is not publicly supported.
> 
> @mthalman Is there a roadmap/eta when this will be supported?

Not that I know of. But that's a question for https://github.com/microsoft/CBL-Mariner.
