### ISSUE TITLE
New Images coming for VS 15.5 Release?

### ISSUE THREAD

**Issue by iamcarbon** [dotnet/dotnet-docker#349]
Compiling projects targeting C# 7.2 require v2.1.2 of the .NET Command Line Tools.

The current published images are running v2.0.3 of the .NET Command Line Tools.

Are updated images expected soon to support the new features released in VS 15.5 today?

**Comment by MichaelSimons** [comment]
Updated SDK images are now available - see the https://github.com/dotnet/dotnet-docker/commit/9f3fd6f529f45ec92e430e7c24cc6a68181916d5
