### ISSUE TITLE
No samples using the windowsservercore as the base image

### ISSUE THREAD

**Issue by girishgouda** [dotnet/dotnet-docker#35]
Hi 
Provide a image with the OS(windowsservercore or nano) and dotnetcli (dotnet new/build/restore) installed in the image . These can be used to create the custom images for asp.net core samples
Thanks

**Comment by MichaelSimons** [comment]
@girishgouda - yes this is something on our radar and are working on it.

**Comment by erichexter** [comment]
any news on this? @MichaelSimons

**Comment by MichaelSimons** [comment]
@girishgouda, @erichexter, As part of the [.NET Core 1.0 release](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/) that happened yesterday, a preview of the [docker images for windowsservercore and nanoserver](https://hub.docker.com/r/microsoft/dotnet/) based on Windows Server 2016 Technical Preview 5 were also released.  Please check them out and let us know what you think.

**Comment by MichaelSimons** [comment]
Closing issue as windowsservercore and nanoserver have now been released.  If issues are encountered with these images, please open a new issue.
