### ISSUE TITLE
Missing images for .NET SDK 6.0.200

### ISSUE THREAD

**Issue by pellared** [dotnet/dotnet-docker#3502]
> We publish .NET images as part of releasing new versions of .NET including major/minor and servicing.

The [.NET SDK 6.0.200](https://github.com/dotnet/sdk/releases/tag/v6.0.200) has been publish some time ago.

The `6.0.200-` container images are not available yet:
- https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
- https://hub.docker.com/_/microsoft-dotnet-sdk

PS. I hope that the `6.0.102` images have not been overridden.

**Comment by mthalman** [comment]
This is on the way: https://github.com/dotnet/dotnet-docker/issues/3493. It'll be included in today's release. Sorry for the delay.

**Comment by pellared** [comment]
Closing as duplicate

**Comment by mthalman** [comment]
6.0.200 SDK images are now published
