### ISSUE TITLE
Issues when building WINDOWS CONTAINERS with Docker MULTI-STAGE

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/dotnet-docker#352]
We evolved [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) to use  Docker MULTI-STAGE in our dockerfiles.
**It works properly when deploying the ASP.NET Core containers into LINUX Containers**.

However, we're getting **random errors when building the containers and targeting WINDOWS CONTAINERS**.

Specifically, the random issues/errors appear when building a container that includes an SPA app (Single Page Application with code using NPM needed for building Angular and TypeScript code).
Looks like the issues are related to paths, but the errors are random. You might get this BUG it in different moments or build steps and not every time you build.

The following is our experience and pain-points:

## Steps to reproduce the issue

1. Clone eShopOnContainers from https://github.com/dotnet-architecture/eShopOnContainers.git

2. In Windows 10 with Docker for Windows installed, switch to Windows containers in case you were using Linux containers, which is the by-default state. 

3. In CMD or PowerShell, move to the root folder where you see the docker-compose files.

4. Build the SPA container with the following command: 
**docker-compose -f docker-compose-windows.yml build webspa** 

5. When the error happens (randomly) you might see something like this:
 
![image](https://user-images.githubusercontent.com/1712635/34007828-04f0e3fe-e0b8-11e7-8791-d1bd5d1dfeff.png)

6. You can execute again the same command **docker-compose -f docker-compose-windows.yml build webspa** to restart the process. It is faster now because the steps that already succeeded are cached. Normally the error happens again, in the same step or one after. After retrying several times, finally the image might complete building.

## Expected behavior
It should behave properly like when building with Linux Containers as target, with no errors at all.

## Actual behavior
You get the mentioned errors, randomly.

## Additional information (e.g. issue happens only occasionally)
As mentioned, the issue happens randomly, in different moments, but usually you will always get it and you need to re-build multiple times.

## Output of `docker version`
Not available right now, I'll update this info.
```
(paste your output here)
```

## Output of `docker info`
Not available right now, I'll update this info.
```
(paste your output here)
```

**Comment by richlander** [comment]
Have you tried MSB w/o compose? Do you still get the same issue? We should isolate the issue as much as possible.

**Comment by MichaelSimons** [comment]
Can you also describe what the Windows Docker Host environment is?

**Comment by CESARDELATORRE** [comment]
We have tested by using “Docker build” and the issue happens the same same way than when using Docker-compose build.
 
re-exec error: exit status 1: output: time="2017-12-15T11:59:55+01:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\a0b81ae5de4a0f0b2bd7801fa2e01bd78dd46c84623dc1f68bbe19849a410d54 flavour=1 folder=C:\WINDOWS\TEMP\hcs210282431"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\a0b81ae5de4a0f0b2bd7801fa2e01bd78dd46c84623dc1f68bbe19849a410d54 flavour=1 folder=C:\WINDOWS\TEMP\hcs210282431
 
Usually, the step where it is failing is the 
RUN npm run build:prod
But sometimes it also happens when running
RUN npm install

You ca see all the steps below.
 
FROM build AS publish
RUN npm rebuild node-sass
RUN npm install
RUN npm run build:prod
RUN dotnet publish -c Release -o /app

**Comment by MichaelSimons** [comment]
@CESARDELATORRE - please provide the `docker info` and `docker version` information for the environment this reproduces on.

**Comment by CESARDELATORRE** [comment]
Info about Docker environment: 
Docker version 17.09.1-ce, build 19e2cf6

**Comment by MichaelSimons** [comment]
@CESARDELATORRE - please run the `docker info` and `docker version` command on your Docker host machine and paste the information into this issue.  This is very important information necessary to diagnose the issue.

**Comment by CESARDELATORRE** [comment]
Here’s the info about the environment:

C:\WINDOWS\System32>docker version
Client:
Version: 17.09.1-ce
API version: 1.32
Go version: go1.8.3
Git commit: 19e2cf6
Built: Thu Dec 7 22:22:26 2017
OS/Arch: windows/amd64
 
Server:
Version: 17.09.1-ce
API version: 1.32 (minimum version 1.24)
Go version: go1.8.3
Git commit: 19e2cf6
Built: Thu Dec 7 22:32:40 2017
OS/Arch: windows/amd64
Experimental: true

————
 
C:\WINDOWS\System32>docker info
Containers: 4
Running: 1
Paused: 0
Stopped: 3
Images: 22
Server Version: 17.09.1-ce
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: ics l2bridge l2tunnel nat null overlay transparent
Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.88GiB
Name: DESKTOP-V1VLQ15
ID: I6JF:V7XG:UJEN:634U:74H3:3SMY:UFM4:IJ3C:2CFR:THPZ:5CWM:APT2
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: -1
Goroutines: 41
System Time: 2017-12-18T09:47:28.8451143+01:00
EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**Comment by CESARDELATORRE** [comment]
Doing further tests.
Afaik, just 2 of the services in the solution (MVC app and SPA app) fail when building the Windows Container image. The rest of the images (regular Web API services) appear to build properly.
On the other hand, ALL of them build and work properly if building LINUX containers.

In order to just try to build the SPA image, run:
`docker-compose -f docker-compose-windows.yml build webspa`

I get this error (Although looks kind of ramdom, sometimes it worked..):
```
ERROR: Service 'webspa' failed to build: re-exec error: exit status 1: output: time="2018-01-05T09:44:20-08:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\edcd14474a98d3dd39f7df35e95f80e34f390a1db4429f4925d04d4635f6cc75 flavour=1 folder=C:\Windows\TEMP\hcs388882919"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\edcd14474a98d3dd39f7df35e95f80e34f390a1db4429f4925d04d4635f6cc75 flavour=1 folder=C:\Windows\TEMP\hcs388882919
```

**In order to just try to build the MVC image, run:**
`docker-compose -f docker-compose-windows.yml build webmvc`

I get this error:
```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
ERROR: Service 'webmvc' failed to build: The command 'cmd /S /C dotnet build --no-restore -c Release -o /app' returned a non-zero code: 1
```

**Environment:**

C:\> **docker version**
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:32:40 2017
 OS/Arch:      windows/amd64
 Experimental: true

 C:\> **docker info**
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 95
Server Version: 17.09.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.97GiB
Name: SURFACESTUDIO
ID: FPAE:QNTQ:ME45:LROO:UTPZ:U5CY:MRC6:CHKM:BXIJ:7UTT:JF7D:B5LC
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 25
 System Time: 2018-01-05T10:09:19.0525069-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by richlander** [comment]
FYI: For those watching, the underlying issue is a Windows Container issue. A fix is in progress. No ETA yet.

**Comment by MichaelSimons** [comment]
Got confirmation that the underlying issue is a Windows Container issue.  Closing as there is nothing to fix in microsoft/dotnet.

**Comment by CESARDELATORRE** [comment]
@MichaelSimons Do you know the issue from the Windows team so we can link to it?

**Comment by MichaelSimons** [comment]
https://github.com/moby/moby/issues/32838
