### ISSUE TITLE
Remove workaround for Mariner ARM container images not setting architecture variant metadata

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3520]
Tracking issue for https://microsoft.visualstudio.com/OS/_workitems/edit/38266794

**Comment by mthalman** [comment]
Apparently the variant metadata is now set: https://github.com/microsoft/CBL-Mariner/issues/4856

This should allow us to remove the workaround from https://github.com/dotnet/dotnet-docker/blob/f68950a9244e5c24b68ab3826a0378d3678a92f2/eng/pipelines/steps/set-imagebuilder-build-args-var.yml

**Comment by lbussell** [comment]
Fixed by https://github.com/dotnet/dotnet-docker/pull/5726
