### ISSUE TITLE
.NET 7 Images are not all tagged as Preview

### ISSUE THREAD

**Issue by busches** [dotnet/dotnet-docker#3531]
### Describe the Bug

Currently the .NET 7 docker images are not all labeled as previews, causing tools like [Renovate](https://github.com/renovatebot/renovate/pull/14477), etc. to suggest upgrading from .NET 6 to 7, even though it's not yet released.

Sample tags from: https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
```
    "7.0",
    "7.0-alpine",
    "7.0-alpine-amd64",
    "7.0-alpine-arm32v7",
    "7.0-alpine-arm64v8",
    "7.0-alpine3.15",
    "7.0-alpine3.15-amd64",
    "7.0-alpine3.15-arm32v7",
    "7.0-alpine3.15-arm64v8",
    "7.0-bullseye-slim",
    "7.0-bullseye-slim-amd64",
    "7.0-bullseye-slim-arm32v7",
    "7.0-bullseye-slim-arm64v8",
    "7.0-cbl-mariner1.0",
    "7.0-cbl-mariner1.0-amd64",
    "7.0-focal",
    "7.0-focal-amd64",
    "7.0-focal-arm32v7",
    "7.0-focal-arm64v8",
    "7.0-nanoserver-1809",
    "7.0-nanoserver-ltsc2022",
    "7.0-windowsservercore-ltsc2019",
    "7.0-windowsservercore-ltsc2022",
    "7.0.100-preview.1",
    "7.0.100-preview.1-alpine3.15",
    "7.0.100-preview.1-alpine3.15-amd64",
    "7.0.100-preview.1-alpine3.15-arm32v7",
    "7.0.100-preview.1-alpine3.15-arm64v8",
    "7.0.100-preview.1-bullseye-slim",
    "7.0.100-preview.1-bullseye-slim-amd64",
    "7.0.100-preview.1-bullseye-slim-arm32v7",
    "7.0.100-preview.1-bullseye-slim-arm64v8",
    "7.0.100-preview.1-cbl-mariner1.0",
    "7.0.100-preview.1-cbl-mariner1.0-amd64",
    "7.0.100-preview.1-focal",
    "7.0.100-preview.1-focal-amd64",
    "7.0.100-preview.1-focal-arm32v7",
    "7.0.100-preview.1-focal-arm64v8",
    "7.0.100-preview.1-nanoserver-1809",
    "7.0.100-preview.1-nanoserver-ltsc2022",
    "7.0.100-preview.1-windowsservercore-ltsc2019",
    "7.0.100-preview.1-windowsservercore-ltsc2022",
```

Only the `7.0.100` specific tags are marked as `-preview` instead of all the `7.0` tags. The suggestion is that all preview docker images, contain the preview tag or alternatively do not exist until ready. We noticed the same issue when .NET 6 went into preview as well.

**Comment by mthalman** [comment]
[Triage] We'll take this under consideration.

The current tagging scheme was seen as a feature allowing people to move to preview versions when they're ready and remain using that tag once the version is released.

**Comment by mthalman** [comment]
[Triage]
We'd like to get community feedback on this issue. If this is something that you'd like to address, please post a comment stating your scenario. We'll gather that feedback and make a determination on how to proceed. We'll leave this open for 1 month to gather feedback.

**Comment by JamieMagee** [comment]
Is there expected to be manual work required from developers in moving from one preview release to another? If so, a mutable tag `7.0` would silently break builds.

**Comment by busches** [comment]
@JamieMagee Not sure I understand what you're asking. Are you saying right now `7.0` points to `7.0.100-preview.1` and when `7.0.200-preview.1` comes out, you'd want `7.0` to point to that too? I don't want that to change, I'd simply want the `7.0` tag to change to `7.0-preview` until it's stable and the `7.0` that points to preview images, would be removed. The `7.0-preview` tag would continue to point to images that match.

The fact that `7.0` points only to `-preview` releases is what's confusing.

Using Go as an example, 1.18 is in RC right now, they don't have a plain `1.18` tag yet, they only have `1.18-rc`. Once it's released, then we'll have `1.18` created. https://hub.docker.com/_/golang?tab=tags&page=1&name=1.18

**Comment by JamieMagee** [comment]
@busches I think we're talking about the same thing, but I want to clarify just to be clear.

Currently `7.0` points to `7.0.100-preview.1`. Later it will point to `7.0.100-preview.2`. Is there expected to be manual upgrade steps required (AKA code changes) in moving from `preview.1` to `preview.2` (or to any later preview).

I am in agreement that the `7.0` tags that don't contain `preview.1` are confusing, for both automation and end users, and I think the Go images support that.

**Comment by busches** [comment]
@JamieMagee I would expect a replacement of `7.0-preview` to point to all future preview images of the `7.0` line. To answer question, no, staying on `7.0-preview` means you'd auto move to the next preview, assuming it was still for `7.0`.

**Comment by busches** [comment]
@mthalman there doesn't seem to be a lot of input here, what do you guys plan to do?

**Comment by mthalman** [comment]
> @mthalman there doesn't seem to be a lot of input here, what do you guys plan to do?

Undetermined at this point. We'll discuss at our next review meeting.

**Comment by mthalman** [comment]
This will be applied for .NET 8. See my comment at https://github.com/dotnet/dotnet-docker/issues/4117#issuecomment-1319263170.
