### ISSUE TITLE
Create dotnet 3.1 alpine arm64 sdk image please

### ISSUE THREAD

**Issue by ecs-jnguyen** [dotnet/dotnet-docker#3538]
### Describe the Problem

I am trying to build and run dotnet 3.1 with arm64 on alpine. I see that the [aspnet](https://hub.docker.com/_/microsoft-dotnet-aspnet/) and [runtime](https://hub.docker.com/_/microsoft-dotnet-runtime/) have the `3.1-alpine-arm64v8`, however the [sdk](https://hub.docker.com/_/microsoft-dotnet-sdk/) does not have the `3.1-alpine-arm64v8` taag

### Describe the Solution

Could I request for a sdk 3.1-alpine-arm64v8 image to be made available please?

**Comment by ecs-jnguyen** [comment]
Ok thank you for the quick response!

So just to clarify, I should build my image with ubuntu or debian arm64 image. Then in the next stage I use the 3.1 alpine arm64 image and copy the binaries over.

Is that correct?

**Comment by MichaelSimons** [comment]
> So just to clarify, I should build my image with ubuntu or debian arm64 image. Then in the next stage I use the 3.1 alpine arm64 image and copy the binaries over.
> 
> Is that correct?

Yes, sorry I wasn't more explicit earlier.
