### ISSUE TITLE
How to build .net6 image on Buster(Debian 10) OS?

### ISSUE THREAD

**Issue by iioter** [dotnet/dotnet-docker#3569]
i use raspberry pi 4,the os info is:
 $ cat /etc/debian_version
10.6
 $ lsb_release  -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster。
I can't find base image for my pi,where is the tag that name is '6.0.201-buster-slim-arm32v7'? Debian 10（arm32v7）

**Comment by iioter** [comment]
i find this issue #3253 .
i can't build .net6 docker image on raspberry pi4(arm32),
when is use mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7 AS base,
mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-arm32v7 AS build,
when run dotnet restore xx.csproj
it console an error 'Aborted (core dumped) The command '/bin/sh -c dotnet restore "xx.csproj"' returned'

**Comment by iioter** [comment]
How to build .net6 image on Buster(Debian 10) OS?

**Comment by mthalman** [comment]
Per the [platform support policy](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md#linux), .NET 6 container images for Debian 10 (Buster) were not provided. They are only available for Debian 11 (Bullseye). You should be able to work around the issue with this container image running on a Raspberry Pi by following the guidance at https://github.com/dotnet/dotnet-docker/issues/3253#issuecomment-956378676.

If you must have .NET 6 with Debian 10, you can follow the [instructions for installing .NET yourself](https://docs.microsoft.com/dotnet/core/install/linux-debian#debian-10-).
