### ISSUE TITLE
Certificate Error when pulling image from mcr.microsoft.com

### ISSUE THREAD

**Issue by baoduy** [dotnet/dotnet-docker#3579]
I got the below error today when pulling the image from mcr.microsoft.com. Please help if anyone knows how to fix the issue.

error pulling image configuration: Get "[https://mcr.microsoft.com/v2/dotnet/sdk/blobs/sha256:95b59e93f9687b9fb7f552ea78809fcf8c03f7b86826ffc2e321862acfbe7b79"] 
(https://mcr.microsoft.com/v2/dotnet/sdk/blobs/sha256:95b59e93f9687b9fb7f552ea78809fcf8c03f7b86826ffc2e321862acfbe7b79%22): x509: certificate is valid for *.azureedge.net, *.media.microsoftstream.com, *.origin.mediaservices.windows.net, *.streaming.mediaservices.windows.net, not mcr.microsoft.com

Thanks
Steven

**Comment by mthalman** [comment]
This isn't specific to the .NET container images but rather to the container registry service itself. Please log an issue at https://github.com/microsoft/containerregistry/.
