### ISSUE TITLE
'Could not find Windows Runtime type 'Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher'.'

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#358]
_Copied from https://github.com/Microsoft/dotnet-framework-docker/issues/77 by @summoncse_

I have created one .Net Core Console App for reading Bluetooth messages and i have referenced Widows.winmd for using BluetoothLEAdvertisementWatcher (Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher). I am getting this "System.TypeLoadException: Could not find Windows Runtime type 'Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher'" error while running docker container.

Dockerfile:

FROM microsoft/dotnet:2.0-runtime-nanoserver-1709 AS base
WORKDIR /app

FROM microsoft/dotnet:2.0-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY *.sln ./
COPY ConsoleApp1/ConsoleApp1.csproj ConsoleApp1/
RUN dotnet restore
COPY . .
WORKDIR /src/ConsoleApp1
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]

Here is look like my csproj -

Exe netcoreapp2.0 ..\..\..\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd true

**Comment by MichaelSimons** [comment]
@summoncse, I am skeptical that the issue you are seeing is related to Nano Server.  Nano Server is a slimmed down Windows SKU so it won't have all the functionality your traditional Windows SKUs have.  I don't see `Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd` on Nano Server.  I'm not sure how your build steps are passing without this.  Have you tried building a Windows Server Core based image to see if that works?  You would have to install .NET Core yourself but that is pretty simple.  You should be able to copy this [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/2.0/sdk/nanoserver-sac2016/amd64/Dockerfile) and change the base image as appropriate.

**Comment by summoncse** [comment]
@MichaelSimons, You are right docker build did not pass i have run "dotnet publish -c Realease -r win10-x86" and docker build from publish folder it passed but i am getting error while running container. 

Dockerfile: 
FROM microsoft/windowsservercore
WORKDIR /app
COPY . ./
ENTRYPOINT ConsoleApp1.exe

Docker build result: 
PS C:\Temp\UwpClassLibrary\ConsoleApp1\bin\Realease\netcoreapp2.0\win10-x86\publish> docker build -t consoleble .
Sending build context to Docker daemon  60.74MB
Step 1/4 : FROM microsoft/windowsservercore
 ---> db8182d67b6c
Step 2/4 : WORKDIR /app
 ---> Using cache
 ---> 72ad458b28d3
Step 3/4 : COPY . ./
 ---> d87225a29b50
Step 4/4 : ENTRYPOINT ConsoleApp1.exe
 ---> Running in a96daa3f030f
Removing intermediate container a96daa3f030f
 ---> a6f3d8500e20
Successfully built a6f3d8500e20
Successfully tagged consoleble:latest

Error:
PS C:\Temp\UwpClassLibrary\ConsoleApp1\bin\Realease\netcoreapp2.0\win10-x86\publish> docker run consoleble

Unhandled Exception: System.TypeLoadException: Could not find Windows Runtime type 'Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher'.
   at ConsoleApp1.Program.Main(String[] args)

**Comment by MichaelSimons** [comment]
@summoncse - Taking a step back can you explain what type of app you are building?  From your comments, I assume it is a UWP app - `PS C:\Temp\UwpClassLibrary\ConsoleApp1\bin\Realease\netcoreapp2.0\win10-x64\publish> docker build -t consoleble`.  Can you explain what it does?  I would like to understand the scenario in which it makes sense to run an app that is using BluetoothLEAdvertisementWatcher within a Nano Server container.  Given the bare bones nature of Nano Server, I question whether what you are trying to do is possible.

**Comment by summoncse** [comment]
@MichaelSimons - I have created .Net Core Console Application for reading Bluetooth Low Energy (BLE) message I have used BluetoothLEAdvertisementWatcher class from UWP because .Net Core does not have api for reading BLE message. 

You can have my code from https://github.com/summoncse/DockerExample/tree/master/UwpClassLibrary

**Comment by MichaelSimons** [comment]
@summoncse - Can you explain why you are trying to run this Bluetooth Console App within a Container based on Nano Server?  Nano Server isn't going to support this.  Regarding the issue of .NET Core not having an API for reading BLE messages - this is an issue for https://github.com/dotnet/corefx.  I would suggest you log an issue in CoreFX specific to the BLE api.

**Comment by summoncse** [comment]
@MichaelSimons - You are right but I need to develop a console application for reading BLE message and create image for docker. question is how can i do that ??

**Comment by MichaelSimons** [comment]
@summoncse - I still don't understanding the scenario for reading BLE messages within a container environment.  Are you deploying this to run in a server environment?

**Comment by summoncse** [comment]
@MichaelSimons - i don't deploy in server environment, i will deploy in Azure IotEdge as a module, it will receive BLE message from Iot device.

**Comment by MichaelSimons** [comment]
@summoncse - I think your best course of action is to follow up with CoreFx on how to read BLE messages and if it is not supported to get support for it.  Once you can do this on a Nano Server SKU then containerizing it should be easy.

**Comment by summoncse** [comment]
@MichaelSimons - CoreFx  does not have api for BLE but UWP has how can i dockerize UWP app ??

**Comment by MichaelSimons** [comment]
@summoncse - UWP apps are not intended to be run in a container.  Containers do not support UI components.

**Comment by summoncse** [comment]
@MichaelSimons - CoreFx does not have api for BLE, Windows Server Core (https://msdn.microsoft.com/en-us/library/mt844528(v=vs.85).aspx) and Nano Server (https://msdn.microsoft.com/en-us/library/mt588480(v=vs.85).aspx) also does not have Bluetooth api, I can not use UWP references  so, how can i do can you please give me solution.

**Comment by summoncse** [comment]
@ddobric

**Comment by MichaelSimons** [comment]
@summoncse - Per my previous comment - please follow up with CoreFX on getting the proper BLE API support.  Closing as there is nothing that can be done in with the microsoft/dotnet images until CoreFX has support for this scenario.
