### ISSUE TITLE
Please support PowerShell core on SDK images

### ISSUE THREAD

**Issue by AceHack** [dotnet/dotnet-docker#360]
Please add powershell core on both linux and windows SDK images

**Comment by AceHack** [comment]
Please also make this the default cmd handler in the image

**Comment by MichaelSimons** [comment]
We would like to hear more requests from the community on this before making a change.  Making the Powershell the default `SHELL` would not be something we would consider as we feel it is not what the Linux community would expect.

**Comment by AceHack** [comment]
Would it be possible to create an alternative tag/image that has PowerShell as the default?  This would make it so I would not have to create my own base image for all my apps that does the same.  Thanks.

**Comment by MichaelSimons** [comment]
If there is a strong demand for such images then it would be something we would consider.  In general we try to limit the number of images permutations as deciphering the differences between all of the images can be difficult.

**Comment by AceHack** [comment]
Just to give a little context, I use PowerShell so I can create one Dockerfile that works on both Windows and Linux containers even though in many cases the builds are complicated and require scripting.  Before I had to maintain two different Dockerfiles and script the same actions in two different languages.  Thanks.

**Comment by richlander** [comment]
Assume we did add powershell to our SDK images. Why would you need the default shell to be powershell in the dotnet images to enable your scenario?

**Comment by AceHack** [comment]
Because on Windows the executable name is powershell and on Linux it’s pwsh.  So at a minimum I would have to have two base images that set the default she'll accordingly and then the multiarch tag.  Then all my services would need to reference the multiarch tag.

**Comment by richlander** [comment]
I can see how that would be nice, but it's well within your capability to solve. It's not so challenging that it's worth us creating a whole series of additional images to update. We'd have to create ~20 new images to make that work.

**Comment by AceHack** [comment]
If you add powershell to the base images for the sdk but don't make it the default could you run the following

#!/bin/bash
ln -s /usr/bin/pwsh /usr/bin/powershell

This is alias pwsh as powershell and I should be able to set the default myself in a way that would work on both OSs in a single docker file.

Thanks.

**Comment by richlander** [comment]
That may be a middle ground.

First, we need more requests to add powershell. This request is the first one I am aware of.

**Comment by itz1508** [comment]
Same request to add powershell :)
________________________________

**Comment by yuhuazhong** [comment]
I second @AceHack on supporting powershell on Linux. It just enable a lot of possibility for development. It also help us make a stronger business case to adopt container technology in our company.

**Comment by kz1000fan** [comment]
Same here...this is a much-needed feature for consistency of experiences.

**Comment by ericrini** [comment]
I would like this feature to.

**Comment by tkring** [comment]
I vote for this feature.  It will help our company adopt AKS.

**Comment by AceHack** [comment]
@richlander looking at PowerShell core 6.1 it's even called pwsh when installed on windows nanoserver-1709 so just including it would be great!  Thanks.

**Comment by richlander** [comment]
Anyone know how big it is once installed?

**Comment by AceHack** [comment]
I'm working on creating a base image myself for nanoserver-1709 and stretch, I'll send the link once I'm done.

**Comment by richlander** [comment]
Please do send the link. I'm most interested in what docker history says, so please (for now) add powshell by itself so that it creates a distinct layer.

**Comment by AceHack** [comment]
@richlander I have not made the multi-arch tag yet, I'll do that tomorrow but here it is on docker hub.
https://hub.docker.com/r/acehack/dotnet/tags/

Also here are the source Dockerfiles.
https://github.com/AceHack/dotnet-docker-powershell

**Comment by MichaelSimons** [comment]
Adding the following to https://github.com/dotnet/dotnet-docker-nightly/blob/master/2.1/sdk/stretch/amd64/Dockerfile results in a layer that is 114 MB.

```
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list' \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        powershell=6.0.0-1.debian.9 \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by sonalgpatil** [comment]
I would like this feature too.

**Comment by t-sup** [comment]
I would like this feature too.

**Comment by AceHack** [comment]
@MichaelSimons you could further reduce the size by removing the .NET core version that comes bundled with PowerShell.  I've requested the PS team makes this a first class scenario.
https://github.com/PowerShell/PowerShell/issues/6058#issuecomment-361179216

**Comment by scottcollins** [comment]
I would also like this feature

**Comment by stdistef** [comment]
I would like this feature too

**Comment by kalenwatermeyer** [comment]
Please add this feature

**Comment by huesie** [comment]
+1 for x-plat targeting - please add this

**Comment by richlander** [comment]
We are happy to do this, with one caveat, per https://github.com/PowerShell/PowerShell/issues/6058#issuecomment-377623781

**Comment by jbogard** [comment]
I originally requested Powershell but really Powershell Core is what I'd like https://github.com/aspnet/aspnet-docker/issues/362. All of my build images have some form of PS, and installing PS on a nanoserver image in any form really is pretty painful to figure out.

**Comment by sandersaares** [comment]
I would like this but would prefer *not* having it as the default handler. PowerShell seems to be quite unpredictable in many commandline interop cases and should always be explicitly called when needed.

**Comment by willwhite1** [comment]
I would like this too

**Comment by KyleGobel** [comment]
I can't tell what this is a request for, there's been a couple things mentioned.
    1.  Powershell as the default shell in the images
    2.  A Powershell default shell alternative image.
    3.  Powershell installed in the image but not the default shell 
    4.  Powershell 'supported'?  (I don't know what this means, can't you just install it?)

Number 2 would be cool, but not if it takes any considerable time for dotnet team to maintain.

I could be missing something, but isn't this a pretty easy one for the community to pick up and publish an image like @AceHack did, or even your own company so you fully control what's in your base image which I imagine most companies would prefer anyway?

**Comment by sandersaares** [comment]
Writing scripts is a basic need. You need scripts everywhere.

Without PowerShell Core, you are limited to platform-native scripts (CMD or Bash) which can maybe work for some but not for all. Especially bad if you want to write a multiplatform app but then are forced to duplicate your scripts in two languages - with PowerShell, you could just use a single universal PowerShell script.

So I would view this not as a request to support PowerShell in some specific way but to support running PowerShell scripts in images. The exact form how that happens is not so important. For me, simple low-maintenance low-effort approaches (both from image author and image user perspective) would be preferred - just chucking `pwsh` in `%PATH%` would be ideal.

**Comment by richlander** [comment]
We're hoping that we'll be able to support pwsh in the SDK images when we ship the 2.1.400 version of the SDK. The CLI team needs to enable a custom executable launcher for pwsh (needs to be signed by Microsoft). Once that is done, the PowerShell team will be able to package pwsh as a .NET Core tool and we'll be able to add it to the SDK image.

**Comment by AceHack** [comment]
have PowerShell as .NET global tool is a cool idea

**Comment by damianpowell** [comment]
+1 for adding PowerShell Core to the SDK images.

**Comment by damianpowell** [comment]
Actually, on reflection, it's helpful to have `pwsh` available in the runtime images too. Take the example of the entrypoint script from the [Quickstart: Compose and ASP.NET Core with SQL Server](https://docs.docker.com/compose/aspnet-mssql-compose/) sample. The obvious alternative of that bash script is to use PowerShell instead - a batch file version would be doable, but pretty horrible.

    $ErrorActionPreference = "Stop"
    while ($true) {
        Write-Host "SQL Server is starting up"
        dotnet ef database update
        if ($?) {
            break
        }
        Sleep -Seconds 1
    }
    Write-host "SQL Server is running - executing command"
    dotnet run --server.urls http://*:80

**Comment by achrjulien** [comment]
We are also missing the ability to use our .ps1 scripts here

**Comment by panmanphil** [comment]
also here, would love an option to use powershell instead of cmd as default, mostly for downloading, unpacking and installs, but also for init scripts that would have to pull in configuration that sort of thing to setup the application

**Comment by yamac-kurtulus** [comment]
Are people even using cmd?

**Comment by fabioimpe** [comment]
Is there any chance to use powershell inside the dotnet image? At least for the sdk version, thank you.

**Comment by achrjulien** [comment]
@fabioimpe On our side, we moved everything to Python and stopped using powershell. It makes life much easier, even though we had to re-write our scripts

**Comment by sandersaares** [comment]
Ouch. I can understand the pain, though - if you can't use Microsoft's scripting language in Microsoft's latest images then what's the point. Developers should never have to pay some tax to use such things together.

**Comment by gauravagarwal28** [comment]
I want this feature too,,,

**Comment by ryanrust** [comment]
Same here, I'd really like Powershell in the SDK images.

**Comment by terrip-mpls** [comment]
The title of this issue is: "Please support PowerShell core on SDK images". I am relatively new to docker so perhaps I don't understand the request but this is how I interpret the request:

When I spin up a docker container from the microsoft/dotnet:2.2-sdk docker image, I want to be able to run powershell scripts from within the container without having to install powershell. In other words, powershell is available as a first class shell in the container and all I have to do to run it is to type powershell on the CMD shell that is presented to me when the container starts.

If my interpretation is correct then I don't understand the request because I have a microsoft/dotnet:2.2-sdk image in my docker cache that I pulled from dockerhub on Dec. 11, 2018 that has powershell core installed in it.

I run Windows 10 and am running the 18.09.1 Community version of both docker server and client. In order to run an interactive container from the aforementioned image, I open a powershell command window with Administrator rights and issue the following command:

docker run -it --rm microsoft/dotnet:2.2-sdk

Once the container starts up (seems to take about 20 seconds) I issue the 'echo %PATH%' command and get this displayed on my console:

C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet;C:\Users\ContainerAdministrator\.dotnet\tools

(Note the presence of C:\Windows\System32\WindowsPowerShell\v1.0 in the path.)

If I then issue the powershell command I'm dropped into a powershell shell. I then issue the $PSVersionTable command from within that powershell shell and I get this output:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1000
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
BuildVersion                   10.0.14393.1000
CLRVersion

It sure looks to me like Powershell Core is installed in my container.

So what am I missing? In other words, why isn't this issue closed?

**Comment by MichaelSimons** [comment]
@terrip-mpls - This issue is about making PowerShell available in **all** of the SDK images.  Currently PowerShell is only available in the nanoserver-sac2016 flavors because it is included with Nano Server.  In the newer versions of Nano Server, PowerShell was removed.  PowerShell is not included in any of the Linux images today.

**Comment by yamac-kurtulus** [comment]
I still don't get it. Are we going to have to build the image from scratch now if we want to use Powershell?

**Comment by MichaelSimons** [comment]
@yamac-kurtulus - if you want to use PowerShell today within one of the microsoft/dotnet images that doesn't already include it, you would have to define a Dockerfile based on the microsoft/dotnet image you want and simply add PowerShell.  You can use the existing [PowerShell Dockerfiles](https://github.com/PowerShell/PowerShell-Docker/tree/master/release/stable) as a guide for how to do this.  Alternatively you can start with one of the PowerShell images and add .NET Core on top of it.

**Comment by richlander** [comment]
We are getting closer to adding PowerShell to the .NET Core SDK image. We have landed on the following scenarios as the primary motivations. It would be great to hear if folks have other use cases that you are considering.

* Write .NET Core application Dockerfiles with PowerShell syntax for any OS.
* Write .NET Core application/library build logic that can be easily containerized. Example: `docker run -it -v c:\myrepo:/myrepo -w /myrepo microsoft/dotnet:3.0-sdk build.ps`

**Comment by sandersaares** [comment]
I have the following use case:

* Before executing main executable, PowerShell script generates its configuration based on the runtime environment (e.g. what directories have been mounted into the container) and performs other adjustments that can only be done at runtime (e.g. creating symlinks to mounted things).

**Comment by Huesie** [comment]
Thanks for the follow-up, Rich, but it's no longer a requirement for teams I work with, viz: we migrated to *Python* scripts for everything.

PowerShell/core is just too poorly supported - e.g. in VSTS tasks; other images; and elsewhere.  I understand many MSFT teams came to same conclusion, e.g. "az cli" is Python+ other x-plat tools are too.

I still use PowerShell locally (great xml+json+collection etc. handing), but Python is liberating with near-perfect cross-platform support + "DreamPie" IDE/multi-line REPL is fast to develop too.

**Comment by jbogard** [comment]
We use it to install dependencies similar to brew/apt-get, since running
MSIs is not really feasible inside a container.

**Comment by yamac-kurtulus** [comment]
Some companies are reluctant to Linux and prefer Windows although they want to use Docker. They want to use Windows images as well. CMD is a terrible scripting environment, not to mention the lack of MSI support, which is required many many many useful applications. 

My use case, for instance, is to be able to run integration tests using a powershell script inside the container.

**Comment by MichaelSimons** [comment]
If you could, please include what SDK container OS is targeted (e.g. nanoserver, debian, etc) when specifying scenarios per @richlander's request.

**Comment by MichaelSimons** [comment]
Closing as PowerShell Core is now included in the latest 3.0 preview release.  See [this announcement](#1069) for more details.

**Comment by AceHack** [comment]
@MichaelSimons Your link is not working

**Comment by MichaelSimons** [comment]
@AceHack - link updated - thanks

**Comment by amirtharaj1102** [comment]
dotnet global tools solve this problem.

FROM mcr.microsoft.com/dotnet/core/sdk:2.2
USER ContainerAdministrator
WORKDIR /app
COPY ["sample/PowershellScript.ps1"," ."]
RUN dotnet tool install --global PowerShell
RUN setx /M PATH "%PATH%;C:\Users\ContainerUser\.dotnet\tools"
ENTRYPOINT ["C:\\Users\\ContainerAdministrator\\.dotnet\\tools\\pwsh.exe", "C:\\app\\PowershellScript.ps1"]

but image gets bulky after this
