### ISSUE TITLE
command docker pull mcr.microsoft.com/dotnet/sdk:6.0 throwing error

### ISSUE THREAD

**Issue by Abhinav1598** [dotnet/dotnet-docker#3750]
Error response from daemon: error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: "<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>00w1yYgAAAADr+GZP0awtS6P+4e4EaPC0TUFBMDJFREdFMDMxMQBFZGdl"

I am using openFaas to create a dotnet function, in the dockerfile pull for sdk:3.1 and runtime:3.1 is there and I am getting the above error.
other images are getting pulled but Microsoft ones are failing.

**Comment by mthalman** [comment]
Closing as duplicate of https://github.com/microsoft/containerregistry/issues/112. Since this is an error from the container registry itself and not the container image, https://github.com/microsoft/containerregistry is the correct repository for this.
