### ISSUE TITLE
BaseUrlUpdater in update-dependencies tool incorrectly identifies dotnet-monitor base urls

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#3769]
The update-dependencies tool fails when it attempts to update dotnet-monitor versions that are not the same as the overall .NET versions (e.g. 6.1, 6.2). See example failing usage: https://dev.azure.com/dnceng/internal/_build/results?buildId=1769734&view=logs&j=00fa4588-b6b6-574f-ae82-807fb3798490&t=14e894eb-e4bd-5b2c-c189-a6aebe347da5

The issue is that the BaseUrlUpdater constructors the base urls by concatenating `baseUrl`, the docker filer version (e.g. 6.1), the branch. However, the dotnet-monitor urls are not of this format; they look like `baseUrl|6.1-monitor|nightly`. The updater is unable to find the calculated key in the manifest variables dictionary and throws an NRE when it calls ToString on the result.

The same cause is also a separate issue for dotnet-monitor 7.0, where it calculates `baseUrl|7.0|nightly`, but that is not the expected variable for dotnet-monitor, and may cause URL calculation problems if dotnet-monitor's baseUrls every diverge for the versions that happen to align with .NET.

**Comment by mthalman** [comment]
Fixed
