### ISSUE TITLE
Broken openssl dependency for powershell in 6.0 x64 sdk

### ISSUE THREAD

**Issue by Feandil** [dotnet/dotnet-docker#3777]
### Describe the Bug

Some libraries in the powershell version installed in 6.0.300-bullseye-slim-amd64 are pointing to versions of openssl that are not present in the image, leading to these libraries not being usable...

### Steps to Reproduce

- Start a container with e.g. `docker run --rm -ti mcr.microsoft.com/dotnet/sdk:6.0.300-bullseye-slim-amd64`. Following commands are within that container
- `ldd /usr/share/powershell/.store/powershell.linux.x64/7.2.3/powershell.linux.x64/7.2.3/tools/net6.0/any/runtimes/linux-x64/native/libpsrpclient.so`: part of the output contains `libssl.so.1.0.0 => not found`
- `find / -name libssl.so.\*`: the version installed is `/usr/lib/x86_64-linux-gnu/libssl.so.1.1`

### Other Information

Looking at the PSWSMan module content, it seems that the version installed in mcr.microsoft.com/dotnet/sdk:6.0.300-bullseye-slim-amd64 is similar to what can be found under glibc-1.0 while the version under glibc-1.1 seems to be compatible

### Output of `docker version`
```
Client:
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        aa7e414fdc
 Built:             Sat May 14 12:48:33 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       f756502055
  Built:            Sat May 14 12:47:27 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.5.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 22
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.17.7-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.45GiB
 Name: lerya-bis
 ID: FPST:5DXX:DA23:S6PG:HTRF:IDHT:M2ZY:QU3T:7F7R:FMYU:DWKW:WOTA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
> ...are pointing to versions of openssl that are not present in the image, leading to these libraries not being usable...

Can you give repro steps that demonstrate how things are not usable?

cc @adityapatwardhan

**Comment by Feandil** [comment]
@mthalman as mentioned in the repro steps, a simple `ldd` on the installed library will show you that anything that will try to load it will fail.

Now withing powershell, AFAIU you'll need to use a cmdlet that use that functionality, that's the case with e.g. `Connect-ExchangeOnline -CertificateFilePath [....] -CertificatePassword [....] -AppId [....] -Organization [....]`:
- If I use the pwsh installed in the container, I get `Exception: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system`
- If I simply replace these libraries with the ones from the glibc-1.1 folder of the WSMan module (without installing WSMan), it works just fine.

Unfortunately, I don't know other cmdlet that rely on libmi or libpsrpclient, so I can't give you a simpler reproducer

**Comment by mthalman** [comment]
@adityapatwardhan - Can you investigate why PowerShell is tied to a specific version of libssl? .NET runtime has logic which interrogates the file system to find the newest available version. That seems like something PowerShell should be doing.

**Comment by adityapatwardhan** [comment]
@Feandil We are in the process of documenting that we are not supporting WSMan remoting on newer non-Windows distros.

Please comment on the issue here if your scenario needs WSMan remoting support. https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8930
