### ISSUE TITLE
Please add a arm32v6 image!

### ISSUE THREAD

**Issue by AnderssonPeter** [dotnet/dotnet-docker#378]
There currently are a few arm32v7 images but no arm32v6 images.
Raspberry pi zero w Uses a arm32v6 cpu, so please add support for arm32v6.

**Comment by MichaelSimons** [comment]
Pi Zero is not supported because ARMv6 does not have the instructions .NET needs. 
(https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md)
