### ISSUE TITLE
Distroless images for Mariner 2.0 contain unneeded cache directory

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3795]
Changes were made in the distroless Dockerfiles for Mariner 2.0 to [migrate from dnf to tdnf](https://github.com/dotnet/dotnet-docker/commit/6d0a8a38cfa6fe509b37699b6fc2dc11a162669f) when installing packages to the staging location.

However, the cleanup logic in the Dockerfile was not updated to account for this change. That was still attempting to delete a cache directory named "dnf":

```Dockerfile
# Clean up staging
RUN rm -rf /staging/etc/dnf \
    && rm -rf /staging/run/* \
    && rm -rf /staging/var/cache/dnf \
    && find /staging/var/log -type f -size +0 -delete
```

But the cache directory is now called tdnf. This causes the tdnf cache directory to not get deleted. This results in an extra 8.5 MB in the image that is not necessary.

**Comment by JamieMagee** [comment]
It looks like manpages are also being included under `/usr/share/man`. That adds another ½MB.

**Comment by JamieMagee** [comment]
And is rpmdb required? If not, it's taking up another ½MB under `/usr/lib/rpm`.

**Comment by JamieMagee** [comment]
I see it in the version I saved:

```
$ docker save mcr.microsoft.com/dotnet/runtime-deps:6.0-cbl-mariner2.0 -o dotnet-distroless.tar
$ tar xvf dotnet-distroless.tar
$ cd dotnet-distroless/c7956f89e801e95cba55526a229626d3f5786fa238b94f3a3fd7754c971dd36a
$ tar xvf layer.tar
$ ls usr/lib/rpm/
macros  platform  rpm.daily  rpm.log  rpm.supp  rpm2cpio.sh  rpmdb_dump  rpmdb_load  rpmpopt-4.17.0  rpmrc  tgpg
```

**Comment by mthalman** [comment]
> `$ docker save mcr.microsoft.com/dotnet/runtime-deps:6.0-cbl-mariner2.0 -o dotnet-distroless.tar`

That's the full Mariner image tag, not distroless. The distroless tag is `6.0-cbl-mariner2.0-distroless`.
