### ISSUE TITLE
Cannot run "Hello World" example from main website

### ISSUE THREAD

**Issue by erindru** [dotnet/dotnet-docker#38]
Hello,

I am trying to get started with .NET Core and though the Docker container would be great for providing me a consistent environment.

However, upon following the basic example described at https://dotnet.github.io/getting-started/#/docker , I get the following:

```
[erin@laptop ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree
[erin@laptop ~]$ docker --version
Docker version 1.11.1, build 5604cbe
[erin@laptop ~]$ docker pull microsoft/dotnet:latest
latest: Pulling from microsoft/dotnet
8b87079b7a06: Already exists 
a3ed95caeb02: Already exists 
1bb8eaf3d643: Already exists 
3e04171ce2e5: Already exists 
a5f69d4d0634: Already exists 
99b12dee501e: Already exists 
Digest: sha256:811023c416971e2107251dde64fa09af45cd1fd9490092e67a2739dd4dc9d633
Status: Image is up to date for microsoft/dotnet:latest
[erin@laptop ~]$ docker run -it --rm microsoft/dotnet:latest
root@2e10a62dc54b:/# mkdir hello_world && cd hello_world
root@2e10a62dc54b:/hello_world# dotnet new
Created new C# project in /hello_world.
root@2e10a62dc54b:/hello_world# dotnet restore
log  : Restoring packages for /hello_world/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 1201ms
error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002702)' for '.NETCoreApp,Version=v1.0'.
info : Committing restore...
log  : Writing lock file to disk. Path: /hello_world/project.lock.json
log  : /hello_world/project.json
log  : Restore failed in 2244ms.

Errors in /hello_world/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002702)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
root@2e10a62dc54b:/hello_world#
```

The main issue being:

```
Errors in /hello_world/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002702)' for '.NETCoreApp,Version=v1.0'.
```
How can I resolve this?

Thanks,
Erin

**Comment by janvorli** [comment]
@piotrpMSFT - this looks like the same issue I was hitting, only that this time, it is with the docker image and when using the way recommended in the Getting started with .NET guide ( https://dotnet.github.io/getting-started/#/docker)

@erindru could you please try to do the following?
`dotnet restore --source "https://dotnet.myget.org/F/dotnet-core"`
That helped me when I was hitting the same issue in a different context.

**Comment by xied75** [comment]
Any thing to do with the releasing of RC2?

**Comment by MichaelSimons** [comment]
This is a point in time issue.  Please refer to the [CLI known Issues](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md#resolving-the-standard-library-packages).  To summarize, for now you need to specify a custom NuGet.config until the RC2 packages are uploaded to nuget.org.

**Comment by MichaelSimons** [comment]
@erindru - the steps you tried before should work now.  The workaround I previously mentioned is no longer needed.  The rc2 packages have been uploaded to nuget.org.
