### ISSUE TITLE
Tag sizes

### ISSUE THREAD

**Issue by przemo098** [dotnet/dotnet-docker#3808]
Hello why I'm unable to see sizes of docker images which you create...
E.g. Python has the tags tab: https://hub.docker.com/_/python?tab=tags
Is there any reason or you don't know how to do this and someone manually creates tables in description ?
I understand that Microsoft hires people who understand algorithms and lives in caves, but please give this task for someone with DX (developer experience)

**Comment by mthalman** [comment]
[Triage] Closing per the previous comment.
