### ISSUE TITLE
CBL-Mariner SDK image should include tar

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3819]
CBL-Mariner 2.0 does not include the `tar` package. This is inconvenient in the SDK image where typical scenarios often involve downloading and extracting tarballs. Including this missing package in the SDK image would make it more convenient for consumers of the image as they wouldn't be forced to install it themselves. And it would put it more in alignment with the SDK images of other distros.

**Comment by eric-desrochers** [comment]
In short term, you can add ‘tar’ in your docker file, until we are finalizing a golden image that MSFT employee will be able to use.

**Comment by mthalman** [comment]
[Triage] Include an announcement to let Mariner users know that this change is coming and for which release.
