### ISSUE TITLE
Mutable distribution release Ubuntu and Debian tags

### ISSUE THREAD

**Issue by JamieMagee** [dotnet/dotnet-docker#3834]
### Describe the Problem

Currently there are .NET images published for 4 different Linux Distributions:

- Ubuntu
- Debian
- Alpine
- Mariner (Unsupported externally)

The tagging schema between them is a little inconsistent. For example, for Alpine and Mariner images there are tags that target a specific distribution release (`6.0-alpine3.15` and `6.0-cbl-mariner2.0`) and tags that don't (`6.0-alpine` and `6.0-cbl-mariner`). However, for Ubuntu and Debian based images there are only tags that target specific distribution releases (`6.0-focal`, `6.0-jammy`, and `6.0-bullseye-slim`).

### Describe the Solution

Create mutable distribution release Ubuntu and Debian tags. For .NET 6.0 that would be `6.0-ubuntu` and `6.0-debian` (or maybe `6.0-debian-slim`)

**Comment by richlander** [comment]
This is intentional.

Alpine is a rolling release and the others are LTS. We don't believe in roll-forward tags for LTS.

**Comment by JamieMagee** [comment]
Thanks for the explanation. Makes sense.

Though, I would like to clarify that Alpine isn't a rolling release. It does have releases (`3.14`, `3.15`, `3.16`, etc.) but they aren't supported for nearly as long as Ubuntu LTS releases (2 years vs 9 years). A rolling release is something like Arch Linux or Gentoo.
