### ISSUE TITLE
Alpine 3.16 icu-libs now contains only en. 

### ISSUE THREAD

**Issue by Belorus** [dotnet/dotnet-docker#3844]
Unit tests that run under SDK image (in our case) started to fail on culture-specific things.

In order to keep full compatibility with previous behavior (all locales) one should install also **icu-data-full** package.

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split

On the other side - alpine based runtime images don't contain icu and people always add this line manually, from that perspective it is a good idea to keep SDK with limited ICU to make sure people are aware of the ICU question.

This is probably more of a question. What is the right behavior for SDK in such situation?

**Comment by richlander** [comment]
I was reading the release notes.

> [nodejs](https://pkgs.alpinelinux.org/packages?name=nodejs&branch=edge&repo=&arch=x86_64&maintainer=) is now compiled with system ICU.

Is that "system ICU" the same as `icu-data-en` or that's a third variant? It doesn't address your question, but I'm curious. It also defines (I assume) what node developers get? Not that we need to make the same choice.

**Comment by richlander** [comment]
It seems that there are a few questions to answer:

1. Should we [update the SDK image](https://github.com/dotnet/dotnet-docker/blob/b53a5c4817768aa8864b4adc60b727cd85356628/src/sdk/6.0/alpine3.16/amd64/Dockerfile#L24) to maintain existing behavior? Seems like the answer should be "yes".
2. Should we update [runtime-deps](https://github.com/dotnet/dotnet-docker/blob/b53a5c4817768aa8864b4adc60b727cd85356628/src/runtime-deps/3.1/alpine3.16/amd64/Dockerfile) to include `icu-data-en` and then stop enabling globalization invariant mode. This one is less convincing but worth discussion.

**Comment by Belorus** [comment]
My 5 cents:

1 - Agree with you
2 - I believe current strategy (i'm none of a MSFT employee, so i can be completely wrong here) is to have slim docker runtime image without ICU and invariant mode enabled. And therefore runtime image doesn't contain any ICU stuff. Those who add it manually probably should now add **icu-data-full**  instead of current recommedacation of **icu-libs**. This probably implies update of documentation, github answers and all the places where dotnet + icu topic was raise

**Comment by spenceclark** [comment]
For me swapping **icu-libs** for **icu-data-full** didn't work as .net complained it couldn't find icu at all. 
So I added both and now I get the full set of locales again:

```
RUN apk add --no-cache icu-libs
RUN apk add --no-cache icu-data-full
```

**Comment by mthalman** [comment]
> I was reading the release notes.
> 
> > [nodejs](https://pkgs.alpinelinux.org/packages?name=nodejs&branch=edge&repo=&arch=x86_64&maintainer=) is now compiled with system ICU.
> 
> Is that "system ICU" the same as `icu-data-en` or that's a third variant? It doesn't address your question, but I'm curious. It also defines (I assume) what node developers get? Not that we need to make the same choice.

"System" in this instance seems to be `icu-libs`. Here's the output of installing `nodejs`:

```console
/ # apk add nodejs
(1/9) Installing ca-certificates (20211220-r0)
(2/9) Installing nghttp2-libs (1.47.0-r0)
(3/9) Installing brotli-libs (1.0.9-r6)
(4/9) Installing c-ares (1.18.1-r0)
(5/9) Installing libgcc (11.2.1_git20220219-r2)
(6/9) Installing icu-data-en (71.1-r2)
Executing icu-data-en-71.1-r2.post-install
*
* If you need ICU with non-English locales and legacy charset support, install
* package icu-data-full.
*
(7/9) Installing libstdc++ (11.2.1_git20220219-r2)
(8/9) Installing icu-libs (71.1-r2)
(9/9) Installing nodejs (16.15.0-r1)
Executing busybox-1.35.0-r13.trigger
Executing ca-certificates-20211220-r0.trigger
OK: 48 MiB in 23 packages
```

**Comment by richlander** [comment]
It's talks about "compiled". Are there different header files for the `-en` and `-full` versions?

**Comment by kaniini** [comment]
It is just the data files, installing `icu-data-full` along with `icu-libs` will work.

**Comment by mthalman** [comment]
[Triage] - We'll work on getting the `icu-data-full` package added into the sdk images for Alpine 3.16. Apologies for the break that occurred here.

**Comment by Belorus** [comment]
> [Triage] - We'll work on getting the `icu-data-full` package added into the sdk images for Alpine 3.16. Apologies for the break that occurred here.

Thanks, but seems the problem is a bit wider than SDK.

It probably makes sense to teach runtime to accept **icu-data-full** (not only "deprecated" **icu-libs**) to avoid situation when we need to install 2 packages where 2nd supercedes first one.

WDYT?

**Comment by mthalman** [comment]
> This is what i see if i only install new `icu-data-full`

Can you explain why your expectation is that it should work with just the `icu-data-full` package installed? It sounds like that's just the data package and [`icu-libs` is still required](https://github.com/dotnet/dotnet-docker/issues/3844#issuecomment-1156692024).

**Comment by Belorus** [comment]
> > This is what i see if i only install new `icu-data-full`
> 
> Can you explain why your expectation is that it should work with just the `icu-data-full` package installed? It sounds like that's just the data package and [`icu-libs` is still required](https://github.com/dotnet/dotnet-docker/issues/3844#issuecomment-1156692024).

Ah, you're right. I've compared contents of the packages, and got that **data** don't duplicate libs one.

I got a bit confused when noticed that "purged" log
![image](https://user-images.githubusercontent.com/1737207/173915758-36f9b281-a73f-4b80-8e01-357dcc290800.png)

Sorry for misleading comment. Seems with your fix we're good :)

**Comment by mthalman** [comment]
Updated sdk images have been published that now include `icu-data-full`.

**Comment by andtii** [comment]
@mthalman The examples how to enable globalization is wrong since its missing icu-data-full
 https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/Dockerfile.alpine-x64#L19

**Comment by dionisvl** [comment]
works for me:
`RUN apk add icu-dev icu-libs icu-data-full`

**Comment by shyameasternent** [comment]
> works for me: `RUN apk add icu-dev icu-libs icu-data-full`

Thanks @dionisvl  this helped me to add for docker instance.

**Comment by yisibl** [comment]
https://qiita.com/k-onoda/items/c0cd9d9d3576275346f0
