### ISSUE TITLE
Increase in CBL-Mariner 1.0 distroless image size

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3849]
The changes from https://github.com/dotnet/dotnet-docker/pull/3833 inadvertently changed the Mariner 1.0 distroless Dockerfile, causing the `dnf` cache directory to no longer be cleaned up. This caused an increase in the runtime-deps image size from 63 MB to 120 MB.

**Comment by richlander** [comment]
That's a healthy size increase!
