### ISSUE TITLE
Installing .NET through .DEB files instead of tarballs

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3865]
With CBL-Mariner, we took the approach of installing .NET by downloading the corresponding RPM files from blob storage and installing them locally. Having the packages being installed instead of extracting from tarballs allows for a seamless experience when downstream consumers end up installing .NET from the Mariner package repository either directly or through a transitive dependency. The package will be recognized as already installed. This avoid wasting time downloading the package and wasted disk space having a duplicate installation of .NET.

We should consider whether to apply this same pattern for DEB files so that a similar seamless experience can be had in Debian and Ubuntu when the packages.microsoft.com repositories are being used.

**Comment by richlander** [comment]
If we did this, would PMC still be registered after install? If so, that would be observable. We'd need to document that, including how to unregister it. Also, `apt update` would result in a new version of .NET for folks rebuilding with old .NET images (say in a private registry). That would be odd, IMO.

**Comment by jander-msft** [comment]
> With CBL-Mariner, we took the approach of installing .NET by downloading the corresponding RPM files from blob storage and installing them locally.

Are distroless images out of scope for this effort? I see that CBL-Mariner images are using RPMs but CBL-Mariner distroless images are still using tarballs.

Would the images install from PMC or from blob storage? It seems that the CBL-Mariner images are currently installing from blob storage, but I'm not certain that this proposal changes that aspect or if this proposal is more like "for what is done for CBL-Mariner, do the same for Ubuntu and Debian images" in terms of acquiring and installing .NET assets.

**Comment by mthalman** [comment]
> If we did this, would PMC still be registered after install? If so, that would be observable. We'd need to document that, including how to unregister it. Also, `apt update` would result in a new version of .NET for folks rebuilding with old .NET images (say in a private registry). That would be odd, IMO.

PMC would not be used, just as it's not used today for CBL-Mariner. We'd be installing the DEB files downloaded directly from blob storage. The reason for this is that we cannot reliably depend on PMC being up-to-date at the time the container images are built on release day.

The scenario that this addresses is when the downstream consumer explicitly configures PMC as a repository.

**Comment by mthalman** [comment]
> Are distroless images out of scope for this effort? I see that CBL-Mariner images are using RPMs but CBL-Mariner distroless images are still using tarballs.

Since the end goal of this is to work well with a package manager, there's no point in doing that in a distroless container because there's no package manager there. So we gain nothing by installing them as RPM packages in that environment.

**Comment by mthalman** [comment]
The scenarios for doing this work aren't compelling. What would be the reason for using .NET as the base image in a scenario where the app package is dependent on a .NET package? We can re-evaluate as needed but closing for now.
