### ISSUE TITLE
Tracking: MCR rendering tool only allows one distinct custom sub-table

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3893]
https://github.com/microsoft/mcr/issues/2051

**Comment by richlander** [comment]
What's the ".NET 6 Preview" that we want to list?

**Comment by MichaelSimons** [comment]
> What's the ".NET 6 Preview" that we want to list?

Jammy distroless images.

**Comment by mthalman** [comment]
We've determined that we don't have a need for this at this point. We only need one distinct sub-table per architecture.
