### ISSUE TITLE
Did not find a suitable dotnet SDK at '/usr/share/dotnet'.

### ISSUE THREAD

**Issue by divinebovine** [dotnet/dotnet-docker#39]
I'm trying to build a new docker image using microsoft/dotnet:1.0.0-rc2-core and I get an error on the following line in my docker file:

`RUN dotnet restore`

Error message:
> Did not find a suitable dotnet SDK at '/usr/share/dotnet'. Install dotnet SDK from https://github.com/dotnet/cli

**Comment by MichaelSimons** [comment]
@divinebovine The `microsoft/dotnet:1.0.0-rc2-core` image only contains .NET Core (the runtime and libraries).  It is intended to be used to publish a [portable application](http://dotnet.github.io/docs/core-concepts/app-types.html) to.  If you want to develop (restore, build, run, test, etc) applications, you will need to use the microsoft/dotnet:1.0.0-preview1 image as this contains the .NET Core SDK.

**Comment by divinebovine** [comment]
@MichaelSimons Thanks, I totally missed that distinction.
