### ISSUE TITLE
Include working samples for ASP.NET Core SPA templates.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#393]
@wdspider commented on [Wed Jul 26 2017](https://github.com/dotnet/dotnet-docker-samples/issues/61)

I created a default ASP.NET Core 2.0 - Angular application using the [SPA templates](https://github.com/aspnet/JavaScriptServices) via the `dotnet new angular` command.  I would like to run / build the application using Docker; therefore, I added the [.dockerignore](https://github.com/dotnet/dotnet-docker-samples/blob/master/aspnetapp/.dockerignore) and [Dockerfile](https://github.com/dotnet/dotnet-docker-samples/blob/master/aspnetapp/Dockerfile) from the aspnetapp sample and changed the base image labels to 2.0.  While `docker build -t myapp .` and `docker run -it --rm -p 5000:80 myapp` successfully built the image and started the container, I receive a [Node Missing Exception.txt](https://github.com/dotnet/dotnet-docker-samples/files/1177615/Node.Missing.Exception.txt) when browsing to http://localhost:5000.

I understand that the exception is due to Node not being installed in the [microsoft/aspnetcore:2.0](https://hub.docker.com/r/microsoft/aspnetcore/) image  What I'm having trouble finding (probably partially due to not using Linux before) is the appropriate commands to put into the Dockerfile to perform the Node installation.  I'm also not having much luck finding an example Dockerfile that enables the webpack hot module support and `dotnet watch` tools in a dev image from [microsoft/aspnetcore-build:2.0](https://hub.docker.com/r/microsoft/aspnetcore-build/) while still testing/running the app from a 
[microsoft/aspnetcore:2.0](https://hub.docker.com/r/microsoft/aspnetcore/) based image.

As such, it would be extremely helpful if these base samples also included a sample based on the SPA templates for the above use-cases.  Another sample on how to attach the debugger to an image also seems extremely helpful.

---

@wdspider commented on [Tue Aug 08 2017](https://github.com/dotnet/dotnet-docker-samples/issues/61#issuecomment-320984243)

For others that it may help, I finally managed to get Node installed within the microsoft/aspnetcore:2.0 image using the following sample dockerfile:
```
# Stage 1 - Build App
 FROM microsoft/aspnetcore-build:2.0 AS build-env
 WORKDIR /app

 # Create starter angular app
 RUN dotnet new angular \
     && dotnet publish -c Release -o out

# Stage 2 - Run App
 FROM microsoft/aspnetcore:2.0

 # Install Node (used for server pre-rendering)
 RUN buildDeps='gnupg' \
     && set -x \
     && apt-get update && apt-get install -y $buildDeps --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* \
     && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
     && apt install nodejs \
     && rm -rf /usr/lib/systemd/* \
     && apt-get purge -y --auto-remove $buildDeps \
     && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
     && node -v

 WORKDIR /app
 COPY --from=build-env /app/out .
 ENTRYPOINT ["dotnet", "app.dll"]
```
That said, I still could use an example on how to get the webpack hot module support / dotnet watch running in the microsoft/aspnetcore-build:2.0 image allowing me to completely develop within the container rather than relying on having .NET Core installed on my machine.

---

@richlander commented on [Sun Nov 12 2017](https://github.com/dotnet/dotnet-docker-samples/issues/61#issuecomment-343809444)

Can you elaborate on `dotnet watch` within a container?  For that to work, what do you plan to use to edit the asp.net site files within the container? Or do you plan to volume mount your site directory so that you can edit them outside the container?

---

@wdspider commented on [Tue Nov 14 2017](https://github.com/dotnet/dotnet-docker-samples/issues/61#issuecomment-344326878)

I was looking for the same rich development experience that currently occurs on your local machine to instead be contained within Docker.  In this way, I would only need Docker, Git, and VS Code installed on my "dev" machine.  All other required components would be provided by Docker containers including the .NET Core SDK or other application specific needs (database / caching / etc).  In this way, as the team's brand new developer on ProjectA; I don't need to figure out how to correctly initialize ProjectA's dev environment beyond knowing which Docker containers I need, which likely would be provided by a docker-compose config.

Yes, I would manage ProjectA's source code on the local machine with Git / VS Code; therefore, I expect that I would need to volume mount the project's root directory into the .NET Core SDK docker container.  After which, I should be able to easily use any of the .NET CLI commands within the docker container whether it's `dotnet new` to create a new project or `dotnet watch` (and Webpack's HMR) to dynamically update the running application code as I modify source code via VS Code.  I should also have an uncomplicated way to attach the debugger to the application running in the docker container.

Essentially, all of the existing dev tooling (at least the .NET Core related ones) would **just work** without requiring me to think much about the fact that ProjectA is actually being compiled / executed within Docker rather than on my local machine.

After typing up this response, I realize that this goal is likely a bit more overarching than just the dotnet-docker-samples repo.  However, the main reason I first arrived at this repro was to obtain the correctly configured Dockerfile that enabled this goal; particularly since I was just starting out with .NET Core / Docker and was confused as to why a brand new `dotnet new angular` project would not execute in the Docker container built from the sample Dockerfile obtained from this sample repro.

---

@jeremiahccarroll commented on [Fri Dec 22 2017](https://github.com/dotnet/dotnet-docker-samples/issues/61#issuecomment-353706945)

I found a solution. Take a look at this commit on 2017-12-12 in the aspnet/aspnet-docker repository: https://github.com/aspnet/aspnet-docker/commit/942f61df4d0305082491f8e3f0b4fc5a8278ca7c

I am using Visual Studio 2017 version 15.5.2 as my IDE on a Windows 10 host machine. I have Angular 5.1.2 in the project alongside .NET Core 2.0.4. My Docker image is 2.0.4-stretch. Adding the text below to my Dockerfile solved the problem:

ENV NODE_VERSION 6.11.3
ENV NODE_DOWNLOAD_URL https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz
ENV NODE_DOWNLOAD_SHA 610705D45EB2846A9E10690678A078D9159E5F941487ACA20C6F53B33104358C

RUN curl -SL "$NODE_DOWNLOAD_URL" --output nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
    && rm nodejs.tar.gz \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && npm install -g bower gulp \
    && echo '{ "allow_root": true }' > /root/.bowerrc

**Comment by natemcmaster** [comment]
FYI - see also https://github.com/aspnet/Docs/issues/5450

**Comment by MichaelSimons** [comment]
Closing - would like to see aspnet cover this in their documentation as part of aspnet/Docs#5450.
