### ISSUE TITLE
Enable signed NuGet package validation for 6.0.4xx

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#3932]
The NuGet team is [re-enabling signed NuGet package validation](https://github.com/NuGet/NuGet.Client/pull/4706). It is enabled by default (for Linux) for .NET 7. It is opt-in for .NET 6. I'm proposing we opt-in to this capability in containers.

I previously mentioned that there was a problem with workloads. There is not. I was wrong. There is no expected breaking change due to enabling this feature. Both .NET 7 and .NET 6.0.4xx have the same behavior.

The only expected "break" is if NuGet finds a package with a bad cert. That's a good break, and the exact same thing would happen if someone used the Windows build of the .NET SDK.

`DOTNET_NUGET_SIGNATURE_VERIFICATION` is exposed to opt-in. If you set it to true, it enables signature verification by default during restore operations. The environment variable name is case-sensitive but the value is not: both `true` and `TRUE` work.

Note that this only affects signature verification during [restore operations](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#description) (e.g.: `dotnet new`, `dotnet add package`, `dotnet restore`, etc.). Other NuGet commands like `dotnet nuget sign` and `dotnet nuget verify` always have verification enabled.

@dtivel

**Comment by mthalman** [comment]
[Triage] - We'll get this implemented for the August release. Prior to then, we'll update the nightly branch to target 6.0.4xx so that it can be tested on both 6.0 and 7.0 in that branch first.

**Comment by mthalman** [comment]
This feature is enabled by default in .NET 7. To enable this in .NET 6, the `DOTNET_NUGET_SIGNATURE_VERIFICATION` variable needs to be set to `true`.
