### ISSUE TITLE
Include sample for DotNet.Watcher.Tools for development time.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#394]
@alexsandro-xpt commented on [Wed Aug 16 2017](https://github.com/dotnet/dotnet-docker-samples/issues/68)

In development should be have a way to run my project with `dotnet watch run` to gain development time when I test my app.

---

@kendrahavens commented on [Wed Aug 30 2017](https://github.com/dotnet/dotnet-docker-samples/issues/68#issuecomment-326059664)

Hey @alexsandro-xpt. Thank you for opening this. We are currently trying to figure out the documentation gaps that would make this approachable. We've had prototypes of this working, but it takes a lot of configuration right now and its not in a state or pattern that we want to recommend to customers yet.

---

@alexsandro-xpt commented on [Fri Sep 01 2017](https://github.com/dotnet/dotnet-docker-samples/issues/68#issuecomment-326671224)

Alright @kendrahavens, I haved tested it in this repository https://github.com/alexsandro-xpt/WatchRunDocker in both v1.1 and v2.0 dotnet core version at master and dotnetcore2 branch, may be this could help something.

**Comment by richlander** [comment]
See #420

**Comment by MichaelSimons** [comment]
@richlander - Why close the issue before the PR is merged?  In general I don't think it is a good engineering practice as you are never certain a PR will be merged.  I would recommend adding the comment `Addresses #394` to the PR so that GH will automatically close the issue when the PR is closed.
