### ISSUE TITLE
Dependency update pipeline fails to create PRs

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#3953]
The [dependency update pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=470&_a=summary) is not creating PRs for modified changes. See https://dev.azure.com/dnceng/internal/_build/results?buildId=1911493&view=logs&j=00fa4588-b6b6-574f-ae82-807fb3798490&t=14e894eb-e4bd-5b2c-c189-a6aebe347da5 as an example. Possible cause is missing credentials for creating the PR:

```
update-dependencies Information: 0 : git status --porcelain results:
 M manifest.versions.json
 M src/monitor/6.2/alpine/amd64/Dockerfile
 M src/monitor/6.2/alpine/arm64v8/Dockerfile
 M src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
 M src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
 M src/monitor/6.2/cbl-mariner/amd64/Dockerfile
 M src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile

update-dependencies Information: 0 : Changes made but no GitHub credentials specified, skipping PR creation
```

**Comment by mthalman** [comment]
This was fixed by https://github.com/dotnet/dotnet-docker/pull/3982
