### ISSUE TITLE
Request for removal of .NET Monitor 5.0 tags

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#4066]
The 5.0 product version of .NET Monitor was not made generally available in any fashion. All 5.0 versions never had official support either. We request that the 5.0 tags for .NET Monitor be removed, which are the following:

- 5.0
- 5.0-alpine
- 5.0-alpine-amd64
- 5.0.0-preview.4
- 5.0.0-preview.4-alpine
- 5.0.0-preview.4-alpine-amd64
- 5.0.0-preview.5
- 5.0.0-preview.5-alpine
- 5.0.0-preview.5-alpine-amd64
- 5.0.0-preview.6
- 5.0.0-preview.6-alpine
- 5.0.0-preview.6-alpine-amd64
- 5.0.0-preview.7
- 5.0.0-preview.7-alpine
- 5.0.0-preview.7-alpine-amd64

cc @dotnet/dotnet-monitor

**Comment by mthalman** [comment]
These have now been deleted.
