### ISSUE TITLE
(This sounds like a question well-suited for stackoverflow rather than the dotnet issue tracker)

### ISSUE THREAD

**Issue by sunainadevi1998** [dotnet/dotnet-docker#4067]
(This sounds like a question well-suited for stackoverflow rather than the dotnet issue tracker)

> Step 4/12 : COPY SanSa/*.csproj ./SanSa/

The error says that you are trying to copy all the `.csproj` files from `SanSa` directory. And no such files exist. You don't have a `SanSa` directory, so that's kind of expected. But this `COPY` instruction doesn't match the contents of your `Dockerfile`. Are you sure you are looking at the right files?

_Originally posted by @omajid in https://github.com/dotnet/dotnet-docker/issues/750#issuecomment-429653681_

**Comment by sunainadevi1998** [comment]
FROM mcr.microsoft.com/dotnet/sdk:5.0 As build
WORKDIR /app
COPY *.sln .
COPY ExamRoom.ItemBanking./*.csproj ./ExamRoom.ItemBanking/
RUN dotnet restore
COPY ExamRoom.ItemBanking/. ./ExamRoom.ItemBanking/
WORKDIR /app/ExamRoom.ItemBanking
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/ExamRoom.ItemBanking/out ./
ENTRYPOINT ["dotnet", "ExamRoom.ItemBanking.dll"]

**Comment by mthalman** [comment]
Closing. This issue seems to be mistakenly created since it's just a copy of comment from another issue.
