### ISSUE TITLE
unknown flag: --target

### ISSUE THREAD

**Issue by Yamdie** [dotnet/dotnet-docker#407]
## Steps to reproduce the issue
1. create project using VS 2017 
2. add docker
3. build

## Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		unknown flag: --target
See 'docker build --help'..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	366	

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
This issue appears to be specific to VS Docker Tools.  Moved to https://github.com/Microsoft/DockerTools/issues/80
