### ISSUE TITLE
Replace crypticpassword with $CREDENTIAL_PLACEHOLDER$

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/dotnet-docker#4118]
In https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md `crypticpassword` is used many times. CredScan – working with passwords requires  `$CREDENTIAL_PLACEHOLDER$`

If you agree, I'll PR and fix.

**Comment by mthalman** [comment]
[Triage]
Approved. I've assigned to you, @Rick-Anderson to fix.
