### ISSUE TITLE
Docker Compose mem_limit causes unexpected shutdown without messages, with exit code 0 and no messages.

### ISSUE THREAD

**Issue by luizcarlosfaria** [dotnet/dotnet-docker#4145]
### Describe the Bug

When use mem_limit on docker-compose without large margin, application crash with exit code 0.

### Steps to Reproduce

On Visual Studio
1. Create a new ASP.NET Core Web App (Model-View-Controller) (.NET 6)
2. Select docker support.
3. After project was created, add Container Orchestration Support and choose Docker-Compose
4. On your docker-compose.yaml set mem_limit to 250m (mem_limit: 250m).

The result when debugger with Visual Studio is .NET producing exit code 0, without any exception, any information, any log.

The result when running without debugger, is the docker producing exit code 139 of execution of my container. 

With docker stats opened, this containers does not growth above 70 mb, before die.

### Other Information

Visual Studio does not show any message.

dotnet does not show any message.

### Output of `docker version`

Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.68.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 23.47GiB
 Name: docker-desktop
 ID: 2EE5:TSPP:PN2S:DDHY:MR3R:GRGG:6FLS:ZW7J:JZZK:MJUU:ECVM:DLFB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 69
  Goroutines: 68
  System Time: 2022-10-15T06:25:23.787379201Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by mthalman** [comment]
I'm unable to reproduce this.

> The result when running without debugger, is the docker producing exit code 139 of execution of my container.

Since you're able to reproduce this outside of VS, can you provide a zip file of your project along with the exact commands to be run that reproduce this?

**Comment by mthalman** [comment]
@luizcarlosfaria - Are you able to provide a repro project and the necessary commands to run?

**Comment by mthalman** [comment]
Closing due to no repro and no response. If you have a zip file with a self-contained repro, please share it and we can come back to this to investigate.
