### ISSUE TITLE
Update readme section order to the mcr.microsoft.com recommendation

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#4161]
Current the readme sections are not ordered as [suggested by mcr.microsoft.com](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/containers-bburns/microsoft-container-registry/microsoft-artifact-registry-also-known-as-microsoft-container-registry-docs/onboardingdocs/documentationstandards) (microsoft internal link).  This should be changed so that .NET is in compliance.  

**Suggested ordering**

About (required)
Featured tags (optional)
Related repositories (optional)
Configuration (optional)
Usage (optional)
Support (required)
License (required)

**Comment by mthalman** [comment]
The ordering of headers is different between the MAR-hosted readmes versus the Docker Hub-hosted readmes. MAR-generated readmes are at https://github.com/dotnet/dotnet-docker/tree/main/.mar/portal. It looks like the ordering is correct for MAR: https://mcr.microsoft.com/en-us/product/dotnet/framework/aspnet/about.

However, the names of the headers could use some updating, it looks like.
