### ISSUE TITLE
Investigate production of distroless-style Alpine images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4162]
There continues to be interest in distroless-style container images for .NET for the obvious reasons of reduced security exposure and smaller image size. One distro we're looking at for this is Alpine. For the .NET 8 milestone, we'll investigate what it would look like to produce distroless-style images based on Alpine. This may involve the use of [apko](https://github.com/chainguard-dev/apko).

**Comment by lbussell** [comment]
[Triage] We don't think this is a good ROI since the Alpine images are already quite small. /cc @richlander
