### ISSUE TITLE
`CryptographicException` in distroless image due to missing home directory for `app` user

### ISSUE THREAD

**Issue by aelij** [dotnet/dotnet-docker#4202]
### Describe the Bug

We got an error from cryptography APIs when using the `6.0.10-cbl-mariner2.0-distroless` image using the `app` user:

> Access to the path '/home/app/.dotnet/corefx/cryptography/x509stores/<store-name>' is denied

```
Cryptographic Exception while adding certificate <thumbprint> to store name:<store-name> location CurrentUser: System.Security.Cryptography.CryptographicException: The X509 certificate could not be added to the store.
 ---> System.UnauthorizedAccessException: Access to the path '/home/app/.dotnet/corefx/cryptography/x509stores/<store-name>' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.AddCertToStore(ICertificatePal certPal)
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
```

### Steps to Reproduce

Call `X509Store.Add()` in a `6.0.10-cbl-mariner2.0-distroless` container with the `app` user.

### Other Information

Workaround: create the `/home/app` directory in the container image and `chown` it to the `app` user.

**Comment by mthalman** [comment]
This is fixed in the 7.0 image: https://github.com/dotnet/dotnet-docker/blob/9b731e901dd4a343fc30da7b8b3ab7d305a4aff9/src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile#L64

We didn't make that change in 6.0 because it wasn't discovered until after 6.0 GA and it would have been a breaking change to make that change in a servicing release.
