### ISSUE TITLE
Include locale en_US.UTF-8 for msbuild

### ISSUE THREAD

**Issue by jspraul** [dotnet/dotnet-docker#4205]
### Describe the Problem

Exec tasks warns: bash : warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
https://github.com/dotnet/msbuild/issues/4194

Often MSBuild warnings are treated as errors.

### Describe the Solution

Include locale en_US.UTF-8 in the dotnet-sdk docker images.

### Additional Context
Related Issue:  Inconsistent use of locale environment variables https://github.com/dotnet/dotnet-docker/issues/1516

I understand "images should be global friendly" but right now MSBuild is not.

List of locales:
```
2022-11-14 11:35:39:/tmp$ sudo docker images --digests | grep dotnet/sdk
mcr.microsoft.com/dotnet/sdk                                                                      6.0                sha256:807eba67b95246174c63daa7f1d5b5990ce555ecbff73437bbe6c31f28660acb   0ff04a23cb9e   6 days ago     737MB
2022-11-14 11:36:00:/tmp$ sudo docker run --name test --rm -it mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash
root@f9186243c4fe:/# locale -a
C
C.UTF-8
POSIX
```

**Comment by mthalman** [comment]
[Triage]
It seems like the correct thing to do here is for https://github.com/dotnet/msbuild/issues/4194 to be fixed so that MSBuild has locale-neutral behavior. Yes, the current set of .NET SDK container images are out of alignment with this MSBuild behavior. But that can't be changed at this point because setting the locale would be a breaking change. The only opportunity to make that change would be for .NET 8. So in that case, it makes more sense for MSBuild to fix that issue in the .NET 8 milestone.

cc @rainersigwald - It would be good to know whether https://github.com/dotnet/msbuild/issues/4194 is committed to be fixed for .NET 8 or not.

**Comment by jspraul** [comment]
> setting the locale would be a breaking change

To be clear: I am _not_ requesting _setting_ the locale, I am requesting inclusion of the  en_US.UTF-8 locale in only the -sdk flavors of the docker image, only so that the included MSBuild can run without warning.

**Comment by rainersigwald** [comment]
> It would be good to know whether [dotnet/msbuild#4194](https://github.com/dotnet/msbuild/issues/4194) is committed to be fixed for .NET 8 or not.

@marcpopMSFT any objection here? The work is easy, the implications I don't fully understand but if we can actually hide it behind .NET 8 we might be able to turn this on now and get lots of preview coverage.

**Comment by marcpopMSFT** [comment]
Are suggesting gating the fix on the TFM (so only targeting net8.0 would have the 4194 change)? That certainly limits risk and I'd be fine with that. It would delay getting the fix to customers though.

**Comment by rainersigwald** [comment]
Yeah, it's the conservative option. I don't know how to gauge impact if we put it in 7.0.200 though.

**Comment by marcpopMSFT** [comment]
On the one hand, 7.0.200 is a feature release so changes are allowed. On the other hand, we try not to break anyone in feature band releases.  Tying it to the 8.0 TFM is fine by me.

**Comment by mthalman** [comment]
[Triage]
We're doing to defer to the current behavior of MSBuild as it exists today and the future change that would occur in .NET 8. This means that prior to .NET 8, the MSBuild logic would cause a warning to occur with the default configuration of the .NET container images. At this point, we're not ready to add `en_US.UTF-8` as an available locale. We want to proceed cautiously with making a change like that. If we get more feedback from people that this is causing issues, then we will reevaluate. It's possible to configure this yourself today to avoid the warning/error from MSBuild by setting `en_US.UTF-8` as an available locale.
