### ISSUE TITLE
New "latest" variant tags

### ISSUE THREAD

**Issue by begerard** [dotnet/dotnet-docker#4206]
Currently the "latest" tag only provide full windows/debian images depending the platform, but do not offer the other variants, like nano/alpine.

We would like to use the "latest" tag, at least for our building images. For that we would need new tags like latest-alpine, latest-nanoserver-1809... same that for the versioned tags.

**Comment by mthalman** [comment]
[Triage]
Can you describe the use case for wanting this?

**Comment by mthalman** [comment]
@begerard - Can you provide a description of your use case for such tags?

**Comment by mthalman** [comment]
Your .NET projects are targeting a specific version though, right? So don't you update your Dockerfile when you update the target .NET version for your project? Can you describe your current workflow for that and how you think it would be helped by having these tags?

**Comment by mthalman** [comment]
@begerard - Any info you can provide regarding [my questions here](https://github.com/dotnet/dotnet-docker/issues/4206#issuecomment-1352007293) would be appreciated.
