### ISSUE TITLE
ARM version missing package 'Microsoft.ApplicationInsights.AspNetCore'

### ISSUE THREAD

**Issue by duckybsd** [dotnet/dotnet-docker#425]
## Steps to reproduce the issue
microsoft/dotnet:2.0.6-runtime-stretch-arm32v7

## Expected behavior
ARM dotnet environment running application

## Actual behavior
Error:
  An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

## Additional information (e.g. issue happens only occasionally)
Seems missing package

## Output of `docker version`

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 06:39:28 2017
 OS/Arch:      linux/arm64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 06:39:28 2017
 OS/Arch:      linux/arm64
 Experimental: false

```

## Output of `docker info`

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 23
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.18-sunxi64
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.956 GiB
Name: SkyNode2
ID: ZS5A:MVHL:MHWT:XY7T:YVKS:LUMN:JKKZ:BSCJ:MDMO:AT4V:3IVG:PK6E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by natemcmaster** [comment]
> This assembly was expected to be in the local runtime store 

You are hitting this issue https://github.com/aspnet/Universe/issues/554. ASP.NET Core does not yet provide an arm32 runtime store.

To opt-out of runtime store trimming, use this command.
```
dotnet publish -p:PublishWithAspNetCoreTargetManifest=false
```

See https://github.com/dotnet/core-setup/issues/3122#issuecomment-326040506

**Comment by duckybsd** [comment]
No fixing my problem.
```
root@0177273b6f3d:/PT# dotnet publish -p:PublishWithAspNetCoreTargetManifest=false Monitor/Monitor.dll

root@0177273b6f3d:/PT# Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

dotnet seems doesn't have this usage?
```
root@0177273b6f3d:/PT# dotnet --help

Usage: dotnet [host-options] [path-to-application]

path-to-application:
  The path to an application .dll file to execute.

host-options:
  --additionalprobingpath <path>      Path containing probing policy and assemblies to probe for
  --depsfile <path>                   Path to <application>.deps.json file
  --runtimeconfig <path>              Path to <application>.runtimeconfig.json file
  --fx-version <version>              Version of the installed Shared Framework to use to run the application.
  --roll-forward-on-no-candidate-fx   Roll forward on no candidate shared framework is enabled
  --additional-deps <path>            Path to additonal deps.json file


Common Options:
  -h|--help                           Displays this help.
  --info                              Displays the host information
```

**Comment by MichaelSimons** [comment]
@duckybsd - Can you share your Dockerfile?  How are you building the app that you are running inside of the `microsoft/dotnet:2.0.6-runtime-stretch-arm32v7` based container? `dotnet publish -p:PublishWithAspNetCoreTargetManifest=false` should be used during the building/publishing of the app you are running inside the container.

**Comment by duckybsd** [comment]
@MichaelSimons Thanks for the clarification, I think I only get the executable binary files, I do not have the source code, so if the publisher doesn't do this then I think there is no way I can fix this problem, this is the application.

https://github.com/Legedric/ptmagic/releases/download/1.3.1/PTMagic.1.3.1.zip

**Comment by MichaelSimons** [comment]
@duckybsd - that is correct.  Closing as the underling issue is tracked with aspnet/Universe#554.
