### ISSUE TITLE
Add environment variables to baser images

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#426]
There are a set of environment variables that are useful for certain scenarios. They are either not set or set in the wrong place. I have taken a dependency on these environment variables being set in dotnet images in #420.

The variables:

* ASPNETCORE_URLS=http://+:80
* DOTNET_USE_POLLING_FILE_WATCHER=1

The `ASPNETCORE_URLS` variable should be set in the runtime-deps images. This enables self-contained apps and every other ASP.NET Core scenario.

The `DOTNET_USE_POLLING_FILE_WATCHER` variable should be set in the SDK image. This is where `dotnet watch` lives and it doesn't without this variable being set.

These changes should be made for .NET Core 2.1 Preview 2.

**Comment by MichaelSimons** [comment]
Thought on setting `ASPNETCORE_URLS=http://+:80` in the SDK image as well?

**Comment by natemcmaster** [comment]
+1 for adding to SDK too. Although not necessarily recommended, people definitely do "dotnet run" in the SDK image to launch their aspnet apps.

**Comment by richlander** [comment]
Needed for `dotnet watch run` ;)

Anyway, added it.

**Comment by richlander** [comment]
This is resolved with #428
