### ISSUE TITLE
Nuget restore authentication issue from a Docker container

### ISSUE THREAD

**Issue by ncoussemacq** [dotnet/dotnet-docker#4281]
Hi,

I've been struggling a few hours trying to setup nuget authentication from a docker container using Credential Manager. I was following this documentation section : https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider but kept facing the same error 
`error NU1301: Unable to load the service index for source https://....`

After some investigation, I managed to have it working by removing line `USER ContainerUser`
<img width="649" alt="image" src="https://user-images.githubusercontent.com/6803679/208941127-6b0b1131-22c0-413b-a8e7-4a278f4f9913.png">

As far as I understand the issue, Azure Credential Manager was being installed for the ContainerAdmin user but the following operations (including dotnet restore command) were executed from ContainerUser account, for which the Credential Manager was not installed. 
I could misunderstand all of it but at least, it worked for me. Shouldn't the documentation be updated ?

Regards,
Nicolas

**Comment by mthalman** [comment]
[Triage]
This should get fixed. First, we should verify that https://github.com/microsoft/artifacts-credprovider/issues/201 is resolved. If so, that means we don't need to switch to `ContainerAdministrator` at all. If not, then the Dockerfile snippet should be updated to continue to run as `ContainerAdministrator` until after the `dotnet restore` command is done.

**Comment by JohnSchmeichel** [comment]
Original issue was never fixed (no great solution there anyways). Have an updated sample as a workaround for review in https://github.com/dotnet/dotnet-docker/pull/4828

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/dotnet-docker/pull/4828
