### ISSUE TITLE
Remove .NET Monitor 6.2 Dockerfiles

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#4292]
.NET Monitor 6.2 is out-of-support on January 11th, 2023 ([announcement](https://github.com/dotnet/dotnet-monitor/discussions/2658)). According to the [support policy](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md#tag-lifecycle) for EOL versions, servicing of the .NET Monitor 6.2 tags will end on February 14th, 2023. At that time, the .NET Monitor 6.2 Dockerfiles should be removed from the repo.

**Comment by mthalman** [comment]
This was fixed as part of https://github.com/dotnet/dotnet-docker/pull/4417
