### ISSUE TITLE
CTRL-C doesn't work on ASP.NET apps with dotnet watch in docker

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#431]
I am running a Docker container per the instructions in #420. CTRL-C works for ASP.NET locally and for console apps in a container but not for ASP.NET apps in a container. I get this same behavior on Windows and macOS.

Command line:

```console
docker run --rm -it -p 8000:80 -v c:\git\dotnet-docker\samples\aspnetapp:/app/ -w /app/aspnetapp microsoft/dotnet-nightly:2.1-sdk dotnet watch run
```

Result:

```console
Hosting environment: Production
Content root path: /app/aspnetapp
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
watch : Shutdown requested. Press Ctrl+C again to force exit.
^C
^C^C^C^C^C^C
^C^C^C^C^C^C^C^C
^C^C^C^C^C
```

/cc @natemcmaster @MichaelSimons @glennc

**Comment by MichaelSimons** [comment]
This appears to be tied to using `dotnet watch` in conjunction with ASP.NET.  CTRL-C works as expected when running an ASP.NET app directly within a container.

**Comment by MichaelSimons** [comment]
Upon further inspection, CTRL-C is working.  It is just extremely slow.

**Comment by richlander** [comment]
I just repro'd that. It takes about 20s for me, on both macOS and Windows. Surprisingly, Windows containers don't seem to have this problem.

**Comment by natemcmaster** [comment]
I can repro, too. You can move this to aspnet/DotNetTools. I have a hunch it may be something in the "kill process tree" code, but I'm not sure.

**Comment by MichaelSimons** [comment]
Copied to https://github.com/aspnet/DotNetTools/issues/410

**Comment by richlander** [comment]
Thanks!!
