### ISSUE TITLE
.NET Monitor: Use archive files instead of .NET tool package for installation

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#4337]
### Describe the Problem

The .NET Monitor Dockerfiles install the dotnet-monitor tool using `dotnet tool install` which installs the platform neutral variant of dotnet-monitor into the image. Post installation steps are necessary to remove files in order to minimize the image, such as the alternate TFMs (the NuGet package includes two TFMs), native files for other platforms, and extra NuGet package files that `dotnet tool install` writes out. The removal process looks like:

```
    dotnet tool install dotnet-monitor --tool-path /app --add-source / --version $DOTNET_MONITOR_VERSION --framework net7.0 --no-cache \
    # To reduce image size, remove all non-net7.0 TFMs
    # To do this safely, we need to first find everything that dotnet tool installed named "dotnet-monitor".
    # The /dotnet-monitor/ folder exists under .store which is not a stable constant to rely on. The result is multi stage search:
    # 1. Find any files in /app
    # 2. Match anything that is under a *folder* called 'dotnet-monitor'
    # 3. Match anything from step 2 that isn't in a '/tools/net7.0' folder (/tools is the folder we use in a nuget file that is stable)
    # 4. Delete everything from step 3
    && find /app -type f -print | grep -i '.*/dotnet-monitor/.*' | grep -v -i '.*/tools/net7[.]0' | xargs rm -rf \
    # To reduce image size further, remove the non-linux assemblies
    && find /app -type f -print | grep -i '.*/dotnet-monitor/.*' | grep -i -E '/(runtimes|shared|shims)/(win|osx)' | xargs rm -rf \
    # To reduce image size further, remove linux assemblies that do not match the x64 architecture
    && find /app -type f -print | grep -i '.*/dotnet-monitor/.*' | grep -i -E '/(runtimes|shared|shims)/(linux-arm64|linux-musl-arm64)' | xargs rm -rf \
    # To reduce image size further, remove symbol files
    && find /app -type f \( -name *.pdb -o -name *.dbg \) -print | xargs rm -rf \
    # Remove all the empty directories left by the previous step
    && find /app -type d -empty -delete \
    # Allow other users to run the tool
    && chmod 755 /app/dotnet-monitor \
    && rm dotnet-monitor.$DOTNET_MONITOR_VERSION.nupkg
```

As the tool evolves over time, this procedure requires manual adjustment to trim down the files to what is necessary for the image.

### Describe the Solution

Currently, the .NET Monitor team is working on new packages in the form of archives (zip for Windows, tar.gz for non-Windows) in addition to maintaining the current .NET Tool offering. The archives are a RID-specific, single TFM offering that only include the necessary files for the target platform and TFM. These archives will be available on the typical blob storage accounts (e.g. `dotnetbuilds` and `dotnetcli`) thus acquisition would be similar to runtime, aspnet, and SDK.

An example file name is `dotnet-runtime-7.0.2-linux-x64.tar.gz` which targets Linux x64 platforms with a .NET 7 shared framework installation.

The Dockerfiles should be updated to use the new archive offering when it is available.

**Comment by richlander** [comment]
Makes sense. We should talk with the SDK team about this scenario, at least to inform their future development. This isn't the first time that prod-oriented use of tools has come up.

@baronfel

**Comment by jander-msft** [comment]
.NET Monitor is now using tarballs starting with the 6.3.2, 7.0.2, and 8.0 Preview 1 releases.
