### ISSUE TITLE
Instructions in the samples for running an ASP.NET app are not optimal

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#437]
From https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/README.md#build-and-run-the-sample-with-docker

> docker run --rm -p 8000:80 --name aspnetcore_sample microsoft/dotnet-samples:aspnetapp

This does not seem optimal to me.  If you were to run this in a production environment I think `--rm` should be replaced with `-d`.  If you were to run this in a development environment I think you should add '-it'.  The reason for this is that if you are running in PS with just '--rm' and hit CTRL+C, Powershell is processing the keystroke.  CTRL+C doesn't cause the running container to be stopped.  You can see this by running `docker ps`.  If you rerun the cmd, it will fail with:

> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Conflict. The container name "/aspnetcore_sample" is already in use by container "4c925968413ae51298c3d1acff54a001a9afc5dce0f68e6d988c7311112fd22e". You have to remove (or rename) that container to be able to reuse that name.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

**Comment by richlander** [comment]
Great feedback.

`--name aspnetcore_sample` is only there to make it easy to get the IP address on Windows. Thoughts on that? I could move that to the Windows section or should we guide people to find the IP address on Windows a different way?

Should we add `-it` to all of the samples and then document the part about `-d` (for prod)? I assume that   both `--rm` and `it` are replaced by `-d`. Yes?

**Comment by MichaelSimons** [comment]
I don't mind specifying a name `--name aspnetcore_sample` as I find this to be a best practice in ASP.NET production scenarios.  It makes management of the running container easier.

I like the suggestion of using `-it` and then document the part about using `-d` in production.

**Comment by richlander** [comment]
I missed a key part. You are saying that the combination of `--name` and no `-it` is a losing proposition but `--name` and `-it` is good. Got it.

**Comment by richlander** [comment]
This is resolved with #420. Right?

**Comment by MichaelSimons** [comment]
Yes it was - thanks
