### ISSUE TITLE
The command for copying Directory.Build.props is added to the template

### ISSUE THREAD

**Issue by zhangzw218** [dotnet/dotnet-docker#4398]
### Describe the Problem

I control the version of nuget with Directory.Build.props, but when constructing the dockerfile, I am warning because the file is not copied:
warning NU1602 d does not provide an inclusive lower bound for dependency...

### Describe the Solution

I solved the problem by manually adding commands:
COPY ["Sub_TitanAbpNextSolution/Directory.Build.props", "Sub_TitanAbpNextSolution/"]

Does the template automatically detect and add file copies, or does it already exist, but I have a configuration problem?

……
dockerfile
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["nuget.config", "."]
COPY ["Sub_TitanAbpNextSolution/nuget.config", "Sub_TitanAbpNextSolution/"]
# I solved the problem by manually adding commands:
COPY ["Sub_TitanAbpNextSolution/Directory.Build.props", "Sub_TitanAbpNextSolution/"]
...
```

**Comment by richlander** [comment]
You copy each file specifically. I don't see where you would expect the file you mention to be copied before the last `COPY` statement. So far, I'm not seeing a .NET-specific problem. It could be that I'm missing something, but it seems like you haven't used the `COPY` commands in the way that you want. Is that right?

**Comment by zhangzw218** [comment]
Directory.Build.props should be a required file, so I want dockerfile to add a copy of this file. (If this file exists)。
I don't have to add it manually.

**Comment by richlander** [comment]
I don't understand. You are copying it. Is that not working? Docker doesn't know which files you want or don't want.

**Comment by zhangzw218** [comment]
It's OK after I add the copy.
……
But I think if I use Directory.Build.props, this file is a must. docker needs this file.
If I didn't use Directory.Build.props, this file doesn't exist, Docker does not need this file.
……
……
Or to put it another way, I think it should be something like nuget.config. If I don't have a custom configuration file, dockerfile won't copy it.
If I customize nuget.config and have a file in the root directory, then the dockerfile will need to be copied automatically when it is generated.
COPY ["nuget.config", "."]
This is automatically added to the dockerfile.

**Comment by MichaelSimons** [comment]
@zhangzw218 - Is this a dockerfile that was generated by Visual Studio or did you create this yourself?

**Comment by zhangzw218** [comment]
Visual Studio generation

**Comment by patverb** [comment]
`Directory.Build.props` files should be scaffolded in new dockerfiles automatically as of Visual Studio 17.6 preview 1.

**Comment by pastrasigns** [comment]
What's the point of this Docker file line of; COPY ["Directory.Build.props", "."]

**Comment by lbussell** [comment]
> What's the point of this Docker file line of; COPY ["Directory.Build.props", "."]

@pastrasigns The line instructs Docker to copy the file "Directory.Build.props" from the build context into the current working directory inside the image. If your project has a Directory.Build.props, you should copy it into your build stage to ensure that build properties shared across multiple projects are available during the Dockerfile build.
