### ISSUE TITLE
Consider using `arm64` instead of `arm64v8` tags for .NET 8

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4400]
Doing that would align with this proposal: https://github.com/dotnet/dotnet-docker/issues/4388

We would still need to backport changes for .NET 6 and .NET 7 (for alias tags).

**Comment by richlander** [comment]
This is no longer needed.

**Comment by mthalman** [comment]
Just to close the loop, the proposal at https://github.com/dotnet/dotnet-docker/issues/4388#issuecomment-1421401384 avoids the need for a different tag.
