### ISSUE TITLE
docker pull mcr.microsoft.com/dotnet/aspnet:6.0 returns 503 service unavailable

### ISSUE THREAD

**Issue by diablo2947** [dotnet/dotnet-docker#4403]

**Comment by richlander** [comment]
There was an outage in the South East Asia that has been affecting folks (including in Australia). Are your still seeing a 503?

https://status.azure.com/status/

**Comment by diablo2947** [comment]
Hi, I am able to pull images now. Thanks for your inputs. Closing the issue

**Comment by richlander** [comment]
Sorry for the inconvenience!

**Comment by mthalman** [comment]
In the future, any issues with the registry itself should be logged at https://github.com/microsoft/containerregistry/issues. There was already an existing issue there for this: https://github.com/microsoft/containerregistry/issues/131
