### ISSUE TITLE
Image for SDK 7.0.200 missing

### ISSUE THREAD

**Issue by nesc58** [dotnet/dotnet-docker#4423]
Hello,
the download for 7.0.200 is available on https://dotnet.microsoft.com/en-us/download/dotnet/7.0 but no docker image exists for 7.0.200. The docker image only exists for 7.0.103. The february release (https://github.com/dotnet/core/issues/8191) should add images for 7.0.200.

Could you please add it?

Kind regards

**Comment by dave-yotta** [comment]
If this is added, everyone using `7.0` will get the breaking changes from `7.0.200`, which has caused a bit of a stir:
https://github.com/dotnet/sdk/pull/29065
https://github.com/dotnet/sdk/issues/30624

**Comment by mthalman** [comment]
Please see our recent announcement about the 7.0.2xx feature band: https://github.com/dotnet/dotnet-docker/discussions/4434. Our plan is to publish this in the March release.

**Comment by richlander** [comment]
You can close it. We are acting on this report.

**Comment by mthalman** [comment]
The 7.0.201 SDK was released early and so new SDK images have been published for this version. See https://github.com/dotnet/dotnet-docker/discussions/4460.
