### ISSUE TITLE
Update to dotnet:release/7.0.2xx broke our build

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/dotnet-docker#4424]
### Describe the Bug

https://github.com/dotnet/sdk/pull/29065

### Steps to Reproduce

dotnet pack -o some-directory

### Other Information

Not your fault that the core team made a breaking change to the dotnet toolchain but there it is.

### Output of `docker version`
n/a

### Output of `docker info`
n/a

**Comment by dave-yotta** [comment]
Due to the way versioning in the sdk works, a reference to `dotnet/aspnet:7.0` is equivilant to `dotnet/sdk:7.0.100` and `dotnet/sdk:7.0.101`. I don't think this helps though, the sdk team release both critical patches and breaking changes as a patch version.

**Comment by mthalman** [comment]
Given that this is not related to the .NET Docker images (they are still on the 7.0.1xx channel of the SDK), I'm closing this.

There is an existing issue to get the SDK images updated to 7.0.200: https://github.com/dotnet/dotnet-docker/issues/4423
