### ISSUE TITLE
Installing and removing `shadow-utils` in .NET 8.0 CBL Mariner 2.0 image leaves behind extra files

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4478]
This caused a size increase of ~10MB.

CBL-mariner2.0 doesn't contain the utilities needed to create new users/groups by default, so we need to install `shadow-utils`. In order to keep image size down, an attempt was made to install and uninstall the package in the same layer. However, some files get left behind. As far as I can tell, the layer adds cracklib, which aligns with the roughly ~10MB size increase.

See here: https://github.com/dotnet/dotnet-docker/blob/89d1f8fdb5fd72570cc80ac81d4da037bc9d79e8/src/runtime-deps/8.0/cbl-mariner2.0/amd64/Dockerfile#L17-L32

**Comment by lbussell** [comment]
After more research, `tdnf` only supports autoremove in versions >= `3.4.0` (https://github.com/vmware/tdnf/pull/283). 

CBL Mariner 2.0 only has version `3.2.2` (and doing a package upgrade doesn't change it, as expected).

**Comment by mthalman** [comment]
@PawelWMS - Any plans to update `tdnf` to >= 3.4.0 any time soon?

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/4652
