### ISSUE TITLE
Update-Dependencies tool fails to update checksum for aspnetcore-runtime-7.0.4-linux-arm.tar.gz

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4488]
When running the following command:

```
./eng/Set-DotnetVersions.ps1 -ProductVersion 7.0 -SdkVersion 7.0.202 -RuntimeVersion 7.0.4 -AspnetVersion 7.0.4
```

It fails to update the checksum in the manifest.versions.json file for the aspnetcore-runtime-7.0.4-linux-arm.tar.gz file. It is left unchanged.

I saw this in the tool's output:

```
update-dependencies Information: 0 : Downloading 'https://dotnetcli.blob.core.windows.net/dotnet/checksums/7.0.4-sha.txt'.
update-dependencies Error: 0 : Checksum file is not in the expected format: https://dotnetcli.blob.core.windows.net/dotnet/checksums/7.0.4-sha.txt
```

**Comment by mthalman** [comment]
[Triage]
Let's make sure to have this fixed prior to the April release.

**Comment by lbussell** [comment]
This bug is fixed in https://github.com/dotnet/dotnet-docker/pull/4531.
