### ISSUE TITLE
Add `ENV` for `app` UID

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4506]
We had a discussion about how folks should use the new `app` user and whether they should use its name or UID for the `USER` instruction. We decided that the UID is best since it works better with the `runAsNonUser` Kubernetes feature.

Plan:

- Add `ENV APP_UID=64198` to `runtime-deps` layer
- Encourage users to use the following pattern: `USER $APP_UID`

It's possible that having an ENV for the UID may be useful for other scenarios.

@karolz-ms

**Comment by tmds** [comment]
> We decided that the UID is best since it works better with the runAsNonUser Kubernetes feature.

@richlander can you elaborate what this means?

**Comment by richlander** [comment]
Per my observations:

- Kubernetes enables you to set and/or test the container user.
- Kubernetes only knows about UIDs.
- If you test the user with `runAsNonUser` in Kubernetes and set the container as a non-root user by name in your Dockerfile, then that test will fail.

Do you observe same?

**Comment by richlander** [comment]
You can use these samples to test: https://github.com/dotnet/dotnet-docker/pull/4502

**Comment by tmds** [comment]
> https://github.com/dotnet/dotnet-docker/pull/4502

This has the answer I was looking for: for `runAsNonRoot: true` to work, you need to use the `USER <uid>` format. Then Kubernetes checks rootless as: `UID != 0`. If you use the `USER <name>` format, then Kubernetes can't figure out `<name>` isn't root.
