### ISSUE TITLE
Add legal notice to Linux containers

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4519]
We received a request to add the following notice to our container images. This would presumably required downloading in the SDK stage and copying in the final stage. The motivation is that our images would better align with GPL expectations with this file in situ (as opposed to relying on a notice on our container registry page).

https://github.com/microsoft/containerregistry/blob/main/legal/Container-Images-Legal-Notice.md

Note: The notice is likely to undergo some edits.

/cc @ariel11

**Comment by mthalman** [comment]
[Triage]
We should consider whether there can be a metadata-based approach for this information instead of a file within the image itself. The OCI spec provides for metadata fields that could potentially be used for this. We'd need to determine what the UX looks like for that.

**Comment by richlander** [comment]
Waiting for more input on this.
