### ISSUE TITLE
GIT CLI missing in .NET 6 SDK Windows

### ISSUE THREAD

**Issue by Sam13** [dotnet/dotnet-docker#4521]
GIT CLI (MinGIT) is missing in .NET6 SDK Windows images - in .NET 7 SDK it is present.
Although path environment variable contains ```C:\Program Files\MinGit\cmd``` in both images.
In .NET6 SDK the path ```C:\Program Files\MinGit``` does not exist.

### Steps to Reproduce
```docker run --rm -it mcr.microsoft.com/dotnet/sdk:7.0.202-windowsservercore-ltsc2019 cmd /c git version```
-> works

``` docker run --rm -it mcr.microsoft.com/dotnet/sdk:6.0.407-windowsservercore-ltsc2019 cmd /c git version```
-> Command not found

### Output of `docker version`
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:43:10 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.1 (101757)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:37:54 2023
  OS/Arch:          windows/amd64
  Experimental:     false

### Output of `docker info`
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 417
 Server Version: 20.10.23
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19044 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19044.2728)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.62GiB
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by richlander** [comment]
I think the question is why the `PATH` is set with git in the .NET 6 image. Isn't that a bug?

https://github.com/dotnet/dotnet-docker/blob/main/src/sdk/6.0/nanoserver-ltsc2022/amd64/Dockerfile#L64

**Comment by mthalman** [comment]
> I think the question is why the `PATH` is set with git in the .NET 6 image. Isn't that a bug?
> 
> https://github.com/dotnet/dotnet-docker/blob/main/src/sdk/6.0/nanoserver-ltsc2022/amd64/Dockerfile#L64

Ah, indeed it is a bug. I'll reopen this to address the removal of it from the `PATH` variable.

**Comment by lbussell** [comment]
MinGit is removed from the PATH in https://github.com/dotnet/dotnet-docker/pull/4528. It'll make it into the next servicing release.
