### ISSUE TITLE
Remove `core` syndication

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4533]
Do we still need this support?

https://github.com/dotnet/dotnet-docker/blob/f4786b8c0b4469f7eb18f891fd6c090561e50006/manifest.samples.json#L18-L31

https://github.com/dotnet/dotnet-docker/blob/f4786b8c0b4469f7eb18f891fd6c090561e50006/manifest.json#L7-L12

**Comment by mthalman** [comment]
This should be resolved before https://github.com/microsoft/mcr/pull/3010 can be merged.

It's also necessary to have this done as a prerequisite to the EOL annotation work since these are still supported tags at this point.

**Comment by lbussell** [comment]
[Triage]

The unused variables from dotnet-docker's manifest can be removed today.

There is an open question about when we can safely remove the active syndication for dotnet/samples repo. There are a few things we can check:

- Telemetry to see if any dotnet/core/samples images are being pulled
- Search across Github / AzDO repos to see if there are any significant usages of these images

If we don't determine there to be any significant use of the dotnet/core/samples images, then we should be OK to stop syndicating them. If there is a non-trivial amount of usage then we'll need an announcement.

**Comment by mthalman** [comment]
Doing a search on GitHub, I'm still seeing quite a bit of usage of `mcr.microsoft.com/dotnet/core/samples`: https://github.com/search?q=mcr.microsoft.com%2Fdotnet%2Fcore%2Fsamples+-is%3Afork&type=code&ref=advsearch. That search is currently returning 235 files.

**Comment by mthalman** [comment]
Announcement has been posted at https://github.com/dotnet/dotnet-docker/discussions/5869

**Comment by mthalman** [comment]
EOL annotations have been applied to all the images in the `core` and `core-nightly` repos. Last step is to unregister those repos from MAR: https://github.com/microsoft/mcr/pull/3010.

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/dotnet-docker/pull/6047.
