### ISSUE TITLE
Add Debian Bookworm images for .NET 6/7

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4535]
.NET 6 images are based on Debian Bullseye. Bullseye will go out of support ahead of .NET 6. We should start producing Debian Bookworm images for .NET 6. Also, OpenSSL 1.x EOL is before .NET 6 EOL. Debian Bullseye includes OpenSSL 1.x and Bookworm 3.x.

- OpenSSL 1.1.1 EOL: September 11, 2023
- Debian Bullseye EOL: ~ July, 2024
- .NET 6 EOL: November 12, 2024

The expectation is the following:

- `6.0-bullseye-slim` tags will be updated through .NET 6 EOL, based on Debian Bullseye.
- `6.0` tags will continue to be based on `bullseye-slim` images for compatibility reasons, even though they may have more CVEs.
- `6.0-bookworm-slim` tags will be based on Debian Bookworm and be opt-in (AKA, you need to update your `FROM` statement).
- We will start by publishing `6.0-bookwork-slim` tags in `dotnet/nightly` repos and then publish to `dotnet` (main) repos after Bookworm is GA.
 
6.0 images:

https://github.com/dotnet/dotnet-docker/blob/f4786b8c0b4469f7eb18f891fd6c090561e50006/src/runtime-deps/6.0/bullseye-slim/arm64v8/Dockerfile#L1

.NET 8 images are already based on Bookworm:

https://github.com/dotnet/dotnet-docker/blob/f4786b8c0b4469f7eb18f891fd6c090561e50006/src/runtime-deps/8.0/bookworm-slim/arm64v8/Dockerfile#L1

.NET 7 images don't need to be changed since .NET 7 EOL is ahead of Bullseye or OpenSSL 1.x EOL.

More info:

- https://wiki.debian.org/DebianReleases
- https://github.com/dotnet/core/blob/main/releases.md
- https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/

**Comment by mthalman** [comment]
[Triage]
This will help to fill in the gap of having a supported Debian version for .NET 6 between July and November (2024).

**Comment by mthalman** [comment]
@lbussell - You can grab my branch at https://github.com/dotnet/dotnet-docker/tree/dev/mthalman/issue4535-bookworm which already starts this work. I think all that's left is to update the image size baselines.
