### ISSUE TITLE
We need a docker image with nuget authentication libraries installed with easy way to pass username and password or PAT in order to access private nuger server to revive packages and dependencies

### ISSUE THREAD

**Issue by RiadKatby** [dotnet/dotnet-docker#4543]

**Comment by mthalman** [comment]
Please see the [documentation for working with private NuGet feeds](https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md). If that doesn't resolve your issue, please open a [discussion thread](https://github.com/dotnet/dotnet-docker/discussions) with details on what you've tried and what issue you are seeing.
