### ISSUE TITLE
Use latest version of syft for image inspection

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4545]
There was an [issue](https://github.com/dotnet/dotnet-docker/issues/4537) that required the tests to [pin to an older version of syft](https://github.com/dotnet/dotnet-docker/pull/4541). The solution to that was discovered that will allow us to now go back to using the latest version. See https://github.com/anchore/syft/issues/1708#issuecomment-1499589501.

We need to specify `--platform <platform>` as an argument to the syft tool to get this to work properly. Example:

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock anchore/syft packages docker:mcr.microsoft.com/dotnet/runtime-deps:8.0-preview-jammy-chiseled-arm32v7 -o json --platform linux/arm
```

**Comment by mthalman** [comment]
[Triage]
It would be better if we could be pinned to a specific version to avoid unintended breakage. Ideally we would have a process in place for updating to newer versions of syft as they are released. This could be done either manually or through automation (using the update-dependencies tool to query for latest reason could be an option).

**Comment by lbussell** [comment]
I have noticed that syft updates very frequently. Around 3, sometimes 4 times per month. They are currently on version 80: https://github.com/anchore/syft/releases/tag/v0.80.0

**Comment by lbussell** [comment]
This should include a way to automatically update the Syft image in the cache ACR as well.

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/5769
