### ISSUE TITLE
Include `8.0-preview` in Featured Tags section of readmes for nightly repos

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4563]
The readmes for nightly repos do not currently list `8.0-preview` in the Featured Tags section:

https://github.com/dotnet/dotnet-docker/blob/3b21071a81fd036d2469afa393486d8ad37f7cdf/README.aspnet.md?plain=1#L7-L12

I think it should be listed as:

```
 * `8.0-preview` (Preview) 
   * `docker pull mcr.microsoft.com/dotnet/nightly/aspnet:8.0-preview` 
 * `7.0` (Standard Support) 
   * `docker pull mcr.microsoft.com/dotnet/nightly/aspnet:7.0` 
 * `6.0` (Long-Term Support) 
   * `docker pull mcr.microsoft.com/dotnet/nightly/aspnet:6.0` 
```

This should only be done for the nightly repos. For the main repos, those readmes wouldn't be updated to include `8.0` until the RC release, per https://github.com/dotnet/dotnet-docker/pull/4128.

**Comment by lbussell** [comment]
These new readmes are live now: https://github.com/dotnet/dotnet-docker/blob/nightly/README.sdk.md#featured-tags
