### ISSUE TITLE
Define a release lifecycle checklist

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4574]
For a given .NET release, there are a number of important tasks that need to be done with the Docker images during its entire lifecycle, starting from the first preview, to GA release, and all the way to its EOL date. We should define a checklist template which defines these tasks just as we do with other release events in https://github.com/dotnet/dotnet-docker/tree/main/.github/ISSUE_TEMPLATE/releases.

Here are some examples of the tasks:

* The process of defining a new set of Dockerfiles
  * Manifest updates
  * Test data updates
  * Image size baseline updates
* Initial preview release
  * PowerShell is excluded from SDK originally until they have a release for the new .NET version
  * Update Featured Tags in nightly branch (https://github.com/dotnet/dotnet-docker/issues/4563)
* Include PowerShell in SDK when a PowerShell release is available
* RC release
  * Update Featured Tags in main branch (https://github.com/dotnet/dotnet-docker/pull/4128)
* GA release
  * Move `latest` tag to new version (https://github.com/dotnet/dotnet-docker/issues/2316)

**Comment by lbussell** [comment]
@mthalman is able to predict the future 🙂

A release checklist would have prevented with these two PRs from being late:
- https://github.com/dotnet/dotnet-docker/pull/4878
- https://github.com/dotnet/dotnet-docker/pull/4875

I propose we do this work in the Post-8.0 timeframe instead of leaving it on the backlog.

**Comment by lbussell** [comment]
This should include updating .NET Docker projects to the latest version of .NET:
- https://github.com/dotnet/docker-tools/issues/1078
- https://github.com/dotnet/docker-tools/issues/1181

**Comment by lbussell** [comment]
- This should include https://github.com/dotnet/dotnet-docker/pull/4963

**Comment by lbussell** [comment]
This should also include adding the .NET version to the .NET Framework SDK image and removing it when it is EOL: https://github.com/microsoft/dotnet-framework-docker/blob/6a3c9d048f75c1e69c0e1059564cd56a90bf9e3c/eng/dockerfile-templates/sdk/Dockerfile#L56-L59
