### ISSUE TITLE
Adding non-root user in jammy issues results in image size increase

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4588]
See https://github.com/dotnet/dotnet-docker/pull/4587. I investigated the difference between the two images:

- `mcr.microsoft.com/dotnet/nightly/runtime-deps@sha256:24cc8445fa87fb3771d40628f6745b3988f425dcd3d6fb80a2384305ae7c536e` (new)
- `mcr.microsoft.com/dotnet/nightly/runtime-deps@sha256:1dd42bff18ccd210bea44f481ee3b49db9cea509e7b7ff2a2e2b3e5aff3a1ac3` (old)

The culprit here is the `/var/log/lastlog` file. It has increased in size from 30kb to 19mb. `/var/log/faillog` has also increased in size from 3.3kb to 2.1mb. This requires some more investigation.

**Comment by mthalman** [comment]
In general, we should probably be cleaning up log files, especially those of this size.

**Comment by lbussell** [comment]
So this actually happens because of https://github.com/dotnet/dotnet-docker/pull/4476. `/var/lib/lastlog` stores user login data *indexed by UID*. So when we increased the UID we inadvertently make this file really big. The solution is to run `adduser` with the `-l` option which omits these log files. PR incoming for that.
