### ISSUE TITLE
Debug breakpoints not working with 2.1 preview in Docker

### ISSUE THREAD

**Issue by jarrettv** [dotnet/dotnet-docker#459]
## Steps to reproduce the issue
1. Create a new 2.1 dot net project
2. Add docker support (from visual studio)
3. Set a breakpoint
4. Debug from the docker-compose project

## Expected behavior
Visual studio breaks on the breakpoint

## Actual behavior
Visual studio doesn't break

## Additional information (e.g. issue happens only occasionally)
Same steps but target 2.0 work fine

Found this related stack-overflow
[Docker and ASP.NET Core 2.1 preview 1
](https://stackoverflow.com/questions/49234614/docker-and-asp-net-core-2-1-preview-1)

## Output of `docker version`

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

## Output of `docker info`

```
Containers: 21
 Running: 2
 Paused: 0
 Stopped: 19
Images: 69
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155dcfd728
ID: TC6X:3WHR:USLJ:ZOVZ:UYJ2:HVAF:OEXT:XPBU:W445:XGCR:PSMU:6YEB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 53
 System Time: 2018-03-30T14:16:16.516292Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
This issue appears specific to VS Docker tooling.  FYI - https://github.com/Microsoft/DockerTools is the repo for VS Docker tooling related issues.  

It looks like an issue already exists for this - https://github.com/Microsoft/DockerTools/issues/92.

@jarrettv -  feel free to open a new issue in the [DockerTools repo](https://github.com/Microsoft/DockerTools) or append info to https://github.com/Microsoft/DockerTools/issues/92 as you see fit.

Closing this issue.
