### ISSUE TITLE
Add Dockerfiles for Alpine 3.18

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4607]
Now that [Alpine 3.18 has been released](https://alpinelinux.org/posts/Alpine-3.18.0-released.html), we should add Dockerfiles for it and get things tested.

**Comment by mthalman** [comment]
[Triage]
As part of this, the existing 8.0 Dockerfiles based on Alpine 3.17 should be updated to just replace 3.17 with 3.18 and not continue providing 3.17 images.

**Comment by hoerup** [comment]
@mthalman will this be in place for net 7.0.6 ? 
Im hoping we soon will to be able to use musl 1.2.4 with DNS-over-tcp fallback

**Comment by lbussell** [comment]
> will this be in place for net 7.0.6 ?

@hoerup Assuming there are no major setbacks, we would like to have Alpine 3.18 images ready for the next release, yes.

**Comment by mthalman** [comment]
> Will it be available for .NET 6?

Yes, it will be made available for all supported versions.

**Comment by aradalvand** [comment]
@mthalman Sorry for tagging you but just wanted to ask approximately when is this going to be done?

**Comment by mthalman** [comment]
Alpine 3.18 images have been published in yesterday's release for 8.0 Preview 5. See https://github.com/dotnet/dotnet-docker/discussions/4662.
