### ISSUE TITLE
Remove SDK Alpine 3.16 Dockerfiles

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#4608]
Removal of the Alpine 3.16 Dockerfiles from the SDK product seems to have been missed in #4505. This is okay because the manifest doesn't contain the entries anymore so they should be building. This is more of cleanup task for consistency.

**Comment by Gabriel-Gotti** [comment]
well i have been hacked 133 times in one month. Valerie Royz's family{boyfriends}, & inlaw's, Heather DeSanto,Shrubb,Bashum,Deckert,Curtis,Riveria,Gracia,Delucca,Langler,Long's,DeBello,Daub/Sabcheck,Sutton,
Tarubbuco,

**Comment by lbussell** [comment]
Alpine 3.16 Dockerfiles are removed in nightly and will make it to main for the June release.
