### ISSUE TITLE
Update image artifact docs with .NET Monitor information

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#4611]
Add a section to https://github.com/dotnet/dotnet-docker/blob/main/documentation/image-artifact-details.md about getting license and notice files from the .NET Monitor images.

**Comment by mthalman** [comment]
[Triage]
This would add another section that builds upon the output of the existing [ASP.NET](https://github.com/dotnet/dotnet-docker/blob/main/documentation/image-artifact-details.md#aspnet-core-image) section and includes the necessary paths for targeting .NET Monitor's installation.
