### ISSUE TITLE
Non-root UID is greater than SYS_UID_MAX

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4624]
### Describe the Bug

This is how we currently create the non-root user in Debian Bookworm:
https://github.com/dotnet/dotnet-docker/blob/e709fa5d158575e78187ed2b8866dc7f6113c535/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile#L17-L27

We're creating a "system" user, but using a UID that exceeds the `SYS_UID_MAX` env variable, resulting in this [warning in CI](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276807&view=logs&j=dd8712c6-8a1e-50f1-fa86-6250d6555872&t=a075e40c-529c-5ca3-4315-cb4ee61596f6&l=259): 
```
useradd warning: app's uid 64198 is greater than SYS_UID_MAX 999
```

As far as I can tell this doesn't have any consequences but it doesn't look great. We should look into if we need the user to be a "system" one and what the consequences of not being a system user are.

### Steps to Reproduce

Build a .NET 8.0 debian-bookworm runtime-deps Dockerfile from the nightly branch.

**Comment by mthalman** [comment]
The original reasoning for defining a system user was that the intention of the user was intended for app execution only, not representative of a human that does interactive login.

**Comment by lbussell** [comment]
From what I can tell, "system" users are only an organizational construct [[1]](https://unix.stackexchange.com/questions/80277/whats-the-difference-between-a-normal-user-and-a-system-user) [[2]](https://unix.stackexchange.com/questions/619654/what-does-the-system-flag-for-adduser-do)

I did a simple test building .NET 8.0 Jammy with and without the --system flag to make sure the user definitions are the same.

```pwsh
> docker run --rm jammy-regular-user cat /etc/passwd
...
app:x:64198:64198::/home/app:/bin/sh

> docker run --rm jammy-system-user cat /etc/passwd
...
app:x:64198:64198::/home/app:/bin/sh
```

Also comparing the images' file trees, the same files are touched on both images when adding the non-root user and there is no size penalty. I think we should remove the `--system` flag in nightly and see if it causes any issues.

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/4676
