### ISSUE TITLE
Official images for the .NET SDK Contains vulnerabilities  7.0.302-alpine3.17-amd64, 7.0-alpine3.17-amd64, 7.0-alpine-amd64, 7.0.302-alpine3.17, 7.0-alpine3.17, 7.0-alpine

### ISSUE THREAD

**Issue by bbassler** [dotnet/dotnet-docker#4625]
https://hub.docker.com/_/microsoft-dotnet-sdk
Official images for the .NET SDK

https://hub.docker.com/_/microsoft-dotnet-aspnet/
Official images for the ASP.NET Core runtime

When downloaded images are scanned by AquaSecurity plug in they show multiple CVEs. Assuming these are valid vulnerabilities what is the remediation process and general timeline?

SDK Image Linux amd64 Tags: 7.0.302-alpine3.17-amd64, 7.0-alpine3.17-amd64, 7.0-alpine-amd64, 7.0.302-alpine3.17, 7.0-alpine3.17, 7.0-alpine
DockerFile: https://github.com/dotnet/dotnet-docker/blob/d791e1535a89d2cf4c240c161b004116bcfdf23e/src/sdk/7.0/alpine3.17/amd64/Dockerfile

<img width="836" alt="2023-05-17_15-25-16" src="https://github.com/dotnet/dotnet-docker/assets/5041382/75db933f-a48b-4e0b-a3fe-61fc42306f37">

ASPNet Core image
SDK Image Linux amd64 Tags: 7.0.5-alpine3.17-amd64, 7.0-alpine3.17-amd64, 7.0-alpine-amd64, 7.0.5-alpine3.17, 7.0-alpine3.17, 7.0-alpine
Docker file: https://github.com/dotnet/dotnet-docker/blob/8f70e8dc26d3d173154a183b1503fb13a0b019ca/src/aspnet/7.0/alpine3.17/amd64/Dockerfile
Too many vulnerabilities to image. Count of 1 critical, 34 High and 12 Medium shown.

<img width="832" alt="aspnet 2023-05-17_15-39-09" src="https://github.com/dotnet/dotnet-docker/assets/5041382/cf066967-95c5-4de1-bce3-c2a5e076bb26">

**Comment by mthalman** [comment]
@bbassler - The one for System.Drawing.Common is tracked by https://github.com/dotnet/sdk/issues/30659 and is actually a false positive as no vulnerable binary file exists in the SDK.

For everything else, please follow the guidance in [Container Vulnerability Workflow](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md). After following that guidance, you can either re-open this issue or log a new one if prompted to do so by the document.
