### ISSUE TITLE
Clean up ENV in composite Dockerfiles

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/dotnet-docker#4632]
The composite Dockerfiles require to have both, `ASPNET_VERSION` and `DOTNET_VERSION`, set in the same file. Right now there are two ENV statements. This issue is just to track a small clean up to make those one ENV statement only.

**Comment by mthalman** [comment]
[Triage]
This is an example of what needs to be updated:

https://github.com/dotnet/dotnet-docker/blob/4819bd175a20d5eed0cbcb5048ecf6e452f05ce3/src/aspnet/8.0/alpine3.17-composite/amd64/Dockerfile#L7-L10

It should be defined as:

```Dockerfile
ENV \
  # .NET Runtime version 
  DOTNET_VERSION=8.0.0-preview.5.23260.3 \
  # ASP.NET Core version 
  ASPNET_VERSION=8.0.0-preview.5.23262.1 
```

**Comment by lbussell** [comment]
In the case of the nightly Dockerfiles, I am wondering if the actual DOTNET_VERSION variable (our "runtime|8.0|build-version") will be incorrect if the aspnet composite runtime is bundled with an older runtime version than dotnet/installer. My guess is it will be incorrect.

**Comment by mthalman** [comment]
> In the case of the nightly Dockerfiles, I am wondering if the actual DOTNET_VERSION variable (our "runtime|8.0|build-version") will be incorrect if the aspnet composite runtime is bundled with an older runtime version than dotnet/installer. My guess is it will be incorrect.

Good point. Might as well log an issue for that.

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/4616
