### ISSUE TITLE
Aspnet Readmes incorrectly lists non-composite tags for composite images

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4634]
Looking at the Aspnet readmes after composite images were added, the composite row in the table lists `8.0-preview-alpine` as a valid tag for these images:

https://github.com/dotnet/dotnet-docker/blob/4819bd175a20d5eed0cbcb5048ecf6e452f05ce3/README.aspnet.md?plain=1#L77-L84

However, pulling this tag (on my amd64 machine) always gives me the non-composite image. To fix this we should separate the composite from the non-composite images in the `manifest.json`, where they are currently grouped under the same shared tags:
https://github.com/dotnet/dotnet-docker/blob/4819bd175a20d5eed0cbcb5048ecf6e452f05ce3/manifest.json#L3863-L3964

**Comment by mthalman** [comment]
> Nice find. Looks like we need some more validation logic in Image Builder. It should not allow duplicate os-type/architecture (e.g. Linux amd64) combinations within a given shared tag.

Looks like @MichaelSimons stole my idea: https://github.com/dotnet/dotnet-docker/pull/4635#discussion_r1204048752. 😉

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/4635
