### ISSUE TITLE
suggestion: remove ENTRYPOINT from distroless images [8.0]

### ISSUE THREAD

**Issue by tmds** [dotnet/dotnet-docker#4650]
Distroless images set :

https://github.com/dotnet/dotnet-docker/blob/948b5fd2b9a77a783b80f712cfc6cc2375665b49/src/runtime/8.0/jammy-chiseled/amd64/Dockerfile#L28-L29

and non-distroless images do not.

```Dockerfile
FROM base
...
CMD ["/usr/bin/dotnet", "assembly.dll" ]
```

If you switch `base` for the above `Dockerfile` from a regular to a distroless, the distroless application image won't work because the `ENTRYPOINT` is pre-pended to the command. It tries to execute: `/usr/bin/dotnet /usr/bin/dotnet assembly.dll`.

@mthalman what do you think about removing the `ENTRYPOINT` from the distroless images? Is there a strong reason to set this?

If desired, `CMD` can still be set to `CMD ["/usr/bin/dotnet", "--info" ]`.

This also applies the Ubuntu Chiseled images: https://github.com/ubuntu-rocks/dotnet.

I noticed the difference while working on: https://github.com/dotnet/sdk-container-builds/issues/398.

cc @baronfel

**Comment by tmds** [comment]
There is no real use-case mentioned in that issue.

These images are meant to be used as base images, and setting an `ENTRYPOINT` affects how derived images behave for `CMD`.

The suggestion is to change:
```
 ENTRYPOINT ["/usr/bin/dotnet"] 
 CMD ["--info"] 
```
to
```
 CMD ["/usr/bin/dotnet", "--info"] 
```

Then `CMD` in derived images works the same across regular and distroless base images.

What do you think?

**Comment by mthalman** [comment]
> Then CMD in derived images works the same across regular and distroless base images.

What is the use case for using `CMD` in regular images without also using `ENTRYPOINT`? I'm trying to better understand where the friction point is for switching between the image types. Can you provide a concrete example of what makes it problematic today?

**Comment by tmds** [comment]
> My view is that using CMD without also specifying ENTRYPOINT is not a good practice. It places too much dependency on how the base image is defined, exactly what you're seeing here. In our sample Dockerfiles, we illustrate the recommended approach of setting the ENTRYPOINT in your app's Dockerfile: https://github.com/dotnet/dotnet-docker/blob/948b5fd2b9a77a783b80f712cfc6cc2375665b49/samples/dotnetapp/Dockerfile#LL19C1-L19C39. If you do that, it will work properly with either base image type.

I understand what you recommend.

Can you explain why
```Dockerfile
 ENTRYPOINT ["/usr/bin/dotnet"] 
 CMD ["--info"] 
```
is preferable to
```Dockerfile
 CMD ["/usr/bin/dotnet", "--info"] 
```
?

If there is no reason, `CMD` can mean the same thing for distroless base images and regular base images if we change to the latter.

**Comment by mthalman** [comment]
> Can you explain why
> 
> ```dockerfile
>  ENTRYPOINT ["/usr/bin/dotnet"] 
>  CMD ["--info"] 
> ```
> 
> is preferable to
> 
> ```dockerfile
>  CMD ["/usr/bin/dotnet", "--info"] 
> ```
> 
> ?
> 
> If there is no reason, `CMD` can mean the same thing for distroless base images and regular base images if we change to the latter.

1. It's more intuitive. By default, there's no entrypoint so, intuitively, it makes more sense to set one and use `CMD` for the args. We then might need to respond to questions of why we did it this way since it seems outside the norm.
2. Setting `ENTRYPOINT` is also self-documenting in the image metadata for the `Config.Entrypoint` property which helps describe the intent of the image we produce.
3. It'd also be a breaking change that we'd need to document if we changed it at this point. If we're going to do that, I'd want the reason for doing so to be a compelling one.

**Comment by mthalman** [comment]
> The main reason is to make `CMD` mean the same thing for distroless and regular images.

But why are you using `CMD` in this way? Here's a snippet from [Docker's documentation for `ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example):

> You can use the exec form of ENTRYPOINT to set fairly stable default commands and arguments and then use either form of CMD to set additional defaults that are more likely to be changed.

Why do you want to use `CMD` in this way to include `dotnet` when `ENTRYPOINT` solves the issue?

**Comment by tmds** [comment]
> But why are you using CMD in this way?

The use-case that triggered me is to use a helper script `ENTRYPOINT` (as described in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint) in combination with a `CMD` that starts the .NET app.

That made me look if some `dotnet/dotnet-docker` base images set the `ENTRYPOINT`, which I learned to be the case for the distroless images.

This `ENTRYPOINT` isn't such a helper script.

I don't see the advantage it gives.
And it gets in the way of `CMD` working the same way as it does for the regular (non-distroless) base images.

**Comment by mthalman** [comment]
> And it gets in the way of CMD working the same way as it does for the regular (non-distroless) base images.

It doesn't get in the way if you use `ENTRYPOINT`, which is the recommended way of doing things in this case. The best practice is for `ENTRYPOINT` to target the primary executable of the container. And `CMD` can be used to further provide default, overridable options of that executable.

**Comment by tmds** [comment]
It would be nice if the base image wasn't opinionated and would allow both `CMD` and `ENTRYPOINT` to be usable.

It seems you disagree, so I'll close this sugestion.
