### ISSUE TITLE
Add scannability support for Ubuntu chiseled images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4667]
The Ubuntu chiseled images are essentially a black box from the perspective of container image scanning tools like [Syft](https://github.com/anchore/syft) and [Trivy](https://github.com/aquasecurity/trivy). This is because those tools typically look for a package database that describes which packages are installed in the image. Due to the way these images are constructed using [chisel](https://github.com/canonical/chisel), no such database exists. For that reason, scanning tools would describe the images as having no packages at all. This is not what we want. It's important that these tools provide a more accurate representation of these images for the purposes of vulnerability reporting and SBOM generation.

Canonical is in the process of developing a [wrapper script for chisel](https://github.com/canonical/rocks-toolbox/blob/main/chisel-wrapper) that will generate a dpkg status file. This file will describe what packages are to be installed by chisel. Later, when a scanning tool is run on the image, it will detect this dpkg status file, just as it would for normal full OS container images, and provide an accurate representation of what packages are in the image. We should update our chiseled Dockerfiles to incorporate this [script ](https://github.com/canonical/rocks-toolbox/blob/main/chisel-wrapper) in its execution.

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/4688
