### ISSUE TITLE
Introduce a mechanism to pin stable versions of Ubuntu Chiseled tooling

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4692]
### Describe the Problem

When building Ubuntu Chiseled images, we always reference the latest version of the `chisel` tool: https://github.com/dotnet/dotnet-docker/blob/2795399a3649c051d76c9cadc718eb7129f28424/src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile#L3

This leaves us vulnerable to breaking changes on the main branch of Canonical's repo.

### Describe the Solution

We should introduce a version or git commit sha entry to the `manifest.versions.json` file for each `chisel` tool we depend on so that we can pin to a stable version when it's time to release.

### Additional Context

We should also think about how we can automate updating this version. Currently there are no versions, tags, or releases on the `chisel` or  `rocks-toolbox` tools.

**Comment by lbussell** [comment]
If applicable, this should also include a way to track and update the golang base image used to build the chisel tool.

**Comment by lbussell** [comment]
Related: https://github.com/dotnet/dotnet-docker/pull/4688 and #4667

**Comment by mthalman** [comment]
[Triage]

We want to avoid having any changes in these repos potentially cause a break in one of the .NET releases. Specifically, that means the `main` branch. As a mitigation for that risk in the short-term, we can pin to a commit. Longer term, the rocks-toolbox and chisel repos will have GitHub releases that we can consume from our infrastructure to update the Dockerfiles as needed.

**Comment by richlander** [comment]
Have we asked the Canonical team if they would be OK with us adding our own tags to their repo?

We could also create a fork and do same.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/4711 and https://github.com/dotnet/dotnet-docker/pull/4724
