### ISSUE TITLE
.NET's non-root UID 64198 exceeds Debian's UID_MAX of 60000

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4693]
Debian Bookworm has a UID_MAX set to 60000, resulting in this warning when creating a non-root user:

```
#6 [3/3] RUN groupadd         --gid=64198         app     && useradd -l         --uid=64198         --gid=64198         --create-home         app
#6 0.610 useradd warning: app's uid 64198 outside of the UID_MIN 1000 and UID_MAX 60000 range.
#6 DONE 0.7s
```

**Comment by richlander** [comment]
Proposal: `59346`

``` bash
% dotnet run
d: 100
o: 111
t: 116
n: 110
e: 101
t: 116
Sum: 654
60000 - 654: 59346
```

Code:

```csharp
string dotnet = "dotnet";
int sum = 0;
int maxUID = 60000;

foreach (var s in dotnet)
{
    Console.WriteLine($"{s}: {(int)s}");
    sum += s;
}

Console.WriteLine($"Sum: {sum}");

Console.WriteLine($"{maxUID} - {sum}: {maxUID - sum}");
```

**Comment by tmds** [comment]
The non-root user on Red Hat images has a uid of `1001`.
Is there a reason you pick such high values?

**Comment by richlander** [comment]
I started by reading this wiki page: https://en.wikipedia.org/wiki/User_identifier#Conventions. It is possible I got confused by the large numbers.

I don't think we're wedded to any one number. 

`1654` would be `1000` + `dotnet`. The UID doesn't have to be unique, but it is also arbitrary.

**Comment by mthalman** [comment]
> I started by reading this wiki page: https://en.wikipedia.org/wiki/User_identifier#Conventions. It is possible I got confused by the large numbers.

This is a relevant sentence from that article:

> Central UID allocations in enterprise networks (e.g., via [LDAP](https://en.wikipedia.org/wiki/LDAP) and [NFS](https://en.wikipedia.org/wiki/Network_File_System) servers) may limit themselves to using only UID numbers well above 1000, and outside the range 60000–65535, to avoid potential conflicts with UIDs locally allocated on client computers.

I think the key is to have a value that will be usable for all types of host systems. One of the factors we need to consider is volume mounting with the container running as the non-root user. In such cases, the host system will need to have a matching UID in order to allow for the appropriate permissions in the mounted volume. For that reason, we essentially want a UID that is in the "lowest-common-denominator" of UID ranges amongst the set of distros we consider to be important enough for this scenario.

**Comment by tmds** [comment]
> 1654 would be 1000 + dotnet.

Yes, a value like this, which is `1000` or higher, but not too high.

@mthalman I don't understand what you mean. Is `1654` an appropriate value? Or should it be in a different range?

**Comment by mthalman** [comment]
Sorry, I didn't mean to imply that number wasn't good. I was just adding some commentary on what the requirement should be here. A number like 1654 seems sufficient.

**Comment by richlander** [comment]
Good thing we hid the UID behind an ENV.

**Comment by lbussell** [comment]
Changed to `1654` in https://github.com/dotnet/dotnet-docker/pull/4715.

**Comment by sliekens** [comment]
@lbussell security scanning vendors recommend a UID of at least 10000 to avoid conflicts with the user table on Kubernetes nodes that host the container:
https://avd.aquasec.com/misconfig/kubernetes/general/avd-ksv-0020/

Can the UID be changed (again) to something between 10000 and 60000? @richlander proposed 59346, that comment appears to have been overlooked.

**Comment by tmds** [comment]
> security scanning vendors recommend a UID of at least 10000 to avoid conflicts with the user table on Kubernetes nodes that host the container:
https://avd.aquasec.com/misconfig/kubernetes/general/avd-ksv-0020/

I haven't seen base images with a uid that high. Because there is a link to `containers[].securityContext.runAsUser` I think this is a recommendation to set `runAsUser > 10000`.
