### ISSUE TITLE
No way to get npm/nodejs installed on the microsoft/dotnet:1.0.0-preview1 image

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/dotnet-docker#47]
Previous images I used (the dnx based stuff), didn't include npm nor node but with following tweaks it could be included. (aspnet needs npm these days)

```
RUN apt-get -qq update && apt-get -qqy --no-install-recommends install \
    git \
    unzip


RUN curl -sL https://deb.nodesource.com/setup_5.x |  bash -
RUN apt-get install -y nodejs
```

This doesn't work any longer with microsoft/dotnet:1.0.0-preview1
Can you please point out what's the easiest way to get npm/nodejs up and running in an image meant for apsnet core clr usage?

thx.
paul.

**Comment by paulvanbladel** [comment]
Feels  like it's related to: 
https://github.com/docker/docker/issues/23138

**Comment by paulvanbladel** [comment]
Simply doing apt-get update gives already trouble.

**Comment by divinebovine** [comment]
Node 5.x is no longer available, you can use 6.x now. See https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Also, if you want to use npm you'll need to apt-get install that too now.

**Comment by paulvanbladel** [comment]
@divinebovine thanks for the prompt reply but 
can you  please try following sequence:

from a (linux) host: 
sudo docker run --rm -it microsoft/dotnet:1.0.0-preview1

in the container: apt-get update

**Comment by MichaelSimons** [comment]
@paulvanbladel, sorry for the issues you are encountering.  The apt-get update issue is indeed related to the llvm feed being down.  #49 should address this.  In the meantime, you should be able to ignore the apt-get update issue from the broken feed.

```
apt-get update ; apt-get -y --no-install-recommends install \
    git \
    unzip
```

Alternatively you could remove it all together.

**Comment by paulvanbladel** [comment]
Thanks @MichaelSimons .
Hi snomis (right?), we met in an other live already i think :)
Not sure how to ignore the fact that apt-get update doesn't work?
I'm trying to create a container which should run an mvc app which needs both npm and nodejs.
When I add in the Dockerfile
RUN apt-get install -y npm
it fails because it needs a previous apt-get update, which stops the container creation process.
I probably need to wait unitl that llvm feed is up again?
cheers
paul.

**Comment by MichaelSimons** [comment]
@paulvanbladel - yes we did work together in the past!  Nice to see you here.

You could ignore apt-get update if all you were doing is just installing npm.

```

FROM microsoft/dotnet:latest

RUN apt-get -qq update ; apt-get -qqy --no-install-recommends install \
    git \
    unzip

RUN apt-get install -y nodejs
```

That really won't do you any good since you need Node.  The Node installer does an apt-get update, therefore if you want a workaround, you would have to remove the llvm package source.

```
FROM microsoft/dotnet:latest

RUN rm /etc/apt/sources.list.d/llvm.list
RUN apt-get -qq update && apt-get -qqy --no-install-recommends install \
    git \
    unzip

RUN curl -sL https://deb.nodesource.com/setup_5.x |  bash -
RUN apt-get install -y nodejs
```

...or as you mention, wait for the mentioned issue to get resolved.

**Comment by paulvanbladel** [comment]
Thanks Michael.

**Comment by paulvanbladel** [comment]
Removing the package source did the job.
FYI: I'm applying it here: https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore/blob/master/BasicSetup/src/AureliaAspNetApp/Dockerfile
Many thanks Michael for the great support. Very much appreciated.
Cheers
paul.
