### ISSUE TITLE
update-dependencies fails for chisel-only update

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4721]
The [update-dependencies pipeline](https://github.com/dotnet/dotnet-docker/blob/main/eng/pipelines/update-dependencies.yml) fails when the only updates to the branch are an update to the commit SHA for the [chisel](https://github.com/canonical/chisel/) repo. It outputs the following error:

```
update-dependencies Information: 0 : git status --porcelain results:
 M manifest.versions.json
 M src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
 M src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
 M src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
 M src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
 M src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
 M src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile

Failed to update dependencies:
System.Exception: 'git status' does not match DependencyInfo information. Git has modified files: True. DependencyInfo is updated: False.
   at Microsoft.DotNet.VersionTools.Automation.DependencyUpdateResults.ChangesDetected() in /_/src/Microsoft.DotNet.VersionTools/lib/src/Automation/DependencyUpdateResults.cs:line 46
   at Dotnet.Docker.UpdateDependencies.ExecuteAsync(Options options) in /update-dependencies/UpdateDependencies.cs:line 82
```

This is related to the changes that were made in https://github.com/dotnet/dotnet-docker/pull/4711.

Based on the output of the error message, the issue is that files in the repo were updated but the Updater class did not return any used DependencyInfos:
https://github.com/dotnet/dotnet-docker/blob/a0622ed5ee4f7341709cbc9161239fa084810641/eng/update-dependencies/BasicVariableUpdater.cs#L22

However, going beyond that particular issue, I think this whole scenario is something we want to avoid. My assertion is that we do not want to update the Dockerfiles solely for the purposes of updating the commit SHA for a dependent repo. A similar rule exists for the use of MinGit. We only update the MinGit version if we're also updating the SDK version:
https://github.com/dotnet/dotnet-docker/blob/a0622ed5ee4f7341709cbc9161239fa084810641/eng/update-dependencies/MinGitUpdater.cs#L23-L33

We should do a similar thing for commit SHAs like chisel.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/4724
