### ISSUE TITLE
Page samples/container-best-practices.md is missing

### ISSUE THREAD

**Issue by Bafff** [dotnet/dotnet-docker#4725]
I noticed that [this page](https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md) links to [Container best practices](https://github.com/dotnet/dotnet-docker/blob/main/samples/container-best-practices.md) which have no content 

Can you help me to find it?

**Comment by mthalman** [comment]
@richlander - You added this reference, but no actual .md file, as part of https://github.com/dotnet/dotnet-docker/pull/4534. Do you recall what content was intended here?
