### ISSUE TITLE
Consume release artifacts of rocks-toolbox repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4745]
With the changes in https://github.com/dotnet/dotnet-docker/pull/4711, we pin to a specific commit of the https://github.com/canonical/rocks-toolbox repo when cloning it in the Dockerfile. This repo will now be creating releases (e.g. https://github.com/canonical/rocks-toolbox/releases/tag/v1.0.0) that we should consume instead of querying for the latest commit. This could reuse the [similar logic](https://github.com/dotnet/dotnet-docker/blob/6da64f31944bb16ecde5495b6a53fc170fbe100d/eng/update-dependencies/UpdateDependencies.cs#L411) that we do with MinGit.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/4752
