### ISSUE TITLE
Remove dotnet/core/samples repo

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4755]
We should delete our old samples repo: `mcr.microsoft.com/dotnet/core/samples`

The replacement is (remove `/core`:  `mcr.microsoft.com/dotnet/samples`

See: https://mcr.microsoft.com/en-us/product/dotnet/samples/about

We moved to the `/dotnet` (no `/core`) repos years ago (.NET 5 timeframe). We kept the old `/dotnet/core` repos for compat. We no longer publish to the old repos (after .NET Core 3.1 went out of support). The `dotnet/core/samples` is the last repo we're still pushing updates to. That's wasteful and we should stop since we have an official samples repo. We take compat on our samples repo seriously, but there has to be an end to supporting this old repo. That's now (ish).

For folks reacting to this change, you should also look at this other breaking change: https://github.com/dotnet/dotnet-docker/discussions/4764

I noticed / was reminded of this old repo via the following line:

https://github.com/dotnet/dotnet-docker/blob/6da64f31944bb16ecde5495b6a53fc170fbe100d/manifest.samples.json#L22-L23

**Comment by mthalman** [comment]
[Triage]
The intent is to remove the `dotnet/core/samples` repo such that no images would exist there anymore. This has already been replaced with the existence of the `dotnet/samples` repo. All tags between the two repos are the same.

There are a number of usages of this repo that this [grep.app query shows](https://grep.app/search?q=mcr.microsoft.com/dotnet/core/samples). We can update those usages with PR updates ahead of removing this.

**Comment by lbussell** [comment]
[Triage] Closing in favor of https://github.com/dotnet/dotnet-docker/issues/4307 which encompasses all dotnet/core repos.
