### ISSUE TITLE
Switch to non-preview tagging pattern for .NET 8 RC1

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4772]
As discussed in https://github.com/dotnet/dotnet-docker/issues/4117, upon the release of .NET 8 RC1, we will switch from producing `8.0-preview` tags to just `8.0`. This will allow customers time to transition to these new tags during the RC period ahead of the GA release.

**Comment by mthalman** [comment]
[Triage]
The `8.0-preview` tags will not be maintained once we ship RC releases.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/4860
