### ISSUE TITLE
add  gss-ntlmssp to dotnet docker images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#478]
@wfurt commented on [Tue Apr 10 2018](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/49)

This is related to https://github.com/dotnet/corefx/issues/28961 and https://github.com/dotnet/wcf/issues/943

Without this NTLM authentication will not work. In the past that would impact only NegotiateStream but in 2.1 this also impacts HTTPClient so the exposure is bigger.

---

@MichaelSimons commented on [Wed Apr 11 2018](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/49#issuecomment-380548032)

@wfurt - Can you clarify which specific images you want `gss-ntlmssp` added to?

---

@wfurt commented on [Wed Apr 11 2018](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/49#issuecomment-380557694)

I look and I was not sure @MichaelSimons. If I know, I would probably craft PR. 

I would like to see it in all .NET Core 2.1*  Linux docker images. 
https://hub.docker.com/r/microsoft/dotnet/

It seems like we publish *stretch* and *bionic* e.g. Debian and Ubuntu. 
Proper place would be somewhere in "runtime-deps".
It seems like arm32 and arm64 exist as well - but I did not test the actual functionality. 

Is that sufficient information? 

---

@MichaelSimons commented on [Wed Apr 11 2018](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/49#issuecomment-380569549)

@wfurt - thanks for the clarification.  I was suspecting you meant the microsoft/dotnet images but wasn't certain.

**Comment by wfurt** [comment]
cc: @karelz

**Comment by MichaelSimons** [comment]
FWIW adding `gss-ntlmssp` to the `2.1.0-preview2-runtime-deps-stretch-slim` image adds 2 MB so the size impact is minimal.

**Comment by MichaelSimons** [comment]
@wfurt - What changes are needed if any to get NTLM authentication working on Alpine?

**Comment by MichaelSimons** [comment]
Per the discussion in https://github.com/dotnet/core-setup/issues/4030, since this is not being added to the native installers, we will not add it to the runtime-deps image.

**Comment by andycode112** [comment]
My program has this problem,it is a dotnet core application and running on docker container of linux.
when it request tfs api, I am got the error:

One or more errors occurred. (GSSAPI operation failed with error - An invalid status code was supplied (Unknown error).)","Code":"999","DocURL":null,"RequestUri":"/api/CodeVersionCtl/GetProjects","RequestBody":"","Result":"System.AggregateException: One or more errors occurred. (GSSAPI operation failed with error - An invalid status code was supplied (Unknown error).) ---> System.ComponentModel.Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (Unknown error).\n   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credentia

**The source code**
public List<TfsProject> GetProjects()
        {
            string projecturl = "http://**.**.**.**:8080/tfs/defaultcollection/_apis/projects";
            HttpClient mywebclient = TfsService.GetHttpClient(projecturl);
            var responsemsg = mywebclient.GetAsync(projecturl);
            string result = responsemsg.Result.Content.ReadAsStringAsync().Result;
            JObject jo = (JObject)JsonConvert.DeserializeObject(result);
            List<TfsProject> list = JsonConvert.DeserializeObject<List<TfsProject>>(jo["value"].ToString());
            return list;
        }

        private static HttpClient GetHttpClient(string url)
        {
            var uri = new Uri(url);
            var credentialsCache = new CredentialCache { { uri, "NTLM", new NetworkCredential("user", "pwd", "***.com") } };
            var handler = new HttpClientHandler { Credentials = credentialsCache };
            var httpClient = new HttpClient(handler) { BaseAddress = uri };
            httpClient.DefaultRequestHeaders.ConnectionClose = false;
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            ServicePointManager.FindServicePoint(uri).ConnectionLeaseTimeout = 60 * 1000;  // Close connection after one minutes

            return httpClient;
        }
