### ISSUE TITLE
Image not updated to latest version for tag aspnet:7.0-cbl-mariner2.0-distroless

### ISSUE THREAD

**Issue by sebader** [dotnet/dotnet-docker#4780]
### Describe the Bug

I just noticed that the image

**mcr.microsoft.com/dotnet/aspnet:7.0-cbl-mariner2.0-distroless** 

is still equivalent to

**mcr.microsoft.com/dotnet/aspnet:7.0.5-cbl-mariner2.0-distroless**

and not to the latest version 7.0.9. I believe this is a bug?!

### Steps to Reproduce

    docker inspect mcr.microsoft.com/dotnet/aspnet:7.0.9-cbl-mariner2.0-distroless
    => sha256:9b43f11eae6a0c2906519bf8ed61973e34057170b0388dce2f52b242f10ac1e6

    docker inspect mcr.microsoft.com/dotnet/aspnet:7.0.5-cbl-mariner2.0-distroless
    => sha256:0651e77910b8ff1e06fca00229863382a20c1591f478b7b219f9fd525e5646f0

    docker inspect mcr.microsoft.com/dotnet/aspnet:7.0-cbl-mariner2.0-distroless
    => sha256:9b43f11eae6a0c2906519bf8ed61973e34057170b0388dce2f52b242f10ac1e6

### Output of `docker version`

Client: Docker Engine - Community
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by lbussell** [comment]
Hi, can you run `docker pull mcr.microsoft.com/dotnet/aspnet:7.0-cbl-mariner2.0-distroless` and try again? This is what I get after pulling all 3 images on my dev machine:
```
PS> docker images --no-trunc --filter=reference='mcr.microsoft.com/dotnet/aspnet:7.0.*-cbl-mariner2.0-distroless'

REPOSITORY                        TAG                               IMAGE ID                                                                  CREATED       SIZE
mcr.microsoft.com/dotnet/aspnet   7.0.9-cbl-mariner2.0-distroless   sha256:0651e77910b8ff1e06fca00229863382a20c1591f478b7b219f9fd525e5646f0   8 days ago    121MB
mcr.microsoft.com/dotnet/aspnet   7.0.5-cbl-mariner2.0-distroless   sha256:9b43f11eae6a0c2906519bf8ed61973e34057170b0388dce2f52b242f10ac1e6   7 weeks ago   121MB

PS> docker images --no-trunc mcr.microsoft.com/dotnet/aspnet:7.0-cbl-mariner2.0-distroless

REPOSITORY                        TAG                             IMAGE ID                                                                  CREATED      SIZE
mcr.microsoft.com/dotnet/aspnet   7.0-cbl-mariner2.0-distroless   sha256:0651e77910b8ff1e06fca00229863382a20c1591f478b7b219f9fd525e5646f0   8 days ago   121MB
```

**Comment by sebader** [comment]
ah strange, yes, now it's indeed updated. No idea where stuff still got cached. thanks anyway!
