### ISSUE TITLE
Mariner 1.0 test data?

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4798]
I still see Mariner 1.0 present in test data.

https://github.com/dotnet/dotnet-docker/blob/5354ff3775517aa591761ba893f4afcb8f57476e/tests/Microsoft.DotNet.Docker.Tests/TestData.cs#L24

Should this have been removed in #4770?

**Comment by lbussell** [comment]
Looks like that code is in the main branch: https://github.com/dotnet/dotnet-docker/blob/5354ff3775517aa591761ba893f4afcb8f57476e/tests/Microsoft.DotNet.Docker.Tests/TestData.cs#L24

In fact the Dockerfiles are still on that branch too: https://github.com/dotnet/dotnet-docker/blob/5354ff3775517aa591761ba893f4afcb8f57476e/src/runtime-deps/6.0/cbl-mariner1.0/amd64/Dockerfile#L1

The Mariner 1.0 code is all removed in nightly, and will be removed with the next servicing release: https://github.com/dotnet/dotnet-docker/blob/5215a73f735688dde92e545525dc0cd06c3f780c/tests/Microsoft.DotNet.Docker.Tests/TestData.cs#L23-L28
