### ISSUE TITLE
Run docker images as non-root

### ISSUE THREAD

**Issue by 030** [dotnet/dotnet-docker#4799]
We would like to run the container as a non-root user. Would it be possible to add such a user like Nginx does? What about adding [the same commands](https://github.com/nginxinc/docker-nginx/blob/1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c/stable/debian/Dockerfile#L16C8-L16C41) to the Dockerfiles i.e.:

>     && addgroup --system --gid 101 nginx \
>     && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx

, but then with dotnet instead of nginx?

**Comment by richlander** [comment]
We have done a variation of that for .NET 8. We won't backport the change to earlier versions since it is breaking.

https://devblogs.microsoft.com/dotnet/securing-containers-with-rootless/
