### ISSUE TITLE
Add arm32v7 2.1-aspnetcore-runtime image

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/dotnet-docker#480]
I [recently created](https://github.com/aspnet/Universe/issues/554) a linux-arm version of the aspnetcore shared runtime. I would like to add a linux-arm image containing this runtime, similar to the bionic/arm32v7 image we have for just the netcore runtime.

**Comment by etherealjoy** [comment]
@natemcmaster 
Thanks.
Would there be significant challenges doing this for arm64v8?

**Comment by natemcmaster** [comment]
At the moment, we don't have an arm64v8 build of ASP.NET Core. The challenges are mostly about resources and timing, and arm64 is not a high priority for the aspnet team.

**Comment by etherealjoy** [comment]
Ok.
Would it be worthwhile for me to try to do something like this to create a custom image
Get the blob from here
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-linux-arm64.tar.gz
https://github.com/dotnet/core-setup
It looks like master has a build for Net Core
And put all the aspnetcore inside along with the app?

**Comment by natemcmaster** [comment]
You might get something that partly works, but it will be problematic for anything that calls native code, such as Kestrel which uses libuv. To make that work, we need to re-compile everything in aspnetcore's dependency graph for arm64, which we are not planning to do, at the moment.

**Comment by natemcmaster** [comment]
I won't have time to get to this done for RC1. 

cc @muratg

**Comment by sdmaclea** [comment]
> such as Kestrel which uses libuv

When I was running linux-arm64 ASP.NET Core TechEmpower benchmarks last year.  The native aarch64/arm64 LibUV.so was present in the packages

**Comment by natemcmaster** [comment]
Should be resolved in 2.1.300-rc1 with https://github.com/dotnet/dotnet-docker/pull/506.

Thanks again @sdmaclea!

**Comment by natemcmaster** [comment]
Correction, this was in PR https://github.com/dotnet/dotnet-docker/pull/507
