### ISSUE TITLE
Missing 7.0.10 in mcr.microsoft.com/dotnet/nightly/aspnet

### ISSUE THREAD

**Issue by JaroslavMajera** [dotnet/dotnet-docker#4810]
### Describe the Bug
There is no 7.0.10 tag in aspnet nightly :(.

**Comment by mthalman** [comment]
Those changes are here: https://github.com/dotnet/dotnet-docker/pull/4802. That PR is blocked right now.

cc @lbussel

**Comment by mthalman** [comment]
I'm curious what you're using nightly for?

**Comment by JaroslavMajera** [comment]
We are happy users of distroless images.

**Comment by richlander** [comment]
Curious ... will you switch to chiseled once those are fully supported or is that what you mean?

**Comment by JaroslavMajera** [comment]
We are already using jammy-chiseled.

**Comment by lbussell** [comment]
@JaroslavMajera these images should be available now. Please let us know if you hit any issues.
