### ISSUE TITLE
Remove Kerberos explicit installation from 8.0 Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4844]
Based on the package installation principles provided in https://github.com/dotnet/dotnet-docker/pull/4842, Kerberos should not be listed for installation in any of the 8.0 Dockerfiles. Currently it's only been removed for Alpine as part of https://github.com/dotnet/dotnet-docker/issues/4751.

Relevant points of the Dockerfile templates:

https://github.com/dotnet/dotnet-docker/blob/4484f4b5fcee3e21594b3886b8d6751200c85977/eng/dockerfile-templates/Dockerfile.linux.install-deps#L32

https://github.com/dotnet/dotnet-docker/blob/4484f4b5fcee3e21594b3886b8d6751200c85977/eng/dockerfile-templates/Dockerfile.linux.install-deps#L41

https://github.com/dotnet/dotnet-docker/blob/4484f4b5fcee3e21594b3886b8d6751200c85977/eng/dockerfile-templates/Dockerfile.linux.install-deps#L50

**Comment by mthalman** [comment]
@richlander - You mentioned at https://github.com/dotnet/dotnet-docker/issues/4804#issuecomment-1674019454 that we could include Kerberos in the `extra` images. Still on board with that?

**Comment by mthalman** [comment]
Actually, if we're including them in `extra`, then the removal from the "full" distro images shouldn't be done since we already decided that the packages added in `extra` would also be represented in the full images.

**Comment by mthalman** [comment]
> @richlander - You mentioned at https://github.com/dotnet/dotnet-docker/issues/4804#issuecomment-1674019454 that we could include Kerberos in the `extra` images. Still on board with that?

After discussion, we settled on not including Kerberos in the `extra` images since it's such an edge case.

**Comment by lbussell** [comment]
This is fixed in https://github.com/dotnet/dotnet-docker/pull/4860
