### ISSUE TITLE
No base images for nightly builds of rc.2

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/dotnet-docker#4871]
I'm trying to use SDK container build to build ASP.NET Core projects into containers targeting nightly rc.2 builds.

My *global.json* file looks like:

```json
{
  "sdk": {
    "version": "8.0.100-rc.2.23462.3",
    "allowPrerelease": true,
    "rollForward": "latestFeature"
  }
}
```

The *Directory.Build.props* in my solution directory looks like:

```xml
<Project>
  <PropertyGroup>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/aspnet:8.0</ContainerBaseImage>
  </PropertyGroup>
</Project>
```

And I publish my projects by running `dotnet publish` in the solution directory:

```
dotnet publish -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerRegistry=$loginServer
```

This seems to result in containers images with an rc.1 runtime build though, so the apps fail to start due to missing the rc.2 version of the runtime they expect. I tried using `mcr.microsoft.com/dotnet/nightly/aspnet:8.0-preview` as well and got the same result.

**Comment by baronfel** [comment]
Having nightly/bleeding-edge images available in some form would be very helpful for the SDK container tests. Right now we pin to the 'N-1' version to test against.

**Comment by richlander** [comment]
> Right now we pin to the 'N-1' version to test against.

Ouch! I didn't realize that. Let's fix that.

**Comment by lbussell** [comment]
These will be available when https://github.com/dotnet/dotnet-docker/pull/4869 is merged. It is on auto-merge now. The SDK build is slightly behind, `8.0.100-rc.2.23462.28` instead of `.3`, but it is updated daily from `dotnet/installer`.

**Comment by tmds** [comment]
This relates to: https://github.com/dotnet/sdk/issues/32099.

> This seems to result in containers images with an rc.1 runtime build though, so the apps fail to start due to missing the rc.2 version of the runtime they expect.

To target an image which may have an older version you can add `RuntimeFrameworkVersion`. This will run on rc1 and higher:

```xml
<TargetFramework>net8.0</TargetFramework>
<RuntimeFrameworkVersion>8.0.0-rc.1</RuntimeFrameworkVersion>
```

**Comment by lbussell** [comment]
These should be available now: https://mcr.microsoft.com/en-us/product/dotnet/nightly/sdk/tags
