### ISSUE TITLE
Make VerifyComplexAppSample Test a [Theory]

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4873]
Looking at the VerifyComplexAppSample test, there are two concerns:

1. The `complexapp` sample Dockerfile uses the multi-platform tags and therefore won't build on Windows in .NET 8 due to https://github.com/dotnet/dotnet-docker/issues/4492:

    https://github.com/dotnet/dotnet-docker/blob/c09ce8b720090c91933e4bd380bd1baa3c89f3d3/samples/complexapp/Dockerfile#L1-L3

2. The test is a `[Fact]`, and therefore runs once per leg but uses only one base image, the multi-platform image, which is Debian. The Dockerfile should be amended to support multiple different images and the test should be amended to test across supported operating systems like the other sample tests.

    https://github.com/dotnet/dotnet-docker/blob/c09ce8b720090c91933e4bd380bd1baa3c89f3d3/tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs#L92-L93

**Comment by mthalman** [comment]
[Triage]
The Dockerfile is meant to be a sample and the `8.0` tag was chosen for simplicity. Modifying the Dockerfile too drastically to support different test environments isn't really the approach we want. It's just a matter of making sure the Dockerfile can be built.

It's not necessary to provide a Windows-compatible Dockerfile as the main intent of the sample is to demonstrate a multi-project solution and how those get composed with a Dockerfile.
