### ISSUE TITLE
Update 2.1 Alpine images to be based on to latest

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#488]
The 2.1 preview Alpine images are based on 3.6 - e.g. https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/alpine/amd64/Dockerfile.  This should be changed to the latest version of Alpine - 3.7.  Depending on when 2.1 ships, 3.8 may be available.

This change is dependent on the completion of https://github.com/dotnet/core-setup/issues/3817

**Comment by richlander** [comment]
This is "edge" in https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Comment by yuleyule66** [comment]
Alpine images are not supported Culture ?

**Comment by MichaelSimons** [comment]
[Globalization is disabled](https://github.com/dotnet/announcements/issues/20) by default with Alpine images in order to produce smaller images. You can re-enable globalization if your application relies on it.  See the [Alpine samples](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/README.md#build-and-run-the-sample-for-alpine-with-docker) for how to do this.

**Comment by robertmiles3** [comment]
Any ETA on getting the dotnet docker images to Alpine 3.8? Looks like it came out about 6 weeks ago so was just wondering (am needing it because it bumps chromium from v61 to v68).

**Comment by MichaelSimons** [comment]
@robertmiles3 - The Docker images for Alpine 3.8 are currently blocked on .NET Core officially supporting 3.8.  This is actively being worked on.  I don't have an ETA as of now.

**Comment by robertmiles3** [comment]
Gotcha, thanks for the update.

**Comment by altinnadmin** [comment]
@robertmiles3 Isn't 3.8 already supported?

Ref. https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
NET Core 2.1 is supported on the following Linux distributions/versions:
- Alpine Linux 3.7 **or later versions** - 64-bit

**Comment by robertmiles3** [comment]
@altinnadmin Yes, 3.8 is supported for runtimes but that's not what I'm referring to. I'm referring to the base `dotnet` docker images getting bumped up to 3.8.

**Comment by MichaelSimons** [comment]
Closing this issue and using #742 to track the Alpine 3.8 specific images.
