### ISSUE TITLE
Changes needed for .NET 8 GA

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4897]
- [x] Move `latest` tag to .NET 8 images
- [x] Update "Featured Tags" section to list `8.0` tag as "Long-Term Support"
- [x] Add Chiseled 6.0/7.0 images and test data to main

**Comment by mthalman** [comment]
[Triage]
The Featured Tag updates can be made in nightly after the RC2 release.

The `latest` tag changes already exist in nightly and that change would need to be made the day of the GA release.

**Comment by lbussell** [comment]
Edited the checklist to include Chiseled release plans.

**Comment by xendren** [comment]
When will the official .Net 8 docker images be available from Dockerhub?

**Comment by MichaelSimons** [comment]
The images are available now.

**Comment by lbussell** [comment]
This issue was completed with https://github.com/dotnet/dotnet-docker/pull/4993. For anyone interested in .NET 8 images, please see the announcement: [".NET 8.0 Container Images Now Available"](https://github.com/dotnet/dotnet-docker/discussions/4995).
