### ISSUE TITLE
Need general documentation page for chiseled/distroless containers

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#4914]
This documentation should highlight the benefits of this container type as well as explain the differences from the "distrofull" images. There should also be a troubleshooting section to explain some of the specific types of issues users can run into with these containers.

Differences to highlight:

* Run as non-root by default
* No shell

One very common issue is that people will run into the following error because there's no shell: `stat /bin/sh: no such file or directory`. That should be specifically called out and explain things.

Some other related documentation issues that can be incorporated into this:

* https://github.com/dotnet/dotnet-docker/issues/4323
* https://github.com/dotnet/dotnet-docker/issues/4811

**Comment by lbussell** [comment]
[Triage] Since we are releasing publicly supported distroless images with .NET 8.0, this documentation is needed soon. It would be nice to have the documentation ready to point to from any release announcements that we decide to post.

**Comment by lbussell** [comment]
This was completed with https://github.com/dotnet/dotnet-docker/pull/4968.
