### ISSUE TITLE
aspnetcore example has wrong port number in documentation

### ISSUE THREAD

**Issue by dsolovay** [dotnet/dotnet-docker#4943]
### Describe the Bug

The online [documentation](https://mcr.microsoft.com/en-us/product/dotnet/samples/about) for the `aspnetapp` sample lists port 80, but this should be port 8080:

> Type the following command to run a sample web application:
       `docker run -it --rm -p 8000:80 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp`
> After the application starts, navigate to http://localhost:8000 in your web browser.

 This should be corrected to:
 
> Type the following command to run a sample web application:
       `docker run -it --rm -p 8080:8080 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp`
> After the application starts, navigate to http://localhost:8080 in your web browser.
 

### Steps to Reproduce

1. Run `docker run -it --rm -p 8000:80 --name aspnetcore_sample mcr.microsoft.com/dotnet/samples:aspnetapp`
2. Navigate to `https://localhost:8000`. 
Site does not load.

### Other Information

docker image inspect shows:

"ASPNETCORE_HTTP_PORTS=8080"

Noted on image ID: 6b22c53fd890

### Output of `docker version`

Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 31
  Running: 0
  Paused: 0
  Stopped: 31
 Images: 19
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: error
  NodeID: 
  Error: error while loading TLS certificate in /var/lib/docker/swarm/certificates/swarm-node.crt: certificate (1 - rmzjjzr2t3zcydchrvk82jwb1) not valid after Fri, 12 May 2023 05:47:00 UTC, and it is currently Thu, 12 Oct 2023 06:10:47 UTC: x509: certificate has expired or is not yet valid: 
  Is Manager: false
  Node Address: 192.168.65.3
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 3.79GiB
 Name: docker-desktop
 ID: C35V:MI7L:RPT6:TRR3:KC2U:TKEQ:GMMA:35GY:VIZL:2YIL:BVRJ:7IYR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 50
  Goroutines: 55
  System Time: 2023-10-15T20:54:42.9698959Z
  EventsListeners: 5
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by lbussell** [comment]
@dsolovay, Thanks for your contribution. This has been fixed and the new readmes should be pushed the next time we publish new images.
