### ISSUE TITLE
PR validation tests are using publicly available images for tests instead of local just-built images on arm32

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4950]
### Describe the Bug

Let's look at [this blocked PR](https://github.com/dotnet/dotnet-docker/pull/4948). Dig into the `fx_dependent_app` tests for .NET 8.0 alpine3.18, which succeeded: https://dev.azure.com/dnceng-public/public/_build/results?buildId=441781&view=ms.vss-test-web.build-test-results-tab

We get the following output during testing: 
```
#5 [fx_dependent_app 1/3] FROM mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine3.18-arm32v7@sha256:c0fd6edd4bb56c1cf506e9b335e3ebf1f16a452bd75c4b0a0671a7536843ea41
#5 sha256:56f722f0720b08a123ef5fc753751eaecc2c478511b2fc45b6b38d1cfe899339
#5 resolve mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine3.18-arm32v7@sha256:c0fd6edd4bb56c1cf506e9b335e3ebf1f16a452bd75c4b0a0671a7536843ea41 done
#5 sha256:c0fd6edd4bb56c1cf506e9b335e3ebf1f16a452bd75c4b0a0671a7536843ea41 1.16kB / 1.16kB done
#5 sha256:3e7c546320e54931cdbcef70c777c9f8ad34dcb3979f6a8e1ba1bfa28e612208 2.60kB / 2.60kB done
#5 DONE 0.1s
```

Hmm.. that image, `mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine3.18-arm32v7@sha256:c0fd6edd4bb56c1cf506e9b335e3ebf1f16a452bd75c4b0a0671a7536843ea41` is publicly available right now. But this build hasn't been published as of this writing because the PR is blocked. Furthermore, that image should've been rebuilt in the previous stage in the PR validation.

Double-check [the build output](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441781&view=logs&j=bd199eb0-50e9-5ce4-184f-fffdfec41943&t=480a4c3b-598d-5fe4-eb31-f69a914fcb64):

```
IMAGES BUILT
------------
mcr.microsoft.com/dotnet/nightly/runtime:8.0.0-alpine3.18-arm32v7
mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine3.18-arm32v7
mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine-arm32v7
...
```

It's been re-built. Let's check the runtime in the image that we pulled during testing.
```
PS> docker run --rm mcr.microsoft.com/dotnet/nightly/runtime:8.0-alpine3.18-arm32v7@sha256:c0fd6edd4bb56c1cf506e9b335e3ebf1f16a452bd75c4b0a0671a7536843ea41 dotnet --list-runtimes  

WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
Microsoft.NETCore.App 8.0.0-rtm.23509.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

That's the current runtime version from `dotnet-docker/nightly`: https://github.com/dotnet/dotnet-docker/blob/b1341c6248e8ffe0a4d57bd6bc7a0b849d7c06fc/manifest.versions.json#L184

NOT from dotnet docker bot's update branch: https://github.com/dotnet-docker-bot/dotnet-docker/blob/c76bca9389afa2228ddc4b5cdbe143fe8e6743bb/manifest.versions.json#L184

### Other Information

I am wondering if this ever happened before. It seems build-cache related. We may need to implement a file-based cache to pass images between PR validation builds and tests, as documented at https://github.com/docker/buildx/blob/v0.8.0/docs/reference/buildx_build.md#build-context.

This could be a consequence using different combinations or versions of BuildKit/buildx due to:
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/918
- This commit: https://github.com/dotnet/dotnet-docker/pull/4911/commits/a3f9af7384a1821cd93b44a5bf257da1694477b1

Maybe relevant: 
- https://github.com/docker/buildx/issues/795.

We should probably write a test that reads the manifest.json and ensures the values in there are defined in the dockerfiles as environment variables or are actually installed. Similar to the VerifyEnvironmentVariables test, but that test doesn't actually check that the version in manifest.versions.json lines up with the images. 

https://github.com/dotnet/dotnet-docker/blob/cba834e07e9002bfae174eb970ad1d1c24027bbd/tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs#L40-L50

**Comment by mthalman** [comment]
This seems related to the fact that it's happening in the arm32 job and doesn't happen on the arm64 job. The arm32 job is running on an arm64 agent, using an arm64 test container, but attempting to access arm32 image names. I wonder if you would get different results if you built/ran the test container to run under emulation for arm32 instead.

**Comment by lbussell** [comment]
[Triage] This was fixed with https://github.com/dotnet/dotnet-docker/pull/4948. It should be ported to main before the next release.
