### ISSUE TITLE
Add Mariner .NET images to "Support tags only" section on MAR

### ISSUE THREAD

**Issue by htaubenfeld** [dotnet/dotnet-docker#5004]
### Describe the Problem

As it stands, the Mariner .NET images are hidden to external users on MAR.

### Describe the Solution

Change the metadata of the Mariner .NET images so that they appear in the "Supported tags only" section on MAR. Customers can expect the same level of support for these images as they do for .NET images built on Ubuntu.

**Comment by lbussell** [comment]
As mentioned in https://github.com/dotnet/dotnet-docker/issues/4701, we should remove the tag listings from the internal Mariner documentation and instead point internal customers to the MAR tag listing.
