### ISSUE TITLE
Reconsider supporting aspnet and runtime chiseled-aot and chiseled-extra for Ubuntu

### ISSUE THREAD

**Issue by Cjewett** [dotnet/dotnet-docker#5014]
We ran into an issue recently where we swapped to jammy-chiseled images for our applications and got an error where Microsoft.SqlClient routinely failed. It doesn't support Globalization Invariant Mode and you can set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to true or false and it won't work in either scenario with jammy-chiseled. aspnet and runtime jammy-chiseled-extra would have solved the problem while keeping dependencies to a minimum though.

https://github.com/dotnet/SqlClient/issues/2206
https://github.com/dotnet/SqlClient/issues/220

**Comment by JiriZidek** [comment]
CodePages (ICU) and TZ tzdata are needed. Might be there a guide how to add them to a resulting image ?

**Comment by DanielLaberge** [comment]
Globalization is unfortunately required in a Web Frontend in order to render localized dates and numbers, and to make use of .resx files.

Related discussion: https://github.com/dotnet/dotnet-docker/issues/4955

**Comment by joegoldman2** [comment]
The primary aim of the AOT image, as well as distroless images in general, is to keep the container size as minimal as possible. These images are designed to include only the essential components needed to run a specific application, without unnecessary dependencies or runtime environments.

Providing a separate .NET runtime and ASP.NET Core runtime images for these use cases would contradict the fundamental purpose of these images. Instead, why not leveraging the runtime-deps image (the extra variant that includes globalization libraries) and publishing the application as a self-contained entity? This allows you to embed the runtime and ASP.NET framework dependencies directly into your application, resulting in a self-contained, standalone container. You can find a sample [here](https://github.com/richlander/container-workshop/blob/main/dockerfile-samples.md#globalapp) from @richlander.

**Comment by JiriZidek** [comment]
> AOT image, as well as distroless images in general

In fact ASP.NET 8 does not support common app: AUTH, MVC or SIGNALR are not compatible - thus AOT looks like a dead-end when considering chiseled image. For me docker file example how to add globalisation support but not using AOT and trimming would be helpful.

**Comment by joegoldman2** [comment]
> > AOT image, as well as distroless images in general
> 
> In fact ASP.NET 8 does not support common app: AUTH, MVC or SIGNALR are not compatible - thus AOT looks like a dead-end when considering chiseled image. For me docker file example how to add globalisation support but not using AOT and trimming would be helpful.

You don't need to publish your app as Native AOT. Just self-contained + runtime-deps (the -extra variant) should work for all the workloads you describe.

**Comment by joegoldman2** [comment]
Without `PublishTrimmed=true`.

**Comment by joegoldman2** [comment]
Without `-p PublishTrimmed=true`.

**Comment by JiriZidek** [comment]
> They are installed directly in the -extra variant image

Aha ! That's what I have been voting for ! So it really exists. This was from MSFT communication not clear to me. I thought it was just an idea... Thx

**Comment by orjan** [comment]
If we're doing a `self contained` we will ship the framework itself for every single build for every application, hence the request for the `-extra` image with batteries included. The would mean that we'll only ship the application for every build and application. We can't just look at a single build in isolation.

**Comment by logicaloud** [comment]
Adding my vote. We use a shared framework deployment for a number of similar containers and several need ICU/TZDATA. Ideally they would share the same base image, i.e. "aspnet-jammy-chiseled-extra". Currently we manually build our own "extra" base image along the lines of #21, but would very much prefer an official source of such an image. Then we know it is up-to-date, without also diving into build triggers, etc., to keep the hand-crafted base image up-to-date with latest security patches

**Comment by nikolai-mb** [comment]
We have several microservices all using EF Core which requires ICU through the SqlClient dependency. Having a aspnet/jammy-chiseled-extra image would allow us to slice 40+ MB of every single container by not using self contained publish.

Are projects using EF Core (or SqlClient) really in such a minority that the aspnet variant is not justified? Looked at 10 services so far and only one can use the aspnet/jammy-chiseled variant, all others are using either EF Core or Hangfire with a SqlClient dependency.

**Comment by lbussell** [comment]
Hi folks, we're working on the Ubuntu Chiseled .NET Runtime/ASP.NET images now thanks to your feedback. You can track the work in https://github.com/dotnet/dotnet-docker/issues/5021. You should expect these to ship and be officially supported with the January .NET 8 servicing release.

**Comment by lbussell** [comment]
[Triage] These images are available in the [nightly aspnet](https://mcr.microsoft.com/product/dotnet/nightly/aspnet/about) and [nightly runtime](https://mcr.microsoft.com/product/dotnet/nightly/runtime/about) repos now. They will be officially supported with the next .NET servicing release (Jan).

**Comment by preardon** [comment]
I need TZData as well, ICU could also be helpful

**Comment by joegoldman2** [comment]
> Hi folks, we're working on the Ubuntu Chiseled .NET Runtime/ASP.NET Core images now thanks to your feedback. You can track the work in #5021. You should expect these to ship and be officially supported with the January .NET 8 servicing release.

Great news!

I see that the .NET Runtime/ASP.NET Core distroless images with globalization support (-extra variant) are only available with Ubuntu Chiseled. Do you also plan cbl-mariner or alpine? And more generally, is there a guideline available regarding the choice of the distribution to use?

**Comment by lbussell** [comment]
> Do you also plan cbl-mariner or alpine? And more generally, is there a guideline available regarding the choice of the distribution to use?

[Triage] @joegoldman2, there are no plans currently to add `-extra` images for Alpine or Azure Linux (CBL Mariner) runtime and aspnet images. For Alpine, it's easy to add new packages using APK if needed. Between Azure Linux and Chiseled, our goal was to take a targeted approach and only offer images that are actively in demand by the community.

There is currently no guidance for choosing between the distros we offer. The closest we have is the [Supported Platforms](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md) documentation, but that's more about *what* we offer. @mthalman or I will file an issue to create some guidance there.

**Comment by lbussell** [comment]
These images are now available in the main `aspnet` and `runtime` repos. Please see the announcement: [Ubuntu Chiseled runtime and aspnet images are now available in the extra variant (#5092)](https://github.com/dotnet/dotnet-docker/discussions/5092).
