### ISSUE TITLE
After upgrading to 8.0, dotnet restore takes too much time

### ISSUE THREAD

**Issue by mcanzerini** [dotnet/dotnet-docker#5019]
### Describe the Bug

With dotnet/sdk:8.0, `dotnet restore` in a container takes way too much time (45 minutes to restore a project).

### Other Information

This only happens in my gitlab ci, not in local. It is probably due to limited resources available for the gitlab runner. 
The ops in charge of the runner tells my that the CPU usage was above 100% during the long restore.

```
$ dotnet restore --no-cache
Restored /builds/**/A.csproj (in 10.11 min).
Restored /builds/**/B.csproj (in 14.13 min).
Restored /builds/**/C.csproj (in 2.03 min).
Restored /builds/**/D.csproj (in 36.08 min).
```

With dotnet/sdk:7.0, the project is restored in 45 seconds.

If I add the option `-v diagnostic`, the process is extermely long during this kind of operations:

```
...
Acquiring lock for the installation of System.Diagnostics.Tracing 4.3.0 (TaskId:91)
Acquired lock for the installation of System.Diagnostics.Tracing 4.3.0 (TaskId:91)
Installed Xamarin.UITest 4.2.0 from https://my.artifactory/artifactory/api/nuget/nuget/ with content hash <xxx>. (TaskId:91)
Acquiring lock for the installation of System.Globalization 4.3.0 (TaskId:91)
Acquired lock for the installation of System.Globalization 4.3.0 (TaskId:91)
Assembly loaded during TaskRun (NuGet.Build.Tasks.RestoreTask): System.Diagnostics.StackTrace, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/System.Diagnostics.StackTrace.dll, MVID: 9f2e188b-5afc-4c69-84d1-4627254ba14f, AppDomain: [Default]) (TaskId:91)
...
```

Any guess on what happen here?

Thanks

**Comment by lbussell** [comment]
[Triage] Hi @mcanzerini, we're not aware of any Docker-specific changes in .NET 8.0 that could be causing this issue with NuGet restore. I would recommend that you file an issue in the [NuGet/Home](https://github.com/NuGet/Home) repo.
