### ISSUE TITLE
Add Ubuntu Chiseled `extra` images for .NET Runtime and ASP.NET Core

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5021]
### Describe the Problem

There is a desire to use globalization libraries in combination with framework-dependent deployments on Ubuntu Chiseled:

- https://github.com/dotnet/dotnet-docker/issues/5014
- https://github.com/dotnet/dotnet-docker/discussions/4821#discussioncomment-7584491

### Describe the Solution

Add Ubuntu Chiseled `-extra` images for .NET Runtime and ASP.NET

**Comment by richlander** [comment]
Related: https://github.com/dotnet/dotnet-docker/issues/5014

Just wanting GH to reference the related issues for discoverability.

**Comment by lbussell** [comment]
[Triage] As mentioned in https://github.com/dotnet/dotnet-docker/issues/5014#issuecomment-1834393550, these images are available now in the [nightly aspnet](https://mcr.microsoft.com/product/dotnet/nightly/aspnet/about) and [nightly runtime](https://mcr.microsoft.com/product/dotnet/nightly/runtime/about) repos. They will be officially supported with the next .NET servicing release (Jan).

**Comment by mantasaudickas** [comment]
If I get it right: alpine3.18-extra (nightly) includes these packages:
- icu-data-full
- icu-libs
- tzdata

and chiseled-extra:
- libicu70_libs
- tzdata_zoneinfo
- tzdata_zoneinfo-icu

Are these covering the same ICU/Timezone aspects in .NET apps?

**Comment by lbussell** [comment]
Yes, you can check the packages installed in the Dockerfiles themselves:

https://github.com/dotnet/dotnet-docker/blob/da5a045dc5dc64d18c8177fadb493da1c86982dc/src/runtime-deps/8.0/alpine3.18-extra/amd64/Dockerfile#L11-L21

https://github.com/dotnet/dotnet-docker/blob/da5a045dc5dc64d18c8177fadb493da1c86982dc/src/runtime-deps/8.0/jammy-chiseled-extra/amd64/Dockerfile#L27-L39

And you can inspect the contents of each image in the distros' respective package repositories. For example:
- [Alpine 3.18 icu-libs](https://pkgs.alpinelinux.org/contents?branch=v3.18&name=icu%2dlibs&arch=x86_64&repo=main)
- [Ubuntu 22.04 Chiseled libicu70_libs](https://github.com/canonical/chisel-releases/blob/ubuntu-22.04/slices/libicu70.yaml)

We aspire for these images be functionally equivalent. If you find that they aren't, please file an issue here.

**Comment by garrettsutula** [comment]
Would it be possible to make the same for earlier versions of .NET e.g. 6.0?

Helpful for the same reasons really - I expect to update projects on older versions of the .NET framework but don't have that done yet.

**Comment by mantasaudickas** [comment]
> We aspire for these images be functionally equivalent for running .NET apps (aside from the lack of package manager and shell in Ubuntu Chiseled). If you find that they aren't, please file an issue.

Sorry, but for me still not clear.. I get that from functionality point of view these will be equivalent.. but what about data?
In alpine-extra we have icu-data-full... so which package in chiseled-extra is equivalent to it?

**Comment by ElkRom** [comment]
Hi, 
Sorry for asking such stupid question, but when do you plan to release this image?

**Comment by MichaelSimons** [comment]
> Hi, Sorry for asking such stupid question, but when do you plan to release image?

They will be released today - See https://github.com/dotnet/dotnet-docker/issues/5014#issuecomment-1834393550.

**Comment by lbussell** [comment]
These images are now available in the main `aspnet` and `runtime` repos. Please see the announcement: [Ubuntu Chiseled runtime and aspnet images are now available in the extra variant (#5092)](https://github.com/dotnet/dotnet-docker/discussions/5092).

**Comment by ElkRom** [comment]
Great news,
Thanks a lot.
Have a nice day

ср, 10 січ. 2024 р. о 00:04 Logan Bussell ***@***.***> пише:

**Comment by coffeesandwitch** [comment]
Looking at using the '-jammy-chiseled-extra' package for our deployments, currently we are using the bloated '-jammy' so we can set the timezone within the dockerfile. would the new -extra package rely soly upon the regional settings as configured in .net?
