### ISSUE TITLE
Dotnet Path Entry not preserved when cross compiling on linux.

### ISSUE THREAD

**Issue by jag-eagle-technology** [dotnet/dotnet-docker#5026]
### Describe the Bug

If a .net application is build on linux and then the results copied into a windows container, dotnet is not available in the path.

### Steps to Reproduce

To allow building multiple versions of both linux and windows containers I am building my ASP.NET image in a linux environment and then copying the resulting files into a asp.net-nanoserver-1809 image. An example of the dockerfile I'm using to to this:
```
# Set BASE_IMAGE and SDK_IMAGE build arguments with default values
ARG BASE_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0
ARG SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0

FROM ${BASE_IMAGE} AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Build the application
FROM --platform=$BUILDPLATFORM ${SDK_IMAGE} AS build
WORKDIR /src
COPY ["Gateway/Gateway.csproj", "Gateway/"]
RUN dotnet restore "Gateway/Gateway.csproj"
COPY . .
WORKDIR "/src/Gateway"
RUN dotnet build "Gateway.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "Gateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Build the final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gateway.dll"]

```

And a simplified version of the build command I am using (the full script compiles multiple versions of windows and both amd64/arm linux, then combines into a multiarch manifest running within an ADO Pipeline):

```
docker buildx build --platform windows/amd64 --push --pull --build-arg BASE_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809 dev-nanoserver-1809 -f src/Gateway/Dockerfile src
```
The docker image fails to run with the error **Error response from daemon: container [removed] encountered an error during hcs::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified.**

And when I launch a terminal in the container and echo path I get the result **c:\Windows\System32;c:\Windows** - without dotnet included.

### Other Information

- buildx is being run on an Azure Pipeline in a microsoft hosted build agent on ubuntu-latest

### Output of `docker version`

Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:39 2023
  OS/Arch:          windows/amd64
  Experimental:     false

### Output of `docker info`

Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 24
  Running: 1
  Paused: 0
  Stopped: 23
 Images: 25
 Server Version: 24.0.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22000 (22000.1.amd64fre.co_release.210604-1628)
 Operating System: Microsoft Windows Version 21H2 (OS Build 22000.2600)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.8GiB
 Name: ET946567
 ID: 37808e2a-5ef9-4553-8d1b-0329dc2fc1b3
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by lbussell** [comment]
[Triage] @jag-eagle-technology, Given that this seems to be a Docker issue and not a .NET issue, if you're still interested in finding a solution I would recommend you file an issue on [containerd](https://github.com/containerd/containerd) or [moby/buildkit](https://github.com/moby/buildkit).
