### ISSUE TITLE
Include `libatomic1` in the `dotnet/sdk` base images

### ISSUE THREAD

**Issue by baronfel** [dotnet/dotnet-docker#5033]
### Describe the Problem

`libatomic1` is a dependency of nodejs, which is a bundled dependency of emsdk and the wasm-tools workload. This dependency is not present in the `dotnet/sdk:8.0` image, and so projects that install the wasm-tool workload fail to build. An example of what this looks like is https://github.com/dotnet/runtime/issues/95477.

### Describe the Solution

Ideally `libatomic1` would be added as a package dependency for the `sdk` images on Ubuntu, and matching dependencies would be added on other distros that we produce SDK images for (e.g. alpine).

cc @lewing @directhex

**Comment by lbussell** [comment]
`libatomic1` is only ~45kb on disk on Debian Bookworm (81kb on arm64), so we should definitely add this to cover wasm scenarios. We should also include a test for this scenario in the future.

**Comment by lbussell** [comment]
This is done with https://github.com/dotnet/dotnet-docker/pull/5066.

Follow-ups are:
- https://github.com/dotnet/dotnet-docker/issues/5084
- https://github.com/dotnet/dotnet-docker/issues/5076
