### ISSUE TITLE
AOT variant for SDK image, or include `clang` and `zlib1g-dev` packages in the image

### ISSUE THREAD

**Issue by hach-que** [dotnet/dotnet-docker#5035]
### Describe the Problem

When building an AOT application using `mcr.microsoft.com/dotnet/sdk:8.0`, you get a failure unless you install the `clang` and `zlib1g-dev` packages.

### Describe the Solution

Either the `sdk:8.0` image should include `RUN apt-get install -y clang zlib1g-dev`, or there should be an AOT variant like `sdk:8.0-aot` that includes these extra packages.

### Additional Context

Without an additional image that includes the dependencies needed for building AOT applications, builds using the `sdk:8.0` image have to run `apt-get update && apt-get install -y clang zlib1g-dev` first, which slows the build down.

**Comment by MichaelSimons** [comment]
Please see the (Preview) Native AOT Images section of the [.NET 8.0 Container Announcement](https://github.com/dotnet/dotnet-docker/discussions/4995) for information about an experimental aot sdk image.
