### ISSUE TITLE
[Arm64/Linux] 3.0 docker images

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/dotnet-docker#504]
@richlander @MichaelSimons It would be nice to start publishing arm64 docker images so more people can dogfood linux-arm64.

Is this is the place to do this? Or are there missing prerequisites in a supporting docker repo?

Is it too early for 2.2?

Worklist [added by MichaelSimons]

- [x] runtime-deps images
- [x] runtime images
- [x] aspnetcore-runtime images
- [x] sdk images
- [x] official build infrastructure
- [ ] ~~[Blocked on machine availability] CI~~ tracked with #792

**Comment by sdmaclea** [comment]
cc/ @etherealjoy

**Comment by etherealjoy** [comment]
@sdmaclea 
Thanks a lot. 

> Is it too early for 2.2?
I tried creating the images from the tar files from the master build , and it runs sometimes and sometimes it does not. Usually there is an error from roslyn.compilers.csharp .targets or something and exit. 

I am using linux-arm64 as rid. 
If I understand well,
arm64 cli build is there
arm64 core-setup build is there
runtime deps I used debian stretch
asp-netcore is missing though I have requested a build here
https://github.com/aspnet/Universe/issues/1117

If you guys build it I would test it asap.  I mean TFM 2.2 is available now right?

**Comment by MichaelSimons** [comment]
This is on our radar but our plates are rather full at the moment with a few upcoming releases.  The main work for us is to get build and ci machines in place.  I would hope in a couple weeks we will have builds available in the nightly repo.

**Comment by etherealjoy** [comment]
@MichaelSimons 
Thanks.
>  I would hope in a couple weeks we will have builds available in the nightly repo.

Including aspnet core?

**Comment by MichaelSimons** [comment]
@etherealjoy  - I can't comment on ASPNET.Core.  Obviously aspnet/Universe#1117 is a requirement.

**Comment by etherealjoy** [comment]
@MichaelSimons 
Thank you. Looking forward to it.

**Comment by sdmaclea** [comment]
@etherealjoy
> Usually there is an error from roslyn.compilers.csharp .targets or something and exit

The last daily linux-arm64 cli build I tested, was failing with a segmentation fault in csc.dll.  I wanted to check to see if it was working on x64.  However, when I looked at yesterdays daily build status, everything was red, so I didn't bother debugging further.

Last I looked ASP.NET build support was included in the CLI.  So you should be able to build ASP.NET core projects for arm64.  (When cli is working)

**Comment by MichaelSimons** [comment]
Closing as 3.0 Arm64 images are now available.

**Comment by etherealjoy** [comment]
@MichaelSimons 
Many Thanks for this.
