### ISSUE TITLE
exec /usr/bin/dotnet: exec format error when build for multiplatforms with .net7 and .net8

### ISSUE THREAD

**Issue by wondertalik** [dotnet/dotnet-docker#5041]
### Describe the Bug

I have a macbook m1. So, i tried build a multiplatfrom images(arm64,amd64) with docker and it finished fine. But when i ran image on linux server i got an error `exec /usr/bin/dotnet: exec format error`

### Steps to Reproduce

1. Create default .net8 web api project with name WebApplication11Api
2. Paste to DockerFile

```
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:8.0.0-jammy AS base
ARG TARGETARCH
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0.100-jammy AS build
ARG TARGETARCH
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["WebApplication11Api/WebApplication11Api.csproj", "WebApplication11Api/"]
RUN dotnet restore "WebApplication11Api/WebApplication11Api.csproj" -a $TARGETARCH
COPY . .
WORKDIR "/src/WebApplication11Api"
RUN dotnet build "WebApplication11Api.csproj" -a $TARGETARCH -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "WebApplication11Api.csproj" -a $TARGETARCH --no-restore -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplication11Api.dll"]
```

Build and publish images

```bash
docker buildx create --use --bootstrap && \
docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_CONFIGURATION=Debug --push -t your_registry*.azurecr.io/net8test:v1.0.0 -f ./WebApplication11Api/Dockerfile .
```

The same happens when i build on linux and try to use builded image on my m1 macbook.
If i do not use `--platform=$BUILDPLATFORM` like explained in this [article](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/) the build is stucks on amd64 platform.

### Output of `docker version`

Docker version 24.0.7, build afdd53b

### Output of `docker info`

```
Client:
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     /Users/admin/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /Users/admin/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/admin/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/admin/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     /Users/admin/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /Users/admin/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/admin/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/admin/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/admin/.docker/cli-plugins/docker-scout

Server:
 Containers: 20
  Running: 14
  Paused: 0
  Stopped: 6
 Images: 202
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.663GiB
 Name: docker-desktop
 ID: de2013d4-09a3-4e20-a30e-4573920208bb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by lbussell** [comment]
Hi @wondertalik, you'll get the `exec /usr/bin/dotnet: exec format error` when you try to run an app with an executable format different than the host architecture. For example, trying to run an arm64 image built on your Mac on an amd64 server.

Your issue may be that you are using `--platform=$BUILDPLATFORM` as your `base` image layer. This is telling Docker to use an arm64 base image when you build on your Mac. If you use `--platform=$TARGETPLATFORM` for your `base` layer instead, this will choose the layer's architecture based on what arguments you provide with the `--platform` Docker build argument. See [Cross compilation](https://docs.docker.com/build/building/multi-platform/#cross-compilation) in the Docker docs for more info.

Our samples are also multi-platform, for example: https://github.com/dotnet/dotnet-docker/blob/da5a045dc5dc64d18c8177fadb493da1c86982dc/samples/aspnetapp/Dockerfile#L3-L21

You'll also notice that we don't use `$TARGETPLATFORM` in this sample. This is because when you build multi-arch Dockerfiles, Docker implicitly uses `$TARGETPLATFORM` as the platform for your final output layer. You may also choose to leave `--platform=$TARGETPLATFORM` out of the `base` layer definition - I ran a small test and found that even defining the `base` layer first and using it later in the `final` layer, Docker was able to resolve the correct platform for the final image.

**Comment by wondertalik** [comment]
@lbussell thank you very much. It works. This is a small detail that i was looking for. I definitely need to dive more to the subject.

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-jammy AS base
```

with this line it works like a charm.

**Comment by kjeske** [comment]
@lbussell I'm a bit confused because sample for .NET 8 introduced `--platform=$BUILDPLATFORM` in FROM. I'm trying to build a very simple image on my Mac with M1 for .NET 8 but I'm getting same error like in the initial post here. What's the correct approach to build Dockerfile in this case?

**Comment by AlexandrSargsyan** [comment]
@wondertalik  Please describe how exactly you resolve the issue, I'm stucked on this over day

**Comment by wondertalik** [comment]
> [@wondertalik](https://github.com/wondertalik) Please describe how exactly you resolve the issue, I'm stucked on this over day

check [repo](https://github.com/wondertalik/azure-container-apps/blob/main/src/HttpApi/Dockerfile)

**Comment by richlander** [comment]
```Dockerfile
RUN apt-get update \
    && rm -rf /var/lib/apt/lists/*
```

This doesn't appear to be doing anything.

**Comment by vitaliiopticom** [comment]
> RUN apt-get update \
>     && rm -rf /var/lib/apt/lists/*
> This doesn't appear to be doing anything.

Well yes, until you want to install any package. I used as example to teach our internal team. So can’t be removed.

The certs it’s not required as well. Just nice to have.

It’s not updated repository, will check what I have in latest code
