### ISSUE TITLE
Question/Request: Alpine 3.19

### ISSUE THREAD

**Issue by csrakowski** [dotnet/dotnet-docker#5052]
### Plans to add/update Alpine 3.19

Hello,
Last week Alpine 3.19 was released, bringing with a version bump to a fresh kernel and Raspberry Pi 5 support.
I am very interested in this, and would therefore like to ask if you already have this update on your backlog/roadmap (and I was just unable to find it), or if I could request that update as a "feature request"?

### Describe the Solution

Ideally, I would like to use "official" base images, as released from this project.
In the mean time, I can just bake my own to get started. This is not a blocking issue at all.

### Additional Context

Link to announcement: https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html

**Comment by lbussell** [comment]
Hi @csrakowski, thanks for the issue. I'll try to get these images added to the nightly repo sometime this week.

**Comment by lbussell** [comment]
From https://github.com/dotnet/dotnet-docker/pull/5065#pullrequestreview-1800589317:
> Due to the PowerShell issue we should avoid moving the floating `alpine` tag to 3.19 until it gets fixed.

Relevant issues:
- https://github.com/dotnet/runtime/issues/96155
- https://github.com/PowerShell/PowerShell/issues/20945

**Comment by lbussell** [comment]
Alpine 3.19 images are now available. Please see the announcement at https://github.com/dotnet/dotnet-docker/discussions/5091.

**Comment by csrakowski** [comment]
Thanks @lbussell 🥳
