### ISSUE TITLE
Define doc providing guidance on Linux distros

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5063]
Now that we have public Mariner support, there are four Linux distros:

* Debian
* Ubuntu
* Alpine
* Mariner

There should be guidance for users to understand which distro they should choose to meet their needs. This should include pros/cons associated with each one as well as associated support and lifecycle info.

Related to this, the [supported platforms doc](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md) needs to be updated to include Mariner.

**Comment by lbussell** [comment]
[Triage] Related: https://github.com/dotnet/dotnet-docker/discussions/5709, https://github.com/dotnet/dotnet-docker/issues/5703

**Comment by richlander** [comment]
> This should include pros/cons 

I'm not sure we're responsible for doing this. Does another project do this in a way we find compelling? I think our stance should be: "Hey ... we support four distros. If there's one you like, that's good news!"

**Comment by mthalman** [comment]
We've certainly made recommendations about which to select in regards to size and security though, right?

**Comment by richlander** [comment]
Fair. However, I think that was easier in the past (before chiseled). It's now more about form factor than distro, IMO.
