### ISSUE TITLE
Docker Hub page load errors

### ISSUE THREAD

**Issue by guardrex** [dotnet/dotnet-docker#5064]
The Microsoft ASP.NET Core documentation references the page at ...

https://hub.docker.com/_/microsoft-dotnet

... in our article [Deploy ASP.NET Core apps to Azure App Service: Use Docker with Web Apps for containers](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-8.0&tabs=visual-studio#use-docker-with-web-apps-for-containers).

The link is throwing a warning in our doc build reports, which might be due to any or all of the errors that the page throws on load ... a 401, two 404s, and 405. We like to keep our build reports clean in order to highlight true warnings/errors. Therefore, I've code-fenced the link to Docker Hub for the moment.

If you close as a won't-fix, no worries ... we'll continue to just code-fence the URL in our docs.

**Comment by andygjp** [comment]
Searching for ".net' in https://hub.docker.com today yields this:

![image](https://github.com/dotnet/dotnet-docker/assets/1445933/a596a172-a630-417d-a5a4-663e6310dbee)

And Docker Desktop fails to find anything when searching for the same term.

**Comment by guardrex** [comment]
@andygjp ... I don't understand the relevance to the issue. Do you need to open a new issue for that report? This issue about 401/404/405 errors of the Docker landing page that are triggering .NET docs build errors. I'm just asking if those are errors that can be fixed so that we can link to the page or if they don't want to fix the errors, and we'll just continue to code-fence the links to keep errors out of our doc build system reports.

... and besides that something seems broken at the moment. Attempting to follow the links from the search result page or requesting the page directly result in an error.

https://hub.docker.com/_/microsoft-dotnet

... is throwing ...

![image](https://github.com/dotnet/dotnet-docker/assets/1622880/05dff1e5-79c7-4d70-81c5-d680cc8a10d2)

**Comment by andygjp** [comment]
I didn't realise this was just about build errors - I googled "docker hub dotnet error" and this was the second result.

I thought the problem in the docker hub was related to your issue.

**Comment by andygjp** [comment]
Someone has created an issue for my specific case: #5097

**Comment by lbussell** [comment]
[Triage] We can't fix the errors from the DockerHub page load. They seem to be due to the Microsoft-owned repos on DockerHub being mirrors that point to MAR instead of being hosted on DH. If there's a way to ignore the error without code-fencing that would be ideal, as the page loads fine. But ultimately we can't do much about this.
