### ISSUE TITLE
dotnet restore within a `docker build` hangs indefinitely

### ISSUE THREAD

**Issue by JovialJerboa** [dotnet/dotnet-docker#5085]
### Describe the Bug

Running `dotnet restore` as part of a `docker build` hangs indefintely. If the `dotnet restore` is performed as part of a `docker run` it completes quickly.

### Steps to Reproduce

I've created a minimal repo to illustrate the issue [here](https://github.com/JovialJerboa/dotnet-docker-issue-repo). The `run.ps1` should display the problem.

The repo contains:

1. Basic Dockerfile
2. Basic csproj file
3. A powershell script `run.ps1` which
   - Runs `dotnet restore` as part of a `docker run`. This should complete within a few seconds.
   - Runs `dotnet restore` as part of a `docker build`. This should hang indefintely.

### Other Information

An example of how long I've waited for this to complete
```powershell
=> [3/3] RUN dotnet restore                                                            4241.1s
```

### Things I've tried to resolve this

**NB:** I've tried each of the following in isolation and reverted the changes after they were unsuccessful.

1. Increasing the amount of memory available to wsl2 - [source1](https://stackoverflow.com/questions/57669467/dotnet-restore-incredibly-slow-inside-docker-compose-build) [source2](https://tsuyoshiushio.medium.com/solving-flaky-dotnet-restore-issue-only-on-docker-failed-to-retrieve-information-cd847573c3f2)
2. Disabling BuildKit - [source](https://stackoverflow.com/questions/66839443/how-to-enable-disable-buildkit-in-docker)
3. Disabling Windows Defender - [source](https://github.com/dotnet/dotnet-docker/issues/1697)

### Additional Logging

I've also tried changing the DockerFile to run with `--verbosity diagnostic`
```dockerfile
RUN dotnet restore --verbosity diagnostic
```

Running this build in powershell with all output redirected to a log file, i.e.
```powershell
docker build . *>> .\log.txt
```

I've attached the [log file](https://github.com/dotnet/dotnet-docker/files/13836811/log.txt)

### Output of `docker version`

Client:

 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`

Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.22GiB
 Name: docker-desktop
 ID: 7a1e95a6-76c6-4c2c-8e97-c446c8abd5de
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile

### Windows version
Microsoft Windows
Version 22H2 (OS Build 19045.3803)

**Comment by richlander** [comment]
I'm assuming the Dockerfile doesn't get to `dotnet build` because it is hung at `dotnet restore`. Is that correct?

**Comment by richlander** [comment]
Change your Dockerfile to include `WORKDIR`. It will then work.

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /source
COPY *.csproj .
RUN dotnet restore
```

I have seen this multiple times. NuGet doesn't work from the root.

**Comment by JovialJerboa** [comment]
@richlander that has indeed helped! Thanks so much 😁

Do you know why that changes things? Is running `dotnet restore` at the root triggering it to scan the entire container FS which is just taking a long time?

Also re: this issue, shall I close it given that [13131](https://github.com/NuGet/Home/issues/13131) exists and has been linked to this?

**Comment by richlander** [comment]
I'm no expert on this behavior, but yes, it's  related to the cost of scanning the entire FS.

Yes, closing this issue is fine. We're just relying on the time we both wasted on this, which will still be evident from a closed issue.

BTW: Have you tried SDK container builds. They are great if they work for your scenario. https://github.com/dotnet/sdk-container-builds

**Comment by JovialJerboa** [comment]
> Yes, closing this issue is fine. 
Awesome, will do

> BTW: Have you tried SDK container builds.
Nope, I wasn't aware of them, but they look very cool. Will give them a try, thanks for the tip!

Thanks again for your help @richlander, really appreciate it 🦸‍♂️

**Comment by richlander** [comment]
Also check out: https://devblogs.microsoft.com/dotnet/announcing-dotnet-chiseled-containers/
