### ISSUE TITLE
tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-01-09T10:21:41+08:00 is after 2024-01-08T23:59:59Z

### ISSUE THREAD

**Issue by Tangtang1997** [dotnet/dotnet-docker#5088]
### Describe the Bug
tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-01-09T10:21:41+08:00 is after 2024-01-08T23:59:59Z

### Steps to Reproduce

using **mcr.microsoft.com/dotnet/aspnet:8.0 As base** pull images.
### Output of `docker version`
Docker version 24.0.7, build afdd53b

### Output of `docker info`
- FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
  ERROR: failed to solve: mcr.microsoft.com/dotnet/sdk:8.0: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://southeastasia.data.mcr.microsoft.com/353485d638e24519ae59b2c19249e31f-vd4vgzv6do//docker/registry/v2/blobs/sha256/8c/8c5c87a4113924f286889309d5d9e9263b8b76e1f0f8f765685d9390a5701266/data?se=2024-01-09T03%3A01%3A45Z&sig=CLm9va8kntRCwHntj1nPJodVlcGSBuG1YIaK1enXggs%3D&sp=r&spr=https&sr=b&sv=2018-03-28&regid=353485d638e24519ae59b2c19249e31f": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-01-09T10:46:34+08:00 is after 2024-01-08T23:59:59Z

- docker pull mcr.microsoft.com/dotnet/aspnet:8.0
  docker: error pulling image configuration: download failed after attempts=6: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-01-09T10:57:19+08:00 is after 2024-01-08T23:59:59Z.

**Comment by richlander** [comment]
You get that pulling the image?

**Comment by Tangtang1997** [comment]
> You get that pulling the image?

I have replaced "McR.microsoft.com/dotnet/aspnet:8.0 As base" with "McR.microsoft.com/dotnet/runtime:8.0", can be to pull.

**Comment by Tangtang1997** [comment]
> You get that pulling the image?

Just tried it and now it's ready. Thank you.
