### ISSUE TITLE
Error visiting (m)any Docker repo for MS .NET

### ISSUE THREAD

**Issue by nwoolls** [dotnet/dotnet-docker#5097]
### Describe the Bug

Trying to visit (m)any of the MS .NET Docker repos on Docker Hub, either those found in the MS Learning docs or those found on the README for this repo, results in an error page:

https://hub.docker.com/_/microsoft-dotnet-framework/

> Something went wrong!
> 
> We've logged this error and will review it as soon as we can. If this keeps happening, please [file a support ticket]> (https://hub.docker.com/support/contact) with the below ID.
> Error ID: ifcrBVLdey

The browser console shows a 404 for e.g.: https://hub.docker.com/v2/repositories/library/microsoft-dotnet-framework/

### Steps to Reproduce

1. Navigate to https://hub.docker.com/_/microsoft-dotnet-framework/

### Other Information

I've tried this in various browsers, on various devices, on various networks, both logged in and not logged in to Docker.com. 

I've also contacted Docker support how had this to say:

> Thanks for reaching out about the issue you're facing with accessing the Microsoft .NET SDK repository on Docker Hub.
> 
> Based on the 404 error you're encountering, it seems like the URL you're trying to access might have been changed or the > repository could have been moved. It looks like Microsoft has been updating their Docker images for .NET. These updates might > have included changes to the Docker Hub repositories. https://learn.microsoft.com/en-us/dotnet/architecture/microservices/net-> core-net-framework-containers/official-net-docker-images
> 
> I'd recommend checking the [dotnet-docker](https://github.com/dotnet/dotnet-docker/issues) repository on GitHub. This > repository provides detailed information and documentation about various .NET Docker images.
> 
> Best regards,
> Docker Support

**Comment by mthalman** [comment]
Thanks, we're aware of the issue. It's actually broader than just .NET and affecting other Microsoft Docker repository pages hosted on Docker Hub. There's a team at Microsoft that's in contact with Docker on this issue.

**Comment by mthalman** [comment]
This is resolved now.
