### ISSUE TITLE
dotnet restore hangs out when building a Dockerfile targeting a DigitalOcean docker machine

### ISSUE THREAD

**Issue by cipriansorlea** [dotnet/dotnet-docker#51]
I have a docker machine, created on DigitalOcean, running Docker v1.11.2.

On this machine, I am trying to build a docker image. 
The Dockerfile is extremely simple:
```
FROM microsoft/dotnet:onbuild
RUN echo 'Setup Done'
```

Based on the onbuils hooks, the dotnet restore command is executed.
Even though the project.json file is almost empty, and therefore the command doesn't have anything to restore, the build of the Docker file hangs.

Here is the source of the project.json

```
{
  "dependencies": {},  

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [        
        "dnxcore50"        
      ]
    }
  }
}
```

And here is the output of the docker build command:

```
ending build context to Docker daemon 5.632 kB
Step 1 : FROM microsoft/dotnet:onbuild
# Executing 2 build triggers...
Step 1 : COPY . /dotnetapp
Step 1 : RUN dotnet restore
 ---> Running in 791300cc1f7e
log  : Restoring packages for /dotnetapp/project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: /dotnetapp/project.lock.json
log  : /dotnetapp/project.json
log  : Restore completed in 4012ms.

NuGet Config files used:
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

Once it outputs the above info, it doesn't do anything else... and there seems to be no network nor CPU activity specific to the docker process.

If I run the same build command targeting a local docker machine , running Docker v1.10.3, this works.

**Comment by MichaelSimons** [comment]
@cipriansorlea, Please excuse me as I am not familiar with DigitalOcean.  Can you state what distro and kernel version your docker host is on?  I just want to make sure you are not running into https://github.com/docker/docker/issues/18180

**Comment by cipriansorlea** [comment]
The distro is ubuntu-15-10-x64.

**Comment by MichaelSimons** [comment]
@cipriansorlea, what is the kernel version?

**Comment by cipriansorlea** [comment]
I edited the previous comment, and added the docker info, including the Kernel version. Hope that helps.

**Comment by MichaelSimons** [comment]
I suspect you are hitting the issue I mentioned before - docker/docker#18180.  Per that issue, 
Ubuntu 15.10: Upgrade kernel to 4.2.0-30.35 or later

Another way to help verify this is to check the distro and kernel version you are using locally and see if it is one of the configurations affected (https://github.com/docker/docker/issues/18180#issuecomment-193708192)

**Comment by MichaelSimons** [comment]
@cipriansorlea - any update?  Did you try upgrading your kernel?  If you were able to resolve the issue feel free to close this issue. Thanks

**Comment by cipriansorlea** [comment]
@MichaelSimons I didn't had a chance to do the upgrade on the Digital Ocean machine, but using Fedora as a base image, I was able to get the machine running with an ASP.NET Core application. I will try again in future releases of Docker, to see if the issue is fixed.

Thanks for your support!

**Comment by OviWanKenoby** [comment]
I am seeing the same problem, but the kernel I have is not matching the ones listed as having problems

Docker Version
--------------

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

 
 -------------------------------
 Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-60-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: udesk
ID: TUR6:WSOD:GRVG:35CX:CNTF:7CBD:MDIT:GS6D:RIV4:H5PM:UHIU:K4PY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
----------------------------------------------

Linux udesk 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

----------------------------------------------

**Comment by MichaelSimons** [comment]
@OviWanKenoby, Does `dotnet new` work or does that hang as well?
