### ISSUE TITLE
Manifest List arm variant doesn't match standard practice?

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/dotnet-docker#510]
## Steps to reproduce the issue
```
$ sudo docker run --rm mplatform/mquery microsoft/dotnet:2.1-sdk
Image: microsoft/dotnet:2.1-sdk
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/armv7
   - windows/amd64:10.0.14393.2189
   - windows/amd64:10.0.16299.371

$ sudo docker run --rm mplatform/mquery ubuntu
Image: ubuntu
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```

## Expected behavior
Variant name to be `v7`

## Actual behavior

Variant name is currently `armv7` which doesn't seem to match current practice (but may work)
## Additional information (e.g. issue happens only occasionally)

The documentation for variant names is apparently missing.  So relying on industry standard practice seems to be the current best practice.

Looking at https://blog.docker.com/2017/11/multi-arch-all-the-things/ It seems `v7` was used for golang in the slides.

Pulling from current golang gives a similar answer to ubuntu above.  Ubuntu was checked as it is another major docker image.

**Comment by MichaelSimons** [comment]
The Docker manifest spec isn't very helpful and has hints the armvN pattern currently being used - https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md

I think I found the right spec though😄 - https://github.com/opencontainers/image-spec/blob/master/image-index.md.
