### ISSUE TITLE
non-root Kubernetes sample is using a defunct image

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#5107]
We should fix this.

https://github.com/dotnet/dotnet-docker/blob/7bca20cb06e1f912fc2e7fa8ce04dda606277537/samples/kubernetes/non-root/non-root.yaml#L15-L17

**Comment by lbussell** [comment]
[Triage] We could use the `aspnetapp-chiseled` tag here from [this proposal](https://github.com/dotnet/dotnet-docker/issues/4932#issuecomment-1816940435) if we make it non-root like we plan to.

**Comment by richlander** [comment]
This was resolved some time ago.
