### ISSUE TITLE
Create a developer-guide.md to provide assistance to those wanting to contribute.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#514]
There should be a developer-guide.me that describe the following:

1. Build images locally
1. Run tests locally
1. Modify existing images
1. Create new images
1. Add/Modify/Obsolete image tags

Our repo should be encouraging external contributions.

See https://github.com/dotnet/dotnet-docker/pull/506#issuecomment-384729639 for a concrete case on why this is needed.

**Comment by jsacapdev** [comment]
@MichaelSimons can i help with this? even if it means running through and validating the PR from an external contributor? If you think I can, let me know how you think I might be able to help.

**Comment by MichaelSimons** [comment]
@jsacapdev - A major component of this documentation includes describing the [manifest.json](https://github.com/dotnet/dotnet-docker/blob/master/manifest.json) - what it contains and how it is used.  Other important aspects are to describe the build infra as well as the tests.  I would welcome your help on validating the PR from an external contributor standpoint.  I will keep you posted.  Thanks
