### ISSUE TITLE
Wrong Code Snippet:  Writing to a Special Directory on a Chiseled Image

### ISSUE THREAD

**Issue by krishankumar95** [dotnet/dotnet-docker#5145]
https://github.com/dotnet/dotnet-docker/blob/27ed26e141b943d8ae973ab7aed011f849c60b21/documentation/ubuntu-chiseled.md?plain=1#L120

Ideally it should be: 
Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"myFile.txt");

**Comment by lbussell** [comment]
[Triage] Thanks for pointing this out. I'll validate your suggestion and submit a PR addressing this.
