### ISSUE TITLE
Add README content for Aspire Dashboard images

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5153]
The README content for the Aspire Dashboard images should detail how exactly they should be used and/or point to official Aspire documentation on how to use the Dashboard project.

**Comment by richlander** [comment]
The Aspire team should own this content and make their signoff on this PR a pre-req of shipping their images.

@joperezr

**Comment by joperezr** [comment]
cc @kvenkatrajan @drewnoakes @davidfowl

**Comment by davidfowl** [comment]
Sounds good, where does it go? In the readme?

**Comment by joperezr** [comment]
No, that will live in this repo. I'm assuming next to the Dockerfile @lbussell? Which means once #5148 goes in it would be in `src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/README`

**Comment by kvenkatrajan** [comment]
Thanks @joperezr . Can we get a sample of what this should like for a container image?  Sorry haven’t done one if this before.

**Comment by MichaelSimons** [comment]
> Sounds good, where does it go? In the readme?

The readme's are generated from a template.  Once https://github.com/dotnet/dotnet-docker/pull/5148 is merged you will see the generated readme at the root of the repo.  One of the main pieces that needs your content is here - https://github.com/dotnet/dotnet-docker/pull/5148/files#diff-5550790524c4ed6cc5505b1ce1767c913bfa0b75fc74a5028ecf5bd0f2547044

> Can we get a sample of what this should like for a container image? Sorry haven’t done one if this before.

I would suggest looking at the readme's for the other images - examples include

https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md
https://github.com/dotnet/dotnet-docker/blob/main/README.aspnet.md
https://github.com/dotnet/dotnet-docker/blob/main/README.monitor.md

After https://github.com/dotnet/dotnet-docker/pull/5148 is merged, the aspire readme will look like: https://github.com/dotnet/dotnet-docker/blob/a0384a3d75794221fa132e1b90eeb24fb1c1d167/README.aspire-dashboard.md

**Comment by MichaelSimons** [comment]
The readme content appears now.

**Comment by MichaelSimons** [comment]
Is there any work remaining here or can this be closed?

**Comment by lbussell** [comment]
Completed with https://github.com/dotnet/dotnet-docker/pull/5326
