### ISSUE TITLE
Aspire Dashboard image fails to start

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5164]
The image `mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0-preview` fails to start.

The image digest specifically is `sha256:b62c4d1fd63d61dc9abcdd220ca047c5049f9a74fc9841096928f72fcc4a94f7`

### Steps to Reproduce

1. `docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0-preview`
2. `docker run mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0-preview`
3. Observe the following error: 

```
Unhandled exception. System.InvalidOperationException: Error parsing URIs from environment variable 'ASPNETCORE_URLS'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Aspire.IEnvironmentVariablesExtensions.<>c.<GetUris>b__3_0(String url) in /_/src/Aspire.Hosting/Utils/IEnvironmentVariables.cs:line 146
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Aspire.IEnvironmentVariablesExtensions.GetUris(IEnvironmentVariables env, String variableName, Uri defaultValue) in /_/src/Aspire.Hosting/Utils/IEnvironmentVariables.cs:line 144
   --- End of inner exception stack trace ---
   at Aspire.IEnvironmentVariablesExtensions.GetUris(IEnvironmentVariables env, String variableName, Uri defaultValue) in /_/src/Aspire.Hosting/Utils/IEnvironmentVariables.cs:line 152
   at Aspire.Dashboard.DashboardWebApplication..ctor() in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 36
   at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
```

**Comment by lbussell** [comment]
The following environment variables are the cause of the issue:

```
DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://*:18889
ASPNETCORE_URLS=http://*:18888
```

I also tried the `http://+:18889` format and had the same error.

I found two formats that do work in this scenario - `http://localhost:18888` and `http://0.0.0.0:18888`. So a workaround to this issue would be to add these arguments to your docker run command: `-e ASPNETCORE_URLS=http://localhost:18888 -e DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://localhost:18889`.

I haven't seen the `+` or `*` URI formats fail in other ASP.NET Core applications. Is this something specific to Aspire or an issue with ASP.NET?

/cc @joperezr @davidfowl

**Comment by davidfowl** [comment]
Yea lets use 0.0.0.0 for now. I'll make sure we fix this on the aspire side.

**Comment by baronfel** [comment]
So I'm using the new, fixed environment variable version of the dashboard (thanks for the quick turnaround!) and I'm having trouble getting the dashboard to start. Here's the docker command I'm using right now:

```terminal
> docker run --rm -it -d -p 18888:18888 -p 18889:18889 mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0-preview aspire-dashboard
```

So I'm mapping ports for HTTP and OTLP, then going to `localhost:18888` in my browser, which renders a white screen. The network pane shows a `POST` to `disconnect`:

![image](https://github.com/dotnet/dotnet-docker/assets/573979/a5b4abd0-3e97-44a3-9890-2b4c613b7ec8)

And the console is talking about an unhandled exception for the blazor circuit:

![image](https://github.com/dotnet/dotnet-docker/assets/573979/47f8a636-41d3-45f4-bde7-646ac157d483)

Are other folks seeing the same things?

**Comment by lbussell** [comment]
I believe this is a known issue - currently the container needs some extra environment variables in order for the portal to render. Apparently this is fixed in the newer versions of the dashboard - we will get new versions out after https://github.com/dotnet/dotnet-docker/issues/5154 is done (or we could get an updated version out by hand while I work on that). @joperezr can comment more on this.

**Comment by baronfel** [comment]
Ok, great! Glad this is a known thing :)

**Comment by davidfowl** [comment]
Not sure.

cc @drewnoakes @kvenkatrajan

**Comment by JamesNK** [comment]
The error from the circuit error should appear in the container's console output. Do you have that available?

**Comment by davidfowl** [comment]
I saw a similar thing when running from the command line outside of the host:

https://github.com/dotnet/aspire/issues/1556#issuecomment-1916189785

**Comment by lbussell** [comment]
[Triage] The fundamental problem described in the issue body has been worked around by https://github.com/dotnet/dotnet-docker/pull/5165. We should open new issues for any additional problems that occur after the dashboard process has started. Additionally I will open an issue to remove the workaround introduced in https://github.com/dotnet/dotnet-docker/pull/5165.
