### ISSUE TITLE
Add aspire-dashboard repo to .NET release notes

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5184]
The aspire repo should be added to the Docker Images section of the release notes once official images are released.

https://github.com/dotnet/core-private/pull/205/files#diff-926d0f3c14eb434e555cb0a05784a54a85cf04f70e62d3771da8dd540e10b14cR66

**Comment by lbussell** [comment]
[Triage] The exact location of the list to be updated is https://github.com/dotnet/core-private/blob/ed779cf7992f2ebbfd7ba25c47c174d9b4b54f88/release-notes/9.0/preview/9.0.0-preview.1.md#L63-L67.

**Comment by lbussell** [comment]
[Triage] @joperezr can you or someone else from the Aspire team pick this up?

**Comment by lbussell** [comment]
Completed with https://github.com/dotnet/core/pull/9380
