### ISSUE TITLE
Revert Port environment variable workaround in Aspire Dashboard images

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5190]
Original issue: https://github.com/dotnet/dotnet-docker/issues/5164

The Aspire Dashboard Dockerfiles currently contain a workaround for a port environment variable issue with the Aspire Dashboard:

https://github.com/dotnet/dotnet-docker/blob/02e6fbd795bb2637042de91092a1194f52ca825c/src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile#L31-L32

I did not find a tracking issue for this on the Aspire repo but presumably it will be fixed eventually. We want all port/URL environment variables to have the shorthand format:

https://github.com/dotnet/dotnet-docker/blob/32c6a5c755ac3316ca552a55b5a8d5bc927c2d66/src/runtime-deps/6.0/alpine3.18/amd64/Dockerfile#L5

**Comment by lbussell** [comment]
[Triage] @joperezr, can you make this change when the correct fix is in Aspire? I didn't find a tracking issue for it.

**Comment by joperezr** [comment]
Yup, will do.

**Comment by lbussell** [comment]
@joperezr is this fixed in Aspire Dashboard yet?

**Comment by JamesNK** [comment]
Hi, I don't know of a tracking issue for this in dotnet/aspire, but I'm fixing it here: https://github.com/dotnet/aspire/pull/5941

It should be fixed for Aspire 9.0.
