### ISSUE TITLE
Breaking change in .NET 8 means instructions to run docker container are wrong

### ISSUE THREAD

**Issue by jonathanpickard3sq** [dotnet/dotnet-docker#5194]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

The instructions in the tutorial are not correct for somebody who has created the microservice using .NET 8.  [Breaking change - default port was changed from 80 to 8080 ](https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port)

There are potentially two fixes for this: either change the command line to run the container:

`docker run -it --rm -p 3000:8080 --name mymicroservicecontainer mymicroservice`

Or change the docker file to enforce the internal container port to port 80 (and leave the command-line as-is):

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY MyMicroservice.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "MyMicroservice.dll"]

ENV ASPNETCORE_HTTP_PORTS=80

```

**Comment by lbussell** [comment]
[Triage] It looks like this issue is already fixed. The [tutorial ](https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run-docker)command uses port `8080` and not `80`. @mairaw are we good to close this? I tried out the instructions and everything seemed fine.

**Comment by mairaw** [comment]
Yes, you can close this. We fixed the port in the tutorial.
