### ISSUE TITLE
Unable to run ASP.NET Core 2.1 RC1 application inside dotnet:2.1-aspnetcore-runtime-alpine

### ISSUE THREAD

**Issue by cypressious** [dotnet/dotnet-docker#529]
See https://stackoverflow.com/questions/50229733/it-was-not-possible-to-find-any-compatible-framework-version-with-asp-net-core?noredirect=1#comment87482033_50229733

## Steps to reproduce the issue
1. Create an ASP.NET Core 2.1-RC1 application
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <Version>$(Version)</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.1.0-preview1-final" />
  </ItemGroup>
</Project>
```
2. Create `Dockerfile`

```
FROM microsoft/dotnet:2.1-sdk-alpine AS builder
WORKDIR /
COPY . .
RUN dotnet restore My.Project/My.Project.csproj
RUN dotnet publish My.Project/My.Project.csproj -o /dockerout/ -c Release

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine
WORKDIR /app
EXPOSE 80 5000

COPY --from=builder /dockerout .

ENTRYPOINT ["dotnet", "My.Project.dll"]
```

3. Run `Dockerfile`

## Expected behavior

Application starts

## Actual behavior

Application doesn't start with error

> It was not possible to find any compatible framework version The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-rc1-final' was not found.
> 
>   - Check application dependencies and target a framework version installed at:
>       /usr/share/dotnet/
>   - Installing .NET Core prerequisites might help resolve this problem:
>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download

## Additional information (e.g. issue happens only occasionally)

Adding `RUN dotnet --version` in the second phase of the `Dockerfile` prints 

> Did you mean to run dotnet SDK commands? Please install dotnet SDK from: go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

If I replace `microsoft/dotnet:2.1-aspnetcore-runtime-alpine` with `microsoft/dotnet:2.1-sdk-alpine`, the application actually works.

## Output of `docker version`

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

## Output of `docker info`

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 35
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155db29d0f
ID: JTBN:THCI:LT7M:W4CB:2KNY:SPHP:AECG:EUDQ:IW6Z:4XT5:ES5O:BJYZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 62
 System Time: 2018-05-08T12:11:57.4517596Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by cypressious** [comment]
@MichaelSimons `docker run --rm microsoft/dotnet:2.1-aspnetcore-runtime-alpine dotnet --list-runtimes` prints

> Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

After trying it again just now, it suddenly started to work. I'm confused.

**Comment by MichaelSimons** [comment]
Is it possible somehow a newer image was pulled?  The behavior you describe could come from having an older preview image cached on disc.

**Comment by MichaelSimons** [comment]
@sam-sarmento - have you verified that you have the latest images pulled?

**Comment by sam-sarmento** [comment]
Yes, I've built with --no-cache --pull

**Comment by sam-sarmento** [comment]
Running: 
docker run -it -P 190839dbfa42 dotnet --list-runtimes prints

Gives me:
Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Shouldn't it be 2.1.0-rc1-final ?

**Comment by sam-sarmento** [comment]
Only difference in my scenario is that I'm running the CentOS version

**Comment by MichaelSimons** [comment]
@sam-sarmento - what image is 190839dbfa42?  If you are using the aspnetcore-runtime image I would expect to see 3 runtimes listed

**Comment by sam-sarmento** [comment]
That is my secondary image, but I'm sure I've built based on Runtime version 2.1.0-rc1 and SDK 2.1.300-rc1-008673

**Comment by MichaelSimons** [comment]
I'm trying to figure out if you are using the aspnetcore-runtime or just the runtime image?  Can you share what your Dockerfile looks like?

**Comment by sam-sarmento** [comment]
I'm using this runtime:
https://www.microsoft.com/net/download/linux-package-manager/centos/runtime-2.1.0-rc1

**Comment by MichaelSimons** [comment]
@sam-sarmento - Does that mean you are not using Docker?  Regardless if you want to run an aspnet core app, you will need the [aspnetcore runtime](https://get.asp.net/)

**Comment by mbhoek** [comment]
I'm experiencing the same issue. Using the following Dockerfile:

```
FROM microsoft/dotnet:2.1-sdk-alpine as builder
WORKDIR /src
COPY . ./
RUN dotnet publish -c Release -o /app

FROM microsoft/dotnet:2.1-runtime-alpine 
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "dotnet-docker-issue.dll"]
```

If I create a new console project using ```dotnet new console```, build the docker using ```docker build -t issue .``` and run it using ```docker run issue``` the output is ```Hello World```, as expected.

If I create a new web project using ```dotnet new web```, build the docker using ```docker build -t issue .``` and run it using ```docker run issue``` the output is 

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-rc1-final' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

I've tried building using ```--pull --no-cache```, same result.

**Comment by MichaelSimons** [comment]
@mbhoek - The '2.1-runtime-alpine` image doesn't contain the ASP.NET Core runtime which is why you are getting the error.  In this scenario, I'm guessing you want to use the `2.1-aspnetcore-runtime-alpine` tag instead.

**Comment by mbhoek** [comment]
@MichaelSimons Thanks, I wasn't aware of that. For anyone else reading this, https://github.com/dotnet/dotnet-docker/#image-variants lists all the variants.
