### ISSUE TITLE
Links lead to 404 in samples/build-for-a-platform.md

### ISSUE THREAD

**Issue by Guiorgy** [dotnet/dotnet-docker#5297]
Links lead to 404 in [samples/build-for-a-platform.md](https://github.com/dotnet/dotnet-docker/blob/main/samples/build-for-a-platform.md#lock-dockerfiles-to-one-platform):

- [Dockerfile.debian-x64](https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.debian-x64)
- [Dockerfile.alpine-arm64](https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.alpine-arm64)

Edit: Further down, under __Conditionalize Dockerfile with --platform__, the link to the Dockerfile also leads to 404.

**Comment by lbussell** [comment]
Thanks for noticing this @Guiorgy. We'll try to get this addressed. If you have any specific questions that our documentation doesn't cover, feel free to open a [discussion](https://github.com/dotnet/dotnet-docker/discussions).

@richlander, we don't have samples for arch-specific Dockerfiles anymore. We should consider re-writing this doc, potentially with a focus on cross-platform builds w/ BuildKit.

**Comment by lbussell** [comment]
[Triage] We should also consider the use of a markdown linter to help catch invalid links in CI. I will file an issue for that.

**Comment by Guiorgy** [comment]
Was wandering if catching dead links in CI would be difficult
