### ISSUE TITLE
[Samples] aspnetapp Dockerfile.preview doesn't work

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#530]
## Steps to reproduce the issue
1. cd samples\aspnetapp
2. docker build -t test -f .\Dockerfile.preview .
3. docker run --rm -it -p 8000:80 test

## Expected behavior
Docker image should run without error and the sample web app should be running

## Actual behavior
Error:
  An assembly specified in the application dependencies manifest (aspnetapp.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

**Comment by Ullmie02** [comment]
Same problem on Raspberry Pi 3
