### ISSUE TITLE
Windows nanoserver image is still pointing to 8.0

### ISSUE THREAD

**Issue by avin3sh** [dotnet/dotnet-docker#5300]
The `8.0-nanoserver-ltsc2022` image, for instance, still gives following output:

```
C:\app>dotnet --info

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71
  RID:          win-x64

```

There have been multiple releases after this, including security patches - but despite the docker page suggesting that the images have updated - it looks like the runtime is still pointing to the original 8.0 version, based on the commit SHA.

**Comment by mthalman** [comment]
I'm unable to repro this. Make sure you're pulling down the latest version of the image. The current version of the image has a digest value of `sha256:5ff18e4cf4315ca452726c893899f4738aec58bc1bd5f20563c2f0c9464b8d54`. That will be visible in the output after running `docker pull`.

```
> docker pull mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-ltsc2022
8.0-nanoserver-ltsc2022: Pulling from dotnet/runtime
Digest: sha256:5ff18e4cf4315ca452726c893899f4738aec58bc1bd5f20563c2f0c9464b8d54
Status: Image is up to date for mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-ltsc2022
mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-ltsc2022
```

From the container:

```
C:\>dotnet --info

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66
  RID:          win-x64
```

**Comment by avin3sh** [comment]
This may have been a mistake at my end. I will look into it. Thank you for confirming.
