### ISSUE TITLE
Use a Markdown linter in PR validation

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5316]
We should add a test or pre-build validation step that runs a markdown linter to check for dead links and proper markdown formatting across all of our docs (not just generated readmes)

Related: #5297 and https://github.com/dotnet/docker-tools/issues/1172

**Comment by richlander** [comment]
The team is trying to put my creative efforts in a straightjacket. "I cannot create under these conditions!"

**Comment by MichaelSimons** [comment]
FYI, the markdownlint tool I have integrated into CI only validates intra document links that use the # anchor ID syntax.  There are requests for it.  It appears a lot of project use https://github.com/tcort/markdown-link-check.

**Comment by MichaelSimons** [comment]
This work is now complete.  The dotnet-docker and dotnet-framework have a markdown linter and markdown link validator GH action.  All markdown issues within the repos have also been addressed
