### ISSUE TITLE
Add support for Azure Linux 3.0 Images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5331]
Add images to nightly for .NET 8+ when Azure Linux 3.0 preview images become available and release to main at GA.

**Comment by lbussell** [comment]
[Triage] The preview images are now available. We can start working on the implementation now. For example: `azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0`

**Comment by lbussell** [comment]
Azure Linux 3.0 support has been added in #5359. I filed https://github.com/dotnet/dotnet-docker/issues/5467 as follow-up work. I consider this task completed even though images are not in the main image repos yet.
