### ISSUE TITLE
Unable to find package Microsoft.NETCore.App.Runtime.linux-musl-x64/Microsoft.NETCore.App.Runtime.linux-musl-x64 when restoring

### ISSUE THREAD

**Issue by jdgiddings** [dotnet/dotnet-docker#5347]
### Describe the Bug

When attempting to `dotnet restore -r linux-musl-x64` a .NET 9.0 project using the `mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview-alpine` image, I get the following errors for each project in the solution:

```
  Unable to find package Microsoft.NETCore.App.Runtime.linux-musl-x64 with version (= 9.0.0-preview.3.24172.9)
    - Found 155 version(s) in nuget.org [ Nearest version: 9.0.0-preview.2.24128.5 ]
```

```
  Unable to find package Microsoft.AspNetCore.App.Runtime.linux-musl-x64 with version (= 9.0.0-preview.3.24172.13)
    - Found 155 version(s) in nuget.org [ Nearest version: 9.0.0-preview.2.24128.4 ]
```

### Steps to Reproduce

1. Create a .NET 9.0 project
2. Attempt to retore said project in `mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview-alpine` using `dotnet restore -r linux-musl-x64`

### Other Information

This appears to be specific to the `linux-musl-x64` runtime identifier

### Output of `docker version`

Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`

Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.685GiB
 Name: docker-desktop
 ID: 62b6d5e3-7706-4a46-8a41-fbe39ce95bc6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile

**Comment by lbussell** [comment]
Hi @jdgiddings,

**Nightly** images with pre-release versions of .NET will require a Nuget.config file with the following package feed added. This is because Preview 3 is not officially released yet - it's a pre-release version of "Preview" software 🙂

```xml
<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
```

You can see the NuGet config we use for testing here: [`NuGet.config.nightly`](https://github.com/dotnet/dotnet-docker/blob/87b3735c6c2ba37277be80dd04099f6cb93e4bb7/tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly). Some stuff like the `<clear />` statement is probably not necessary for your use case.

You may also be looking for the "stable" preview version of .NET 9 (which is currently Preview 2): https://mcr.microsoft.com/en-us/product/dotnet/sdk/tags. Images from repos without `nightly` in the name won't require any special NuGet config to work.

**Comment by jdgiddings** [comment]
Thank you!
