### ISSUE TITLE
Readme Related Repositories sections should link to the aspire-dashboard repo

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5349]
They do in the nightly repos but not in the official repos.  This is because of a condition in the template for when aspire-dashboard was only available in nightly

From https://raw.githubusercontent.com/dotnet/dotnet-docker/main/eng/readme-templates/RelatedRepos.md:

```
}}{{if isNightlyRepo && SHORT_REPO != "aspire-dashboard"
    :* [dotnet/nightly/aspire-dashboard]({{InsertTemplate("Url.md", [ "readme-host": ARGS["readme-host"], "repo": "dotnet/nightly/aspire-dashboard" ])}}): .NET Aspire Dashboard (Preview)
}}
```

**Comment by lbussell** [comment]
Related: https://github.com/dotnet/dotnet-docker/issues/5348

**Comment by MichaelSimons** [comment]
This can't be done in Docker Hub yet because of https://github.com/dotnet/dotnet-docker/issues/5415
