### ISSUE TITLE
Docker Hub ASP.NET Core Runtime page not updated to new ASP.NET versions

### ISSUE THREAD

**Issue by thohng** [dotnet/dotnet-docker#5354]
Docker Hub content is not up to date: https://hub.docker.com/_/microsoft-dotnet-aspnet

Page still show information of last month release Mar/2024, instead of Apr/2024

9/Apr/2024 and 11/Apr/2024 release: 6.0.29, 7.0.18, 8.0.4 and 9.0.0-preview.3.

**Workaround**:
- GitHub repo: https://github.com/dotnet/dotnet-docker/blob/main/README.aspnet.md#full-tag-listing
- MAR Portal: https://mcr.microsoft.com/en-us/product/dotnet/aspnet/tags

**The current issue on Docker Hub content**

![image](https://github.com/dotnet/dotnet-docker/assets/9668549/0dc4a42e-90b1-4c98-88e6-85fa0036cb77)

**Comment by mthalman** [comment]
We're aware of the issue and have an open support request for [MAR](https://mcr.microsoft.com) to have this fixed. They handle the synchronization to Docker Hub.

This purely a Docker Hub content issue. All images are updated for the release and new version tags do exist; they're just not showing up on the Docker Hub page content. You can find current supported tags either here in our GitHub repo (e.g. [aspnet repo](https://github.com/dotnet/dotnet-docker/blob/main/README.aspnet.md#full-tag-listing)) or on the MAR portal (e.g. [aspnet repo](https://mcr.microsoft.com/en-us/product/dotnet/aspnet/tags)).

**Comment by thohng** [comment]
> This purely a Docker Hub content issue. All images are updated for the release and new version tags do exist; they're just not showing up on the Docker Hub page content. You can find current supported tags either here in our GitHub repo (e.g. [aspnet repo](https://github.com/dotnet/dotnet-docker/blob/main/README.aspnet.md#full-tag-listing)) or on the MAR portal (e.g. [aspnet repo](https://mcr.microsoft.com/en-us/product/dotnet/aspnet/tags)).

Go to GitHub repo or MAR Portal as workaround solution
