### ISSUE TITLE
aspire-dashboard repository page is missing from Docker Hub

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5415]
This new repo was never syndicated by MAR - https://hub.docker.com/_/microsoft-dotnet-aspire-dashboard/

**Comment by mairaw** [comment]
I imagine this would fix the broken link at https://hub.docker.com/r/microsoft/dotnet under featured repos?

**Comment by mthalman** [comment]
> I imagine this would fix the broken link at https://hub.docker.com/r/microsoft/dotnet under featured repos?

This was actually resolved previously. The issue with the 404 you're seeing looks to be pervasive and is affecting all Microsoft-owned repos on Docker Hub. I'll get this escalated.

**Comment by mthalman** [comment]
Related issue: https://github.com/dotnet/dotnet-docker/issues/5742

I'm resolving this issue though since the page is there using the new URL format: https://hub.docker.com/r/microsoft/dotnet-aspire-dashboard
