### ISSUE TITLE
Docker image Build - Unable to load the service index for source https://api.nuget.org/v3/index.json for projects that require restoring Nuget packages on Windows server 2016

### ISSUE THREAD

**Issue by maulik-modi** [dotnet/dotnet-docker#543]
## Steps to reproduce the issue
1. Start with Windows Server 2016 and Install Docker Enterprise edition
2. Checkout [Musicstore ](https://github.com/dockersamples/dotnet-musicstore)git repository
3. Run command docker build -f Dockerfile.windows -t dotnetmusicstore20180515

## Expected behavior
All steps of docker build are successfully completed and Image with tag dotnetmusicstore20180515 is available

## Actual behavior
Sending build context to Docker daemon 2.168MB
Step 1/15 : FROM microsoft/dotnet:sdk-nanoserver
---> 8f13c75d6f1d
Step 2/15 : SHELL powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';
---> Using cache
---> 6f76ac31e2c4
Step 3/15 : RUN New-Item -Path \MusicStore\samples\MusicStore -Type Directory; New-Item -Path build -Type Directory
---> Using cache
---> 5b38f86b224e
Step 4/15 : WORKDIR MusicStore
---> Using cache
---> 6406891d6398
Step 5/15 : COPY samples/MusicStore/MusicStore.csproj samples/MusicStore/MusicStore.csproj
---> Using cache
---> 5ba9afed64c7
Step 6/15 : COPY NuGet.config .
---> Using cache
---> 0362b902118a
Step 7/15 : COPY version.props .
---> Using cache
---> d643d585c194
Step 8/15 : COPY build/*.props build/
---> Using cache
---> a6c3a8d6d4ff
Step 9/15 : RUN dotnet restore --runtime win10-x64 .\samples\MusicStore
---> Running in fbe67aff85fc
Restoring packages for C:\MusicStore\samples\MusicStore\MusicStore.csproj...
C:\Program Files\dotnet\sdk\1.1.9\NuGet.targets(102,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.1.9\NuGet.targets(102,5): error : An error occurred while sending the request. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.1.9\NuGet.targets(102,5): error : A security error occurred [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore --runtime win10-x64 .\samples\MusicStore' returned a non-zero code: 1

## Additional information (e.g. issue happens only occasionally)
Issue happens all the time in our project as well as on Sample project

## Output of `docker version`

```
PS C:\Users\Administrator\Desktop\Cyg\dotnet-musicstore> docker --version
Docker version 17.06.2-ee-10, build 66261a0
```

## Output of `docker info`

```
PS C:\Users\Administrator\Desktop\Cyg\dotnet-musicstore> docker info
Containers: 11
Running: 0
Paused: 0
Stopped: 11
Images: 37
Server Version: 17.06.2-ee-10
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: l2bridge l2tunnel nat null overlay transparent
Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 4GiB
Name: DOCKER
ID: DUY3:2JTV:D7IM:ZOOA:PFNY:ERQT:RUKH:PMYS:VPJM:J55Q:BADS:2OKW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
@maulik-modi - It looks like this sample is rather out of date.  It is [using a very old preview build of ASP.NET Core](https://github.com/dockersamples/dotnet-musicstore/blob/master/samples/MusicStore/MusicStore.csproj#L24).  Because of this it is using [non-production NuGet feeds ](https://github.com/dockersamples/dotnet-musicstore/blob/master/NuGet.config).  The sample needs updating as it won't build.

When I build it I am getting different errors

```
...
C:\MusicStore\samples\MusicStore\MusicStore.csproj : error NU1202: Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.0.0-preview1-final is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x64. Package Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.0.0-preview1-final supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
C:\MusicStore\samples\MusicStore\MusicStore.csproj : error NU1202: Package Microsoft.AspNetCore.Mvc.TagHelpers 2.0.0-preview1-final is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x64. Package Microsoft.AspNetCore.Mvc.TagHelpers 2.0.0-preview1-final supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
C:\MusicStore\samples\MusicStore\MusicStore.csproj : error NU1202: Package Microsoft.AspNetCore.Mvc 2.0.0-preview1-final is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x64. Package Microsoft.AspNetCore.Mvc 2.0.0-preview1-final supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
...
```

The error you are seeing seems unrelated to the project being out of date.

> error : Unable to load the service index for source https://api.nuget.org/v3/index.json

Can you verify that you can access it within a container within your environment?  

```
FROM microsoft/nanoserver:sac2016
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest -UseBasicParsing -OutFile index.json https://api.nuget.org/v3/index.json
RUN Write-Host $(Get-Content index.json -Raw)
```

**Comment by maulik-modi** [comment]
I received this message after placing Invokewebrequest
![error](https://user-images.githubusercontent.com/34910430/40124073-50943c42-5945-11e8-884e-c33883a460b0.PNG)

The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -UseBasicParsing -OutFile index.json https://api.nuget.org/v3/index.json' returned a non-zero code: 1

**Comment by MichaelSimons** [comment]
I did spot this script which may be helpful - https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/Debug-ContainerHost.

I'm going to close this issue since it is not specific to the microsoft/dotnet images.  Feel free to continue the conversation.

**Comment by maulik-modi** [comment]
@MichaelSimons , Thanks for pointing me to Debug-ContainerHost, I am attaching diagnostics log here. It seems to be all fine. Moreover, internet must be fine in docker as It was able to pull Base image and other layers that are visible in attached snapshot.

I am still not able to figure out the cause of Nuget restore issue.
[Diagnostics.txt](https://github.com/dotnet/dotnet-docker/files/2011798/Diagnostics.txt)

PS C:\Users\Administrator\Desktop\Cyg\dotnet-musicstore> docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
<none>                       <none>              573d871a6e43        15 hours ago        1.13GB
<none>                       <none>              a6c3a8d6d4ff        23 hours ago        1.85GB
<none>                       <none>              c5421fbaf3ec        40 hours ago        2.94GB
<none>                       <none>              bd3b6b6f3c48        40 hours ago        2.94GB
keepitsafeapi201805          latest              027d75206fa7        40 hours ago        2.94GB
<none>                       <none>              57906c8fc02e        41 hours ago        1.35GB
dotnetapp-prod               latest              86bcbfb79674        2 days ago          1.22GB
<none>                       <none>              5035490ecb16        2 days ago          2.65GB
microsoft/aspnetcore-build   2.0                 21be248b5580        5 days ago          2.94GB
microsoft/aspnetcore         2.0                 b6b5d16a11d9        5 days ago          1.35GB
microsoft/dotnet             2.0-sdk             2f3c21c6fc76        8 days ago          2.63GB
microsoft/dotnet             sdk-nanoserver      8f13c75d6f1d        8 days ago          1.84GB
microsoft/dotnet             2.0-runtime         13c118cb63db        8 days ago          1.22GB
microsoft/nanoserver         latest              90714e312e09        8 days ago          1.13GB
microsoft/nanoserver         sac2016             90714e312e09        8 days ago          1.13GB
hello-world                  nanoserver          b1bf314a296b        4 weeks ago         1.11GB
PS C:\Users\Administrator\Desktop\Cyg\dotnet-musicstore>

**Comment by MichaelSimons** [comment]
Maybe if you executed this interactively you could dig up some more information by inspecting the error that is thrown.

```
docker run -it --rm microsoft/nanoserver:sac2016
powershell
Invoke-WebRequest -UseBasicParsing -OutFile index.json https://api.nuget.org/v3/index.json
$error[0]
$error[0].Exception
$error[0].Exception.InnerException
```
