### ISSUE TITLE
New tag for alpine images

### ISSUE THREAD

**Issue by meziantou** [dotnet/dotnet-docker#5530]
### Describe the Problem

When referencing the alpine SDK image, you can use one of the following
- `mcr.microsoft.com/dotnet/sdk:8.0-alpine`
- `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine3.18-amd64`

It would be great to also have the following tag:
- `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine`

When using tools such as [Renovate](https://github.com/renovatebot/renovate) to update dependencies, they preserve the tag "suffix" (`-alpine`). So, it can update from `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine` to `mcr.microsoft.com/dotnet/sdk:8.0.301-alpine`. But it cannot update from `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine3.18-amd64` to `mcr.microsoft.com/dotnet/sdk:8.0.301-alpine3.20-amd64`.

Adding the new tag would allow project to reference a specific version of the SDK and rely on tools to get updates. I think it would help for reproducible builds.

### Describe the Solution

Add a new tag for the SDK image with the specific SDK version, e.g. `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine`

So, you'll have the following tags:
- `mcr.microsoft.com/dotnet/sdk:8.0-alpine`
- `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine`
- `mcr.microsoft.com/dotnet/sdk:8.0.300-alpine3.18-amd64`

**Comment by MichaelSimons** [comment]
Thanks @meziantou for logging this issue.

> I think it would help for reproducible builds.

Are you not concerned about the impact of new major Alpine distro versions like alpine 3.19 to 3.20?

**Comment by meziantou** [comment]
I agree this could be a concern. But currently, I've seem more build breaking because of a new .NET SDK (e.g. new warnings from analyzers) rather than a new base image. That's why I think there can be a middle ground with `8.0.300-alpine`

**Comment by lbussell** [comment]
Is this something that could be solved by using some [custom regex for Renovate bot](https://docs.renovatebot.com/modules/manager/regex/)?

**Comment by meziantou** [comment]
Do you mean create a regex to update versions based on the current format `8.0.300-alpine3.18-amd64`?
If so, I'm not sure how you would write it to be equivalent to `8.0.300-alpine`. The regex would detect the version for the first part (8.0.300) and update it. But I don't know how it can know how to replace the last part (3.18-amd64).

Currently, I think the best you can do is pinning the image version, i.e. `8.0-alpine@sha`, but the actual version is not human readable.

**Comment by lbussell** [comment]
[Triage] Another thing to consider is that a tag with a fixed .NET version and a floating Alpine version could potentially be misleading, as the floating Alpine version implies that the version will be updated over time. In reality, it would never change (since we only update Alpine versions with .NET servicing releases). We want to continue to make sure that upgrading OSes is an intentional choice, so we won't be adding these tags.

You may want to support this issue on the Renovate repo for supporting the scenario of bumping the OS at the same time as a product version for Docker images: https://github.com/renovatebot/renovate/issues/27012

**Comment by lordcheeto** [comment]
It's a bit of a hacky workaround, but in addition to the standard SemVer major, minor and patch versions, renovate supports build and revision versions (which are treated like patches). [You can use a regular expression](https://docs.renovatebot.com/modules/versioning/regex/) to tell renovate how to parse that.

```json
"packageRules": [
    {
      "matchDatasources": ["docker"],
      "matchPackageNames": ["mcr.microsoft.com/dotnet/sdk"],
      "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)(\\.(?<patch>\\d+))?(-(?<compatibility>alpine)((?<build>\\d+).(?<revision>\\d+))?(-\\w*)?)?$"
    }
  ]
```
