### ISSUE TITLE
Upgrade MinGit version to 2.45.2

### ISSUE THREAD

**Issue by chi-qin** [dotnet/dotnet-docker#5550]
### Describe the Problem

Git 2.45.1 has some bugs of git lfs, in the release notes for 2.45.2, they also acknowledge the issue: https://github.com/git/git/blob/master/Documentation/RelNotes/2.45.2.txt

```
In preparing security fixes for four CVEs, we made overly aggressive
"defense in depth" changes that broke legitimate use cases like 'git
lfs' and 'git annex.'  This release is to revert these misguided, if
well-intentioned, changes that were shipped in 2.45.1 and were not
direct security fixes.
```

### Describe the Solution

Bump MinGit version to 2.45.2

### Additional Context

I would be happy to send one pr for you.

**Comment by mthalman** [comment]
The MinGit version is automatically upgraded with each servicing release. That happens to be today and will be covered by https://github.com/dotnet/dotnet-docker/pull/5545.
