### ISSUE TITLE
Readme generation issue

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5561]
The PreBuildValidation job runs tests to ensure the Dockerfiles and Readmes are in sync with the templates. This runs the generation logic. For readmes, this is failing when running the rendering tool.

[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2473037&view=results) (internal link)

[ICM link](https://portal.microsofticm.com/imp/v3/incidents/incident/512797743/summary) (internal link)

**Comment by lbussell** [comment]
[Triage] The rendering tool will no longer be supported. We should take this opportunity to remove our dependency on the rendering tool.
