### ISSUE TITLE
Unable to run Windows Time Service within a container

### ISSUE THREAD

**Issue by DNikitenko** [dotnet/dotnet-docker#559]
## Steps to reproduce the issue
1. Run _microsoft/dotnet-framework_ Docker container:
    `docker run -it --rm microsoft/dotnet-framework:4.7.2-runtime-20180508-windowsservercore-1803`
2. Enter `w32tm /register` command.
3. Enter `net start w32time` command.

## Expected behavior
The Windows Time Service is started successfully.

## Actual behavior
The service could not be started with the following error:

> The Windows Time service is starting.
> The Windows Time service could not be started.
> A system error has occurred.
> System error 5 has occurred.
> Access is denied.

## Additional information (e.g. issue happens only occasionally)
My application requires Windows Time Service to be enabled. A typical problem resolution which I see in web for the error like that is to run those commands from an elevated cmd/powershell. But I'm already an administrative user (_ContainerAdministrator_).
Also I've tried to enable administrator user and to run a .ps1 script with the same commands from an Administrator account - and it's all the same.

## Output of `docker version`

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 14
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.8GiB
Name: WSW-1HWKXF2
ID: PKZF:AMLV:BOME:SZZM:RFTD:YVFA:JGBU:WLAC:K4CV:KKHP:EBFD:AY5U
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 57
 System Time: 2018-05-30T17:35:19.0461548+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
@DNikitenko - Since this issue is not specific to the .NET images, it would be best to post your question to the [Windows Containers Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).  

FWIW, I tried your repo using the microsoft/windowsservercore:ltsc2016 image and the time service appears to run without issue.  This may be a potential workaround.  I can only guess that some of the required components were removed as part of the effort to reduce the size of the 1803 OS image.
