### ISSUE TITLE
Is there any vulnerability or security issues in Chiseled images build with multistage docker file.

### ISSUE THREAD

**Issue by Amit-limbasiya** [dotnet/dotnet-docker#5642]
### Discussed in https://github.com/dotnet/dotnet-docker/discussions/5641

<div type='discussions-op-text'>

<sup>Originally posted by **Amit-limbasiya** July  2, 2024</sup>
I am confused about the security issues or vulnerabilities in the custom chiseled images built with the multistage docker file.
I have requirements like I need the container image of the application having chiseled base images plus a new relic dotnet agent installed in it.

As a security purpose, chiseled images removed all the commands like curl, wget, rm, apt, apt-get etc. And it builds a non-interactive image container. So I choose the approach where I build a custom base image(docker file is attached below) in which, in first stage I used `debian:bookworm-slim` image which will have the commands that are used to install the agent and the final image is `aspnet:8.0-jammy-chiseled-extra` chiseled image. 

So the question is, Is there any security issue or vulnerability in the created custom base image? Also, the created custom base image can be considered as `aspnet:8.0-jammy-chiseled-extra` image with new relic agent installed?

Dockerfile of custom base image with newrelic dotnet agent installed.
```
FROM debian:bookworm-slim AS newrelic
ARG ENVIRONMENT_NAME
ENV ENVIRONMENT_NAME ${ENVIRONMENT_NAME}
RUN apt-get update && apt-get install -y procps wget ca-certificates gnupg \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update \
    && echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
    && wget https://download.newrelic.com/548C16BF.gpg \
    && apt-key add 548C16BF.gpg \
    && apt-get update \
    && apt-get install -y newrelic-dotnet-agent \
    && rm -rf /var/lib/apt/lists/*

FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled-extra AS base
COPY --from=newrelic /usr/local/newrelic-dotnet-agent /usr/local/newrelic-dotnet-agent
ARG NEW_RELIC_KEY

# Enable the agent
ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={90232161-FGC2-4B31-B559-F6E5DA1CAB9A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so \
NEW_RELIC_LICENSE_KEY=$NEW_RELIC_KEY

USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
```</div>

**Comment by richlander** [comment]
Provided answer at https://github.com/dotnet/dotnet-docker/discussions/5641?notification_referrer_id=NT_kwDOACfNVLMxMTMzNzg3MjI4NzoyNjA4NDY4#discussioncomment-9937185
