### ISSUE TITLE
Re-enable PowerShell Arm32 tests for 9.0

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5645]
Now that https://github.com/dotnet/runtime/issues/104106 is confirmed to be fixed, we can re-enable the PowerShell Arm32 tests by deleting this section of code: https://github.com/dotnet/dotnet-docker/blob/cf33fd0516835c363dc2d864748648e498cbe62d/tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs#L42-L46

This can only be done once nightly begins targeting Preview 7, where the fix is contained.

**Comment by lbussell** [comment]
Added to August Patch Tuesday so we'll remember this for Preview 7.
