### ISSUE TITLE
Please display image sizes in MiB on the mcr.microsoft.com

### ISSUE THREAD

**Issue by Hermholtz** [dotnet/dotnet-docker#5652]
### Problem

Sometimes I need to know the base image size so that I can select the smallest one (for example for tiny embedded machines).

By looking for example at this list: https://mcr.microsoft.com/en-us/product/dotnet/runtime/tags
I cannot see image sizes. It's a basic information that should be available even easier than a full SHA256 hash.

### Proposed solution

Please include image size in MiB in the list.
Alternative is to download the image by image and check it, which is not efficient in any context.

Thank you.

**Comment by richlander** [comment]
Here is an issue you can jump on: https://github.com/microsoft/containerregistry/issues/164. The `microsoft/containerregistry` repo is the correct repo to share the feedback. We're a user of that registry, just like you.
