### ISSUE TITLE
Re-enable aspnet app scenario test

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5657]
The aspnet app scenario test was disabled for certain conditions due to https://github.com/dotnet/runtime/issues/66310. That issue has since been resolved. We should re-enable the test now.

Note that the test is currently disabled with different conditions between the two branches right now:

https://github.com/dotnet/dotnet-docker/blob/e5a690412442a5c6f4ea7980d14d3f354e6b4651/tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs#L29-L34

https://github.com/dotnet/dotnet-docker/blob/1976a730ee19672ba3342990bb28b48b06205aff/tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs#L29-L34

**Comment by lbussell** [comment]
Tests are re-enabled with https://github.com/dotnet/dotnet-docker/pull/5680 and https://github.com/dotnet/dotnet-docker/pull/5681
