### ISSUE TITLE
Define common implementation for skipping tests

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5658]
The Blazor wasm test is intentionally disabled for the main branch by https://github.com/dotnet/dotnet-docker/commit/d150c8c8614da4f9f8c1b102f51ea9ba1aea84e7. But this same change does not exist in nightly because it is possible to run that test in that branch.

A similar situation exists for the SDK comparison test: https://github.com/dotnet-docker-bot/dotnet-docker/commit/df4580402ac8affe7a652acc4d0288d141ce300d

The test files between the branches should ideally be in sync. We should define an implementation that is common to both branches but differs in behavior based on some environmental input provided.

**Comment by lbussell** [comment]
[Triage] Blazor and Windows SDK Comparison tests aside, we should have a mechanism that allows us to skip tests dependent on branch (main vs. nightly) which allows us to keep the test source code the same.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/5699. We should use `Config.IsNightlyRepo` to skip tests based on branch.
