### ISSUE TITLE
Remove unncessessary ASP.NET Core 2.1 Dockerfile step 'RUN dotnet restore'

### ISSUE THREAD

**Issue by Andrioden** [dotnet/dotnet-docker#566]
[ASP.NET Core 2.1 sample Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile) has a uneccessary step, that also fails for other solution projects added to the solution, like a test project.

`RUN dotnet restore`

dotnet restore documentation states:
> [Starting with .NET Core 2.0, you don't have to run dotnet restore because it's run implicitly by all commands that require a restore to occur, such as dotnet new, dotnet build and dotnet run](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)

It is uncessessary because a publish/build command is later run, obviously.  : P

It fails for other projects because they have not been copied to the ./aspnetapp/ folder. You might think; "but add the other project with Copy", no, one does not always want to do so! Like for test projects which should not be built as part of the Dockerimage. Instead i want to only build the actual deployed aspnetapp.dll.

By removing the "RUN dotnet restore" step we make sure only the neccessary projects is restored.

**Comment by MichaelSimons** [comment]
@Andrioden - The pattern used in the sample Dockerfiles that performs an explicit restore is designed to avoid the overhead of restoring each time the Dockerfiles are built.  This is advantages for development scenarios where you are making changes and rebuilding the Dockerfiles numerous times.  See Docker's documentation on [build cache](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache).

In practice this means that when you first build the sample Dockerfile, the layers that correspond to each instruction are produced.  Now suppose you make a code change to a `.cs` file.  The restore layer is able to be reused when you `docker build`.  As a result your docker build will be faster (much faster if you have a bunch of NuGet dependencies).

The [dotnet sample Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile) shows this pattern in use with multiple projects.  Notice that the tests are built and run as part of the Docker build process.  Obviously this is a single sample and therefore may not meet your particular needs/desires.  We are open to feedback and want to hear usage patterns people find useful.

**Comment by Andrioden** [comment]
@MichaelSimons - Thank you for this detailed answer, I did not know that the build cache corresponds to each instruction! I am changing my code and closing this issue.
