### ISSUE TITLE
Consider using Microsoft-built Golang images for Ubuntu Chisel infrastructure

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5666]
We use Golang images from DockerHub in order to install and run the Chisel tooling in the Ubuntu Chiseled Dockerfiles.

https://github.com/dotnet/dotnet-docker/blob/2d5b83cb7b7c8c428a214e03aa8585a5129f884c/src/runtime-deps/8.0/noble-chiseled/amd64/Dockerfile#L1

We should consider using the Microsoft build of Golang, in the official Microsoft Golang images, to cut down on external dependencies - https://github.com/microsoft/go-images

As a side note, we should also have the Golang version defined as a variable in `manifest.versions.json`.

**Comment by MichaelSimons** [comment]
This might be appropriate for the Microsoft builds but doesn't feel appropriate for the public Dockerfiles given the Microsoft Golang images are for Microsoft only use.

**Comment by richlander** [comment]
I came to the same conclusion. It is a good idea to consider, but I think we should stay the course.

**Comment by lbussell** [comment]
Closing this in favor of https://github.com/dotnet/dotnet-docker/issues/5675, since we can just use the binary version of Chisel.
