### ISSUE TITLE
Unable to get website running as per instructions

### ISSUE THREAD

**Issue by alexkolt** [dotnet/dotnet-docker#567]
## Steps to reproduce the issue
1. Install Docker
2. Run command: docker run --name aspnetcore_sample --rm -it -p 8000:80 microsoft/dotnet-samples:aspnetapp
3. navigate to localhost:8000

## Expected result
App open

## Actual result
Website not found.

4. Now try to get IP Address as per Windows instructions. Run: docker exec aspnetcore_sample ipconfig. 

## Expected result
IP Address displayed

## Actual result
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"ipconfig\": executable file not found in $PATH": unknown

5. Try alternative to get IP Address. Run: docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" aspnetcore_sample

## Expected result
IP Address displayed

## Actual result
empty

6. Improvise. Run: docker inspect aspnetcore_sample. Find IPAddress: 172.17.0.2. Try to go to 172.17.0.2:8000

## Expected result
Website displayed

## Actual result
Website not found

7. On to stackoverflow. https://stackoverflow.com/questions/35731548/asp-net-on-docker-not-serving-web-app-to-browser. Take suggested IP Address - 192.168.99.100. Go to 192.168.99.100:8000

## Expected result / Actual result

Website displayed

## Additional information (e.g. issue happens only occasionally)
Windows 10 Home
Docker toolbox

## Output of `docker version`

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.05.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.05.0-ce (TCL 8.2.1); HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.6MiB
Name: default
ID: HGTC:4PAJ:5JCY:B4NL:JDZ4:4DMO:D5ZS:OLAF:UY3N:AW5Z:YGK4:DNUB
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Comment by MichaelSimons** [comment]
@alexkolt - The [ASP.NET Core apps in Windows Containers](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-windows.md) instructions are for running in a Windows containers environment.  By looking at the `docker version` you included, I can tell you are running in `linux containers mode` on a Windows machine.  These instructions are for running in `Windows containers mode`.  

When you are running within a linux containers environment, I would expect that you can access http://localhost:8000 from a browser running on the host machine.  Can you confirm those are the steps you tried?  Have you verified the aspnetcore_sample container is running?  What is the console output from your `docker run --name aspnetcore_sample --rm -it -p 8000:80 microsoft/dotnet-samples:aspnetapp` command?

**Comment by MichaelSimons** [comment]
To elaborate on the difference in the instructions between windows and linux containers... 

`docker exec aspnetcore_sample ipconfig` is a Windows specific instruction.  `ipconfig` is the Windows command that retrieves the IP address of the machine it is run on.  This is not a valid command in a typical Linux environment.  

`docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" aspnetcore_sample` is also a Windows Specific instruction.  This is because the docker NetworkSettings are different between Windows and Linux containers.

**Comment by alexkolt** [comment]
Michael,

Thank you for explaining. I'm not that familiar with Docker and that was default setup. Curious that it did that.

However I'm not able to access it using http://localhost:8000 link, only using http://192.168.99.100:8000.

I'll check the console output when I get home.

Thanks

**Comment by alexkolt** [comment]
```
$ docker run --name aspnetcore_sample --rm -it -p 8000:80 microsoft/dotnet-samples:aspnetapp
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {b096e2f1-0e4e-41f5-87be-a62b227f321e} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

**Comment by MichaelSimons** [comment]
In order to help pinpoint the issue could you try a different scenario such as `docker run --detach --publish 8000:80 --name webserver nginx`?  I'm trying to determine if this is a Docker host configuration issue or something specific to the ASP.NET Core sample image.

**Comment by alexkolt** [comment]
One liner response:
```
$ docker run --detach --publish 8000:80 --name webserver nginx
8bf0d883bf4585a5655f5b8a6492196f3e2939e8c8f019469cab64e8010866d6
```

**Comment by MichaelSimons** [comment]
@alexkolt - I forgot to include that after starting the container, you should try accessing http://localhost:8000.

**Comment by alexkolt** [comment]
Ok, tried that.

localhost:8000 does not work.

by docker ip: http://192.168.99.100:8000/ works, but takes me to nginx page, not the standard asp page.

What is my next step?

**Comment by MichaelSimons** [comment]
This confirms a docker host configuration issue and not something specific to the microsoft/dotnet image.  I've not seen this issue before and am not sure what the next step is.  Perhaps a question for https://stackoverflow.com/ or an [docker issue](https://github.com/moby/moby)

**Comment by alexkolt** [comment]
Thank you, will take it there.
