### ISSUE TITLE
Install Chisel tool from binaries instead of compiling from source

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5675]
Chisel is currently being installed by compiling it to produce the binaries:

https://github.com/dotnet/dotnet-docker/blob/dd53688fef338a92c9860840788a9e4ebbc78f9a/src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile#L8

Instead, we should just download the install tarball directly from the release page (e.g. [0.10.0](https://github.com/canonical/chisel/releases/tag/v0.10.0)).

This would prevent issues like https://github.com/dotnet/dotnet-docker/pull/5663. It also would make https://github.com/dotnet/dotnet-docker/issues/5666 irrelevant.

**Comment by lbussell** [comment]
Completed with https://github.com/dotnet/dotnet-docker/pull/5713
