### ISSUE TITLE
Dead link in aspnetapp sample README

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5693]
There is a dead link in the aspnetapp sample README file:

https://github.com/dotnet/dotnet-docker/blob/0e25bce9f186aa9d6f1bab5d5f25e69b5b5d3432/samples/aspnetapp/README.md#L77

`enable-healthchecks.md` does not exist.

**Comment by richlander** [comment]
https://github.com/dotnet/dotnet-docker/pull/5694
