### ISSUE TITLE
Container crashed when visit the app from browser.

### ISSUE THREAD

**Issue by SaekiRaku** [dotnet/dotnet-docker#570]
## Steps to reproduce the issue
1. Start by `docker-compose up -d`
2. Visit `http://127.0.0.1`
3. Then the `netcore` container crashed
4. And it generate a file in the project folder, file's name is `core.17478`, `core.15724`, etc. These files looks like crash logs, but it doesn't make sense to me. 

[https://github.com/SaekiRaku/Issue-dotnet-docker](https://github.com/SaekiRaku/Issue-dotnet-docker)

This is my test project repositorie . And it's running perfect on my other server. Just crashed on one of them.
You can find the `core.17478` file at [Issue-dotnet-docker/app/core.17478](https://github.com/SaekiRaku/Issue-dotnet-docker/blob/master/app/core.17478)

## Expected behavior

Container should running perfect.

## Actual behavior

Crash.

## Additional information (e.g. issue happens only occasionally)

* It's running perfect on my other server.
* And server's system version is `CentOS Linux release 7.3.1611 (Core)`
* Before crashed use `docker logs` to see the logs, and the output is：

```
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {5f527900-bd97-4b98-9b03-ebc3a3610d89} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

## Output of `docker version`

```
[root@www test]# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

## Output of `docker info`

```
Containers: 15
 Running: 12
 Paused: 0
 Stopped: 3
Images: 17
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.581GiB
Name: www.change.tm
ID: JWA2:LITY:26FB:54ND:HWHY:FCV7:CFHZ:KSW2:QYVQ:BKSA:V2KA:OFV7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
@SaekiRaku - do you have SELinux enabled on your Docker host machine?  I suspect you have encountered https://github.com/dotnet/coreclr/issues/17931.

**Comment by SaekiRaku** [comment]
@MichaelSimons No, I checked my server and SELinux is `disabled`.

![image](https://user-images.githubusercontent.com/12109558/41070764-2200b4bc-6a27-11e8-9f62-71d214d601ed.png)

**Comment by MichaelSimons** [comment]
@SaekiRaku - can you try running with the 2.1 images in microsoft/dotnet-nightly.  These images contain the latest 2.1.1 fixes.

**Comment by SaekiRaku** [comment]
@MichaelSimons - 😆Wow, Amazing! It's worked! Thank you very much.
