### ISSUE TITLE
BlazorWASM scenarios in .NET 6 on CBL Mariner 2.0 require the `which` package

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5700]
.NET 6 CBL Mariner 2.0 SDK has an issue with BlazorWASM build scenarios because the SDK is unable to find the correct python version. I confirmed that installing `which` fixes this scenario. See https://github.com/dotnet/runtime/issues/98714#issuecomment-2196644017.

We should either install `which` in the .NET 6 CBL Mariner 2.0 SDK image, or install `which` as part of our test scenario.

The disabled test in question is here: https://github.com/dotnet/dotnet-docker/blob/0d3b28e55ab1db56c25ba3ecd3a0abacc520158d/tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs#L66-L71

**Comment by richlander** [comment]
Installing tools in the official images to make tests work seems bad, particularly after the major .NET version has transitioned to maintenance.

**Comment by MichaelSimons** [comment]
> Installing tools in the official images to make tests work seems bad, particularly after the major .NET version has transitioned to maintenance.

I don't see this as a "test" scenario rather it is the E2E use case for building a BlazorWASM project template.

That being said, I don't think this meets the servicing bar for the last 6 months of the LTS release.  I would be more interested in if this affects .NET 8.0 +.

**Comment by lbussell** [comment]
Yes, I agree with Michael - this is a user scenario that has never worked, yet it should have worked from the beginning. It's not a case of adding the package as a tool just for our tests. `which` is a required dependency for the SDK to function properly. Whether it meets the bar is a separate question. Documentation might be sufficient here.

**Comment by richlander** [comment]
Got it. If this is also present with .NET 8, then we should engage the scenario owners.

**Comment by lbussell** [comment]
It is .NET 6 only.

**Comment by richlander** [comment]
Seems like we can pass on this then, yes?

**Comment by lbussell** [comment]
[Triage] Since we haven't received any complaints about this specific scenario and it's late in .NET 6's servicing lifecycle, we shouldn't add `which` to the image. We can however add the package to our test to validate the scenario.
