### ISSUE TITLE
Broken repo pages on Docker Hub

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5742]
There's an issue with the repo pages on Docker Hub where pages using a certain URL format are no longer loading (404 result). This is pervasive across all Microsoft-owned repos.

Example broken URL: https://hub.docker.com/_/microsoft-dotnet-sdk/
Example working URL: https://hub.docker.com/r/microsoft/dotnet-sdk/

This is a regression as the currently broken URL format was previously working.

We're working with the MAR team which manages the Docker Hub content syndication to get this issue resolved: [IcM ticket](https://portal.microsofticm.com/imp/v3/incidents/incident/527764874/summary) (internal link).

**Comment by lbussell** [comment]
@mthalman, should we just proactively update these links now? https://github.com/dotnet/dotnet-docker/blob/41a2f2766ff71601aef369a7b7ddc2d9bacaaebc/.portal-docs/docker-hub/README.md?plain=1#L9-L14

**Comment by mthalman** [comment]
I don't know how that file was generated. It doesn't reflect the current state of the branch. It's in main but the links are for nightly. The readme in mcrdocs is defined with the correct links:

https://github.com/microsoft/mcrdocs/blob/e9987f444ce05835d76a86d017c3edbedfc64f86/teams/dotnet/README.md?plain=1#L3-L9

**Comment by mthalman** [comment]
> I don't know how that file was generated. It doesn't reflect the current state of the branch. It's in main but the links are for nightly. The readme in mcrdocs is defined with the correct links:
> 
> https://github.com/microsoft/mcrdocs/blob/e9987f444ce05835d76a86d017c3edbedfc64f86/teams/dotnet/README.md?plain=1#L3-L9

Follow up on cleaning that up: https://github.com/dotnet/dotnet-docker/pull/5743

**Comment by mairaw** [comment]
It's interesting because for me the links work on and off again. Last night, I first saw all the featured repos links not working and then only the aspire one. 

One minute ago, https://hub.docker.com/_/microsoft-dotnet-sdk/ was broken, and then right at this minute is redirecting to https://hub.docker.com/r/microsoft/dotnet-sdk

**Comment by mthalman** [comment]
Yep, there is weird behavior with redirection, or lack thereof, on Docker Hub's side. There's nothing wrong with how our page's links are defined.

**Comment by lbussell** [comment]
[Triage] It seems that our latest readme update (https://github.com/microsoft/mcrdocs/commit/ea7413687f57a5c90554113e43b103c1e0be44cc) may not have been correctly syndicated to DockerHub. We should try to update the main readme again and see if that resolves the issue on our product family page. The issue will still exist for search results and other links not managed by us however.

**Comment by lbussell** [comment]
[Triage] This appears to be fixed now. Links between DockerHub pages no longer lead to a 404 page.
