### ISSUE TITLE
Sectigo Code Signing Certificate Trust

### ISSUE THREAD

**Issue by josephdecock** [dotnet/dotnet-docker#5750]
### Describe the Bug

The "Sectigo Public Code Signing Root R46" certificate is not trusted by the 8.0 sdk images. This causes build warnings or errors when trying to validate the signatures of NuGet packages signed with a certificate that was issued by Sectigo.

### Steps to Reproduce

From the sdk:8.0 image:

```sh
mkdir repro
cd repro
dotnet new web
dotnet add package Duende.IdentityServer --version 7.0.6 # This package was signed with sectigo's certificate
dotnet build
```

And you get warning NU3042 (The following X.509 root certificate is untrusted because it is not present in the certificate bundle at /usr/share/dotnet/sdk/8.0.303/trustedroots/codesignctl.pem.)

### Other Information

Sectigo has both an intermediate certificate, signed by AAA, and a newer root CA that they self sign. A windows update on May 28 added the newer certificate to the trusted root CA store. This eventually made its way into the build pipeline for the NuGet packages I create (Duende.IdentityServer, etc), and the result is NuGet packages that are signed with a certificate chain that terminates at the new root CA. Because this is not trusted by the sdk, consumers of my NuGet packages are getting build failures. 

As a workaround, I've instructed my users to add the new Sectigo Public Code Signing Root R46 to the certificate bundle mentioned in the error message. 

How often is that certificate bundle changed? Can it be updated to include Sectigo's new certificate?

For reference, the new self-signed sectigo certificate has thumbprint ccbbf9e1485af63ce47abf8e9e648c2504fc319d.

### Output of `docker version`

Conversations
docker output
Inbox
Joe DeCock
	
Attachments1:02 PM (0 minutes ago)
	
to me

 2 Attachments  •  Scanned by Gmail
	

Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/josephdecock/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 11
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 37087817-9888-4cde-b926-4f556a9ce4fe
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/josephdecock/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by richlander** [comment]
The behavior differs by OS:

- macOS: Validation is opt-in and uses the cert bundle in the SDK
- Linux: Validate is enabled and uses the global code signing cert store if present and the cert bundle in the SDK if not
- Windows: Always uses the global cert store

The cert bundle in the SDK is updated regularly: https://github.com/dotnet/sdk/pulls?q=is%3Apr+Trusted+roots

I'll ask about this particular cert chain.

**Comment by dtivel** [comment]
@josephdecock, the new Sectigo certificate is already in the codesignctl.pem certificate bundle [here](https://github.com/dotnet/sdk/blob/release/8.0.3xx/src/Layout/redist/trustedroots/codesignctl.pem#L8623-L8654).

I think my commit merged after 8.0.303 was published, so the change is not in 8.0.303.  It'll be in the next release though.

**Comment by josephdecock** [comment]
Thanks so much @dtivel! Am I right to assume that the next release will be on the second tuesday of the month - August 13th?

**Comment by richlander** [comment]
Yes. We have a release planned for that day.

**Comment by richlander** [comment]
Please report back if you don't see the results you expect. Closing since this has already been resolved.

**Comment by richlander** [comment]
BTW: You can test with a nightly build.

https://github.com/dotnet/sdk/blob/main/documentation/package-table.md
