### ISSUE TITLE
Document policy on when support is added for new OS versions

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5756]
The [Supported Platforms documentation](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md) describes what Linux distros and Windows versions are supported as well as what new versions will have support added for.  The document is not specific however on **when** the new versions will appear.  For example the document states the following for Ubuntu:

> As new LTS versions are released, support is added to the latest .NET version and latest LTS (if they differ).

Is support added during the next .NET servicing cycle or within "n" days of the OS release date?  What is the SLA?

Capturing these specifics will guide the expectations of customers and will be the basis for them to provide feedback on.  It will also instruct the development team on how to operate.

**Comment by richlander** [comment]
I think we should document this as "best effort" along the lines of: "We will add support for new operating system versions at best effort, typically within one month, and often aligning with our next monthly update."

In the past, this was very difficult with the required RID updates. Those are no longer a problem, so it seems like its just testing that we're dependent on at this point.
