### ISSUE TITLE
Docker Hub readme does not get generated by eng\readme-templates\Get-GeneratedReadmes.ps1

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5763]
If you modify https://github.com/dotnet/dotnet-docker/blob/main/eng/readme-templates/About.product-family.md and regenerate the readmes via running eng\readme-templates\Get-GeneratedReadmes.ps1, https://github.com/dotnet/dotnet-docker/blob/main/.portal-docs/docker-hub/README.md will not be regenerated.

This looks to be a regression caused by https://github.com/dotnet/dotnet-docker/pull/5603.  The manifest only [has one product family readme defined](https://github.com/dotnet/dotnet-docker/blob/main/manifest.json#L2).  There is no product family readme defined for Docker Hub.

**Comment by mthalman** [comment]
That file is unnecessary anyway. It's been deleted in nightly: https://github.com/dotnet/dotnet-docker/pull/5743.
