### ISSUE TITLE
UpdateDependencies tool should not update Syft version if there are no new .NET versions

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5788]
This is to reduce developer toil and compute usage. We should only update Syft when there is an actual product update. See https://github.com/dotnet/dotnet-docker/pull/5784 for example. The resulting PR title is also incorrect.

Related: https://github.com/dotnet/dotnet-docker/issues/4545

**Comment by mthalman** [comment]
You could make an argument that updating Syft independently of .NET version updates is the correct behavior. The Dockerfiles are not dependent on the Syft version; it's the tests that depend on it. And those can be run even if the Dockerfiles haven't changed. It would help to catch any issues outside the context of any .NET version update.

**Comment by lbussell** [comment]
Good point. I think something is up with our PR validation triggering, since https://github.com/dotnet/dotnet-docker/pull/5784 didn't trigger the tests.

**Comment by mthalman** [comment]
> Good point. I think something is up with our PR validation triggering, since #5784 didn't trigger the tests.

Weird. It should have according to the path filters: https://github.com/dotnet/dotnet-docker/blob/7c3be0e21508f8eb34d53618dce1d14323fcab10/eng/pipelines/dotnet-core-pr.yml#L6-L12

**Comment by lbussell** [comment]
[Triage] This seems like it'll be a rare occurrence, so devs should just make sure to update the dependency flow PR title before a syft update gets merged by itself. We should file a follow-up issue to update the dependency flow PR title to a more generic one.
