### ISSUE TITLE
`src/aspnet/9.0/noble-chiseled-composite/arm32v7` Dockerfile associated with incorrect Image

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/dotnet-docker#5859]
While writing the schema tag tests for https://github.com/dotnet/dotnet-docker/issues/5838, I discovered the discrepancy in the manifest.json:

The `src/aspnet/9.0/noble-chiseled-composite/arm32v7` dockerfile is associated with the following tags in the nightly branch:
-  9.0.0-rc.1-noble-chiseled-composite-arm32v7
- 9.0-noble-chiseled-composite-arm32v7
- 9.0.0-rc.1-azurelinux3.0
- 9.0-azurelinux3.0

In the manifest you can see it listed [here](https://github.com/dotnet/dotnet-docker/blob/nightly/manifest.json#L7512-L7526) with the azurelinux3.0 images.

I believe that this dockerfile is associated with the incorrect image. It should be listed in [this part](https://github.com/dotnet/dotnet-docker/blob/nightly/manifest.json#L7446-L7473) of the manifest.

**Comment by mthalman** [comment]
Did this cause a test failure in the tests you're working on or was this something you discovered manually? We should ensure that we have a test that can catch a scenario like this.

**Comment by ellahathaway** [comment]
> Did this cause a test failure in the tests you're working on or was this something you discovered manually?

This was something that I caught with two of the tests that I was writing. Those two tests validate that each dockerfile has the correct multi-platform tags; The tests expected this dockerfile to have `9.0.0-rc.1-noble-chiseled-composite` and `9.0-noble-chiseled-composite`, respectively, and failed when they did not exist.

**Comment by lbussell** [comment]
Fixed in https://github.com/dotnet/dotnet-docker/pull/5866
