### ISSUE TITLE
dotnet push-to-deploy images

### ISSUE THREAD

**Issue by alrz** [dotnet/dotnet-docker#5861]
### Describe the Problem

In staging environments a push-to-deploy setup can be much faster by moving the build inside the same container as app.

### Describe the Solution

The container would host a git bare repo that changes will be pushed to. When push hooks are triggered the source is rebuild and deployed inside the same instance.

**Comment by lbussell** [comment]
Hi @alrz - it's not clear what you are asking here. Are you asking for a sample showing a continuous deployment setup with .NET container images?

There are many fast and continuous deployment methods that don't involve hosting your app in a .NET SDK image or rebuilding the app inside the deployed container. For example, [Deploy to Azure Container Apps with GitHub Actions](https://learn.microsoft.com/azure/container-apps/github-actions).

**Comment by lbussell** [comment]
[Triage] Closing this issue as not planned since there's no clear work to be done here and no response from @alrz.
