### ISSUE TITLE
Package validation tests are failing for Jammy chiseled 

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5898]
The `VerifyInstalledPackages` tests are failing for all jammy-chiseled jobs:

```
Assert.Equal() Failure
Expected: OrderedEnumerable<String, String> ["base-files", "ca-certificates", "libc6", "libgcc-s1", "libssl3", ...]
Actual:   DistinctIterator<String> ["base-files", "ca-certificates", "gcc-12-base", "libc6", "libgcc-s1", ...]
```

It seems there is a new `gcc-12-base` package showing up.

[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2542303) (internal link)

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/5899
