### ISSUE TITLE
Stop referencing Docker Hub repos in GitHub readmes and documentation

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5905]
In the past, the Docker Hub repo readmes were preferred because of the nicely formatted tags table.  Due to size constraints these were removed.  Because of that, it no longer makes sense to direct readers of the GitHub readmes and documentation to the Docker Hub readmes.  Instead, the links should be updated to reference the appropriate GitHub readmes.

This is related to https://github.com/dotnet/dotnet-docker/issues/5872#issuecomment-2356458998

**Comment by lbussell** [comment]
[Triage] This was fixed for dotnet-docker in https://github.com/dotnet/dotnet-docker/pull/5921

@MichaelSimons Please file a follow-up issue to fix this in the microsoft/dotnet-framework-docker repo as well.
