### ISSUE TITLE
Can I run my windows exe in dotnet container?

### ISSUE THREAD

**Issue by iver3on** [dotnet/dotnet-docker#591]
if not how I can do it.
My container is Linux OS.
I try wine but it not worked.
any other suggestions?
Thanks a lot.

**Comment by MichaelSimons** [comment]
You can run a .NET Core application within Windows or Linux based containers using the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) images.  The [.NET Core Docker samples](https://github.com/dotnet/dotnet-docker/blob/master/samples/README.md) show how.

You can run a .NET Full Fx application within in Windows based containers using the [microsoft/dotnet-framework](https://hub.docker.com/r/microsoft/dotnet-framework/) images.  The [.NET Full FX samples](https://github.com/Microsoft/dotnet-framework-docker/blob/master/samples/README.md) show how.

**Comment by MichaelSimons** [comment]
@iver3on - Did my response help answer your questions?  If not can you explain your scenario in more detail of what you would like to achieve?

**Comment by MichaelSimons** [comment]
Closing - if there are additional questions, feel free to continue the conversation or log a new issue.
