### ISSUE TITLE
Documentation is asking to pull a .NET 8.0 Image for a .NET 9.0 target sample app. 

### ISSUE THREAD

**Issue by RickyNotaro** [dotnet/dotnet-docker#5919]
Documentation outdated since #5882
### Describe the Bug
 
Since #5882, the dotnet sample app is targeting dotnet 9. The documention in https://github.com/dotnet/dotnet-docker/blob/main/samples/build-in-sdk-container.md is guiding the user to use the dotnet/sdk:8.0 image. 
 
Following the documentation gives an error : `/usr/share/dotnet/sdk/8.0.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(166,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 9.0.  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0. Download the .NET SDK from https://aka.ms/dotnet/download [/app/dotnetapp.csproj]`
### Steps to Reproduce
```
cd samples/dotnetapp/
docker pull mcr.microsoft.com/dotnet/sdk:8.0
docker run --rm -v ${pwd}:/app -w /app mcr.microsoft.com/dotnet/sdk:8.0 dotnet publish -c Release -o out -r win-x64 --self-contained false
[ERROR NETSDK1045]
```
### Other Information
 
Issue is not happening when using sdk:9.0

**Comment by lbussell** [comment]
Thanks, this slipped by me in #5858! I'll get it fixed ASAP.
