### ISSUE TITLE
Missing tags for .NET Monitor

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#5932]
As identified in https://github.com/dotnet/dotnet-docker/pull/5878#discussion_r1756929430, the .NET Monitor tag pattern is different than the .NET Aspire tag pattern.

### .NET Monitor Tags
.NET Monitor tag pattern for 8.x and lower is:
- `<major>.<minor>.<patch>-<distro>-<arch>`
- `<major>.<minor>.<patch>-<distro>`
- `<major>.<minor>.<patch>`
- `<major>.<minor>-<distro>-<arch>`
- `<major>.<minor>-<distro>`
- `<major>.<minor>`
- `<major>-<distro>-<arch>`
- `<major>-<distro>`
- `<major>`

.NET Monitor tag pattern for 9+ is:
- `<major>.<minor>.<patch>-<arch>`
- `<major>.<minor>.<patch>` 
- `<major>.<minor>-<arch>`
- `<major>.<minor>`
- `<major>`

The tag pattern is simpler compared to 8.x and lower since only a single distro is offered in .NET Monitor 9 and higher.

### .NET Aspire Tags
.NET Aspire tag pattern is:
- `<major>.<minor>.<patch>-<arch>`
- `<major>.<minor>.<patch>` 
- `<major>.<minor>-<arch>`
- `<major>.<minor>`
- `<major>-<arch>`
- `<major>`

### Missing .NET Monitor Tags Compared to .NET Aspire
Compared to .NET Aspire, it appears that .NET Monitor is missing the following tags:
- 9.x and higher: `<major>-<arch>`
- 8.x and lower: `<major>-<arch>` and `<major>.<minor>-<arch>`

### Other Observations
The main .NET product also does not have `<major>.<minor>-<arch>` tags. The .NET Monitor product largely mimicked the main .NET product tagging pattern, hence the lack of this tag.

### Proposed Changes
For consistency among the appliance-style images, I propose the following changes:
- Add `<major>-<arch>` and `<major>.<minor>-<arch>` to .NET Monitor 8.x
- Add `<major>-<arch>` to .NET Monitor 9.x

The team should also consider whether runtime-deps/runtime/aspnet/sdk images should have `<major>.<minor>-<arch>` convenience tags as well.

**Comment by lbussell** [comment]
[Triage] After some discussion, we decided that arch-specific tags provide little value for appliance-style images, so we should not create additional tags to resolve this discrepancy between .NET monitor and aspire-dashboard images. Instead, we should open a second issue with a proposal to remove arch-specific tags from appliance images. That issue should include updating the [supported tags documentation for appliance images](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md), and should also call out any discrepancies between tagging patterns for appliance style images.

Related: https://github.com/dotnet/dotnet-docker/issues/5918
