### ISSUE TITLE
.NET Monitor docs should describe purpose and usage of dotnet/monitor/base image

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#5933]
There are two .NET Monitor images that are produced:
- `dotnet/monitor`
- `dotnet/monitor/base`

It is not obvious what the difference is between these two images and why a customer would choose one over the other.

Brief explanation of the difference between the two:
- `dotnet/monitor` is the image intended for the vast majority of customers to use. It is the entire composite of the full .NET Monitor offering, including the base tool installation and all .NET Monitor extensions.
- `dotnet/monitor/base` is a base image that contains only the core .NET Monitor package. Extensions such as egress providers do not exist in this image. This image is meant as a building block for producing a customized image that only contains the extensions that a given customer would need.

Fortunately, the featured repos of most of the documentation steer customers toward the `dotnet/monitor` image. However, the `dotnet/monitor/base` image has very little documentation about why it exists and how it should be used.

The current proposal is that:
- the `dotnet/monitor` documentation should be updated to succinctly refer to the base image and its purpose
- the `dotnet/monitor/base` documentation should be updated to describe in detail the purpose of the image and how it can be used.

**Comment by lbussell** [comment]
[Triage] @jander-msft are you able to complete this before November Patch Tuesday?
