### ISSUE TITLE
Undocument arch-specific tags on .NET appliance images

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-docker#5946]
### Describe the Problem

The appliance-style (`dotnet/monitor` and `dotnet/aspire-dashboard`) and sample (`dotnet/samples`) images have various tags for describing the product version, the architecture, and distro of the image. While distro information has been removed in newer releases, the architecture and product version information remains. The tag listing for these images can be intimidating due to the matrix of possibilities and may lead to choice paralysis or confusion as to which tag should be used.

Upon further reflection, the tag matrix can be greatly simplified if the arch-specific tags are removed or undocumented. An example simplification in this manner is described for the sample images in #5918. Using `dotnet/monitor:8` Ubuntu Chiseled as another example, the tag listing would be simplified from:

```
8.0.4-ubuntu-chiseled-amd64, 8.0-ubuntu-chiseled-amd64, 8-ubuntu-chiseled-amd64, 8.0.4-ubuntu-chiseled, 8.0-ubuntu-chiseled, 8-ubuntu-chiseled, 8.0.4, 8.0, 8, latest
```
to
```
8.0.4-ubuntu-chiseled, 8.0-ubuntu-chiseled, 8-ubuntu-chiseled, 8.0.4, 8.0, 8, latest
```

### Describe the Solution

- [x] For `dotnet/aspire-dashboard:8*` images, all arch-specific tags are to be undocumented to prevent breaking changes in current usage.
- [x] For `dotnet/monitor:9*` and lower version images, all arch-specific tags are to be undocumented to prevent breaking changes in current usage.
- [ ] For `dotnet/samples` images, all arch-specific tags are to be removed.

For `dotnet/monitor/base`, all arch-specific tags are to remain since this is a base image used for adding extensions upon it, which may require native dependencies or may have native entrypoints.

### Additional Context

The arch-specific tags are largely useful for images that are meant to be used as base images upon which derivative images are produced, especially if native dependencies are added in the deriving image. Given that the appliance-style and sample images are intended to be used as-is (not expected to be derived), the arch-specific tags do not provide much value. The assumption is that the vast majority use case is that users will use the manifest tags as-is without needing to further specify the platform. If needed, users can specify platform information on container tooling (such as `docker run --platform linux/amd64` or `FROM --platform linux/amd64` within Dockerfiles) to specify which architecture should be used.

**Comment by jander-msft** [comment]
I've updated the issue to reflect that arch-specific tags of .NET Monitor 9 and lower are to be undocumented rather than having a bifurcation of treatment between 9 vs 8 and lower.

**Comment by lbussell** [comment]
This proposal is documented in detail in this announcement: [New tagging scheme for .NET Monitor, Aspire Dashboard, and samples (dotnet/dotnet-docker#5961)](https://github.com/dotnet/dotnet-docker/discussions/5961)

@jander-msft, since [Simplify dotnet/samples tags tables by un-documenting arch specific tags (#5918)](https://github.com/dotnet/dotnet-docker/issues/5918) already exists, what do you say we "re-target" this issue to refer to appliance-style images only, and close it since they have been undocumented. We can track the samples work with #5918.

And we can open two/three new issues for removing the tags completely (Samples, Monitor, and Aspire Dashboard).
