### ISSUE TITLE
Create breaking change announcement for .NET Monitor 9.0 OS changes

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5958]
.NET Monitor 9.0 is offered on Azure Linux 3.0 only, and the OS version has been removed from the tag since there is no selection to be made. A breaking change issue should be created at https://github.com/dotnet/docs

See the breaking change issue from .NET 8 as a reference: https://github.com/dotnet/docs/issues/38043

**Comment by jander-msft** [comment]
Breaking change announcement has been requested: https://github.com/dotnet/docs/issues/43379

**Comment by lbussell** [comment]
Thanks Justin!
