### ISSUE TITLE
Without node, need powershell in nanoserver images

### ISSUE THREAD

**Issue by andreujuanc** [dotnet/dotnet-docker#597]
Hi, now that nodejs was removed from official microsoft images, installing node is not as easy as it seems.

The problem is that looks like nanoserver image does not include powershell. Which makes things complicated to download/unpack/checksum/etc.

There is almost no serious web development that does not include node. I understand that diferent node versions was getting out of hand. 

But for Visual Studio users, we cannot do multistage debugging. VS overrides dockerfile and executes only the first state + some mounts from the local dev machine. (See https://stackoverflow.com/questions/46949192/docker-applications-works-fine-via-docker-compose-up-but-how-to-run-it-via-vis/47095754#47095754 )

That makes hard to do multistage to install node, when there is no powershell in the first image.

There is no problem in linux when you can just curl, etc.

My feature request is just that this repo, being the official one, should listen to developers and understand realworld scenarios.

I'm not the only one who thinks this way: https://github.com/dotnet/dotnet-docker/issues/360 

I opened this issue, because that one is open since Jan2018 and that one is specifically about PSCore.

Cheers!

**Comment by andreujuanc** [comment]
We can't do it like this https://github.com/aspnet/aspnet-docker/blob/5a0c97dd61e8ed4e1c8c8e7264b3f17ae87e9866/2.1/nanoserver-1709/amd64/runtime/Dockerfile in vs2017 because of the way debugging works.

**Comment by MichaelSimons** [comment]
We are working on getting PS added to the SDK image.  There are several pieces that need to fall into place first.  This work is being tracked with #360.

**Comment by andreujuanc** [comment]
Alright, fair enough! thanks!
