### ISSUE TITLE
NuGet push

### ISSUE THREAD

**Issue by vassilvk** [dotnet/dotnet-docker#60]
This is more of a question/discussion.

In a CI scenario where this Docker image is used to build, test and deploy a NuGet package, how would one go about the third step -- deploy to a NuGet repository?

In the previous Mono-based Docker image ([ASP.NET RC1](https://hub.docker.com/r/microsoft/aspnet/)) we had `nuget cli` included in the image, so one could do `nuget push`.

With this new image, I see no way to push to a NuGet repository through `dotnet cli`, nor do I see `nuget cli` being included.

Looking around, I can't even find if `nuget` is ported to CoreCLR. If it isn't, then the only option left is to build a derivative Docker image which includes `nuget` CLI, which means also including Mono -- seems like a departure from the clean CoreCLR-only approach.

I think in an ideal world, either `dotnet cli` will provide a `push` action to deploy to NuGet repositories, or `nuget cli` would be ported to CoreCLR. If not, this Docker image is only half-way there as it relates to a CI scenario, which would be one of the best selling points of using Docker to begin with.

I'd appreciate anyone's thoughts on this.

**Comment by MichaelSimons** [comment]
NuGet client has been ported to [.NET Core](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core).  The dotnet CLI defers to it when performing the NuGet related commands it exposes such as dotnet restore.  There is a [NuGet.CommandLine.XPlat](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.CommandLine.XPlat) assembly which can be used to perform a [push](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PushCommand.cs).

The long term plan for how the NuGet commands will be exposed in the dotnet CLI is changing/TBD with the move to msbuild.  Follow the activity on [dotnet CLI ](https://github.com/dotnet/cli) as well as [NuGet ](https://github.com/nuget/home) for more information on this evolves.

In the mean time if you want to play around the NuGet.CommandLine.XPlat.dll I was able to invoke it  via 'dotnet NuGet.CommandLine.XPlat.dll' after dropping the following NuGet.CommandLine.XPlat.runtimeconfig.json next to the dll in `/usr/share/dotnet/sdk/1.0.0-preview2-003121`

```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0"
    }
  }
}
```

**Comment by naamunds** [comment]
Another option is to use the existing dotnet.runtimeconfig.json, which has the same content as what you pasted above, by using the `runtimeconfig` argument.  For example: `dotnet exec --runtimeconfig /usr/share/dotnet/sdk/1.0.0-preview2-003121/dotnet.runtimeconfig.json /usr/share/dotnet/sdk/1.0.0-preview2-003121/NuGet.CommandLine.XPlat.dll push [...]`

**Comment by vassilvk** [comment]
Thanks @MichaelSimons, @naamunds.
