### ISSUE TITLE
TFS 2015 (on-premise) No test runs are available for this build.

### ISSUE THREAD

**Issue by sajeelmunir** [dotnet/dotnet-docker#603]
## Steps to reproduce the issue
1. dotnet-docker-unit-testing 
2. I was using "docker build --pull --target testrunner -t dotnetapp:test . "
3. restore, build and test compiles OK

## Expected behavior
Project should build and Publish Test Results

## Actual behavior
No test runs are available for this build.

## Output of `docker version`

```
2018-06-18T15:59:01.5089350Z ##[section]Starting: Publish Test Results **/TestResults/.trx
2018-06-18T15:59:01.5169352Z ==============================================================================
2018-06-18T15:59:01.5169352Z Task : Publish Test Results
2018-06-18T15:59:01.5169352Z Description : Publish Test Results to VSTS/TFS
2018-06-18T15:59:01.5169352Z Version : 1.0.36
2018-06-18T15:59:01.5169352Z Author : Microsoft Corporation
2018-06-18T15:59:01.5169352Z Help : More Information
2018-06-18T15:59:01.5169352Z ==============================================================================
2018-06-18T15:59:01.5289370Z Preparing task execution handler.
2018-06-18T15:59:04.1029466Z Executing the powershell script: C:\dockerbuild_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.36\PublishTestResults.ps1
2018-06-18T15:59:04.7099383Z ##[warning]No test result files were found using search pattern 'C:\dockerbuild\2\s*\TestResults*.trx'.
2018-06-18T15:59:04.7379423Z ##[section]Finishing: Publish Test Results **/TestResults/*.trx
```

## Output of `docker info`

```
[warning]No test result files were found using search pattern 'C:\dockerbuild\2\s*\TestResults*.trx'.
```

How to Publish Test Results to VSTS/TFS? Any suggestions ?

**Comment by MichaelSimons** [comment]
@sajeelmunir, It is not clear to me what steps you are following to get the following warning

> [warning]No test result files were found using search pattern 'C:\dockerbuild\2\s*\TestResults*.trx'.

Can you please clarify? What cmds are you executing after your three repo steps?  Are you running the tests as described in https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-unit-testing.md#running-a-test-runner-container?

**Comment by sajeelmunir** [comment]
Hi @MichaelSimons ,
Thank you for your prompt reply. Yes, I am running the tests as described.

**1- TFS: Building a Continuous Delivery Pipeline:**
- (Docker Command 1) = "docker build --pull --target testrunner -t dotnetapp:test ."
- (Docker Command 2) = "docker run --rm -v C:\git\dotnet-docker\samples\dotnetapp\TestResults:/app/tests/TestResults dotnetapp:test"

**Works fine and create a test file:**
Project: dotnet-docker\samples\dotnetapp
(Dockerfile) WORKDIR /app
Test Results File Log: C:\app\tests\TestResults\ContainerAdministrator_85B0DDBF1064_2018-06-19_20_22_05.trx

**2- VsTest - testAssemblies failed:**
##[error]Error: Search folder: 'C:\app\tests\TestResults' should be a directory and it should exist.

How to set up build deployment pipeline? Please let me know if I am missing something or if something should be changed.

Thank you in advance.

**Comment by MichaelSimons** [comment]
Can you include the output from running `docker info` and `docker version` so that I know what your docker configuration looks like?  Thanks

**Comment by MichaelSimons** [comment]
@sajeelmunir , Sorry I'm still not understanding your repo steps.  What are you doing after `(Docker Command 2)` which leads to `##[error]Error: Search folder: 'C:\app\tests\TestResults' should be a directory and it should exist.`?

**Comment by sajeelmunir** [comment]
@MichaelSimons 
**λ docker info**
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 182
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.94GiB
Name: Home
ID: HXZV:OMVE:WK2T:COJQ:CPEX:5DCX:GN4E:JO5Z:2RQF:JFAL:VQMV:DJHJ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2018-06-19T22:04:50.8407522+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**λ docker version**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

**Comment by sajeelmunir** [comment]
@MichaelSimons 

Building a Continuous Delivery Pipeline STEPS:
**1- Docker_Command.png**
![docker_command](https://user-images.githubusercontent.com/30804434/41624506-d8fab376-740d-11e8-8446-934181c9ecb3.png)
**2- Copy_Files.png**
![copy_files](https://user-images.githubusercontent.com/30804434/41624528-e3e9e55e-740d-11e8-8408-2e70e0022277.png)
**3- vsTest.png**
![vstest](https://user-images.githubusercontent.com/30804434/41624542-eff201c4-740d-11e8-8f3d-b5e96fd117c5.png)

**Comment by sajeelmunir** [comment]
@MichaelSimons 
![vstest_build failed](https://user-images.githubusercontent.com/30804434/41624841-c36c6f08-740e-11e8-8c36-e1d74ac17366.png)

**Comment by MichaelSimons** [comment]
I noticed two things:
1. In screen shot 1, you volume mount the Build.SourcesDirectory into the Docker container to copy the test results to.  In screen shot 2, your copy source is the Agent.BuildDirectory.  I would expect the two paths to be the same.
2. I don't understand the purpose of screen shot 3.  The tests where already run as a result of the docker command executed in screen shot 1.  The trx file stores test results in XML simple text file format.

**Comment by MichaelSimons** [comment]
@sajeelmunir - I think the trick is to use the Publish Test Results task since the tests have already been run in the container.
![image](https://user-images.githubusercontent.com/8290530/41663853-ff721db2-7469-11e8-9eab-697051ec0f90.png)

In my example, I am using the Build.StagingDirectory as the location to put the test results in.
![image](https://user-images.githubusercontent.com/8290530/41663936-31519c9a-746a-11e8-9c9b-f3b4d837027a.png)

Now the `Tests` tab is populated.
![image](https://user-images.githubusercontent.com/8290530/41665208-0eebeaf4-746d-11e8-8457-6e3638f795e4.png)

**Comment by sajeelmunir** [comment]
@MichaelSimons 

It works like a charm! I really appreciate your support! Thank you so much for taking the time to read and respond! 👍 

Could you please share "**Build dotnetapp test and test dotnetapp**" screenshots as well? i hope you won't mind. 🥇 

Cheers,

**Comment by MichaelSimons** [comment]
![image](https://user-images.githubusercontent.com/8290530/41677356-ac74c24e-748d-11e8-8b14-79f6adf02ba3.png)

![image](https://user-images.githubusercontent.com/8290530/41677425-dc036d12-748d-11e8-879a-d88a2d4a8672.png)

**Comment by MichaelSimons** [comment]
Closing, feel free to continue the conversation if needed.
