### ISSUE TITLE
Microsoft.ApplicationInsights.AspNetCore store missing

### ISSUE THREAD

**Issue by petertsu** [dotnet/dotnet-docker#604]
Pull latest microsoft/dotnet . Try to start asp.net core app .
Error:
  An assembly specified in the application dependencies manifest (My.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

The application working as expected on previous images

**Comment by MichaelSimons** [comment]
@petertsu - Can you give concrete steps that can be used to reproduce this issue?  There are not enough details to provide you much guidance/help.

**Comment by petertsu** [comment]
@MichaelSimons    There is no issue with docker . My bad .  I close the issue

**Comment by ateregulov** [comment]
I have same problem.

**Comment by MichaelSimons** [comment]
@ateregulov, Can you give concrete steps that can be used to reproduce this issue?
