### ISSUE TITLE
can't compile F# projects on microsoft/dotnet:2.1-sdk-alpine (bash dependency)

### ISSUE THREAD

**Issue by ctaggart** [dotnet/dotnet-docker#605]
I'm opening an issue here in case the fix for https://github.com/dotnet/cli/issues/9538 is to simply add `bash` to the dotnet:2.1-sdk-alpine which seams like the easiest fix.

**Comment by MichaelSimons** [comment]
Closing as we do not want to add `bash` to the alpine image.  The underlying product issue will need to be fixed for the best out of box experience.

**Comment by ctaggart** [comment]
@MichaelSimons, do you have a link to the product issue to be fixed? Did you agree with the product team that they would fix it?
