### ISSUE TITLE
Docker pull for runtime:9.0.0

### ISSUE THREAD

**Issue by varndellwagglebee** [dotnet/dotnet-docker#6069]
### Describe the bug

Pulling the .Net Runtime 9.0 gives this error message:

docker pull mcr.microsoft.com/dotnet/runtime:9.0.0
Error response from daemon: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://mcr.microsoft.com/v2/dotnet/runtime/manifests/sha256:1e5eb0ed94ca96a34a914456db80e48bd1bb7bc3e3c8eda5e2c3d89c153c3081": EOF

### Which .NET image(s) are you using?

mcr.microsoft.com/dotnet/runtime:9.0.0

### Steps to reproduce

Run the following command: docker pull mcr.microsoft.com/dotnet/runtime:9.0.0   

### Output of `docker version`

```console

```

### Output of `docker info`

```console

```

**Comment by mthalman** [comment]
Hi @varndellwagglebee. It looks like this behavior is from the registry, not the container image. For registry issues, please go to https://github.com/microsoft/containerregistry/issues.
