### ISSUE TITLE
Debug Net Framework 4.7.1 class libraries using Docker for Windows and Linux containers

### ISSUE THREAD

**Issue by oscarllopmediolanum** [dotnet/dotnet-docker#607]
## Steps to reproduce the issue
1. Create an ASP.NET Core web application project with support for Docker using Linux containers
2. Create a C# class library in  the .NET Framework 4.7.1 with a static test method, for example:

```
using System;

namespace ClassLibrary1
{
     public class Class1
     {
         public static void Test ()
         {
             string b = "b";
         }
     }
}
```

3. Include a breakpoint in the instruction `string b = "b"`
4. Include a reference to this library in the web application
5. Replace in ValuesController.cs

```
[HttpGet]
public ActionResult <IEnumerable <string >> Get ()
{
     return new string [] {"value1", "value2"};
}
```

```
[HttpGet]
public ActionResult <IEnumerable <string >> Get ()
{
     ClassLibrary1.Class1.Test ();
     return new string [] {"value1", "value2"};
}
```

5. Debug the web application

## Expected behavior
The execution stops at the breakpoint

## Actual behavior
The execution doesn't stops at the breakpoint

## Additional information (e.g. issue happens only occasionally)
The Issue always happens 
Using microsoft/dotnet:2.1-aspnetcore-runtime container

**Comment by MichaelSimons** [comment]
All issues related to VS Docker tooling should get logged at https://github.com/Microsoft/DockerTools.

Copied this issue to https://github.com/Microsoft/DockerTools/issues/127.
