### ISSUE TITLE
Missing images for mcr.microsoft.com/dotnet/nightly/sdk:9.0.101

### ISSUE THREAD

**Issue by austindrenski** [dotnet/dotnet-docker#6091]
Hi folks, looks like the nightly sdk images didn't ship with the rest of yesterday's images. 

Could someone please take a look and ping back with an ETA?

```
ERROR: mcr.microsoft.com/dotnet/nightly/sdk:9.0.101-alpine3.20-aot: not found
```

- https://mcr.microsoft.com/artifact/mar/dotnet/nightly/sdk/tags

**Comment by lbussell** [comment]
Yes, I'll take a look at this now. Thanks.

**Comment by austindrenski** [comment]
Thanks @lbussell, appreciate the quick response!

> Are you using nightly images solely for the AOT images or for some other reason? Just curious.

@richlander just for building AOT images. It'll be a great day when the AOT tag variants are available for the non-nightly images 🙂

**Comment by richlander** [comment]
I'd love to hear more about what you are doing. If you are interested in chatting, please reach out at `dotnet@microsoft.com`.
