### ISSUE TITLE
Dockerfile in this document is incorrect

### ISSUE THREAD

**Issue by DavidPrio** [dotnet/dotnet-docker#610]
@hihigash commented on [Thu Jun 28 2018](https://github.com/dotnet/docs.ja-jp/issues/120)

`dotnet run` command builds `dotnet.dll`.
However, `Hello.dll` is specified for ENTRYPOINT of Dockerfile.

The correct Dockerfile is as follows.

```Dockerfile
FROM microsoft/dotnet:2.0-sdk
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/dotnet.dll"]
```

Thanks,
hihigash

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [.NET Core での Docker の基礎の学習](https://docs.microsoft.com/ja-jp/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/core/docker/docker-basics-dotnet-core.md)
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

---

@hihigash commented on [Thu Jun 28 2018](https://github.com/dotnet/docs.ja-jp/issues/120#issuecomment-400929744)

Update.
This problem also exists in the docs (en-us).

---

@DavidPrio commented on [Fri Jun 29 2018](https://github.com/dotnet/docs.ja-jp/issues/120#issuecomment-401419387)

Hello, @hihigash ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by MichaelSimons** [comment]
@DavidPrio - why did you move this issue here?  The issue is with the documentation that resides in https://github.com/dotnet/docs*.  This repo is specific to the `microsoft/dotnet` docker images.

**Comment by DavidPrio** [comment]
@MichaelSimons Sorry, I was not able to find the right repo using ZenHub, I now replicated it manually. Thanks!
