### ISSUE TITLE
Unable to host ASP.NET core 2.1 https web application n docker

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/dotnet-docker#630]
Hi,
I have done all the steps to host a sample application in ASP.NET core 2.1 with https

 in docker as stated in the tutorial. Same code  at [SampleDockerMVC.zip](https://github.com/dotnet/dotnet-docker/files/2189188/SampleDockerMVC.zip)
1 Drive link for source
https://1drv.ms/u/s!AoG_S7xXx9nDhM0XPbB2BwIGlUrGgw
## Steps to reproduce the issue
1. Unzip the attached code
2. Ensure docker is started
3. Run the attached code.

## Expected behavior
The code should be deployed in docker and kestrel should start

## Actual behavior
Getting an error
```
sampledockermvc_1  | crit: Microsoft.AspNetCore.Server.Kestrel[0]
sampledockermvc_1  |       Unable to start Kestrel.
sampledockermvc_1  | System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
sampledockermvc_1  | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
sampledockermvc_1  | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
sampledockermvc_1  |
sampledockermvc_1  | Unhandled Exception: System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
sampledockermvc_1  | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
sampledockermvc_1  | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
sampledockermvc_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
sampledockermvc_1  |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
sampledockermvc_1  |    at SampleDockerMVC.Program.Main(String[] args) in /src/SampleDockerMVC/Program.cs:line 18
sampledockermvc_sampledockermvc_1 exited with code 139
```
## Additional information (e.g. issue happens only occasionally)
Version of docker :18.03.1-ce
.NEt core 2.1

## Output of `docker version`

Docker version 18.03.1-ce, build 9ee9f40
(paste your output here)

## Output of `docker info`

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 92
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.442GiB
Name: linuxkit-00155d3cc31d
ID: 4XDN:IGE3:HLEP:6EPJ:QSBY:FVQU:CG4E:KGL6:76OX:HGJO:BSZI:HFFY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 36
 System Time: 2018-07-12T14:40:28.5966099Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by disophisis** [comment]
I'm seeing this as well while using the steps [listed in the aspnetcore-docker-https-development.md](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https-development.md)

I have gotten https with local docker to work using the steps [listed in the aspnetcore-docker-https.md](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md)

The first URL refers to a sample project that I've downloaded and attempted to get working using the steps provided (**Windows using Linux containers**) but even the sample project throws the "No server certificate was specified" error.

**Comment by disophisis** [comment]
I'm having the same issue when I attempt to use [the steps outlined in aspnetcore-docker-https-development.](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https-development.md)

**Comment by VenkateshSrini** [comment]
@disophisis ,
I have tried adding the
 `ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword" ASPNETCORE_Kestrel__Certificates__Default__Path=/https/SampleDockerMVC.pfx`
to docker-compose override. But that also did not solve. I thought the "__" could be problem and replaced it with "_". That also did not work. The code with all these are present in below URL
https://1drv.ms/u/s!AoG_S7xXx9nDhM0XPbB2BwIGlUrGgw

Is there any way we get the attention of Microsoft on this ?


Thanks & regards

**Comment by VenkateshSrini** [comment]
Hi,
Any updates on this issue?

**Comment by natemcmaster** [comment]
I'm not very familiar with [the tutorial in question](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https-development.md), but I scanned it quickly and saw this note

> Note: The certificate name, in this case aspnetapp.pfx must match the project assembly name.

Your project assembly name is SampleDockerMVC, so try updating the export to SampleDockerMVC.pfx, not aspnetapp.pfx.

**Comment by VenkateshSrini** [comment]
The issue I was facing was with setting environment variables the same is provided here
https://github.com/aspnet/KestrelHttpServer/issues/2725

**Comment by VenkateshSrini** [comment]
@natemcmaster,
We need to mount the cert path to the docker. How to do the same with docker-compose file?
How will we send in the password using the docker-compose file?

**Comment by VenkateshSrini** [comment]
Hey,
I was able to get the same working. Please see the code at [HTTPS certificate in prod mode](https://1drv.ms/u/s!AoG_S7xXx9nDhNITjOTbIKONyO006Q)

There are two yaml file one with .Dev extension and the other .Prod.yml extension. The Deploy.CMD has the commands updated.

**Comment by MichaelSimons** [comment]
@VenkateshSrini - it seems like you were able to resolve this issues.  Closing - feel free to continue the conversation.

**Comment by chrisckc** [comment]
I resolved as per my comments here:
https://github.com/aspnet/Docs/issues/6199
It looks like some improvements can be made though

**Comment by happyesthete** [comment]
This worked for me:
https://github.com/aspnet/AspNetCore.Docs/issues/6199#issuecomment-489397675
