### ISSUE TITLE
Interactive command prompt inside container

### ISSUE THREAD

**Issue by pcgeek86** [dotnet/dotnet-docker#64]
I can't get an interactive command prompt. I tried doing this:

```
docker run --rm app:1 cmd
```

This just exited right away.

```
docker run --rm app:1 powershell
```

This one just hung, until I terminated it with CTLR + C.

Any ideas?

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by naamunds** [comment]
@pcgeek86 Try adding "-it" to your "docker run" command: `docker run -it --rm app:1 cmd`.  See the "Foreground" section of https://docs.docker.com/v1.11/engine/reference/run/ for more info.

By the way, you might not need to (or want to) specify a command ("cmd" or "powershell" in your examples). Dockerfiles will often include a CMD or ENTRYPOINT, and in that case, specifying it on the command line when doing "docker run" either overrides the CMD or is appended as arguments to the ENTRYPOINT.  For example, the README of this repo has the example command `docker run -it --rm --name my-running-app my-dotnet-app`.

**Comment by MichaelSimons** [comment]
@pcgeek86, Did you try out the suggestion @naamunds provided?  If the suggestion resolved your issue feel free to close this issue.  If not let us know so that we can try to provide additional help.

-Thanks

**Comment by pcgeek86** [comment]
@MichaelSimons @naamunds Sorry, I'll give this a shot soon. Been super busy lately. Thanks for the help!! I'll close and re-open if I can't get it working.
