### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.

### ISSUE THREAD

**Issue by kwitkamp** [dotnet/dotnet-docker#640]
## Steps to reproduce the issue
1. Create image(s) by running : docker-compose build customermanagementapi
2. Create and start container by running : docker-compose up

## Expected behavior
Image created and container starting

## Actual behavior
Exception when starting the container:
System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.

## Output of `docker version`
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: true

## Output of `docker info`
Containers: 8
 Running: 3
 Paused: 0
 Stopped: 5
Images: 36
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 3.16.0-6-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2MiB
Name: LIN02
ID: MZSJ:BKT4:B5Q3:6BRZ:PAXO:3LNA:QSVQ:NSV2:BEFE:BU62:UGEP:MDRN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

Added the Dockerfile and compose file.
[docker-compose.zip](https://github.com/dotnet/dotnet-docker/files/2206338/docker-compose.zip)

**Comment by kwitkamp** [comment]
The above works on a Windows machine but gives the exception on a linux machine

**Comment by kwitkamp** [comment]
The source is available on: https://github.com/edwinvw/pitstop

So on my windows machine I use Linux containers, as is a requirement for using the source example. There it works.

Moving the full source to a Linux machine, it fails.

Only modification I made was taking out the sqlserver and using the one I have already available.

**Comment by MichaelSimons** [comment]
FWIW I was able to run on in my Linux environment which is Ubuntu 16.04
```
...
customermanagementapi             | Hosting environment: Production
customermanagementapi             | Content root path: /
customermanagementapi             | Now listening on: http://[::]:5100
customermanagementapi             | Application started. Press Ctrl+C to shut down.
...
```

**Comment by kwitkamp** [comment]
OK, thanks, I have now switched to Ubuntu 16.04 and it's also working.
