### ISSUE TITLE
Help: Use letsencrypt certificate

### ISSUE THREAD

**Issue by mathisloge** [dotnet/dotnet-docker#642]
Hey there,
i´m trying to get my project to run with caddy as a proxy. But i dont really know how to configure the https to use it from caddy. Is there any easy way to get the letsenrypt certificates from caddy into kestrel? 

The sample project just demonstrate it with a self signed certificate. 

The project is build with docker.

**Comment by jespersh** [comment]
Are you looking to use https between the user and caddy or caddy and kestrel?
`Kestrel <=> Caddy proxy <=> User`

If you're looking to encrypt between Kestrel and Caddy, then take a look at this doc: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x (search for https)
If you're looking to encrypt between Caddy and the User, then you'll need to take a look at Caddy's docs. I took a glance and I couldn't figure out myself if Caddy generates the certificate itself just by providing an email. The examples part of this page: https://caddyserver.com/docs/tls does seem to mention giving certificate files to a configuration file in Caddy

**Comment by mathisloge** [comment]
Thanks for your reply. 
I´ve got the connection between caddy <=> User running with https. 
But i dont really know if it is necessary to have an https connection between caddy and kestrel also. 

My project is running on a docker swarm in its own network and connected to the caddy network. 

I will look into the link you provided.

**Comment by jespersh** [comment]
That depends entirely on how much you trust your internal network. It reminded me of this: https://security.stackexchange.com/questions/188208/do-i-need-to-encrypt-connections-inside-a-corporate-network

**Comment by mathisloge** [comment]
thanks for that link!

i will try to figure it out how to encrypt everything. I will update this thread if i have  a solution. 
Until then i will close this.

**Comment by ZackTech** [comment]
I have seen this blog : https://westerndevs.com/Tools/Lets-Encrypt-ASPNET-Core/
My application is running on Ubuntu and I want to use to certbot, however as part of the challenge it wants to write a file to http://{mydomainname}.com/.well-known/acme-challenge how can I facilitate that in my asp.net core application?
