### ISSUE TITLE
No docker content trust

### ISSUE THREAD

**Issue by noelmcgrath** [dotnet/dotnet-docker#645]
## Steps to reproduce the issue
1. export DOCKER_CONTENT_TRUST=1
2. docker pull microsoft/dotnet:2.1-aspnetcore-runtime

## Expected behavior
Image would be downloaded

## Actual behavior
Error: remote trust data does not exist for docker.io/microsoft/dotnet: notary.docker.io does not have trust data for docker.io/microsoft/dotnet

## Additional information (e.g. issue happens only occasionally)
Docker content trust is used toverify that the image is exaclty what the publisher created and is a docker security best practise
Is there a reason why these images dont use this?

**Comment by MichaelSimons** [comment]
Internal issue tracking MCR support - https://github.com/microsoft/mcr/issues/707.

**Comment by lbussell** [comment]
We plan to provide signed images via https://github.com/dotnet/dotnet-docker/issues/4589 using the `notary` tool. As this tool doesn't support `DOCKER_CONTENT_TRUST`, we have no plans to support it.
