### ISSUE TITLE
Bitnami Minideb, minimal image

### ISSUE THREAD

**Issue by wahmedswl** [dotnet/dotnet-docker#646]
Hi,
    It would be great to test bitnami minideb as alternative base image https://github.com/bitnami/minideb, their are official minideb based images available from bitnami but still still not any for dotnet. Current sdk image un-compress is sized at 1+Gb, is alpine based images ready for production workloads as minideb promise lighter but wast compatibility

Thanks

**Comment by MichaelSimons** [comment]
microsoft/dotnet already offers Linux alpine images in addition to stretch-slim, and bionic.  The distros we add are driven by demand.  We will reconsider in response to demand.
