### ISSUE TITLE
Document packages required for using non-mainline apis

### ISSUE THREAD

**Issue by jugglingthebits** [dotnet/dotnet-docker#649]
## Steps to reproduce the issue
1. Create a C# project
2. Reference [Aspose.Slides.NET](https://www.nuget.org/packages/Aspose.Slides.NET/)
3. Create method that opens some PowerPoint presentation using `new Apose.Slides.Presentation(..)`
3. Create a Docker image for this project based on `microsoft/dotnet:2.1-sdk`
4. Execute `dotnet run` in Docker container

## Expected behavior
The Aspose.Slides library is loaded.

## Actual behavior
`dotnet run` crashes with `System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.` (see #618 for details)

## Additional information (e.g. issue happens only occasionally)
There is no documentation on https://hub.docker.com/r/microsoft/dotnet/ that mentions anything about non-mainline apis not being supported within the Docker images out of the box.
It would be helpful if there was documentation linked from that page where non-mainline apis (namespaces?) are listed together with the packages required to enable them.

**Comment by MichaelSimons** [comment]
The appropriate documentation shouldn't be Docker specific.  You encounter the same issue when using the deb packages to install the product.  This is a general .NET Core problem.  What are the native dependencies the product has?  More specifically what are the native dependencies broken down by area.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/docs #7207](https://github.com/dotnet/docs/issues/7207) via [**ZenHub**](https://www.zenhub.com/)
