### ISSUE TITLE
Get error when building edge module image for arm32v7.

### ISSUE THREAD

**Issue by luyaok** [dotnet/dotnet-docker#650]
## Steps to reproduce the issue
Used the Visual Studio Code at Ubuntu 16.04, run command "Azure IoT Edge: Build IoT Edge Module Image" --> select the arm32v7 platform. Get the following error:

standard init linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c useradd -ms /bin/bash moduleuser'  returned a non-zero code: 1

But for the amd64 platform is OK.

## Additional information (e.g. issue happens only occasionally)
.NET Core SDK
version: 2.1.302

Runtime Environment:
OS Name: debian
OS Version: 9
OS Platform: Linux
RID: debian.9-x64

## Output of `docker version`

```
Version: 18.06.0-ce
API version: 1.38
OS/Arch: linux/amd64
```

Is it expected behavior?

**Comment by MichaelSimons** [comment]
@luyaok - can you share what your Dockerfile looks like and what the complete build output is?  Have you tried building it on ARM hardware?

**Comment by luyaok** [comment]
@MichaelSimons My Dockerfile.arm32v7:

```
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleModule.dll"]
```
And the complete build output is:

```
sudo docker build  --rm -f "/home/rita/Desktop/samplemodule/EdgeSolution/modules/SampleModule/Dockerfile.arm32v7" -t ritacontainer.azurecr.io/samplemodule:0.0.1-arm32v7 "/home/rita/Desktop/samplemodule/EdgeSolution/modules/SampleModule"
[sudo] password for rita:
Sending build context to Docker daemon  500.7kB
Step 1/12 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> 9e243db15f91
Step 2/12 : WORKDIR /app
 ---> Using cache
 ---> 270308131379
Step 3/12 : COPY *.csproj ./
 ---> Using cache
 ---> 8b43de3e6659
Step 4/12 : RUN dotnet restore
 ---> Using cache
 ---> e7364aaf79d9
Step 5/12 : COPY . ./
 ---> Using cache
 ---> 74252ddb1dfa
Step 6/12 : RUN dotnet publish -c Release -o out
 ---> Using cache
 ---> 5c43d3712e9a
Step 7/12 : FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
 ---> 879f82697af8
Step 8/12 : WORKDIR /app
 ---> Using cache
 ---> e276344385e7
Step 9/12 : COPY --from=build-env /app/out ./
 ---> Using cache
 ---> b851e17ceee0
Step 10/12 : RUN useradd -ms /bin/bash moduleuser
 ---> Running in 7095f8416e8b
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c useradd -ms /bin/bash moduleuser' returned a non-zero code: 1
rita@rita-Virtual-Machine:~/Desktop/samplemodule$ 
```

**Comment by MichaelSimons** [comment]
I am not sure what you are trying is supported.  Building ARM images on a linux AMD64 host is not supported (at least by default).  If you search around you will see people have solutions involving QEMU.  The alternative I prefer is to setup physical ARM hardware (e.g. an inexpensive Raspberry PI) and use a remote Docker client on my AMD64 machine to communicate with the ARM Docker daemon.

**Comment by luyaok** [comment]
@MichaelSimons Thanks for the response. I'll change to Windows 10 to build the ARM image.
