### ISSUE TITLE
Request routing to ASPNETCORE (2.1) application does not work.

### ISSUE THREAD

**Issue by ddobric** [dotnet/dotnet-docker#663]
## Steps to reproduce the issue
I have created a simple aspnet core 2.1 application and built a Linux container. Here is the docker-file:

```
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app
COPY ./ ./
RUN dotnet restore XYZ/myproject.csproj
WORKDIR /app
RUN dotnet publish XYZ/myproject.csproj  -c Release -o ../out
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "./myapp.dll"]
```

Request routing to application does not work.

## Expected behavior
When application is started, it should observer http/s requests.
Start with :
`docker run --rm -p 5433:5433 asp:1 --urls http://localhost:5443`

Application should be reachable from browser.

## Actual behavior
docker host does not route requests to application.

I tried following:
```
docker run --rm -p 5433:5433 asp:1 --urls http://localhost:5443
docker run --rm -p 5433:5433 asp:1 --urls http://*:5443
docker run --rm -p 5433:5433 asp:1 --urls http://172.20.0.2:5443 (172.20.0.2 is container's IP)
```
Navigating to application within browser does not work.
```
http://172.20.0.2:5443 (does not work) 
http://localhost:5443 (does not work)
```

## Additional information 
To workaround the problem I added following route:
`route /P add 172.0.0.0 MASK 255.0.0.0 10.0.75.2`
After that requests are routed correctly to the app. 

**Questions**:
Why is adding of this route required? When this route is added, docker host consumes 20% of CPU even if no any container is running. Additionally, RAM consumption increases up to 10 GB.

Another intersting information might be, that I tried mosquito MQTT server in docker (just another app with listener). Interestingly listening on that container works well, without adding of any additional route to the route table. 

## Output of docker version

```
Docker version 18.06.0-ce, build 0ffa825(paste your output here)
```

## Output of `docker info`

```
Containers: 286
 Running: 1
 Paused: 0
 Stopped: 285
Images: 64
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d003f03
ID: NIFQ:ST3V:O3CF:SECH:ZA3Z:FCHZ:EE2B:HDAZ:OXE6:4OFG:Z2BX:4VKS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 60
 System Time: 2018-08-20T08:01:14.7742255Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ddobric** [comment]
Sure. I started it with --urls ..
As mentioned, it works only when adding additional route to t route table.

**Comment by MichaelSimons** [comment]
I think you want to use `+` instead of localhost as in `--urls http://+:5443`.  You can try this with the ASP.NET Core sample.

```
docker run -it --rm -p 8000:5432 microsoft/dotnet-samples:aspnetapp --urls http
://+:5432
```

**Comment by MichaelSimons** [comment]
Closing - if the provided answer is not sufficient, feel free to respond and reopen.
