### ISSUE TITLE
Please add runtime tags for Windows 10 LTSB (long term servicing branch i.e. 1607)

### ISSUE THREAD

**Issue by damianpowell** [dotnet/dotnet-docker#669]
You have tags for most of the current versions of windows:
- 2.1-aspnetcore-runtime-nanoserver-1803
- 2.1-aspnetcore-runtime-nanoserver-1709
- 2.1-aspnetcore-runtime-nanoserver-sac2016

You support the `Semi-Annual Channel` but the `Long-Term Servicing Branch` is conspicuously missing. Currently I am building my own image for this based on `microsoft/nanoserver:10.0.14393.2248` but I would much rather use an officially sanctioned image. While I understand that the LTSB version is rare, it is still a current version of Windows and .NET Core officially supports it according to the [.NET Core Prerequisites](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x) page. Could you start maintaining an official tag, please?

**Comment by MichaelSimons** [comment]
Can you clarify what tag you are asking for?  The title suggests `Windows 10 LTSB`.  I am not sure what you mean by this.  The description leads me to believe you are looking for a nanoserver ltsb tag.

It is my understanding that Nano Server hasn't released an LTSB version yet.  The three active releases they provide images for are SAC releases.

**Comment by fsudaman** [comment]
We have this same requirement. We are currently running into problem with ACI as well as it only support LTSC image. From what I found, it appears that there is now LTSC tags for nanoserver https://hub.docker.com/r/microsoft/nanoserver/

More details on the issue we experience (source: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#image-version-not-supported)
-----
"Azure Container Instances supports Windows images based only on Long-Term Servicing Channel (LTSC) versions. To mitigate this issue when deploying Windows containers, always deploy LTSC-based images."

**Comment by MichaelSimons** [comment]
@fsudaman - I think the nanoserver LTSC tag is misdocumented - it doesn't seem to exist.  I've reported this to the owners of `microsoft/dotnet`.

**Comment by MichaelSimons** [comment]
To summarize, there are two issue at hand.

1. The [NanoServer Docker Hub page](https://hub.docker.com/r/microsoft/nanoserver/) mentions a ltsc2016 tag in the readme, but it doesn’t exist.  This is a documentation error.  The 2016 nanoserver release was a sac release.  The floating tag for this release is sac2016.
2. The ACI guidance is misleading as it related to nanoserver which hasn't had an ltsc release.  In this case ACI supports images based on microsoft/nanoserver:sac2016.  If you want to deploy a .NET Core app to ACI then you should base it on the appropriate microsoft/dotnet:***-nanoserver-sac2016 tag.

I have followed up with the appropriate teams within Microsoft about these issues.  microsoft/dotnet will not be adding an ltsc2016 tag as there isn't one for nanoserver.  Closing as there aren't any changes for microsoft/dotnet.
