### ISSUE TITLE
COPY failed: no source files were specified

### ISSUE THREAD

**Issue by chandra00** [dotnet/dotnet-docker#674]
Hi i am new to Docker and i tried the sample from docker docs .net core application.I have downloaded the zip file and extracted it.I am using git bash with ec2.While building the docker file i got an error like

Step 3/10 : COPY *.csproj ./
COPY failed: no source files were specified

How to resolve this?

**Comment by MichaelSimons** [comment]
@chandra00 - Could you please provide some more details?  It would be most helpful if you would include concrete steps that can be used to reproduce the issue.  Include what sample you are trying to build and what Docker cmds you are executing.  Thanks

**Comment by MichaelSimons** [comment]
Closing due to no response.  @chandra00, if this is still an issue please add the details requested and reopen.
