### ISSUE TITLE
Why explicitly restore

### ISSUE THREAD

**Issue by niesmo** [dotnet/dotnet-docker#694]
Quick question.

Looking at the dockerfiles that you guys have in this repo, I see a pattern where you first copy the `.csproj` for the project and then simply restore the packages for that project (before copying the rest of the project files). Then in another step, you copy the code and publish the `dll`.
![image](https://user-images.githubusercontent.com/5835438/45110402-23062b00-b110-11e8-826e-fd33e92f0b3a.png)
[dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile#L5)

Is there an advantage to doing it this way?

**Comment by MichaelSimons** [comment]
Closing issue but feel free to continue the discussion.

**Comment by niesmo** [comment]
@MichaelSimons that makes a lot of sense. Thanks
