### ISSUE TITLE
2.1.3-aspnetcore-runtime-nanoserver-1803 filesystem layer verification failed

### ISSUE THREAD

**Issue by tempworks-paul** [dotnet/dotnet-docker#698]
## Steps to reproduce the issue
1. docker pull microsoft/dotnet:2.1.3-aspnetcore-runtime-nanoserver-1803

## Expected behavior

Successfully docker pull microsoft/dotnet:2.1.3-aspnetcore-runtime-nanoserver-1803

## Actual behavior

2.1.3-aspnetcore-runtime-nanoserver-1803: Pulling from microsoft/dotnet
e46172273a4e: Already exists
1f7d468f830c: Verifying Checksum
26274f5498c6: Download complete
568d7822a573: Download complete
b67610628156: Download complete
42931f28c1f8: Download complete
dccd10e20a87: Download complete
filesystem layer verification failed for digest sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30

## Additional information (e.g. issue happens only occasionally)

Able to reproduce on two different operating systems and Docker versions:
Windows Server 1709 -- 17.06.2-ee-5
Windows 10 1803 -- 18.06.1-ce

## Output of `docker version`

```
Client:
 Version:      17.06.2-ee-5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:51:36 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-5
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:54:07 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

## Output of `docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 17.06.2-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 16299 (16299.431.amd64fre.rs3_release_svc_escrow.180502-1908)
Operating System: Windows Server Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8GiB
Name: TWSV16VSTS-B1
ID: 2QRQ:WQC6:4LVJ:66CN:IPWN:XYCN:IIMY:AJEV:C3ZL:TVMW:7WJR:2HH6
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
This looks like an issue with Docker versus the image itself.  @tempworks-paul can you report this to Docker?

**Comment by MichaelSimons** [comment]
We have many people using this image.  I re-verified yesterday that I can pull this image both on Windows 10 and Windows Server.

**Comment by tempworks-paul** [comment]
Well, I can't replicate today on the same machines there were having a problem yesterday. Chocking it up to network gremlins.  Thanks Machael.
