### ISSUE TITLE
SECURITY: Alpine 3.8.1-based images need to be fast tracked

### ISSUE THREAD

**Issue by DrEsteban** [dotnet/dotnet-docker#709]
https://www.theregister.co.uk/2018/09/15/alpine_linux_bug/

https://alpinelinux.org/posts/Alpine-3.8.1-released.html

**Comment by smarts** [comment]
I heard this affects alpine 3.2-3.8, so any images based on that alpine version range should be rebuilt

**Comment by MichaelSimons** [comment]
@DrEsteban - Thanks for bringing this to our attention.  The microsoft/dotnet alpine images were rebuilt subsequent to the patch.
