### ISSUE TITLE
Get https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.1-sdk: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by ronbok** [dotnet/dotnet-docker#722]
## Steps to reproduce the issue
1. docker build -t aspnetapp .
2.
3.

## Expected behavior
Container should have built...

## Actual behavior
unauthorized: incorrect username or password

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
Curious if you try executing `docker logout` and then `docker pull microsoft/dotnet:2.1-sdk` what will happen.

**Comment by ronbok** [comment]
That was it...seems like you need to incognito mode when pulling public if logged in.  Thanks!
