### ISSUE TITLE
Reset to actual User in Dockerfiles after setting PATH

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/dotnet-docker#728]
## Steps to reproduce the issue
1. docker run -it microosft/dotnet:2.0-runtime cmd
2. Microsoft Windows [Version 10.0.17134.285]
   (c) 2018 Microsoft Corporation. All rights reserved.

   C:\>echo %USERDOMAIN%\%USERNAME% 
   User Manager\ContainerUser
   C:\>
3. I don't know how to start a container (command : docker run) with `ContainerAdministrator`, but i suspect, it will give `ContainerUser` in above command because we set it inside the [dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/nanoserver-1809/amd64/Dockerfile#L30)

I found the issue this after we changed our Dockerfile's base image from `2.1.5-runtime-nanoserver-sac2016` to `2.1.5-runtime-nanoserver-1809`. `2.1.5-runtime-nanoserver-sac2016` does not have `User ContainerUser` line whereas `2.1.5-runtime-nanoserver-1809` has it. We start container image in admin mode.

## Expected behavior
We should keep the same `User` in which actual docker container is started.

## Actual behavior
We switch to `ContainerUser` in images greater than `*-nanoserver-1709`.

## Additional information (e.g. issue happens only occasionally)
Issue happens always.

## Output of `docker version`

```

C:\>docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     false

C:\>
```

## Output of `docker info`

```
C:\Users\asnegi>docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 18.06.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Enterprise Version 1803 (OS Build 17134.286)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.704GiB
Name: asnegi-tmp
ID: OZ3W:YBD5:NEIN:MCDB:AE6G:MTD3:G5PW:MTX2:JKMF:6WDL:FZSO:U2XZ
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2018-10-07T21:08:58.5660673+05:30
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
This is a change in behavior within the Windows OS images (e.g. microsoft/nanoserver).  In `microsoft/nanoserver:sac2016`, the default user is ContainerAdministrator.  In `microsoft/nanoserver:1709` and newer the default user is ContainerUser.  If you want to run as ContainerAdministrator you can change the user with the `USER` instruction within a Dockerfile or you can use the `-u, --user` command line option with `docker run` e.g. `docker run --rm -u ContainerUser microsoft/nanoserver:1709 cmd /C echo %USERNAME%`.

Closing as this is not specific to the .NET images.  Feel free however to continue the discussion.

**Comment by ashishnegi** [comment]
Thanks for the command.
i tried with:
```
>docker run -it --rm -u ContainerAdministrator microsoft/windowsservercore:1709 cmd /C whoami
user manager\containeradministrator
>docker run -it --rm -u ContainerUser microsoft/windowsservercore:1709 cmd /C whoami
user manager\containeruser
```
Good enough.

I then tried with `dotnet`.
However, it uses nanoserver which does not have `whoami` command. I tried with `%username%`.

Why these 2 commands show different result ?

```
E:\service-fabric-mesh-preview\samples\src\azurefiles-volume>docker run -it --rm -u ContainerAdministrator microsoft/dotnet:2.2-runtime cmd /C echo %username%
asnegi

E:\service-fabric-mesh-preview\samples\src\azurefiles-volume>docker run -it --rm -u ContainerAdministrator microsoft/dotnet:2.2-runtime cmd
Microsoft Windows [Version 10.0.17763.1]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>echo %username%
ContainerAdministrator

C:\>
```

**Comment by MichaelSimons** [comment]
Sorry I about that, I was using PowerShell.  If you are executing with `cmd` you will need to escape the `%`.  Try using `^%username^%` instead.

**Comment by MichaelSimons** [comment]
The reason you were seeing different results is that the variable `%username%` was getting evaluated on the Docker host machine before the docker run was being executed.  In essence you were executing `docker run -it --rm -u ContainerAdministrator microsoft/dotnet:2.2-runtime cmd /C echo asnegi`.  By escaping the variable reference correctly, the container is what evaluates the variable reference.

**Comment by ashishnegi** [comment]
Thanks @MichaelSimons You are correct. Verified :
```
>docker run -it --rm -u ContainerAdministrator microsoft/dotnet:2.2-runtime cmd /C echo ^%username^%
ContainerAdministrator

>docker run -it --rm -u ContainerUser microsoft/dotnet:2.2-runtime cmd /C echo ^%username^%
ContainerUser
```

Can you help me understand why does not having a line `USER ContainerUser` in dotnet's Dockerfile is not effecting the first command above ? Does passing `-u ContainerAdministrator` in `docker run` affect only the last line ? or may be I am totally wrong. Please give more details.

**Comment by MichaelSimons** [comment]
@ashishnegi - I'm not sure I understand your question.  Specifying a user when running e.g. `docker run -u ContainerAdministrator` will override any user specified with the `USER` instruction within an image/Dockerfile.

**Comment by ashishnegi** [comment]
@MichaelSimons Thanks I understand it now.
