### ISSUE TITLE
Host images on mcr.microsoft.com

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#745]
Steve Lasker wrote a blog back in May titled [Microsoft syndicates container catalog ](https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/), describing how Microsoft will start serving container images from mcr.microsoft.com, the Microsoft Container Registry (MCR), and syndicating the content describing the container images with Docker Hub and Red Hat.

When this transition is done, the images on Docker Hub will remain and serviced as to not cause any disruption to existing users.  All existing images will be copied to MCR and new tags will only be added to MCR.

The following is a working proposal of the repo hierarchy for the entire .NET family.

- [ ] mcr.microsoft.com/dotnet (dotnet landing repo - no images)
- [ ] mcr.microsoft.com/dotnet/framework (full FX landing repo – no images)
- [ ] mcr.microsoft.com/dotnet/framework/runtime
- [ ] mcr.microsoft.com/dotnet/framework/sdk
- [ ] mcr.microsoft.com/dotnet/framework/aspnet
- [ ] mcr.microsoft.com/dotnet/framework/wcf
- [ ] mcr.microsoft.com/dotnet/framework/samples
- [x] mcr.microsoft.com/dotnet/core (core landing repo – no images)
- [x] mcr.microsoft.com/dotnet/core/runtime
- [x] mcr.microsoft.com/dotnet/core/runtime-deps
- [x] mcr.microsoft.com/dotnet/core/aspnet
- [x] mcr.microsoft.com/dotnet/core/sdk
- [x] mcr.microsoft.com/dotnet/core/samples
- [x] mcr.microsoft.com/dotnet/core-nightly (core nightly landing repo – no images)
- [x] mcr.microsoft.com/dotnet/core-nightly/runtime
- [x] mcr.microsoft.com/dotnet/core-nightly/runtime-deps
- [x] mcr.microsoft.com/dotnet/core-nightly/aspnet
- [x] mcr.microsoft.com/dotnet/core-nightly/sdk

**Comment by frankfuu** [comment]
Any plans for these images to be cached on [Azure Pipeline's hosted service](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml)?

**Comment by kkbruce** [comment]
Hi @MichaelSimons 

Have any about release date plans?

**Comment by MichaelSimons** [comment]
I am going to start to work on this.  mcr.microsoft.com/dotnet/core-nightly will be the first repo moved as it is a good repo to flush the issues out with.  After that the others shouldn't be much work.  There is no definitive date on when the work will be complete.

**Comment by MichaelSimons** [comment]
This work is complete.  Moving the Full FX images to MCR is being tracked under https://github.com/Microsoft/dotnet-framework-docker/issues/223
