### ISSUE TITLE
microsoft/dotnet:2.1-runtime-stretch-slim image is different to dotnet:2.1.5-runtime-stretch-slim

### ISSUE THREAD

**Issue by rothwewi** [dotnet/dotnet-docker#754]
## Steps to reproduce the issue
1. Pull the image microsoft/dotnet:2.1-runtime-stretch-slim, note the hash
2. Pull the image microsoft/dotnet:2.1.5-runtime-stretch-slim, note the hash
3. The hashes are different, 

## Expected behavior
I believe they should be the same image with different tags. Note the 2.1-runtime-stretch-slim is the same as the other related tags, it appears the 2.1.5-runtime-stretch-slim is the same as the previous version.

## Actual behavior
Hashes are different

## Output of `docker version`

```
Not relevant
```

## Output of `docker info`

```
Not relevant
```

**Comment by MichaelSimons** [comment]
Closing - not reproducible as noted.
