### ISSUE TITLE
aspnetcore runtime based container gives error message as install dotnet sdk 

### ISSUE THREAD

**Issue by mstechies** [dotnet/dotnet-docker#758]
## Steps to reproduce the issue
1. Add ROUTE to enable MSI inside container in the dockerfile
2. Build docker image using dotnet:2.1-aspnetcore-runtime as base image from VSTS build definition. I am using Docker task.

## Expected behavior
Gives error as below when starting the container 
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

## Actual behavior
dotnet command should execute and start the container to listen. 

## Additional information (e.g. issue happens only occasionally)
Image built with same DockerFile worked last week. The issue surfaced from starting of this week. When the same DockerFile to build the image from a Windows Server 2016 with containers machine outside VSTS, the error does not occur.

## Output of `docker version`
Docker version 17.06.2-ee-16, build 9ef4f0a
```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
@mstechies - I'm having a hard time following the steps to reproduce the issue.  I don't understand what you mean by

> Add ROUTE to enable MSI inside container in the dockerfile

It would be helpful if you could share your Dockerfile and include details about what platform you are building on (e.g. include the output from docker version and docker info).  Providing concrete steps that can be used to reproduce the issue is the best way to resolve the issue quickly.  - Thanks

**Comment by mstechies** [comment]
I have attached the DockerFile. 
[DockerFile.txt](https://github.com/dotnet/dotnet-docker/files/2487636/DockerFile.txt)

docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false

docker info

Containers: 42
 Running: 2
 Paused: 0
 Stopped: 40
Images: 27
Server Version: 17.06.2-ee-16
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2551.amd64fre.rs1_release.181004-1309)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5GiB
Name: rcbvmsint000000
ID: 4NEO:KDKU:EHV6:WCOX:ABB4:YMEA:OUYJ:2EXZ:ILXL:6YNU:ADV3:YWXW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 34
 System Time: 2018-10-17T13:40:13.5695955Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MichaelSimons** [comment]
Have you tried running the resulting image interactively overriding the `ENTRYPOINT` and then inspect the contents of the app directory to ensure the `MyApp` assemblies were correctly copied into the image?

**Comment by mstechies** [comment]
@MichaelSimons Thanks for the hint. I got this resolved. Thanks for the help.
