### ISSUE TITLE
Updated Mono version 5.10.0179-R1 no longer works on 2.1-runtime-alpine image

### ISSUE THREAD

**Issue by mc1985** [dotnet/dotnet-docker#762]
## Steps to reproduce the issue
1.apk add --no-cache mono --repositoryhttp://dl-cdn.alpinelinux.org/alpine/edge/testing
2.
3.

## Actual behavior
Error relocating /usr/bin/mono: getrandom: symbol not found

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
@mc1985 - I'm having troubles following your steps to reproduce the problem.  Do you get the indicated error when running `apk add --no-cache mono --repositoryhttp://dl-cdn.alpinelinux.org/alpine/edge/testing`?  I'm not seeing how this is a problem specific to the microsoft/dotnet:2.1-runtime-alpine image.  If this is mono specific, an issue should be opened with them.

**Comment by Hellslicer** [comment]
The error happens when you use mono.
Simple repro:
```sh
apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing mono-dev
cat > main.cs <<EOF
using System;
 
public class HelloWorld
{
    static public void Main ()
    {
        Console.WriteLine ("Hello Mono World");
    }
}

EOF
csc main.cs
mono main.exe
```
`csc` and `mono` will output:
```
Error relocating /usr/bin/mono: getrandom: symbol not found
```

**Comment by alexey-kondratov** [comment]
I have same problem. I see a solution - to expand the number of mono packages in the repositories of the alpine image.

**Comment by MichaelSimons** [comment]
This issue seems related to mono/apline and is not something specific to the microsoft/dotnet images.  By that I mean you get the same behavior with the alpine base image and mono outside of the .NET Core images.  Please follow up with mono/alpine as appropriate.

**Comment by RehanSaeed** [comment]
Did anyone figure out a workaround?
