### ISSUE TITLE
Missing 1.0.0-sdk tag

### ISSUE THREAD

**Issue by styfle** [dotnet/dotnet-docker#77]
It looks like there is no `1.0.0-sdk` tag.

```sh
$ docker run -it  microsoft/dotnet:1.0.0-sdk sh
Unable to find image 'microsoft/dotnet:1.0.0-sdk' locally
Pulling repository docker.io/microsoft/dotnet
docker: Tag 1.0.0-sdk not found in repository docker.io/microsoft/dotnet.
```

**Comment by MichaelSimons** [comment]
@styfle, Yes there is no `1.0.0-sdk` tag.  While .NET Core Runtime and Libraries are at V1.0, the tooling such as the .NET Core command line tools, Visual Studio and Visual Studio Code that enable you to work with .NET Core projects are in preview ([more](https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/)).  If you want to try out the latest sdk, please use the `1.0.0-preview2-sdk` or `latest` tags. If you want to run an already published app then consider the `1.0.0-core` or `1.0.0-core-deps` tags.

**Comment by styfle** [comment]
I see. I thought the CLI was packaged with runtime and versioned the same. For example with node.js, both the runtime ([node](https://github.com/nodejs/node)) and the libraries ([npm](https://github.com/npm/npm)) are part of the container and released at the same time even though they are technically two products with two different versions.

I was hoping to do development in a container so I could have the exact same environment in production, then possibly switch sdk to core if the size was too big in production.

**Comment by MichaelSimons** [comment]
The SDK image contains both the CLI as well as the runtime so you should be able to use it for both development and production.  It is substantially larger than just the runtime image.  The SDK image's version it associated with the CLI that is contains.

**Comment by MichaelSimons** [comment]
Closing as I believe the issue was clarified.  @styfle please reopen if you disagree.
