### ISSUE TITLE
dotnet restore fails for non-root user on 1.0.0-preview2-sdk

### ISSUE THREAD

**Issue by kalahari** [dotnet/dotnet-docker#78]
If you attempt to run `dotnet restore` (or `dotnet new`) as a non-root user, the NuGet cache population fails because `/tmp/NuGetScratch` is owned by root. Upstream bug is here: https://github.com/NuGet/Home/issues/2793.

Removing `/tmp/NuGetScratch` resolves the issue.

```
$ docker run -it --rm microsoft/dotnet:1.0.0-preview2-sdk
root@85fc27c5bede:/# useradd -d /opt/foobar -u 1000 -m -s /bin/bash foobar
root@85fc27c5bede:/# su - foobar
foobar@85fc27c5bede:~$ mkdir app
foobar@85fc27c5bede:~$ cd app
foobar@85fc27c5bede:~/app$ dotnet new

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2118 ms
Expanding 100% 8398 ms
Failed to create prime the NuGet cache. restore failed with: 1
Created new C# project in /opt/foobar/app.
```

**Comment by kalahari** [comment]
I submitted #79 to remove the `/tmp/NuGetScratch` directory.

**Comment by MichaelSimons** [comment]
Does this same issue occur with the Windows Containers based images?

**Comment by MichaelSimons** [comment]
For the repo scenario mentioned - it is unfortunate in a way that the NuGet cache is user specific.  The `microsoft/dotnet:1.0.0-preview2-sdk` Dockerfile explicitly triggered the NuGet cache to be built yet in this usage, it simply adds bloat to the image.

**Comment by MichaelSimons** [comment]
Regarding Windows Containers, it looks as the the NuGetScratch directory gets created in the under the current user's folder `c:\users\xxx\appdata\local\temp\nugetscratch` therefore this is not a problem.

**Comment by naamunds** [comment]
This was fixed by https://github.com/dotnet/dotnet-docker/pull/79.

**Comment by JimbeanZN** [comment]
This is also failing on Windows 10 (64-bit). I have removed the NuGetScratch directory but with no luck. Any other ideas on how to get this working?

**Comment by naamunds** [comment]
@JimbeanZN Sorry to hear that you're hitting this issue also.  Can you give more details about your repro environment?  Which Docker image are you using?  As what sort of user are you running `dotnet` commands when you see this issue?  Is the error output the same as that posted at the top of this issue?
