### ISSUE TITLE
503 error when trying to use microsoft/dotnet:2.1-sdk  using Docker Hub

### ISSUE THREAD

**Issue by paulohumberto42** [dotnet/dotnet-docker#780]
## Steps to reproduce the issue
I'm getting a 503 error when building my application on dockerhub, using the microsoft/dotnet:2.1-sdk.
```
# Build asp.net core
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app
COPY . ./
WORKDIR /app/src/ApplicationName
RUN dotnet publish -c Release -o /app/out /p:LinkDuringPublish=false
```

## Expected behavior
Application building

## Actual behavior
`Get https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.1-sdk: received unexpected HTTP status: 503 Service Unavailable`

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`
```
Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env


Get https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.1-sdk: received unexpected HTTP status: 503 Service Unavailable
```
```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
Docker Hub Registry is currently having "elevated error rates" - see https://status.docker.com/.  Closing as this is a Docker Hub issue.

**Comment by paulohumberto42** [comment]
The service is back to normal! I guess they fixed it.
