### ISSUE TITLE
Azure DevOps pipeline limitations when using SDK images

### ISSUE THREAD

**Issue by AArnott** [dotnet/dotnet-docker#788]
(Some of) the docker images produced here do not include the `sudo` package. While for manual use of docker images this is ok, since the docker gives the default user root access and they can install packages, when using these images to build in Azure Pipelines, the user account within the container used to execute build steps is _not_ `root`.

Azure Pipelines builds that use these images cannot possibly install any additional packages. They can't sudo to install them because sudo isn't in the image, and since Azure Pipelines runs build steps as non-root, `apt install` without `sudo` fails.

#784 demonstrates the fix for one of the images.

**Comment by MichaelSimons** [comment]
> (Some of) the docker images produced here do not include the sudo package

I'm not recalling any microsoft/dotnet images that include sudo.  Which images am I overlooking?

**Comment by AArnott** [comment]
I'm not claiming that any images *do* include `sudo`. I'm only claiming that some _don't_. I didn't do a thorough audit to determine if *all* of them don't.

**Comment by MichaelSimons** [comment]
For reference, here an Azure DevOps build pipeline that illustrates the inability to add packages.

```
resources:
  containers:
  - container: dotNetSdk_container
    image: microsoft/dotnet:2.1-sdk-stretch
jobs:
- job: TestBuild
  pool: Hosted Ubuntu 1604
  container: dotNetSdk_container
  steps:
  - script: |
      apt-get update
      apt-get install -y --no-install-recommends dpkg-dev
    displayName: Add arbitrary build pre-req
```

When this is run there is a Initialize Container step that Azure DevOps runs.  This shows how they are dynamically adding/changing the user.

```
2018-11-06T19:19:12.1790275Z ##[section]Starting: Initialize container
2018-11-06T19:19:12.2196936Z ##[command]/usr/bin/docker version --format '{{.Server.Version}}'
2018-11-06T19:19:19.1124242Z '18.06.1-ce'
2018-11-06T19:19:19.1158477Z Docker daemon version: '18.06.1-ce'
2018-11-06T19:19:19.1158760Z ##[command]/usr/bin/docker version --format '{{.Client.Version}}'
2018-11-06T19:19:19.2841555Z '18.06.1-ce'
2018-11-06T19:19:19.2861823Z Docker client version: '18.06.1-ce'
2018-11-06T19:19:19.2939439Z ##[command]/usr/bin/docker pull microsoft/dotnet:2.1-sdk-stretch
2018-11-06T19:19:19.7355159Z 2.1-sdk-stretch: Pulling from microsoft/dotnet
...
2018-11-06T19:20:29.6422482Z Digest: sha256:99651eda57a35a990e1ddd390fa878221939a4525634486e348b317cb9ced0fb
2018-11-06T19:20:29.6598079Z Status: Downloaded newer image for microsoft/dotnet:2.1-sdk-stretch
2018-11-06T19:20:29.6668005Z ##[command]/usr/bin/docker network create vsts_network_c3fa91c659ef4d6da8171236b5a211b0
2018-11-06T19:20:29.8440044Z f5354ab75dac2274f842217f817e35c015d89e260e4524c385b448b5a7444a22
2018-11-06T19:20:29.8508655Z ##[command]/usr/bin/docker create --name dotNetSdk_container_microsoftdotnet21sdkstretch --network=vsts_network_c3fa91c659ef4d6da8171236b5a211b0 -v /var/run/docker.sock:/var/run/docker.sock    -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/home/vsts/agents/2.141.1/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" microsoft/dotnet:2.1-sdk-stretch "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
2018-11-06T19:20:42.5375141Z 4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6
2018-11-06T19:20:42.5420842Z ##[command]/usr/bin/docker start 4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6
2018-11-06T19:20:44.9641497Z 4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6
2018-11-06T19:20:44.9685716Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 which bash
2018-11-06T19:20:45.1122799Z /bin/bash
2018-11-06T19:20:45.1412064Z ##[command]whoami 
2018-11-06T19:20:45.2168497Z vsts
2018-11-06T19:20:45.2168781Z ##[command]id -u vsts
2018-11-06T19:20:45.2604688Z 1001
2018-11-06T19:20:45.2604906Z Try create an user with UID '1001' inside the container.
2018-11-06T19:20:45.2640195Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
2018-11-06T19:20:45.4253335Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 useradd -m -u 1001 vsts_VSTSContainer
2018-11-06T19:20:45.9035853Z Grant user 'vsts_VSTSContainer' SUDO privilege and allow it run any command without authentication.
2018-11-06T19:20:45.9036048Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 groupadd VSTS_Container_SUDO
2018-11-06T19:20:46.2002467Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 usermod -a -G VSTS_Container_SUDO vsts_VSTSContainer
2018-11-06T19:20:46.4401795Z ##[command]/usr/bin/docker exec  4a9200670c8177403230debbdb9fe52945eb30a05d9cfb7d8d529b58ca79b5e6 su -c "echo '%VSTS_Container_SUDO ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
2018-11-06T19:20:46.6281991Z ##[section]Finishing: Initialize container
```

The `Add arbitrary build pre-req` step fails with:

```
2018-11-06T19:20:52.5462065Z Reading package lists...
2018-11-06T19:20:52.5486460Z E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
2018-11-06T19:20:52.5539210Z E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
2018-11-06T19:20:52.5539574Z E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

**Comment by MichaelSimons** [comment]
A few thoughts:
1.  The microsoft/dotnet images align with the various _Official_ Docker images.  As it related to this issue, the SDK images are based on the [buildpack-deps](https://hub.docker.com/_/buildpack-deps/) images which do not include `sudo`.  This is to say in general _Offical_ Docker images are going to have the same shortcomings when used with the Azure DevOps container functionality.
2.  Wouldn't a preferred pattern be to build up a customized Docker image with the necessary build pre-reqs included and then use this within your build versus including the overhead of building up the build environment on each build?

**Comment by AArnott** [comment]
> Wouldn't a preferred pattern be to build up a customized Docker image with the necessary build pre-reqs included?

Sure. And that's what I've done. But I have a tool that requires two more packages than are included with `microsoft/dotnet:2.1-sdk-bionic`. Asking folks who use my tool to install two more packages that are clearly trusted packages from the ubuntu package feed is reasonable. IMO, asking them to trust me and use my private docker image is not, nor is asking each of my many users to create their own custom docker images -- all because a tiny `sudo` package was omitted from the base image. 

Installing `sudo` is pretty quick, and so is installing the other two packages I need.
I can imagine `buildpack-deps` leaving `sudo` out because these images are used for a wide variety of purposes, and are intentionally minimal. They may be used for runtimes where `sudo` represents a security risk. And they are very likely *designed* to be built upon with additional layers. But I consider the `microsoft/dotnet:2.1-sdk` images to be designed to be sufficient to build our stuff, rather than just as a minimal base layer that folks are expected to have to add new docker layers to. While that's of course an option, it seems *way* overkill to require that to add a tiny little package.

And beyond installing packages, suppose I just needed to modify a config file in a protected location in the linux file system? `sudo echo "something" >> /etc/some.conf` is so easy. Why in the world should I have to create a whole new docker image for that?

Every CI system (AppVeyor, Azure Pipelines, etc.) advertises that build agents have root access to their VMs. It's considered very popular to offer this. I don't know why Pipelines runs the steps as an ordinary user by default, but as we see in the log above, these containers _are_ granted `sudo` privileges. But that's no good if `sudo` isn't present.

Even if you don't want to add `sudo` to your *runtime* images, I hope you can see the applicability of it in the *sdk* packages, yes?

**Comment by vtbassmatt** [comment]
For CI, often it's handy to be root. It seems reasonable to expect `sudo` in a CI container. The question is: are these containers supposed to be build environments or are they a base to build apps on? If they're the former, then they ought to have `sudo`. The "focused containers" my team is planning to ship will have `sudo` since they're explicitly for CI.

(I'm an Azure Pipelines PM, whether that weighs positively or negatively on your opinion of my opinion.)

**Comment by richlander** [comment]
For clarity, here are the official docs on this topic: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

**Comment by richlander** [comment]
None of the other app platforms (AFAICT) include this command. If .NET adds it, what will the story be for Java, Node, and friends?

**Comment by AArnott** [comment]
Good question, @richlander. Thanks for sharing that, BTW. FWIW, I've never had any problem using `sudo` in a CI build.

@vtbassmatt Why does Azure Pipelines go to lengths to avoid executing build steps with the `root` user? Every cloud CI system out there seems to advertise root access available to the build, and Pipelines is among them. Yet specifically when running within a Container, it blocks this. Can this be changed?

**Comment by richlander** [comment]
> I can imagine buildpack-deps leaving sudo out because these images are used for a wide variety of purposes, and are intentionally minimal

A clarification on that. I don't consider buildpack-deps minimal. They clearly left out sudo for reasons other than size.

@vtbassmatt -- can you tell us more about these focussed containers?

**Comment by MichaelSimons** [comment]
See https://github.com/docker-library/buildpack-deps/issues/84 regarding `buildpack-deps` not including `sudo`.

**Comment by vtbassmatt** [comment]
@AArnott the agent runs outside the container, executing steps inside the container. A handful of in-box tasks cooperate with agent-side plugins to accomplish their work, specifically artifact uploading and source fetching. I'm not 100% sure why the agent doesn't run as root on the host (guess: to match the recommended deployment scenario for private agents). We found that most containers run as root, which means that the agent side can't read files created by root in the container. If we could depend on the host offering passwordless sudo, we could make those agent-side things elevate. That's true in hosted but not necessarily true on private agents, so instead, we solved it by injecting a user whose files we know we can read later. It's a decision we'd like to revisit but haven't gotten to.

@richlander to help avoid situations like this thread :grin:, we're going to offer "batteries-included" CI-ready containers for a few ecosystems: .NET, Node, and Go at first. We have the [Node and .NET ones prepped](https://github.com/Microsoft/azure-pipelines-image-generation/tree/master/containers), but we haven't done any blogging or updating templates or anything to officially launch them.

**Comment by richlander** [comment]
Just looked at that @vtbassmatt ... I'm missing see the batteries that included in the .NET Core one. Can you point me to it? Also, how do you plan to manage both servicing and newer versions (like 2.2 and 3.0)?

https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/containers/dotnetcore/2.1/stretch/amd64/Dockerfile

**Comment by vtbassmatt** [comment]
Good question @richlander - I think I'll stop saying "batteries included" when it's really more of a "known good base to build on". If all you need is .NET Core, use the image directly; if you need more, use it as a base.

We need to come up with our servicing strategy. I think most likely you'll see us do multiple tags, so you can depend on `<image>:2.1`, `<image>:2.2`, etc.

**Comment by AArnott** [comment]
@richlander The ones you provide don't include `sudo`. :)

But as far as using them, I would hope and expect that the way Pipelines does this is they build their image based on yours. Then folks can bring _any_ image based on yours to Pipelines and they download much faster since the base image is already present on the VM.

**Comment by richlander** [comment]
I mis-read the Dockerfiles. I didn't realize what `base\debian` was. I do now. It's really confusing to see FROM lines to images that won't be pushed to DockerHub. 

The suggestion from @AArnott makes sense to me. The current Dockerfiles are not best practice.

I'd still like to hear a plan on servicing for these images.

**Comment by MichaelSimons** [comment]
Closing as we are not going to make this change.  Azure DevOps should reconsider their implementation to better support "bring your own image".

**Comment by bancek** [comment]
I've got a similar error and one solution that works without "bringing your own image" is to mount `/usr/bin/sudo` as a volume:

```yaml
pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: tests
    image: ubuntu:18.04
    options: '-v /usr/bin/sudo:/usr/bin/sudo -v /usr/lib/sudo/libsudo_util.so.0:/usr/lib/sudo/libsudo_util.so.0 -v /usr/lib/sudo/sudoers.so:/usr/lib/sudo/sudoers.so -v /etc/sudoers:/etc/sudoers'

container: tests

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
  displayName: 'Install system dependencies'
```

**Comment by oddhack** [comment]
@AArnott not intending to reopen this, but wondering how you're coping with the limitation today? I just ran into exactly the same problem as a newb to Azure, using a dockerhub debian container which I tried to add some additional packages to. We do this in our internal Gitlab CI setup and there's no issue doing it (from the same docker image). I eventually realized there was no way to install packages in the container (aside perhaps from @bancek's heroic but, perhaps fragile against image changes workaround above) and am stymied for the time being. Thanks!

**Comment by AArnott** [comment]
@oddhack When I need sudo I build my own docker images and use those in AzP. But most of my repos don't need sudo. Even installing the .NET SDK can be done in a non-elevated way on all operating systems.

**Comment by rklec** [comment]
> And beyond installing packages, suppose I just needed to modify a config file in a protected location in the linux file system? sudo echo "something" >> /etc/some.conf is so easy. 

BTW Azure DevOps nbow by default [requires containers to include `sudo`](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#linux-based-containers) and also does that `echo` step during setup automatically (creates a new user and gives it all sudo rights).
But as the `sudo` binary is missing in .NET containers, simple Linux dependencies cannot be installed.
