### ISSUE TITLE
ARM32v7 images are being published with tags that declare an amd64 architecture

### ISSUE THREAD

**Issue by robcresswell** [dotnet/dotnet-docker#805]
The image `microsoft/dotnet:2.0.0-runtime-deps-stretch-arm32v7` declares what appears to be an incorrect architecture. It would be wonderful if you could correct this so that anything that programmatically hits these tags is aware of the architecture. Thanks!

```
$ curl -s https://hub.docker.com/v2/repositories/microsoft/dotnet/tags/2.0.0-runtime-deps-stretch-arm32v7/ | jq .           
{
  "name": "2.0.0-runtime-deps-stretch-arm32v7",
  "full_size": 62953163,
  "images": [
    {
      "size": 62953163,
      "architecture": "amd64",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    }
  ],
  "id": 13998783,
  "repository": 408906,
  "creator": 474760,
  "last_updater": 2099355,
  "last_updated": "2017-11-13T16:11:32.808016Z",
  "image_id": null,
  "v2": true
}
```

**Comment by MichaelSimons** [comment]
@robcresswell - Can you explain how this is impacting you?  We'd like to know before deciding what action to take.  Thanks.

**Comment by robcresswell** [comment]
Sure! Part of what we're doing involves programmatically executing some commands in a docker container, and the environment that runs in depends on the architecture of the container; which we detect from the above metadata. If thats incorrect, errors happen :) In this specific case, it means carrying workarounds just for dotnet, which is the only image we've come across so far with this error / inconsistency.

**Comment by MichaelSimons** [comment]
I removed the following tags as they are not valid.  The 2.0 arm variants were preview only and are EOL.    
`https://hub.docker.com/v2/repositories/microsoft/dotnet/tags/2.0.0-runtime-deps-stretch-arm32v7` `https://hub.docker.com/v2/repositories/microsoft/dotnet/tags/2.0.0-runtime-stretch-arm32v7`

**Comment by MichaelSimons** [comment]
@robcresswell - if you discover any other discrepancies, please let us know.  Thanks for bringing this to our attention.

**Comment by robcresswell** [comment]
Awesome; really appreciate the response! Thanks @MichaelSimmons

**Comment by robcresswell** [comment]
@MichaelSimons There are still tags being published with an incorrect architecture; `microsoft/dotnet:2.0.3-runtime-stretch-arm32v7` is one. Would you prefer a new issue to track this?
