### ISSUE TITLE
New microsoft/dotnet:2.1-sdk-stretch image released 11/13/2018 no longer builds projects with runtime 2.1.401

### ISSUE THREAD

**Issue by cgibbons** [dotnet/dotnet-docker#808]
## Steps to reproduce the issue
1.Create a console app with a global.json setting sdk to 2.1.401
2.Create docker file using microsoft/dotnet:2.1-sdk-stretch (make sure to force pull new image)

## Expected behavior
Image will build

## Actual behavior
A compatible SDK version for global.json version: [2.1.401] from [/app/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

## Additional information (e.g. issue happens only occasionally)
**Output of docker build**
Step 1/11 : FROM microsoft/dotnet:2.1-sdk-stretch AS build-env
2.1-sdk-stretch: Pulling from microsoft/dotnet
bc9ab73e5b14: Already exists
193a6306c92a: Already exists
e5c3f8c317dc: Already exists
a587a86c9dcb: Already exists
e965236cc190: Pull complete
3ceeb2161cb9: Pull complete
2b1b3bb39b9a: Pull complete
Digest: sha256:92a9737728a20cc46e6fbadf917657af9bb6edd9482cfc3cc834f80014c4a8a4
Status: Downloaded newer image for microsoft/dotnet:2.1-sdk-stretch
 ---> 172060ed1902
Step 2/11 : ENV NODE_VERSION 8.12.0
 ---> Running in 7482db5b0678
Removing intermediate container 7482db5b0678
 ---> a3ed3eef8fe7
Step 3/11 : ENV NODE_DOWNLOAD_URL https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz
 ---> Running in f86b43d50d67
Removing intermediate container f86b43d50d67
 ---> 05fb569a5ca8
Step 4/11 : ENV NODE_DOWNLOAD_SHA 3df19b748ee2b6dfe3a03448ebc6186a3a86aeab557018d77a0f7f3314594ef6
 ---> Running in 7e597fdd36cf
Removing intermediate container 7e597fdd36cf
 ---> ae01f3fb8d06
Step 5/11 : RUN curl -SL "$NODE_DOWNLOAD_URL" --output nodejs.tar.gz     && echo "$NODE_DOWNLOAD_SHA nodejs.tar.gz" | sha256sum -c -     && mkdir -p /usr/local/opt/nodejs8
   && tar -xzf "nodejs.tar.gz" -C /usr/local/opt/nodejs8 --strip-components=1     && rm nodejs.tar.gz     && ln -f -s /usr/local/opt/nodejs8/bin/node /usr/local/bin/node
 && ln -f -s /usr/local/opt/nodejs8/bin/node /usr/local/bin/nodejs
 ---> Running in 27063ae0def0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.3M  100 16.3M    0     0  5680k      0  0:00:02  0:00:02 --:--:-- 5681k
nodejs.tar.gz: OK
Removing intermediate container 27063ae0def0
 ---> ee2af4bfc957
Step 6/11 : WORKDIR /app
 ---> Running in 8de58a3ee1cc
Removing intermediate container 8de58a3ee1cc
 ---> 7c5b74a4c632
Step 7/11 : RUN curl -o- -L https://yarnpkg.com/install.sh | bash
 ---> Running in bd22ea9403b0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7041    0  7041    0     0  27430      0 --:--:-- --:--:-- --:--:-- 27503
Installing Yarn!
> Downloading tarball...

[1/2]: https://yarnpkg.com/latest.tar.gz --> /tmp/yarn.tar.gz.2ntQmEHmSc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93  100    93    0     0    417      0 --:--:-- --:--:-- --:--:--   418
100   609    0   609    0     0    883      0 --:--:-- --:--:-- --:--:--  1344
100 1139k  100 1139k    0     0   499k      0  0:00:02  0:00:02 --:--:-- 1479k

[2/2]: https://yarnpkg.com/latest.tar.gz.asc --> /tmp/yarn.tar.gz.2ntQmEHmSc.asc
100    97  100    97    0     0    705      0 --:--:-- --:--:-- --:--:--   705
100   613    0   613    0     0   2079      0 --:--:-- --:--:-- --:--:--  2079
100   832  100   832    0     0   2194      0 --:--:-- --:--:-- --:--:--  2194
> Verifying integrity...
gpg: key 1646B01B86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Nov  7 15:13:31 2018 UTC
gpg:                using RSA key E21930C4D0A4AA4618581F7AE074D16EB6FF4DE3
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
     Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
> GPG signature looks good
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /root/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

> Successfully installed Yarn 1.12.3! Please open another terminal where the `yarn` command will now be available.
Removing intermediate container bd22ea9403b0
 ---> 30e719dbd1f6
Step 8/11 : ENV PATH "$PATH:/root/.yarn/bin"
 ---> Running in fdb83fb7bd4a
Removing intermediate container fdb83fb7bd4a
 ---> 179705ac1718
Step 9/11 : COPY . .
 ---> c2122ba83463
Step 10/11 : RUN dotnet restore MessageCenter.Web/MessageCenter.Web.csproj --no-cache && cd /app/MessageCenter.Web/ClientApp && yarn install --non-interactive
 ---> Running in 41bc01997b9f
A compatible SDK version for global.json version: [2.1.401] from [/app/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The command '/bin/sh -c dotnet restore MessageCenter.Web/MessageCenter.Web.csproj --no-cache && cd /app/MessageCenter.Web/ClientApp && yarn install --non-interactive' returned a non-zero code: 145

## Output of `docker version`

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

## Output of `docker info`

Containers: 37
 Running: 5
 Paused: 0
 Stopped: 32
Images: 350
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.8GiB
Name: linuxkit-00155d409c0b
ID: M3PI:2LBO:NGBR:PVGX:2FO5:CBUX:JYZ2:FN7I:45B2:WX6G:3CYI:52RS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 62
 Goroutines: 78
 System Time: 2018-11-13T17:31:58.7447198Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MichaelSimons** [comment]
@cgibbons, your two settings are in conflict with each other.  Your `global.json` is saying that the project must be built with `2.1.401` while your Dockerfile is saying to use the latest version of `2.1` which is currently `2.1.500`.  If you want to pin your project to `2.1.401` then you should modify your Dockerfile to `2.1.401-sdk-stretch`.  If you want to build with the latest `2.1`  version, you should remove the sdk setting from the `global.json` file.  It looks like the `global.json` doesn't support version ranges - https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

**Comment by cgibbons** [comment]
That's what I was afraid of, when I set all this up months ago, the document I ready said to use 2.1-sdk image for all 2.1 development, I didn't see any mention of the compatibility of sdk versions, I assumed 2.1.x sdk would be compatible with all 2.1.x sdk versions.
