### ISSUE TITLE
microsoft/dotnet:2.1-aspnetcore-runtime-alpine  has something wrong  to display Chinese

### ISSUE THREAD

**Issue by dustdragonpzc** [dotnet/dotnet-docker#816]
## Steps to reproduce the issue
1. in dockerfile  I use  microsoft/dotnet:2.1-aspnetcore-runtime-alpine as a base image
2.  in my application, I got zh-HANS through   this variable System.Globalization.CultureInfo.CurrentUICulture.Name,but the correct is zh-Hans
3. so I can not get my Chinese configuration file to display Chinese .like xxx.zh-Hans.xml

**Comment by MichaelSimons** [comment]
This does not seem like something specific to the `microsoft/dotnet` alpine images but rather the CoreFx alpine behavior.  Moving to CoreFx.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/corefx #33625](https://github.com/dotnet/corefx/issues/33625) via [**ZenHub**](https://www.zenhub.com/)
