### ISSUE TITLE
docer publish: assemblies is missing

### ISSUE THREAD

**Issue by MosheL** [dotnet/dotnet-docker#831]
## Steps to reproduce the issue
1. follow this article: https://blog.devcenter.co/deploy-asp-net-core-2-0-apps-on-heroku-eea8efd918b6
simple web application, based on  https://github.com/MarkPieszak/aspnetcore-Vue-starter
2. get logs from heroku
3. get this error message:

018-11-25T20:33:43.534271+00:00 heroku[web.1]: State changed from crashed to starting
2018-11-25T20:33:49.176427+00:00 heroku[web.1]: Starting process with command `/bin/sh -c ASPNETCORE_URLS\=http://\*:\32109\ dotnet\ dll.dll`
2018-11-25T20:33:50.982490+00:00 heroku[web.1]: State changed from starting to crashed
2018-11-25T20:33:50.922446+00:00 heroku[web.1]: Process exited with status 140
2018-11-25T20:33:50.866764+00:00 app[web.1]: Error:
2018-11-25T20:33:50.866788+00:00 app[web.1]: An assembly specified in the application dependencies manifest (shippi.deps.json) was not found:
2018-11-25T20:33:50.866823+00:00 app[web.1]: package: 'Google.Protobuf', version: '3.5.1'
2018-11-25T20:33:50.866890+00:00 app[web.1]: path: 'lib/netstandard1.0/Google.Protobuf.dll'

When I am looking on the published directory,  the DLL is in, and with the correct version.

## Expected behavior
app will work

## Actual behavior
app was failed

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

## Output of `docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d073f06
ID: MRWV:BZHJ:FFJP:RPYA:VV5S:Q5EM:PTEU:CHQA:XPSA:MGKS:KU5V:MHCY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 46
 System Time: 2018-11-25T20:39:38.089506Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

I was saw the same problem on Debian machine, with a similar project.

**Comment by MosheL** [comment]
update: the real problem is simple but stupid: the files was copied, but to the wrong directory.

the problem is the error message isn't helping to understand wahts going on. I can't  shell into the container  and test things as the container was crashed.

**Comment by MichaelSimons** [comment]
@MosheL - my recommendation in situations like this is to run the container interactively locally.  Since ASP.NET Core images have an `ENTRYPOINT` defined to launch the app you will need to override it.  `docker run -it --rm --entrypoint /bin/bash my_aspnetcore_app_image`  In this case, you should be able to more easily discover the files were not in the expected location.

If you have specific suggestions on the error experience, please log an issue w/ASP.NET Core.

**Comment by MosheL** [comment]
the problem was the docker  container was works locally.

the problem was fixed after I was changed the Dockerfile from


```
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /publish
COPY . .
CMD ls
CMD ASPNETCORE_URLS=http://*:$PORT dotnet shippi.dll
```

Into

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /publish
COPY . ./
CMD ls
CMD ASPNETCORE_URLS=http://*:$PORT dotnet shippi.dll
```

why it was solve the problem? I don't know. it working now.
