### ISSUE TITLE
Broken link to Dokerfile of samples

### ISSUE THREAD

**Issue by KarlisVe** [dotnet/dotnet-docker#846]
## Steps to reproduce the issue
1. Open dotnet-docker samples [Readme.md](https://github.com/dotnet/dotnet-docker/blob/master/samples/README.md)
2. Click on sample in section "Try a pre-built ASP.NET Core Docker Image" 

## Expected behavior
Page is opened: https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile

## Actual behavior
Opens 404 page: https://github.com/dotnet/dotnet-docker/blob/master/samples/Dockerfile

**Comment by MichaelSimons** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/847.
