### ISSUE TITLE
Supported Linux Distros

### ISSUE THREAD

**Issue by brentarias** [dotnet/dotnet-docker#85]
I know what Linux distros are supported by .Net Core because it is stated clearly on the .Net Core web site.  However, I need to know what Linux distros the *.Net Core docker image supports*.  I can't find that information in this repo, on the .Net Core site, or on dockerhub.

I'm new to Docker, so perhaps there is an obvious way to get my answer that I've missed.

Am I supposed to believe that a single .Net Core Docker image supports *all* the Linux distros that are supported by .Net Core itself?  I didn't think Docker worked that way...

**Comment by MichaelSimons** [comment]
@brentarias - Each Docker image contains its own OS.  You can see this by walking the FROM image chain.  For example [microsoft/dotnet:latest](https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview2/debian/Dockerfile) is based on [buildpack-deps:jessie-scm](https://github.com/docker-library/buildpack-deps/blob/master/jessie/scm/Dockerfile) which is based on [buildpack-deps:jessie-curl](https://github.com/docker-library/buildpack-deps/blob/master/jessie/curl/Dockerfile) which is based on debian:jessie

Docker images can be run on any host distro (*).  By that I mean you can take a Docker image that is based on Debian and run it from a Debian, Ubuntu, RedHat, etc machine.  The majority of the official Docker images are based on Debian per [this ](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/from) guideline.  There are some runtime images that are based on Alpine per [this](https://github.com/docker-library/docs/blob/master/.template-helpers/variant-alpine.md) guideline.  If you want/need an image based on a different distro, you can very easily copy/fork an official Dockerfile and tweak it to meet your needs.

(*) There are some exceptions to this.  For example I believe RedHat based images can only be run on a RedHat host.  Also [Windows Containers](https://msdn.microsoft.com/virtualization/windowscontainers/containers_welcome) can only be run on the Windows OS variants that support Windows Containers.

**Comment by MichaelSimons** [comment]
@brentarias - Did my last response answer your question?  If so, please feel free to close this issue.  If not, let us know what part isn't clear.

**Comment by MichaelSimons** [comment]
@brentarias - Closing issue, feel free to re-open if there are additional questions.
