### ISSUE TITLE
2.2-sdk/latest container image fails to run

### ISSUE THREAD

**Issue by jishf** [dotnet/dotnet-docker#853]
## Steps to reproduce the issue
1. Pull image from docker hub - `docker pull microsoft/dotnet:latest` or `docker pull microsoft/dotnet:2.2-sdk`
2. Attempt to run the image - `docker run -ti microsoft/dotnet:latest`
3. View command output.

## Expected behavior
The container runs, steps above should spawn a shell within the container.

## Actual behavior
The `docker run` command fails, and the following error is given:
```
[user@machine ~]$ docker run -ti microsoft/dotnet:2.2-sdk
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
```

Running the `docker inspect` command on the image also gives an error:
```
[user@machine ~]$ docker inspect microsoft/dotnet:latest
[]
Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument
``` 
## Additional information (e.g. issue happens only occasionally)
I removed the image a few times and re-downloaded with no success.

I have also cloned the repo myself, and successfully built and run the 2.2-sdk image that is created. 

I haven't tried any of the other images; e.g. 2.2-aspnetcore-runtime/2.2-runtime/2.2-runtime-deps

## Output of `docker version`

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:47 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

## Output of `docker info`

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 56
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.18.17-200.fc28.x86_64
Operating System: Fedora 28 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 251.8GiB
Name: the-mothership
ID: RAVJ:6ERF:ZKSI:BIEC:Q3R5:ZERP:W7FN:Y5ZD:CSGY:U3OY:VRRP:PVCD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Comment by MichaelSimons** [comment]
@jishf - I'm not able to reproduce this in my Docker environments.  Is this a Docker environment you've used other multi-arch tags in before?  I'm curious if you've tried other images such as python:latest or golang:latest.  I would also suggest trying the dotnet:2.2-runtime tag in your environment.

**Comment by jishf** [comment]
> @jishf - I'm not able to reproduce this in my Docker environments. Is this a Docker environment you've used other multi-arch tags in before? I'm curious if you've tried other images such as python:latest or golang:latest. I would also suggest trying the dotnet:2.2-runtime tag in your environment.

Hi Michael, apologies for the delay, I've been able to run other container images with the latest tag. I've also been able to run the 2.1 image with no issues either. 

I'm back in the office today with the environment I was using, so I can double check just now.

**Comment by jishf** [comment]
Okay - I've double-checked the 2.2-sdk image on two different systems (my Macbook and a CentOS VM), both with the same docker version (18.09.0), and they were both successful. 

My Fedora workstation was still having an issue, but after a ```docker system prune -a ```, I was able to re-download the 2.2-sdk image, and run it successfully. 

Happy to close this off myself :)
