### ISSUE TITLE
2.2/sdk/nanoserver-1809/amd64/Dockerfile not synchronised with RTM release of .NET Core 2.2

### ISSUE THREAD

**Issue by TheRealEdwardCullen** [dotnet/dotnet-docker#855]
## Steps to reproduce the issue
1. Download dotnet-sdk-2.2.100-win-x64.zip from location in dockerfile
2. Download dotnet-sdk-2.2.100-win-x64.zip from .NET Core 2.2 release announcement
3. Compare file hashes

## Expected behavior
Version of file used by Docker image corresponds to version in official release announcement.

## Actual behavior
Docker image uses version "2.2.100-rtm-009602", official release is to version "2.2.100-rtm-009607".

## Additional information
Until this release, it was possible to use either the dockerfile or the release announcement as reference for SHA values. This also brings variance into what's installed, depending on whether one is using a Docker image or has downloaded the file via the release announcement.

**Comment by MichaelSimons** [comment]
> Docker image uses version "2.2.100-rtm-009602", official release is to version "2.2.100-rtm-009607".

I think this is actually swapped around.  The docker image has the newer bits.

**Comment by MichaelSimons** [comment]
This was corrected with the 2.2.1 release.
