### ISSUE TITLE
Azure Function Iot Edge module error [Centos 7.5]: Access to path 'proc/1/map_files' denied

### ISSUE THREAD

**Issue by rishirana87** [dotnet/dotnet-docker#865]
## Steps to reproduce the issue
1.Follow tutorial at :https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function
2.Added a timer trigger Azure Function to run as module.
Code:
using System.IO;
using Microsoft.Azure.Devices.Client;
using Newtonsoft.Json;
using System;
using System.Text;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Timers;
using Microsoft.Azure.WebJobs.Extensions.EdgeHub;
using Microsoft.Azure.WebJobs.Host;
using System.Collections.Generic;
using System.Threading.Tasks;

public static class Azv2PocAzureFunction
{
[FunctionName("Azv2PocAzureFunction")]
public static async Task Run(TimerInfo myTimer,IAsyncCollector<Message> output, TraceWriter log)
 {
    log.Info($"C# Timer Azure Function executed at : {DateTime.UtcNow}");

    var telemetryDataPoint = new {
   deviceId = "timerFunction",
   deviceTime = DateTime.UtcNow,
   processedBy =  "IotEdgeModule"
    };
    var  outMessageString = JsonConvert.SerializeObject(telemetryDataPoint);
    var outMessage = new Message(Encoding.UTF8.GetBytes(outMessageString));
    await output.AddAsync(outMessage);
 }

3. Dockerfile already has /app defined as working directory so no issues in that regard -
Dockerfile contents:

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/azure-functions/dotnet:2.0-iot-edge

ENV AzureWebJobsScriptRoot=/app

ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=build-env /app/out /app

## Expected behavior
The command _sudo iotedge list_ command should list this module as 'running;

## Actual behavior
The module is in failed state with code 139

## Output of `docker version`
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:22 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false
## Output of `docker info`
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842GiB
Name: azv2pocvm
ID: FMDR:TARD:PK2K:N3PK:PFRD:OUTJ:GCX3:FAG5:7BNK:HJ4T:T2IM:CTOF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
![img](https://user-images.githubusercontent.com/46006044/50243158-7451d600-03f2-11e9-9168-922bd6837cd9.png)
![img1](https://user-images.githubusercontent.com/46006044/50243553-79635500-03f3-11e9-8fb6-a7086b08d9a3.png)

**Comment by MichaelSimons** [comment]
Can you track down the issue further as there are a number of components involved in the repro steps.  Have you tried the blog steps verbatim first?   Feel free to re-open once you've verified all upstream components.

**Comment by rishirana87** [comment]
@MichaelSimons Thanks!...probably need to raise this as an issue in another repo. Would appreciate if you could please delete the issue raised here to prevent confusion.
