### ISSUE TITLE
.NET Core 2.2 alpine images have 'unknown' rid

### ISSUE THREAD

**Issue by tmds** [dotnet/dotnet-docker#872]
.NET Core 2.2 alpine images use alpine 3.8. This rid isn't in the .NET Core 2.2 rid graph.
This causes .NET Core to fall back to the `linux-x64` rid.
This may cause issues in particular because `linux-x64` implies glibc, and alpine uses musl.

**Comment by MichaelSimons** [comment]
This is an issue with the **RID graph** in CoreFx.  Moving issue.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/corefx #34316](https://github.com/dotnet/corefx/issues/34316) via [**ZenHub**](https://www.zenhub.com/)
