### ISSUE TITLE
Installing dotnet 2.1 core runtime in other Alpine images

### ISSUE THREAD

**Issue by priyaananthasankar** [dotnet/dotnet-docker#892]
## Steps to reproduce the issue
1. Have a Python 3.6 alpine base image
2. Want to install Dotnet 2.1 core runtime in it using apk command or any other way

## Expected behavior
Run dotnet commands

## Actual behavior
Cannot find any documentation or reference that shows such an example. 

## Additional information (e.g. issue happens only occasionally)
Dotnet core 2.1 runtime installations depends on debian packages. If I want to install dotnet core 2.1 runtime in a python alpine base image, it seems like not possible today?

Motivations:

- Installing python on a dotnet alpine is possible and works, but the reverse would render me a smaller image. Python installations on existing docker base files that are non python, always tend to occupy space. 

- People prefer a python base image for data science related work but when they want to run any dotnet based functions or DLL's this becomes a roadblock. 

Any suggestions appreciated to install dotnet core 2.1 in python alpine base image. (NOT looking to get a dotnet core 2.1 base image alpine and installing python on it - this exists)

**Comment by MichaelSimons** [comment]
.NET Core does not currently support installation via apk packages.  If you want to install .NET Core on alpine, please reference how it is done in the [Dockerfiles](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/alpine3.7/amd64/Dockerfile) for .NET Core Alpine images.

**Comment by MichaelSimons** [comment]
cc @dleeapho, @leecow - I'm going to move this issue to core-setup as an ask for apk support.

**Comment by MichaelSimons** [comment]
@priyaananthasankar - I'm going to close this issue as I copied the ask for apk support to core-setup.  Feel free to continue any conversations specific to Docker here.

**Comment by priyaananthasankar** [comment]
@MichaelSimons : so in the example you linked, I see this:
FROM $REPO:2.1-runtime-deps-alpine3.7 
Can I use a python alpine image as a base? I want to start with a python alpine image and install the dotnet core runtime in there. What method do you suggest?

**Comment by kriscoleman** [comment]
All of these links are broken, how is this done?

**Comment by mthalman** [comment]
> All of these links are broken, how is this done?

Since this issue was originally asking about 2.1, you can find the current 2.1 runtime-deps Dockerfile for Alpine here: https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/alpine3.10/amd64/Dockerfile.  

I've also just published instructions for how to install .NET Core for scenarios exactly like this: https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/installing-dotnet.md.

**Comment by mario-contestabile** [comment]
> .NET Core does not currently support installation via apk packages. If you want to install .NET Core on alpine, please reference how it is done in the [Dockerfiles](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/alpine3.7/amd64/Dockerfile) for .NET Core Alpine images.

Can you verify that ^ link it is 404

**Comment by mthalman** [comment]
> > .NET Core does not currently support installation via apk packages. If you want to install .NET Core on alpine, please reference how it is done in the [Dockerfiles](https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime/alpine3.7/amd64/Dockerfile) for .NET Core Alpine images.
> 
> Can you verify that ^ link it is 404

That Dockerfile is no longer published so it had been removed.  Please see these [instructions](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/installing-dotnet.md) on how to install .NET Core in a Dockerfile.
