### ISSUE TITLE
Windows 10 build Edge module for arm32v7 gives error "exec format error"

### ISSUE THREAD

**Issue by joncooke** [dotnet/dotnet-docker#897]
From all accounts building for arm32v7 on Windows 10 worked previously, however for me it's not working.
I don't know if a recent change has caused the error or if I'm doing something wrong somewhere.

I've looked at various other similar issues (e.g. [#650](https://github.com/dotnet/dotnet-docker/issues/650)) and others but they're all either issues with building on Linux or bugs that were fixed.

## Steps to reproduce the issue
1. Using VS Code in Windows 10 create IoT Edge solution & C# edge module
2. Change platform to arm32v7
3. Right click on deployment.template.json and select "Build IoT Edge Solution"

## Environment
OS: Windows 10 Pro 1803
.NET Core SDK version: 2.1.503

## Expected behavior
Solution should be built.

## Actual behavior
Build fails with error:

> Step 1/12 : FROM microsoft/dotnet:2.1-sdk AS build-env
>  ---> 2986052fe712
> Step 2/12 : WORKDIR /app
>  ---> Using cache
>  ---> e9035a612494
> Step 3/12 : COPY *.csproj ./
>  ---> Using cache
>  ---> 5e6ffcda4e12
> Step 4/12 : RUN dotnet restore
>  ---> Using cache
>  ---> 59fb557f3a65
> Step 5/12 : COPY . ./
>  ---> Using cache
>  ---> 3c53024d12d3
> Step 6/12 : RUN dotnet publish -c Release -o out
>  ---> Using cache
>  ---> 3acad60ce8bf
> Step 7/12 : FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
>  ---> ff658372e54a
> Step 8/12 : WORKDIR /app
>  ---> Using cache
>  ---> e5e87856cae6
> Step 9/12 : COPY --from=build-env /app/out ./
>  ---> Using cache
>  ---> 5b10e7421010
> Step 10/12 : RUN useradd -ms /bin/bash moduleuser
>  ---> Running in 53615064ab23
> standard_init_linux.go:207: exec user process caused "exec format error"
> The command '/bin/sh -c useradd -ms /bin/bash moduleuser' returned a non-zero code: 1

## Additional information (e.g. issue happens only occasionally)
The code itself builds and runs fine when built for amd64.

## Dockerfile
Dockerfile.arm32v7:
```
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "WCD_ToHub_cs.dll"]
```

## Output of `docker version`

```
Docker version 18.03.0-ce, build 0520e24302
```

## Output of `docker info`

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 187
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.92-boot2docker
Operating System: Boot2Docker 18.09.1 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.4MiB
Name: default
ID: A4LZ:MV45:CFFI:IJRR:6UUB:HR6A:ACQZ:325L:VH76:ZXJK:RZNT:5FEI
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: 192.168.99.100
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by joncooke** [comment]
My current theory is that it's related to the type of Docker installed.

Since we use non-HyperV VMs a lot I installed Docker Toolbox and the build result is the above bug.
However I grabbed another PC and installed Docker for Windows, the result was I could build the sample C# module against arm32v7.

There is some difference in the version between Docker Toolbox and Docker for Windows but nothing too large:
DT: 18.03.0-ce
DfW: 18.09.1

**Comment by MichaelSimons** [comment]
@joncooke - I am not surprised at all that running arm images on a amd64 Docker Toolbox environment isn't working.  As Docker states [here](https://docs.docker.com/toolbox/overview/)

> Legacy desktop solution. Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.

This issue does not appear specific to the .NET Core images.  I suspect you will see the same thing with the following Dockerfile.

```
FROM arm32v7/debian:stretch-slim

RUN useradd -ms /bin/bash moduleuser
USER moduleuser
```

**Comment by joncooke** [comment]
Is it possible that the documentation can be updated somehow to show the dependencies for different build targets and the limitations of any alternatives?
If nothing else at least it'll save anyone else scratching their head wondering why things aren't working.

**Comment by MichaelSimons** [comment]
The scenario of invoking `useradd` is not a limitation coming from the microsoft/dotnet images.  This is a limitation of Docker Toolbox.  Given this, we feel it is not appropriate to document in the microsoft/dotnet repo.
