### ISSUE TITLE
WinAPI error when deploying a simple app

### ISSUE THREAD

**Issue by sauryadas** [dotnet/dotnet-docker#90]
using the following sample and getting a Win API error

1.git clone  https://github.com/shraddhaagrawal/scratch
2.cd scratch/acs/HelloWorldApp
5. docker build -t mydemosnew:aspnetcorehelloworldnew .
6. docker run -d -p 80:5000 mydemosnew:aspnetcorehelloworldnew

![image](https://cloud.githubusercontent.com/assets/15387759/17344826/65942f2e-58b8-11e6-877e-cd8ae75a3757.png)

@shraddhaagrawal

**Comment by MichaelSimons** [comment]
@sauryadas, what OS are you using in your Docker host environment?

**Comment by sauryadas** [comment]
@MichaelSimons operatingsystem=Windows Server 2016 Datacenter Technic                                                                             al Preview 5

**Comment by MichaelSimons** [comment]
@sauryadas, FYI - The Dockerfile from the repro doesn't look like it matches the output you included.  The Dockerfile indicates FROM microsoft/dotnet:latest.  The output indicates FROM microsoft/dotnet:windowsservercore.

Assuming the windowsservercore image is being used, have you tried running a standalone windowsservercore container?  `docker run -it --rm windowsservercore cmd`  I am seeing some issues recently with this.  I suspect you are encountering the same issue.

**Comment by sauryadas** [comment]
@MichaelSimons i updated the Dockerfile to use the windowsservercore version.

and yes i get the same error while i try to run a standalone container

![image](https://cloud.githubusercontent.com/assets/15387759/17349182/a43d53aa-58d0-11e6-94af-286f0e1309ea.png)

**Comment by MichaelSimons** [comment]
@sauryadas, sorry I don't have a suggestion that works on Windows Server 2016 TP5.  @PatrickLang, do you have any suggestions on how to workaround this problem?

**Comment by MichaelSimons** [comment]
Linking to https://github.com/docker/docker/issues/25336

**Comment by MichaelSimons** [comment]
@sauryadas, all of the microsoft/dotnet windowsservercore and nanoserver images have been rebuilt against the 10.0.14300.1000 base OS images.  You will need to update docker according to docker/docker#25336 in order to make use of these images.  Please let me know if you encounter any issues.

Closing issue.
