### ISSUE TITLE
Alpine runtime missing dependency in a multi-project application

### ISSUE THREAD

**Issue by smubarak-ali** [dotnet/dotnet-docker#902]
## Explanation

I have created a multi-project web-api application and using the docker multi-stage builds to deploy it.
But I am getting the error " An assembly specified in the application dependencies manifest (API.deps.json) was not found:"

Adding the following didn't help
`
<PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>
`

My docker file is as follows:
![image](https://user-images.githubusercontent.com/11365385/51437727-26740a80-1cdd-11e9-82a9-c13137646b39.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/11365385/51437690-8cac5d80-1cdc-11e9-8328-11a5779d9b73.png)

## Additional information (e.g. issue happens only occasionally)
I have tested this exact docker file in a new web-api application without multi-projects and without dapper and it is working correctly. But when I add the dapper dependency it starts throwing the same error as above.

I have tested with the self-contained way but still the same error persist.

## Output of `docker version`

![image](https://user-images.githubusercontent.com/11365385/51437747-7f43a300-1cdd-11e9-9317-6e39babb1349.png)

## Output of `docker info`

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.79-boot2docker
Operating System: Boot2Docker 18.09.0 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.4MiB
Name: default
ID: VAT6:AMZH:SVFJ:7HVL:AZH3:Y7D3:FPMY:5FAS:2GOM:XAFG:D7UV:KTED
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by smubarak-ali** [comment]
Hi @MichaelSimons 
Thanks for the help. I have added a `.dockerignore` file but the same problem persist.
I even tried to use the self-container approach but to no avail.

![image](https://user-images.githubusercontent.com/11365385/51782954-afbb8f00-216c-11e9-8d58-43fea857510b.png)

Currently, I am unable to run the app in runtime image. I am running in the sdk image and it's working fine. To point out one thing, I am using docker tools in windows 8.1

**Comment by MichaelSimons** [comment]
@smubarak-ali - Do you have a project that reproduces the problem that you can share with me?  When you say that you are running in the sdk image, is that the alpine sdk image?

**Comment by smubarak-ali** [comment]
@MichaelSimons 
I have scaffold a web API project and add the docker file. I have added a dependency and now it's not working in a runtime image.

[https://github.com/smubarak-ali/DockerTest](https://github.com/smubarak-ali/DockerTest)

Yes, I am currently using Alpine SDK image for building and hosting and it's working fine. The ideal thing would to deployed the published files in a runtime image and host that image

**Comment by MichaelSimons** [comment]
@smubarak-ali - You cannot simply copy the output of the `dotnet build` and run it in a runtime container.  You will need to execute `dotnet publish` and copy its output.  The `dotnet build` output does not contain all of the dependencies.

Try this instead:

```
FROM microsoft/dotnet:2.2-sdk-alpine as build
COPY . ./docker-test/
WORKDIR /docker-test/API/
RUN dotnet publish -c Release -o ../deploy

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine as runtime
COPY --from=build /docker-test/deploy /app
WORKDIR /app
EXPOSE 5000:5000
ENTRYPOINT [ "dotnet", "API.dll" ]
```

**Comment by smubarak-ali** [comment]
@MichaelSimons thank you for your support. I can't believe I made such a stupid mistake and wasted so much time. I should have focused more on the Dockerfile...
