### ISSUE TITLE
Using SQLite crashes alpine asp.net core 2.2 (but not 2.1) runtime image with Segmentation Fault (aka silently)

### ISSUE THREAD

**Issue by smuellener** [dotnet/dotnet-docker#907]
## Steps to reproduce the issue
1. clone repro repo https://github.com/smuellener/SqliteSegmentationFaultAlpineDetCoreApp2_2.git
2. dotnet publish -c Release -v n -o ./obj/Docker/publish SqliteTestApp.csproj
3. docker build -t sqlitetestapp .
4. docker run -it sqlitetestapp /bin/sh
5. dotnet SqliteTestApp.dll

## Expected behavior
Application runs without Segmentation Fault crash

## Actual behavior
Segmentation Fault crash

## Additional information

- A standard example project from microsoft is used for reproduction: https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite
- Built using Current SDK version (2.2.103)
- Does not Segmentation Fault crash when microsoft/dotnet:2.1-aspnetcore-runtime-alpine is used

## Output of `docker version`

Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by MichaelSimons** [comment]
@smuellener - Can you move this issue to https://github.com/aspnet/EntityFrameworkCore/issues?  This feels like an issue to SQLite and alpine, a musl based distro.
