### ISSUE TITLE
Nanoserver with Windows Authentication

### ISSUE THREAD

**Issue by biiiipy** [dotnet/dotnet-docker#911]
Nanoserver, since being retargeted for containers and shrunken in size, no longer supports Windows authentication - https://github.com/aspnet/aspnet-docker/issues/398
So for the systems that use Windows authentication and want to use containers, Nanoserver isn't an option. The recommendation is to use ServerCore image, but it's ~4GB in size vs ~300MB for the Nanoserver, and that is a huge difference. I understand that the goal of nanoserver is to cut down the image as much as possible, but in the process a fundamental feature has been cut. 
**Nanoserver + Windows Authentication is the perfect container host** for Active Directory managed domains. Please provide a middle ground solution for this, for example:
1) Release a new image based on Nanoserver, but with Windows Authentication support(_Microserver_ 😉)
2) Provide a guide/package how to build that kind of image ourselves, if you do not want to fully support it. (Either by adding to Nanoserver image or severely cutting down ServerCore image)

**Comment by mthalman** [comment]
[Triage]
This is not something we can solve within .NET since it requires an implementation from the base Windows image. Feel free to file an issue at https://github.com/Microsoft/Windows-Containers/issues to request this functionality.
