### ISSUE TITLE
Add Alpine 3.9 images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#921]
Alpine 3.9 has been released and the microsoft/dotnet alpine images should be updated to based on it.

The following is the proposal.
1. 3.0 will only have 3.9 images of Alpine.
2. Add 3.9 Alpine images for 2.1 and 2.2.  The floating `alpine` tag will be updated to reference 3.9.  Keep the older alpine images for a period (3 months) before being deprecated.

Related issues:
https://github.com/dotnet/corefx/issues/33870
https://github.com/dotnet/corefx/pull/34789

**Comment by rickardp** [comment]
The Alpine 3.9 OpenSSL issue appears to be fixed in the 2.2.105 SDK build. I am successfully using Alpine 3.9 for my builds now.

**Comment by MichaelSimons** [comment]
Alpine images are now available.  The `alpine` floating tag has not been updated to reference 3.9 images yet because we wanted to investigate an issue we found - #974
