### ISSUE TITLE
Enhance the usability of the image size validation tests

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#936]
It would be valuable to run the image size validation as part of CI - https://github.com/dotnet/dotnet-docker/tree/nightly/tests/performance.  This will help detect regression upfront as the Dockerfiles are updated.  

In order for this to be really valuable #373 and #792 should be fixed.

**Comment by mthalman** [comment]
@MichaelSimons - I'm assuming this would be something we would only want warnings for and that it shouldn't fail the build?  If so, then how useful is this versus the standalone size validation pipeline?

**Comment by MichaelSimons** [comment]
Renamed the issue to address the broader usability of the image size validation tests.  In discussing with @mthalman here are the key points to address.

- [ ] 1. CI should catch missing/additional baseline data.  This be useful for scenarios in which new images are added or images are being removed.  In these scenarios, the baselines should get updated in step with adding/removing the images.
- [ ] 1. Image Builder should have support for updating the baseline file.  This should support an option to only update baseline entries that exceed the threshold.  It would be convenient if there was a script checked into the repo to trigger a baseline update.
- [ ] 1. (Optional) Support a mode where only the size of the .NET owned layers are checked.  Changes to the .NET layers would be something we would want a differentiated alert on and treat more critically.

It is important to note that we do not want CI to fail when an existing image exceeds the size threshold.  This can be triggered simply by changes to base images which are beyond our control.  This type of CI failure could get in the way at critical release times and become a maintenance burden.
