### ISSUE TITLE
[Question] seeing image tags and image sizes in mcr.microsoft.com

### ISSUE THREAD

**Issue by jonathann92** [dotnet/dotnet-docker#967]
Since changing the docker images to be hosted on mcr, how would I view all the previous tags like 2.1.7 and 2.2.0? In docker hub I used to be able to see a "tags" columns and it would have all the previous tags and the size of the docker file.

**Comment by MichaelSimons** [comment]
@jonathann92 - you can find the full tags listings here
[sdk tags](https://mcr.microsoft.com/v2/dotnet/core/sdk/tags/list)
[aspnet tags](https://mcr.microsoft.com/v2/dotnet/core/aspnet/tags/list)
[runtime tags](https://mcr.microsoft.com/v2/dotnet/core/runtime/tags/list)
[runtime-deps tags](https://mcr.microsoft.com/v2/dotnet/core/runtime-deps/tags/list)

I am not aware of any listing that provides a summary of the image sizes. @rotata, can you verify?

**Comment by MichaelSimons** [comment]
A link to the full tags listing will be handled with #990.  There are no plans to surface the image size info at this time.
