### ISSUE TITLE
Lack of 3.0.100-preview3 images on dockerhub

### ISSUE THREAD

**Issue by garfieldos** [dotnet/dotnet-docker#978]
## Steps to reproduce the issue
1. docker pull microsoft/dotnet:3.0.100-preview3-apline-sdk

## Expected behavior
Pulling image

## Actual behavior
Error response from daemon: manifest for microsoft/dotnet:3.0.100-preview3-apline-sdk not found

## Additional information (e.g. issue happens only occasionally)
On docker hub page about dotnetcore there is information about 3.0.100-preview3 tag (https://hub.docker.com/_/microsoft-dotnet-core-sdk/), but this image is not available on the registry. List downloaded from https://registry.hub.docker.com/v1/repositories/microsoft/dotnet/tags doesn't contain this docker image.

## Output of `docker version`
Docker version 18.09.0, build 4d60db4

**Comment by MichaelSimons** [comment]
@garfieldos - 3.0 preview 3 images are only available on mcr.  Please refer to the [3.0 preview 3 announcement](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/) and [mcr announcement](https://github.com/dotnet/dotnet-docker/issues/935) for more details.

`docker pull mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview3-alpine`

**Comment by richlander** [comment]
See [.NET Core Container Images now Published to Microsoft Container Registry](https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/) for the most updated information on our use of MCR.
