### ISSUE TITLE
Was support for windows version 10.0.14393 removed recently?

### ISSUE THREAD

**Issue by twhittakeriq** [dotnet/dotnet-docker#987]
I have a system set up to build docker images nightly based on dotnet 2.1 for windows version 14393... this build started failing yesterday at about noon, and now I can no longer locate Docker images for .net core 2.1 for the Windows Server 2016 build 14393... did something change recently?

**Comment by guillaumerose** [comment]
The Docker Desktop CI seems to have caught this error also. Nodes running Windows 10 15063 can't pull `microsoft/dotnet:2.1-sdk` anymore.

**Comment by StefanScherer** [comment]
Seems like the manifest list does not contain all Windows versions.

{code}
$ mq microsoft/dotnet
Unable to find image 'mplatform/mquery:latest' locally
latest: Pulling from mplatform/mquery
db6020507de3: Pull complete 
f11a2bcbeb86: Pull complete 
Digest: sha256:e15189e3d6fbcee8a6ad2ef04c1ec80420ab0fdcf0d70408c0e914af80dfb107
Status: Downloaded newer image for mplatform/mquery:latest
Image: microsoft/dotnet
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - windows/amd64:10.0.16299.1029
   - windows/amd64:10.0.17134.648
   - windows/amd64:10.0.17763.379
   - windows/arm
{code}


{code}
$ mq microsoft/dotnet:2.1-sdk
Image: microsoft/dotnet:2.1-sdk
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - windows/amd64:10.0.16299.1029
   - windows/amd64:10.0.17134.648
   - windows/amd64:10.0.17763.379
{code}

So no 14393 in there.

BTW: mq is an alias for docker run --rm mplatform/mquery a nice tool from Phil Estes

**Comment by MichaelSimons** [comment]
Nano Server sac2016 reached the end of the support lifecycle (eol) a few months ago.  We stopped patching/producing the image this month as a result of this.  Because it is eol, it was removed from the multi-platform tags.  The qualified tags still exist if you have a need to continue using Nano Server sac2016 images.

- `2.2.2-nanoserver-sac2016`, `2.2-nanoserver-sac2016`
- `2.1.8-nanoserver-sac2016`, `2.1-nanoserver-sac2016`
- `1.1.11-nanoserver-sac2016`, `1.1-nanoserver-sac2016`
- `1.0.14-nanoserver-sac2016`, `1.0-nanoserver-sac2016`

**Comment by twhittakeriq** [comment]
OK, I was able to locate the base images I needed with the more specific tags noted above.  I am trying to produce an updated build of software that is still using these images as their base (because they're being deployed to a Windows Server 2016 machine on build 14393).  We are working to migrate away from this requirement, but have not been able to do so yet.

Thank you for the quick response on this!

**Comment by MichaelSimons** [comment]
See our [.NET Core Container Images now Published to Microsoft Container Registry](https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/) blog post which also discusses the Nano Server 2016 images.
