### ISSUE TITLE
Add manifest to better support Windows and Linux based platforms

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#99]
With the current state of Docker and Windows Containers, a Windows based image cannot be run on Docker for Linux/Mac/Windows.  They can only be run from a Windows Containers environment.  Likewise a Linux based image cannot be run from a Windows Containers environment. The error experience when a user tries to pull/run an image in an unsupported environment is less than ideal.  A [manifest](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md) should be created which will help solve this problem.  A manifest will provide two benefits.  First, it will prevent an image from being pulled in an unsupported environment.  When a pull attempt is made from an unsupported environment, the error experience is meaningful and obvious as to why the operation cannot be performed.  Second, a manifest will allow a single tag (e.g. sdk, core, onbuild) to be pulled from multiple platforms.  When the tag is pulled, docker will inspect the manifest to figure out which image should be used for the current platform.

This [blog post](https://blog.docker.com/2016/04/docker-windows-server-tp5/) explains manifests and how they are useful.

This work is currently blocked on having docker tooling support for manifests.  For instance the microsoft/dotnet images are built with the Docker auto-build infrastructure within Docker Hub but it is not capable of producing a manifest.

**Comment by darrenstahlmsft** [comment]
FYI, when attempting to pull a Linux container image on a Windows Container host, the error message is much better:
```
>docker run microsoft/dotnet
Unable to find image 'microsoft/dotnet:latest' locally
latest: Pulling from microsoft/dotnet
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.
``

I don't think the same can be said about pulling a Windows image on a Linux host though, but don't have one handy to test.
